### ISSUE TITLE
Pasting in markdown cells pastes twice (regression in 4.0)

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#13206] opened 2022-10-10 10:00 UTC
## Description

Pasting in markdown cells pastes twice

## Reproduce

1. Open JupyterLab 4.0 alpha
2. Create markdown cell
3. Paste some text (using a shortcut or shift + right click context menu)
4. See it occur twice

![pastes-twice-in-markdown](https://user-images.githubusercontent.com/5832902/194840517-eb61c561-4e9a-4d64-a7b0-c8d6a22d89fa.gif)
![pastes-twice-bis](https://user-images.githubusercontent.com/5832902/194840513-28afc55d-64f0-450a-9ede-72bb2fa91764.gif)

## Expected behavior

Pastes once.

## Context

- Operating System and version: Linux Ubuntu
- Browser and version: Chrome and Firefox
- JupyterLab version: 4.0.0a29

**Comment by yczhangsjtu** [comment] 2023-01-12 07:59
This issue seems to appear again in 4.0.0-alpha.32. The function `replaceSelection` has been completely changed.

**Comment by fcollonval** [comment] 2023-01-18 16:13
I can confirm 4.0 has it. This is because `handlePaste` handling is not yet restored following CodeMirror 6 migration.

It will be fixed by https://github.com/jupyterlab/jupyterlab/pull/13639 that restore the `handlePaste` feature.

**Closed** 2023-02-27 11:12 UTC
Labels: bug, tag:Regression
