### ISSUE TITLE
Make Contextual Help Faster (do not scan large data)

### ISSUE THREAD

**Issue by oldrichsmejkal** [jupyterlab/jupyterlab#12954] opened 2022-08-17 08:28 UTC
### Problem

* When "Contextual help" tab is open and large pd.DataFrame (e.g. few GBs) is loaded in memory of current tab (kernel), whole JupyterLab lags (seconds to tens of seconds) when cursor is at that large pd.DataFrame
* "Contextual help" is doing something like display(df), which needs to scan that dataframe every time cursor is there, showing 
* (showing "String form:" displaying str(dataframe) before pd.DaFrame help)

### Proposed Solution
* Turn off this behaviour or better make it configurable (e.g. option: "Do not display data in Contextual help (makes UI faster)": True/False)

### Additional context
* Because lag is really long and occurs often, it makes "Contextual Help" basically unusable when working with bigger data 
* This feature should therefore help many users (there is a lot of forum questions about "very slow Jupyterlab UI", I believe a lot of them can be actually because of this issue)

**Comment by krassowski** [comment] 2022-08-17 14:56
Also, there was a PR linked in that issue which https://github.com/jupyterlab/jupyterlab/pull/11447 which alleviates this problem. You have not listed your JupyterLab version. If it is older than 3.3, you might benefit from upgrading.

**Comment by oldrichsmejkal** [comment] 2022-08-17 15:16
> Also, there was a PR linked in that issue which #11447 which alleviates this problem. You have not listed your JupyterLab version. If it is older than 3.3, you might benefit from upgrading.

Thanks for info.
My version is 3.4.2
Maybe it is really better than previously (less frequent updates).

But I still believe it could be really helpful to have an option to turn data scannig off and leave just normal docs in "Contextual Help".
(Those lags still makes it more productive in many use cases to close contextual help and use just google or execute ? command when help is needed..)

**Comment by jweill-aws** [comment] 2022-08-18 17:18
Closing as duplicate of #11458 per @krassowski .

**Closed by jweill-aws** 2022-08-18 17:18 UTC
Labels: status:Duplicate, enhancement, status:Needs Triage
