### ISSUE TITLE
How to figure out current jupyterlab theme in script imported by notebook

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/jupyterlab#3855] opened 2018-02-11 04:27 UTC
I really like `jupyterlab`'s dark theme, and have been using it a lot lately. One problem though is that it makes the tick and axis labels on plots unreadable, as they end up being black text on a very dark background. I've been fixing this by manually adding a line to my notebook preambles:

    plt.style.use('dark_background')

but I was wondering if there might be an automated way of setting the plot style based on the current theme.

Normally my notebook preamble is a single line that just imports and runs a setup script:

    from setupJupyter import setupJupyter; setupJupyter()

The script runs a bunch of `ipython` magics (i.e. `%pylab inline`, `%load_ext autoreload`) and sets up the plotting environment (via a bunch of matplotlib style sheet stuff). Is there any way for my setupJupyter script to determine the current theme used by `jupyterlab`? Or is the idea of reading `jupyterlab` settings in python code a pipe dream?

I was thinking there might be a relevant attribute somewhere in the InteractiveShell instance returned by `get_ipython()`, but I didn't see anything obvious.

**Comment by ian-r-rose** [comment] 2018-02-11 19:32
Thanks for bringing this up! There are a couple of places where it would be useful to be able to query some information about the currently active theme (cf. #3458, #3681). There are two basic use-cases as I see it:
1. Responding to the theme in client-side extension code. This would be accomplished by exposing some basic metadata about the currently active theme in the `ThemeManager` APIs.
2. As you describe, responding to it in kernel-side code. That is a trickier use-case: by design the kernels don't know much about the front-end that is displaying the results of computation. I don't really see a good solution to that at the moment, but perhaps somebody else does. For matplotlib, maybe we could make the `%notebook` extension theme-aware?

**Comment by ellisonbg** [comment] 2018-02-20 23:49
As an aside, it would be nice if folks wanted to help improve the dark theme for matplotlib to work better.

**Comment by InfoSecC** [comment] 2018-03-18 21:14
Personally, I have been working around the dark theme issue with Matplotlib axis labels, edges, and ticks not showing up (dark on dark) by adding this to the top of my notebooks, but it would be nice not to have to. 

Linux / MacOS
`with open(r'/Users/username/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/themes.jupyterlab-settings') as json_data:
    theme = json.load(json_data)
    theme = theme['theme']
    print(theme)
    if theme == 'JupyterLab Dark':
        rcParams['axes.edgecolor'] = 'white'
        rcParams['axes.labelcolor'] = 'white'
        rcParams['xtick.color'] = 'white'
        rcParams['ytick.color'] = 'white'
        rcParams['text.color'] = 'white'
`

PC
`with open (r'C:\Users\username\.jupyter\lab\user-settings\@jupyterlab\apputils-extension\themes.jupyterlab-settings') as json_data:
    theme = json.load(json_data)
    theme = theme['theme']
    print(theme)
    if theme == 'JupyterLab Dark':
        rcParams['axes.edgecolor'] = 'white'
        rcParams['axes.labelcolor'] = 'white'
        rcParams['xtick.color'] = 'white'
        rcParams['ytick.color'] = 'white'
        rcParams['text.color'] = 'white'
`

You could also work around this using `plt.style.use('dark_background')` as @telamonian suggested, which looks a bit different, but again it would be nice not to have to use a workaround at all.

Linux / MacOS
`with open(r'/Users/username/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/themes.jupyterlab-settings') as json_data:
    theme = json.load(json_data)
    theme = theme['theme']
    print(theme)
    if theme == 'JupyterLab Dark':
        plt.style.use('dark_background')
`

PC
`with open (r'C:\Users\username\.jupyter\lab\user-settings\@jupyterlab\apputils-extension\themes.jupyterlab-settings') as json_data:
    theme = json.load(json_data)
    theme = theme['theme']
    print(theme)
    if theme == 'JupyterLab Dark':
        plt.style.use('dark_background')`

**Comment by jasongrout** [comment] 2018-03-19 15:48
As a thought experiment: what happens if two people are hooked to the same kernel, one using a dark theme, and one using a light theme, and someone plots a matplotlib plot? Since the plot is generated in the kernel as an image, it presumably has to decide in the kernel whether to be a dark or light theme, or it has to render both. What should matplotlib do?

**Comment by jasongrout** [comment] 2018-03-28 05:26
> As a thought experiment: what happens if two people are hooked to the same kernel, one using a dark theme, and one using a light theme, and someone plots a matplotlib plot? Since the plot is generated in the kernel as an image, it presumably has to decide in the kernel whether to be a dark or light theme, or it has to render both. What should matplotlib do?

(Note that for something like bqplot or vega, where the rendering is actually done in the client, we *can* change the rendering based on the theme)

**Comment by ian-r-rose** [comment] 2018-03-28 05:29
It's possible we could also do that with the `%matplotlib notebook` interface. Embedding of plain PNGs remains thorny, however.

**Comment by jasongrout** [comment] 2018-03-28 05:40
Even the matplotlib notebook interface renders the actual image in the kernel, though.

**Comment by ian-r-rose** [comment] 2018-03-28 05:57
I don't know a lot about the `%notebook` interface, but might it be able to send some metadata about the theme, since it already assumes a notebook frontend? We could then change the background color of the div in response.

**Comment by jasongrout** [comment] 2018-03-28 06:17
> but might it be able to send some metadata about the theme, since it already assumes a notebook frontend? We could then change the background color of the div in response.

Oh, interesting. If I understand you right, matplotlib sends along information about what theme it is rendering for, and then we just change the background of the image to match what it was rendering for, rather than trying to match the system them? As in, if mpl renders for a light theme, then even if we are in a dark theme, we put a light background behind the image?

**Comment by ian-r-rose** [comment] 2018-03-28 06:30
Yeah, something like that. You put it better than I did!

**Comment by GallowayJ** [comment] 2018-07-05 13:08
> As an aside, it would be nice if folks wanted to help improve the dark theme for matplotlib to work better.

I'd like to work on improving the JupyterLab Dark Theme but I'm unsure on where I should start. Should I make changes to [variables.css](https://github.com/jupyterlab/jupyterlab/blob/master/packages/theme-dark-extension/style/variables.css) in the Dark theme? My initial thought is to alter the `class="p-Widget jp-RenderedImage jp-mod-trusted jp-OutputArea-output"` to be a shade grey. P.s. I've asked a question on StackOverflow [here](https://stackoverflow.com/questions/51191993/how-to-edit-a-jupyterlab-theme)

I'm also open trying other approaches if there are suggestions..

**Comment by jasongrout** [comment] 2018-07-05 15:35
FYI, I posted a gist about experimenting with theme colors: https://gist.github.com/jasongrout/753216b2d3320b0abec6143d36f5d640

**Comment by GallowayJ** [comment] 2018-07-05 16:37
@jasongrout Thanks a lot for the gist. In the end it was more straight forward than I'd imaged to customize the theme. I added `.jp-RenderedImage {
  background-color: #A4A4A4
}` to my `variables.css` file to change output cells with plot/images to grey and leave other output cell (i.e. text) as black. I've attached a screenshot to this comment.

![jupyterlabcustomdarktheme](https://user-images.githubusercontent.com/5037175/42335846-011e284e-8082-11e8-9578-51e3a744f7e3.png)

**Comment by alexveden** [comment] 2018-07-30 03:33
What do you think about setting and checking environment variables for dark theme?

```
import os
import matplotlib.pyplot as plt
if os.environ.get('JLDARK'):
    plt.style.use(['dark_background'])
```

**Comment by jasongrout** [comment] 2018-07-30 17:05
Another possibility is to just set the background of the matplotlib image to be whatever you want, instead of transparent. That way it at least shows up no matter what the theme (though it probably looks worse than doing the dark stylesheet, for example).

```python
import matplotlib as mpl
mpl.rcParams['figure.facecolor'] = 'w'
```

<img width="484" alt="screen shot 2018-07-30 at 10 04 30 am" src="https://user-images.githubusercontent.com/192614/43411766-019b9dda-93e0-11e8-9085-18379d571190.png">

**Comment by blink1073** [comment] 2018-09-11 18:45
Fixed by https://github.com/jupyterlab/jupyterlab/pull/5232

**Closed by blink1073** 2018-09-11 18:45 UTC
Labels: pkg:themes, tag:Design and UX
