### ISSUE TITLE
VDOM is not maintained any longer

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#13891] opened 2023-01-30 13:44 UTC
## Description

[vdom](https://github.com/nteract/vdom) is not longer maintained and the CI is breaking when bumping [ipywidgets](https://github.com/jupyterlab/jupyterlab/pull/13820) to v8:

![image](https://user-images.githubusercontent.com/8435071/215491918-7e93a185-4258-4e14-9c89-c66ec9896bf6.png)

## Reproduce

Try the test snippet with ipywidgets v8.

```py
from IPython.display import display
from vdom.helpers import h1, p, img, div, b

display(
    div(
        h1('Our Incredibly Declarative Example'),
        p('Can you believe we wrote this ', b('in Python'), '?'),
        img(src='https://turnoff.us/image/en/death-and-the-programmer.png', style={'height': '268px'}),
        p('What will ', b('you'), ' create next?')
    )
)
```

## Potential solution

I propose to extract VDOM ~~and vega~~ extension from JupyterLab into the [jupyter-renderer](https://github.com/jupyterlab/jupyter-renderers) projects.

> This implies removing the section about those in the documentation: [[1]](https://jupyterlab.readthedocs.io/en/stable/user/file_formats.html#vega-vega-lite) [[2]](https://jupyterlab.readthedocs.io/en/stable/user/file_formats.html#virtual-dom)

**Comment by jasongrout** [comment] 2023-02-01 17:24
It looks like the problem is just that the ipython_genutils dependency is not specified in vega? Perhaps before, ipywidgets 7 depended on that package, so we didn't see that vdom was using it without having it specified as a dependency.

I think it may still make sense to extract the vdom package, but it also does seem like it is a pretty simple fix.

**Comment by jasongrout** [comment] 2023-02-01 17:30
Looking further, yes, +1 from me for moving vdom out of core. If the underlying package is broken and unmaintained, I don't think even moving to renderers is right - it should probably be moved to a separate repo and then archived. If the pypi package is not being maintained, we shouldn't be maintaining the frontend extension.

Normally we would encourage the underlying pypi project to maintain the frontend extension as part of their package so that it is more tightly coupled with the underlying package. That didn't happen here, but if it had, the frontend extension would be unmaintained at this point too.

**Comment by jasongrout** [comment] 2023-02-01 17:31
> and vega extension

From the dev meeting: @fcollonval is creating a separate issue for moving vega out.

**Comment by dlqqq** [comment] 2023-02-01 19:35
I'm OK with owning this, given that I'm already doing [something similar](https://github.com/jupyterlab/jupyterlab/pull/13877). @jasongrout Where would this new repo live?

**Comment by dlqqq** [comment] 2023-02-01 21:54
@jasongrout Just created [the issue](https://github.com/nteract/vdom/issues/109). Is there anybody I should ping for higher visibility and a better chance of getting a repository allocated? I see that @fcollonval is a member of nteract, but I'm unsure whether this gives him unilateral authority to create a new repo underneath nteract.

**Comment by fcollonval** [comment] 2023-02-02 08:30
Xref: issue to discuss vega package case: https://github.com/jupyterlab/team-compass/issues/176

**Comment by fcollonval** [comment] 2023-02-02 08:36
I + :100: with Jason proposal.

@dlqqq thanks for proposing your help. I'm a member because I push a PR on papermill. But otherwise I'm not involved in nteract. And unfortunately that project is dying. You can give a try to their chat on [Discord](https://discord.gg/tQrtRwuxqW)

**Comment by jasongrout** [comment] 2023-02-02 21:12
I'll note that the code can be resurrected for nteract vdom to maintain at any point by pulling it from our git history, so I'd suggest we plan to remove it from JupyterLab core in the next few weeks before the code freeze.

**Closed** 2023-02-10 09:53 UTC
Labels: maintenance

**Comment by rgbkrk** [comment] 2023-03-25 16:04
IIRC the original jupyterlab renderer for vdom was pretty simple and I was used to it just working. I didn't notice issues until I started making sure to test on the most recent versions of IPython.

There was some event work that @gnestor and @rmorshea had worked on, but I think they've moved on and I'd prefer to keep vdom down to the simple spec of tags and attributes. Happy to help with transition, but it was very nice to be able to use vdom in jupyterlab as is.
