### ISSUE TITLE
Anchors Are Not Working for Japanese heading

### ISSUE THREAD

**Issue by ruoyu0088** [jupyterlab/jupyterlab#12402] opened 2022-04-14 01:01 UTC
## Description

Links with Japanese anchor cannot jump to the heading, for example ` [日本語](test.ipynb#日本語)`.

## Reproduce

Create a notebook `test.ipynb` with two heading cell:

```
## 日本語
```

```
## English
```

Create a markdown file with the following links:

```
* [English](test.ipynb#English)
* [日本語](test.ipynb#日本語)
```

Open the Markdown preview page, and click the two links. the "English" link works, but the "日本語" link doesn't work.

## Context

- Operating System and version: Windows 10
- Browser and version: Chrome  100.0.4896.75
- JupyterLab version: 3.3.3

**Comment by jweill-aws** [comment] 2022-04-14 16:33
I can reproduce this in JupyterLab 4. The ¶ links beside each heading generate working anchor links, such as `#日本語`, but using Markdown syntax does not generate working intrapage links for Japanese anchors.

**Comment by jweill-aws** [comment] 2022-04-14 16:34
An anchor link to a header with a mixture of ASCII and Japanese text, like `#Heading-日本語`, also does not work in Markdown syntax.

**Comment by jweill-aws** [comment] 2022-04-14 16:41
The characters `日本語` are rendered in the Markdown cell output as `%E6%97%A5%E6%9C%AC%E8%AA%9E`, the escaped bytes of the UTF-8 representation of these characters.

**Comment by jweill-aws** [comment] 2022-04-14 16:43
From the [URL Standard defined by WhatWG](https://url.spec.whatwg.org/#concept-url-fragment): "A [URL](https://url.spec.whatwg.org/#concept-url)’s fragment is either null or an [ASCII string](https://infra.spec.whatwg.org/#ascii-string) that can be used for further processing on the resource the [URL](https://url.spec.whatwg.org/#concept-url)’s other components identify. It is initially null."

To comply with this standard, we may have to define fragments as ASCII text for all heading links, even if those heading links contain non-ASCII characters.

**Comment by jweill-aws** [comment] 2022-04-14 16:48
This line in `rendermime` generates a header by replacing all spaces with hyphens. This is incomplete. The function needs to:
1. Replace all _non-ASCII characters_ with either nothing or an ASCII character such as a hyphen
2. Generate unique IDs for all headers, even if the logic in (1) above reduces headers to identical ASCII strings.

https://github.com/jupyterlab/jupyterlab/blob/7d23ead2a51c44e261243f916e46dea46ae1b837/packages/rendermime/src/renderers.ts#L835

**Comment by ruoyu0088** [comment] 2022-04-15 02:24
The HTML code of the rendered markdown link is:

```html
<a href="http://127.0.0.1:8888/files/sandbox/test.ipynb?_xsrf=...#%E6%97%A5%E6%9C%AC%E8%AA%9E"
 rel="noopener" 
target="_blank" 
data-commandlinker-command="rendermime:handle-local-link" 
data-commandlinker-args="{&quot;path&quot;:&quot;sandbox/test.ipynb&quot;,&quot;id&quot;:&quot;#%E6%97%A5%E6%9C%AC%E8%AA%9E&quot;}">日本語</a>
```
in the `data-commandlinker-args` field, there are `path` and `id` attributes, if I change the `id` attribute from `#%E6%97%A5%E6%9C%AC%E8%AA%9E` to `#日本語`, the link works.

To confirm this, create a %%html cell in a new notebook, and add following HTML code, and run the cell.

```html
<a href="" 
       rel="noopener" 
       target="_blank" 
       data-commandlinker-command="rendermime:handle-local-link" 
       data-commandlinker-args="{&quot;path&quot;:&quot;sandbox/test.ipynb&quot;,&quot;id&quot;:&quot;#日本語&quot;}">日本語</a>

**Comment by jweill-aws** [comment] 2022-05-26 17:58
Resolving as duplicate of #1932.

**Closed by jweill-aws** 2022-05-26 17:58 UTC
Labels: bug, pkg:rendermime, good first issue
