### ISSUE TITLE
Cannot copy and paste portions of text in a cell

### ISSUE THREAD

**Issue by callegar** [jupyterlab/jupyterlab#12315] opened 2022-03-31 17:34 UTC
## Description

It seems to be impossible or extremely erratic to copy and paste only pieces of text from a cell (be it a code cell or a markdown cell).

It is unclear to me if this is a designed behavior or an actual bug. In either case, it can result inconvenient.

It is also unclear to me if this issue is a duplicate of other ones (e.g.,  #11353) or merely related to it.

Finally, being able to test only in linux (and mainly with firefox) it is unclear to me if this issue is specific to linux or not. For sure, in linux neither the *selection* nor the actual *clipboard* work as one would naturally expect.

For instance, you are able to *select* some text (e.g. from a markdown source cell). The selected text gets properly highlighted on screen. However it does not get to the selection. Once the text is selected, pressing CTRL-C does not copy the selected text in the clipboard either.  By right clicking and looking at the context menu (or by looking at the *Edit* menu) you can get to the *Copy Cells* action. But that does not work either. It does not look like neither the selected text nor the text of the whole cell gets into the clipboard when some text (in opposition to the whole cell) is selected.

This seems a bit confusing.

It would be great if the Edit (or the contextual) menu could be adapted automatically to whatever is selected. If you have a whole cell or a few of them selected, then the action should be *Copy Cells*. However, if you only have some text from a cell selected it would be much better to have a *Copy Cell Text* action.

As a workaround you can copy just portions of text by using SHIFT+RIGHT_CLICK to open the contextual menu of the browser rather than that of the notebook, but is seems a bit unnatural to have to resort to it for something like coping a bit of text.

Is the observed behavior the designed one or is it accidental (a bug?). Could improving the current behavior (even if it is the designed one) be considered (at least as a low priority task)?

**Comment by jweill-aws** [comment] 2022-04-07 17:09
There is an issue out concerning changing the expectation: #3224. Resolving this one as a duplicate of #3224. Thank you for your contribution.

**Closed by jweill-aws** 2022-04-07 17:09 UTC
Labels: bug, status:Needs Triage
