### ISSUE TITLE
Lab hangs when try to open a directory contains too many files

### ISSUE THREAD

**Issue by miracatici** [jupyterlab/jupyterlab#8230] opened 2020-04-19 15:29 UTC
## Description
I'm using JupyterLab with Docker image on a server. I mount my project folder to container as a volume. There is a directory inside and this directory contains ~112k (~112000) PNG files. When I try to open (browse) the directory with JupyterLab, it hangs. It is mostly being unresponsive, so I have to restart container.  There is no turning wheel or bar or etc. It seems like a Small File Problem. However, I thought that directory and file listing should be async task, it should not block my UI. 

## Context

- Operating System and version: Ubuntu 18.04 + Docker Engine 19.03
- Browser and version: Chrome 
- JupyterLab version: 2.0.1
- JupyterLab server version: 1.07

**Comment by blink1073** [comment] 2020-04-23 11:53
Hi @miracatici, this is because our file browser currently renders all of the file items for a directory, rather than only rendering what will be currently visible.  

If anyone has the bandwidth to look at this, the code for rendering the file items is [here](https://github.com/jupyterlab/jupyterlab/blob/master/packages/filebrowser/src/listing.ts#L193).

**Comment by benzzdan** [comment] 2020-09-29 03:14
Hi, in my case I have installed jupyterhub helm chart --version 0.9.1, that installs jupyterlab 2.1.3 on the users notebook servers, we notice a particular issue when a user had over 9k files of sizes between 2.5MB-11MB, as soon as the user opens the notebook server, it starts to hang and makes the page unresponsive, is there a workaround for this? other than just not having too many files on a directory? I have tweaked memory limits and cpu but that does not seems to be the issue.

**Comment by adambielski** [comment] 2021-02-23 21:10
This is quite a big issue for me, too. With ~20k files it hangs for a few good minutes. Is there any workaround? I avoid opening such folders, but sometimes it just happens and I'm stuck with unresponsive jupyterlab.

**Comment by ericspod** [comment] 2021-02-25 23:39
This appears to also occur when creating a directory within the current directory and populating it with a large number of files. For example, while downloading a tarball with a large number of files and extracting it into the directory currently viewed file browser the Jupyterlab session will hang as described. This is without actually navigating into the large directory so precaching directory contents is also a problem.

**Comment by mwakaba2** [comment] 2021-08-02 20:31
This issue seems related to #8700.
@echarles is working on a PR to add pagination on the jupyter server side: https://github.com/jupyter-server/jupyter_server/issues/538

**Comment by fcollonval** [comment] 2022-02-16 09:36
Closing as duplicate of #8700

**Closed by fcollonval** 2022-02-16 09:36 UTC
Labels: bug, pkg:filebrowser, tag:Performance
