### ISSUE TITLE
JupyterLab always request to Build 

### ISSUE THREAD

**Issue by manuelsh** [jupyterlab/jupyterlab#5350] opened 2018-09-21 10:46 UTC
When running jupyter lab I am asked to `Build`, with the following message:

```
JupyterLab build is suggested:
jupyter-matplotlib needs to be included in build
@jupyter-widgets/jupyterlab-manager needs to be included in build
```

However, after building and reloading jupyter lab I get again the same request, nothing is solved. This is the log of the build:

```[W 10:38:29.677 LabApp] Build recommended
[W 10:38:29.677 LabApp] jupyter-matplotlib needs to be included in build
[W 10:38:29.677 LabApp] @jupyter-widgets/jupyterlab-manager needs to be included in build
[W 10:40:28.743 LabApp] The extension "jupyterlab_bokeh" is outdated.

[I 10:40:28.744 LabApp] > node /usr/local/lib/python3.5/dist-packages/jupyterlab/staging/yarn.js install
yarn install v1.9.4
info No lockfile found.
[1/4] Resolving packages...
warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[2/4] Fetching packages...
error url-loader@1.0.1: The engine "node" is incompatible with this module. Expected version ">= 6.9.0 || >= 8.9.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[I 10:40:39.759 LabApp] > node /usr/local/lib/python3.5/dist-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.9.4
$ webpack --config webpack.prod.config.js
/bin/sh: 1: webpack: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by blink1073** [comment] 2018-09-21 10:51
Hi @manuelsh, what is `node -v`?

**Comment by manuelsh** [comment] 2018-09-21 10:58
v6.2.2

thanks

**Comment by blink1073** [comment] 2018-09-21 10:58
Also, what is `jupyter lab --version`?

**Comment by manuelsh** [comment] 2018-09-21 10:58
0.34.7

**Comment by blink1073** [comment] 2018-09-21 11:02
Ah, we added a node version check after that.   The most recent version of jupyterlab ensures `node>=6.11.5` before attempting to build, for compatibility with the node packages we are using to build.  Are you able to update your version of `node`?

**Comment by manuelsh** [comment] 2018-09-21 11:18
I just installed the latest version of node, and have the same issue... Used nvm to install it.

Tried with version 6.11.5 and same. Maybe related to `bokeh` library?

```
[W 11:16:53.367 LabApp] Build recommended
[W 11:16:53.367 LabApp] jupyter-matplotlib needs to be included in build
[W 11:16:53.367 LabApp] @jupyter-widgets/jupyterlab-manager needs to be included in build
[I 11:16:55.230 LabApp] Kernel started: 90bf2cb6-2ac3-4d55-b6d8-abcda87b5242
[I 11:16:55.797 LabApp] Adapting to protocol v5.1 for kernel 90bf2cb6-2ac3-4d55-b6d8-abcda87b5242
[I 11:16:55.797 LabApp] Adapting to protocol v5.1 for kernel 90bf2cb6-2ac3-4d55-b6d8-abcda87b5242
[W 11:16:59.156 LabApp] The extension "jupyterlab_bokeh" is outdated.

[I 11:16:59.158 LabApp] > node /usr/local/lib/python3.5/dist-packages/jupyterlab/staging/yarn.js install
yarn install v1.9.4
info No lockfile found.
[1/4] Resolving packages...
warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[2/4] Fetching packages...
error html-webpack-plugin@3.2.0: The engine "node" is incompatible with this module. Expected version ">=6.9".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[I 11:17:11.174 LabApp] > node /usr/local/lib/python3.5/dist-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.9.4
$ webpack --config webpack.prod.config.js
/bin/sh: 1: webpack: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by blink1073** [comment] 2018-09-21 11:27
I'm working on build system fixed in https://github.com/jupyterlab/jupyterlab/pull/5351, I'll install nvm and look into this next.

**Comment by blink1073** [comment] 2018-09-21 11:34
Confirmed locally, it is using my system node instead of the current nvm version.

**Comment by blink1073** [comment] 2018-09-21 11:55
@minrk, I traced this to [jupyter_core](https://github.com/jupyter/jupyter_core/blob/c8c35524b969d479f9ae6c8dd40f27093ec7814f/jupyter_core/command.py#L116) adding my Anaconda executable path to the start of the PATH even though it is already on the PATH.  Is the only solution here to move away from `jupyter lab` and use top level `jupyterlab` scripts?

**Comment by jasongrout** [comment] 2018-09-21 12:01
@blink1073 - that code looks like it is only triggered if jupyter was run with an absolute path (so that `jupyter` may not have been on the path). Are we running jupyter with an absolute path?

This reminds me of the yarn bug that we had an issue with: https://github.com/yarnpkg/yarn/issues/5935

**Comment by jasongrout** [comment] 2018-09-21 12:03
(a workaround for this is, if `jupyter` was run with an absolute path, to search the path directories for the exact same jupyter script, and if it finds it (and not another `jupyter` script), don't prepend the directory)

**Comment by blink1073** [comment] 2018-09-21 12:09
I literally ran 'jupyter lab build'

**Comment by blink1073** [comment] 2018-09-21 12:10
'jupyter-lab build' grabs the correct node version.

**Comment by manuelsh** [comment] 2018-09-21 15:30
I assume you are working on solving the issue or can I do something already to solve it?

Thanks!

**Comment by blink1073** [comment] 2018-09-21 17:11
We don't yet have a workaround for using nvm, unfortunately

**Comment by manuelsh** [comment] 2018-09-21 17:16
What if I install node using something else instead of nvm?

**Comment by manuelsh** [comment] 2018-09-22 13:27
Thanks, but don't use conda. Will see if there is another way.

**Comment by blink1073** [comment] 2018-09-22 13:29
What does the following print?:

```
which jupyter-lab
which node
echo $PATH
```

**Comment by saulshanabrook** [comment] 2018-11-30 22:01
I am closing this for now, until we hear some input on whether the correct node version is being picked up in your path.  If you could run those commands and print the output, we can keep diagnosing thits.

**Closed by saulshanabrook** 2018-11-30 22:01 UTC
Labels: tag:Build System, type:Question

**Comment by manuelsh** [comment] 2018-12-02 18:53
Apologies, @blink1073 , for some reason I missed your last message. Issue was solved by updating jupyter. Thanks.

**Comment by blink1073** [comment] 2018-12-03 14:52
Glad to hear it!

**Comment by lakshya2315** [comment] 2019-02-03 03:50
I am having the same problem, although jupyter lab is launching fine but it is keep on requesting to build `@jupyter-lab/toc` extension. Here is the launch screen of the jupyter-lab looks like on the terminal:
```
[Shrushtis-MBP:~]$jupyter-lab
[I 21:00:04.411 LabApp] JupyterLab extension loaded from /anaconda3/lib/python3.6/site-packages/jupyterlab
[I 21:00:04.412 LabApp] JupyterLab application directory is /anaconda3/share/jupyter/lab
[W 21:00:04.413 LabApp] JupyterLab server extension not enabled, manually loading...
[I 21:00:04.421 LabApp] JupyterLab extension loaded from /anaconda3/lib/python3.6/site-packages/jupyterlab
[I 21:00:04.421 LabApp] JupyterLab application directory is /anaconda3/share/jupyter/lab
[I 21:00:04.422 LabApp] Serving notebooks from local directory: /Users/Shrushti
[I 21:00:04.422 LabApp] The Jupyter Notebook is running at:
[I 21:00:04.423 LabApp] http://localhost:8888/?token=c50b09ebd1b96a51435d610d180f8d2a0503817ca9af148d
[I 21:00:04.423 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 21:00:04.429 LabApp]

    To access the notebook, open this file in a browser:
        file:///Users/Shrushti/Library/Jupyter/runtime/nbserver-84311-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=c50b09ebd1b96a51435d610d180f8d2a0503817ca9af148d
[I 21:00:08.025 LabApp] Node v11.8.0

[W 21:00:08.540 LabApp] Build recommended
[W 21:00:08.540 LabApp] @jupyterlab/toc needs to be included in build
[I 21:00:10.625 LabApp] Kernel started: 6a67eb37-f69f-4534-8f42-e819c11f8f37
[I 21:00:11.541 LabApp] Node v11.8.0

[I 21:00:11.585 LabApp] > node /anaconda3/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
[I 21:00:12.441 LabApp] Adapting to protocol v5.1 for kernel 6a67eb37-f69f-4534-8f42-e819c11f8f37
[I 21:00:12.442 LabApp] Adapting to protocol v5.1 for kernel 6a67eb37-f69f-4534-8f42-e819c11f8f37
yarn install v1.9.4
error An unexpected error occurred: "ENOTDIR: not a directory, scandir '/Users/Shrushti/.config/yarn/link'".
info If you think this is a bug, please open a bug report with the information provided in "/anaconda3/share/jupyter/lab/staging/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[I 21:00:13.601 LabApp] > node /anaconda3/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build
yarn run v1.9.4
error An unexpected error occurred: "ENOTDIR: not a directory, scandir '/Users/Shrushti/.config/yarn/link'".
info If you think this is a bug, please open a bug report with the information provided in "/anaconda3/share/jupyter/lab/staging/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[I 21:00:17.820 LabApp] Starting buffering for 6a67eb37-f69f-4534-8f42-e819c11f8f37:5062cf9b-46f1-46dd-becc-466c1f38f187
[I 21:00:18.789 LabApp] Node v11.8.0

[W 21:00:19.269 LabApp] Build recommended
[W 21:00:19.272 LabApp] @jupyterlab/toc needs to be included in build
[I 21:00:20.654 LabApp] Adapting to protocol v5.1 for kernel 6a67eb37-f69f-4534-8f42-e819c11f8f37
[I 21:00:28.198 LabApp] Adapting to protocol v5.1 for kernel 6a67eb37-f69f-4534-8f42-e819c11f8f37
[I 21:05:00.861 LabApp] Starting buffering for 6a67eb37-f69f-4534-8f42-e819c11f8f37:725ed454-a4dd-4a30-901c-7b733874867e
^C[I 21:05:45.578 LabApp] interrupted
Serving notebooks from local directory: /Users/Shrushti
1 active kernel
The Jupyter Notebook is running at:
http://localhost:8888/?token=c50b09ebd1b96a51435d610d180f8d2a0503817ca9af148d
Shutdown this notebook server (y/[n])? ^C[C 21:05:45.757 LabApp] received signal 2, stopping
[I 21:05:45.758 LabApp] Shutting down 1 kernel
[I 21:05:46.065 LabApp] Kernel shutdown: 6a67eb37-f69f-4534-8f42-e819c11f8f37
```
