### ISSUE TITLE
Who owns jupyterlab.readthedocs.io ?

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#2956] opened 2017-09-01 15:40 UTC
The main documentation seem to be jupyterlab-tutorial.readthedocs.io

If this is the case then jupyterlab.readthedocs.io should likely redirect or say that it's not the canonical docs. Otherwise people will discover it, link to it, and users will be confused.

**Comment by blink1073** [comment] 2017-09-01 16:14
@willingc, do you own this?  I checked and I do not.

**Comment by willingc** [comment] 2017-09-01 17:18
Nope, I do not. Looking at the RTD build page, it looks like @mpacer may be the owner.
<img width="1014" alt="screenshot 2017-09-01 12 17 08" src="https://user-images.githubusercontent.com/2680980/29980505-aea500b0-8f0f-11e7-97bf-37213db200ab.png">

**Comment by mpacer** [comment] 2017-09-01 18:09
Not sure how that could have happened… happy to fix the situation. What exactly needs to occur?

**Comment by blink1073** [comment] 2017-09-01 18:12
You should be able to add maintainers at this link: https://readthedocs.org/dashboard/jupyterlab/users/

**Comment by blink1073** [comment] 2017-09-01 18:13
If you add `blink1073` I can handle the rest.

**Comment by mpacer** [comment] 2017-09-01 18:13
@willingc @ellisonbg @Carreau  what's your usernames on readthedocs? I'll happily add you as maintainers.

I just pointed it at jupyterlab/jupyterlab I'm very confused as to how this happened though.

**Comment by mpacer** [comment] 2017-09-01 18:14
Yep! Got it

**Comment by blink1073** [comment] 2017-09-01 18:15
I added ellisonbg and willingc, carreau doesn't seem to exist.

**Comment by mpacer** [comment] 2017-09-01 18:17
It's not GitHub usernames so it's fortunate that they're rtd usernames match :) I'm guessing @Carreau has a username but off the top of my head I'm not sure what.

**Comment by Carreau** [comment] 2017-09-01 18:24
I'm supposed to be `@carreau` on rtfd. At least that who I am on nbconvert. Try to change the casing of the C `@Carreau`/`@carreau`, I know I had some issue with that on Travis. I never remember which one is has issues.

**Comment by blink1073** [comment] 2017-09-01 18:25
Ah, lowercase did the trick.

**Comment by blink1073** [comment] 2017-09-01 18:27
Once we've made a new tagged release, we can make sure it has updated and point our README to the new page.

**Comment by Carreau** [comment] 2017-09-01 18:33
> Once we've made a new tagged release, we can make sure it has updated and point our README to the new page.

The Jupyter.org website also need to be updated. We likely want to setup some kind of redirect/page with information as well.

**Comment by mpacer** [comment] 2017-09-01 18:41
So I think it is already updated based on what I'm seeing when I go to
http://jupyterlab.readthedocs.io/en/latest/

**Comment by blink1073** [comment] 2017-09-01 18:43
@mpacer, that's showing a very old build.

**Comment by mpacer** [comment] 2017-09-01 18:53
Where can I find the version number of it? Because it should now point at jupyterlab/jupyterlab…

**Comment by mpacer** [comment] 2017-09-01 18:57
Like… the dependency graph that I'm seeing here didn't exist as of 6 days ago: 

![image](https://user-images.githubusercontent.com/2482408/29983896-b4a1f2fa-8f0c-11e7-85cb-7fb7556564e5.png)

**Comment by Carreau** [comment] 2017-09-01 19:19
There is a lot of caching on CDNs. It can take a wile to propagate. I definitively do not even see the Jupyter Theme on readthedocs (at least not yet).

**Comment by blink1073** [comment] 2017-09-01 19:20
I'm now seeing the updated version.

**Comment by mpacer** [comment] 2017-09-11 21:51
Can we close this now that this has been addressed?

**Comment by blink1073** [comment] 2017-09-11 21:52
Actually, I need to update the readme to close this, coming right up.

**Comment by jzf2101** [comment] 2017-09-11 21:59
@ian-r-rose made the dependency graph

**Comment by blink1073** [comment] 2017-09-11 22:02
believe the issue is that there can be only one named project on RTD (they aren't scoped by user), and @mpacer had created a project on a fork, which prevented us from creating one for this org.

**Comment by jzf2101** [comment] 2017-09-11 22:07
@mpacer can you add me too?

**Comment by blink1073** [comment] 2017-09-11 22:09
I can do it, what is your rtd login name, @jzf2101 (I tried your github handle first)?

**Comment by jzf2101** [comment] 2017-09-11 22:10
Oh do I need to make an account?

**Comment by jzf2101** [comment] 2017-09-11 22:11
@blink1073 try again

**Comment by blink1073** [comment] 2017-09-11 22:14
All set!

**Comment by willingc** [comment] 2017-09-11 22:25
Looks good. @jzf2101 Do you want the honors of closing? :crown:

**Comment by Carreau** [comment] 2018-02-02 20:29
this was fixed-unfixed-refixed ... so reopeneing.

**Closed** 2018-02-03 00:26 UTC
Labels: tag:Documentation
