### ISSUE TITLE
Feature request: Notebook "busy" in browser tab

### ISSUE THREAD

**Issue by jaklinger** [jupyterlab/jupyterlab#4355] opened 2018-04-11 10:32 UTC
A small but useful feature of Jupyter Notebook is the "busy" status in the browser tab (note: I'm using Chrome, but I assume this is independent of the browser). In Notebook, this is denoted by three dots:

![image](https://user-images.githubusercontent.com/19347498/38611431-8a663c44-3d7b-11e8-95e3-0782a3e595ec.png)

But this feature doesn't appear to exist in Lab whilst code is running. Are there any plans to implement it?

**Comment by saulshanabrook** [comment] 2018-04-11 15:25
I think this is a duplicate of #3957. Feel free to reopen or comment if this issue is different.

**Closed by saulshanabrook** 2018-04-11 15:25 UTC

**Comment by jasongrout** [comment] 2018-04-11 15:36
(when closing a duplicate issue, please add it to the "Reference" milestone...)

**Comment by saulshanabrook** [comment] 2018-04-11 16:06
@jasongrout Will do, thanks.
