### ISSUE TITLE
Keyboard shortcuts override key combinations

### ISSUE THREAD

**Issue by AntoineGautier** [jupyterlab/jupyterlab#15754] opened 2024-02-06 13:20 UTC
The following overwrites the key combination to enter the character `{` on French keyboard layout on macOS — when running jupyterlab on remote linux machine and accessing the server via local browser:

https://github.com/jupyterlab/jupyterlab/blob/82051a9d0c6dc93677b0b66560aea48d71aaa043/packages/application-extension/schema/commands.json#L87-L94

Other key combinations are overwritten by default shortcuts: 

- `Alt Shift 5` overwrites `[`
- `Alt ]` overwrites `}`

**Comment by krassowski** [comment] 2024-02-06 13:21
Thank you @AntoineGautier, this is a duplicate of https://github.com/jupyterlab/jupyterlab/issues/15744 - but your report helps to clarify that just how many languages are affected.

**Comment by JasonWeill** [comment] 2024-02-06 17:18
Closing as a duplicate of #15744.

**Closed by JasonWeill** 2024-02-06 17:18 UTC
Labels: status:Duplicate, status:Needs Triage
