### ISSUE TITLE
Feature Request - Metadata editor for Notebook (formatted like the Cell Metadata editor)

### ISSUE THREAD

**Issue by timkpaine** [jupyterlab/jupyterlab#5092] opened 2018-08-10 16:18 UTC
Probably a "Good First Issue"

Right now, you can right click an ipynb and open with Editor, but it doesn't necessary pretty-print it, and it displays the entire notebook. The Cell Metadata editor has some nice validation in it, it would be nice to have something similar for the Notebook itself. 

For context, we store some version control and other information in the notebook metadata

**Comment by blink1073** [comment] 2018-08-11 09:03
Duplicate of https://github.com/jupyterlab/jupyterlab/issues/1308.  :wink:

**Closed by blink1073** 2018-08-11 09:03 UTC
