### ISSUE TITLE
autocomplete (dot-tab) not always working in the same cell where variable is defined

### ISSUE THREAD

**Issue by t1nux** [jupyterlab/jupyterlab#7829] opened 2020-01-28 15:28 UTC
## Description

If a variable is defined in a cell, and the cell is executed, that variable does not always have a working auto-complete functionality if you try to auto-complete in the same cell were it was defined. This **does** work (ie. no bug) for instance for `str`, but not for a `numpy.array` and in my experience almost all other types.

I know this used to work in notebook, but that was quite a while ago.

## Reproduce

write this in a cell:

```python
x = np.array([0, 2])
```
execute the cell, for instance with CTRL-Enter to stay in the cell, and try to use auto-complete using something like

```python
x.TABTAB
```
**in the same cell**, ie. it looks like this:

```python
x = np.array([0, 2])
x.TABTAB
```
## Expected behavior

auto-complete works (but it doesn't)

## Context
The same (faulty) behavior also happens on jupyterlab test servers, eg. mybinder.org

- Operating System and version: Arch Linux
- Browser and version: Firefox
- JupyterLab version: 1.2.6

**Comment by vidartf** [comment] 2020-01-29 13:03
Confirmed on binder.

**Comment by agbaum** [comment] 2020-02-04 16:45
I can work on fixing this if no one else is!

**Comment by vidartf** [comment] 2020-02-04 17:35
@agbaum That would be very welcome 👍

**Comment by agbaum** [comment] 2020-02-13 23:22
So it turns out this is sort of an issue with jedi, the completer used by IPython. Here's a demonstration of the issue using jedi itself, where `success` is the equivalent of the string that gets sent via the completion request in the scenario that works, and `fail` is the string that gets sent in the scenario that fails.

```
x = np.array([0, 2])
success = "x."
fail = """x = np.array([0, 2])
             x."""

success_complete = jedi.Interpreter(success, [locals()]).completions()
fail_complete = jedi.Interpreter(fail, [locals()]).completions()
```

`success_complete` then has a bunch of completions in it, and `fail_complete` is empty. My understanding of this behavior is that jedi looks at the failing string and sees that we've redefined `x`, so it doesn't make sense for it to apply the old completions, as it doesn't know what `x` will be after the redefinition. It isn't able to make a prediction without knowing what x will be after the redefinition will, so it just returns nothing.

I can submit a bug report to jedi, but it's not clear to me that this behavior is a bug within the context of a line-by-line interpreter like ipython. The issue seems to stem from the fact that jupyter notebooks exist somewhere between an interpreter and a text editor.

One solution would be to have our completer only submit one line at a time, but that breaks any desired behavior we might have with multi-line completions. i.e.:


```
np.array([1,
2,
3]).TABTAB
```

I suppose a more perfect workaround would be to figure out how to cut the current expression (regardless of number of lines), and only submit that. That get's tricky when we're trying to be language agnostic, although I suppose it could be in the ipykernel (and the xpython kernel as well I suppose).

@vidartf Do you have any thoughts on all of this? It's turned out to be a bigger fish than I was really expecting.

**Comment by telamonian** [comment] 2020-02-14 01:46
@agbaum what about what @t1nux said about it working as expected for builtin types and for notebook classic?

**Comment by agbaum** [comment] 2020-02-14 04:41
I was able to reproduce the bug in notebook classic, my understanding of that comment was that it worked as expected at some point in the past.

As for built in types, I think jedi is just able to make those kinds of completions for builtin types. For instance, if you open up a clean ipython terminal and type:

`x = '.'; x.TABTAB`

it will autocomplete. Jedi knows that x has been defined as a string and will do the autocomplete, it just doesn't seem to have that capability for more complex types. I could submit a bug report/feature request to jedi for adding that autocomplete capability for complex types. It seems easy to extend the logic that makes `np.array([0,2]).TABTAB` work to `x=np.array([0,2]); x.TABTAB` . However things get harder with something like:

```
x = pd.read_csv('file').transpose().sum() 
x.TABTAB
```

In which case it seems like we just might be asking for behavior that differs from the way jedi thinks about autocompleting in the context of interpreters.

**Comment by t1nux** [comment] 2020-02-14 10:56
Just to clarify my initial post, the currently not working completion **in the same cell**, ie.
```
x = np.array([1, 2])
x.TABTAB
```
 used to work in the past for the normal notebook. That was quite a bit before lab. I actually managed to find an old winpython version which I had on a USB stick, where this is still working. It is winpython-3.5.2.3 (from 2016). There, the above mentioned completing is working (for `str` and `np.array`).

However, `x = 'bla'; x.TABTAB` is not working in that old version.

I was actually unaware that `x = 'bla'; x.TABTAB` is working in current versions, but that might be part of the problem. Jedi seems to be too smart and interprets things.

In the past, I **had to do** CTRL-enter (to stay in the cell) and only then the completion would work. So, `x` had to be initialized before any completion on `x` would work. This seems to have changed in recent versions. 

Granted, this change can be welcome (for `str`) but not so much for `np.array`.

Still, in a long cell, I find it sometimes a bit annoying that I have to split the cell just to have autocomplete, and then to recombine them after.

For completeness, these are the versions in that old winpython:
- winpython 5.3.2.3
- python 3.5.2
- jupyter 4.2.0
- jupyter notebook 4.2.3
- ipython 5.1.0

**Comment by nscozzaro** [comment] 2020-05-07 18:38
This could be specific to numpy parsing in Jedi, I saw others mentioned this:
https://github.com/davidhalter/jedi/issues/1230
https://github.com/davidhalter/jedi/issues/372

**Comment by krassowski** [comment] 2024-08-24 20:28
As per discussion this issue was likely a problem in the jedi library used by IPython for completions. Bot jedi issues linked above are closed now.

IPython also has a different implementation of tab-completer that does not depend on `jedi` which can be used as a fallback if future version of `jedi` breaks (to activate it run `%config IPCompleter.use_jedi=False`

The originally reported issue cannot be reproduced:

![image](https://github.com/user-attachments/assets/8901b427-fefd-4f18-981b-218fbce255ac)

I will close this as it is not actionable on JupyterLab side as there is no code responsible for generation of tab completion suggestions in JupyterLab. In future please report issues with IPython in the IPython repository: https://github.com/ipython/ipython and with jedi in the jedi repository: https://github.com/davidhalter/jedi

**Closed by krassowski** 2024-08-24 20:28 UTC
Labels: help wanted, status:Needs Discussion, pkg:notebook
