### ISSUE TITLE
Search term is sometimes appended at the end of the output

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#8224] opened 2020-04-15 23:35 UTC
## Description

The search term is sometimes appended at the end of the output.

## Reproduce

1. Run:

```python
from pandas import *
x = read_table()  # should raise an error
```

2. Search for `read_table` (should be in code cell and in an output)
3. See the backtrace output being distorted

![some_hits_are_appended](https://user-images.githubusercontent.com/5832902/79398698-2bc01380-7f79-11ea-8a0c-16970311cfea.gif)

It is even more ridiculous when there are multiple hits in the output.

## Expected behavior

The match is highlighted, but not displaced

## Context

- Browser and version: Chrome Version 81.0.4044.92
- JupyterLab version: 2.1.0

I once got:

```js
Uncaught TypeError: Cannot read property 'editor' of null
    at CodeCell.get editor [as editor] (widget.js:178)
    at refreshNextNCells (notebooksearchprovider.js:136)
```

but I do **not** think that it is related.

**Comment by jasongrout** [comment] 2020-04-15 23:40
Note in your image that the text is not appended to the output, but rather is moved from three lines above, that used to read `x = read_table()`. Even weirder. Perhaps it is just a css issue, where highlighting it just moved the text to the bottom somehow?

**Comment by krassowski** [comment] 2020-04-15 23:54
A reasonable guess, but I think it's not css; I do not see css positioning, but the `span` is moved to the end of the `pre`:

![Screenshot from 2020-04-16 00-52-49](https://user-images.githubusercontent.com/5832902/79399958-a9d1e980-7f7c-11ea-8439-6599af75bcab.png)

**Comment by jasongrout** [comment] 2020-04-16 13:24
> A reasonable guess, but I think it's not css; I do not see css positioning, but the `span` is moved to the end of the `pre`:

Oh wow, that is definitely weird.

**Comment by quangIO** [comment] 2020-04-20 05:23
I can confirm this weird behavior. Somehow the span was moved to the beginning of the pre for me.
![Wrong span](https://user-images.githubusercontent.com/13181907/79716445-b28c2d80-82a4-11ea-94a8-89fe472989a0.png)
* Firefox 76.0 on Linux x64
* Latest JupyterLab from the master branch

**Comment by ianhi** [comment] 2020-04-23 16:21
1. This does not occur if you use the vim search functionality built into codemirror:
![vim_search](https://user-images.githubusercontent.com/10111092/80123232-987c7480-855c-11ea-8f59-7b672208ec19.gif)

2. You can toggle the repositioning back and forth based on whether or not you fully type out table:
![search_moving](https://user-images.githubusercontent.com/10111092/80123301-ae8a3500-855c-11ea-9315-8941a34c8d5c.gif)

**Comment by ianhi** [comment] 2020-04-23 16:32
4. whether the span is placed at the start or end of the error seems to be related to the search terms positioning the error message. Whether it is in the first half or the second half:
![halfway_point_search](https://user-images.githubusercontent.com/10111092/80124509-5d7b4080-855e-11ea-8db3-3c5996850a64.gif)

**Comment by krassowski** [comment] 2020-05-13 19:07
Another edgcase:

![Screenshot from 2020-05-13 20-06-06](https://user-images.githubusercontent.com/5832902/81854156-6b1c5880-9555-11ea-9985-899bbaf3016a.png)

**Comment by jasongrout** [comment] 2020-10-23 16:27
Similar issue, but with output moving to the *start* of the text, is at #9181. My guess is that there is one fix for both issues.

**Comment by krassowski** [comment] 2021-02-04 23:10
Adding some reduced examples.

Setup:

```python
from IPython.display import HTML, display
```

### Failure: appends in front

```python
display(HTML(f'<pre><span>x</span>{1+1}z</pre>'))
```

- search for `2`
- expected: `x2z`
- actual: `2xz`

### Failure: appends at the end

```python
display(HTML(f'<pre>x{1+1}<span>z</span></pre>'))
```

- search for `2`
- expected: `x2z`
- actual: `xz2`

### Success: 

```python
display(HTML(f'<pre>x{1+1}z</pre>'))
```

- search for `2`
- expected: `x2z`
- actual: `x2z`

**Closed** 2021-02-09 13:13 UTC
Labels: pkg:documentsearch, tag:Search and Replace
