### ISSUE TITLE
Default recordTiming to true

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#9510] opened 2020-12-24 13:58 UTC
### Problem

By default record timing is disabled. I propose we default it to enabled. The amount of data it adds is minimal and seems to be bug free from usage over the last year or so. A lot of people get confused with having to turn this setting on for [deshaw/jupyterlab-execute-time](https://github.com/deshaw/jupyterlab-execute-time). Even without this plugin, it makes the property inspector more useful.

### Proposed Solution

Update [this](https://github.com/jupyterlab/jupyterlab/blob/b4db7f03d2ad0b91a9c8c252c56ae5e4a9408fbb/packages/notebook-extension/schema/tracker.json#L366) to true.

**Comment by krassowski** [comment] 2021-01-06 16:24
It might be a slight UX regression for users who diff their notebooks. Not a huge problem because the diffing tools allow to [ignore specific cell metadata](https://nbdime.readthedocs.io/en/latest/config.html#configuring-ignores), or they could turn it of manually, but still an extra noise in a lot of beginners notebooks. At minimum, this would need a good note in the changelog describing how to restore the previous behavior.

**Comment by mlucool** [comment] 2021-01-07 23:11
Agreed. Do I update something now in the PR or when it comes time to cut a release is it noted?

**Comment by goanpeca** [comment] 2021-06-08 19:01
Closing this as the behavior should remain opt-in. 

See: https://github.com/mlucool/jupyterlab/commit/6c520d7d763ec9a02096c9410cbb211272f5e5e0

https://github.com/deshaw/jupyterlab-execute-time/ could change the setting on activation, and possibly ask the user before doing so.

Thanks @mlucool !

**Closed by goanpeca** 2021-06-08 19:01 UTC
Labels: enhancement
