### ISSUE TITLE
Cell context menu does not appear on firefox

### ISSUE THREAD

**Issue by jacob22** [jupyterlab/jupyterlab#16396] opened 2024-05-29 22:44 UTC
The context menu for a cell fails to open in Firefox, but works properly on Chromium.
Environment:
Python: 3.11.7
Jupyter lab: 4.2.1
Firefox: 115.11.0esr (Linux)
Chromium: 124.0.6367.118 (Debian Linux testing)

![chromium](https://github.com/jupyterlab/jupyterlab/assets/7280465/992b6393-f36d-4b23-bea9-3a039153d85c)
![firefox](https://github.com/jupyterlab/jupyterlab/assets/7280465/74906f95-ca57-470c-aad4-e7cfaf349ac5)

**Comment by ruvilonix** [comment] 2024-05-30 22:32
Same here. It works in Edge 125.0.2535.67 (Official build) (64-bit), but not in Firefox 118.0.1 (64-bit).

It is Jupyter Lab 4.2.1 running in a Conda environment. When I create a new environment and install jupyterlab, then run it, it is still missing the full context menu.

**Comment by krassowski** [comment] 2024-05-31 08:28
This is because you are using an old versions of Firefox which does not support `:has()` selector. Please either:
- upgrade Firefox to v121, or
- if using Firefox v103-120 enable `layout.css.has-selector.enabled` flag in the `about:config` page, or
- downgrade JupyterLab to v4.1.x

Thank you for report. I will close this issue as a duplicate of https://github.com/jupyterlab/jupyterlab/issues/16391.

**Closed by krassowski** 2024-05-31 08:28 UTC
Labels: status:Needs Triage
