### ISSUE TITLE
Add explanatory texts for settings in the visual settings editor

### ISSUE THREAD

**Issue by joelostblom** [jupyterlab/jupyterlab#12425] opened 2022-04-17 16:27 UTC
### Problem

It is currently not possible to know what the effect of selecting some of the options in the visual settings editor. For example, I had no idea what "line wrap: bounded" did until I found issue https://github.com/jupyterlab/jupyterlab/pull/4936.

![image](https://user-images.githubusercontent.com/4560057/163723466-a3ec0535-f79f-484c-a2f3-bdaab060f8ec.png)

### Proposed Solution

Add explanatory text,either on hover for each option, or on the side of the dropdown for the selected option. In this case, what is in the PR comment would be great:

-    off: lines never wrap,
-    on: lines wrap at viewport border,
-    wordWrapColumn: lines wrap at column specified by wordWrapColumn parameter,
-    bounded: lines wrap at minimum between viewport width and wordWrapColumn parameter.

**Comment by jweill-aws** [comment] 2022-04-21 17:44
This is possible in our current schema, but it is not implemented for every option. To add this enhancement, we'd need to modify the schema to have better documentation.

![image](https://user-images.githubusercontent.com/93281816/164519529-43169712-6df5-492d-8725-e7b29fea4b46.png)

**Comment by jweill-aws** [comment] 2022-04-21 17:47
Affected code in here:

https://github.com/jupyterlab/jupyterlab/blob/7d6749ce4f467f8d374bb3930fcdadadee073fb5/packages/console-extension/schema/tracker.json#L131-L135

**Comment by JasonWeill** [comment] 2024-05-23 16:52
@kiansahafi Thank you for offering to help! It looks like fixing this issue will require creating an optional additional key to describe values such as `"off"` and `"on"` in `enum` settings, and it will require modifying the settings editor to use those descriptions in the UI. Please feel free to add comments or open a draft pull request (PR) if you have any questions. Once you're ready to propose a change, you can open a PR marked ready for review.

**Comment by kiansahafi** [comment] 2024-05-26 14:30
@JasonWeill  thanks for the helps, i have been trying to build the project but could not build it through the docker file because of [this issue](https://github.com/jupyterlab/jupyterlab/issues/14651), is there an alternative way to build the project or i should just wait until the issue is resolves?

**Comment by krassowski** [comment] 2024-05-26 14:58
@kiansahafi how exactly were you trying to use docker? That issue should have been closed long ago (I just did it now) because the scripts that were mentioned were rewritten, and the new docker image is tested regularly.

The up to date docker instructions are here: https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html#setup-using-docker

> is there an alternative way to build the project 

Yes, the docker is not required at all. A couple of ways to setup local development. You can either follow
- a) manually steps
  1. https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html#installing-node-js-and-jlpm
  2. https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html#installing-jupyterlab
- b) one of the three automated setup options (Dev Container, Docker, Vagrant - not sure if Vagrant works though): https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html#using-automation-to-set-up-a-local-development-environment

(the order of presentation in docs needs improving - if you see what I mean feel welcome to send a docs PR)

> should just wait until the issue is resolves

no issues with docker are known to me as of today so it will not resolve itself unless you can report the exact problem :)

**Comment by kiansahafi** [comment] 2024-05-26 15:12
@krassowski thanks for the feedback, i am executing this command (as it is in the documentation): `bash docker/start.sh`

it fails to builds giving this error:

```
Dockerfile:55
--------------------
  53 |     
  54 |     # Build the cache in /home/$MAMBA_USER/jupyterlab_cache
  55 | >>> RUN micromamba run yarn install
  56 |     
  57 |     WORKDIR /home/$MAMBA_USER/jupyterlab
--------------------
ERROR: failed to solve: process "/usr/local/bin/_dockerfile_shell.sh micromamba run yarn install" did not complete successfully: exit code: 1
```


docker build Error:
<img width="1125" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/82085912/d733cd87-6024-41f8-b4c2-d9d9243e545a">

(i am using a macbook M1)

**Comment by krassowski** [comment] 2024-05-26 15:16
Two questions:
- can you open a new issue about docker setup failing on Mac M1?
- can you include the full traceback as the screenshot above is cut off in the place where things start to get interesting?

Thank you!

**Comment by kiansahafi** [comment] 2024-05-26 15:46
@krassowski thank you again. i have opened it as a [new issue](https://github.com/jupyterlab/jupyterlab/issues/16379).

**Comment by Adam-D-Lewis** [comment] 2024-10-09 10:13
I was considering working on this.  It looks like the affected code has been removed in this PR - https://github.com/jupyterlab/jupyterlab/pull/13639.  The affected setting has been changed to a boolean.

**Comment by krassowski** [comment] 2024-10-09 10:47
Closing as per above, thanks @Adam-D-Lewis!

**Closed by krassowski** 2024-10-09 10:47 UTC
Labels: enhancement, pkg:console, good first issue
