### ISSUE TITLE
Delete Files from JupyterLab UI

### ISSUE THREAD

**Issue by rsubra13** [jupyterlab/jupyterlab#3792] opened 2018-02-01 23:32 UTC
Hi,
When I try to delete the files from jupyterLab, I get an error "Delete Failed
Invalid response: 500 Internal Server Error"

**Version:**
Beta 1 Release
Version 0.31.2

**Comment by blink1073** [comment] 2018-02-03 22:38
Hi @rsubra13, can you please run `jupyter lab` from a terminal, and see if there is any log output associated with the file you are deleting?

**Comment by wkvolkman** [comment] 2018-02-09 04:02
Hello, this is a duplicate of https://github.com/jupyterlab/jupyterlab/issues/3793 for which I provided the log information.

**Closed** 2018-03-05 17:28 UTC
Labels: status:Needs Info
