### ISSUE TITLE
Error when using /lab/tree

### ISSUE THREAD

**Issue by jpuerto-psc** [jupyterlab/jupyterlab#13181] opened 2022-10-04 15:56 UTC
## Description

If you append `/lab/tree` to the JupyterLab URL without anything else, JupyterLab gets into a state where on any reload, it throws an error about the Path not being found.

## Reproduce

1. Launch a JupyterLab session.
2. Manually modify the URL such that the it ends in `/lab/tree`.
3. This should throw a popup error as follow:
<img width="473" alt="image" src="https://user-images.githubusercontent.com/68066250/193867106-02a3cae3-c728-4b4a-99f9-0e80d156282d.png">
4. Click Dismiss and refresh the page. This should throw the same error.

## Expected behavior

This error should only appear when the URL is invalid. Refreshing the page (or attempting to load a different path using the `/lab/tree` URL method) should not throw the same error.

## Context

- Operating System and version: macOS 12.6 & Ubuntu 18.04
- Browser and version: Chrome 105.0.5195.125
- JupyterLab version: 3.4.5

<details><summary>Troubleshoot Output</summary>
<pre>
WARNING: You are using pip version 20.3.1; however, version 22.2.2 is available.
You should consider upgrading via the '/Users/jpuerto/user_workspaces_dir/jpuerto/test/venv/bin/python -m pip install --upgrade pip' command.
$PATH:
	/Users/<username>/user_workspaces_dir/<username>/test/venv/bin
	/usr/local/opt/python@3.7/bin
	/usr/local/bin
	/usr/bin
	/bin
	/usr/sbin
	/sbin
	/Users/<username>/.fzf/bin

sys.path:
	/Users/<username>/user_workspaces_dir/<username>/test/venv/bin
	/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python38.zip
	/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8
	/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/lib-dynload
	/Users/<username>/user_workspaces_dir/<username>/test/venv/lib/python3.8/site-packages

sys.executable:
	/Users/<username>/user_workspaces_dir/<username>/test/venv/bin/python

sys.version:
	3.8.2 (default, Jul 14 2020, 05:39:05)
	[Clang 12.0.0 (clang-1200.0.26.2)]

platform.platform():
	macOS-12.6-x86_64-i386-64bit

which -a jupyter:
	/Users/<username>/user_workspaces_dir/<username>/test/venv/bin/jupyter
	/usr/local/bin/jupyter

pip list:
	Package               Version
	--------------------- -----------
	anyio                 3.6.1
	appnope               0.1.3
	argon2-cffi           21.3.0
	argon2-cffi-bindings  21.2.0
	asciitree             0.3.3
	asttokens             2.0.8
	attrs                 22.1.0
	Babel                 2.10.3
	backcall              0.2.0
	beautifulsoup4        4.11.1
	black                 22.8.0
	bleach                5.0.1
	certifi               2022.6.15
	cffi                  1.15.1
	charset-normalizer    2.1.1
	click                 8.1.3
	debugpy               1.6.3
	decorator             5.1.1
	defusedxml            0.7.1
	entrypoints           0.4
	executing             1.0.0
	fasteners             0.17.3
	fastjsonschema        2.16.1
	generate-tiff-offsets 0.1.7
	h11                   0.13.0
	h2                    4.1.0
	hpack                 4.0.0
	hypercorn             0.14.1
	hyperframe            6.0.1
	idna                  3.3
	importlib-metadata    4.12.0
	importlib-resources   5.9.0
	ipykernel             6.15.2
	ipython               8.4.0
	ipython-genutils      0.2.0
	ipywidgets            8.0.1
	jedi                  0.18.1
	Jinja2                3.1.2
	json5                 0.9.10
	jsonschema            4.15.0
	jupyter-client        7.3.5
	jupyter-core          4.11.1
	jupyter-server        1.18.1
	jupyterlab            3.4.5
	jupyterlab-pygments   0.2.2
	jupyterlab-server     2.15.1
	jupyterlab-widgets    3.0.2
	lxml                  4.9.1
	MarkupSafe            2.1.1
	matplotlib-inline     0.1.6
	mistune               2.0.4
	mypy-extensions       0.4.3
	nbclassic             0.4.3
	nbclient              0.6.7
	nbconvert             7.0.0
	nbformat              5.4.0
	negspy                0.2.24
	nest-asyncio          1.5.5
	notebook              6.4.12
	notebook-shim         0.1.0
	numcodecs             0.10.2
	numpy                 1.23.2
	packaging             21.3
	pandas                1.4.4
	pandocfilters         1.5.0
	parso                 0.8.3
	pathspec              0.10.0
	pexpect               4.8.0
	pickleshare           0.7.5
	pip                   20.3.1
	pkgutil-resolve-name  1.3.10
	platformdirs          2.5.2
	priority              2.0.0
	prometheus-client     0.14.1
	prompt-toolkit        3.0.30
	psutil                5.9.1
	ptyprocess            0.7.0
	pure-eval             0.2.2
	pycparser             2.21
	Pygments              2.13.0
	pyparsing             3.0.9
	pyrsistent            0.18.1
	python-dateutil       2.8.2
	pytz                  2022.2.1
	pyzmq                 23.2.1
	requests              2.28.1
	scipy                 1.9.1
	Send2Trash            1.8.0
	setuptools            51.0.0
	six                   1.16.0
	sniffio               1.3.0
	soupsieve             2.3.2.post1
	stack-data            0.5.0
	starlette             0.20.4
	terminado             0.15.0
	tifffile              2020.10.1
	tinycss2              1.1.1
	toml                  0.10.2
	tomli                 2.0.1
	tornado               6.2
	traitlets             5.3.0
	typing-extensions     4.3.0
	urllib3               1.26.12
	vitessce              1.0.9
	wcwidth               0.2.5
	webencodings          0.5.1
	websocket-client      1.4.0
	wheel                 0.36.1
	widgetsnbextension    4.0.2
	wsproto               1.2.0
	zarr                  2.12.0
	zipp                  3.8.1
</pre>
</details>

<details><summary>Command Line Output</summary>
[output_log.txt](https://github.com/jupyterlab/jupyterlab/files/9708596/output_log.txt)
</details>

**Comment by jweill-aws** [comment] 2022-10-06 16:32
This is a duplicate of #12768.

**Closed by jweill-aws** 2022-10-06 16:32 UTC
Labels: bug, status:Needs Triage
