### ISSUE TITLE
Non visible cursor when editing files (e.g. .py) with dark theme

### ISSUE THREAD

**Issue by QuentinQuinten** [jupyterlab/jupyterlab#4104] opened 2018-03-04 19:33 UTC
When one selects the **`Dark Theme`** instead of the **`Light Theme`** in the settings it is no longer possible to see the the curser in projects files like Python files. This makes it nearly impossible to edit these files while using the  **`Dark Theme`** .

**Comment by ian-r-rose** [comment] 2018-03-08 15:45
Hi @QuentinQuinten, there was a bug to this effect, but it has been fixed in a recent patch release. What version of JupyterLab are you running, and can you try updating?

**Comment by QuentinQuinten** [comment] 2018-03-08 15:57
@ian-r-rose I am running Version 0.31.10. I only have this problem when using the **`default`** TextEditor Theme while the **`Dark Theme`**  for Jupyter Lab is selected.

**Comment by JacquotLeHaricot** [comment] 2018-03-08 17:09
Hi all, 
first thank you for this wonderful tool that is JupyterLab. Can't get enough of it.
Then, I too experience a non-visible cursor in Jupyter Lab :
* JupyterLab version 0.31.10
* with Firefox Quantum 58 (could reproduce the issue with Chrome 64)
* only in the code editor (not in the notebooks) ; theme is the default one
* at all levels of zoom

**Comment by JacquotLeHaricot** [comment] 2018-03-08 17:22
Hi all, 
first thank you for this wonderful tool that is JupyterLab. Can't get enough of it.
Then, I too experience a non-visible cursor in Jupyter Lab :
* JupyterLab version 0.31.10 
* with Firefox Quantum 58 (could reproduce the issue with Chrome 64)
* only in the code editor (not in the notebooks) ; whatever the text editor theme
* at all levels of zoom
I updated jupyterlab version to 0.31.12 but the error persists.

**Comment by LucFrachon** [comment] 2018-03-10 18:12
Hi, I have the same issue. I am running Jupyter Lab 0.31.12 on Chromium, through a Xming window launched in Windows Ubuntu Bash.
It was working fine yesterday and today the cursor is not visible, regardless of the Jupyter Lab theme, Editor theme and zoom level. It makes it very hard to write any code.

**Comment by Fred-Byrd** [comment] 2018-03-22 18:57
Hey folks,

Just wanted to add some info that may be helpful regarding this issue (or related issues). I was configuring my editor settings to turn off auto closing brackets. I first tried it by editing the Text Editor Settings and put the following in the User Overrides:

``{ "editorConfig": { "autoClosingBrackets": false} }

And received the same error reported above; I could not see my cursor. Editing notebook files didn't show this issue, and when I reverted my changes the cursor reappeared. Oddly, brackets still didn't auto-close as one would expect.

It might have something to do with manual entries in the User Overrides section then. Maybe the back-end that joins these overrides into the rest of the editor settings is acting up?

**Comment by ian-r-rose** [comment] 2018-03-22 23:57
Hi @Fred-Byrd, thanks, you are completely right. This should have been fixed in #4158, and will be available in the next release.

**Comment by JacquotLeHaricot** [comment] 2018-03-27 08:28
If I'd have to add my 2 cents @ian-r-rose, I have no visible cursor whatever my Text Editor Config User Overrides are.
Maybe it's multiple causes for a single error ?...

**Comment by saulshanabrook** [comment] 2018-09-10 16:40
Has anyone had this issue since 0.32.0?

**Comment by ian-r-rose** [comment] 2018-09-10 16:50
This has been fixed more than once, but I think it is working properly in 0.34.

**Comment by jasongrout** [comment] 2018-09-10 16:54
> This has been fixed more than once, but I think it is working properly in 0.34.

I just checked, and it's working for me.

**Closed by jasongrout** 2018-09-10 16:54 UTC
Labels: pkg:fileeditor, status:Needs Info

**Comment by louis-red** [comment] 2018-09-13 13:05
All good for me in 0.32.1

**Comment by jasongrout** [comment] 2018-09-13 16:51
Thanks for following up!
