### ISSUE TITLE
Close without saving dialog even when no changes

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#3706] opened 2018-01-24 05:12 UTC
When I try and close a file which I've just opened and has no changes I still see the *"Close without saving"* dialog:

![image](https://user-images.githubusercontent.com/881019/35315594-e1b449fe-0118-11e8-8a2e-53596041522a.png)

python 3.6.4
jupyterlab 0.31.1

**Comment by ian-r-rose** [comment] 2018-01-24 17:36
@dhirschfeld I can't reproduce this on `v0.31.1` or on master. Can you think of anything unusual about your setup?

**Comment by dhirschfeld** [comment] 2018-01-24 19:19
It's running in a Windows Container. Also that file was from a git repo - can't see that that could affect it tho

Wondering how I can debug further?

**Comment by blink1073** [comment] 2018-01-24 20:43
I suspect this will be fixed in the process of fixing https://github.com/jupyterlab/jupyterlab/issues/3495

**Comment by blink1073** [comment] 2018-03-05 19:01
On second thought, I think the issue here is that the file endings might have changed.  When you open the file, does the close icon in that tab change to a filled circle?

**Comment by dhirschfeld** [comment] 2018-03-06 03:25
On holiday so prob can't check for a couple of weeks. If I forget to update this issue feel free to ping me again here...

**Comment by jasongrout** [comment] 2018-03-15 22:48
Bumping to beta 3. @dhirschfeld - if you can ping back when you're ready to move forward, that would be great!

**Comment by dhirschfeld** [comment] 2018-04-03 07:17
Looks like it is a line ending thing. As soon as I open it the line endings are changed and if I then save it git thinks it's modified. You can see the line endings changing in the before and after `Get-Content` calls below:

![image](https://user-images.githubusercontent.com/881019/38234848-6f166eec-3762-11e8-95d0-a40228c36745.png)

**Comment by dhirschfeld** [comment] 2018-04-03 07:18
Also, after saving the "unsaved indicator" doesn't reflect the fact that the file has been saved:
![image](https://user-images.githubusercontent.com/881019/38234993-f5b6265e-3762-11e8-8cfa-b31fca083b4c.png)

After saving the dialog doesn't pop up and git does show the changed content so you know the save did in fact take place

**Closed** 2018-11-14 03:10 UTC
Labels: pkg:docregistry, tag:Backwards compatible, type:Bug
