### ISSUE TITLE
Hyperlink in notebook to a heading in another notebook not working in JL

### ISSUE THREAD

**Issue by kdeleeuw11** [jupyterlab/jupyterlab#6268] opened 2019-04-29 03:41 UTC
Hi! Thanks for using JupyterLab.

If you are reporting an issue with JupyterLab, please use the [GitHub issue](https://github.com/jupyterlab/jupyterlab/issues) search feature to check if your issue has been asked already. If it has, please add your comments to the existing issue.

The JupyterLab team and Project Jupyter value our community, and JupyterLab
follows the Jupyter [Community Guides](https://jupyter.readthedocs.io/en/latest/community/content-community.html).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10]
- Browser [e.g. chrome 69.0, firefox 62.0]
- JupyterLab [e.g. 0.34.2]

**Additional context**

If available, please include the following details:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser console here.
</pre>
</details>

**Comment by kdeleeuw11** [comment] 2019-04-29 03:47
I have two notebooks, test1.ipynb and test2.ipynb. In test1 I have a number of headings, one of them "section 2".  In test2 I have a hyperlink: [section 2](test1.pynb#section-2). When I click on this hyperlink in test2, it opens test1 but does not go to "section 2". When I test this in the classic notebook  it works ok and jumps to "section 2".

**Comment by agoose77** [comment] 2019-04-29 09:00
Possibly related to https://github.com/jupyterlab/jupyterlab/issues/5877 ?

**Comment by jasongrout** [comment] 2019-04-29 14:29
> Possibly related to #5877 ?

Sounds likely. @kdeleeuw11, can you try in the latest prerelease (1.0a3) and see if it works there? You can also check on current master by using the dev binder: https://mybinder.org/v2/gh/jupyterlab/jupyterlab/master?urlpath=lab-dev/

**Comment by kdeleeuw11** [comment] 2019-04-30 01:59
I have retested this using the link below to binder. I got the same result, it doesn’t work in JupyterLab, but it works ok in the classic notebook.

**Comment by jasongrout** [comment] 2019-04-30 23:35
Thanks @kdeleeuw11. Sounds like there is still something to do in jupyterlab. Can we get a reproducible test case for this? Can you give us the exact markdown code in two notebooks where the links aren't working in jlab, but are working in classic notebook?

**Comment by jasongrout** [comment] 2019-04-30 23:44
> Possibly related to #5877 ?

Looks like it probably isn't #5877. In JLab 1.0a3, if I generate a markdown cell with `## *header*`, I get:

```html
<h2 id="header"><em>header</em><a target="_self" href="#header" class="jp-InternalAnchorLink">¶</a></h2>
```
Of course, this is problematic if we have two views of the same notebook on the page (or even two markdown cells with that same text), since ids are suppose to be unique on a page. But perhaps it's the best we can do for now.

@kdeleeuw11 - we can debug this further when we have a test case (i.e., the markdown from your anchor, and the markdown from your link to the anchor).

**Comment by kdeleeuw11** [comment] 2019-05-01 05:15
Attached two notebooks, test1.ipynb and test2.ipynb. test2.ipynb has a link to section 3 in test1.ipynb. I have put in a number lines of text in test1 to properly test whether the link jumps to the correct heading.

**Comment by jasongrout** [comment] 2019-05-01 05:25
Thanks for getting these together! Apparently your attachments didn't make it to the github issue, so we can't see them.

I think it would be sufficient to give us the markdown you are using in your cell for section 3 of test1.ipynb, and the markdown you are using in test2.ipynb to link to that section 3.

**Comment by kdeleeuw11** [comment] 2019-05-01 05:31
The markdown in test1 is:  # Section 3. I have quite a number of lines in the markdown above the one with  # Section 3 so you can see whether the link jumps to the right markdown cell. 

The markdown in test2 is:  [Reference to Section 3 in notebook test1](test1.ipynb#Section-3)

**Comment by jasongrout** [comment] 2019-05-01 06:21
This works for me in the dev binder: https://mybinder.org/v2/gh/jupyterlab/jupyterlab/master?urlpath=lab-dev/. I'm using Firefox 66 on macOS. What are you using?

I created two files, test1.ipynb and test2.ipynb. In test1, I made a bunch of empty cells, then a cell with `# Section 3`. In test2, I made a markdown cell with the code you have above: `[Reference to Section 3 in notebook test1](test1.ipynb#Section-3)`. Clicking on the link in several different situations always opened up test1 scrolled to the right place.
![references](https://user-images.githubusercontent.com/192614/57007584-40c15c80-6bd9-11e9-8a1d-75a924e88fd0.gif)

**Comment by kdeleeuw11** [comment] 2019-05-01 06:52
I am using Chrome Version 73.0.3683.86 on MacOS. I will test with Firefox and also Safari and will let you know

**Comment by kdeleeuw11** [comment] 2019-05-01 07:00
I might have found the issue. It works for me on Firefox and now also on Chrome but only if test1 is already open. If it is not open, the link will open test1, but doesn’t jump to section 3. I had tested it with the notebook closed

**Comment by jasongrout** [comment] 2019-05-01 07:21
I tested it with the notebook closed, and then open (see the video above). Did it work for you in Firefox with the notebook closed?

**Comment by kdeleeuw11** [comment] 2019-05-01 07:25
Yes, I did and it didn’t work. I am pretty sure that I am doing the same as you do. I will try in Safari and see what happens.

**Comment by kdeleeuw11** [comment] 2019-05-01 07:37
I have now tested in Safari and also created a test3 notebook with empty cells instead of text. I still get the same result in all three browsers. When the notebook is closed, it opens the notebook but doesn’t jump to section 3. It is strange, I hope I am not wasting your time.

**Comment by jasongrout** [comment] 2019-05-01 08:02
Just checking, you're using the dev binder link for your tests? https://mybinder.org/v2/gh/jupyterlab/jupyterlab/master?urlpath=lab-dev/

**Comment by kdeleeuw11** [comment] 2019-05-01 08:03
No, it is on my local computer

**Comment by jasongrout** [comment] 2019-05-01 08:04
Please use the dev binder link. That way we are testing exactly the same JupyterLab version, i.e., the current development master version. That will tell us if things are fixed already.

**Comment by kdeleeuw11** [comment] 2019-05-01 08:10
It works when I use the dev binder link. 

I have to leave, but I am happy to do further testing tomorrow (I live in Sydney Australia). Would also be happy to do testing of other functionality if that would help. I am not very technical, but I have experience in testing software from a user point of view. I am now retired.

**Comment by jasongrout** [comment] 2019-05-01 08:17
If it works in the dev binder link, then I think we are good! It's fixed in the current codebase, and will be in the next release. Thanks for testing it!

**Closed by jasongrout** 2019-05-01 08:17 UTC
Labels: status:Needs Info

**Comment by jasongrout** [comment] 2019-05-01 08:18
If you want to help out with other things, feel free to test other issues, or install the latest prereleaes using `pip install --pre jupyterlab` in a new environment and let us know of issues you see. Thanks again, I see you are very thorough in your testing.

**Comment by kdeleeuw11** [comment] 2019-05-02 02:19
Just to confirm that it works in the prerelease. I just installed version 1.0.0a3 and the link now works also on my local environment
