### ISSUE TITLE
JupyterLab 0.35.4 cannot handle folder names  or file names with blanks in them

### ISSUE THREAD

**Issue by jofowler** [jupyterlab/jupyterlab#5592] opened 2018-11-06 00:30 UTC
**Describe the bug**
JupyterLab 0.35.4 cannot open, delete or rename folders or files that have a blank in their name.
This is particularly unfortunate since when you create a new folder, it is initially named "Unnamed Folder"

**To Reproduce**

1. Go to 'JupyterLab File Browser.'
2. Click on 'New Folder'
3. Double click on the "Unnamed Folder" that was just created to naviagate to the folder
4. Error message is displayed, 'Directory not found: ""'
5. Right click on "Unnamed Folder" select Delete
6. Confirm the Delete
7. Error message is displayed "Invalid response: 404 Not Found"
8. Right click on "Unnamed Folder" select Rename
9. Type in a new file name like Fred
10. Error message is displayed "Rename Error Invalid response: 500 Internal Server Error"

**Expected behavior**
Expected to navigate to the folder, delete the folder, rename the folder.

**Desktop (please complete the following information):**
- OS: [e.g. Windows 10]
- Browser: Chrome Version 70.0.3538.77 (Official Build) (64-bit)
- JupyterLab 0.35.4 is running on Centos 6.10 in VirtualBox 5.22 on Windows 10

**Comment by madx** [comment] 2018-11-07 08:50
I tried to reproduce this and I do not get the errors you mentionned. I am running JupyterLab 0.35.4 on ArchLinux

**Comment by ian-r-rose** [comment] 2018-11-07 15:21
I also cannot reproduce this on Linux.

**Comment by jofowler** [comment] 2018-11-07 21:56
I am hitting this bug with JupyterLab running on Centos 6.10 in Virtuabox.

**Comment by jasongrout** [comment] 2018-11-12 23:57
Does it work in the classic notebook for you? (Click Help > Launch Classic Notebook to start the classic notebook with exactly the same server).

**Comment by jofowler** [comment] 2018-11-13 00:29
The problem appears to be related to how the blank in the folder name or file name is being escaped.

> ls -al | grep Untitled
drwxr-xr-x.  2 cyberdyne_admin cyberdyne_admin     6 Nov 12 18:39 Untitled Folder
> ls -al Untitled%20Folder
ls: cannot access Untitled%20Folder: No such file or directory
> ls -al Untitled%%20Folder
ls: cannot access Untitled%%20Folder: No such file or directory

**Comment by jofowler** [comment] 2018-11-13 15:35
This looks very similar to a problem that was fixed in notebook 5.1.0  Notebook issue #2867

**Comment by jasongrout** [comment] 2020-04-02 16:42
Closed as fixed in Notebook. Thanks!

**Closed by jasongrout** 2020-04-02 16:42 UTC
Labels: tag:Browser Compatibility, type:Bug
