### ISSUE TITLE
"@jupyter-widgets/jupyterlab-manager" is not a valid npm package

### ISSUE THREAD

**Issue by david-waterworth** [jupyterlab/jupyterlab#6759] opened 2019-07-04 03:11 UTC
Since updateing to version 1.1 ( from a release candidate) I'm getting the following error:

`jupyter labextension install @jupyter-widgets/jupyterlab-manager`

> An error occured.
> ValueError: "@jupyter-widgets/jupyterlab-manager" is not a valid npm package

Not sure if it's using a cached version? Is there a way of forcing download of the latest, or is jupyter-widgets not been updated yet? (I've updated to ipywidgets-7.5.0)

**Comment by david-waterworth** [comment] 2019-07-05 06:12
I've worked it out

`jupyter labextension install @jupyter-widgets/jupyterlab-manager --debug`

Error: EACCES: permission denied, mkdir '/home/david/.npm/_cacache/index-v5/17/5a'

For some reason I don't have write access to ~/.npm

After I fixed the fs permissions the error went away

**Comment by vidartf** [comment] 2019-07-08 11:38
Thanks for reporting back with the root cause and remediation of your issue! Closing as resolved then.

**Closed by vidartf** 2019-07-08 11:38 UTC
