### ISSUE TITLE
File Save Error

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#3506] opened 2018-01-01 08:37 UTC
I got the following error when saving a notebook. 

File Save Error

'_xsrf' argument missing from POST

**Comment by blink1073** [comment] 2018-01-02 09:39
Hi @dclong, did this happen when refreshing a JupyterLab page after restarting the notebook server?  
If you restart the server and it gets a new token that differs from the previous one, then the client will attempt to use the previous token, which will be rejected by the server.   The server will then expect to see the `_xsrf` authentication, which would not have been provided by the client because it is using token authentication.  We cannot provide both forms of authentication to the server.

I believe the way to avoid this is to use a password (` jupyter notebook password`).

**Comment by dclong** [comment] 2018-01-02 12:17
@blink1073 
I'm using JupyterLab via JupyterHub. I don't know whether JupyterHub restarted the notebook server or not. JupyterHub is authenticated using password, however, I'm not sure how the underlying notebook server is authenticated. I need to read docs about JupyterHub on this.

**Comment by blink1073** [comment] 2018-01-02 12:56
Does this give a string value when entered into the browser web console?  `JSON.parse(document.getElementById('jupyter-config-data').textContent).token`.

Also, does this give an answer that is not `-1`:  `document.cookie.indexOf('_xsrf')`?

**Comment by dclong** [comment] 2018-01-02 13:17
1. `JSON.parse(document.getElementById('jupyter-config-data').textContent).token` returns an empty string.

2. `document.cookie.indexOf('_xsrf')` returns 0

But as I mentioned I'm using JupyterHub and the issue is gone right now. I'll have a try of these 2 commands immediate if I come across the same issue again.

**Comment by blink1073** [comment] 2018-01-02 13:33
Great, thanks!

**Comment by sbailey** [comment] 2018-03-29 22:43
FYI, I had the same experience of a 403 error mentioning "'_xsrf' argument missing from POST" in the jupyter.log.  Like @dclong I was using JupyterHub and I confirmed with the admins that it had not been restarted around the time of the problem.

It appeared to happen spontaneously: saving was working fine, and then 10 minutes later I started getting the 403 errors and couldn't save.  I had been using the notebook for several days.

Anecdotally I'm under the impression that saving becomes flaky if the notebook loses the network connection unexpectedly, e.g. if I close my laptop without remembering to first close the browser window running the notebook from a remote JupyterLab / JupyterHub.  When I come back to the notebook in that case sometimes it works, and sometimes it has problems saving after further updates.  I've never had a problem when I've remembered to cleanly close the window (while leaving the notebook running on the remote server) and then reconnect from a new window later.  I can't back this up with reproducible examples, but I mention this in case it is a clue.

**Comment by xguse** [comment] 2018-05-17 13:17
does anyone have a method to recover from this? I would really like to not lose my work when this happens.

**Comment by damienrj** [comment] 2018-05-18 18:31
@xguse At least in my case restarting the notebook server without closing the notebook window allowed me to save the notebook.

**Comment by Honghe** [comment] 2018-06-13 06:12
Meet `'_xsrf' argument missing from POST` too when export draw.io to image.
* JSON.parse(document.getElementById('jupyter-config-data').textContent).token returns an empty string.
* document.cookie.indexOf('_xsrf') returns 0

**Comment by tbenst** [comment] 2018-07-16 17:50
Encountered same problem. Here's how to reproduce (at least in Firefox on ubuntu):
1. launch jupyter lab
2. open an existing ipynb
3. make changes (do not save)
4. `pkill firefox`
5. relaunch firefox
6. make new changes to same ipynb and try to save

**Comment by AnaHristian** [comment] 2018-09-28 08:54
Had the same error spontaneously using Jupyter Notebook, I shutdown all the running notebooks, it took a few minutes and everything returned to normal, the autosaved message from the notebook appeared, I restarted the kernels and continued my work.

**Comment by bdoury** [comment] 2018-10-05 09:32
I had the same issue today. Any chance someone is working on this bug?
Thanks

**Comment by jasongrout** [comment] 2018-10-05 10:51
@bdoury - was it with drawio for you too?

**Comment by bdoury** [comment] 2018-10-05 11:11
@jasongrout, No it was not. To me it looks like the issue started while I was trying open a connection using cx_Oracle. After restarting my python environment and jupyterlab, the issue disappeared and I was not able to reproduce it. Sorry that I cannot be more specific.

**Comment by johntiger1** [comment] 2018-10-07 02:14
I can also reproduce the error via Amazon EC2 and JupyterLab.

**Comment by Zohaggie** [comment] 2018-10-24 21:20
I sometimes get this if I am returning to a notebook that has been running for some time, particularly if I am working on my Windows 10 laptop. I have found that if I open the same notebook again in a new window then it fixes the problem, and I can then close the newly opened notebook and continue working in the previously opened one.

**Comment by shak360** [comment] 2018-11-10 04:33
I fixed this by simple closing and opening again. I can't really find the root cause of the issue. I did have the notebook and Jupyter lab open for over 2 days which may have contributed to that error.

**Comment by zodoctor** [comment] 2018-11-27 17:37
This happened to me a few times, and the problem fixed itself after a while from my laptop disconnecting and reconnecting to wifi.  I essentially closed my laptop and opened it again a few times over the span of a few hours and eventually the notebook was able to reconnect and none of my work was lost. This definitely isn't a fix to the issue, but if you're in a pinch and worried you'll lose work, give this a try.

**Comment by jonnor** [comment] 2019-01-06 19:06
I just ran into this issue. Possibly also from reconnecting wifi and/or laptop suspend.

IHowever, after doing "Download .ipynb" (which got me a few hours old version) the issue somehow resolved itself, the next "Save" was successful and stored the latest version. So this is a possible workaround to not loose any work. Please vote up/down if this works for you.

**Comment by RiskofStorm** [comment] 2019-01-11 09:39
I just ran sometimes at this issue. Restart Jupyter lab was work just fine. Just copy-paste all the code on temp file.
Now it seem my brain turned on and I found my **NoJS addon blocked jupyter lab**. 

Console log error:
```
[W 12:29:23.308 LabApp] Could not determine jupyterlab build status without nodejs
```

**Comment by cbeauhilton** [comment] 2019-01-21 13:16
> I just ran into this issue. Possibly also from reconnecting wifi and/or laptop suspend.
> 
> IHowever, after doing either
> A) "Download .ipynb" (which got me a few hours old version) or B) "Make a copy" (opens old version in new window) the issue somehow resolved itself. The next "Save" was successful and stored the latest version. Maybe it updated the token somehow? So this is a _possible_ workaround to avoid losing work.

Just want to confirm that "Download .ipynb" allowed the next save to work, as for @jonnor . I left the notebook open over the weekend on a Windows 10 laptop.

**Comment by nalagoa** [comment] 2019-02-02 01:10
@Zohaggie the workaround you provided works flawlessly. Thanks!

**Comment by labarba** [comment] 2019-03-03 21:58
`'_xsrf' argument missing from POST` error just happened to me, running locally on my Mac. 

The notebook wouldn't save, then I got "Kernel error" when trying to restart the kernel. I downloaded as .ipynb, but when opening that notebook, it gave the same error. It also didn't have my last work on a long markdown cell with lots of math. 

My Jupyter session had been running for several days, and I had that notebook open for at least 3 days—fortunately, pushing my work to GitHub. Only one markdown cell lost, but I copied to clipboard before exiting.

**Comment by MarthinusBosman** [comment] 2019-03-06 15:38
Just had this error. What worked for me was to open a different notebook. Then save works for everything again.

**Comment by ellisonbg** [comment] 2019-03-06 16:00
Thanks everyone for the comments here, hopefully that will help us to debug it.

**Comment by emirkmo** [comment] 2019-03-06 16:17
I just received this error. Working on jupyter notebook locally which has been running for several days. 

I had pressed save manually and naively thought perhaps closing and reopening from a save would fix the issue. However I lost several hours of work as the notebook reverted to one from a few hours ago.

I was wondering if the manual saves could be found anywhere in the log or am I SOL?

Using safari 12.0 Mac OS Sierra with uBlock Origin extension running, in case this is somehow due to the browser. (However these notebooks are all local.)

**Comment by ian-r-rose** [comment] 2019-03-06 16:19
@afshin Is it possible that this problem will be fixed by https://github.com/jupyterlab/jupyterlab/pull/6005/commits/8626663c62cb63f8510d4453a3ed83e9159a91d8?

**Comment by afshin** [comment] 2019-03-11 21:10
It is *possible*, yes. Let's loop back when that PR is in.

**Comment by pboulos** [comment] 2019-04-03 01:01
I've encountered the same error, the notebook had been open for a few days, and the error appeared during a routine autosave.

The notebook in question was dealing with some map data visualisation. It happened during a WiFi connection drop as others mentioned here, however, my notebook was entirely local.

**Comment by jasongrout** [comment] 2019-04-17 17:00
Can you try now that the 1.0a3 prerelease has been released?

**Comment by notuntoward** [comment] 2019-05-20 18:26
I got this error on Firefox when I accidentally deleted the Jupyterlab browser tab and then restored it with Ctrl-Shift-T ("Undo the close of a window.").

**Comment by Pombalino** [comment] 2019-05-22 16:35
Encountered the same issue on a local notebook that'd been open for only a few hours. Jupyter version 4.4.0. My code messed only with local files and the error came up while I was out for lunch, Notebook was idle. Had trouble with restarting Kernel as well.

**Comment by blink1073** [comment] 2019-05-29 11:39
For reference, this is the PR that should have fixed the behavior: https://github.com/jupyterlab/jupyterlab/pull/6141.  It will be in the next (alpha 4) release.

**Comment by lorenzznerol** [comment] 2019-07-12 08:19
Good news.

### --------------> **Just press F5 in the browser window.** <----------------

Worked for Jupyter notebook using Edge, Windows 10 Pro, 64bit, anaconda prompt still open of course.

The version of the notebook server is: 5.7.4
The server is running on this version of Python: Python 3.7.1

It reloaded the page for quite a long time, exactly the time it would need to open the file at a fresh start as it is quite large. When it finally reappeared, any even unchanged changes of the last seconds were still there. This includes changes where I could not save anymore due to the  "_xsrf' argument missing from POST" error. So this is not a reaload of the file, but just of the page. All of the objects that I had loaded were also still in memory.

p.s.: Of course, at first I have downloaded the file as .ipynb and also as html for being safe in any case.

**Comment by ghuname** [comment] 2019-08-12 06:53
I confirm that lorenzznerol's solution is working.

**Comment by alfredsasko** [comment] 2019-08-13 07:46
Guys is there any way to recover lost work after closing the browser? I got the same bug and work further for 3 days, autosave was not generated, closed browser and opened it again.

**Comment by bumi001** [comment] 2019-09-02 11:42
I am using Jupyterhub with Jutyter lab. I see that the browser is making a request to /user/*****/api/sessions and the cookie sent has the _xsrf set to a string. However, the server responds with:
{"message": "'_xsrf' argument missing from POST", "reason": null}

Not sure if the server is expecting the _xsrf string as part of the json object.

**Comment by bruno-pinheiro** [comment] 2019-09-09 16:07
I experienced the same issue today. I'm using jupyter lab with python 3.6 in a conda environment. My only way was to download de .dio file, open it on draw.io online and them export to png.

**Comment by soerendip** [comment] 2019-09-18 17:07
Same here, jupyter-lab was running overnight. Logged in remotely in the meantime to see the current state. Then back in my office, continuing to work on it, the error appeared out of the blue.
 
Python 3.7.4
  - jupyter_client=5.3.1=py_0
  - jupyter_core=4.4.0=py_0
  - jupyterlab=1.0.2=py37hf63ae98_0
  - jupyterlab_server=1.0.6=py_0

**Comment by paedrik** [comment] 2019-09-23 20:34
I had this problem as well and lost my data. 

However, I think my problem was that that the directory I was in in the parent jupyter browser session looked messed up showing 'Self%20Study' instead of just 'Self Study'. 

I coudn't create a new file either and was getting this same "'_xsrf' argument missing from POST" error. 
I didn't restart the session. I clicked on the parent directory and back into the 'Self Study' directory and that fixed the error. Unfortunately, not before having lost my work.

Hope that helps someone.

**Comment by kostrykin** [comment] 2019-10-07 11:50
The following solution was the only which worked for me without losing my work:

> Just open another notebook on the same kernel, and the issue is magically gone; you can again save the notebooks that were previously showing the _xsrf error.

Credits go to [https://stackoverflow.com/a/55601395/1444073]()

**Comment by billtubbs** [comment] 2019-11-15 19:37
I have this problem today for the first time.  Can't save notebook, rename it, run it or restart the kernel.  The solution of opening another notebook with the same kernel doesn't work in my case either.  It says "An error occurred when opening notebook. '_xsrf' argument missing from POST."

The recent terminal readout looks something like this:

```
[W 11:27:04.650 NotebookApp] 403 POST /api/sessions (127.0.0.1): '_xsrf' argument missing from POST
[W 11:27:04.650 NotebookApp] '_xsrf' argument missing from POST
[W 11:27:04.650 NotebookApp] 403 POST /api/sessions (127.0.0.1) 1.25ms referer=http://localhost:8888/notebooks/Documents/.../Untitled.ipynb?kernel_name=conda-env-torch-py
```

At the moment my only option is to start a new jupyter browser tab, reopen the notebook and manually copy across all recent changes I made.

Mac OS X 10.13.6

**Comment by onetwoview** [comment] 2019-11-26 09:44
I've had the same thing happening, also after using the cx_Oracle module in Jupyter Notebook. The issue disappeared after restarting Jupyter Notebook.

**Comment by chucknotech** [comment] 2019-12-27 07:54
Hi
I just faced the same issue. It wasnt allowing a Save or a New File creation with the error message - '_xsrf' argument missing from POST

One quick dirty way to manage the situation was:
a. Right click on the existing browser tab
b. Click Duplicate
c. It opened up the exact same contents and lines of code etc
d. Since this was opened up now and we are immediately saving it, there is probably very less opportunity for the token to change (refer to comments above from blink1073) and thus, I was able to conduct both actions - File Save, and New File

Hope this helps.

**Comment by ThomasAJ05** [comment] 2020-01-12 07:37
chucknotech no good for me. I received a 'forbidden' when trying to duplicate.

1. Is anyone working on this problem - I cannot tell from the posts here. (Issue opened 2 years ago)
2.  I wasn't doing anything 'fancy' - just working on a not very long notebook with ALL resources on my laptop. Windows 10 and Chrome.
3. Luckily I copied each cell to notepad so I could recreate the notebook..
4. Should the developers read this I highly recommend that the faint brown error message that appears in the top right hand area of notebook be replaced by an 'in your face browser type notification message or better still a custom Javascipt or similar with bold red writing'.  I have no idea how long the message had been there but after I logged out of Jupyter and then restarted all and opened the notebook it was last saved yesterday. Please consider.

**Comment by chucknotech** [comment] 2020-01-12 14:31
Not sure what your exact issue is. My previous solution was just quick and dirty. You have to consider what your environments are. For example, my problem was related to tornados. I uninstalled Anaconda and reinstalled the same and most of the problems were solved. If you want to test out without the uninstall and reinstall, here are few solutions at the Anaconda prompt:
a. pip install tornado --5.1.1 (please check out exact command)
If its a tornado problem (if its a kernel connection issue, mostly its a tornado issue)

**Comment by lorenzznerol** [comment] 2020-01-12 15:46
F5 is all you need, please see my comment in summer 2019. I do not know why I was downvoted for this, as it clearly worked for me, and one other person could confirm this as well. It could be that there were downvotes from people who did not try it, because they did not leave any comments. I cannot guarantee that F5 is always working, of course, but it rather seems that there are downvotes without experience. If that is the case, it does not shed a good light on them. If it is not the case, they still should have dropped a comment and explain their downvote.

**Comment by durandg12** [comment] 2020-02-05 14:18
> I sometimes get this if I am returning to a jupyter notebook (not lab) that has been running for some time, particularly if I am working on my Windows 10 laptop. I have found that if I open the same notebook again in a new window then it fixes the problem, and I can then close the newly opened notebook and continue working in the previously opened one.

The problem just happened to me, and this solution worked for me. Thanks @ChrisPalmerNZ !

**Comment by XFengwei** [comment] 2020-02-11 15:13
The only way that I can come up with is to restart Jupyter and open the same Jupyter file and copy the unsaved contents into the just-open file. Finish, and shut the previous one down

**Comment by soerendip** [comment] 2020-02-14 22:56
Got this with jupyter lab and the Diagram editor jupyterlab-drawio when trying to save a drawing.

**Comment by jgmeyerucsd** [comment] 2020-03-02 16:09
I accidentally fixed this in windows by going to the anaconda prompt and typing 'control+x'. I meant to type 'control+c' to kill the process but then the process started printing that is was saving the files and the '_xrsf missing from post' at the top of the notebooks disappeared...

**Comment by Abdelgo** [comment] 2020-03-06 22:07
There is a method that you could try that works for me, you keep open your Notebook that you cannot save (to not lost your work), then go on Jupyter Console where you can navigate through you files, go to the folder where you have your notebook select the notebook facing this issue, open it on another page, you let it until the kernel is connected then you can close this new window. once you come to your old Notebook you will find that the issue is fixed. Hope that it helps

**Comment by Judape** [comment] 2020-03-26 12:37
Easy solution:

1. Go to the prompt/terminal where you first opened the notebook. 
2. Copy the URL link to login with a token when you connect for the first time. It should look like this

                http://localhost:8888/?token=f1a75b69989e62e...

3. Paste the link into a new tab in your browser where you're working and close the old "Home" one. Everything should work now :)

**Comment by youweiliang** [comment] 2020-03-27 07:00
The problem is a nightmare. I lost my work.

**Comment by jolespin** [comment] 2020-04-09 18:01
@youweiliang  I lost mine.  It just started happening randomly.

**Comment by emanuelef** [comment] 2020-06-11 09:15
Similar issue for me (running JupyterLab 2.1.4). 
In my case I'm getting "The network connection was lost." message, but I'm able to run the kernel, add new notebooks and basically everything apart from saving that file.

**Comment by briancullinan** [comment] 2020-09-06 04:43
This security is ridiculous. It doesn't do anything for anyone.

**Comment by bumi001** [comment] 2021-01-09 17:54
Assuming that you are running Jupyterlab behind a reverse proxy, you need to take the _xsrf cookie value and set the header X-Xsrftoken. For example, in the context of openresty you could do:

     rewrite_by_lua_block {
      local xsrf = ngx.var.cookie__xsrf;
      ngx.req.set_header("X-Xsrftoken", xsrf);
    }

Doing the above works for me.

**Comment by dario-passos** [comment] 2021-02-20 21:20
The solution I came across seems too simple but it worked. Go to the /tree aka Jupyter home page and refresh the browser. Worked.

**Comment by dario-passos** [comment] 2021-02-20 21:22
When this kind of error happens in Jupyter (not Jupyterlab), I just go to the /tree aka Jupyter home page and refresh the browser

**Comment by stu16291** [comment] 2021-02-20 22:30
> 
> 
> When this kind of error happens in Jupyter (not Jupyterlab), I just go to the /tree aka Jupyter home page and refresh the browser

This thread is so long that no one can read it anymore ;), see the ["just press F5" answer of summer 2019](https://github.com/jupyterlab/jupyterlab/issues/3506#issuecomment-510796879). It is probably only working in Jupyter notebook, while the question is about jupyterlab, else I do not understand the many downvotes.

I repeated the answer again at https://github.com/jupyterlab/jupyterlab/issues/3506#issuecomment-573427825.

**Comment by lorenzznerol** [comment] 2021-02-20 22:34
> 
> 
> When this kind of error happens in Jupyter (not Jupyterlab), I just go to the /tree aka Jupyter home page and refresh the browser

This thread is so long that no one can read it anymore ;), see the ["just press F5" comment of summer 2019](https://github.com/jupyterlab/jupyterlab/issues/3506#issuecomment-510796879). It is probably only working in Jupyter notebook, while the question is about jupyterlab, else I do not understand the many downvotes.

I repeated the solution again at https://github.com/jupyterlab/jupyterlab/issues/3506#issuecomment-573427825.

**Comment by cchwala** [comment] 2021-04-24 19:17
I had the same problem with saving notebooks. I use jupyterlab on a remote machine via ssh port-forwarding. I have the jupyterlab server running in a screen session for several months on this server. The terminal output of jupyterlab said something about "notebook not trusted".

So, following [this SO answer](https://stackoverflow.com/a/44943805/356463) I did
```
jupyter trust notebook-name.ipynb
```

Afterwards I was able to save my notebook without problems.

**Comment by briancullinan** [comment] 2021-04-25 14:50
Security should be removed from storage. The whole point is to prevent some
drive by website from executing local notebooks. Notebooks could be saved
in local storage and synchronized and versioned like Google Docs does in
offline mode. Then security can focus on only executing, by requesting a
token when the notebook is executed you don't lose any work saving and
coding it.

**Comment by cchwala** [comment] 2021-06-25 13:09
Update: What I wrote above (trusting the notebook) did not help with the problem of saving the notebook.

But since I switched to another VPN for connecting to the remote machine, the problem has gone away. Hence, this might have something to do with how you connect to the remote machine. The VPN I use now tunnels all traffic, the VPN is used before did only set up some very specifc tunnels at specific ports.

**Comment by chogg** [comment] 2022-09-08 03:16
I see a lot of workarounds here.

 I wonder how this can be fixed in the code base? What is the ideal behaviour? Presumably, you can always save the notebook and this error doesn’t come up (or if it does, the solution is clearer to the user). I’m new to the community, so I don’t know how to get agreement on the solution.

**Comment by afshin** [comment] 2022-09-08 13:53
@chogg, sorry that you had a bad experience. Do you believe this specific issue affecting you, though?

There hasn't been any activity on this thread in over a year and I am wondering if you're experiencing the issue referenced here or some other issue. Does this issue exist on versions of that have come out since this thread was first opened in 2018 or last commented on in 2021?

If so, please feel free to open a new issue so that it does not get lost in the noise!

**Closed by afshin** 2022-09-08 13:53 UTC
Labels: bug, status:Needs Info, pkg:services
