### ISSUE TITLE
Notebook with kotlin-jupyter kernel works in notebook and console, but not lab

### ISSUE THREAD

**Issue by apatrida** [jupyterlab/jupyterlab#1604] opened 2017-02-03 04:00 UTC
I am using the latest kotlin-jupyter kernel an it runs fine in jupyter notebook, and jupyter console.  Running lab starts the notebook and the server, but then execution of lines just silently does nothing.  A protocol difference or where else I can look for more information?

```
MacApatrida:~ jminard$ jupyter lab --debug
[D 00:58:27.133 LabApp] Searching [u'/Users/jminard', '/Users/jminard/.jupyter', '/Users/jminard/anaconda/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 00:58:27.133 LabApp] Looking for jupyter_config in /etc/jupyter
[D 00:58:27.134 LabApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 00:58:27.134 LabApp] Looking for jupyter_config in /Users/jminard/anaconda/etc/jupyter
[D 00:58:27.134 LabApp] Looking for jupyter_config in /Users/jminard/.jupyter
[D 00:58:27.134 LabApp] Looking for jupyter_config in /Users/jminard
[D 00:58:27.135 LabApp] Looking for jupyter_notebook_config in /etc/jupyter
[D 00:58:27.135 LabApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 00:58:27.135 LabApp] Looking for jupyter_notebook_config in /Users/jminard/anaconda/etc/jupyter
[D 00:58:27.136 LabApp] Loaded config file: /Users/jminard/anaconda/etc/jupyter/jupyter_notebook_config.json
[D 00:58:27.136 LabApp] Looking for jupyter_notebook_config in /Users/jminard/.jupyter
[D 00:58:27.136 LabApp] Looking for jupyter_notebook_config in /Users/jminard
[D 00:58:27.142 LabApp] [nb_conda_kernels] refreshing conda info
[D 00:58:27.858 LabApp] [nb_conda_kernels] refreshing conda kernelspecs
[I 00:58:27.859 LabApp] [nb_conda_kernels] enabled, 2 kernels found
[I 00:58:28.545 LabApp] ✓ nbpresent HTML export ENABLED
[W 00:58:28.545 LabApp] ✗ nbpresent PDF export DISABLED: No module named nbbrowserpdf.exporters.pdf
[I 00:58:28.545 LabApp] JupyterLab alpha preview extension loaded from /Users/jminard/anaconda/lib/python2.7/site-packages/jupyterlab
[I 00:58:28.551 LabApp] [nb_conda] enabled
[I 00:58:28.625 LabApp] [nb_anacondacloud] enabled
[I 00:58:28.631 LabApp] Serving notebooks from local directory: /Users/jminard
[I 00:58:28.631 LabApp] 0 active kernels
[I 00:58:28.631 LabApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 00:58:28.631 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[D 00:58:28.647 LabApp] 200 GET /api/contents/?content=1&1486094308523 (::1) 12.97ms
[D 00:58:28.991 LabApp] Using contents: services/contents
[D 00:58:29.006 LabApp] 304 GET /lab (::1) 23.89ms
[D 00:58:29.092 LabApp] 304 GET /lab/main.css (::1) 1.11ms
[D 00:58:29.095 LabApp] 304 GET /lab/loader.bundle.js (::1) 1.06ms
[D 00:58:29.096 LabApp] 304 GET /lab/main.bundle.js (::1) 0.83ms
[D 00:58:29.142 LabApp] 304 GET /static/components/MathJax/MathJax.js?config=TeX-AMS_HTML-full,Safe&delayStartupUntil=configured (::1) 0.77ms
[D 00:58:29.578 LabApp] 304 GET /static/components/MathJax/config/TeX-AMS_HTML-full.js?rev=2.6.0 (::1) 1.13ms
[D 00:58:30.948 LabApp] 200 GET /api/contents/?content=1&1486094310922 (::1) 14.10ms
[D 00:58:31.140 LabApp] Found kernel kotlin in /Users/jminard/.ipython/kernels
[D 00:58:31.144 LabApp] Native kernel (python2) available from /Users/jminard/anaconda/lib/python2.7/site-packages/ipykernel/resources
[D 00:58:31.144 LabApp] Found kernel kotlin in /Users/jminard/.ipython/kernels
[D 00:58:31.144 LabApp] Native kernel (python2) available from /Users/jminard/anaconda/lib/python2.7/site-packages/ipykernel/resources
[D 00:58:31.145 LabApp] 200 GET /api/kernelspecs?1486094311135 (::1) 5.91ms
[D 00:58:31.147 LabApp] 200 GET /api/terminals?1486094311137 (::1) 0.71ms
[D 00:58:31.266 LabApp] 304 GET /lab/fcad2f97acb3c868bd1ca7629d36d80e.svg (::1) 0.84ms
[D 00:58:31.268 LabApp] 304 GET /lab/93441bee5fcf0a095b35aa85f722b06c.svg (::1) 0.66ms
[D 00:58:31.269 LabApp] 304 GET /lab/26a0370f727f4667dfbf94b8ec576dc4.svg (::1) 0.65ms
[D 00:58:31.271 LabApp] 304 GET /lab/2b609d364e2e1d67ba33a81c58d9eb8a.svg (::1) 0.78ms
[D 00:58:31.321 LabApp] 200 GET /api/sessions?1486094311316 (::1) 1.59ms
[D 00:58:31.333 LabApp] 200 GET /api/contents/?content=1&1486094311320 (::1) 10.69ms
[D 00:58:31.360 LabApp] 304 GET /static/components/MathJax/config/Safe.js?rev=2.6.0 (::1) 0.86ms
[W 00:58:31.409 LabApp] No such file or directory: test-kotlin 2.ipynb
[W 00:58:31.410 LabApp] 404 GET /api/contents/test-kotlin%202.ipynb?1486094311401 (::1) 5.35ms referer=http://localhost:8888/lab
[D 00:58:31.472 LabApp] 304 GET /lab/e6cf7c6ec7c2d6f670ae9d762604cb0b.woff2 (::1) 0.95ms
[D 00:58:33.949 LabApp] 200 GET /api/contents/?content=1&1486094313925 (::1) 9.16ms
[D 00:58:33.951 LabApp] 200 GET /api/terminals?1486094313933 (::1) 0.59ms
[D 00:58:33.952 LabApp] 200 GET /api/sessions?1486094313936 (::1) 0.83ms
[D 00:58:33.953 LabApp] 200 GET /api/sessions?1486094313926 (::1) 0.61ms
[D 00:58:33.954 LabApp] 200 GET /api/terminals?1486094313939 (::1) 0.54ms
[I 00:58:34.013 LabApp] Creating new notebook in /
[D 00:58:34.015 LabApp] Saving /Users/jminard/Untitled21.ipynb
[D 00:58:34.024 LabApp] 201 POST /api/contents/?1486094314005 (::1) 11.95ms
[D 00:58:34.046 LabApp] 200 GET /api/contents/?content=1&1486094314026 (::1) 13.02ms
[D 00:58:34.951 LabApp] 200 GET /api/contents/?content=1&1486094314938 (::1) 9.30ms
[D 00:58:35.930 LabApp] 200 GET /api/sessions?1486094315919 (::1) 0.74ms
[D 00:58:35.932 LabApp] 200 GET /api/terminals?1486094315925 (::1) 0.72ms
[D 00:58:36.278 LabApp] 200 GET /api/sessions?1486094316274 (::1) 0.94ms
[D 00:58:36.280 LabApp] 200 GET /api/terminals?1486094316276 (::1) 0.64ms
[D 00:58:36.943 LabApp] 200 GET /api/contents/?content=1&1486094316923 (::1) 11.17ms
[D 00:58:36.954 LabApp] 200 GET /api/contents/?content=1&1486094316941 (::1) 9.81ms
[D 00:58:36.964 LabApp] 200 GET /api/contents/?content=1&1486094316923 (::1) 9.73ms
[D 00:58:38.934 LabApp] Found kernel kotlin in /Users/jminard/.ipython/kernels
[D 00:58:38.934 LabApp] Native kernel (python2) available from /Users/jminard/anaconda/lib/python2.7/site-packages/ipykernel/resources
[D 00:58:38.934 LabApp] Found kernel kotlin in /Users/jminard/.ipython/kernels
[D 00:58:38.934 LabApp] Native kernel (python2) available from /Users/jminard/anaconda/lib/python2.7/site-packages/ipykernel/resources
[D 00:58:38.935 LabApp] 200 GET /api/kernelspecs?1486094318924 (::1) 2.37ms
[D 00:58:39.943 LabApp] 200 GET /api/contents/?content=1&1486094319920 (::1) 9.65ms
[D 00:58:40.547 LabApp] Renaming checkpoint /Users/jminard/.ipynb_checkpoints/Untitled21-checkpoint.ipynb -> /Users/jminard/.ipynb_checkpoints/kotlin-test-1-checkpoint.ipynb
[D 00:58:40.548 LabApp] 200 PATCH /api/contents/Untitled21.ipynb?1486094320541 (::1) 2.58ms
[D 00:58:40.557 LabApp] 200 GET /api/contents/kotlin-test-1.ipynb?type=notebook&content=1&1486094320551 (::1) 2.45ms
[D 00:58:40.581 LabApp] Found kernel kotlin in /Users/jminard/.ipython/kernels
[D 00:58:40.581 LabApp] Native kernel (python2) available from /Users/jminard/anaconda/lib/python2.7/site-packages/ipykernel/resources
[D 00:58:40.582 LabApp] Starting kernel: [u'java', u'-jar', u'/Users/jminard/.ipython/kernels/kotlin/kotlin-jupyter-kernel-0.3.0.jar', u'/Users/jminard/Library/Jupyter/runtime/kernel-8d68e0fd-fc73-4b34-b408-898f5adba2ff.json', u'-cp=/Users/jminard/.ipython/kernels/kotlin/kotlin-stdlib-1.1.0-beta-38.jar:/Users/jminard/.ipython/kernels/kotlin/jupyter-lib-0.3.0.jar:/Users/jminard/.ipython/kernels/kotlin/annotations-13.0.jar']
[D 00:58:40.588 LabApp] Connecting to: tcp://127.0.0.1:49711
[I 00:58:40.589 LabApp] Kernel started: 8d68e0fd-fc73-4b34-b408-898f5adba2ff
[D 00:58:40.589 LabApp] Kernel args: {'kernel_name': u'kotlin', 'cwd': u'/Users/jminard'}
[D 00:58:40.591 LabApp] 201 POST /api/sessions?1486094320553 (::1) 32.84ms
[D 00:58:40.657 LabApp] 200 GET /api/contents/kotlin-test-1.ipynb/checkpoints?1486094320651 (::1) 1.77ms
[D 00:58:40.659 LabApp] 200 GET /api/contents/kotlin-test-1.ipynb/checkpoints?1486094320652 (::1) 0.88ms
[D 00:58:40.688 LabApp] 200 GET /api/kernels/8d68e0fd-fc73-4b34-b408-898f5adba2ff?1486094320673 (::1) 0.98ms
[D 00:58:40.702 LabApp] 200 GET /api/contents/?content=1&1486094320684 (::1) 12.09ms
[D 00:58:40.704 LabApp] 200 GET /api/contents/kotlin-test-1.ipynb/checkpoints?1486094320696 (::1) 1.03ms
[D 00:58:40.712 LabApp] Initializing websocket connection /api/kernels/8d68e0fd-fc73-4b34-b408-898f5adba2ff/channels
[D 00:58:40.714 LabApp] Requesting kernel info from 8d68e0fd-fc73-4b34-b408-898f5adba2ff
[D 00:58:40.714 LabApp] Connecting to: tcp://127.0.0.1:49708
[main] INFO ikotlin - Starting server: KernelConfig(ports=[49712, 49708, 49711, 49710, 49709], transport=tcp, signatureScheme=hmac-sha256, signatureKey=319c4df4-4d50-48e5-adc9-079b35ca93ee, pollingIntervalMillis=100, classpath=[/Users/jminard/.ipython/kernels/kotlin/kotlin-stdlib-1.1.0-beta-38.jar, /Users/jminard/.ipython/kernels/kotlin/jupyter-lib-0.3.0.jar, /Users/jminard/.ipython/kernels/kotlin/annotations-13.0.jar])
[main] INFO ikotlin - start listening
[main] INFO ikotlin - Starting kotlin repl 1.1.0-beta-38
[D 00:58:41.146 LabApp] 200 GET /api/sessions?1486094321141 (::1) 1.03ms
[D 00:58:41.149 LabApp] 200 GET /api/terminals?1486094321142 (::1) 0.70ms
[D 00:58:41.707 LabApp] 200 GET /api/contents/?content=1&1486094321693 (::1) 10.60ms
[main] INFO ikotlin - Using classpath:
/Users/jminard/anaconda/jre/lib/charsets.jar
/Users/jminard/anaconda/jre/lib/jce.jar
/Users/jminard/anaconda/jre/lib/jsse.jar
/Users/jminard/anaconda/jre/lib/management-agent.jar
/Users/jminard/anaconda/jre/lib/resources.jar
/Users/jminard/anaconda/jre/lib/rt.jar
/Users/jminard/anaconda/jre/lib/ext/cldrdata.jar
/Users/jminard/anaconda/jre/lib/ext/dnsns.jar
/Users/jminard/anaconda/jre/lib/ext/jaccess.jar
/Users/jminard/anaconda/jre/lib/ext/localedata.jar
/Users/jminard/anaconda/jre/lib/ext/nashorn.jar
/Users/jminard/anaconda/jre/lib/ext/sunec.jar
/Users/jminard/anaconda/jre/lib/ext/sunjce_provider.jar
/Users/jminard/anaconda/jre/lib/ext/sunpkcs11.jar
/Users/jminard/anaconda/jre/lib/ext/zipfs.jar
/Users/jminard/.ipython/kernels/kotlin/kotlin-jupyter-kernel-0.3.0.jar
/Users/jminard/.ipython/kernels/kotlin/kotlin-stdlib-1.1.0-beta-38.jar
/Users/jminard/.ipython/kernels/kotlin/jupyter-lib-0.3.0.jar
/Users/jminard/.ipython/kernels/kotlin/annotations-13.0.jar
[D 00:58:42.366 LabApp] Received kernel info: {u'protocol_version': u'5.0', u'language_version': u'1.1.0-beta-38', u'language_info': {u'file_extension': u'kt', u'name': u'kotlin'}, u'language': u'Kotlin'}
[D 00:58:42.367 LabApp] Opening websocket /api/kernels/8d68e0fd-fc73-4b34-b408-898f5adba2ff/channels
[D 00:58:42.367 LabApp] Connecting to: tcp://127.0.0.1:49708
[D 00:58:42.367 LabApp] Connecting to: tcp://127.0.0.1:49709
[D 00:58:42.368 LabApp] Connecting to: tcp://127.0.0.1:49710
[D 00:58:42.474 LabApp] 304 GET /lab/1.1.bundle.js (::1) 0.95ms
[D 00:58:42.714 LabApp] 200 GET /api/contents/?content=1&1486094322699 (::1) 10.20ms
[D 00:58:42.944 LabApp] 200 GET /api/contents/?content=1&1486094322922 (::1) 11.95ms
[D 00:58:43.721 LabApp] 200 GET /api/contents/?content=1&1486094323707 (::1) 10.20ms
[D 00:58:43.924 LabApp] Found kernel kotlin in /Users/jminard/.ipython/kernels
[D 00:58:43.924 LabApp] Native kernel (python2) available from /Users/jminard/anaconda/lib/python2.7/site-packages/ipykernel/resources
[D 00:58:43.924 LabApp] Found kernel kotlin in /Users/jminard/.ipython/kernels
[D 00:58:43.924 LabApp] Native kernel (python2) available from /Users/jminard/anaconda/lib/python2.7/site-packages/ipykernel/resources
[D 00:58:43.927 LabApp] 200 GET /api/kernelspecs?1486094323917 (::1) 4.61ms
[D 00:58:43.934 LabApp] 200 GET /api/sessions?1486094323919 (::1) 0.95ms
[D 00:58:43.937 LabApp] 200 GET /api/terminals?1486094323926 (::1) 0.80ms
[D 00:58:43.941 LabApp] 200 GET /api/sessions?1486094323930 (::1) 0.75ms
[D 00:58:43.942 LabApp] 200 GET /api/terminals?1486094323935 (::1) 0.44ms
[D 00:58:44.729 LabApp] 200 GET /api/contents/?content=1&1486094324714 (::1) 10.44ms
[W 00:58:44.930 LabApp] No such file or directory: test-kotlin 2.ipynb
[W 00:58:44.930 LabApp] 404 GET /api/contents/test-kotlin%202.ipynb?1486094324920 (::1) 1.43ms referer=http://localhost:8888/lab
[I 00:58:44.940 LabApp] Uploading file to /test-kotlin 2.ipynb
[D 00:58:44.940 LabApp] Saving /Users/jminard/test-kotlin 2.ipynb
[D 00:58:44.947 LabApp] 201 PUT /api/contents/test-kotlin%202.ipynb?1486094324933 (::1) 8.34ms
[D 00:58:44.959 LabApp] 200 GET /api/contents/?content=1&1486094324935 (::1) 10.98ms
[D 00:58:44.960 LabApp] 200 GET /api/contents/test-kotlin%202.ipynb/checkpoints?1486094324948 (::1) 0.89ms
[D 00:58:45.736 LabApp] 200 GET /api/contents/?content=1&1486094325721 (::1) 10.65ms
[D 00:58:45.939 LabApp] 200 GET /api/contents/?content=1&1486094325919 (::1) 9.72ms
[D 00:58:45.941 LabApp] 200 GET /api/terminals?1486094325925 (::1) 0.81ms
[D 00:58:45.942 LabApp] 200 GET /api/sessions?1486094325920 (::1) 0.93ms
[D 00:58:46.293 LabApp] 200 GET /api/sessions?1486094326286 (::1) 1.26ms
[D 00:58:46.295 LabApp] 200 GET /api/terminals?1486094326288 (::1) 0.66ms
[D 00:58:46.743 LabApp] 200 GET /api/contents/?content=1&1486094326729 (::1) 10.42ms
[D 00:58:46.944 LabApp] 200 GET /api/contents/?content=1&1486094326918 (::1) 9.43ms
[D 00:58:46.954 LabApp] 200 GET /api/contents/?content=1&1486094326925 (::1) 9.40ms
[D 00:58:47.754 LabApp] 200 GET /api/contents/?content=1&1486094327738 (::1) 10.51ms
[D 00:58:48.759 LabApp] 200 GET /api/contents/?content=1&1486094328745 (::1) 10.75ms
[D 00:58:48.944 LabApp] 200 GET /api/contents/?content=1&1486094328925 (::1) 8.98ms
[D 00:58:49.770 LabApp] 200 GET /api/contents/?content=1&1486094329753 (::1) 11.63ms
[D 00:58:50.775 LabApp] 200 GET /api/contents/?content=1&1486094330760 (::1) 10.63ms
[D 00:58:51.149 LabApp] 200 GET /api/sessions?1486094331137 (::1) 0.90ms
[D 00:58:51.151 LabApp] 200 GET /api/terminals?1486094331146 (::1) 0.60ms
[D 00:58:51.782 LabApp] 200 GET /api/contents/?content=1&1486094331767 (::1) 10.78ms
[D 00:58:52.791 LabApp] 200 GET /api/contents/?content=1&1486094332777 (::1) 10.35ms
[D 00:58:52.935 LabApp] Initializing websocket connection /api/kernels/670747ee-b7d5-46fe-80c5-49b7583febbb/channels
[W 00:58:52.939 LabApp] 404 GET /api/kernels/670747ee-b7d5-46fe-80c5-49b7583febbb/channels?session_id=2a8b9c5715bbe96c79528de0068b9444&token=undefined (::1): Kernel does not exist: 670747ee-b7d5-46fe-80c5-49b7583febbb
[D 00:58:52.939 LabApp] Using contents: services/contents
[W 00:58:52.966 LabApp] 404 GET /api/kernels/670747ee-b7d5-46fe-80c5-49b7583febbb/channels?session_id=2a8b9c5715bbe96c79528de0068b9444&token=undefined (::1) 30.83ms referer=None
[D 00:58:53.801 LabApp] 200 GET /api/contents/?content=1&1486094333785 (::1) 11.05ms
[D 00:58:53.933 LabApp] 200 GET /api/sessions?1486094333917 (::1) 1.24ms
[D 00:58:53.935 LabApp] 200 GET /api/sessions?1486094333927 (::1) 1.06ms
[D 00:58:53.937 LabApp] 200 GET /api/terminals?1486094333927 (::1) 0.87ms
[D 00:58:53.938 LabApp] 200 GET /api/terminals?1486094333929 (::1) 0.79ms
[D 00:58:54.811 LabApp] 200 GET /api/contents/?content=1&1486094334795 (::1) 10.75ms
```

**Comment by blink1073** [comment] 2017-02-03 16:39
Hi @apatrida, it looks like the version 5.0 protocol should be supported by the kernel (which is what we use): https://github.com/ligee/kotlin-jupyter/search?utf8=%E2%9C%93&q=protocolVersion.  Are there any errors in the web console on the page?

**Comment by apatrida** [comment] 2017-02-04 14:52
no errors, no output.

**Comment by blink1073** [comment] 2017-02-04 15:04
I was afraid of that ;).  I'll install the kotlin kernel on Monday and try it out.

**Comment by blink1073** [comment] 2017-02-06 11:15
Ah, the issue is that we are expecting an `idle` status after every iopub message per the 5.0 spec: "Changed in version 5.0: Busy and idle messages should be sent before/after handling every request, not just execution."   The classic notebook is more lenient because it also supports older protocol versions.

http://jupyter-client.readthedocs.io/en/latest/messaging.html#kernel-status

**Comment by apatrida** [comment] 2017-02-06 14:27
ok, thanks, I'll go make the fix to the kotlin kernel.  thanks for pushing
me in the right direction.

**Comment by jtpio** [comment] 2023-05-25 14:48
Closing as the fix had to be implemented in the kotlin kernel: https://github.com/Kotlin/kotlin-jupyter

**Closed by jtpio** 2023-05-25 14:48 UTC
Labels: question, pkg:notebook
