### ISSUE TITLE
Output does not update after close and reopening Jupyterlab in the browser

### ISSUE THREAD

**Issue by Hoeze** [jupyterlab/jupyterlab#7901] opened 2020-02-20 16:47 UTC
## Description
Output does not update after close and reopening Jupyterlab in the browser

## Reproduce
1. Open JupyterLab in the browser
2. Run long-running task, e.g. Keras training
3. Close and re-open the browser page

## Expected behavior
Output should be cached and should continue after re-opening the browser page.

## Context

- Operating System and version: Anaconda
- Browser and version: Firefox 73
- JupyterLab version: 1.2.3

This is basically a copy of https://github.com/jupyter/jupyter/issues/83.

**Comment by vidartf** [comment] 2020-03-12 14:19
Closing as a duplicate of https://github.com/jupyterlab/jupyterlab/issues/2833

**Closed by vidartf** 2020-03-12 14:19 UTC
