### ISSUE TITLE
3.4.2: redundant `pre-commit` build dependency

### ISSUE THREAD

**Issue by kloczek** [jupyterlab/jupyterlab#12666] opened 2022-06-07 18:59 UTC
I'm using now patch like below:
```patch
--- a/setup.cfg~        2022-05-03 15:02:35.000000000 +0000
+++ b/setup.cfg 2022-05-11 03:54:40.009558735 +0000
@@ -52,7 +52,6 @@
     requests
     requests_cache
     virtualenv
-    pre-commit
 ui-tests = build

 [options.entry_points]
--- a/pyproject.toml~   2022-05-03 15:02:35.000000000 +0000
+++ b/pyproject.toml    2022-05-11 03:54:39.133558386 +0000
@@ -1,5 +1,5 @@
 [build-system]
-requires=["jupyter_packaging~=0.9,<2", "pre-commit"]
+requires=["jupyter_packaging~=0.9,<2"]
 build-backend = "jupyter_packaging.build_api"

 [license]

```
'pre-commit` is not used at all duting build. If it is CI that module should be part of the CI dependencies.

**Comment by jtpio** [comment] 2022-06-08 06:51
Thanks @kloczek.

Linking to https://github.com/jupyterlab/jupyterlab/issues/12575 which does the same observation.

**Comment by fcollonval** [comment] 2022-06-10 06:15
Closing as duplicate of #12575

**Closed by fcollonval** 2022-06-10 06:15 UTC
Labels: bug, tag:Build System
