### ISSUE TITLE
Shift-Enter on debug magic hides prompt, execution frozen

### ISSUE THREAD

**Issue by LunarLanding** [jupyterlab/jupyterlab#11027] opened 2021-09-08 10:57 UTC
## Description

Execution frozen, requiring  kernel restart, if shift+enter is used on debug cell.
This maybe did not happen before.

## Reproduce
 In cell:
  ```python
  def f():
      raise ValueError
  f()
  ```
Then run `%debug` in a new cell. Kernel is shown as executing as expected.
Then select prompt, and press `shift+enter`.
Prompt will be hidden; debug cannot be exited since it requires entering `exit()` at prompt.
Interrupting also does not unfreeze kernel.

## Expected behavior

Prompt not hidden on `shift-enter`; line sent to debug prompt.

## Context

- Operating System and version: Windows 10 on client,  Ubuntu 18.04.5 LTS on server
- Browser and version: Firefox 91.0.2 
- JupyterLab version: 3.1.10

**Comment by AnakinShieh** [comment] 2021-10-16 04:55
I have met the same issue, and it's quite annoying, wasting almost my whole day.

**Comment by krassowski** [comment] 2021-10-16 09:53
This is a duplicate of #8632 and was ultimately fixed by #10792 which was included in JupyterLab 3.2 released this week.

**Comment by krassowski** [comment] 2021-10-16 09:55
Confirmation that the reproduction instructions no longer lead to the issue in 3.2, and that the guard properly gets invoked:

![fixed-in-3 2](https://user-images.githubusercontent.com/5832902/137583137-985e6c43-b260-4caa-9de0-2a313e005371.gif)

**Closed by krassowski** 2021-10-16 09:55 UTC
Labels: bug, status:Duplicate, status:Answered
