### ISSUE TITLE
Jump in focus when cell with large output is re-executed

### ISSUE THREAD

**Issue by jorisvandenbossche** [jupyterlab/jupyterlab#1810] opened 2017-02-27 13:17 UTC
It's hard for such issues to look for existing ones, but I ran into the following 'wrong' behaviour:

- I have a cell with a large output, in this case a matplotlib figure
- I execute this -> all is fine
- I re-execute this -> the window jumps a few cells below (too far below so the actual next cell that is now selected is not visible. I numbered the cells below in the following gif)

![peek 2017-02-27 14-10](https://cloud.githubusercontent.com/assets/1020496/23362631/f53154a8-fcf6-11e6-84b2-722b3d43c7cd.gif)

When this exactly happens, depends on the exact circumstances. For example, I don't see it if I use a smaller figure that fits completely on the screen (eg `figsize=(5,5)`. I also don't see it if there are only a few cells after the cell in question.

Reported with Jupyterlab 0.16.2 from conda-forge, using Chrome on Ubuntu.

**Comment by jorisvandenbossche** [comment] 2017-02-27 13:30
Follow-up:

If there are *more* cells after the cell with large output I re-execute, there is even different behaviour (it first jumps to the same place as in the gif above (a few cells to the bottom), but then jumps back to the selected cell in focus -> which is also not the correct behaviour I think):

![peek 2017-02-27 14-20](https://cloud.githubusercontent.com/assets/1020496/23362885/1e2e1200-fcf8-11e6-8d46-f20103d0dd06.gif)

If there are *less* cells after the one I re-execute, I get also other behaviour (but in this case the correct I think, which is: select the next cell, but keep output in focus):

![peek 2017-02-27 14-25](https://cloud.githubusercontent.com/assets/1020496/23362985/9c58e8a8-fcf8-11e6-8b2d-4b4437183603.gif)

(note: in the end I scroll down manually to show that the next cell is in focus)

If you want the notebook from the gif: http://nbviewer.jupyter.org/gist/jorisvandenbossche/1d8baa3fe6550416e81cad7719093cca, but I thus varied the amount of cells after the figure.

**Comment by blink1073** [comment] 2017-02-27 16:27
Hi @jorisvandenbossche, thank you for the detailed report.  This is indeed a duplicate of https://github.com/jupyterlab/jupyterlab/issues/1526.

**Comment by jorisvandenbossche** [comment] 2017-02-27 16:32
Ah, I also commented in the other issue... Already forgot that :-) 
I suppose that the reason/fix is probably related, but note that the situation is slightly different: in the other issue I was executing the cell above the cell with large output, here I am re-executing the cell with large content itself (the first time I execute it is fine).

**Comment by blink1073** [comment] 2017-02-27 16:33
Fair enough, let's leave this open to make sure that [this](https://github.com/jupyterlab/jupyterlab/issues/1526#issuecomment-275724503) solves both problems.

**Closed** 2017-03-15 14:13 UTC
Labels: cat:Design and UX, component:Notebook, in progress
