### ISSUE TITLE
The main Dock Panel area does not change color to match JupyterLab theme

### ISSUE THREAD

**Issue by vabarbosa** [jupyterlab/jupyterlab#8652] opened 2020-07-06 23:52 UTC
## Description

When switching to JupyterLab Dark theme the main dock panel area remains white.

![image](https://user-images.githubusercontent.com/13156555/86668519-b46eae80-bfc0-11ea-8beb-8aec9f89b453.png)

&nbsp;  

This was discovered while working on [Elyra to support Dark Mode](https://github.com/elyra-ai/elyra/issues/625).

And it may possibly be similar to the issue being referenced here: https://github.com/jupyterlab/jupyterlab/issues/8365

If this is not the intended behavior and is a welcomed contribution to Jupyter Lab, I can take on this issue to work on it.

## Reproduce

1. Launch JupyterLab
1. Go to > Settings > JupyterLab Theme > JupyterLab Dark
1. Notice the white background for the main area

![image](https://user-images.githubusercontent.com/13156555/86668519-b46eae80-bfc0-11ea-8beb-8aec9f89b453.png)

## Expected behavior

The background of the main area to change to a dark color corresponding to the Dark Theme

## Context

- Operating System and version: macOS 10.15.5
- Browser and version: Firefox 77.0.1 (64-bit)
- JupyterLab version: Version 2.1.4

**Comment by lresende** [comment] 2020-07-07 18:42
We noticed this while validating dark theme on [Elyra](https://github.com/elyra-ai/elyra) and @vabarbosa had a workaround on our side, but this should be fixed on lab.

**Comment by jasongrout** [comment] 2020-07-07 19:07
Here is what it looks like for me in jlab 2.1.5, Firefox 78, macOS:
 
<img width="586" alt="Screen Shot 2020-07-07 at 11 56 13 AM" src="https://user-images.githubusercontent.com/192614/86829179-f6433780-c048-11ea-9767-d84bbab20d89.png">

It looks like the background color doesn't change between the dark and light theme, but the background color itself seems all right in either theme. Looks like for me, that color is inherited from the body: `background: var(--jp-layout-color3)`.

**Comment by ajbozarth** [comment] 2020-07-07 20:00
I did some research into this and discovered the root cause. It was previously raised in #5867 actually, lab sets the background color on the body. So if any css library imported in an extension also sets that css value then it'll override the lab theme. In the case for Elyra, it's our use of the Carbon css library that sets the background of the body. So the fix for this should be addressed as described in that PR, that is to move the theme value out of the body css to a more specific DOM element.

**Closed** 2024-07-08 10:54 UTC
