### ISSUE TITLE
Single click to open file

### ISSUE THREAD

**Issue by jianboy** [jupyterlab/jupyterlab#17028] opened 2024-12-03 05:08 UTC
### Problem

Single click to open file, such as vscode.

see this video:

https://github.com/user-attachments/assets/a94d66ec-b0bc-4e9b-82cf-3a91fc05a70e

**Comment by krassowski** [comment] 2024-12-03 09:15
@jianboy you can enable opening by single click in settings in JupyterLab 4.3.0 and newer.

`Settings Editor` → `File Browser` → `Navigate files and directories with single click`

This was implemented in https://github.com/jupyterlab/jupyterlab/pull/16598.

**Comment by JasonWeill** [comment] 2024-12-03 17:07
Closing as a duplicate of #14071.

**Closed by JasonWeill** 2024-12-03 17:07 UTC
Labels: enhancement, status:Needs Triage
