### ISSUE TITLE
Monospace/code text not rendered at the correct size in Markdown headers 

### ISSUE THREAD

**Issue by fndari** [jupyterlab/jupyterlab#5080] opened 2018-08-08 22:55 UTC
When used in headers, monospaced/code text, i.e. using the `` (backtick) syntax in Markdown, is rendered at the normal (text body) size, rather than at the expected header size. This seems to be happening only with JupyterLab; when opening the exact same notebook using "Launch Classic Notebook", the monospaced text is rendered at the correct, expected size.

EDIT: JupyterLab version is 0.32.1

Screenshots from a minimal example:

Using JupyterLab:
![jupyterlab-issue-header-1](https://user-images.githubusercontent.com/6341901/43868543-f37fbafc-9b22-11e8-99ba-0c0d3f9be34c.png)

Using Classic Notebook:
![jupyterlab-issue-header-2](https://user-images.githubusercontent.com/6341901/43868544-f3973966-9b22-11e8-9cae-5399c5923b6a.png)

The source (the same for both cases) is:

```md
# Testing `HistBook`
```

**Comment by Zsailer** [comment] 2018-08-16 23:27
Thanks for posting @fndari. 

I think this is a duplicate of Issue #4609 and was fixed in PR #4617.

**Closed** 2018-09-07 00:14 UTC
