### ISSUE TITLE
Customizable keyboard shortcut to comment lines of code

### ISSUE THREAD

**Issue by Jacques2101** [jupyterlab/jupyterlab#8882] opened 2020-08-21 17:20 UTC
Hi I'm always frustrated when I tried to comment codes. I use alt + mouse to select multiple lines but I would like to use alt + C or something like that. It seems that with an English keyboard, we can use alt + / but it is not working with a French keyboard on a Mac. 
Add this keyboard shortcut even for French keyboard would be great 
Thx

**Comment by ianhi** [comment] 2020-09-29 16:43
This is the same as https://github.com/jupyterlab/jupyterlab/issues/4778

**Comment by JasonWeill** [comment] 2024-03-12 16:21
Closing as duplicate of #4778

**Closed by JasonWeill** 2024-03-12 16:21 UTC
Labels: enhancement, tag:Keyboard
