### ISSUE TITLE
Allow Smooth Scrolling With Arrow Keys

### ISSUE THREAD

**Issue by H-Sorkatti** [jupyterlab/jupyterlab#12894] opened 2022-08-02 05:11 UTC
### Problem

I'd like to be able to scroll up and down the notebook freely using the arrow keys and not just shifting cell focus.

### Proposed Solution

In the original plain Jupyter notebooks, I can get the desired behaviour by executing the following:
```
%%javascript

Jupyter.keyboard_manager.command_shortcuts.remove_shortcut("up");
Jupyter.keyboard_manager.command_shortcuts.remove_shortcut("down");
```
This command is not working in JupyterLab.
Any solutions to this?

Thanks.

### Additional context
I'm on JupyterLab 3.4.4

**Comment by jweill-aws** [comment] 2022-08-04 17:27
The keyboard shortcut manager in JupyterLab has shortcuts for "Select Cell Above"/"Select Cell Below". You can override these to keys other than <kbd>Up</kbd> and <kbd>Down</kbd>. You can see this in the advanced settings editor under keyboard shortcuts: https://jupyterlab.readthedocs.io/en/stable/user/interface.html#keyboard-shortcuts

**Comment by H-Sorkatti** [comment] 2022-08-05 09:05
@jweill-aws 
I only found a gui interface for the keyboard shortcuts. 
I could not override the desired keys. when I try to edit them to a new key it ends up adding the new one to the default keys.

**Comment by jweill-aws** [comment] 2022-08-05 15:19
I also observed that with the most recent version of JupyterLab: If I click <kbd>ArrowUp</kbd> and choose another shortcut, the new shortcut is _added to_ the list, not replacing <kbd>ArrowUp</kbd>.

@krassowski is this a bug in the keyboard shortcuts editor?

**Comment by krassowski** [comment] 2022-08-05 16:11
Yes, that seems like a bug. Might be related to https://github.com/jupyterlab/jupyterlab/issues/12316. And annoyingly JSON editor is not working (https://github.com/jupyterlab/jupyterlab/issues/12891).

**Comment by jweill-aws** [comment] 2022-08-05 16:19
Resolving this as a duplicate of #12316 — once users can delete shortcuts, @H-Sorkatti will be able to make their browser's scrolling available again.

**Closed by jweill-aws** 2022-08-05 16:19 UTC
Labels: status:Duplicate, enhancement, status:Needs Triage
