### ISSUE TITLE
Option to copy file path when browsing in "files" tab

### ISSUE THREAD

**Issue by mikeyford** [jupyterlab/jupyterlab#4145] opened 2018-03-08 12:10 UTC
Hey there,

Really excited by the Jupyter Lab project. I have one small usability "wish" rather than an issue. I hope this is the right place.

When browsing files, it would be really great to have a "copy path" option in the right-click menu for a file, so I can easily specify which file I want to load in with my code.

Thanks for considering my request and keep up the great work :)

Mike

**Comment by ian-r-rose** [comment] 2018-03-08 15:27
Hi @mikeyford, thanks for the input! This is a duplicate of #4074, can we continue the discussion there?

**Closed by ian-r-rose** 2018-03-08 15:27 UTC
