### ISSUE TITLE
Jupyter Notebook Docker with M1 chip? 

### ISSUE THREAD

**Issue by bigtimecodersean** [jupyterlab/jupyterlab#12081] opened 2022-02-17 19:49 UTC
## Description

I am attempting to run a single cell RNA seq tutorial on my Macbook. I am running a (Python) Jupyter Labs notebook through a Docker container. 

Issue: 
- I have run many cells successfully. However, when I run certain cells, the kernel crashes. There are no error signals; the cell just doesn’t run and I need to re-run the whole notebook again.  These are not highly computationally expensive, (eg. A cell that is solely importing packages) and friends of mine have no problem running.
## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

Jupyter version: 6.4.5  Google Chrome Version 98

My machine details: 
- OS: macOS Big Sur Version 11.1
- Chip Apple M1
- Memory 16GB 

I have checked Activity Monitor, and my RAM usage is supposedly quite normal. I’ve exited all other apps and attempted to run the cell as well. 
 I’m curious what you think might be going on ? What other information would be helpful for me to provide?  Where else would be useful to ask this question?   Thanks 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>
$PATH:
	/Users/seanmcgowan/opt/miniconda3/bin
	/Users/seanmcgowan/opt/miniconda3/condabin
	/opt/homebrew/bin
	/opt/homebrew/sbin
	/Library/Frameworks/Python.framework/Versions/3.10/bin
	/usr/local/bin
	/usr/bin
	/bin
	/usr/sbin
	/sbin
	/Applications/Keybase.app/Contents/SharedSupport/bin

sys.path:
	/Users/seanmcgowan/opt/miniconda3/bin
	/Users/seanmcgowan/opt/miniconda3/lib/python39.zip
	/Users/seanmcgowan/opt/miniconda3/lib/python3.9
	/Users/seanmcgowan/opt/miniconda3/lib/python3.9/lib-dynload
	/Users/seanmcgowan/.local/lib/python3.9/site-packages
	/Users/seanmcgowan/opt/miniconda3/lib/python3.9/site-packages

sys.executable:
	/Users/seanmcgowan/opt/miniconda3/bin/python

sys.version:
	3.9.5 (default, May 18 2021, 12:31:01) 
	[Clang 10.0.0 ]

platform.platform():
	macOS-10.16-x86_64-i386-64bit

which -a jupyter:
	/Users/seanmcgowan/opt/miniconda3/bin/jupyter

pip list:
	Package                           Version
	--------------------------------- -------------------
	anaconda-client                   1.9.0
	anndata                           0.7.8
	anndata2ri                        1.0.6
	anyio                             3.5.0
	appnope                           0.1.2
	argon2-cffi                       20.1.0
	async-generator                   1.10
	attrs                             21.2.0
	Babel                             2.9.1
	backcall                          0.2.0
	backports.entry-points-selectable 1.1.1
	beautifulsoup4                    4.10.0
	bleach                            4.0.0
	brotlipy                          0.7.0
	certifi                           2021.10.8
	cffi                              1.14.6
	chardet                           4.0.0
	click                             8.0.3
	clyent                            1.2.2
	conda                             4.11.0
	conda-package-handling            1.7.3
	cryptography                      3.4.7
	cycler                            0.11.0
	dataclasses                       0.6
	debugpy                           1.4.1
	decorator                         5.1.0
	defusedxml                        0.7.1
	distlib                           0.3.4
	dunamai                           1.8.0
	entrypoints                       0.3
	filelock                          3.4.0
	get-version                       3.5.3
	gprofiler                         1.2.2
	gprofiler-official                1.0.0
	h5py                              3.6.0
	idna                              2.10
	importlib-metadata                4.8.1
	ipykernel                         6.4.1
	ipython                           7.27.0
	ipython-genutils                  0.2.0
	ipywidgets                        7.6.5
	jedi                              0.18.0
	Jinja2                            3.0.1
	joblib                            1.1.0
	json5                             0.9.6
	jsonschema                        3.2.0
	jupyter-client                    7.0.1
	jupyter-console                   6.4.0
	jupyter-core                      4.8.1
	jupyter-server                    1.13.5
	jupyterlab                        3.2.9
	jupyterlab-pygments               0.1.2
	jupyterlab-server                 2.10.3
	jupyterlab-widgets                1.0.0
	kiwisolver                        1.3.2
	llvmlite                          0.37.0
	MarkupSafe                        2.0.1
	matplotlib                        3.4.3
	matplotlib-inline                 0.1.2
	mistune                           0.8.4
	natsort                           8.1.0
	nbclassic                         0.3.5
	nbclient                          0.5.3
	nbconvert                         6.1.0
	nbformat                          5.1.3
	nest-asyncio                      1.5.1
	networkx                          2.6.3
	nltk                              3.6.5
	notebook                          6.4.5
	numba                             0.54.1
	numexpr                           2.8.1
	numpy                             1.20.3
	packaging                         21.0
	pandas                            1.3.4
	pandocfilters                     1.4.3
	parso                             0.8.2
	patsy                             0.5.2
	pexpect                           4.8.0
	pickleshare                       0.7.5
	Pillow                            8.4.0
	pip                               21.1.3
	pipenv                            2021.11.23
	platformdirs                      2.4.0
	prometheus-client                 0.11.0
	prompt-toolkit                    3.0.20
	ptyprocess                        0.7.0
	pycosat                           0.6.3
	pycparser                         2.20
	Pygments                          2.10.0
	pynndescent                       0.5.5
	pyOpenSSL                         20.0.1
	pyparsing                         2.4.7
	pyrsistent                        0.18.0
	PySocks                           1.7.1
	python-dateutil                   2.8.2
	pytz                              2021.3
	pytz-deprecation-shim             0.1.0.post0
	PyYAML                            6.0
	pyzmq                             22.2.1
	qtconsole                         5.1.1
	QtPy                              1.10.0
	regex                             2021.11.2
	requests                          2.25.1
	rpy2                              3.4.5
	ruamel-yaml-conda                 0.15.100
	scanpy                            1.8.2
	scikit-learn                      1.0.1
	scipy                             1.7.1
	seaborn                           0.11.2
	Send2Trash                        1.8.0
	setuptools                        52.0.0.post20210125
	sinfo                             0.3.4
	sip                               4.19.13
	six                               1.16.0
	sklearn                           0.0
	sniffio                           1.2.0
	soupsieve                         2.3
	statsmodels                       0.13.1
	stdlib-list                       0.8.0
	tables                            3.7.0
	terminado                         0.9.4
	testpath                          0.5.0
	threadpoolctl                     3.0.0
	tornado                           6.1
	tqdm                              4.61.2
	traitlets                         5.1.0
	tzdata                            2021.5
	tzlocal                           4.1
	umap-learn                        0.5.2
	urllib3                           1.26.6
	virtualenv                        20.10.0
	virtualenv-clone                  0.5.7
	wcwidth                           0.2.5
	webencodings                      0.5.1
	websocket-client                  1.2.3
	wheel                             0.36.2
	widgetsnbextension                3.5.1
	xlrd                              1.2.0
	zipp                              3.6.0

conda list:
	# packages in environment at /Users/seanmcgowan/opt/miniconda3:
	#
	# Name                    Version                   Build  Channel
	anaconda-client           1.9.0            py39hecd8cb5_0  
	anndata                   0.7.8                    pypi_0    pypi
	anndata2ri                1.0.6                    pypi_0    pypi
	anyio                     3.5.0                    pypi_0    pypi
	appnope                   0.1.2           py39hecd8cb5_1001  
	argon2-cffi               20.1.0           py39h9ed2024_1  
	async_generator           1.10               pyhd3eb1b0_0  
	attrs                     21.2.0             pyhd3eb1b0_0  
	babel                     2.9.1                    pypi_0    pypi
	backcall                  0.2.0              pyhd3eb1b0_0  
	beautifulsoup4            4.10.0                   pypi_0    pypi
	bleach                    4.0.0              pyhd3eb1b0_0  
	brotlipy                  0.7.0           py39h9ed2024_1003  
	ca-certificates           2021.10.26           hecd8cb5_2  
	certifi                   2021.10.8        py39hecd8cb5_2  
	cffi                      1.14.6           py39h2125817_0  
	chardet                   4.0.0           py39hecd8cb5_1003  
	click                     8.0.3                    pypi_0    pypi
	clyent                    1.2.2            py39hecd8cb5_1  
	conda                     4.11.0           py39hecd8cb5_0  
	conda-package-handling    1.7.3            py39h9ed2024_1  
	cryptography              3.4.7            py39h2fd3fbb_0  
	cycler                    0.11.0                   pypi_0    pypi
	dataclasses               0.6                      pypi_0    pypi
	debugpy                   1.4.1            py39h23ab428_0  
	decorator                 5.1.0              pyhd3eb1b0_0  
	defusedxml                0.7.1              pyhd3eb1b0_0  
	dunamai                   1.8.0                    pypi_0    pypi
	entrypoints               0.3              py39hecd8cb5_0  
	get-version               3.5.3                    pypi_0    pypi
	gprofiler                 1.2.2                    pypi_0    pypi
	gprofiler-official        1.0.0                    pypi_0    pypi
	h5py                      3.6.0                    pypi_0    pypi
	icu                       58.2                 h0a44026_3  
	idna                      2.10               pyhd3eb1b0_0  
	importlib-metadata        4.8.1            py39hecd8cb5_0  
	importlib_metadata        4.8.1                hd3eb1b0_0  
	ipykernel                 6.4.1            py39hecd8cb5_1  
	ipython                   7.27.0           py39h01d92e1_0  
	ipython_genutils          0.2.0              pyhd3eb1b0_1  
	ipywidgets                7.6.5              pyhd3eb1b0_1  
	jedi                      0.18.0           py39hecd8cb5_1  
	jinja2                    3.0.1              pyhd3eb1b0_0  
	joblib                    1.1.0                    pypi_0    pypi
	jpeg                      9d                   h9ed2024_0  
	json5                     0.9.6                    pypi_0    pypi
	jsonschema                3.2.0              pyhd3eb1b0_2  
	jupyter-server            1.13.5                   pypi_0    pypi
	jupyter_client            7.0.1              pyhd3eb1b0_0  
	jupyter_console           6.4.0              pyhd3eb1b0_0  
	jupyter_core              4.8.1            py39hecd8cb5_0  
	jupyterlab                3.2.9                    pypi_0    pypi
	jupyterlab-server         2.10.3                   pypi_0    pypi
	jupyterlab_pygments       0.1.2                      py_0  
	jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
	kiwisolver                1.3.2                    pypi_0    pypi
	libcxx                    10.0.0                        1  
	libffi                    3.3                  hb1e8313_2  
	libpng                    1.6.37               ha441bb4_0  
	libsodium                 1.0.18               h1de35cc_0  
	llvmlite                  0.37.0                   pypi_0    pypi
	markupsafe                2.0.1            py39h9ed2024_0  
	matplotlib                3.4.3                    pypi_0    pypi
	matplotlib-inline         0.1.2              pyhd3eb1b0_2  
	mistune                   0.8.4           py39h9ed2024_1000  
	natsort                   8.1.0                    pypi_0    pypi
	nbclassic                 0.3.5                    pypi_0    pypi
	nbclient                  0.5.3              pyhd3eb1b0_0  
	nbconvert                 6.1.0            py39hecd8cb5_0  
	nbformat                  5.1.3              pyhd3eb1b0_0  
	ncurses                   6.2                  h0a44026_1  
	nest-asyncio              1.5.1              pyhd3eb1b0_0  
	networkx                  2.6.3                    pypi_0    pypi
	nltk                      3.6.5                    pypi_0    pypi
	notebook                  6.4.5            py39hecd8cb5_0  
	numba                     0.54.1                   pypi_0    pypi
	numexpr                   2.8.1                    pypi_0    pypi
	numpy                     1.20.3                   pypi_0    pypi
	openssl                   1.1.1m               hca72f7f_0  
	packaging                 21.0               pyhd3eb1b0_0  
	pandas                    1.3.4                    pypi_0    pypi
	pandocfilters             1.4.3            py39hecd8cb5_1  
	parso                     0.8.2              pyhd3eb1b0_0  
	patsy                     0.5.2                    pypi_0    pypi
	pexpect                   4.8.0              pyhd3eb1b0_3  
	pickleshare               0.7.5           pyhd3eb1b0_1003  
	pillow                    8.4.0                    pypi_0    pypi
	pip                       21.1.3           py39hecd8cb5_0  
	prometheus_client         0.11.0             pyhd3eb1b0_0  
	prompt-toolkit            3.0.20             pyhd3eb1b0_0  
	prompt_toolkit            3.0.20               hd3eb1b0_0  
	ptyprocess                0.7.0              pyhd3eb1b0_2  
	pycosat                   0.6.3            py39h9ed2024_0  
	pycparser                 2.20                       py_2  
	pygments                  2.10.0             pyhd3eb1b0_0  
	pynndescent               0.5.5                    pypi_0    pypi
	pyopenssl                 20.0.1             pyhd3eb1b0_1  
	pyparsing                 2.4.7              pyhd3eb1b0_0  
	pyqt                      5.9.2            py39h23ab428_6  
	pyrsistent                0.18.0           py39h9ed2024_0  
	pysocks                   1.7.1            py39hecd8cb5_0  
	python                    3.9.5                h88f2d9e_3  
	python-dateutil           2.8.2              pyhd3eb1b0_0  
	python.app                3                py39h9ed2024_0  
	pytz                      2021.3                   pypi_0    pypi
	pytz-deprecation-shim     0.1.0.post0              pypi_0    pypi
	pyyaml                    6.0              py39hca72f7f_1  
	pyzmq                     22.2.1           py39h23ab428_1  
	qt                        5.9.7                h468cd18_1  
	qtconsole                 5.1.1              pyhd3eb1b0_0  
	qtpy                      1.10.0             pyhd3eb1b0_0  
	readline                  8.1                  h9ed2024_0  
	regex                     2021.11.2                pypi_0    pypi
	requests                  2.25.1             pyhd3eb1b0_0  
	rpy2                      3.4.5                    pypi_0    pypi
	ruamel_yaml               0.15.100         py39h9ed2024_0  
	scanpy                    1.8.2                    pypi_0    pypi
	scikit-learn              1.0.1                    pypi_0    pypi
	scipy                     1.7.1                    pypi_0    pypi
	seaborn                   0.11.2                   pypi_0    pypi
	send2trash                1.8.0              pyhd3eb1b0_1  
	setuptools                52.0.0           py39hecd8cb5_0  
	sinfo                     0.3.4                    pypi_0    pypi
	sip                       4.19.13          py39h23ab428_0  
	six                       1.16.0             pyhd3eb1b0_0  
	sklearn                   0.0                      pypi_0    pypi
	sniffio                   1.2.0                    pypi_0    pypi
	soupsieve                 2.3                      pypi_0    pypi
	sqlite                    3.36.0               hce871da_0  
	statsmodels               0.13.1                   pypi_0    pypi
	stdlib-list               0.8.0                    pypi_0    pypi
	tables                    3.7.0                    pypi_0    pypi
	terminado                 0.9.4            py39hecd8cb5_0  
	testpath                  0.5.0              pyhd3eb1b0_0  
	threadpoolctl             3.0.0                    pypi_0    pypi
	tk                        8.6.10               hb0a8c7a_0  
	tornado                   6.1              py39h9ed2024_0  
	tqdm                      4.61.2             pyhd3eb1b0_1  
	traitlets                 5.1.0              pyhd3eb1b0_0  
	tzdata                    2021.5                   pypi_0    pypi
	tzlocal                   4.1                      pypi_0    pypi
	umap-learn                0.5.2                    pypi_0    pypi
	urllib3                   1.26.6             pyhd3eb1b0_1  
	wcwidth                   0.2.5              pyhd3eb1b0_0  
	webencodings              0.5.1            py39hecd8cb5_1  
	websocket-client          1.2.3                    pypi_0    pypi
	wheel                     0.36.2             pyhd3eb1b0_0  
	widgetsnbextension        3.5.1            py39hecd8cb5_0  
	xlrd                      1.2.0                    pypi_0    pypi
	xz                        5.2.5                h1de35cc_0  
	yaml                      0.2.5                haf1e3a3_0  
	zeromq                    4.3.4                h23ab428_0  
	zipp                      3.6.0              pyhd3eb1b0_0  
	zlib                      1.2.11               h1de35cc_3

conda env:
	name: base
	channels:
	  - defaults
	dependencies:
	  - anaconda-client=1.9.0=py39hecd8cb5_0
	  - appnope=0.1.2=py39hecd8cb5_1001
	  - argon2-cffi=20.1.0=py39h9ed2024_1
	  - async_generator=1.10=pyhd3eb1b0_0
	  - attrs=21.2.0=pyhd3eb1b0_0
	  - backcall=0.2.0=pyhd3eb1b0_0
	  - bleach=4.0.0=pyhd3eb1b0_0
	  - brotlipy=0.7.0=py39h9ed2024_1003
	  - ca-certificates=2021.10.26=hecd8cb5_2
	  - certifi=2021.10.8=py39hecd8cb5_2
	  - cffi=1.14.6=py39h2125817_0
	  - chardet=4.0.0=py39hecd8cb5_1003
	  - clyent=1.2.2=py39hecd8cb5_1
	  - conda=4.11.0=py39hecd8cb5_0
	  - conda-package-handling=1.7.3=py39h9ed2024_1
	  - cryptography=3.4.7=py39h2fd3fbb_0
	  - debugpy=1.4.1=py39h23ab428_0
	  - decorator=5.1.0=pyhd3eb1b0_0
	  - defusedxml=0.7.1=pyhd3eb1b0_0
	  - entrypoints=0.3=py39hecd8cb5_0
	  - icu=58.2=h0a44026_3
	  - idna=2.10=pyhd3eb1b0_0
	  - importlib-metadata=4.8.1=py39hecd8cb5_0
	  - importlib_metadata=4.8.1=hd3eb1b0_0
	  - ipykernel=6.4.1=py39hecd8cb5_1
	  - ipython=7.27.0=py39h01d92e1_0
	  - ipython_genutils=0.2.0=pyhd3eb1b0_1
	  - ipywidgets=7.6.5=pyhd3eb1b0_1
	  - jedi=0.18.0=py39hecd8cb5_1
	  - jinja2=3.0.1=pyhd3eb1b0_0
	  - jpeg=9d=h9ed2024_0
	  - jsonschema=3.2.0=pyhd3eb1b0_2
	  - jupyter_client=7.0.1=pyhd3eb1b0_0
	  - jupyter_console=6.4.0=pyhd3eb1b0_0
	  - jupyter_core=4.8.1=py39hecd8cb5_0
	  - jupyterlab_pygments=0.1.2=py_0
	  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
	  - libcxx=10.0.0=1
	  - libffi=3.3=hb1e8313_2
	  - libpng=1.6.37=ha441bb4_0
	  - libsodium=1.0.18=h1de35cc_0
	  - markupsafe=2.0.1=py39h9ed2024_0
	  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
	  - mistune=0.8.4=py39h9ed2024_1000
	  - nbclient=0.5.3=pyhd3eb1b0_0
	  - nbconvert=6.1.0=py39hecd8cb5_0
	  - nbformat=5.1.3=pyhd3eb1b0_0
	  - ncurses=6.2=h0a44026_1
	  - nest-asyncio=1.5.1=pyhd3eb1b0_0
	  - notebook=6.4.5=py39hecd8cb5_0
	  - openssl=1.1.1m=hca72f7f_0
	  - packaging=21.0=pyhd3eb1b0_0
	  - pandocfilters=1.4.3=py39hecd8cb5_1
	  - parso=0.8.2=pyhd3eb1b0_0
	  - pexpect=4.8.0=pyhd3eb1b0_3
	  - pickleshare=0.7.5=pyhd3eb1b0_1003
	  - pip=21.1.3=py39hecd8cb5_0
	  - prometheus_client=0.11.0=pyhd3eb1b0_0
	  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
	  - prompt_toolkit=3.0.20=hd3eb1b0_0
	  - ptyprocess=0.7.0=pyhd3eb1b0_2
	  - pycosat=0.6.3=py39h9ed2024_0
	  - pycparser=2.20=py_2
	  - pygments=2.10.0=pyhd3eb1b0_0
	  - pyopenssl=20.0.1=pyhd3eb1b0_1
	  - pyparsing=2.4.7=pyhd3eb1b0_0
	  - pyqt=5.9.2=py39h23ab428_6
	  - pyrsistent=0.18.0=py39h9ed2024_0
	  - pysocks=1.7.1=py39hecd8cb5_0
	  - python=3.9.5=h88f2d9e_3
	  - python-dateutil=2.8.2=pyhd3eb1b0_0
	  - python.app=3=py39h9ed2024_0
	  - pyyaml=6.0=py39hca72f7f_1
	  - pyzmq=22.2.1=py39h23ab428_1
	  - qt=5.9.7=h468cd18_1
	  - qtconsole=5.1.1=pyhd3eb1b0_0
	  - qtpy=1.10.0=pyhd3eb1b0_0
	  - readline=8.1=h9ed2024_0
	  - requests=2.25.1=pyhd3eb1b0_0
	  - ruamel_yaml=0.15.100=py39h9ed2024_0
	  - send2trash=1.8.0=pyhd3eb1b0_1
	  - setuptools=52.0.0=py39hecd8cb5_0
	  - sip=4.19.13=py39h23ab428_0
	  - six=1.16.0=pyhd3eb1b0_0
	  - sqlite=3.36.0=hce871da_0
	  - terminado=0.9.4=py39hecd8cb5_0
	  - testpath=0.5.0=pyhd3eb1b0_0
	  - tk=8.6.10=hb0a8c7a_0
	  - tornado=6.1=py39h9ed2024_0
	  - tqdm=4.61.2=pyhd3eb1b0_1
	  - traitlets=5.1.0=pyhd3eb1b0_0
	  - urllib3=1.26.6=pyhd3eb1b0_1
	  - wcwidth=0.2.5=pyhd3eb1b0_0
	  - webencodings=0.5.1=py39hecd8cb5_1
	  - wheel=0.36.2=pyhd3eb1b0_0
	  - widgetsnbextension=3.5.1=py39hecd8cb5_0
	  - xz=5.2.5=h1de35cc_0
	  - yaml=0.2.5=haf1e3a3_0
	  - zeromq=4.3.4=h23ab428_0
	  - zipp=3.6.0=pyhd3eb1b0_0
	  - zlib=1.2.11=h1de35cc_3
	  - pip:
	    - anndata==0.7.8
	    - anndata2ri==1.0.6
	    - anyio==3.5.0
	    - babel==2.9.1
	    - beautifulsoup4==4.10.0
	    - click==8.0.3
	    - cycler==0.11.0
	    - dataclasses==0.6
	    - dunamai==1.8.0
	    - get-version==3.5.3
	    - gprofiler==1.2.2
	    - gprofiler-official==1.0.0
	    - h5py==3.6.0
	    - joblib==1.1.0
	    - json5==0.9.6
	    - jupyter-server==1.13.5
	    - jupyterlab==3.2.9
	    - jupyterlab-server==2.10.3
	    - kiwisolver==1.3.2
	    - llvmlite==0.37.0
	    - matplotlib==3.4.3
	    - natsort==8.1.0
	    - nbclassic==0.3.5
	    - networkx==2.6.3
	    - nltk==3.6.5
	    - numba==0.54.1
	    - numexpr==2.8.1
	    - numpy==1.20.3
	    - pandas==1.3.4
	    - patsy==0.5.2
	    - pillow==8.4.0
	    - pynndescent==0.5.5
	    - pytz==2021.3
	    - pytz-deprecation-shim==0.1.0.post0
	    - regex==2021.11.2
	    - rpy2==3.4.5
	    - scanpy==1.8.2
	    - scikit-learn==1.0.1
	    - scipy==1.7.1
	    - seaborn==0.11.2
	    - sinfo==0.3.4
	    - sklearn==0.0
	    - sniffio==1.2.0
	    - soupsieve==2.3
	    - statsmodels==0.13.1
	    - stdlib-list==0.8.0
	    - tables==3.7.0
	    - threadpoolctl==3.0.0
	    - tzdata==2021.5
	    - tzlocal==4.1
	    - umap-learn==0.5.2
	    - websocket-client==1.2.3
	    - xlrd==1.2.0
	prefix: /Users/seanmcgowan/opt/miniconda3

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>
<img width="1447" alt="Screen Shot 2022-02-17 at 11 48 43 AM" src="https://user-images.githubusercontent.com/85389086/154559431-2c9f18fb-d867-4f8c-b872-07ab7a3c5ae4.png">

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by agoose77** [comment] 2022-02-22 11:43
This is very unlikely to be a JupyterLab bug - it sounds like your kernel is crashing, and that is almost guaranteed to be an issue with the libraries you're using in Python. It would be a good idea to work out which line of code is likely causing the crash, and file a bug report with the library author.

I'm going to close this issue, because I don't think that it's a JupyterLab bug. If you determine otherwise in future, please feel free to re-open the issue!

Despite closing this issue, I'd be happy to try and help you debug this. It would be helpful if you could share a notebook that is causing the crash, and detail the top-level packages you installed (rather than the environment snapshot) so that I can reproduce.

**Closed by agoose77** 2022-02-22 11:43 UTC
Labels: bug, status:Needs Triage
