### ISSUE TITLE
Jupyter lab (with pandas library imported) interface lagging when moving cursor and "Show Contextual Help" is open side-by-side to the notebook

### ISSUE THREAD

**Issue by paul-cvp** [jupyterlab/jupyterlab#11506] opened 2021-11-19 14:49 UTC
The interface lags for a 3-5 seconds (cannot click, cannot type, cannot see cursor) when navigating through python code and looking at "Show Contextual Help" while using the pandas library.

Context:
- Operating System and version: WSL 2.0 Linux Ubuntu 20.04 virtual machine on Windows 10
- Browser and version: Chrome Version 96.0.4664.45 (Official Build) (64-bit) + Edge (same behavior)
- JupyterLab version: 3.2.3 
- Pandas version: 1.3.4
- Python version: 3.8.5 64bit

This should be enough to replicate the lagging issue:
```
import os
import numpy as np
import pandas as pd

df = pd.DataFrame()
```

**Comment by krassowski** [comment] 2021-11-19 17:32
Thanks for the reproduction instructions! Seems like a duplicate of https://github.com/jupyterlab/jupyterlab/issues/11458?

**Comment by paul-cvp** [comment] 2021-11-20 13:12
Hi. If I assume that by "Inspector panel" he means the same as the "Show Contextual Help", in other words pressing "CTRL + I" then yes, it does sound very similar. It could be happening in general with really big packages or packages with a lot of text in the documentation like "pandas" or "seaborn". It does not seem to happen with smaller packages, like "numpy".

**Comment by krassowski** [comment] 2021-11-20 13:16
Yes, "Contextual Help" used to be named "Inspector" and the code name remained.

**Comment by krassowski** [comment] 2022-01-21 18:07
Closing as a duplicated in favour of #11506. Thanks for the report.

**Closed by krassowski** 2022-01-21 18:07 UTC
Labels: bug, status:Duplicate
