### ISSUE TITLE
maxNumberOutputs with stdout/stderr

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#10046] opened 2021-04-05 21:53 UTC
### Problem

`maxNumberOutputs` works well for many mime-renders, but it has some issues with stdout/stderr as it seems like Jupyterlab is combining these as aggressively as possible into the least number of mime outputs (I may be misunderstanding this).

Example:
```
import random
for i in range(100):
    for x in range(10):
        print(x, flush=True)
    for x in range(10):
        print(x, file=sys.stderr, flush=True)
```

This has 200 outputs:
![image](https://user-images.githubusercontent.com/1813603/113629797-e3d84780-9634-11eb-8ec6-1355733e20c5.png)

But I would expect 2000 (one per print) due to the usage of flush. Without flush, example had only two outputs.

### Proposed Solution

It's not clear what should be done here, but the value of `maxNumberOutputs` is greatly diminished if print statements don't count towards it because of how they get combined. [Limit Output](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/limit_output/readme.html) from notebook approximates better behavior I think end users expected with `maxNumberOutputs`.

**Comment by goanpeca** [comment] 2021-04-06 15:06
>Jupyterlab is combining these as aggressively as possible into the least number of mime outputs

It is indeed doing that, it will try to create as small number of nodes as possible, see https://github.com/jupyterlab/jupyterlab/blob/master/packages/outputarea/src/model.ts#L306

**Comment by echarles** [comment] 2021-07-12 11:42
@mlucool The reproducer for this issue is the same as https://github.com/jupyterlab/jupyterlab/issues/10045#issuecomment-813662295

Is this a duplicate or a different issue?

**Comment by echarles** [comment] 2021-07-13 15:31
As discussed with @goanpeca, I am working on this.

**Comment by echarles** [comment] 2021-08-05 08:17
Looks to me this is a duplicate of https://github.com/jupyterlab/jupyterlab/issues/10045 which has more details and comments.

Closing this one in favor of https://github.com/jupyterlab/jupyterlab/issues/10045

Please reopen if you think it should not be closed.

**Closed by echarles** 2021-08-05 08:17 UTC
Labels: enhancement
