### ISSUE TITLE
Parallel execution in different cells

### ISSUE THREAD

**Issue by wybert** [jupyterlab/jupyterlab#13033] opened 2022-08-31 21:20 UTC
Hi, I would like to have a parallel execution feature in different cells. In Jupyterlab when you click run in two cells, it will run continually, if two cells do not rely on each other, It would be nice to run it parallelly. It cound speed up the data analysis process.

Users can toggle this feature by using a magic command, like `%%parallel`. The Maximum parallel cells can be set by users also.

**Comment by davidbrochart** [comment] 2022-08-31 21:40
Hi @wybert,

It can already be done using multithreading or multiprocessing.
In the Python ecosystem, you can have a look at these libraries:
- ipyparallel: https://ipyparallel.readthedocs.io
- Dask: https://www.dask.org

And at the kernel level:
- akernel: https://github.com/davidbrochart/akernel (although it's concurrency rather than parallelism).
- This PR in ipykernel: https://github.com/ipython/ipykernel/pull/955

**Comment by jweill-aws** [comment] 2022-09-01 17:26
Thanks for your suggestion, @wybert ! I'm closing this issue for now, but if the suggestions that @davidbrochart offered don't meet your needs, please reopen it. I appreciate your contribution to JupyterLab.

**Closed by jweill-aws** 2022-09-01 17:26 UTC
Labels: enhancement, status:Needs Triage

**Comment by krassowski** [comment] 2022-09-01 17:35
This is also a duplicate of #8963.

**Comment by wybert** [comment] 2022-09-01 18:42
> Thanks for your suggestion, @wybert ! I'm closing this issue for now, but if the suggestions that @davidbrochart offered don't meet your needs, please reopen it. I appreciate your contribution to JupyterLab.

The suggestion @davidbrochart is not exactly what I am looking for. 

The asynchronous execution in akernel is kind of what I am looking for. But akernel is not intuitive and it's better to support other types of cells too. Like, run bash code cell (such as `pip install pandas`) and python code cell below it at the same time.  #8963 is the same feature as here.

**Comment by jweill-aws** [comment] 2022-09-01 19:22
OK, thanks @wybert . I'll leave this as closed. Let's continue the discussion in #8963.
