### ISSUE TITLE
Better support of data frame/table in output

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#1295] opened 2016-11-26 18:20 UTC
To generate a good report, we often have to 
1. present data frame/table interactively (being able to order by columns, filtering rows, etc.)
2. highlight data in tables
It's appealing for JupyterLab to support these two features. It seems that the JS library DataTable can leveraged to implement the first feature. A JS library for spreadsheet can probably be used to implement the second feature.

**Comment by blink1073** [comment] 2016-11-28 02:28
Hi @dclong, we are discussing the display of data frames in https://github.com/jupyterlab/jupyterlab/issues/1194.  For spreadsheets, you can use a bokeh output: http://bokeh.pydata.org/en/0.11.1/docs/user_guide/interaction.html#data-table.

**Comment by ellisonbg** [comment] 2016-12-23 16:09
Closing as duplicate of #1194

**Closed by ellisonbg** 2016-12-23 16:09 UTC
Labels: type:Question
