### ISSUE TITLE
Update to TypeScript 5 final

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#13872] opened 2023-01-27 10:41 UTC
### Problem

TypeScript 5 beta is now available: https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/

We should directly update to it for JupyterLab 4.0 since its final release will likely be available before JupyterLab 4 final.

### Proposed Solution

Update to TypeScript 5.

### Additional context

Some work to update TypeScript had already started in https://github.com/jupyterlab/jupyterlab/pull/13028. Although it's been lagging a bit behind and had to go through multiple rebases due to issues in some dependencies.

**Comment by krassowski** [comment] 2023-02-02 18:48
@JasonWeill we cannot do this in 4.1. Could we avoid moving issues which have to be addressed in 4.0 (either because they are regressions or because they require a major version bump) to 4.1 milestone, please?

**Comment by jasongrout** [comment] 2023-02-05 04:38
According to the TS 5.0 [timeline](https://github.com/microsoft/TypeScript/issues/51362), 5.0RC is expected 28 Feb, with 5.0 final released 14 Mar.

+1 to updating to TS 5.0 if possible for jlab 4.0.

**Comment by jasongrout** [comment] 2023-02-05 05:37
I submitted a quick PR at https://github.com/jupyterlab/jupyterlab/pull/13925 to look at upgrading to TS 5.0 beta.

**Comment by jtpio** [comment] 2023-02-20 14:56
The update to TypeScript 5 beta landed in https://github.com/jupyterlab/jupyterlab/pull/13925.

We can keep this issue open to update to TypeScript 5 final.

**Comment by JasonWeill** [comment] 2023-03-16 17:12
@jtpio TypeScript 5 is now available: https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/

**Comment by jtpio** [comment] 2023-03-16 17:34
Nice thanks for the heads up. PR incoming.

**Closed** 2023-03-17 07:09 UTC
Labels: help wanted, maintenance
