### ISSUE TITLE
CTRL+Z in text editor doesn't move the text view to where the undoing happened

### ISSUE THREAD

**Issue by lpuglia** [jupyterlab/jupyterlab#15781] opened 2024-02-09 13:18 UTC
## Description

Since i moved to jupyterlab > 4.0.0 the text editor view has stopped moving to the undo place when pressing CTRL+Z.

This issue is similar to what was discussed in https://github.com/jupyterlab/jupyterlab/issues/11253, but it is for the text editor view (this issue seems to be back in the notebook view as well)

## Reproduce

https://github.com/jupyterlab/jupyterlab/assets/2184440/f8521f52-fae1-4ade-b121-2febb50cb087

it's hard to see in the video, but at around 00:03 i press CTRL+Z. The undo is applied correctly as the added string is removed, but the viewport doesn't move back to where that happened. Before 4.0.0 this feature wasn't perfect by any mean (quite rough around the edges compared to any modern IDE) but not having it at all is quite annoying.

## Expected behavior

Anything like a modern IDE would be appreciated, VSCode behavior is quite the standard.

## Context

- Operating System and version: Linux Ubuntu 22.04
- Browser and version:  Any
- JupyterLab version: >4.0.0

**Comment by krassowski** [comment] 2024-02-09 14:26
Thank you @lpuglia for the report. I believe that this is a duplicate of https://github.com/jupyterlab/jupyterlab/issues/15102. I had looked into this last week, see https://github.com/jupyterlab/jupyterlab/issues/15102#issuecomment-1925762476. Contributions welcome!

**Comment by JasonWeill** [comment] 2024-02-09 18:02
Let's keep the discussion going in #15102.

**Closed by JasonWeill** 2024-02-09 18:02 UTC
Labels: bug, status:Duplicate, status:Needs Triage

**Comment by lpuglia** [comment] 2024-02-10 18:15
nice, sorry, not sure how i missed it!

**Comment by jasongrout** [comment] 2025-12-07 03:57
FYI, I've moved the discussion from issue #11253 to https://github.com/jupyterlab/jupyterlab/issues/18180
