### ISSUE TITLE
Jumpy scrollbar in windowed mode

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#14467] opened 2023-05-01 12:31 UTC
## Description

Given a large notebook with outputs that vary in size (lots of text, matplotlib output, no output) the scrollbar in full windowing mode is very jumpy. Switching to no windowing fixes this.

## Reproduce

See gif below and watch how jittery a mouse drag is.
![jumpy-scroll](https://user-images.githubusercontent.com/1813603/235451784-b74c214d-9eab-4acd-864f-a4e69d09c02e.gif)

## Expected behavior

Scrolling is smooth

## Context
Lab @ 4.0.0b2

CC @jtpio @fcollonval

**Comment by JasonWeill** [comment] 2023-05-02 16:26
Closing as duplicate of #13343.

**Closed by JasonWeill** 2023-05-02 16:26 UTC
Labels: bug, status:Needs Triage

**Comment by mlucool** [comment] 2023-05-02 17:29
This was a duplicate. Sorry!
