### ISSUE TITLE
Context Menu Option to Comment/Block Comment selected lines

### ISSUE THREAD

**Issue by diyoyo** [jupyterlab/jupyterlab#15943] opened 2024-03-07 13:31 UTC
### Problem

* I'm always frustrated when using keyboard shortcuts because they don't always work in my given setup (fr keyboard on mac laptop is the worst, I'd like to say). Especially "Block Commenting", which is the most frequent one that I use on a daily basis.

### Proposed Solution

* Add an option in the contextual menu that would allow the current selection to be commented in/out 
* Or add a command for which we could create a new item in the Cell Toolbar settings.

### Additional context

Pleaaaaase 🥺🥺🥺🥺

**Comment by JasonWeill** [comment] 2024-03-12 16:22
Closing as a duplicate of #4778.

**Closed by JasonWeill** 2024-03-12 16:22 UTC
Labels: status:Duplicate, enhancement, status:Needs Triage
