### ISSUE TITLE
Cannot paste files into empty folder

### ISSUE THREAD

**Issue by mimischi** [jupyterlab/jupyterlab#4250] opened 2018-03-27 09:15 UTC
Hope I did not overlook some open issue reporting this.

If one copies a file and goes into some empty folder, it is not possible to paste the file. The context menu does not show up for right-clicks on empty areas (e.g. the white space underneath the file list). My current workaround is to move up one level -> click on any file -> Paste -> drag&drop previously copied file into the desired (empty) folder.

**Comment by ian-r-rose** [comment] 2018-03-27 15:56
Thanks for the report @mimischi, this is indeed a duplicate of #3602 (and it really needs fixing!). Can we continue the discussion there?

**Closed** 2018-03-27 16:13 UTC
