### ISSUE TITLE
[feature request] Switching between last used tabs

### ISSUE THREAD

**Issue by idoDavid** [jupyterlab/jupyterlab#4177] opened 2018-03-14 13:11 UTC
Hi,

The move next/previous tabs are not very useful when you have a lot of tabs open but you actually work with only two. Can you add a switch to last used tab button? so pressing the same key combo swithches between the same tabs?

**Comment by jasongrout** [comment] 2018-03-14 15:44
That sounds really useful. Thanks for posting an issue about it!

**Comment by siryog90** [comment] 2018-03-16 08:05
If the issue is assigned to anyone yet, I would like to give it a go as a first contribution.

**Comment by ian-r-rose** [comment] 2018-03-16 15:32
Go ahead @siryog90. Feel free to ping us here or submit work-in-progress if you have any questions about how to get started

**Comment by siryog90** [comment] 2018-03-16 22:50
@ian-r-rose @sccolbert I just took a first look at the source code, as well as the relevant snippets of phosphor. It seems the `TabBar` widget does not store active tab history in a list. However, there is a private field `previousTitle` that seems perfect for this task. Any chance this field could be made public?

**Comment by ian-r-rose** [comment] 2018-03-16 23:05
Rather than accessing a private member of `TabBar`, I'd recommend listening to the `app.shell.currrentChanged` signal, which will let you know when the active widget in the main work area changes (as well as what it was previously). You can then use this to keep an up-to-date reference to the current and previous widgets, allowing you to toggle back and forth.

An example of using this signal can be found in `inspector-extension`.

**Comment by siryog90** [comment] 2018-03-17 08:01
@ian-r-rose As far as a design choice, this issue seems closely related to the issue of [activating previous/next tab](https://github.com/jupyterlab/jupyterlab/pull/1647/files/0971ebf0bd6b1e8e47f119931d8edf2b93c9cea4#diff-4654a4eab10f0b358b6cb7e4c598b42e). Would you suggest adding to `shell.ts` like in the aforementioned issue, or implementing a new extension?

**Comment by idoDavid** [comment] 2018-03-18 08:26
@siryog90 @ian-r-rose for the feature I'm imagining, you have to remember 2 locations:

1. The current location
2. The last jumped to location

Upon click/keyboard shortcut, navigate between the two. behavior should be like this:
- Given I'm scrolling manually at section 5
- and I click on some external link (from Toc or other navigation links) to section 2
- and I jump to section 2 
- When I click the back button or back keyboard shortcut
- Then I go back to section 5

In contrast, this is *not* a good behavior:
- Given I'm scrolling manually at section 5
- and I click on some external link (from Toc or other navigation links) to section 2
- and I jump to section 2 
- and I click the back button or back keyboard shortcut
- and I go back to section 5
- and I continue scrolling to section 5.1
- when I press the back button 
- Then I jump back to section 5 *Not the desired behavior, we wanted to jump back to section 2!*

So as I mentioned, the last location of manual scrolling and the last jumped to location are the two locations we usually want to switch between. Is it possible to identify them separately? is it possible to identify a jump-to event?

**Comment by ian-r-rose** [comment] 2018-03-18 14:47
@siryog90 I think this can be done without modifying `shell.ts`. I agree that it's related to previous/next tab, but it could probably be implemented in the `mainmenu-extension` package, in the same function that adds the other tab-manipulation functions: https://github.com/jupyterlab/jupyterlab/blob/master/packages/mainmenu-extension/src/index.ts#L460

**Comment by DevOpsChris** [comment] 2018-07-14 16:14
I'll take a stab at the issue for scipy2018 sprint.  If anyone hasn't already.

**Comment by ivanov** [comment] 2018-07-14 16:32
@DevOpsChris just gave me the heads up that this seems to be finished with #4296, so I'm closing this issue.
Happy hacking! :bowtie:

**Closed by ivanov** 2018-07-14 16:32 UTC
Labels: good first issue

**Comment by idoDavid** [comment] 2018-07-16 15:04
@ian-r-rose @siryog90 is this deployed? I'm on version 0.32.1 and seems like that functionality is not available.

**Comment by ian-r-rose** [comment] 2018-07-16 15:08
I don't think it has been released yet (we plan to release 0.33 this week though!).
