### ISSUE TITLE
Doing “create new view for output” with Python API?

### ISSUE THREAD

**Issue by gkvoelkl** [jupyterlab/jupyterlab#4021] opened 2018-02-26 15:59 UTC
Is there a way to do “create new view for output” in Python within a notebook?
Available? Planned? Suggestion?

Thanks.

Regards Gerhard

**Comment by AdrienLeveque** [comment] 2018-02-26 16:23
One possibility is to click right in the "In" and select "Create New View for Outputs" as in this post:
https://github.com/jupyterlab/jupyterlab/issues/3782

**Comment by gkvoelkl** [comment] 2018-02-26 16:36
I am looking for doing the within Python.

**Comment by ian-r-rose** [comment] 2018-02-26 16:42
Hi @gkvoelkl, as far as I know there is currently no way to do what you are suggesting. By design, the backend typically knows very little about the frontend environment (in this case, JupyterLab), which is receiving the outputs of the code.

It should be possible to add some metadata to the output that suggests to the frontend: "render this in some sort of side panel", but I don't think there has been much experimentation on that front yet.

**Comment by saulshanabrook** [comment] 2018-06-27 15:32
I am closing this as a duplicate of https://github.com/jupyterlab/jupyterlab/issues/3692. Please comment/re-open if you believe it is a different issue.

**Closed by saulshanabrook** 2018-06-27 15:32 UTC
Labels: pkg:outputarea, type:Question
