### ISSUE TITLE
Some parts of strings are URL encoded in output

### ISSUE THREAD

**Issue by jbulow** [jupyterlab/jupyterlab#8501] opened 2020-06-01 14:29 UTC
In jupytelab 2.1.3 I the end of strings are url encoded:

`'<http://example.com>'`

outputs as:

`'<http://example.com&gt;'`

In vanilla jupyter the output is, as expected:

`'<http://www.example.com>'`

**Comment by bh1428** [comment] 2020-06-06 13:39
Having the same issue in jupyterlab 2.1.4 and it's not only an '>' at the end. An '&' is url encoded as well, this:
`'<http://example.com/something?param1=1&param2=2>'`

outputs as:
`'<http://example.com/something?param1=1&amp;param2=2&gt;'`

In vanilla jupyter the output is as expected:
`'<http://example.com/something?param1=1&param2=2>'`

The link target for the url is encoded as well, i.e. if you click the link in jupyterlab you are sent to the url encoded link (in vanilla jupyter you can click the link and you are directed to the correct url).

**Comment by jasongrout** [comment] 2021-01-27 16:34
Closing as duplicate of #8376

**Closed by jasongrout** 2021-01-27 16:34 UTC
