### ISSUE TITLE
adding beautifier to jupyter lab

### ISSUE THREAD

**Issue by reza1615** [jupyterlab/jupyterlab#5754] opened 2018-12-11 03:38 UTC
Please add beautifier extensions like autopep8 and code prettify. [There are](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/6af8e5e84e4746476c5b476b7e38f63d7abb2064/src/jupyter_contrib_nbextensions/nbextensions/code_prettify) the similar extensions for jupyter notebook

**Comment by bollwyvl** [comment] 2018-12-11 14:01
Probably a dupe of this:
https://github.com/jupyterlab/jupyterlab/issues/4521


The language server protocol also provides a standard way for multiple
language formatters to exist:
https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md

https://github.com/jupyterlab/jupyterlab/issues/2163

**Comment by jasongrout** [comment] 2018-12-11 23:23
Thanks. As @bollwyvl points out, we're tracking this suggestion at #4521.

**Closed by jasongrout** 2018-12-11 23:23 UTC
