### ISSUE TITLE
Feature request: TOC for Python files

### ISSUE THREAD

**Issue by stefansimik** [jupyterlab/jupyterlab#7924] opened 2020-02-25 10:01 UTC
## Description

When working with *.py files in jupyter notebook, orientation is not very comfortable,
especially in bigger  modules, containing many functions / classes / ...

It would be huge step forward in daily usability to add TOC (Table of content)
for *.py files, that could contain list of main elements in currently viewed file

* list of all functions and classes in order they are in file
* with option to filter what is displayed (functions / classses / variables)
* with option to see them in alphabetical order (not only in order as they are in file)

For inspiration: Existing TOC for jupyter notebooks.
Existing implementation should be the same, but with ability to process *.py files
https://github.com/jupyterlab/jupyterlab-toc

**Comment by lresende** [comment] 2020-02-25 11:19
This is a duplicate of https://github.com/jupyterlab/jupyterlab-toc/issues/9. Please discuss any other details on the toc repository.

**Closed by lresende** 2020-02-25 11:19 UTC
