### ISSUE TITLE
Consider making Jupyter Lab mobile friendly

### ISSUE THREAD

**Issue by DamienPetrilli** [jupyterlab/jupyterlab#3275] opened 2017-11-23 12:35 UTC
Hi,

I just discovered and started messing around with Jupyter Lab so I might have missed something. However, while Jupyter Notebooks mostly worked on touch based screen, Jupyter Lab is not usable on an iPad 12.9”. It seems the UI relies on double clicks and other mouse driven events which are not available (for example I can’t open a folder, one tap selects it, double tap trigger the rename folder).

I am not sure if it’s because it’s an Alpha or if it’s because touch screens weren’t in the priority list.

More and more people are using tablets nowadays and it would be great if Jupyter Lab supported touch screen based devices. Taking a tablet and connect to a Jupyter Notebook remotely is super useful.

Cheers

**Comment by dwt** [comment] 2017-11-29 15:03
Some more info of things that don‘t work well / workarounds

* Navigating the files tab via the arrow keys does not work - opening files with enter does. That means that a mix of gestures and keyboard does get me around
* in notebooks, arrow keys to change the selected cell don‘t work (if you are not in editing mode)
* in notebooks: arrow keys Do Not allow you to navigate to a different cell
* cannot use escape to leave the focus of a cell (as written above)

There is probably more, but I haven‘t found it yet.

**Comment by juniorrojas** [comment] 2018-03-29 06:14
What repos / directories / documentation should one get familiar with in order to be able to extend the interface (to make it work on mobile, for instance). Would it require making changes in external repos like phosphorjs?

**Comment by chrism2671** [comment] 2018-04-27 13:46
I’m trying to use it on my iPad today and I can’t seem to open files. Anyone got any suggestions?

**Comment by bollwyvl** [comment] 2018-04-27 15:35
Try a long tap to trigger the context menu, then "open". Works on chrome,
at least...

**Comment by saptarshiguha** [comment] 2018-11-16 20:02
Another thing not working is dragging window panes to resize. It would be really nice to make Jupyterlab mobile friendly making it truly device free.

**Comment by dentarthur** [comment] 2018-12-17 01:45
It seemed ok for very briefly running mybinder sample on Samsung 10.5" Android Tablet.

This environment with keyboard is quite suitable for most things despite small screen and no mouse. But it is normal to zoom the screen with Android finger movements both to see details more clearly and to push buttons more easily.

Result of doing so is that control bar with run button at top disappears. (Returns when unzoom).

Should default to freezing the control bar at top of screen despite any zooming of entire screen done at Android end. (Or provide easily noticed instructions on how to configure this).

Perhaps it would be easier to fix this minor flaw for Android Tablets that generally have small screens before 1.0 even though iPad has other more complex issues?

**Comment by dandm1** [comment] 2019-07-08 18:42
+1 on doing some basic things for mobile support. It sounds like most things can be achieved if you have enabled an on-screen keyboard - but that isn't always possible / easy.  For example I was not able to find any way to navigate around the file browser or open files using my iPad.

**Comment by hanzhihua72** [comment] 2019-08-21 19:23
+1. One thing that would be very nice is add mobile support for when Jupyter Notebook/Lab exports as HTML, make the HTML mobile friendly. Like can you imagine going to a conference, and scanning a QR code from a poster presentation to look into someone's repository, and then playing with the jupyter notebook in their environment that they have set up?? Most people don't carry laptops with them, so this would be a huge win for reproducible research.

**Comment by jasongrout** [comment] 2019-08-21 20:15
> One thing that would be very nice is add mobile support for when Jupyter Notebook/Lab exports as HTML, make the HTML mobile friendly.

Great idea. We use nbconvert to convert notebooks. Can you file the issue there? https://github.com/jupyter/nbconvert

**Comment by jameslao** [comment] 2019-09-25 17:00
After upgrading to iPadOS 13 everything seems to be working!

**Comment by jasongrout** [comment] 2019-09-25 17:09
That's great to hear! To be more clear, which of the following have equivalents that work?

* clicking
* clicking and dragging
* right-clicking (context menu)
* hover

**Comment by jasongrout** [comment] 2019-09-25 17:11
Also, are you saying that it works with a mouse paired with an ipad, or it works with native ipad touch?

**Comment by jameslao** [comment] 2019-09-25 17:17
@jasongrout Ah... I realized I was a bit too excited. To be specific double-click is working with native touch, so at least it's usable.

**Comment by jasongrout** [comment] 2019-09-25 17:37
It looks like you can pair a mouse with ipados 13, which apparently is a new feature. I'd love to hear if using a mouse makes jlab work as well as on a desktop.

**Comment by BrianChevalier** [comment] 2019-09-27 19:33
Pairing a mouse is an accessibility feature and only simulates what is possible by touching the screen. I have found that most features work except resizing panels and rearranging tabs. Tapping and holding a tab to try and move it fails. Otherwise most things work well with touch. Although, I’m not sure what would be required to allow touch/whatever magic Apple is doing to reroute touch to mouse events to allow moving tabs. Also, right click doesn’t exist so any extensions that require it (i.e. the LaTeX jupyterlab extension can’t be activated.)

**Comment by mathematicalmichael** [comment] 2019-10-01 21:40
Also just tried it out. Massive improvements overall. 
Click and drag, say to rearrange tabs in jlab, does not work with fingers or pencil. Double click does. Shift enter does not without a keyboard (cell or console execution). No right click. 

Highest priority is rearranging tabs and being able to execute with shift + carriage return, that would make this extremely usable for hand held demonstrations

**Comment by jasongrout** [comment] 2019-10-01 22:20
I think the notebook toolbar has a play button that can be used to execute cells as well.

**Comment by telamonian** [comment] 2019-10-01 22:34
Ooo, maybe we could come up with a canonical "run + advance" gesture. Does anyone in the community have mobile dev experience? Is this kind of stuff easier to do on iOS or Android?

**Comment by mathematicalmichael** [comment] 2019-10-01 23:23
> I think the notebook toolbar has a play button that can be used to execute cells as well.

Yup that’s its saving grace for sure.

**Comment by BlueRhino** [comment] 2019-12-17 15:36
I have been paying attention to this issue. Is there any alternative to right-clicking?

**Comment by BrianChevalier** [comment] 2020-03-18 20:16
HUGE update on iPadOS! A mouse/trackpad works like a regular cursor that does hovering, supports right click and supports rearranging tabs! These features require a pointing device and don’t work with touch but they’re now possible! This is available in iOS 13.4 available for the public next week!

https://twitter.com/_brianchevalier/status/1240370028643377152?s=21

**Comment by jasongrout** [comment] 2020-03-18 22:47
This is so great to hear. Thanks for sharing!

**Comment by urfdvw** [comment] 2020-03-26 17:16
As iPadOS 13.4 arrive, secondary clock and drag ability is added to cursor. Jupyter lab is fully usable now.

**Comment by jtpio** [comment] 2020-04-23 15:37
One big use case for sticking to the classic notebook is the ability to use it from a phone, and be able to run cells by repeatedly clicking on the run button. An concrete example would be checking the status of a long computation (or rerunning some cells) while out on a lunch break.

The classic notebook renders quite nicely on a mobile phone:

![image](https://user-images.githubusercontent.com/591645/80117966-199d3100-8588-11ea-9d03-1880cc6aa2fd.png)

However in the case of lab it's much harder to see the content and run cells from a phone:

![image](https://user-images.githubusercontent.com/591645/80117848-f3779100-8587-11ea-9fa5-2853d76786d7.png)

Switching to landscape mode helps a bit but a lot of the vertical space becomes unusable.

**Comment by blink1073** [comment] 2020-04-23 15:39
From the above difference it sounds like we could respond to a small screen size by collapsing side panels and moving the prompt above the cell and regain parity.

**Comment by jtpio** [comment] 2020-04-23 15:44
We should also look into making the toolbar scrollable (or on multiple lines) to be able to reach the buttons on the right side.

**Comment by blink1073** [comment] 2020-04-23 16:32
Right, I was being a bit hand-wavy, there would certainly be more dedicated UX and implementation work needed.

**Comment by JasonWeill** [comment] 2023-02-15 17:32
Between improvements in JupyterLab and iOS/iPadOS/Android/etc, JupyterLab is much more usable on mobile and tablet devices now compared with when this issue was opened.

Closing this issue, but please open more issues if you see any other bugs affecting mobile or tablet. Thanks!

**Closed by JasonWeill** 2023-02-15 17:32 UTC
Labels: tag:Feature Parity, tag:Design and UX, pkg:notebook, pkg:application, tag:Mobile
