### ISSUE TITLE
repeated request to rebuild with lab

### ISSUE THREAD

**Issue by cekees** [jupyterlab/jupyterlab#3731] opened 2018-01-26 12:46 UTC
I'm getting repeated "build recommended" requests

![buildrecommended](https://user-images.githubusercontent.com/613654/35440347-4a1e6cf4-029f-11e8-9e34-7d87d653aa87.png)

![laberror](https://user-images.githubusercontent.com/613654/35440294-0b76d162-029f-11e8-93f8-374aaa9f6c80.png)

**Comment by vidartf** [comment] 2018-01-29 17:27
If you are using the beta release of pythreejs, this is a know issue that will be fixed before release. If not, I'm not sure what it is.

**Comment by blink1073** [comment] 2018-01-29 17:29
The problem is that the uglify plugin requires node 4.8, while before our minimum version was set by yarn at 4.0.  We need to check the node version explicitly as we did previously.

**Closed** 2018-02-04 01:20 UTC
Labels: tag:Build System, type:Bug
