### ISSUE TITLE
Variable assignment is in Chinese, and breakpoint debugging is not allowed.

### ISSUE THREAD

**Issue by GreatBoy** [jupyterlab/jupyterlab#11423] opened 2021-11-10 03:16 UTC
### Problem

Variable assignment is in Chinese, and breakpoint debugging is not allowed. For example:
![image](https://user-images.githubusercontent.com/11404895/141042897-fc9a7f83-3ced-49f0-ba21-10a80c576c5c.png)

If code has not Chinese, this is can be add breakpoint.

![image](https://user-images.githubusercontent.com/11404895/141042813-75074e31-2768-4f36-80a1-8e256e45d9ec.png)

### Proposed Solution
When there is Chinese in the code, it's great to support debugging.

**Comment by franckchen** [comment] 2021-11-12 09:04
Encountered the same problem, I looked at the code. Bcz of cell is not a file, but DAP need to debug by file. so jupyterlab need to calculate cell code by murmur2 hash to a unique file temp. and i the the murmur2 hash has implement twice, python and js. However, the calculation results of the two are different. so....

**Comment by jtpio** [comment] 2021-11-12 17:29
Thanks @GreatBoy @franckchen for reporting.

Linking to https://github.com/jupyterlab/jupyterlab/pull/9158 as related, which should have fixed such issues.

I just tested with JupyterLab 3.2.3 and the `xeus-python` and `ipykernel` kernels:

https://user-images.githubusercontent.com/591645/141509196-a8caa9ef-c94c-40f7-8073-4e51eeb9e3b4.mp4

This seems to be working fine with `xeus-python` as the kernel. So maybe the issue is with the implementation of the murmur2 hash function in `ipykernel`?

**Comment by franckchen** [comment] 2021-11-16 09:30
> This seems to be working fine with `xeus-python` as the kernel. So maybe the issue is with the implementation of the murmur2 hash function in `ipykernel`?

yes, i think this problem is about murmur2 implements in python. 
I found x-python i found murmur2 relevant code. https://github.com/jupyter-xeus/xeus/blob/4d9ad257b2b580c303b3c682f2cfd9d947548d9f/src/xsystem.cpp#L124

but in ipykernel. i cant find any results through search murmur2 keyword

**Comment by jtpio** [comment] 2021-11-16 09:40
cc @JohanMabille who might know about the differences between the xeus-python and ipykernel implementations

**Comment by franckchen** [comment] 2021-11-18 02:27
My colleagues has fixed this bug. 

https://github.com/ipython/ipykernel/pull/801

**Comment by jtpio** [comment] 2021-11-18 09:45
Nice thanks for reporting here!

Closing since this is tracked in `ipykernel` and being fixed there: https://github.com/ipython/ipykernel/pull/801

**Closed by jtpio** 2021-11-18 09:45 UTC
Labels: bug, pkg:debugger
