### ISSUE TITLE
Julia Syntax Highlighting

### ISSUE THREAD

**Issue by tristanc** [jupyterlab/jupyterlab#8267] opened 2020-04-24 02:33 UTC
## Description

Sometimes the text in cells in Julia disappear.  If I change the cell type to markdown or raw, the text re-appears, but if I change it back to code, it disappears again.  If I change kernel to python, for example, the code re-appears; it disappears if I change kernel back to Julia.

I believe it's a bug in the syntax highlighting code.  There was a fix for a julia language problem in a recent version of codemirror (5.53.0) -- perhaps it is the same issue.

## Reproduce

Make a new julia notebook.  
Paste into cell:  
        return (β-β2) * ((lockidx-min(t,lockidx))/10)^.05 + β2  

Cell should disappear.  It works if you have a leading "0" before the decimal point.

Paste: 
       return (β-β2) * ((lockidx-min(t,lockidx))/10)^0.05 + β2

Cell should stay, with correct syntax highlighting.

## Context

jupyter --version
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.3
ipython          : 7.13.0
ipykernel        : 5.2.1
jupyter client   : 6.1.3
jupyter lab      : 2.1.0
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.6
traitlets        : 4.3.3

Ubuntu 18.04.3 LTS
Firefox 74.0.1

**Comment by jasongrout** [comment] 2020-04-24 22:11
I see these errors in the js console when reproducing this: Error: Mode julia failed to advance stream.

It looks like this particular bug may be fixed in CodeMirror 50.0:

> julia mode: Don't break on zero-prefixed integers.

**Comment by jasongrout** [comment] 2020-04-24 22:12
I think the fix would be upgrading CodeMirror. Setting this as a good first issue: I think it may be as simple as running `jlpm run update:dependency codemirror`, then testing, committing, and pushing a PR. Do you want to try it?

**Comment by tristanc** [comment] 2020-04-25 22:14
Thanks for verifying! I get the same js console error. I don't have a dev install, so I don't think I can test the update, though.

**Comment by JiangXL** [comment] 2020-04-26 13:53
In my case, code in cell will disappear when I type number at line beginning inside a loop:
``` julia
for i in 1:3
     0
end
```
(Although Julia doesn't accept that variance begins with number)

**Comment by telamonian** [comment] 2020-04-28 07:06
This should be fixed by #8293, which is now merged into master

**Closed** 2020-04-29 14:22 UTC
Labels: good first issue
