### ISSUE TITLE
Shortcut for closing the sidebar

### ISSUE THREAD

**Issue by sccolbert** [jupyterlab/jupyterlab#2505] opened 2017-06-21 18:12 UTC
It would be nice to have a command/shortcut for closing the sidebar. Something like `Escape` which only applies if nothing else more specific should happen on `Escape`.

**Comment by stephenholtz** [comment] 2017-06-22 00:23
@sccolbert what about something like `⌘ + Esc` Both in the editors with Vim and in the notebooks I tend to use `Esc` quite a bit. It could get kind of obnoxious if this flipped the sidebar down unintentionally, e.g. if I didn't know what was in focus.

**Comment by ellisonbg** [comment] 2017-12-19 06:41
Closing as duplicate of #3393

**Closed by ellisonbg** 2017-12-19 06:41 UTC
Labels: tag:Design and UX, type:Enhancement
