### ISSUE TITLE
Printing support

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#4096] opened 2018-03-03 01:22 UTC
If one tries to print the classic notebook from the browser, the pdf only contains the open document. The jupyterlab v0.31 renders the whole UI in the print view instead.

**Comment by saulshanabrook** [comment] 2018-11-29 20:35
Closing as duplicate of https://github.com/jupyterlab/jupyterlab/issues/1314

**Closed by saulshanabrook** 2018-11-29 20:35 UTC
Labels: pkg:notebook, tag:Feature Parity, type:Enhancement
