### ISSUE TITLE
Add a shortcut to shutdown the notebook

### ISSUE THREAD

**Issue by benlindsay** [jupyterlab/jupyterlab#4390] opened 2018-04-14 18:46 UTC
The `CMD-S` and `CTRL-Q` keyboard shortcuts for save and close are great, but I don't see a shortcut for shutting down the notebook. Is there one that I've missed? Honestly I personally very rarely want to close a notebook without shutting it down completely, so I'd prefer if `CTRL-Q` closed and shutdown the notebook, or at least if there there was an option to tell it to do that. Any help here would be appreciated.

Thanks!

**Comment by telamonian** [comment] 2018-04-30 08:16
This seems to me like a basic necessity that needs to be added sooner rather than later. I'm sure part of the issue is deciding on a button convention. I'd personally favor something along the lines of

- `^W`: close notebook tab (ie what `^Q` does now)
- `^Q`: close notebook tab and shutdown kernel

This layout would have the virtue of preserving the semantics of the W (close window) and Q (quit program) shortcuts that exist across pretty much every OS.

**Comment by benlindsay** [comment] 2018-04-30 10:10
Sounds reasonable to me!

**Comment by ian-r-rose** [comment] 2018-09-06 21:00
There is a "Close and shutdown" item in the File menu which does what you are suggesting. It currently doesn't have a keyboard shortcut, but you could assign one to it using the advanced settings editor.

I also think it would be reasonable to have something like `Accel Shift Q` to do this as a default. Keep in mind that these shortcuts (particularly `Accel Q` and `Accel W`) may not work on all browsers/OSs. I, for instance, can't use either, since Firefox reserves those on my machine.

Marking as a good first issue.

**Comment by blink1073** [comment] 2018-10-26 14:05
Here is the command: 

https://github.com/jupyterlab/jupyterlab/blob/3a87d085716d433bea030593d8611e7ac1b6defc/packages/mainmenu-extension/src/index.ts#L52

We need to add an entry for that command in our shortcuts file:

https://github.com/jupyterlab/jupyterlab/blob/master/packages/shortcuts-extension/schema/plugin.json#L420

**Closed** 2018-10-27 01:50 UTC
Labels: DISC2018, good first issue, pkg:notebook
