### ISSUE TITLE
Routing short-circuit prevents /lab/tree from opening notebook

### ISSUE THREAD

**Issue by thoralf-gutierrez** [jupyterlab/jupyterlab#8359] opened 2020-05-03 21:23 UTC
## Description

I have written a server extension that downloads a notebook and then redirects the user to `/lab/tree/path/to/notebook.ipynb` to open the notebook.

When the user gets redirected, an additional redirection occurs, and the user gets redirected to `/lab/workspaces/auto-X/tree/path/to/notebook.ipynb?clone`.

At this point there is no more redirections, and the tab of the notebook does not open, and I notice this console log :
```
Routing /lab/workspaces/auto-X/tree/path/to/notebook.ipynb?clone was short-circuited by apputils:load-statedb
```

The log line seems to be coming from here
https://github.com/jupyterlab/jupyterlab/blob/v2.1.1/packages/application/src/router.ts#L165

If I refresh the tab with `/lab/workspaces/auto-X/tree/path/to/notebook.ipynb?clone`, then it works: the URL changes to `/lab/workspaces/auto-X` and the notebook is open.

I am seeing the issue with JupyterLab 2.1.1, but this was working well with JupyterLab 1.2.4.

Does someone know what could be going on in the routing for the short-circuit to happen? Does someone know where I can find the javascript locally so I can add more log lines to better understand what is going on?

## Reproduce

1. Go to `/lab/tree/path/to/notebook.ipynb` and wait to be redirected to a new workspace
2. Notice the notebook did not open
3. Open browser console, and notice the "routing was short-circuited" log.

## Expected behavior

The redirection to a workspace is fine but the routing should continue through and open the notebook.

## Context

- Operating System and version:  Ubuntu 16.04
- Browser and version: Chrome 81.0.4044.129
- JupyterLab version: 2.1.1

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/home/user/bin
	/home/user/.local/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/snap/bin

sys.path:
	/usr/local/bin
	/usr/local/lib/python36.zip
	/usr/local/lib/python3.6
	/usr/local/lib/python3.6/lib-dynload
	/usr/local/lib/python3.6/site-packages

sys.executable:
	/usr/local/bin/python3.6

sys.version:
	3.6.10 (default, May  2 2020, 14:29:12)
	[GCC 5.4.0 20160609]

platform.platform():
	Linux-4.4.0-124-generic-x86_64-with-debian-stretch-sid

which -a jupyter:
	/usr/local/bin/jupyter

pip list:
	Package                        Version
	------------------------------ --------------
	alembic                        1.4.2
	appdirs                        1.4.3
	async-generator                1.10
	attrs                          19.3.0
	backcall                       0.1.0
	bleach                         3.1.5
	certifi                        2020.4.5.1
	certipy                        0.1.3
	cffi                           1.14.0
	chardet                        3.0.4
	cloningtool                    0.1.5
	colorama                       0.4.3
	cryptography                   2.9.2
	decorator                      4.4.2
	defusedxml                     0.6.0
	distlib                        0.3.0
	entrypoints                    0.3
	filelock                       3.0.12
	gitdb                          4.0.4
	GitPython                      3.1.1
	idna                           2.9
	importlib-metadata             1.6.0
	importlib-resources            1.5.0
	ipykernel                      5.2.1
	ipython                        7.14.0
	ipython-genutils               0.2.0
	ipywidgets                     7.5.1
	isort                          4.3.21
	jedi                           0.17.0
	Jinja2                         2.11.2
	json5                          0.9.4
	jsonschema                     3.2.0
	jupyter                        1.0.0
	jupyter-client                 6.1.3
	jupyter-console                6.1.0
	jupyter-core                   4.6.3
	jupyter-telemetry              0.1.0
	jupyterhub                     1.1.0
	jupyterhub-ldapauthenticator   1.0
	jupyterhub-tesla-authenticator 2.1.10.post859
	jupyterlab                     2.1.1
	jupyterlab-code-formatter      1.2.5
	jupyterlab-git                 0.10.1
	jupyterlab-server              1.1.1
	jupyterlab-templates           0.2.3
	ldap3                          2.7
	Mako                           1.1.2
	MarkupSafe                     1.1.1
	mistune                        0.8.4
	nbconvert                      5.6.1
	nbdime                         2.0.0
	nbformat                       5.0.6
	nbresuse                       0.3.4
	nbserverproxy                  0.8.8
	notebook                       6.0.3
	oauthenticator                 0.7.3
	oauthlib                       3.1.0
	packaging                      20.3
	pamela                         1.0.0
	pandocfilters                  1.4.2
	param                          1.9.3
	parso                          0.7.0
	pexpect                        4.8.0
	pickleshare                    0.7.5
	pip                            20.1
	prometheus-client              0.7.1
	prompt-toolkit                 3.0.5
	ptyprocess                     0.6.0
	pyasn1                         0.4.8
	pycparser                      2.20
	Pygments                       2.6.1
	PyJWT                          1.7.1
	pyOpenSSL                      19.1.0
	pyparsing                      2.4.7
	pyrsistent                     0.16.0
	python-dateutil                2.8.1
	python-editor                  1.0.4
	python-json-logger             0.1.11
	pyviz-comms                    0.7.4
	pyzmq                          19.0.0
	qtconsole                      4.7.3
	QtPy                           1.9.0
	requests                       2.23.0
	ruamel.yaml                    0.16.10
	ruamel.yaml.clib               0.2.0
	Send2Trash                     1.5.0
	setuptools                     40.6.2
	six                            1.14.0
	smmap                          3.0.2
	SQLAlchemy                     1.3.16
	terminado                      0.8.3
	testpath                       0.4.4
	tornado                        6.0.4
	traitlets                      4.3.3
	urllib3                        1.25.9
	virtualenv                     20.0.18
	wcwidth                        0.1.9
	webencodings                   0.5.1
	widgetsnbextension             3.5.1
	yapf                           0.28.0
	zipp                           3.1.0
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[D 14:21:20.564 LabApp] Searching ['/home/user', '/home/user/.jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 14:21:20.565 LabApp] Looking for jupyter_config in /etc/jupyter
[D 14:21:20.565 LabApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 14:21:20.565 LabApp] Looking for jupyter_config in /home/user/.jupyter
[D 14:21:20.565 LabApp] Looking for jupyter_config in /home/user
[D 14:21:20.566 LabApp] Looking for jupyter_notebook_config in /etc/jupyter
[D 14:21:20.567 LabApp] Loaded config file: /etc/jupyter/jupyter_notebook_config.py
[D 14:21:20.567 LabApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 14:21:20.567 LabApp] Loaded config file: /usr/local/etc/jupyter/jupyter_notebook_config.json
[D 14:21:20.567 LabApp] Looking for jupyter_notebook_config in /home/user/.jupyter
[D 14:21:20.567 LabApp] Looking for jupyter_notebook_config in /home/user
[D 14:21:20.569 LabApp] Raising open file limit: soft 1024->4096; hard 1048576->1048576
[D 14:21:20.573 LabApp] Paths used for configuration of jupyter_notebook_config:
    	/etc/jupyter/jupyter_notebook_config.json
[D 14:21:20.573 LabApp] Paths used for configuration of jupyter_notebook_config:
    	/usr/local/etc/jupyter/jupyter_notebook_config.json
[D 14:21:20.574 LabApp] Paths used for configuration of jupyter_notebook_config:
    	/home/user/.jupyter/jupyter_notebook_config.json
[I 14:21:21.166 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.6/site-packages/jupyterlab
[I 14:21:21.166 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[D 14:21:21.347 LabApp] Using default logger
[D 14:21:21.347 LabApp] Using default logger
[D 14:21:21.347 LabApp] Using default logger
[D 14:21:21.347 LabApp] Using default logger
[I 14:21:21.354 LabApp] Serving notebooks from local directory: /home/user
[I 14:21:21.354 LabApp] The Jupyter Notebook is running at:
[I 14:21:21.354 LabApp] http://localhost:8888/?token=REDACTED
[I 14:21:21.354 LabApp]  or http://127.0.0.1:8888/?token=REDACTED
[I 14:21:21.354 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 14:21:21.358 LabApp] No web browser found: could not locate runnable browser.
[C 14:21:21.358 LabApp]

    To access the notebook, open this file in a browser:
        file:///home/user/.local/share/jupyter/runtime/nbserver-22687-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=REDACTED
     or http://127.0.0.1:8888/?token=REDACTED
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
index.js:31 hub-extension: Found configuration  ObjecthubHost: ""hubPrefix: "/hub/"__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
index.js:50 Starting application in workspace: "/lab/workspaces/auto-X"
router.js:131 Routing /lab/workspaces/auto-X/tree/path/to/notebook.ipynb?clone was short-circuited by apputils:load-statedb</pre>
</details>

**Comment by jasongrout** [comment] 2020-05-05 22:37
Assigned to 3.0 since it seems like a significant regression from 1.x

**Comment by ellisonbg** [comment] 2020-09-13 17:31
Fixed in master, closing.

**Closed by ellisonbg** 2020-09-13 17:31 UTC
