### ISSUE TITLE
Shift-tab unindent vs. docstring/signature information

### ISSUE THREAD

**Issue by schmidi314** [jupyterlab/jupyterlab#15901] opened 2024-03-03 11:55 UTC
## Description

Shift-tab has (at least) two functions: (1) unindenting one level and (2) showing signature and docstring of a function. If typed inside of an indented function

![Peek 2024-03-03 12-54](https://github.com/jupyterlab/jupyterlab/assets/74381262/eaeb403b-0fac-4cbc-be7c-9df0294ba214)

## Reproduce

1. New notebook
2. Define some function 
```
def test(a,b):
    print(a, b)
```
3. Use test(a,b) indented
```
if True:
    test(a, b)
```
4. With cursor inside `test(a,b)` parentheses, hit shift-tab. --> info is shown AND test is unindented

## Expected behavior

Only info should be shown. NO un-indentation.

## Context

- Operating System and version: Linux and Windows tried
- Browser and version: Firefox
- JupyterLab version: 4.1.2

**Comment by krassowski** [comment] 2024-03-03 12:50
@schmidi314 thanks for opening the issue, I believe this is a duplicate of https://github.com/jupyterlab/jupyterlab/issues/15821 (regression in 4.1); there is a pull request fixing it (https://github.com/jupyterlab/jupyterlab/pull/15898) - help in review of the PR would be appreciated!

**Comment by schmidi314** [comment] 2024-03-03 16:33
Ah yes, @krassowski you're right. My apologies. I didn't understand the word "dedent" :)

I tried your PR via binder and it solves my problem. Thanks for tackling this! Is there anything I can do? (you mentioned help in review..??) Unfortunately I'm pretty busy these days so I couldn't really get active in this repo like I planned.

**Comment by krassowski** [comment] 2024-03-03 17:21
Thanks @schmidi314! If you could leave a review comment on https://github.com/jupyterlab/jupyterlab/pull/15898 just saying that you tried this via binder and it does the intended thing it would already be of a help to other reviewers as they no longer need to validate that it does the thing but only to look at the code to check if it looks right. Of course if you feel like looking at the code as well and leaving any comments that would be appreciated too but I was suggesting just testing it out and leaving a comment over in the PR :)

**Comment by krassowski** [comment] 2024-03-03 17:24
> I didn't understand the word "dedent" :)

It is confusing with so many code verbs used for roughly the same things ("dedent", "unindent", "outdent", "indent less")

**Comment by JasonWeill** [comment] 2024-03-05 17:12
Closing in favor of #15821.

**Closed by JasonWeill** 2024-03-05 17:12 UTC
Labels: bug, status:Duplicate, status:Needs Triage
