### ISSUE TITLE
Jupyterlab does not show anything in browser

### ISSUE THREAD

**Issue by minsuk1** [jupyterlab/jupyterlab#16389] opened 2024-05-29 08:22 UTC
jupyterlab 3.6.7
notebook 5.7.5
when i do some background work like 
[ python jupyter -nbconvert --execute - to notebook tmp.ipynb & ]
and i do F5 the browser is blank it keeps loading, how should i solve it

**Comment by krassowski** [comment] 2024-05-31 08:43
I would suggest trying a fresh installation of the latest version of JupyterLab (4.2.x) and checking if it still happens for you.

**Comment by JasonWeill** [comment] 2024-06-04 16:14
@minsuk1 Can you try using a newer version of JupyterLab?

**Comment by minsuk1** [comment] 2024-06-07 00:29
> @minsuk1 Can you try using a newer version of JupyterLab?
> 
> If the problem recurs, could you please provide info about which operating system (including version) and browser (including version) you're using? Does the issue persist after clearing your cache/history? Thanks!

i did version up,to 4.2.1. and python version 3.11
it still doesn't work keep hanging

**Comment by minsuk1** [comment] 2024-06-13 00:21
> Hi @minsuk1, just to clarify, doing a fresh installation of JupyterLab and clearing your browser cache/history did not resolve this issue right? Do you see an error in the terminal where you are running the nbconvert command, or the console where you load the page?
> 
> I was able to install JupyterLab 3.6.7 and Notebook 5.7.5 and run the command `jupyter nbconvert --execute --to notebook tmp.ipynb &` then start JupyterLab in a Chrome browser where the page loaded. I am using MacOS Ventura and Chrome Version 125.0.6422.142 (Official Build) (arm64)

i changed the command to "jupyter lab --core -mode ~~" after that the frequency of hanging is very low but it still sometimes occurs. not only using nbconvert. i did fresh installation and clearing cache and history

**Comment by JasonWeill** [comment] 2024-06-18 16:08
When you're running these commands, are you running them in a terminal inside JupyterLab, or are you running them in a separate terminal on your computer? In Activity Monitor, do you see a high level of CPU usage and memory usage? If so, is this by Jupyter or another process? If you close other resource-intensive processes, do you still see this problem?

**Comment by minsuk1** [comment] 2024-06-20 05:56
> When you're running these commands, are you running them in a terminal inside JupyterLab, or are you running them in a separate terminal on your computer? In Activity Monitor, do you see a high level of CPU usage and memory usage? If so, is this by Jupyter or another process? If you close other resource-intensive processes, do you still see this problem?

no there's no any process except jupyterlab

**Comment by JasonWeill** [comment] 2024-06-25 16:07
Do you still see this bad behavior if you run `jupyter lab` with no additional options?

**Comment by JasonWeill** [comment] 2024-07-02 16:09
@minsuk1 Can you provide info about which browser, including version, you see this issue with? Do you still see the same issue if you disable extensions in the browser or run it in private mode / incognito / safe mode? Do you see this with any other browsers on your system?

**Comment by JasonWeill** [comment] 2024-07-09 16:05
Because we have not been able to reproduce this issue, and we haven't received responses to the questions above, I'm going to close this issue. Please reopen or open a new issue if you notice any other issues with JupyterLab.

**Closed by JasonWeill** 2024-07-09 16:05 UTC
Labels: bug, status:Needs Info, status:Needs Triage
