### ISSUE TITLE
Workspaces Documentation - How to return to default workspace

### ISSUE THREAD

**Issue by jzf2101** [jupyterlab/jupyterlab#5378] opened 2018-09-25 01:22 UTC
When I try to get to the default worspace `/lab` I get the `please use a different workspace` message.  Our documentation doesn't make it clear how to keep using the main workspace.  Is there something we can to do make this clearer?  @afshin ?

**Comment by jasongrout** [comment] 2018-09-25 03:29
That message should only pop up if you have that workspace open in another tab. Do you have the default `/lab` workspace open in another tab?

**Comment by jzf2101** [comment] 2018-09-25 14:52
It claims I do but I don't so I assumed it was a bug.

**Comment by jasongrout** [comment] 2018-09-25 16:14
It would be a bug if you don't. When I've been surprised by this warning, it was because I had a session open in another browser window hidden behind something. 

Can you narrow down instructions so we can reproduce it?

**Comment by agoose77** [comment] 2018-09-28 08:51
I also have this issue, fresh from OS restart (that is, no Jupyter instances have yet been running). Can't add much in terms of reproducibility, but I'll take a look.
` angus@angus-Inspiron-7559  ~/Documents/notebooks  jupyter --version
4.4.0
 angus@angus-Inspiron-7559  ~/Documents/notebooks  jupyter lab --version
0.34.12
 angus@angus-Inspiron-7559  ~/Documents/notebooks  



`

**Comment by agoose77** [comment] 2018-09-28 08:56
It seems that every time I kill Jupyter with CTRL+C from the terminal, upon relaunching Jupyterlab the previous session remains "in-use" despite no instances of any Jupyter process(es) from the previous session still running.

**Comment by koustuvsinha** [comment] 2018-10-11 23:41
I have this issue as well. Intermittently it just asks me to rename a new workspace, and keeps asking so even when i provide a new name. Running the-littlelest-jupyter-hub on Ubuntu 18.04, GCP. Client using Firefox

![screenshot from 2018-10-11 19-36-05](https://user-images.githubusercontent.com/5122822/46839753-7877cc80-cd8d-11e8-89c5-c32354421216.png)

**Comment by jwlockhart** [comment] 2018-11-18 16:31
I am also having this issue with a newer version of jupyter lab. I ended a jupyter lab session with ^C, and when I relaunch it says the workspace is already in use by another window. Deleting the contents of `~/.jupyter/lab/workspaces` had no effect.

```
$ jupyter --version
4.4.0
$ jupyter lab --version
0.35.3
```

**Comment by sashaostr** [comment] 2018-12-09 12:44
same problem here.
$ jupyter lab --version
0.35.3
$ jupyter --version
4.4.0

**Comment by choldgraf** [comment] 2018-12-21 21:05
just a note that this issue has come up in nbgitpuller as well (https://github.com/jupyterhub/nbgitpuller/issues/57). If students have an already-running jupyterlab session (which is common in teaching) and then they click an `nbgitpuller` link, then it'll open in a new tab and give them the "change workspaces" dialog

**Comment by daliati** [comment] 2019-02-26 17:17
I am having the same issue running lab on the hub. Even after restarting the server. Even after restarting the server and removing ~/.jupyter/lab/workspaces

**Comment by kaandocal** [comment] 2019-05-27 09:30
I have been encountering the same problem for the past few months, with Jupyter asking me to provide a new workspace name repeatedly without success. Is there any progress on this issue? 

(Jupyter v4.4.0, JupyterLab v0.35.4)

**Comment by jasongrout** [comment] 2019-05-27 14:57
On master now, it will automatically create a new workspace instead of asking you for a name.

**Comment by stephan-jacobs** [comment] 2019-07-12 01:56
For what it's worth, I had this happen on the latest version of jupyterlab when my browser was set to block all cookies. I don't really have an issue with that though, I just figured I'd mention it if anyone comes across this in the future. 
To fix it I just changed the setting to allow cookies and then I installed a content blocker :)

**Comment by ibqn** [comment] 2019-12-27 15:22
> On master now, it will automatically create a new workspace instead of asking you for a name.

Starting from which version? can this be easily back-ported to other jupyterlab versions, say, 0.35.7?

**Comment by afshin** [comment] 2019-12-27 15:26
This is a 1.x feature. We have recently released a beta for 2.0 and plan to release 2.0 final in the next couple weeks. Our target is to release two major versions per year. Back-porting this feature to the 0.35.x branch would be non-trivial.

**Comment by jasongrout** [comment] 2020-02-05 22:04
Closing, with the suggestion to upgrade to JupyterLab 1.0 or the upcoming 2.0.

**Closed by jasongrout** 2020-02-05 22:04 UTC
Labels: status:Needs Info, tag:Documentation, type:Bug
