### ISSUE TITLE
Edit<Find: The option to select a single cell to make changes has disappeared.

### ISSUE THREAD

**Issue by akitxu** [jupyterlab/jupyterlab#14769] opened 2023-06-28 21:02 UTC
Dear all.
Until recently, by selecting "Edit<Find", in the window that opened, Icould choose to modify the selected value, in all the cells of the notebook, or only in one cell. 
For a short time, and I don't know why, this possibility no longer appears, so the change is made to me in all the matches it finds in all the columns of the DataFrame. What can be the cause?. What I can do?. I will appreciate help.

**Comment by krassowski** [comment] 2023-06-28 21:09
I presume you updated to JupyterLab 4. It is still there in JupyterLab 4.0, you need to click on the filters icon (previously it was under three dots), see https://github.com/jupyterlab/jupyterlab/pull/14090
Can you see the filters button? If it is not there please provide more details (version, screenshot).

**Comment by akitxu** [comment] 2023-06-29 08:18
krassowski . Thank you. Indeed, the click on the filters icon replaces the three previous points.

**Comment by JasonWeill** [comment] 2023-06-30 20:19
Thanks @krassowski ! Closing as by design in JupyterLab 4.

**Closed by JasonWeill** 2023-06-30 20:19 UTC
Labels: bug, status:Needs Triage
