### ISSUE TITLE
Auto Close Brackets not works in Code Console

### ISSUE THREAD

**Issue by GF-Huang** [jupyterlab/jupyterlab#10882] opened 2021-08-20 17:09 UTC
![image](https://user-images.githubusercontent.com/4510984/130269170-a0c51884-cb52-442a-86a3-93adaa464f9c.png)

It does not auto add the `)`, why?

![image](https://user-images.githubusercontent.com/4510984/130269205-bbfb8e3a-11a0-4f8a-b846-b7d627a890ef.png)

![image](https://user-images.githubusercontent.com/4510984/130269246-f37c4b0f-e726-4fad-aa47-0342f519eb5b.png)

![image](https://user-images.githubusercontent.com/4510984/130269265-9642744a-51a8-49a6-9836-8e74d1215a4f.png)

**Comment by krassowski** [comment] 2021-08-21 15:19
@GF-Huang thanks for reporting it. This looks like a duplicate of #10874, can you please confirm whether this is correct?

**Comment by GF-Huang** [comment] 2021-08-21 15:22
Yes.

**Comment by krassowski** [comment] 2021-08-21 15:47
Thank you. I will close this one to focus the discussion in #10874.

**Closed by krassowski** 2021-08-21 15:47 UTC
Labels: bug, status:Duplicate
