### ISSUE TITLE
Collapsing Output cells - Downgrade from Notebook

### ISSUE THREAD

**Issue by phil-zxx** [jupyterlab/jupyterlab#5897] opened 2019-01-22 11:39 UTC
Hi,

Is it possible to collapse the output cell in Jupyter Lab, while still showing some of the output?

In **Jupyter notebook** you can click on the white area under `Out[XX]:` to collapse the output:

![image](https://user-images.githubusercontent.com/32247590/51532972-79fb6b00-1e39-11e9-9c8d-6d94716da333.png)

In my opinion, **Jupyter Lab** has two issues here:
 1. To collapse the output one has to click on the blue line on the left of the output cell ("harder" to click there than it is in the notebook, because of the smaller surface area). Clicking anywhere in the white area is more efficient from an UI-point of view.
 2. Once collapsed the output is completely gone. It'd be nice to keep at least some of it (e.g. just show the first few lines, as is the case in jupyter notebook).

![image](https://user-images.githubusercontent.com/32247590/51533006-95667600-1e39-11e9-864a-6025288695e4.png)

As for point 2: a compromise could be to introduce several levels of "collapsation": *first click* = show first few lines, *second click* = just show ..., *third click* = show everything again

What do people think? Is there room for improvement?

---

My system:
- Windows 10
- Jupyter Lab 0.35.4

**Comment by telamonian** [comment] 2019-01-22 12:15
Would actual code folding meet your needs? That feature was just added to master a couple of days ago in #5761. It'll probably wind up in the release build in a month or two, but if you can't wait you can always go ahead and [build Jupyterlab from source](https://github.com/jupyterlab/jupyterlab/blob/master/CONTRIBUTING.md#installing-jupyterlab).

**Comment by phil-zxx** [comment] 2019-01-22 12:52
This is a great feature, but code folding only *folds the code*, not the *output*, or did I misunderstand this feature?

**Comment by telamonian** [comment] 2019-01-22 13:11
Whoops, didn't distinguish when I read your question. I'm not sure that this specific styling issue has come up before, but it's definitely possible that the height of a collapsed cell output can become a user defined option (via the settings editor).

It seems a little tricky to implement though, so it might not happen right away. The relevant code is in the `Collapser` class/subclasses in `packages/cells/src/collapser`. Currently the behavior of `Collapser` is to swap out the cell output node and replace it with a dummy node, rather than simply narrowing it.

**Comment by jasongrout** [comment] 2019-01-22 15:57
Also, in JLab, you can easily collapse/uncollapse or scroll/unscroll many outputs at once by selecting multiple cells and using the appropriate commands from the View menu or the right-click menu or the command palette.

**Comment by jasongrout** [comment] 2019-01-22 15:59
For more examples of how to do this, please see the videos in the JupyterLab documentation: https://jupyterlab.readthedocs.io/en/stable/user/notebook.html

(Search for "collapse" or "scroll" to find the two short screencasts covering this topic)

**Comment by phil-zxx** [comment] 2019-01-23 15:34
Thanks, Jason. I really like the idea of having collapsing & scrolling as 2 independent features.

Two questions though:
1. Are there keyboard shortcuts for toggling between scroll/unscroll? Having to first right click in the cell or having to click on View, and then "navigate" to the scroll entry, leaves room for improvement.
2. Is there a plan to enable users to toggle between scroll/unscroll as they could do in the notebook? (= clicking in the white space area on the left of the cell)

**Comment by jasongrout** [comment] 2019-01-23 16:38
> Are there keyboard shortcuts for toggling between scroll/unscroll? Having to first right click in the cell or having to click on View, and then "navigate" to the scroll entry, leaves room for improvement.

This is discussed in https://github.com/jupyterlab/jupyterlab/issues/4028#issuecomment-450543292 (and the surrounding comments), and then discussed a bit more in https://github.com/jupyterlab/jupyterlab/pull/5817.

> Is there a plan to enable users to toggle between scroll/unscroll as they could do in the notebook? (= clicking in the white space area on the left of the cell)

There is general design review of the notebook interface mentioned in https://github.com/jupyterlab/jupyterlab/issues/1742, but I think that discussion is stalled right now. I don't know of any specific proposals to utilize that whitespace to scroll/unscroll the cells. Perhaps you can add your feedback in that issue?

**Comment by phil-zxx** [comment] 2019-01-23 16:57
https://github.com/jupyterlab/jupyterlab/issues/4028#issuecomment-450543292 is nice, but it's even better when combined with #5817. I can see how "toggle status could be indeterminate", but you could simply default to either scroll or unscroll when this happens (alternatively, just default to the first cell's status). Is this an option?

**Comment by jasongrout** [comment] 2019-01-23 21:30
I think there are very established ways of working with toggling state and multiple items. It would be good to have an overview of them, and especially on the edge cases.

**Comment by zertrin** [comment] 2019-01-26 03:35
I am also a big proponent for using the whitespace to scroll/unscroll cells as my impression from using it and seeing other colleagues use it is that it is quite intuitive for new users and at the same time very practical (easy to click, because of the large area). No new user would use right click for this (actually, non-expert users rarely ever use right click) and thus will never discover it.

**Comment by phil-zxx** [comment] 2019-02-14 16:14
Any update on this?

**Comment by jasongrout** [comment] 2019-02-14 17:20
I don't think there's any update beyond the conversation above. #5817 is now released in the 1.0 prerelease.

**Comment by jasongrout** [comment] 2019-02-14 17:23
It seems there are two things unresolved above: using whitespace to scroll/unscroll cells, for which the following comment above applies:

> There is general design review of the notebook interface mentioned in #1742, but I think that discussion is stalled right now. I don't know of any specific proposals to utilize that whitespace to scroll/unscroll the cells. Perhaps you can add your feedback in that issue?

And there's also the suggestion: 

> [#4028 (comment)](https://github.com/jupyterlab/jupyterlab/issues/4028#issuecomment-450543292) is nice, but it's even better when combined with #5817. I can see how "toggle status could be indeterminate", but you could simply default to either scroll or unscroll when this happens (alternatively, just default to the first cell's status). Is this an option?

For which the next step is (probably on a new issue):

> I think there are very established ways of working with toggling state and multiple items. It would be good to have an overview of them, and especially on the edge cases.

**Comment by Linusnie** [comment] 2020-02-27 09:59
Wouldn't it be possible to add back the option to click the "sidebar" (highlighted in the picture) to enable/disable the scrolling in the same way that it was working in Notebooks? Clicking the blue bar could still hide the output completely without a change. This way both options are there

This is the main issue keeping me from moving completely to jupyterlab at the moment

![Screenshot from 2020-02-27 10-51-54](https://user-images.githubusercontent.com/12471058/75432888-6a5d2880-594f-11ea-8818-61cfb93e2cf3.png)

**Comment by jvaldiviezo9** [comment] 2020-04-07 02:21
Any update on this? I think this will be very useful as well the option to limit the output to some amount or characters to avoid overload the browser.

**Comment by jasongrout** [comment] 2020-04-07 05:01
CC @tgeorgeux - any update on designs for these sorts of things in the notebook?

**Comment by louis925** [comment] 2020-04-27 02:02
Any update on this? This is the main issue preventing me from switching to jupyterlab.

**Comment by orena1** [comment] 2020-11-25 18:42
I think there is a bit confusing here on what exactly is needed, 
As a first step I made this gif so it will be clear what is available:

![collapsing](https://user-images.githubusercontent.com/8983713/100269095-afee6680-2f5e-11eb-89d9-e3605f485a94.gif)

**Comment by zertrin** [comment] 2020-12-15 07:37
> I think there is a bit confusing here on what exactly is needed,
> As a first step I made this gif so it will be clear what is available:

I think https://github.com/jupyterlab/jupyterlab/issues/5897#issuecomment-591884430 sums it up.

Now it's easy to completely hide content by clicking on the blue bar, but toggling scrolled/un-scrolled is hidden in a right click menu which requires 2 clicks and mouse movement to select the correct menu element. That's quite unfriendly. We have been requesting to bring back the old behaviour of clicking on the blank space to toggle this for quite some time. Not sure what is blocking...

**Comment by goanpeca** [comment] 2020-12-15 14:51
Hi @zertrin, thanks for the input :) . We are looking into this with @isabela-pf evaluating options to improve the situation.

Cheers!

**Comment by mauhcs** [comment] 2021-01-31 10:23
JupiterLab is great, but the right-click for partially hide the output is quite disruptive. 
The `click in the blue bar to hide all` is awesome, though.

**Comment by phil-zxx** [comment] 2021-01-31 13:43
@goanpeca Appreciate you looking into this. Has there been any update on this?

**Comment by raghuvv** [comment] 2021-04-04 09:24
Clicking in the white space to enable/disable output scrolling on the selected cell output is a very useful and intuitive feature. Appreciate if it can be brought back to JupyterLab 

I don't mind the blue bar click feature to hide the entire output but the click target area especially when collapsed is rather small (inconvenient). On similar lines the scroll bar for a partially collapsed output cell is too think and the scrolltab is too small for a click and drag target.

**Comment by Zethson** [comment] 2021-04-09 10:03
I would also be happy if these features were using the same hotkeys as jupyter notebooks. E.g. shift + o should collapse the current cell.

**Comment by linminhtoo** [comment] 2021-06-16 10:08
Bumping this once again as it is such a lovely and useful feature of Jupyter Notebooks

**Comment by Marsdrummer** [comment] 2021-07-04 06:45
+1 on the request to make Lab act like Notebook in this feature. Also, the little ^ button via extension in the top nav bar to collapse is great.

**Comment by set92** [comment] 2021-08-19 10:18
@isabela-pf Is there any news on this? Maybe as a quick fix for 4.0 there could be an option in settings to enable by default "Enable scrolling for outputs" instead of needing to use the right-click menu to enable it per output cell?

**Comment by raghuvv** [comment] 2021-08-30 14:39
This is what I did in the meantime to avoid having to click enable scrolling on each cell:

1. INSTALL "Stylus" extension for Chrome
2. Add a custom CSS override for local JupyterLab URL with the following CSS snippet.

```
.jp-OutputArea-child {
    max-height: 15em;
}

.jp-OutputArea-child .jp-OutputArea-output {
    overflow: auto;
}
```

This is to automatically scroll the contents of cell outputs (without having to manually right-click and select "Enable Scrolling for Output").

In future updates to JupyterLab, I really hope this becomes a native setting.

**Comment by isabela-pf** [comment] 2021-08-31 14:25
@set92 sorry, I'm not actively working on this. At this point I'm not even sure why Gonzalo said I was. I'll stay subscribed to this issue and keep it on my list, but I honestly don't know when I will get to it. Sorry about that.

**Comment by twopwood** [comment] 2021-12-06 16:51
Is anyone currently looking into this?  It seems there are still a couple suggestions on this thread that are worth looking into.  I added one idea as [#11625](https://github.com/jupyterlab/jupyterlab/issues/11625).  Out of curiosity, are these features that could be added via extensions or is the behavior too fundamental?  Thanks.

**Comment by zertrin** [comment] 2021-12-13 04:37
Yes this is still the main blocker for me to start using jupyterlab, after all these years... Still hoping for some love to address this UX regression.

**Comment by krassowski** [comment] 2021-12-16 00:33
Given how many votes were cast in favour of this issue (including after the solution which is already available was described and the issue was assigned to Reference milestone), and that it would be needed to achieve feature parity with Notebook, I would like to propose we include this one in 4.0 milestone to discuss it further at a future triage meeting.

**Comment by jtpio** [comment] 2021-12-31 12:15
Posting some notes after quickly looking at how this could be implemented.

The classic notebook adds an overlay on top of the output prompts:

![image](https://user-images.githubusercontent.com/591645/147822636-0b703676-4960-4a0d-9d34-753142a7511e.png)

JupyterLab creates an `OutputPrompt` for each output:

![image](https://user-images.githubusercontent.com/591645/147822686-210bdae9-066f-44fe-97b1-2b2055436f09.png)

Probably this could then be implemented in JupyterLab by also adding an overlay that spans all the output prompts, and listening on the click event to toggle `cell.scrolled`. This overlay should however probably not be available on mobile (the layout is more compact on mobile, see https://github.com/jupyterlab/jupyterlab/pull/11762 for reference).

**Comment by rtaori** [comment] 2022-08-23 05:49
Just chiming in to bump on this issue. I have been a Notebook poweruser for multiple years, and recently decided to switch to Lab when I bought a new machine. The one click to enable/disable scroll is a crucial feature I relied on! It took me an hour before I stumbled on this thread and discovered there was a right click option for this - very unintuitive in my opinion. Could we please add this functionality back (as an optional setting at least)? Tying this to the 4.0 milestone would be great.

**Comment by PAGWatson** [comment] 2023-01-13 13:57
I also agree with those who would like functionality to automatically scroll long outputs. 

I tried @raghuvv 's solution using Stylus, but found an issue with that is that warnings produced by modules (and I use one module in particular that produces many warnings) seem to be treated as distinct from script output, so sections of script output divided by warning messages can become very long without being scrolled.

**Comment by krassowski** [comment] 2023-02-02 19:04
Let's keep this discussion about the collapsing improvement, there is a separate issue about automatically enabling scrolling for long outputs: https://github.com/jupyterlab/jupyterlab/issues/9673#issue-793851632

**Comment by krassowski** [comment] 2023-02-24 00:05
Ok, anyone interested please give #14072 a try on binder, follow this link: [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/krassowski/jupyterlab/collapse-output?urlpath=lab)

**Closed** 2023-02-24 12:24 UTC
Labels: enhancement, tag:Feature Parity, tag:Design and UX, pkg:notebook

**Comment by phil-zxx** [comment] 2023-02-24 14:46
Thank you so much, @krassowski. I am glad this issue finally found a resolution. After 4 years! :)
