### ISSUE TITLE
jupyterlab slow startup (along with dask issues) after upgrade on HPC platform

### ISSUE THREAD

**Issue by apatlpo** [jupyterlab/jupyterlab#4286] opened 2018-03-30 18:38 UTC
I am running jupyterlab along with a dask cluster on an HPC platform.
The deployment follows [that](https://pangeo-data.github.io/pangeo/setup_guides/cheyenne.html)

I am experiencing a significant slow down (seconds scale to minute scale) of jupyterlab start up after an upgrade from dask 0.15.4 / jupyterlab 0.29.1 to latest dask / jupyterlab 0.31.12 as well as more serious issues with dask/distributed.

@mrocklin encouraged me to mention the problem here as well on top of dask/distributed issue dask/distributed#1869 as he believe the problem may be related to something else like tornado

Does anybody has any advice on what I could try to do to diagnose what is going wrong ?

**Comment by saulshanabrook** [comment] 2018-09-10 17:06
I am not sure why JupyterLab would be slow to start unfortunately. I am closing this since I am not sure how to reproduce this behavior. Feel free to comment if you have more details.

**Closed by saulshanabrook** 2018-09-10 17:06 UTC
