### ISSUE TITLE
Images don't display with RTC enabled 

### ISSUE THREAD

**Issue by andrii-i** [jupyterlab/jupyterlab#16844] opened 2024-10-08 22:23 UTC
## Description
When RTC is enabled, images won't display.

## Reproduce

1. Install JupyterLab and jupyter-collaboration.
2. Open an image from the file browser.
3. See image not shown.

## Expected behavior

Images should be displayed.

## Context

Accordingly to this comment https://github.com/jupyterlab/jupyter-collaboration/issues/229#issuecomment-1877616229 by @davidbrochart 

> The problem is that the frontend asks for a document of type file, which corresponds to a [YUnicode](https://github.com/jupyter-server/jupyter_ydoc/blob/bd998983bbf6b566bb0314faa48b8e51ba7747b6/jupyter_ydoc/yunicode.py) shared document, but this doesn't handle binary data. Instead, it should ask for a blob which correspond to a [YBlob](https://github.com/jupyter-server/jupyter_ydoc/blob/bd998983bbf6b566bb0314faa48b8e51ba7747b6/jupyter_ydoc/yblob.py).

**Comment by davidbrochart** [comment] 2024-10-09 14:29
I think the problem is not only a matter of using `YBlob` instead of `YUnicode`, but also that the initial content of the shared document is empty, before being loaded from disk, which causes the image renderer to fail. We would need the image renderer to update to shared document updates, which is actually a requirement for it to be collaborative. Indeed we could imagine a JupyterLab image editor that could make changes to the image, and these changes should be rendered live on all clients.
So this requires changes both in jupyter-collaboration and jupyterlab.

**Comment by davidbrochart** [comment] 2024-10-09 20:47
Thinking about it, this would be a good use-case for [content providers](https://github.com/jupyterlab/jupyterlab/pull/16744).
A bitmap image is not really something we can collaborate on, at least at the byte level. It doesn't make sense for two users to change the same byte and expect CRDTs to resolve a conflict. On top of that, the default image opener is JupyterLab is a read-only renderer, which cannot edit the image.
Then it would make sense to open images in non-collaborative mode, just by having the RTC content provider filter out image files. This would nicely solve this issue.
cc @jtpio @krassowski

**Comment by davidbrochart** [comment] 2024-10-10 10:11
I opened https://github.com/jupyterlab/jupyter-collaboration/pull/368 which should fix this issue.

**Comment by davidbrochart** [comment] 2024-10-11 15:41
It should be fixed in jupyter-collaboration v2.1.3.

**Comment by jtpio** [comment] 2024-10-11 18:44
Looks like https://github.com/jupyterlab/jupyter-collaboration/pull/368 was merged, so closing as fixed.

**Closed by jtpio** 2024-10-11 18:44 UTC
Labels: bug, tag:Real Time Collaboration
