### ISSUE TITLE
Workspace loaded when opening a simple view link directly

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#12644] opened 2022-06-02 00:07 UTC
## Description

If you open a file in simpleview with a direct link, behind the active notebook, the rest of the workspace loads. This creates a problem both in terms wasted performance as well as  user interaction issues. One example is users will get popups about "File Changed" for the hidden files if they are working on them in another tab in their workspace. Can we only load the file listed in tree view?

## Reproduce
https://user-images.githubusercontent.com/1813603/171521092-f1861c78-91a1-469b-85a5-88f2b68aaa5e.mov

Per above, I use the `tree` link to load a file in simple view, but then when you uncheck simple, you can see the rest of the workspace did load.

## Expected behavior

Only the file you navigated to loaded.

## Context

Lab@3.4.2

**Comment by jweill-aws** [comment] 2022-06-09 17:08
This is the expected behavior. When opening JupyterLab, even in Simple mode, your session is restored.

**Comment by mlucool** [comment] 2022-06-09 17:28
Per above, this causes a pretty serious degradation in user experience. Can we reopen to discuss?

**Comment by jweill-aws** [comment] 2022-06-09 17:32
If you add `reset=true` to your URL, your session should be cleared of other tabs besides the active one. Is there another action that we can take to improve the experience?

**Comment by mlucool** [comment] 2022-06-09 18:04
That would work. Can loading a URL in simple mode default to that (even if we make this opt in)?

**Comment by mlucool** [comment] 2022-06-10 21:45
As a note, reset clears the workspace so opening a new tab after no longer will show the last used workspace.

**Comment by afshin** [comment] 2022-06-29 11:13
I have been thinking about this issue and I think there are several improvements we could consider and should begin to build:

---
1. **The `MainAreaWidget` should *optionally* allow its contents to be lazily loaded.** This could be accomplished by accepting a JSON serializable argument to pass into a command that generates its content pane. If JupyterLab *only* fully renders the currently active tab at initial load time this would improve both startup performance and the resources consumed by simple mode. (cc: @jasongrout, @jtpio)
2. **When the layout is restored at initial startup, JupyterLab should not render every widget if it is going to be in simple mode.** It should either short-circuit that part of layout restoration (which might require a full page refresh if the user chooses to switch back to full mode). This means that instead of simply re-hydrating all widgets in the workspace, the initialization and restoration of the application should be more nuanced. (cc: @ellisonbg, @jasongrout)
3. **The workspace JSON schema should be published and versioned.** This way if we build some of these behaviors around what exists in a workspace, we can check its version and validate that we can actually generate a meaningful experience based on what exists in the workspace file. (cc: @tonyfast, @bollwyvl)
4. **We should add a user setting for simple mode that closes all other tabs.** This would be a user preference and for users who actually want this behavior, it would make their simple mode more responsive. (cc: @mlucool, @isabela-pf)
5. **When `autosave` is enabled, the `isDirty` flag should not trigger a warning dialog to the user when they try to close a tab (or as above, if the tab is automatically closed).** Instead, the application should automatically save the document. This is related to but ultimately orthogonal to RTC saving behavior. (cc: @davidbrochart, @hbcarlos, @dmonad, @echarles)

I am happy to write each of these suggestions as issues and to begin working on one or more of them. I'm also happy for others to take them up if they are interested. But before that, I would like to solicit thoughts and opinions. This issue isn't *exactly* about any of the suggestions above, but I think they each improve the experience of loading a workspace whether in simple mode or in full mode.

**Comment by davidbrochart** [comment] 2022-06-29 12:07
> 5\. **When `autosave` is enabled, the `isDirty` flag should not trigger a warning dialog to the user when they try to close a tab (or as above, if the tab is automatically closed).** Instead, the application should automatically save the document. This is related to but ultimately orthogonal to RTC saving behavior.

Yes, RTC follows this behavior since we auto-save one second after each document change, and there is a [PR](https://github.com/jupyterlab/jupyterlab/issues/12685) to get rid of the warning dialog for this reason.

**Comment by afshin** [comment] 2022-06-29 12:27
> We should add a user setting for simple mode that closes all other tabs. This would be a user preference and for users who actually want this behavior, it would make their simple mode more responsive.

One version of this we might consider is where switching to simple mode closes other tabs but does not remove them from the workspace. This would involve separating out the re-hydration information of simple mode from full mode inside the workspace file.

**Comment by bollwyvl** [comment] 2022-06-29 14:29
> 3. The workspace JSON schema should be published and versioned. 

Yep #6013 cover most of my thoughts on this. 

Underlying this: thinking about a workspace as "a 2d series of commands," I also think having a robust schema for commands (https://github.com/jupyterlab/lumino/issues/58) would pave the way to better discovery and cross-client automation capabilities. 

- splitting the modal command palette and an "advanced commands" (restoring categories) would allow for building up complex behaviors... perhaps this is a part of #6944 
- A number of folk still express concern about Notebook 7 kernel packages not being able to change the global state of the UI
  - [ipylab](https://github.com/jtpio/ipylab) can do a lot of it
  - but a `application/jupyter-commands+json` display type would be a lower bar, 
    - more likely to be implementable by more clients and kernels
    - wouldn't leak too much implementation detail. 
    - the first time a command is issued by a kernel, it could get a confirmation dialog (with the `title` of the command) and opt into auto-run, either by command or kernel

**Comment by fcollonval** [comment] 2022-07-02 11:41
> One version of this we might consider is where switching to simple mode closes other tabs but does not remove them from the workspace.

What will be the purpose of keeping the other main tabs in the workspace description? Would it make sense to drop them and introduce a recent tabs feature to quickly access previously opened main widgets?

**Comment by afshin** [comment] 2022-07-04 23:13
@fcollonval,
> What will be the purpose of keeping the other main tabs in the workspace description? Would it make sense to drop them and introduce a recent tabs feature to quickly access previously opened main widgets?

My idea was that we store the "tabs for full mode" and also the "document in single mode" so that when you switch off of simple mode you can see the old workspace. But this idea falls apart because we have the tab switcher even in simple mode. Your idea might be a better approach.

**Comment by SylvainCorlay** [comment] 2022-11-20 01:48
Should we close this issue since #13037 is merged?

**Closed** 2022-11-20 13:52 UTC
Labels: bug, status:Needs Discussion, Tag:Workspaces
