### ISSUE TITLE
[Bug]Invisible Cursor with Jupyterlab

### ISSUE THREAD

**Issue by ksvensson8** [jupyterlab/jupyterlab#7329] opened 2019-10-11 16:35 UTC
## Description
I'm not quite sure how I I triggered it, but using the light jupyter theme now has no cursor. Switching to dark theme the cursor is still there, as is switching to the notebook view (localhost:xxxx/tree)

## Reproduce
I am not sure what triggered it to begin with, but I have tried restarting kernel with no luck. I haven't changed any settings, although I do have the extension manager enabled.

## Expected behavior
A cursor

## Context

- Operating System and version: Windows Server 2012 R2 Standard 64-bit (6.3 Build 9600)
- Browser and version: Chrome Version 77.0.3865.90 (Official Build) (64-bit)
- JupyterLab version: 1.14

<details><summary>Troubleshoot Output</summary>
<pre>

sys.executable:
        c:\users\myuser\pycharmprojects\ds\venv\scripts\python.exe

sys.version:
        3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)
]

platform.platform():
        Windows-2012ServerR2-6.3.9600-SP0

where jupyter:
        c:\Users\myuser\PycharmProjects\DS\venv\Scripts\jupyter.exe
        C:\python36\Scripts\jupyter.exe

pip list:
        Package                           Version
        --------------------------------- -----------
        attrs                             19.2.0
        backcall                          0.1.0
        bleach                            3.1.0
        Click                             7.0
        click-plugins                     1.1.1
        cligj                             0.5.0
        colorama                          0.4.1
        cycler                            0.10.0
        decorator                         4.4.0
        defusedxml                        0.6.0
        entrypoints                       0.3
        Fiona                             1.8.6
        GDAL                              2.4.1
        geopandas                         0.6.0
        graphviz                          0.13
        ipykernel                         5.1.2
        ipython                           7.7.0
        ipython-genutils                  0.2.0
        ipywidgets                        7.5.1
        jedi                              0.15.1
        Jinja2                            2.10.3
        joblib                            0.14.0
        json5                             0.8.5
        jsonschema                        3.0.2
        jupyter                           1.0.0
        jupyter-client                    5.3.3
        jupyter-console                   6.0.0
        jupyter-contrib-core              0.3.3
        jupyter-contrib-nbextensions      0.5.1
        jupyter-core                      4.6.0
        jupyter-highlight-selected-word   0.2.0
        jupyter-latex-envs                1.4.6
        jupyter-nbextensions-configurator 0.4.1
        jupyterlab                        1.1.4
        jupyterlab-server                 1.0.6
        jupyterthemes                     0.20.0
        keplergl                          0.1.1
        kiwisolver                        1.1.0
        lesscpy                           0.13.0
        lxml                              4.4.1
        MarkupSafe                        1.1.1
        matplotlib                        3.1.1
        mistune                           0.8.4
        munch                             2.3.2
        nbconvert                         5.6.0
        nbformat                          4.4.0
        nbpresent                         3.0.0
        networkx                          2.3
        notebook                          6.0.1
        numpy                             1.17.2
        pandas                            0.25.1
        pandocfilters                     1.4.2
        parso                             0.5.1
        pickleshare                       0.7.5
        pip                               19.0.3
        ply                               3.11
        prometheus-client                 0.7.1
        prompt-toolkit                    2.0.10
        pydotplus                         2.0.2
        Pygments                          2.4.2
        pyodbc                            4.0.27
        pyparsing                         2.4.2
        pyproj                            2.4.0
        pyrsistent                        0.15.4
        python-dateutil                   2.8.0
        pytz                              2019.3
        pywin32                           224
        pywinpty                          0.5.5
        PyYAML                            5.1.2
        pyzmq                             18.1.0
        qtconsole                         4.5.5
        scikit-learn                      0.21.3
        scipy                             1.3.1
        Send2Trash                        1.5.0
        setuptools                        40.8.0
        Shapely                           1.6.4.post2
        six                               1.12.0
        SQLAlchemy                        1.3.9
        terminado                         0.8.2
        testpath                          0.4.2
        tornado                           6.0.3
        traitlets                         4.3.3
        traittypes                        0.2.1
        wcwidth                           0.1.7
        webencodings                      0.5.1
        widgetsnbextension                3.5.1
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>

C:\Users\myuser\PycharmProjects\DS>cmd /k cd /d c:\Users\myuser\pycharmpro
jects\DS\venv\Scripts & activate & jupyter lab --notebook-dir=c:\users\myuser
\pycharmprojects\DS\notebooks
[I 11:18:07.901 LabApp] The port 8888 is already in use, trying another port.
[I 11:18:07.902 LabApp] The port 8889 is already in use, trying another port.
[I 11:18:07.956 LabApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 11:18:07.999 LabApp] JupyterLab extension loaded from c:\users\myuser\pych
armprojects\ds\venv\lib\site-packages\jupyterlab
[I 11:18:08.000 LabApp] JupyterLab application directory is c:\users\myuser\p
ycharmprojects\ds\venv\share\jupyter\lab
[I 11:18:08.115 LabApp] √ nbpresent HTML export ENABLED
[W 11:18:08.115 LabApp] ? nbpresent PDF export DISABLED: No module named 'nbbrow
serpdf'
[I 11:18:08.116 LabApp] Serving notebooks from local directory: c:\users\myuser\pycharmprojects\DS\notebooks
[I 11:18:08.116 LabApp] The Jupyter Notebook is running at:
[I 11:18:08.117 LabApp] http://localhost:8890/?token=20e4c62891c04b1ab44d48f6491
3bdb7dc31f8cf2a7c3540
[I 11:18:08.117 LabApp]  or http://127.0.0.1:8890/?token=20e4c62891c04b1ab44d48f
64913bdb7dc31f8cf2a7c3540
[I 11:18:08.117 LabApp] Use Control-C to stop this server and shut down all kern
els (twice to skip confirmation).
[C 11:18:08.127 LabApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/myuser/AppData/Roaming/jupyter/runtime/nbserver-2854
4-open.html
    Or copy and paste one of these URLs:
        http://localhost:8890/?token=20e4c62891c04b1ab44d48f64913bdb7dc31f8cf2a7
c3540
     or http://127.0.0.1:8890/?token=20e4c62891c04b1ab44d48f64913bdb7dc31f8cf2a7
c3540
[I 11:18:11.952 LabApp] Build is up to date
-[I 11:18:13.436 LabApp] Kernel started: a9534ebc-9a3a-47e7-a5f5-070ed996e52b
[I 11:23:33.620 LabApp] Starting buffering for a9534ebc-9a3a-47e7-a5f5-070ed996e
52b:072eba3f-3f79-4c20-9b62-b8231cc52a94
[I 11:23:37.868 LabApp] Build is up to date
[I 11:23:41.764 LabApp] Build is up to date
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by vidartf** [comment] 2019-10-12 09:30
Just to clarify: Are you talking about the mouse cursor or the text editor cursor?

**Comment by ksvensson8** [comment] 2019-10-14 13:26
The text editor cursor, sorry.

**Comment by vidartf** [comment] 2019-10-18 13:44
Are you able to regularly reproduce this, or was this a one off? If regularly, would you mind sharing one or more screenshots screen captures? This would help with narrowing down the troubleshooting :)

**Comment by ksvensson8** [comment] 2019-10-18 15:29
It was persistent...until you asked me to take more screenshots. :) It now appears that the cursor has returned. I'm not quite sure what step I took to redo it - I was having other issues with jupyterlab using the keplergl plugin that I was able to repair by switching to tree and back - perhaps going to the notebooks and then back to lab repaired it? In any event, if it reappears I will try and identify what I did to trigger it to disappear.

**Comment by jasongrout** [comment] 2019-10-18 15:49
Sometimes I think that happens if the browser zoom is not 100%. Was that maybe the issue?

**Comment by ksvensson8** [comment] 2019-10-18 15:51
No - browser (Chrome) is always at 100% zoom.

**Comment by dpatchigolla** [comment] 2019-11-06 01:35
I came searching for this exact issue. I am not getting the text editor cursor in Jupyter Lab, only in one specific virtual env. I use default light theme. Trying out the Dark theme, I could see the cursor. It goes away if I try light theme again. 
I could reproduce this 100% when  I am in that virtual env.

**Comment by dpatchigolla** [comment] 2019-11-06 01:37
Chrome Version 77.0.3865.120 (Official Build) (64-bit)
Windows 10 Home 64 bit
Jupyter Lab version: 1.1.4

**Comment by annelisagrout** [comment] 2019-11-06 12:55
To narrow this down:

* please try with the latest release, 1.2.1
* Make sure that there are no browser extensions enabled
* try in browser incognito mode
* make sure the browser zoom is at 100%
* is it always Chrome? Does it have an issue in any other browser?
* Launch JupyterLab in `jupyter lab --core-mode` to make sure you don't have any jlab extensions installed

(this is part of our issue diagnosis guidelines: https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html )

**Comment by jasongrout** [comment] 2019-11-06 13:01
To narrow this down:

* please try with the latest release, 1.2.1
* Make sure that there are no browser extensions enabled
* try in browser incognito mode
* make sure the browser zoom is at 100%
* is it always Chrome? Does it have an issue in any other browser?
* Launch JupyterLab in `jupyter lab --core-mode` to make sure you don't have any jlab extensions installed

(this is part of our issue diagnosis guidelines: https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html )

**Comment by jasongrout** [comment] 2020-02-05 22:15
Closing since the author did not follow up. Please comment here if you'd like to continue the discussion.

**Closed by jasongrout** 2020-02-05 22:15 UTC
Labels: status:Needs Info
