### ISSUE TITLE
the command 'export' don't work well in jupyter lab

### ISSUE THREAD

**Issue by Ethan-Chen-plus** [jupyterlab/jupyterlab#13775] opened 2023-01-15 05:51 UTC
## Description
As we know, use '!' can do command line in jupyterlab cells.
![image](https://user-images.githubusercontent.com/84905965/212524960-0d4d69b5-47db-43b0-94d5-bdfa9c01d405.png)

However when I use export , it doesn't work well. As you can see, I use echo and I get nothing.

## Expected behavior

I expect to see the echo '/mnt/k/kewei/haahsummer' thing.

## Context

- Operating System and version: wsl ubuntu 1804
- Browser and version: edge
- JupyterLab version: 3.2.9

**Comment by JasonWeill** [comment] 2023-01-19 18:16
When you use `!` to run a command in IPython or Jupyter Notebook, the command runs in a shell by itself. After you've run your `export` command in one cell, it works successfully (setting an environment variable in cell 1) but then the `echo` command in your second cell operates in a different shell, where that environment variable was not set.

We have a "magic" command `%env` for setting environment variables that might work better for your use case: https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-env . You can also use the `%%bash` magic command to run a script in a single cell, rather than one command at a time in multiple cells.

This is working by design; closing this out. Please open another issue if you find any other bugs or enhancement requests. You can also get help on [our Discourse forum](https://discourse.jupyter.org/).

**Closed by JasonWeill** 2023-01-19 18:16 UTC
Labels: bug, status:Needs Triage
