### ISSUE TITLE
command that startup jupyterlab 3 with bracket auto close?

### ISSUE THREAD

**Issue by linlol** [jupyterlab/jupyterlab#13272] opened 2022-10-19 12:53 UTC
Recently we are migrating our internal jupyterlab 2 to jupyterlab 3 (running in docker with config and notebooks stored externally), and we realised that in jupyterlab 2.x by default we have brackets auto-close, however, in jupyterlab 3 it is not auto-closed by default.

though it is just a one-click change in jupyterlab frontend, it could be better if we can make the default behaviour consistent with those in jupyter lab 2.x

In this case, is it able to config it in startup command or some external config file such that we can configure it initially.

**Comment by jweill-aws** [comment] 2022-10-20 17:24
According to the [JupyterLab 3.1.0 changelog](https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#id194), bracket auto-closing is no longer enabled by default. From the changelog:

> The closing bracket is no longer automatically added by default; the old behaviour can be re-enabled from the menu bar `(Settings -> Auto Close Brackets)` or from the Advanced Settings Editor.

If you want this to be enabled in your Docker image automatically, you can customize the advanced settings to re-enable this option, then save your settings in the image. You can see where settings are saved here: https://jupyterlab.readthedocs.io/en/stable/user/directories.html#jupyterlab-user-settings-directory

This feature is working by design, so I'm going to close this issue. If you have other questions about setting up JupyterLab, I recommend asking them in our Discourse forum (linked above) or in our [Gitter channel](https://gitter.im/jupyterlab/jupyterlab#).

**Closed by jweill-aws** 2022-10-20 17:24 UTC
Labels: enhancement, status:Needs Triage

**Comment by krassowski** [comment] 2022-10-20 17:28
> In this case, is it able to config it in startup command or some external config file such that we can configure it initially.

Just to note, `overrides.json` would be sufficient here as discussed in https://github.com/jupyterlab/jupyterlab/issues/5741#issuecomment-1062799919.
