### ISSUE TITLE
Entering vi(1) commands in JupyterLab notebooks causes scroll to bottom of cell ...

### ISSUE THREAD

**Issue by nmvega** [jupyterlab/jupyterlab#16576] opened 2024-07-11 19:47 UTC
Hello Friends:

I'm running the below library versions in a `Python` virtual environment.

My **JupyterLab Notebooks** use **vim(1)** emulation.

I don't know when this problem started, but every time I perform, say, a **w!** editor operation to save changes, the Notebook scrolls to the bottom of the current **input cell**, but doesn't go back up to the cursor input location so that I can continue working. I have to scroll back up each time and find where I was.

The behavior use to be a convenient and quick **appearance** of the **ed(1)** one-line editor at the bottom of the display as you typed a **vi(1)** command, then it would **disappear** and you were taken back to your cursor. It no longer does that.

Can anyone suggest what to check for and/or how to fix this?

Thank you in advance! (See below).

```
Python 3.12.4
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter_ai==2.18.1
jupyter_ai_magics==2.18.1
jupyter_client==8.6.2
jupyter_core==5.7.2
jupyter_server==2.14.1
jupyter_server_terminals==0.5.3
jupyterlab==4.2.3
jupyterlab-vim==4.1.3
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.2
jupyterlab_widgets==3.0.11
```

**Comment by krassowski** [comment] 2024-07-12 10:03
I think this is not an issue in JupyterLab but in [jupyterlab-vim](https://github.com/jupyterlab-contrib/jupyterlab-vim) with the root cause likely in [codemirror-vim](https://github.com/replit/codemirror-vim)
Public. I would suggest to close this issue and open a new one on jupyterlab-vim repository; the next step would be to confirm if this (cursor not jumping back to selection) is reproducible in pure codemirror-vim (which I guess it should be).

**Comment by nmvega** [comment] 2024-07-12 11:45
@krassowski Thank you. I'm currently typing from a small phone :blush: but when able I'll open an issue there. Thank you for the feedback.

**Comment by JasonWeill** [comment] 2024-07-16 16:14
@nmvega Thank you for opening an issue in jupyterlab-vim! Closing in favor of your issue in the other subproject.

**Closed by JasonWeill** 2024-07-16 16:14 UTC
Labels: bug, status:Needs Triage

**Comment by nmvega** [comment] 2024-07-18 19:40
> @nmvega Thank you for opening an issue in jupyterlab-vim! Closing in favor of your issue in the other subproject.

Thank you! :blush:
