### ISSUE TITLE
opening pdf file bug

### ISSUE THREAD

**Issue by icankeep** [jupyterlab/jupyterlab#10707] opened 2021-07-27 11:19 UTC
# reproduce
1. open pdf file
![image](https://user-images.githubusercontent.com/39434627/127145079-2dc0746a-d377-4e1a-a09c-3f188c2561fc.png)
2. switch to a notebook
3. switch back to the pdf file
![image](https://user-images.githubusercontent.com/39434627/127145102-005fceb2-3c36-42dc-9ce9-c8e2d600c76c.png)

# result
The view of pdf will not render properly.  my jupyterlab version is 3.0.14

**Comment by krassowski** [comment] 2021-07-27 11:48
It looks like a duplicate of #10374 to me, which it seems is a bug in Chromium itself (but if you can find a workaround that we could apply that would be great!).

**Comment by krassowski** [comment] 2021-07-27 12:00
Closing as a duplicate.

**Closed by krassowski** 2021-07-27 12:00 UTC
Labels: bug, status:Duplicate
