### ISSUE TITLE
the Chinese characters were garbled in jupyterlab

### ISSUE THREAD

**Issue by hyliush** [jupyterlab/jupyterlab#14518] opened 2023-05-10 12:06 UTC
![image](https://github.com/jupyterlab/jupyterlab/assets/49185490/7f336943-d6a2-4b69-b4cc-1096d12e59d0)

browser: chrom
jupyterlab3.6.1
the Chinese characters were garbled.

**Comment by JasonWeill** [comment] 2023-05-10 19:08
Resolving as a duplicate of #14274, fixed by #14178.

**Closed by JasonWeill** 2023-05-10 19:08 UTC
Labels: bug, status:Needs Triage
