### ISSUE TITLE
Saving and closing a MimeDocument quickly results in "Disposed" error

### ISSUE THREAD

**Issue by quigleyj-mavenomics** [jupyterlab/jupyterlab#5787] opened 2018-12-19 15:00 UTC
**Describe the bug**

When saving and closing a tab quickly (eg, Ctrl+S Ctrl+Q), the `docmanager:save` command ends up in a race condition where if the DocumentModel is disposed before the save is executed, a popup will appear with "File Save Error for (file name here): Disposed".

**To Reproduce**

1. (optional): Go to your browser dev tools and enable network throttling. This makes the bug much easier to reproduce.
2. Open any document, such as a notebook or image, making sure not to change it. Otherwise you'll get the unsaved changes dialog.
3. As quickly as you can, press Ctrl+S and then Ctrl+Q

**Expected behavior**

The save should go through without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/20070398/50226339-f7324c80-0370-11e9-9c84-1a6b7332cb8d.png)

**Desktop (please complete the following information):**

Reproduced on a local machine (Win7, Chrome 70, JupyterLab 0.35.4, network throttling set to Fast 3G) and on a remote server (EC2 t2.small RHEL, Chrome 70, JupyterLab 0.35.4, no throttling)

**Additional context**

As noted above, this issue cropped up on a CI server we run for testing an extension suite we're developing. This CI server is significantly slower than running locally, which causes this issue to be more prominent.

<details>
<summary>Browser Output</summary>
NB: This error is thrown by a promise callback in @jupyterlab/docregistry <code>Context#_maybeSave()</code>

<pre>
context.js:516 Uncaught (in promise) Error: Disposed
    at promise.then.model (context.js:516)
</pre>
</details>

**Comment by ian-r-rose** [comment] 2019-05-10 23:29
Thanks for the report @quigleyj-mavenomics. I'm having a hard time reproducing this, either on 0.35.4 or on master, with network throttling enabled. Is there anything else that you think might be relevant? The line that function that produces this error dialog sure *seems* like it is correctly checking for whether the context has been disposed:
https://github.com/jupyterlab/jupyterlab/blob/5211238d72626c1fd7b1fcfb92a1052c8e025380/packages/docregistry/src/context.ts#L482-L514

**Comment by quigleyj-mavenomics** [comment] 2019-05-13 16:52
I can still do it reliably on a clean 0.35.4 with network throttling. For reference, I set mine to `Slow 3G` on Chrome, but I can also reproduce it on `Fast 3G`. I also just tested with a clean 1.0.0a3, and could reproduce it there as well.

**Comment by ian-r-rose** [comment] 2019-05-18 01:06
Hmm, I'm still unable to repro with 3G throttling. Your example shows a notebook, but the title specifies a `MimeDocument`. Can you confirm that this is for all documents, not just `MimeDocument`s?

**Comment by jasongrout** [comment] 2019-05-23 06:17
When I use firefox, set throttling to "Regular 2G", open a notebook, and immediately hit the close tab shortcut before the spinner resolves, I get the "Close without saving" dialog instead: 
![Screen Shot 2019-05-22 at 11 15 09 PM](https://user-images.githubusercontent.com/192614/58229929-7104a280-7d22-11e9-8bb4-2de951152e58.png)

**Comment by jasongrout** [comment] 2019-05-23 06:19
Interestingly, the tab doesn't close until the spinner resolves and the notebook displays. Perhaps that's why the disposed error doesn't occur.

**Comment by jasongrout** [comment] 2019-05-23 06:36
When I open a png image and immediately close it before the spinner resolves, the tab immediately closes (unlike the notebook). I still don't get the disposed error mentioned in the OP.

**Comment by jasongrout** [comment] 2019-05-23 08:30
It looks like the notebook seems like it is dirty because deserializing a notebook sets dirty to true, and the widget loading the model in turn changes the widget, which changes the model, which sets dirty to true. At some point after the initial load, dirty is set to false, though. Closing a tab seems to interrupt that, thought.

**Comment by jasongrout** [comment] 2019-05-23 08:37
Bumping to 1.1 since it is (a) the file save issue above is a corner case and (b) we can't reproduce the original error in master.

**Comment by jasongrout** [comment] 2019-12-02 17:31
Closing as resolved. Please post here if you can reproduce it with the current release or current master.

**Closed by jasongrout** 2019-12-02 17:31 UTC
