### ISSUE TITLE
Support keymaps in notebook cells

### ISSUE THREAD

**Issue by arel** [jupyterlab/jupyterlab#3992] opened 2018-02-24 00:27 UTC
I am new to using JupyterLab and it's fantastic. I can't however figure out how to set keymaps that work in the text editor cells of a notebook (e.g., Ctrl-D in "sublime mode" to highlight matching words).

This also seems related to #1362 (feel free to combine and close as duplicate).

I am using JupyterLab Beta Release Series Version 0.31.8.

![screenshot 2018-02-23 at 7 24 18 pm](https://user-images.githubusercontent.com/153497/36623256-fcd20f58-18d0-11e8-9365-57948ae98179.png)

**Comment by ian-r-rose** [comment] 2018-03-06 15:53
This is a duplicate of #1362. Different keymaps are not available for the notebook at this time. This is largely due to the fact that the notebook also has a set of keyboard driven commands which are likely to conflict with the non-default keymap. It is possible to make this work, but with a fairly large amount of effort. See https://github.com/jwkvam/jupyterlab_vim for an example of enabling vim keybindings.

**Comment by lebesgue** [comment] 2018-03-06 15:59
How difficult would be to integrate the select_keymap nbextension? Thank you for the answer. (https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/select_keymap)

**Comment by ian-r-rose** [comment] 2018-03-06 16:02
It would be fairly straightforward to do that, similar to what @jwkvam has done. The more complex part is thinking through where the keymap conflicts with the notebook keybinding, and resolving those.

**Comment by saulshanabrook** [comment] 2018-05-08 14:38
Closing this as a duplicate.

**Closed by saulshanabrook** 2018-05-08 14:38 UTC
Labels: pkg:cells, status:Duplicate
