### ISSUE TITLE
Save & Restore Layout

### ISSUE THREAD

**Issue by profjsb** [jupyterlab/jupyterlab#502] opened 2016-07-21 18:38 UTC
When restarting the Lab it would be useful to jump into a saved state of the layout, along with saved locations of the cursors in the text editors. Might be easiest to have a new filetype 

Something like:

``` bash
jupyter lab my_layout1.juplab
```

Which would then open the Lab and all the components with the saved layout. Likewise, in the "File..." menu, we could have a `Save current layout...` and `Restore layout...` along with file dialog popup.

**Comment by jasongrout** [comment] 2016-07-21 18:47
Thanks. Yes, this ties into a larger conversation about JupyterLab settings.

**Comment by blink1073** [comment] 2016-07-21 18:47
Hi @profjsb, agree!  This depends on functionality forthcoming in `phosphor`: https://github.com/phosphorjs/phosphor/issues/33, as well as settings (what Jason said).

**Comment by ellisonbg** [comment] 2016-08-17 04:14
Yes, we at least need to get page reload to work...

**Comment by blink1073** [comment] 2016-11-09 01:29
We can minimally implement the behavior where the open widgets are restored when the browser refreshes for Beta.

**Comment by blink1073** [comment] 2016-11-18 19:59
With #1242 and #1260 we now have the ability to restore the open notebooks, terminals, consoles, editor files, and csv widgets, along with the current working directory of the file browser.   I'm moving this broader issue to 1.0.

**Closed** 2017-03-09 22:22 UTC
Labels: cat:Feature Parity, component:Application, type:Enhancement

**Comment by OliverEvans96** [comment] 2017-12-16 16:57
So is saving and loading layouts currently supported, then? The issue is closed, but I can't find any such feature in 0.30.6.

**Comment by sccolbert** [comment] 2017-12-16 17:57
When refreshing/restarting jupyterlab, it restores to how you last had it automatically. There's currently no way of saving "name layouts" which you can recall at-will, although that wouldn't be too difficult to implement.

**Comment by narenst** [comment] 2018-05-03 22:17
Currently, page reload restores the layout successfully. Is it possible to start a fresh jupyterlab server with a given fixed layout?

I want to have a terminal open and docked to the bottom half of the interface when a user opens the jupyterlab endpoint. (It is okay if they later restructure their layout).

**Comment by jasongrout** [comment] 2018-05-03 22:28
There is now a way to save a "workspace" layout, but having it as a template like that is currently not quite exposed to the user.

**Comment by narenst** [comment] 2018-05-03 22:31
Thanks for the response! Does saving a workspace require explicit user action? Or is it auto-saved by the browser? Also where is this workspace layout stored.

**Comment by cocoaaa** [comment] 2019-03-06 20:40
@narenst: I found my workspace setting files (jsons) in `~/.jupyter/lab/workspaces`.  You can check your jupterlab paths by running `jupyter lab path`.
