### ISSUE TITLE
Future of ui-components package: drop Blueprint; should we use Material-UI?

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/jupyterlab#7574] opened 2019-12-02 17:14 UTC
Refs:
#6828
#6890

There's currently an ongoing discussion about the future of the `ui-components` package in Jupyterlab core:

- There's no particular reason to keep the Blueprint dependency around. We should refactor out the sparse use of it in `ui-components` and drop the dep
    - This should be easy, and it will be an API breaking change, so it should maybe go in for 2.0

- Should we replace Blueprint with Material-UI?
    - Pro:
        - Does a lot of nice stuff that would be too much work to do on our own
        - Really nice dialog boxes
    - Con:
        - Does a lot of complex stuff that we don't need
        - May be counterproductive for accessibility stuff

**Comment by vidartf** [comment] 2019-12-02 17:15
Duplicate of https://github.com/jupyterlab/jupyterlab/issues/6890 ?

**Comment by telamonian** [comment] 2019-12-02 17:24
We're discussing issue triage for the 2.0 RC. This is meant to supercede #6890. Basically, the first part of #6890 (removing Blueprint) is easy, and should prob go in 2.0, whereas the second part (should we use Material-UI/something else/nothing?) requires more discussion (and also @ellisonbg).

**Comment by saulshanabrook** [comment] 2020-03-27 19:28
Hey Max. Did you look into doing a custom theme for material UI? https://material-ui.com/customization/theming/

That way we could wrap our top level react render in the react widget with this context... And then users can just use native material UI components and they will be themed.

It would be nice to not *have* to wrap all their components... Instead just maybe export our own if we really need a new one, but otherwise just relying on theming theirs.

cc @echarles who is also exploring this

**Comment by saulshanabrook** [comment] 2020-03-27 19:42
One thing to be aware of is MUI's internal plans on what library they are using, There is a long running issue to switch to styled components from their own internal system (https://github.com/mui-org/material-ui/issues/6115). It seems like in their next version, they will switch to styled components and maybe also let this configurable, so that you could use it with multiple CSS in JS solutions (https://github.com/mui-org/material-ui/issues/20012).

**Comment by echarles** [comment] 2020-03-27 19:58
Just did a quick scan and not sure of the impacts. But whatever internal solution and compatibility option MUI  will provide, I would expect they will keep a theming layer like https://material-ui.com/customization/theming/ (maybe with breaking changes)?

**Comment by saulshanabrook** [comment] 2020-03-27 19:59
@echarles Yes that's true! It only matters if we care about which one it uses internally, which I am not sure if we.

**Comment by saulshanabrook** [comment] 2020-03-27 19:59
i.e. but it does mean we can't pre-generate css files for all our styles at build time and instead rely on this CSS in JS thing (AFAIK)

**Comment by echarles** [comment] 2020-03-27 20:02
you mean for `all our themes`? Btw I am experimenting to automate genration of CSS artifacts for  `jlab theme -> mui theme` as well as the reverse `mui-theme -> jlab theme`.

**Comment by saulshanabrook** [comment] 2020-03-27 20:06
Oh cool! Would love to see that. It looks like we might be able to do server side rendering with it: https://cssinjs.org/server-side-rendering?v=v10.1.1

**Comment by oliviertassinari** [comment] 2020-03-27 20:26
Hi, I'm happy to answer any questions your team might have around Material-UI, what we offer today, and where we aim to go.

**Comment by saulshanabrook** [comment] 2020-03-27 20:42
Thank you @oliviertassinari!

**Comment by telamonian** [comment] 2020-03-30 03:17
> Hey Max. Did you look into doing a custom theme for material UI?

No, but:

- I do think it would be a good idea to supply a jlab theme for mui
- it would require the `jlab theme -> mui theme` converter @echarles mentioned (btw, what do you want the `mui-theme -> jlab theme` version for?). Otherwise, it wouldn't sync up with the current user-selected theme.

The current plan for jupyterlab ui-components (as discussed at the last dev meeting) is for us to implement our own simple, limited, jlab-specific components sans framework. Rather than experimenting with mui, the priority is currently to finish removing the blueprint dependency by replacing all of our blueprint-based components with our own home grown ones.

Here's the list of what's left (from `packages/ui-components/src/blueprint.tsx`):

- `Button`
- `InputGroup`
- `Collapse`
- `Select`
- `Checkbox`

I'll get around to these eventually. If anyone else wants to take a crack at one (or more) of them, I'd be glad to help review PR code instead

**Comment by telamonian** [comment] 2020-03-30 03:22
@oliviertassinari The thing I'd like to talk with you about the most is: "how should Jupyterlab handle UI accessibility?" We've never been able to make much progress on this issue on our own, and it is an important issue. Any thoughts and/or shining example projects about how MUI can help us implement accessibility in a well-thought out and consistent fashion?

**Comment by echarles** [comment] 2020-03-30 03:38
> btw, what do you want the mui-theme -> jlab theme version for

If you define a mui theme, it would make sense for me to generate to needed jlab css that reflect that look and feel. This needs a mapping between MUI definitions and the jlab CSS variables. If this is not clear enough, which is prolly the case, you will need to wait for a demo :)

> The current plan for jupyterlab ui-components (as discussed at the last dev meeting) is for us to implement our own simple, limited, jlab-specific components sans framework

I guess this does not limit exploring alternatives plan.

> Checkbox

This has been introduced by the work for the Listings, and finally the checkbox has been replaced by a button. So it is not used at all for now, but obviously a needed widget.

**Comment by telamonian** [comment] 2020-03-30 03:47
Yeah, neither `Select` nor `Checkbox` are currently used in core code, but since they're publicly exported we'd still need replacements (or just to wait until the 3.0 release to make the breaking change of deleting them).

**Comment by oliviertassinari** [comment] 2020-03-30 16:06
@telamonian Regarding the accessibility part, I think that it could still be interesting for jupyterlab to leverage some of our components for it. For instance, looking at the UI, I can see the following elements:

- Breadcrumb 
  - Preview: <img width="93" alt="Capture d’écran 2020-03-30 à 17 42 05" src="https://user-images.githubusercontent.com/3165635/77932500-eb407480-72ad-11ea-9126-0c1e503784d1.png">
  - Your team could rebuilt it. A few accessibility recommendations in MUI: https://material-ui.com/components/breadcrumbs/#accessibility
- Combobox
  - Preview: <img width="292" alt="Capture d’écran 2020-03-30 à 17 43 01" src="https://user-images.githubusercontent.com/3165635/77932795-4f633880-72ae-11ea-895d-3cb6361964ac.png">
  - High opportunity cost for building internally. You can leverage this unstyled version: https://material-ui.com/components/autocomplete/#useautocomplete
- TreeView
  - Preview: <img width="332" alt="Capture d’écran 2020-03-30 à 17 44 45" src="https://user-images.githubusercontent.com/3165635/77932693-2f337980-72ae-11ea-9d70-bd7a5513c4a4.png">
  - The current version is definitely not keyboard accessible. High opportunity cost for building internally. You could customize our component: https://material-ui.com/components/tree-view/#accessibility. Here is used in a JSON context: https://material-ui.com/customization/default-theme/#explore
- Modal Dialog
  - Preview: <img width="474" alt="Capture d’écran 2020-03-30 à 17 49 53" src="https://user-images.githubusercontent.com/3165635/77933279-e92ae580-72ae-11ea-9f1a-0db035b9f691.png">
  - High opportunity cost for building internally. You can leverage this unstyled version: https://material-ui.com/components/modal/.
- DataGrid
  - Preview: <img width="538" alt="Capture d’écran 2020-03-30 à 17 54 21" src="https://user-images.githubusercontent.com/3165635/77933817-8554ec80-72af-11ea-860c-d49b786a1af8.png">
  - High opportunity cost for building internally. We don't support it yet, but it's a high-priority, work in progress. This is no coincidence: https://twitter.com/MaterialUI/status/1244629034769793025 ;).
- Nested menu
  - Preview: <img width="500" alt="Capture d’écran 2020-03-30 à 17 52 39" src="https://user-images.githubusercontent.com/3165635/77933609-47f05f00-72af-11ea-91af-78e59b380d8b.png">
  - High opportunity cost for building internally. W don't support it yet, not sure if it will happen soon: #11723.
- Grid Layout
  - Preview: <img width="546" alt="Capture d’écran 2020-03-30 à 17 56 52" src="https://user-images.githubusercontent.com/3165635/77934106-e5e42980-72af-11ea-9adb-36c80c63f419.png">
  - Less likely to be built internally. We might support it later on. We have it on our radar, e.g. this issue by JPmorgan: #15372.

**Comment by jasongrout** [comment] 2020-03-30 17:02
@oliviertassinari, thanks for commenting. Is your grid work underway? Can you point to where that work is happening?

**Comment by oliviertassinari** [comment] 2020-03-30 17:05
@jasongrout The work is underway but will likely take months (it's a massive effort). The latest update: https://github.com/mui-org/material-ui/pull/18872#issuecomment-586369465

**Comment by jasongrout** [comment] 2020-03-30 17:10
> The work is underway but will likely take months (it's a significant effort)

Thanks for the link. We totally understand the grid we use took months to develop as well: https://github.com/jupyterlab/lumino/tree/master/packages/datagrid

**Comment by oliviertassinari** [comment] 2020-03-30 17:15
@jasongrout Well, considering we want to position this grid between Kendo-UI and Ag-grid, it might be months only for the MVP 😆.

**Comment by jasongrout** [comment] 2020-03-30 17:25
A few other notes. I think one of the main considerations here is not what it cost to *build* something (since you are pointing out things that we've already built or incorporated), but what it costs to maintain or extend for our needs. And obviously we can't think about switching to mui controls that haven't been built yet :).

> Breadcrumb

Maintained internally.

> Combobox 

This is not a combobox UX, but rather a static list that always displays with a filter textbox

> TreeView

We don't maintain this internally. We use react-json-tree

> Modal Dialog

Maintained internally

> DataGrid

Maintained internally (in the Lumino project). Not quite to ag-grid level features, but may have more performant foundation that ag-grid. Again, we totally understand it taking months to build to an mvp.

> Nested menu

Maintained internally (Lumino). As you point out, not built in mui yet.

> Grid Layout / Splitter control

Maintained internally (Lumino). As you point out, not built in mui yet.

**Comment by jasongrout** [comment] 2020-03-30 17:33
> Thanks for sharing the link!

Also, look at https://github.com/jupyterlab/lumino/tree/master/examples/example-datagrid for a standalone demo of the grid.

**Comment by oliviertassinari** [comment] 2020-03-30 18:23
> how should Jupyterlab handle UI accessibility?

@telamonian Our components are often a direct mapping of https://www.w3.org/TR/wai-aria-practices/ to React. So outside providing accessible components, Material-UI won't help your team much. Sure you could benchmark our implementation and our `## Accessibility` sections in the documentation, but it leaves the whole integration of these different parts to you. Internally, we use the following tools:

- https://wave.webaim.org/
- https://validator.w3.org/
- https://www.w3.org/WAI/standards-guidelines/aria/
- https://github.com/GoogleChrome/lighthouse
- The community that reports a11y issues
- https://github.com/evcohen/eslint-plugin-jsx-a11y
- The screenreaders

---

So, as much of what the value of Material-UI for you could be, I'm not sure to understand the problem you wish to solve with it. I think that it depends on how you value the following dimensions. 

1. An application can only be as accessible as its weakest element. If a third-party or internal component isn't inaccessible, it will need to be addressed. It won't be enough to make your app accessible.
2. What features do you have in your roadmap that Material-UI could speed-up? I have seen #689 that could be solved with [notistack](https://iamhosseindhv.com/notistack/demos#hide-icon-variants) (MUI ecosystem). But maybe they are some other features that you could benefit from contributions of the community (now and in the future).
3. How specific are your requirements? While Material-UI split its feature into multiple components to leveraging tree-shaking, we prioritize the most common use-cases. We make tradeoffs in this direction, we don't aim to support non-frequent use cases (we only make sure we expose enough API so it become DIY for users). If you need Material-UI to make tradeoffs that go against the need of the many, it will be a problem. A prop used in less than 5% of the time? Not for us, sorry.

**Comment by fcollonval** [comment] 2022-08-17 07:18
Closing as it was decided to remove Blueprint and not to include material-UI. The path forward will be to integrate a Jupyter Toolkit based on web components.

**Closed by fcollonval** 2022-08-17 07:18 UTC
Labels: status:Needs Discussion, tag:Design System CSS

**Comment by oliviertassinari** [comment] 2022-08-17 10:57
@jasongrout Do you mean that you are moving forward with https://github.com/jupyterlab-contrib/jupyter-ui-toolkit?

**Comment by fcollonval** [comment] 2022-08-17 12:06
> Do you mean that you are moving forward with https://github.com/jupyterlab-contrib/jupyter-ui-toolkit?

Probably but the move will likely happen not before Q4 when JupyterLab 4.0 is out. So the final toolkit basis may still change. But it will certainly not be React based (nor Vue, nor Angular) as the goal of the toolkit is to be usable in any Jupyter projects with as light constrains on the technological stack as possible.
