### ISSUE TITLE
Performance regression for multiple large notebooks 3.3 -> 3.4

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab#13092] opened 2022-09-14 16:39 UTC
## Description

After https://github.com/jupyterlab/jupyterlab/pull/11074 there was a performance regression for users who have multiple larger notebooks open at the same time. E.g. for ~10 notebooks open, I see tab switching increase from ~2s to ~7s with that PR. Since the behavior is configurable via the settings, users have a viable workaround if they identify the issue, but it might not be something that the user will easily figure out on their own. I would therefore argue for:

- Changing the default back to `display`, as I believe the efficiency gained for the two notebook case are "smaller" than the efficiency loss of many notebooks. This is subjective though, but I at least think we should have a discussion about it.
- Adding a benchmark for multiple notebooks open. This is a common use case, and highlights issues where the effect of a lot of hidden DOM nodes on the page is important.

## Reproduce

1. Create a notebook with a bunch of code cells with a few lines of code (10-20 lines). The cells can have the same content, so duplicating the cells a bunch of time is probably the quickest way
2. Duplicate the notebook a few time for ~10 versions. 
3. Open all of them, and wait for the kernels to initialize
4. Refresh the page to get fresh state
5. Switch tabs between the notebooks, and record the time it takes to switch (maybe via browser profiling).
6. Change the setting from "scale" to "display"
7. Refresh the page and repeat the tab switching timing.

## Context

This was tested for JupyterLab version 3.4.x. It might also hold true for 4.x, but I haven't tested that.

**Comment by vidartf** [comment] 2022-09-15 09:12
cc @fcollonval

**Comment by fcollonval** [comment] 2022-09-15 09:51
Thanks for providing a detailed description of the regression. Indeed currently we only test for 2 notebook opened at a time. It will be interesting to open more notebook to see what is happening.

Would you mind providing the browser used (and its version)? The use of scale is not optimized similarly in all browsers.
Could you confirm that the switch is longer even after the first switch? - When using scale, the first time the user will switch to a tab newly opened, a style recalculation will be carried out. That will slow down the first switch action (this is not happening with display none because it requires a full style recalculation by the browser). But then the following switch should be faster.

Regarding 4.x, it is gonna be trickier because we will have the feature of notebook windowing and the switch to codemirror 6. So more testing will be needed to figure out what is the best combination of settings.

**Comment by vidartf** [comment] 2022-09-15 15:51
@fcollonval I've tested this with Chrome 103.5060 and 105.0.

**Comment by vidartf** [comment] 2022-09-16 11:05
> Could you confirm that the switch is longer even after the first switch?

No, the switch is quick after the first loop through all notebooks, provided that the main area doesn't get resized.

There is also another pretty sever issue that is caused (or aggravated?) by this change:
- Set the hiddenMode to "scale" and refresh the page.
- Open up the "Jupyter Reference" page from the "Help" menu. This will trigger multiple CORS policy errors in the browser (this will happen irregardless of the `hiddenMode`)
- Switch to a different tab in the main area. The UI will now be frozen...

**Comment by vidartf** [comment] 2022-09-16 15:04
I tested the UI freeze above in Firefox, and that does not have the issue (it still gives CORS errors, but the UI does not freeze). But I was able to reproduce it in Edge, which means it is probably a webkit issue.

**Comment by fcollonval** [comment] 2022-09-19 08:22
Thanks for the additional information. 

Related to the reported Jupyter Reference issue: https://github.com/jupyterlab/jupyterlab/issues/13039

I can confirm to that opening an help iframe breaks the app in Chrome but not in Firefox.

In light to that, we should indeed invert the default behavior to use the previous way for hiding tabs.

**Closed** 2022-09-22 12:35 UTC
Labels: bug, pkg:application, tag:Performance
