### ISSUE TITLE
500: internal server error trying to print notebooks

### ISSUE THREAD

**Issue by callegar** [jupyterlab/jupyterlab#11913] opened 2022-01-21 20:32 UTC
## Description

Using jupyter lab with a chrome browser, I have recently started to experience an issue when trying to print notebooks using "File->Print", where the browsers opens a print preview window where, rather than a preview, I see a page with a big text saying "500: Internal Server Error". Much smaller there is also the text "nbconvert failed: 'tuple' object is not callable".

## Reproduce

File->Print

## Expected behavior

The browser should open its print dialog, with a correct print preview.

## Context

- Operating System and version: Linux 20.04
- Browser and version: Google-Chrome Version 98.0.4758.66 (Official Build) beta (64-bit)
- JupyterLab version: Version 3.2.8

**Comment by davidbrochart** [comment] 2022-01-21 20:37
Duplicate of #11885.

**Comment by krassowski** [comment] 2022-01-21 20:39
Thanks for opening the issue. This looks like a duplicate of https://github.com/jupyterlab/jupyterlab/issues/11885; the underlying nbconvert issue was fixed in https://github.com/jupyter-server/jupyter_server/pull/667 but it seems that a new version with the patch was not released yet.

@davidbrochart is there a known workaround like downgrading to a lower version of `jupyter_server`? I understand how it can feel for a user who needs to export/print the notebook ASAP to not be able to do so.

**Comment by callegar** [comment] 2022-01-21 20:41
Thanks for the quick identification of the issue as a duplicate, I missed that.

**Comment by davidbrochart** [comment] 2022-01-21 20:58
> @davidbrochart is there a known workaround like downgrading to a lower version of `jupyter_server`?

Yes, `pip install jupyter_server==1.13.1` should fix it. Sorry for the short answer @callegar, and thanks for reporting!

**Comment by davidbrochart** [comment] 2022-01-22 08:25
Now that jupyter_server v1.13.4 is out, `pip install jupyter_server --upgrade` should work.

**Closed** 2022-02-01 23:55 UTC
Labels: bug, status:Duplicate, status:Answered, status:Closing as Answered
