### ISSUE TITLE
Open a file from command line

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#8959] opened 2020-09-04 18:56 UTC
### Problem

In the classic notebook, you can open a file from the command line with `jupyter notebook myfile.ipynb`

As far as I can tell, we cannot do something similar with JupyterLab. It would be great if we can give a list of files on the command line that JupyterLab would open a new workspace:

```sh
jupyter lab myfile.ipynb myfile.csv
```

**Comment by goanpeca** [comment] 2020-09-04 19:25
Sounds like a great idea!

I have a question;

Would this open the files all tabbed together? Is there a way to specify how files can be opened in separate tabs?

If I open only notebooks then it makes sense to have them tabbed together

But for the example:

`jupyter lab myfile.ipynb myfile.csv` It may be useful to have 2 separate tabs open.

I have always found that the workflow of opening something and then moving things around to tab them in a separate place to be a bit annoying 😶.

This is probably a bigger and different issue, but how could some "predefined" positions be defined (in a customizable way) so that every time I open a terminal I get in the bottom right, and every time I open a data grid I see in the top right (or something.)

**Comment by jasongrout** [comment] 2020-09-04 19:35
For starters, I would love to just see the files opened. Then I would suggest having a cli switch for opening in single-document mode, so it could be similar to the notebook (simplified interface, open a file).

**Comment by goanpeca** [comment] 2020-09-04 19:39
>For starters, I would love to just see the files opened.

Agreed :-)

**Comment by dclong** [comment] 2020-09-08 18:01
Related to this issue: https://github.com/jupyterlab/jupyterlab/issues/5056

**Comment by agoose77** [comment] 2020-10-08 11:03
Would it be acceptable to add this in the form of a new subcommand? That way we don't shadow the existing subcommands e.g. `build`, `clean`.

**Comment by telamonian** [comment] 2020-10-12 19:48
@agoose77 I think the convention would either be to require an `-f` flag (or the like) in front of each file path, or to add a separator between any flags/subcommands and the list of files to open (eg `jupyter lab -- file1.txt file2.txt etc`).

Of course we could also do a new subcommand like `jupyter labopen`, but that feels like it would be overkill/confusing, since you're essentially doing the same action as the `lab` subcommand (ie open jlab) but with some bells and whistles

**Comment by EricCousineau-TRI** [comment] 2021-01-20 12:32
Huh... it seems like this issue is more of a regression in UX?
We were using `jupyter lab <notebook>` for `jupyterlab==2.2.8`, and it worked fine; however, upon upgrading to `jupyterlab==3.0.3`, it seems like this indeed doesn't work :(

Reproduction steps (for Ubuntu 18.04, CPython 3.6.9, with `python3-venv` apt package installed); see result of `pip freeze` for each env here (at time of writing):
https://gist.github.com/EricCousineau-TRI/52697ee5c13fc928ca342a2048b156a1
```sh
mkdir /tmp/jupyter_example && cd /tmp/jupyter_example

cat > example_notebook.ipynb <<EOF
{
 "cells": [],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
EOF

mkdir old && cd old
python3 -m venv .
./bin/pip install -I pip==20.3.3
./bin/pip install jupyterlab==2.2.8 ipykernel==5.3.4 notebook==6.1.4
./bin/jupyter lab ../example_notebook.ipynb
# Yay, it opens it up!
# Final URL: http://localhost:8888/lab/tree/example_notebook.ipynb

cd ..
mkdir new && cd new
python3 -m venv .
./bin/pip install -I pip==20.3.3
./bin/pip install jupyterlab==3.0.3 ipykernel==5.4.3 notebook==6.1.6
./bin/jupyter lab ../example_notebook.ipynb
# It just opens up the plain Launcher tab :(
# Final URL: http://localhost:8888/lab
```

EDIT: Also tried `./bin/pip install jupyterlab==3.0.3 ipykernel==5.3.4 notebook==6.1.4` to see if those may have anything to do with it - same result as `new`, where command-line notebook arg is still effectively ignored.

NOTE: Transferred from this post :facepalm:

**Comment by EricCousineau-TRI** [comment] 2021-01-20 12:34
My vote is that we restore the functionality that was present in older `jupyterlab`; then worry about design for multiple files as a separate isssue?

**Comment by EricCousineau-TRI** [comment] 2021-01-20 12:48
I don't know diddly about the internals of the Jupyter ecosystem (can review the docs at a later point), but doing a naive diff between `v2.2.8..v3.0.3`, maybe it's something related to these changes? https://github.com/jupyterlab/jupyterlab/pull/7416 commit: c667d853
@echarles If you have time to peek in, do you think this may be it related to the command-line "regression"?

**Comment by echarles** [comment] 2021-01-20 13:15
@EricCousineau-TRI I think https://github.com/jupyter-server/jupyter_server/issues/278 is not the cause of the issue reported here. To let you know, jupyterlab 3 is using jupyter-server as server, whereas jupyterlab 2 is using the classic notebook. So yes, prolly the root cause of this issue is that change.

**Comment by EricCousineau-TRI** [comment] 2021-01-20 13:34
Gotcha, thanks!

I'm reviewing some of the dev docs - do you have any quick pointers on how to modify command-line parsing for the `lab` subcommand for `jupyterlab>=3`?

**Comment by EricCousineau-TRI** [comment] 2021-01-20 13:37
Oh... it looks like the logic is here? Just not sure how to connect the dots between `sys.argv`, the relevant superclasses, and this code:
https://github.com/jupyterlab/jupyterlab/blob/089af7012759e80ce6dcb7503bfadee67bf82a90/jupyterlab/labapp.py#L660-L664

**Comment by EricCousineau-TRI** [comment] 2021-01-20 13:46
My free-wheeling guess points in this general direction:
https://github.com/jupyter-server/jupyter_server/blob/edf4a08784a191130a199d5ea0b1ab6b83d7d3fc/jupyter_server/extension/application.py#L341-L367

**Comment by jasongrout** [comment] 2021-01-20 15:08
Moving to 3.1 since it is indeed a regression from 2.x.

**Comment by jasongrout** [comment] 2021-01-20 15:11
Here is the relevant code from Jupyter Server: https://github.com/jupyter-server/jupyter_server/blob/edf4a08784a191130a199d5ea0b1ab6b83d7d3fc/jupyter_server/serverapp.py#L1322

**Comment by jasongrout** [comment] 2021-01-20 15:13
Note that with jlab 3, `jupyter lab <directory>` does correctly set that directory as the root directory, so at least that part is working.

**Comment by jasongrout** [comment] 2021-01-20 15:28
It looks like this works:

```diff
diff --git a/jupyterlab/labapp.py b/jupyterlab/labapp.py
index d373b36df9..92e55720b1 100644
--- a/jupyterlab/labapp.py
+++ b/jupyterlab/labapp.py
@@ -660,7 +660,7 @@ class LabApp(NBClassicConfigShimMixin, LabServerApp):
         if self.serverapp.file_to_run:
             relpath = os.path.relpath(self.serverapp.file_to_run, self.serverapp.root_dir)
             uri = url_escape(ujoin('{}/tree'.format(self.app_url), *relpath.split(os.sep)))
-            self.default_url = uri
+            self.serverapp.default_url = uri
             self.serverapp.file_to_run = ''
```

And indeed, it looks like setting `--LabApp.default_url` has no effect.

**Comment by jasongrout** [comment] 2021-01-20 15:38
@Zsailer - any thought on why `jupyter lab --LabApp.default_url` has no effect, but `jupyter lab --ServerApp.default_url` does? See also the comment just above this, showing we have to set the server app default url to get the 'open file from command line' behavior working.

**Comment by Zsailer** [comment] 2021-01-21 17:25
jupyter-server/jupyter_server#393 addresses this issue. 

Note, nbclassic will (temporarily) raise a warning that this trait exists in both ServerApp and LabApp. This warning is dropped in this PR: https://github.com/jupyterlab/nbclassic/pull/42#pullrequestreview-573548923

**Comment by EricCousineau-TRI** [comment] 2021-01-21 17:27
Sweet, thank you!
How should this issue be closed? Just want me to test on my end to see if cmd-line now works as expected?

**Comment by Zsailer** [comment] 2021-01-21 17:29
I'll cut some patch releases of jupyter_server + nbclassic today, but if you want to test out these changes before, that would be great.

**Comment by EricCousineau-TRI** [comment] 2021-01-21 19:20
Works great!!!

I updated my above repro steps to include `jupyter-server@master`:
```sh
mkdir /tmp/jupyter_example && cd /tmp/jupyter_example
cat > example_notebook.ipynb <<EOF
{
 "cells": [],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
EOF

mkdir new && cd new
python3 -m venv .
./bin/pip install -I pip==20.3.3
./bin/pip install jupyterlab==3.0.3 ipykernel==5.4.3 notebook==6.1.6
./bin/pip install git+https://github.com/jupyter-server/jupyter_server@2477da6d8f1df4ceade1fa4412bdd0e19ee09ed1
./bin/jupyter lab ../example_notebook.ipynb
# Ermagherd, it worked!
# Final URL: http://localhost:8888/lab/tree/example_notebook.ipynb
```

**Comment by jtpio** [comment] 2021-01-30 13:03
Opening a notebook from the command line seems to be fixed with `jupyter-server==1.2.3`: https://github.com/jupyter-server/jupyter_server/releases/tag/1.2.3

To update:

```bash
pip install -U jupyter-server
```

**Comment by meeseeksmachine** [comment] 2021-02-05 02:12
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/changing-default-tab-when-jupyterlab-starts/7808/5

**Comment by jasongrout** [comment] 2021-02-05 02:21
It looks like Jupyter Server 1.2.3 was pulled from pypi as a broken release. I just tried with Jupyter Server 1.3.0, though, and this still does not work to open `test.txt`:

```
jupyter lab ./test.txt
```

However, this does work now:

```
jupyter lab --LabApp.default_url='/lab/tree/test.txt'
```
so at least there's that.

(Thought it opens test.txt *and* a Launcher tab, where I would have expected it to not open a default launcher since it was already opening another file)

**Closed** 2021-02-18 11:09 UTC
Labels: type:Enhancement

**Comment by dclong** [comment] 2021-02-18 17:56
Does it work if a jupyter_server is already running? Will it start a new jupyter_server or running the notebook using the existing jupyter_server?

**Comment by jasongrout** [comment] 2021-02-18 18:01
IIRC, `jupyter lab <file>` starts a new server.

**Comment by jtpio** [comment] 2021-02-19 09:10
With https://github.com/jupyter-server/jupyter_server/pull/415 and https://github.com/jupyterlab/jupyterlab_server/pull/162, it looks like it will be possible to remove this logic?

https://github.com/jupyterlab/jupyterlab/blob/13f6daf68f30c4470c836f99906fc0010d307bd4/jupyterlab/labapp.py#L660-L664
