### ISSUE TITLE
"jupyter labextension develop" fails when using '-' in package names

### ISSUE THREAD

**Issue by raulotaolea** [jupyterlab/jupyterlab#9576] opened 2021-01-08 19:00 UTC
## Problem
After creating an extension using cookiecutter:

```zsh
cookiecutter https://github.com/jupyterlab/extension-cookiecutter-ts
```
with the following data:
```zsh
author_name []: 
python_name [myextension]: extension-name-with-hyphens
labextension_name [extension-name-with-hyphens]: extension-name-with-hyphens
project_short_description [A JupyterLab extension.]: 
has_server_extension [n]: 
has_binder [n]: 
repository [https://github.com/github_username/extension-name-with-hyphens]: 
```
and then using `jupyter labextension` command to develop it:
```zsh
cd extension-name-with-hyphens
jupyter labextension develop . --overwrite
```
it fails after installing the extension, without creating a symlink to the jupyterlab dir:
```
...
Installing collected packages: extension-name-with-hyphens
  Running setup.py develop for extension-name-with-hyphens
Successfully installed extension-name-with-hyphens
An error occured.
ModuleNotFoundError: No module named 'extension_name_with_hyphens'
See the log file for details:  /var/folders/__/z_79kpl14rscmfdcnrk5dnw80000gn/T/jupyterlab-debug-gacaqqs5.log
```
During the process, **hyphens in the extension name are replaced by underscores**, causing the error.

## Proposed Solution
It seems that `develop` command replaces `-` with `_` [here](https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/federated_labextensions.py#L379), resulting in the error described. It should not do the replacement.

## Additional context
JupyterLab 3.0

**Comment by raulotaolea** [comment] 2021-01-08 19:21
@meeseeksdev tag Extensions

**Comment by raulotaolea** [comment] 2021-01-08 19:22
@meeseeksdev tag tag:Extensions

**Comment by raulotaolea** [comment] 2021-01-11 14:04
@meeseeksdev tag type:Bug

**Comment by jasongrout** [comment] 2021-01-13 21:57
Looks like this was introduced in #9471 by @jtpio and reviewed by @blink1073 - can either of you comment about this?

**Comment by jtpio** [comment] 2021-01-14 08:03
I think the reasoning behind https://github.com/jupyterlab/jupyterlab/pull/9471 was to address the case of the distribution name being with `-` and the package name with `_`.

However it's true that it appears broken at the moment when the distribution name and the package name are the same (faced the same issue recently with an extension).

We can probably revert that change for now (what this PR does), and iterate on the `develop` script more (to try to address https://github.com/jupyterlab/jupyterlab/issues/9421)

**Comment by jasongrout** [comment] 2021-01-14 08:04
> We can probably revert that change for now (what this PR does), and iterate on the `develop` script more (to try to address #9421)

Feel free to merge, then, if this PR is good to you.

**Comment by jtpio** [comment] 2021-01-14 08:07
> what this PR does

This PR: https://github.com/jupyterlab/jupyterlab/pull/9577

**Comment by jtpio** [comment] 2021-01-14 08:08
> I think the reasoning behind #9471 was to address the case of the distribution name being with `-` and the package name with `_`.

However the script will most likely fail again in this case.

Maybe a better fix could be to try with both `-` and `_`?

**Comment by jtpio** [comment] 2021-01-14 18:10
> and then using `jupyter labextension` command to develop it:
> 
> ```shell
> cd extension-name-with-hyphens
> jupyter labextension develop . --overwrite
> ```

@raulotaolea hmm this is what I get when reproducing the steps in a new environment:


https://user-images.githubusercontent.com/591645/104631107-0f820c00-569c-11eb-9f2c-59ec9eb6c851.mp4

With the correct symlink:

```bash
$ ls -lisah ${CONDA_PREFIX}/share/jupyter/labextensions/
total 12K
drwxrwxr-x 2 jtp jtp 4.0K Jan 14 19:08 .
drwxrwxr-x 6 jtp jtp 4.0K Jan 14 19:08 ..
lrwxrwxrwx 1 jtp jtp   88 Jan 14 19:08 extension-name-with-hyphens -> /path/to/extension-name-with-hyphens/extension-name-with-hyphens/labextension

```

**Comment by jtpio** [comment] 2021-01-15 10:31
@raulotaolea do you still get the issue when using the same steps as described in the [video above](https://github.com/jupyterlab/jupyterlab/issues/9576#issuecomment-760369282), after creating a new environment?

**Comment by raulotaolea** [comment] 2021-01-18 10:52
Hi @jtpio, thanks a lot for taking the time to dig into this.

I'm creating the environment with conda:
```zsh

conda create --name test python=3.8
conda activate test
conda install -c conda-forge jupyterlab jupyter-packaging cookiecutter
```
then I check versions:
```zsh
jupyter --version
```
```zsh
jupyter core     : 4.7.0
jupyter-notebook : 6.2.0
qtconsole        : not installed
ipython          : 7.12.0
ipykernel        : 5.4.2
jupyter client   : 6.1.11
jupyter lab      : 3.0.5
nbconvert        : 6.0.7
ipywidgets       : not installed
nbformat         : 5.1.2
traitlets        : 5.0.5
```
Then I use cookiecutter to create the extension template:
```zsh
cookiecutter https://github.com/jupyterlab/extension-cookiecutter-ts
```
```zsh
author_name []: 
python_name [myextension]: extension-name-with-hyphens
labextension_name [extension-name-with-hyphens]: extension-name-with-hyphens
project_short_description [A JupyterLab extension.]: 
has_server_extension [n]: 
has_binder [n]: 
repository [https://github.com/github_username/extension-name-with-hyphens]: 
```
And finally used `labextension` command:
```zsh
cd extension-name-with-hyphens
jupyter labextension develop . --overwrite
```
and got the same error.

The difference is that I'm using python 3.8 and I have nodejs v14.15.1 already installed.

**Comment by raulotaolea** [comment] 2021-01-20 10:53
@jtpio I have tried the same steps (`aaa-aaa-aaa` as project name) in a clean Ubuntu 20.04 and I got the same error:

<img width="1600" alt="Captura de pantalla 2021-01-20 a las 10 52 09" src="https://user-images.githubusercontent.com/27988486/105157758-96583e00-5b0d-11eb-8977-eb43eb9aa35b.png">

It only works if I provide the `python_name` with underscores, e.g, `package_name`. `labextension_name` could be with hyphens, e.g, `extension-name`.

Btw, I noticed a verification error in your video. It seems that `federated_labextenions.py` is corrupted. Could you be using another version?

**Comment by jtpio** [comment] 2021-01-21 09:33
> Btw, I noticed a verification error in your video. It seems that `federated_labextenions.py` is corrupted. Could you be using another version?

Thanks @raulotaolea for pointing that out. It indeed looks like the package was corrupted.

I could reproduce the issue after recreating the environment from scratch with JupyterLab 3.0.5.

**Comment by hbcarlos** [comment] 2021-01-21 09:37
I'm facing the issue too. I'll be happy to open a PR for a robust solution.

**Comment by jtpio** [comment] 2021-01-21 09:45
Thanks @hbcarlos for looking into this too.

Ideally the `develop` command should handle these cases:

1. `extension-with-hyphens` as distribution with `extension-with-hyphens` as the module
2. `extension-with-hyphens` as distribution with `extension_with_hyphens` as the module
3. `extension_with_hyphens` as distribution with `extension_with_hyphens` as the module

https://github.com/jupyterlab/jupyterlab/pull/9471 was meant to handle 2, but it looks like it doesn't with 1.

Maybe there could also be a way to test these cases on CI (probably in the usage tests).

**Comment by raulotaolea** [comment] 2021-01-21 14:54
Yep, exactly, the first case is the one not working. In the meantime, I've sorted it out naming the extensions as in the 2nd case.

**Comment by jtpio** [comment] 2021-02-05 17:12
FYI @raulotaolea closing as this should be fixed in https://github.com/jupyterlab/jupyterlab/pull/9655

Many thanks for reporting and the details!

**Closed by jtpio** 2021-02-05 17:12 UTC
Labels: tag:Extensions, type:Bug

**Comment by raulotaolea** [comment] 2021-02-09 11:20
Thanks to you @jtpio !
