### ISSUE TITLE
No warning/error message when kernal is forced to restart

### ISSUE THREAD

**Issue by NicWayand** [jupyterlab/jupyterlab#4273] opened 2018-03-29 17:43 UTC
Sometimes when running a notebook the kernal restarts (in my case due to a OOM issue) but does not give the user any message. The cell will still show an asterisk, as if its running, but only when the user hovers the mouse over the circle at the top right, will it show that the kernal is restarting.

I would expect a larger warning to the user, either in the current cell, or at the top of the notebook, to let them now some issue has occurred.

In the terminal where jupyter lab was started gives: 
`KernelRestarter: restarting kernel (1/5), keep random ports`

jupyterlab 0.31.12

**Comment by clkao** [comment] 2018-10-22 07:39
This happens in 0.34.7 as well.

**Comment by clkao** [comment] 2018-12-24 16:19
Note for plain old notebook, there's a simple popup for OOM/restarted kernel, which should be informative enough.

<img width="1144" alt="2018-12-25 12 17 05" src="https://user-images.githubusercontent.com/69736/50403586-ac825b80-07da-11e9-8714-86c99d39dc43.png">

**Comment by kykrueger** [comment] 2019-02-07 15:53
I'd like to see more details as to why the kernel has had to restart. Some sort of stack trace from what the kernel was trying to execute.

**Comment by jasongrout** [comment] 2019-02-07 16:17
That would be great, however if it was an OOM, it's killed suddenly without a stack trace, IIRC.

**Comment by kykrueger** [comment] 2019-02-07 16:45
How can we tell if it was an OOM problem?

**Comment by jasongrout** [comment] 2019-02-08 07:12
With our current infrastructure, I'm not sure you could easily. The process is gone and we just notice it no longer is responding to heartbeats.

**Comment by kykrueger** [comment] 2019-02-08 09:25
Gotcha, 

Some of the jupyter docs for [the architecture](https://jupyter.readthedocs.io/en/latest/architecture/how_jupyter_ipython_work.html) were really helpful for understanding where the limitation lies. Would I be correct to assume that this crash and restart is caused by a timeout between the kernel and notebook server?

Is this something that the notebook server has an interface for, but the kernel has not implemented?

**Comment by jasongrout** [comment] 2019-02-08 15:38
> Is this something that the notebook server has an interface for, but the kernel has not implemented?

Right. There is a message the server sends the frontend that indicates the restart happened without a user request, and JupyterLab currently is not distinguishing between that and a restart requested by the user. The classic notebook notifies the user if a restart happens that was not requested.

I worked on this and many other things in #4724, but that turned into a much more ambitious project that should be postponed until after 1.0. I still plan to look again at this specific issue to investigate solving just it (https://github.com/jupyterlab/jupyterlab/issues/4748 is the 1.0 issue for this, though perhaps this should be the 1.0 issue and that should be closed as a duplicate).

**Comment by jasongrout** [comment] 2019-02-08 15:41
> I still plan to look again at this specific issue to investigate solving just it

And as with any issues, help is welcome! If anyone wants to take this up, please comment on the issue so that work isn't duplicated.

**Comment by kykrueger** [comment] 2019-02-10 11:59
> I worked on this and many other things in #4724, but that turned into a much more ambitious project that should be postponed until after 1.0.

@jasongrout that looks like quite the rabbit-hole. I'd be quite happy if we can solve this separately. I've never used TypeScript or JavaScript, but I'll see if I can help.

**Comment by jasongrout** [comment] 2019-04-23 19:54
For reference, here is where that message is displayed in the classic notebook: https://github.com/jupyter/notebook/blob/eea37a6b2110e0b8a5491f17e241fa3c8aecb5f7/notebook/static/notebook/js/notificationarea.js#L122-L146

and it is triggered here: https://github.com/jupyter/notebook/blob/eea37a6b2110e0b8a5491f17e241fa3c8aecb5f7/notebook/static/services/kernels/kernel.js#L1106-L1113

**Comment by jasongrout** [comment] 2019-04-24 00:39
It seems that killing the kernel process so that it autostarts does not work in jlab (I can't use the newly started kernel)

**Closed** 2019-05-15 11:15 UTC
Labels: pkg:notebook, type:Enhancement
