### ISSUE TITLE
Downloading an svg file using the file browser fails

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#6658] opened 2019-06-20 04:33 UTC
To reproduce:

* Create an svg file.
* Right click on it in the file browser.
* Select "Download"

Browser gives a download error.

**Comment by jasongrout** [comment] 2019-06-20 04:56
I just went to an svg in our source, right clicked, and downloaded, and it worked great. What was the error?

**Comment by echarles** [comment] 2019-06-20 07:13
I have just build current master and tried to download a file (svg, ppt...) - I get error in the chrome (Failed - Forbidden) - Strangely, I don't see a request in devtools.

The server log shows:

```
[W 09:08:19.210 LabApp] Blocking request with no referer
[W 09:08:19.211 LabApp] 403 GET /files/amazon/AWS_Simple_Icons_ppt.pptx (::1): Blocking request from unknown origin
[W 09:08:19.212 LabApp] 403 GET /files/amazon/AWS_Simple_Icons_ppt.pptx (::1) 2.16ms referer=None
```

**Strangely, the same actions in Firefox works well (no error, file is downloaded correctly)!!!**

Chrome Incognito fails also.

**Comment by echarles** [comment] 2019-06-20 07:24
This is prolly duplicate of #6609. I guess @jasongrout browser if FF while @saulshanabrook and @ellisonbg browser is Chrome.

**Comment by jasongrout** [comment] 2019-06-20 12:01
> I guess @jasongrout browser if FF

You're right that I am using FF. Sorry for not mentioning it earlier.

**Comment by jasongrout** [comment] 2019-06-20 12:03
https://github.com/jupyterlab/jupyterlab/issues/6106 looks relevant

**Comment by jasongrout** [comment] 2019-06-20 12:18
Looks like we should probably revert #6546, given the discussion on #6106 and #6546.

**Comment by jasongrout** [comment] 2019-06-20 12:19
Or perhaps we can (shudder) do a browser test and only have the download attribute in firefox, but not in Chrome?

**Comment by athornton** [comment] 2019-06-21 17:55
1.0.0a.10 still exhibits this behavior: in Chrome, I get a "Failed - Forbidden" when I try to download a file.  (It appears that file type does not matter).  I *can* download in Safari.

Most of my users use Chrome, and many of them like to download files.

As far as I can tell, no log of the event is being generated--I neither see an HTTP request on the Network tab of Developer Tools nor a log in the console.

**Comment by tslaton** [comment] 2019-06-21 18:02
I'm working on this right now.

**Comment by tslaton** [comment] 2019-06-21 21:46
Adding the xsrf token as @minrk suggested here: https://github.com/jupyterlab/jupyterlab/issues/6106#issuecomment-476535334 solves this issue. But I'm wary of the potential security implications of doing this. I don't have a good understanding of the xsrf token.

Is there a risk in exposing it in the href in this way @minrk?

**Comment by tslaton** [comment] 2019-06-21 22:29
If PR https://github.com/jupyterlab/jupyterlab/pull/6686 looks secure, I recommend we go with it. I'm going to create another PR with an approach I know is safe in the meantime.

**Closed** 2019-06-21 23:27 UTC
Labels: pkg:filebrowser, type:Bug
