### ISSUE TITLE
Newline auto-indent after using quotation marks inside f-string curly brackets

### ISSUE THREAD

**Issue by atsukoba** [jupyterlab/jupyterlab#6319] opened 2019-05-07 13:26 UTC
Apologies if this is already a known issue.
Auto-indent with newlines do not work correctly when using two types of quotation marks inside Python3.6 style `f-string` as function arguments (or use f-string in the parentheses). 

Editor misrecognized the indent position and all the newlines after `print()` will be auto-indented to the column of `print()`, since the parenthese `)` of the `print()` is recognized as strings. I think this should be a bug.

[![Image from Gyazo](https://i.gyazo.com/e6d6e2e7835815026aef60876374f314.gif)](https://gyazo.com/e6d6e2e7835815026aef60876374f314)

### Environment

- `jupyter` 4.4.0
- `jupyterlab` 0.35.6
- Python 3.6.4 (anaconda3-5.1.0)
- macOS Mojave 10.14.4
- Google Chrome 74.0.3729.131

**Comment by jasongrout** [comment] 2019-05-07 16:53
Does it work in CodeMirror? https://codemirror.net/mode/python/index.html

**Comment by atsukoba** [comment] 2019-05-07 17:29
@jasongrout Thank you for your response.

On the CodeMirror page, this situation was not reproduced.

**Comment by atsukoba** [comment] 2019-05-07 17:33
This issue on CodeMirror repo should be relevant to this error.

[Wrong highlighting and indentation for Python f-strings with nested strings #5668](https://github.com/codemirror/CodeMirror/issues/5668)

**Comment by jasongrout** [comment] 2019-05-07 18:12
Looks like it's in codemirror 5.42. So this is either already solved in master, or it will be by #6313. So it sounds like we should close this as either already fixed, or as a duplicate to #6313. Do you want to try tackling #6313? It's a good first issue to upgrade codemirror.

**Comment by jasongrout** [comment] 2019-05-07 18:12
(Also, thanks for the excellent report - your gif above made the problem very easy to see)

**Closed by jasongrout** 2019-05-07 18:12 UTC

**Comment by jasongrout** [comment] 2019-05-07 18:13
Looks like this is a duplicate of https://github.com/jupyterlab/jupyterlab/issues/5588, actually.
