### ISSUE TITLE
JLab cell collapser frontend & backend get out-of-sync when deleting collapsed cells

### ISSUE THREAD

**Issue by Pete-rePete** [jupyterlab/jupyterlab#16525] opened 2024-06-25 19:37 UTC
## Description
Possible duplicate of https://github.com/jupyterlab/jupyterlab/issues/10593, but documenting / characterizing it more thoroughly.

* The frontend treats deletion of collapsed cells as a "group delete". Upon deletion, all the collapsed cells are gone.
* The backend treats it like it's only deleting the header, not the collapsed cells. So, upon re-opening, only the header is gone.

See the 20-second GIF below.
![jlab_bug](https://github.com/jupyterlab/jupyterlab/assets/11905777/ae4f1c68-2b58-4224-96ac-edf6a01cb76a)

## Reproduce

1. Create 2 header cells with a couple code cells beneath each
2. Collapse the header
3. Delete it, and save. Notice how the header + all the collapsed cells are gone.
4. Close the JLab tab, then re-open it. Notice how all the collapsed cells aren't gone.

## Expected behavior

I would expect all the collapsed cells to be properly deleted.

## Context

- First, I ran latest `jupyter/base-notebook`, which looking at it, isn't particularly up-to-date. (uses ubuntu I believe)
```
REPOSITORY             TAG          IMAGE ID       CREATED        SIZE
jupyter/base-notebook  latest       07bb7d6acc26   8 months ago   1.07GB
```
- Next, on my Windows machine I just pip installed `jupyterlab-4.2.2` and ran `jupyter lab` and reproduced it exactly the same way.

**Comment by krassowski** [comment] 2024-06-25 19:51
There is no logic on backend, so I would expect it all to have the same case as https://github.com/jupyterlab/jupyterlab/issues/10593.

**Comment by Pete-rePete** [comment] 2024-06-26 15:25
Ah yes, the bug is related to the frontend selector, and this issue is a dupe

**Comment by JasonWeill** [comment] 2024-07-02 16:15
Closing as a duplicate of #10593. Thanks @Pete-rePete for your contribution!

**Closed by JasonWeill** 2024-07-02 16:15 UTC
Labels: bug, status:Needs Triage
