### ISSUE TITLE
Run cells with a specified tag

### ISSUE THREAD

**Issue by jweill-aws** [jupyterlab/jupyterlab#12069] opened 2022-02-16 17:17 UTC
Split from #11926 by @icankeep

### Problem

No way to run all the cells associated with a given tag

### Proposed Solution

Provide an option in the UI to run cells with a specified tag.

**Comment by krassowski** [comment] 2022-12-28 15:04
It appears to be a duplicate of #2917.

**Closed** 2022-12-28 17:28 UTC
Labels: status:Duplicate, enhancement
