### ISSUE TITLE
Is there a way to turn off these settings/file name borders in Juypyter lab?

### ISSUE THREAD

**Issue by mjnur** [jupyterlab/jupyterlab#15708] opened 2024-01-28 17:54 UTC
### Problem
I upgraded to Jupiter lab 4.0.11 recently and found that now my files and settings I navigate to have this blue/white border around them now, like some accessibility mode has been enabled?

<img width="332" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/35612704/57835a8b-aa34-45cb-b8cf-2b68ae5ebf3f">

<img width="248" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/35612704/6b64de91-ab38-43c5-bec6-880b7fa27ede">

### Proposed Solution

Is there a setting to turn this feature off? it was automatically enabled for me after downloading Jupiter lab 4.0.11. I could not find this after doing some searches trying to describe this. 

Apologies in advance if this information already exists somewhere. Thank you!

**Comment by jans-code** [comment] 2024-01-29 09:39
i think those boxes are quite annoying too.
you can add

```
.jp-DirListing-itemText:Focus {
    outline-width: 0px;
}
```

to your theme's css.

**Comment by krassowski** [comment] 2024-01-29 11:33
I fully agree that this is quite annoying and would love to find a solution which satisfies both an average user and the accessibility requirements. This issue is a duplicate of https://github.com/jupyterlab/jupyterlab/issues/14678 so let's revive the discussion in there - thanks!

**Closed by krassowski** 2024-01-29 11:33 UTC
Labels: status:Duplicate, enhancement, pkg:fileeditor, status:Needs Triage
