### ISSUE TITLE
Favorites files/paths in filebrowser

### ISSUE THREAD

**Issue by malliwi88** [jupyterlab/jupyterlab#1412] opened 2016-12-13 03:09 UTC
I think it might be useful to have a Bar or option to store favorite items, so that navigation is expedited to files that are often used.

**Comment by blink1073** [comment] 2016-12-13 14:15
Agreed, thank you for the suggestion.  This depends on our forthcoming handling of Settings.

**Comment by ellisonbg** [comment] 2017-12-19 06:32
Closing as duplicate of #2043

**Closed by ellisonbg** 2017-12-19 06:32 UTC
Labels: pkg:filebrowser, type:Enhancement
