### ISSUE TITLE
Shareable link not directing to correct file

### ISSUE THREAD

**Issue by pmarcellino** [jupyterlab/jupyterlab#8607] opened 2020-06-24 06:43 UTC
## Description

When in jupyterlab I right click a file and then copy the shareable link and post it into a new tab, I end up at the last jupyter lab window I had open, not the one in the link.

Here is an example link
http://localhost:8889/lab/tree/Documents/Documents/Curve%20Approximation.ipynb

## Reproduce

Go to JupyterLab
Right click file in browser
Click "Copy shareable link"
Post link in new tab
You don't end up at the linked file

## Expected behavior

Opening the linked file in JupyterLab

**Comment by pmarcellino** [comment] 2020-06-24 19:03
I went in and did a whole new os and jupyter lab install on a fresh box and end up with the same issue.

**Comment by pmarcellino** [comment] 2020-06-25 16:31
@afshin I've been trying to dive into this as best I can. Could it somehow be related to the changes in https://github.com/jupyterlab/jupyterlab/pull/6234 ?

I think it might have to do with the link not having a workspace in it anymore, which then redirects to the default workspace and ignore the tree portion of the URL?

Although it could very easily be that I am just misunderstanding the changes you made, and that they aren't related at all.

Thank you,
pmarcellino

**Comment by afshin** [comment] 2020-06-25 16:42
@pmarcellino I'm not sure when this regression happened, but I'm seeing this behavior in the current version of JupyterLab in the main branch. I don't think the bug has existed since the PR you linked because that was over a year ago, but clearly something has indeed changed. Thanks for the bug report!

**Comment by afshin** [comment] 2020-06-25 16:42
If we fix this in time for a 2.2 release, that is even better, but I've tagged it with the 3.0 milestone for now.

**Comment by pmarcellino** [comment] 2020-06-26 21:27
Thanks afshin. I was trying to further trouble shoot what could be causing the issue, but it's just too complicated for me.

**Comment by afshin** [comment] 2020-06-27 03:42
Thank you! It's a good lead and it could just be wishful thinking on my part to hope the bug has not existed for a year, it may well have. Cheers!

**Comment by yzq89** [comment] 2020-07-16 10:00
I've been tracking this issue as we're users of the redirect functionality. I suspect this issue is related & could be helpful in identifying the bug: https://github.com/jupyterlab/jupyterlab/issues/8359

**Comment by ellisonbg** [comment] 2020-09-13 17:31
Fixed in master, closing.

**Closed** 2020-09-18 18:40 UTC
Labels: type:Bug
