### ISSUE TITLE
How can I resume the long time running cell and continue output?

### ISSUE THREAD

**Issue by GF-Huang** [jupyterlab/jupyterlab#9621] opened 2021-01-14 22:22 UTC
### Problem
I started jupyter-lab by `screen`. I'm using tensorflow to training my model, but I lost the connection. How can I resume the running cell (which it's training) and continue output?

![image](https://user-images.githubusercontent.com/4510984/104656204-ded0bf80-56f9-11eb-8657-bfe526e5d360.png)

#### It's running, the lost star `[*]`, and the output did not update.

![image](https://user-images.githubusercontent.com/4510984/104656283-00ca4200-56fa-11eb-9299-0b8fc063eee5.png)

**Comment by set92** [comment] 2021-07-01 05:23
I think this is a duplicated of #4237, not sure which one you want to keep.

**Comment by krassowski** [comment] 2023-12-02 13:56
Closing as a duplicate of of #2833.

Of note there is now a PR implementing this: https://github.com/jupyterlab/jupyterlab/pull/15448

**Closed by krassowski** 2023-12-02 13:56 UTC
Labels: enhancement, tag:Real Time Collaboration
