### ISSUE TITLE
Ideas on how to improve the find experience

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#13756] opened 2023-01-11 23:34 UTC
### Problem

The find experience does not feel as intutive as other editors (jetbrains, vscode, etc). Below is a list of ideas to consider to improve this.

### Proposed Solution

Below is somewhat ordered from our perceived most to least value.

1. If the search box is open, the first escape should close that, even when in cell edit mode. Today you need to either click the x or push the hotkey then escape. At that point you are no longer focused in the cell you were trying to edit.
2. Merge cell search + notebook search. It would improve the UX to have a single experience on how to find something. Today there are two ways and it's confusing at times. UX experience suggestion:
a. Whether cell vs. notebook searching is done should depend on a toggle icon inside the search textbox (i.e. move the selected cell option from the hidden `...`).
b. If the toggle is disabled, it should act like the current notebook search.
c. If the toggle is enabled, we're in cell editing mode, and some text is selected, then the scope should be limited to that selected text
d. if the toggle is enabled, we're in cell editing mode, and no text is selected, then the scope should be limited to the current cell
e. if the toggle is enabled, we're in command mode, and some cells are selected, then the scope should be limited to those cells (and not be affected by any selections inside those cells)
f. if the toggle is enabled, we're in command mode, and no cells are selected, then the scope should be limited to the current cell
3.  When find is opened it should either:
a. Start with the currently selected text
b. The last text it was closed with
c. Nothing if it was the first time and no text is selected
4. Add whole word matching
5. Add replace with preserve case

### Additional context

I think VSCode does this very well and it would be a good project to use as a guide.

**Comment by krassowski** [comment] 2023-01-14 12:06
> 1. If the search box is open, the first escape should close that, even when in cell edit mode. Today you need to either click the x or push the hotkey then escape. At that point you are no longer focused in the cell you were trying to edit.

This was previously reported in https://github.com/jupyterlab/jupyterlab/issues/13311 and my fix from  https://github.com/jupyterlab/jupyterlab/pull/13340 was merged into 4.0 branch.

> 2. Merge cell search + notebook search. It would improve the UX to have a single experience on how to find something. Today there are two ways and it's confusing at times.

+1 I agree with points (a)-(f). Previously it was suggested that we add a shortcut to activate CodeMirror-level fine and replace (https://github.com/jupyterlab/jupyterlab/issues/6650#issuecomment-879829848.), but I agree that it is better to have a consistent UI box for all of them.

However, I think that we will need a visual indicator of sorts to convey what is the search region as otherwise it will still be confusing. The indicator could be an added text in the search box or in-document highlight of the selected cells/selected text. Thoughts?

> Whether cell vs. notebook searching is done should depend on a toggle icon inside the search textbox

Together with (4) this could be too many buttons. We could hide some of them under a cog icon as in the GNOME text editor:

![Screenshot from 2023-01-14 11-51-06](https://user-images.githubusercontent.com/5832902/212470454-3a15daa2-f5ca-4b79-8d65-99ad5c3ab384.png)

Or collapse them into a context menu with a funnel icon:

[Screencast from 2023-01-14 11-55-33.webm](https://user-images.githubusercontent.com/5832902/212470569-29181534-5850-4467-bcbd-90885209ff36.webm)

> 3. When find is opened it should either:

+1

> 4. Add whole word matching

+1

> 5. Add replace with preserve case

+1

**Comment by krassowski** [comment] 2023-01-17 23:00
> When find is opened it should either:
> a. Start with the currently selected text

What would make more sense if selection is multi-line: start with the first line, or bail (as implemented currently)? Or maybe we should just implement multi-line search as proposed in https://github.com/jupyterlab/jupyterlab/issues/13801?

**Comment by krassowski** [comment] 2023-02-25 17:56
> Whether cell vs. notebook searching is done should depend on a toggle icon inside the search textbox (i.e. move the selected cell option from the hidden `...`)

On implementation level this is not trivial as all "filters" are abstracted and listed in `...`.

On UX level it seems the problem is that after closing and re-opening the search box the filters get collapsed in `...` again:

![search-state](https://user-images.githubusercontent.com/5832902/221372089-f1c4ceaf-bf30-4635-bc9c-a8edb43290fe.gif)


I propose that we:
- rework "Search Selected Cell(s)" filter to "Search in Selection" where selection is dynamically determined as in (b)-(f)
   - make the title dynamic, e.g. "Search in 2 Selected Cells", "Search in Selected Text" (or even "Search in 11 Selected Lines")
- ensure that the filters (`...`) are visible after closing and re-opening the panel
   - squeeze them one next to another to prevent occluding user notebook (reduce the cost of having it always on)
- change the three dots to a filter icon
- if any of the filters are active and the filters list is collapsed, show a small orange/blue dot over the filter icon to make user aware that filters which are not shown are active.

**Comment by krassowski** [comment] 2023-02-25 18:10
This could look like this:

![Screenshot from 2023-02-25 18-08-58](https://user-images.githubusercontent.com/5832902/221372827-f8d4e286-5644-492e-9473-b6c61796d436.png)

![Screenshot from 2023-02-25 18-10-14](https://user-images.githubusercontent.com/5832902/221372876-d14478f1-ff78-419a-b358-50fb55ef2776.png)

**Comment by krassowski** [comment] 2023-02-25 18:12
We could also move the filter icon closer to all other icons without sacrificing space in the input text:

![Screenshot from 2023-02-25 18-12-01](https://user-images.githubusercontent.com/5832902/221372953-63fbac76-1faf-4857-8491-aa731ab303ad.png)

**Closed** 2023-03-10 12:53 UTC
Labels: enhancement, tag:Search and Replace, pkg:documentsearch
