### ISSUE TITLE
Match highlight after replace in notebook gets lost

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#13968] opened 2023-02-12 15:36 UTC
While in #13884 I fix a number of issues in search and add tests, a few non-trivial bugs in the replace logic remain. These are not apparent in the unit tests at the moment because the updates are emitted after a debouncer delay; we should also test with the debouncer disabled so that we can account for the side-effects from delayed updates.

One of the issues is that after replacing the highlight is in a broken state:
- codemirror editor correctly shows the highlight
- search overlay shows `-/2` (after briefly correctly showing `1/2`)

Starting from:

![Screenshot from 2023-02-12 15-27-41](https://user-images.githubusercontent.com/5832902/218320281-2817bc7f-4e23-4eae-88ff-f0dba38c5247.png)

Expected (and briefly seen - greyed out because I needed to set a breakpoint in debugger to capture it in this transitive state):

![Screenshot from 2023-02-12 15-27-56](https://user-images.githubusercontent.com/5832902/218320271-9da9dd7b-9aa3-42fd-bf0d-9752b6176dfb.png)

Current:

![Screenshot from 2023-02-12 15-27-59](https://user-images.githubusercontent.com/5832902/218320258-212882bc-bd39-4e9d-8f28-d596ba18d890.png)

This is because the query gets restarted after replace operation:

![Screenshot from 2023-02-12 15-24-46](https://user-images.githubusercontent.com/5832902/218320058-3acf9f0a-cc84-4a52-b6c4-b070e8d3924d.png)

Notebook listens to changes (`_onSelectionChanged`):

https://github.com/jupyterlab/jupyterlab/blob/edfbea4f9c556875882dfbe71bf77d31e81e5883/packages/notebook/src/searchprovider.ts#L270-L273

which emits `stateChanged` signal (with an incorrect assumption that we should not highlight next item - this is only true if we are not in replace mode!):

https://github.com/jupyterlab/jupyterlab/blob/edfbea4f9c556875882dfbe71bf77d31e81e5883/packages/notebook/src/searchprovider.ts#L579-L592

https://github.com/jupyterlab/jupyterlab/blob/edfbea4f9c556875882dfbe71bf77d31e81e5883/packages/notebook/src/searchprovider.ts#L572-L577

this then leads via debouncer:

https://github.com/jupyterlab/jupyterlab/blob/edfbea4f9c556875882dfbe71bf77d31e81e5883/packages/documentsearch/src/searchmodel.ts#L41

https://github.com/jupyterlab/jupyterlab/blob/edfbea4f9c556875882dfbe71bf77d31e81e5883/packages/documentsearch/src/searchmodel.ts#L248-L252

https://github.com/jupyterlab/jupyterlab/blob/edfbea4f9c556875882dfbe71bf77d31e81e5883/packages/documentsearch/src/searchmodel.ts#L43-L47

to restarting the query:

https://github.com/jupyterlab/jupyterlab/blob/edfbea4f9c556875882dfbe71bf77d31e81e5883/packages/documentsearch/src/searchmodel.ts#L299-L317

https://github.com/jupyterlab/jupyterlab/blob/edfbea4f9c556875882dfbe71bf77d31e81e5883/packages/documentsearch/src/providers/genericsearchprovider.ts#L287-L288

and during restart we loose the highlight.

**Comment by krassowski** [comment] 2023-02-12 16:22
I think we should avoid restarting query naively on every update if possible.

I am not sure if `_documentHasChanged` flag was meant to be a performance optimisation or prevent jumping around. It looks like this was added in https://github.com/jupyterlab/jupyterlab/pull/11689 (CC @fcollonval, @afshin for thoughts).

**Comment by fcollonval** [comment] 2023-02-15 15:46
Thanks for the deep analysis

> I think we should avoid restarting query naively on every update if possible.

If I recall correctly, this was the attempt with:

https://github.com/jupyterlab/jupyterlab/blob/5c6ccf8eff542d421c6f59e35e88559a5b924d61/packages/cells/src/searchprovider.ts#L326

But as your analysis points out, they are other events like selection changed that are preventing that optimization.

> I am not sure if `_documentHasChanged` flag was meant to be a performance optimisation or prevent jumping around. It looks like this was added in #11689 (CC @fcollonval, @afshin for thoughts).

I don't recall exactly. But I would say to prevent jumping around as I did not spend much time on optimizing the search.

**Comment by fcollonval** [comment] 2023-02-27 07:53
Related to this - replacing multiple words requires more clicks than needed:

![replace-not-fluid](https://user-images.githubusercontent.com/8435071/221505218-a3d370c3-3946-4faf-b93e-b140a05fb54a.gif)

In the above screencast, the first match is replaced by a click on the _Replace_ button. But then although the second match is highlighted as current, I needed to click twice on the _Replace_ button to get it replace.

**Comment by JasonWeill** [comment] 2024-02-26 22:00
Are you still seeing this? I tried to reproduce this with tip-of-`main` in JupyterLab and I couldn't reproduce the behavior that @fcollonval and @krassowski found. I agree that rerunning the whole query is suboptimal, but considering the complexity of extensions like Jupyter Collaboration (RTC), a lot of things could cause a notebook's content to change.

**Comment by JasonWeill** [comment] 2024-03-01 18:57
I am seeing something superficially similar with the changes in #15881, where after cycling through the cell, I see no highlights until I click "find next" or "replace". I'm not sure whether it's the same issue as what you saw above.

**Comment by JasonWeill** [comment] 2024-04-24 21:20
This is now fixed by #15881.

**Closed** 2024-04-25 17:39 UTC
Labels: bug, tag:Search and Replace, tag:Regression
