### ISSUE TITLE
Menu entries are not highlighted on mouse over

### ISSUE THREAD

**Issue by timhoffm** [jupyterlab/jupyterlab#5509] opened 2018-10-17 20:36 UTC
The menu entries are not highlighted anymore when the mouse hovers over them:

**Actual Behavior**
![grafik](https://user-images.githubusercontent.com/2836374/47114246-9779d100-d25b-11e8-9ca7-f50e7c9f411d.png)

**Desired Behavor**
![grafik](https://user-images.githubusercontent.com/2836374/47114443-1838cd00-d25c-11e8-95cc-75c0e721dd91.png)

This is due to #2737, which changed the background of `.p-MenuBar-item.p-mod-active` from `var(--jp-layout-color2)` to `var(--jp-layout-color1)`.

@cameronoelsen I'm unclear if this was an intentional change, but I think that active elements should give a visual feedback when the mouse moves over them.

**Comment by jasongrout** [comment] 2018-11-13 00:36
CC @tgeorgeux

**Comment by jasongrout** [comment] 2018-11-13 00:46
I can confirm that top-level menus are not highlighted in jlab 0.35.4 on hover.

**Comment by tgeorgeux** [comment] 2018-11-14 23:04
@timhoffm You are absolutely correct, I know the menus have been working since that PR was released so it may have broken somewhere else along the line. We're currently working on a new UI package, at which point it should be fixed, but it seems simple enough to swap back in the correct colors in the mean time.

**Closed** 2018-11-16 02:54 UTC
Labels: good first issue, help wanted, tag:Design and UX, type:Bug
