### ISSUE TITLE
osx terminal bug on pipe "|"

### ISSUE THREAD

**Issue by gnzsnz** [jupyterlab/jupyterlab#16557] opened 2024-07-08 10:10 UTC
## Description

on osx terminal does not support pipe character "|", i tested this on firefox/ubuntu and is working fine, but on firefox/safari osx "|" "#" "[" does not work on terminal

## Reproduce

1. Go to osx firefox/safari
2. Click on --> open new termial
4. type "|" or "[" of "#" 
5. See error --> "(arg: 7)"

## Expected behavior

to be able to use special characters "|" "#" "[" 

## Context

- Operating System and version: osx sonoma
- Browser and version: firefox 127.02/safari 17.5
- JupyterLab version: 4.2.2

**Comment by JasonWeill** [comment] 2024-07-08 21:40
@gnzsnz Thank you for opening this bug! Which national type of keyboard are you using (US, French, etc)? We sometimes see bugs where the JupyterLab terminal does not parse characters correctly on non-QWERTY keyboards; for example, see #11257 and #11058.

**Comment by gnzsnz** [comment] 2024-07-09 09:34
Thanks for looking into this.

I'm using swiss French keyboard map.


Regards

**Comment by JasonWeill** [comment] 2024-07-09 16:10
@gnzsnz Thanks! This looks like a duplicate of #11257, so let's continue the conversation there. I appreciate your contribution.

**Closed by JasonWeill** 2024-07-09 16:10 UTC
Labels: bug, status:Duplicate, status:Needs Triage
