### ISSUE TITLE
How do I change terminal from powershell to git bash or cmd?

### ISSUE THREAD

**Issue by ds19991999** [jupyterlab/jupyterlab#7154] opened 2019-09-05 03:47 UTC
# How do I change terminal from powershell to git bash or cmd?
![20190905113345](https://user-images.githubusercontent.com/33677811/64310458-ae8bf380-cfd2-11e9-8eb3-19b37d7ca146.png)

## Description

I want to change terminal from PS to git bash, what should I do?

## Environment
```
C:\Windows\system32>jupyter --version
jupyter core     : 4.5.0
jupyter-notebook : 6.0.1
qtconsole        : not installed
ipython          : 7.8.0
ipykernel        : 5.1.2
jupyter client   : 5.3.1
jupyter lab      : 1.1.1
nbconvert        : 5.6.0
ipywidgets       : not installed
nbformat         : 4.4.0
traitlets        : 4.3.2

C:\Windows\system32>jupyter lab --version
1.1.1

OS:Windows 10 Pro
```

**Comment by blink1073** [comment] 2019-09-05 09:08
Hi @ds19991999, this article is a good summary: https://medium.com/@konpat/using-git-bash-in-jupyter-noteobok-on-windows-c88d2c3c7b07. 

If you'd like to contribute, adding some instructions to https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/user/terminal.rst would be most appreciated!

**Comment by ds19991999** [comment] 2019-09-05 09:49
> Hi @ds19991999, this article is a good summary: https://medium.com/@konpat/using-git-bash-in-jupyter-noteobok-on-windows-c88d2c3c7b07.
> 
> If you'd like to contribute, adding some instructions to https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/user/terminal.rst would be most appreciated!

It works, thank you!

**Comment by ds19991999** [comment] 2019-09-05 10:11
It seems that git bash has some bug ......

![bash](https://user-images.githubusercontent.com/33677811/64332511-49062a00-d007-11e9-8267-d3f4e01c2e57.gif)

**Comment by blink1073** [comment] 2019-09-05 15:33
This is a known bug, but I'm not sure exactly what the root cause is: https://github.com/jupyter/terminado/issues/45

**Comment by blink1073** [comment] 2019-09-05 15:34
We are tracking that bug on JupyterLab in https://github.com/jupyterlab/jupyterlab/issues/4060

**Comment by dhirschfeld** [comment] 2019-09-05 22:53
You can also set the `SHELL` env var which the notebook will use:
https://github.com/jupyter/notebook/blob/d145301b5583366fc0c5e938ded80f07a0bc1bbf/notebook/terminal/__init__.py#L21-L23

**Comment by jasongrout** [comment] 2019-09-28 06:24
Closing as resolved. Thanks everyone!

**Closed by jasongrout** 2019-09-28 06:24 UTC
