### ISSUE TITLE
Unrendered last cell and warning in the search function (3.1.0b1)

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10578] opened 2021-07-08 11:44 UTC
## Description

1. I saw an unrendered cell appear at the end of the notebook when working in last or penultimate cell
2. I noticed that the search bar shows a very verbose warning message saying the document is still loading (which indicates a loading error); this warning is stuck and does not go away after many minute since

![Screenshot from 2021-07-08 12-37-00](https://user-images.githubusercontent.com/5832902/124915561-97145c00-dfe9-11eb-95ab-e2fc7475a7b5.png)

There are no logs in developer console.

## Reproduce

TBD

## Expected behavior

- User should never see un-rendered cell.
- User should not see the "document is still loading warning" get stuck

## Context

Previous similar issue reported in #10435 and deemed fixed with #10505 (which certainly improved things).

CC @echarles @goanpeca 

- Browser and version: Chrome 91
- JupyterLab version: 3.1.0b1

**Comment by echarles** [comment] 2021-07-08 11:53
> I saw an unrendered cell appear at the end of the notebook when working in last or penultimate cell

Thx for reporting @krassowski. Can you detail a little bit the scenario driving to that issue? Are you seeing a un-rendered cell before working in the last cell?

**Comment by krassowski** [comment] 2021-07-08 12:02
I will fill in the details once I find a way to reproduce.

**Comment by krassowski** [comment] 2021-07-08 13:40
I encountered more suspicious behaviour related to cell rendering. Let's start by creating some cells:

![adding-cells-causes-scroll](https://user-images.githubusercontent.com/5832902/124930801-8b309600-dff9-11eb-9cca-664ae126d757.gif)

- starting with cell 22 the notebook no longer:
  - auto focuses the newly created cell
  - auto-scrolls to the new cell
- edge navigation is broken as reported in #10434
- pressing <kbd>Shift</kbd> + <kbd>Enter</kbd> still creates a new cell but also scroll upwards (why?) which is very strange

Now, I delete the empty cells I created and follow to add new cells with <kbd>Shift</kbd> + <kbd>Enter</kbd> again:

![repro-3](https://user-images.githubusercontent.com/5832902/124931350-08f4a180-dffa-11eb-8118-ebe63ffffe8a.gif)

this causes one of the cells to become unrendered. We can recover it by cut-paste operation:

![can recover](https://user-images.githubusercontent.com/5832902/124931506-2fb2d800-dffa-11eb-9e4d-4b17bf454468.gif)

I also encountered it in an earlier trial without the extra step of removing cells I think:

![shift-enter-bheaviour](https://user-images.githubusercontent.com/5832902/124930516-4f95cc00-dff9-11eb-8b9c-2b97535b8a1a.gif)

**Comment by echarles** [comment] 2021-07-08 13:48
@krassowski I will look into the detailed report. You have at hand the scenario that fails, so if you could apply them on jupyterlab 2.3, this would help me to nail down the origin. Did we have some of those issue in 2.3 and didn't see them, or is it on master?

**Comment by krassowski** [comment] 2021-07-08 13:51
I also cannot focus one of the cells; I deleted other cells but this one remained and is inaccessible:

![cannot-focus](https://user-images.githubusercontent.com/5832902/124932300-deefaf00-dffa-11eb-9e04-9ad6c2aa31be.gif)

More screencast:

![more-recording](https://user-images.githubusercontent.com/5832902/124932825-4ad21780-dffb-11eb-8e20-5900349e6357.gif)

I will have a look at 2.3, but I did not use it earlier (other than testing on binder).

**Comment by krassowski** [comment] 2021-07-08 13:52
There might be an interaction with undo function as well.

**Comment by echarles** [comment] 2021-07-08 14:27
Did a few test on master (2.3 seems to behave the same) and I would say there is a special case of the last cell (there seems to be a explicit scrolling somewhere). Will look at fixes tomorrow.

**Comment by echarles** [comment] 2021-07-11 08:41
@krassowski I have opened a fix in https://github.com/jupyterlab/jupyterlab/pull/10602. The reported issue are solved, and I have not been able to reproduce a unrendered cell. However, please try out the fix, you may have more ideas to break it 👍

**Comment by blink1073** [comment] 2021-07-12 11:29
Fixed by https://github.com/jupyterlab/jupyterlab/pull/10602

**Closed by blink1073** 2021-07-12 11:29 UTC
Labels: bug
