### ISSUE TITLE
Right Click -> Open Folder -> Right Click -> Open Folder -> 404

### ISSUE THREAD

**Issue by tak-matroid** [jupyterlab/jupyterlab#4975] opened 2018-07-26 18:48 UTC
If you right click on a folder (let's say it's called `workspace`), and choose Open, then it will work for the first time, but then if you right click on a subdirectory (let's say it's called `python`), and choose Open, you will start to see mysterious errors, saying:
```
Server Connection Error
Invalid response: 404 Not Found
```

Looking at the logs of Jupyter Notebook, this is what I found:
```
[W 18:43:58.492 LabApp] 404 GET /api/contents/workspace/workspace/python?content=......
```

See the problem here? `workspace` shows up twice  in the URL.

**Comment by jandrewtorres** [comment] 2018-07-27 02:09
Duplicate of #4913

**Closed** 2019-06-21 05:40 UTC
