### ISSUE TITLE
Can't shutdown kernel from the "Running" tab

### ISSUE THREAD

**Issue by aavanian** [jupyterlab/jupyterlab#4551] opened 2018-05-11 01:58 UTC
Clicking the "SHUTDOWN" button doesn't stop the kernel.
Using "Close and shutdown notebook" works.

The console shows this when clicking the "SHUTDOWN" button:
![image](https://user-images.githubusercontent.com/13487305/39902598-744ad24c-5501-11e8-840d-2309582cf509.png)

Version and extensions:
```
JupyterLab v0.32.0
Known labextensions:
   app dir: C:\Users\alexandre.avanian\AppData\Local\Continuum\Miniconda3\share\jupyter\lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.35.0 enabled  ok
@pyviz/jupyterlab_holoviews
        @pyviz/jupyterlab_holoviews v0.5.1 enabled  ok
jupyterlab-toc
        jupyterlab-toc v0.2.0 enabled  ok
jupyterlab_bokeh
        jupyterlab_bokeh v0.5.0 enabled  ok
ipykernel                 4.8.2
```

**Comment by jasongrout** [comment] 2018-05-11 16:46
Can you try in incognito/Private mode with no other JupyterLab extensions loaded, to try to narrow down the problem? If that works, can you try enabling your extensions one at a time to see if it is one of the extensions?

**Comment by jasongrout** [comment] 2018-05-11 16:47
(Just to confirm, the shutdown button works fine for me on JupyterLab 0.32.1)

Can you also upgrade to JupyterLab 0.32.1 and check with that?

**Comment by aavanian** [comment] 2018-05-12 10:25
Another precision: that's on windows 10 and chrome. Even with incognito window, all jupyterlab extensions disabled, updated to version 0.32.1 and rebuilt, same issue.

On OSX and chrome, jupyterlab 0.32.1 and lab extensions enabled, it works.

**Comment by souw** [comment] 2018-05-20 13:19
Having the identical issue here, also on windows 10 and chrome

**Comment by jasongrout** [comment] 2018-05-21 15:17
Does it work on firefox on windows 10?

**Comment by aavanian** [comment] 2018-05-22 01:29
Neither. Clicking the kernel or the shutdown button shows a `TypeError: e is null` in the console.

**Comment by blink1073** [comment] 2018-08-06 12:09
I just tried on Windows 10 with JLab 0.33.6 and Chrome 68 and was not able to reproduce.

**Comment by dclong** [comment] 2018-08-09 14:17
It seems that this issue has been fixed in JLab 0.33.8. I don't see it any more.

**Comment by blink1073** [comment] 2018-08-09 14:19
Fixed by https://github.com/jupyterlab/jupyterlab/pull/5067 most likely.

**Comment by blink1073** [comment] 2018-08-13 09:38
Closing this one, please ping back anyone if you're still seeing this in JLab 0.33.10 or newer.

**Closed by blink1073** 2018-08-13 09:38 UTC

**Comment by aavanian** [comment] 2018-08-13 11:05
I confirm it doesn't happen anymore with 0.33.8
