### ISSUE TITLE
Modify comment shortcut (cmd + /)

### ISSUE THREAD

**Issue by JacoGasp** [jupyterlab/jupyterlab#5164] opened 2018-08-20 13:59 UTC
Hello,
I'm using my mac laptop with an italian keyboard where '/' and '#' are not "primary" symbols.
This means that to achieve those symbols I need to press shift+7 for /, and option+à to have #.

In this way JupyterLab doesn't not recognize the proper shortcut to comment lines (i.e. cmd+shift+7, that in addition is a Safari reserved shortcut).

Looking at the keyboard shortcut settings there's no property to override the comment lines command.

Is there any workaround?
Thanks

**Comment by blink1073** [comment] 2018-08-21 08:05
Hi @JacoGasp, unfortunately that shortcut is [hardcoded](https://github.com/jupyterlab/jupyterlab/blob/156a569cae094edebfbd7a4a7a18aeccbeec1705/packages/codemirror/src/factory.ts#L24) and cannot yet be configured.

**Comment by JacoGasp** [comment] 2018-08-21 13:56
Hey @blink1073, thanks for reply. 
Ouh, this is sad... it’s a such too important command to not having it!

Can I change that line without screwing everything up?

**Comment by blink1073** [comment] 2018-08-21 14:40
Unfortunately, it would.  We need to surface extra keys as a CodeMirror setting.

**Comment by JacoGasp** [comment] 2018-08-21 16:33
Ok, got it. Thanks you tagged the issue :) 
I stay tuned for updates!

**Comment by LarsHill** [comment] 2019-07-02 13:40
Are there any updates related to this issue? I use a German keyboard and encounter the same problem. I would love to bind commenting to cmd+#, but there is no option to do so.

**Comment by martinvoigt** [comment] 2019-12-02 09:14
@blink1073 Any updates on this?
For me, this is the single most annoying missing thing in JupyterLab when using a non-English keyboard layout...

**Comment by blink1073** [comment] 2019-12-02 21:55
No updates unfortunately.  I've added the help wanted tag.

**Comment by jasongrout** [comment] 2020-05-19 12:02
This is a duplicate of #4778. Let's consolidate with the discussion on that earlier issue.

**Closed by jasongrout** 2020-05-19 12:02 UTC
Labels: help wanted, pkg:codemirror, tag:Feature Parity, type:Bug
