### ISSUE TITLE
Shutting down a closed notebook kernel reopens the notebook.

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#5084] opened 2018-08-09 17:40 UTC
This is a weird one:
![notebook-shutdown](https://user-images.githubusercontent.com/5728311/43915603-103b14aa-9bc0-11e8-8958-f7f8a030b649.gif)

**Comment by jasongrout** [comment] 2018-08-09 17:58
This is fixed in #5067. This is a duplicate of #5065.

**Closed** 2018-08-09 17:59 UTC
Labels: pkg:notebook, pkg:running, type:Bug
