### ISSUE TITLE
How to change the jupyterlab favicon.ico?

### ISSUE THREAD

**Issue by pumpkiiinnn** [jupyterlab/jupyterlab#15682] opened 2024-01-23 07:46 UTC
hi,i want change jupyterlab favicon.ico,But I don't know how to do it🥺

**Comment by krassowski** [comment] 2024-01-23 12:32
Let's discuss in https://github.com/jupyterlab/jupyterlab/issues/2405

**Comment by JasonWeill** [comment] 2024-01-23 17:47
Closing as duplicate of #2405.

**Closed by JasonWeill** 2024-01-23 17:47 UTC
Labels: bug, status:Duplicate, status:Needs Triage
