### ISSUE TITLE
HTML inline style not shown in trusted notebook's markdown cell

### ISSUE THREAD

**Issue by kllp** [jupyterlab/jupyterlab#11473] opened 2021-11-16 10:24 UTC
## Reproduce
- Open jupyterlab v3.2.3, create a new notebook and add a markdown cell:
```html
<span style="font-size:42px">Irrelavant text.</span>
```
- The style does not apply
https://stackoverflow.com/questions/68815487/html-inline-style-not-applying-in-jupyter-notebook-cells-anymore
## Expected behavior
html should be rendered correctly just like in latest jupyter notebook v6.4.5

**Comment by krassowski** [comment] 2021-11-16 10:35
Thank you for reporting, this is indeed a regression. It worked well in version 3.2.1 and stopped working in 3.2.2. We need to start testing rendering of styled elements in Markdown in the visual regression testing.

**Comment by meeseeksmachine** [comment] 2021-11-19 17:36
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/style-attributes-in-markdown-cells/11761/2

**Comment by drewyoungren** [comment] 2021-11-20 17:10
The same effect can be seen in the regular markdown previewer starting with 3.2.2 as well.

![image](https://user-images.githubusercontent.com/19934878/142734977-18b9ca6e-ccbd-4f2c-a279-995696242465.png)

**Comment by krassowski** [comment] 2021-11-20 18:47
This could be because of an upstream bug in sanitize-html: https://github.com/apostrophecms/sanitize-html/issues/510

**Comment by krassowski** [comment] 2021-11-20 18:55
That bug was already fixed in `sanitize-html` 2.5.3 [by removing `klona`](https://github.com/apostrophecms/sanitize-html/pull/511). Now, we did not have any update of `sanitize-html` recently but an update of `klona` broke this for us, so we need to pin `klona` to `2.0.4` or upgrade `sanitize-html` to `2.5.3`. This happened in the [3.2.2 release indeed](https://github.com/jupyterlab/jupyterlab/blame/4852e50b431a491b154a69acbf95b948e69e4d89/jupyterlab/staging/yarn.lock#L4617-#L4619).

**Closed** 2021-11-22 08:24 UTC
Labels: bug
