### ISSUE TITLE
It cannot show folders with name "__pycache__" and files with suffix .so

### ISSUE THREAD

**Issue by xigua88-66** [jupyterlab/jupyterlab#12906] opened 2022-08-04 02:11 UTC
## Description
1. When I try to delete a folder in the working directory of jupyter, an exception of "not empty" is reported. I use the terminal tool to view the directory and find that there is a folder named "__pycache__" in the directory, but there is no It is displayed on the jupyter page.
![image](https://user-images.githubusercontent.com/54090607/182747753-fc8db848-8a8a-4800-8b00-127e235936ce.png)

2. When I uploaded a file with a suffix of .so in the jupyter working directory, the page did not display my file. But when I view using terminal command line, there is this file in the directory.
![image](https://user-images.githubusercontent.com/54090607/182747932-c7a6ef4d-cc3d-400e-8a92-11d4714e1ff0.png)

**Comment by krassowski** [comment] 2022-08-04 17:27
The `jupyter-server` contents manager by default hides a number of files and directories which are configurable with `ContentsManager.hide_globs` traitlet, which defaults to:

```python
["__pycache__", "*.pyc", "*.pyo", ".DS_Store", "*.so", "*.dylib", "*~",]
```

You can learn more about configuration of server in the [jupyter-server documentation](https://jupyter-server.readthedocs.io/en/latest/users/configuration.html).

**Comment by jweill-aws** [comment] 2022-08-04 17:43
Thank you for your issue! This behavior is by design, and can be modified as @krassowski says above, so I'm going to close it.

**Closed by jweill-aws** 2022-08-04 17:43 UTC
Labels: bug, status:Needs Triage
