### ISSUE TITLE
When will the latest version support video playback?

### ISSUE THREAD

**Issue by iotctech** [jupyterlab/jupyterlab#9336] opened 2020-11-15 02:50 UTC
I have seen [**jupyterlab-mp4**](https://github.com/jupyterlab/jupyterlab-mp4) extension in the older vision, but the extension has never been updated. I need to play video in jupyterlab, It's there have any good suggestions? thx

**Comment by jtpio** [comment] 2020-11-16 11:45
Thank @iotctech. 

This is more of an issue with the `jupyterlab-mp4` extension itself. The fix would be to update its dependencies to target the latest version and make sure breaking changes (if any) are addressed.

Would you mind moving the conversation to https://github.com/jupyterlab/jupyterlab-mp4/issues/6?

**Comment by jasongrout** [comment] 2020-11-16 18:06
I think it would be great if we supported video files in core as well. Feel free to make a PR to JupyterLab to move that code to JupyterLab itself. If I were doing it, I would basically mirror the image rendering support in https://github.com/jupyterlab/jupyterlab/blob/master/packages/rendermime/src/factories.ts, https://github.com/jupyterlab/jupyterlab/blob/master/packages/rendermime/src/renderers.ts, and https://github.com/jupyterlab/jupyterlab/blob/master/packages/rendermime/src/widgets.ts

**Comment by jtpio** [comment] 2020-11-16 18:17
> I think it would be great if we supported video files in core as well.

That sounds like a good option too.

Opened https://github.com/jupyterlab/jupyterlab-mp4/issues/7 for visibility.

**Comment by iotctech** [comment] 2020-11-17 02:08
> > I think it would be great if we supported video files in core as well.
> 
> That sounds like a good option too.
> 
> Opened [jupyterlab/jupyterlab-mp4#7](https://github.com/jupyterlab/jupyterlab-mp4/issues/7) for visibility.

I also think it's a great idea to support video file in jp core, and it will bring us great convenience in the deep learning field. 

The `jupyterlab-mp4` project has not been maintained for a long time, There is no hope to look forward to their update.

Thanks again for your attention.

**Comment by songkevinc** [comment] 2021-05-03 20:41
Any updates on this? I think it would be great to have this extension in the core. I just updated to jupyter3 and am sort of regretting it now that I can't visualize videos as easily as before, ha.

**Comment by jtpio** [comment] 2021-05-04 11:48
@songkevinc I think this is still open for anyone to pick up and submit a PR to JupyterLab to add the extension.

**Comment by songkevinc** [comment] 2021-05-04 13:17
@jtpio Sounds good. Well, I've never built a jupyterlab extension before, but maybe I'll give it a shot, ha.

**Comment by songkevinc** [comment] 2021-12-17 18:39
Hello, so I tested this with Jupyterlab  version `3.25.0` but all I had to change was the `rendermime-interfaces` dependency version to `3.0.0` in the `package.json`:
 ```"dependencies": {
    "@jupyterlab/rendermime-interfaces": "^3.0.0",
    "@phosphor/widgets": "^1.5.0"```

I'm not sure what the best way to accommodate old jupyterlab version users as well as accommodate users using jupyterlab version 3. Would appreciate any guidance to getting this change merged.

**Comment by songkevinc** [comment] 2021-12-17 19:45
Sorry, I must have messed something up, but I actually had to change the `@phosphor` dependency to `@lumino`, add the appropriate dependencies and added `skipLibCheck: true` in the `tsconfig` file to be able to run `npm build` correctly. My forked repo is [here](https://github.com/songkevinc/jupyterlab-mp4). I'll create a PR to get it merged to `jupyterlab/jupyterlab-mp4`

**Comment by jasongrout** [comment] 2021-12-22 09:26
Adding as a good first issue - I think you could still follow the suggestions in https://github.com/jupyterlab/jupyterlab/issues/9336#issuecomment-728231010 to add a video renderer that basically followed the pattern already in the code for the image renderer.

**Comment by vidartf** [comment] 2022-06-17 16:26
Closing this as a duplicate of https://github.com/jupyterlab/jupyterlab/issues/3860

**Closed by vidartf** 2022-06-17 16:26 UTC
Labels: good first issue
