### ISSUE TITLE
Command 'jupyter notebook' opens Jupyter lab

### ISSUE THREAD

**Issue by mjspeck** [jupyterlab/jupyterlab#3934] opened 2018-02-21 15:15 UTC
After updating Jupyter lab, the jupyter notebook command now opens Jupyter lab.

**Comment by blink1073** [comment] 2018-02-21 16:46
Hi @mjspeck, if you type `jupyter-notebook` in a terminal, it takes you to the `/lab` page?

**Comment by mjspeck** [comment] 2018-02-21 22:52
Correct.

**Comment by mjspeck** [comment] 2018-02-22 03:26
```
#!/Users/mattspeck/anaconda3/bin/python

# -*- coding: utf-8 -*-
import re
import sys

from notebook.notebookapp import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

**Comment by mjspeck** [comment] 2018-02-22 13:34
Oddly, this seemed to fix the issue:

```
$ conda upgrade jupyterlab
Solving environment: done

## Package Plan ##

  environment location: /Users/mattspeck/anaconda3

  added / updated specs: 
    - jupyterlab


The following packages will be DOWNGRADED:

    jupyterlab: 0.31.8-py36_1 conda-forge --> 0.31.8-py36_0

Proceed ([y]/n)? y
```

**Comment by blink1073** [comment] 2018-02-22 15:02
That is odd.  Closing since we don't have a way to reproduce and you're back on track.  Cheers!

**Closed by blink1073** 2018-02-22 15:02 UTC

**Comment by sradomski** [comment] 2018-03-05 13:48
Same issue here, MacOSX latest CLI installer (as of 2h ago) into custom directory.

**Comment by blink1073** [comment] 2018-03-05 14:22
This is now fixed in `0.31.11.`

**Comment by yunqu** [comment] 2018-07-16 21:13
We used to have `jupyter notebook` running in the background, then in URL we can just change `/tree?` to `/lab` in order to change from jupyter notebook to jupyter lab.

Basically, jupyter lab is enabled for jupyter notebook automatically.

However, it seems now I have to manually start jupyter lab; starting jupyter notebook does not give you jupyter lab anymore.

Just curious about the plan: would jupyter lab stay separate with jupyter notebook, or are they supposed to be both provided by a single command?

**Comment by blink1073** [comment] 2018-07-17 02:04
Hi @yunqu, what you are trying to do should still work, if `jupyterlab` is installed as a server extension.  JupyterLab uses the same server as the classic notebook.   `jupyter serverextension list` will tell you whether `jupyterlab` is enabled, you can use `jupyter serverextension enable jupyterlab` if it is not.  If you run the command `jupyter lab` directly, it will manually use the JupyterLab server extension even if it isn't enabled.  Hope that helps.

**Comment by yunqu** [comment] 2018-07-17 22:17
@blink1073  Thanks! It indeed still work.
