### ISSUE TITLE
Workspace area in Launcher or Right Hand Sidebar

### ISSUE THREAD

**Issue by psychemedia** [jupyterlab/jupyterlab#12547] opened 2022-05-09 10:34 UTC
Workspaces don't often seem to get mentioned much in the context of JupyterLab, but they can provide a really useful way for helping manage different projects.

It's not really obvious how to create or open new workspaces, not how to keep track of multiple workspaces.

Could a "Workspace" area be added to the launcher to make it easier to keep track of multiple workspaces, and make it easier to launch into them? Or would right hand side bar Workspace manager palette be more appropriate (eg eg launcher items themselves are customisable within a particular workspace)?

**Comment by psychemedia** [comment] 2022-05-09 10:43
Ah, I see there is already https://github.com/jupyterlab/jupyterlab/issues/6944

I also note a https://stackoverflow.com/questions/52656747/how-can-i-list-all-existing-workspaces-in-jupyterlab for listing available workspaces.

**Comment by jweill-aws** [comment] 2022-05-12 17:41
Thank you for filing this! Resolving as a dupe of #6944.

**Closed by jweill-aws** 2022-05-12 17:41 UTC
Labels: status:Duplicate, enhancement, status:Needs Triage
