### ISSUE TITLE
TypeError: argument of type 'float' is not iterable

### ISSUE THREAD

**Issue by julianofischer** [jupyterlab/jupyterlab#8339] opened 2020-05-01 02:42 UTC
## Description and Reproduce

The following error occurs:

    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-153-272ea6776028> in <module>
          1 aux = 0
          2 for index, row in df.iterrows():
    ----> 3     if ('- Vivo' in row['Track Name']):
          4         print(row['Track Name'])
    
    TypeError: argument of type 'float' is not iterable

when I try to run the following snippet:

    for index, row in df.iterrows():
        if ('- Vivo' in row['Track Name']):
            print(row['Track Name'])

the same occurs if I change the snippet to

    for index, row in df.iterrows():
        if ('/ Vivo' in row['Track Name']):
            print(row['Track Name'])

## Expected behavior

Filter the rows where the column "Track Name" contains " - Vivo"

## Context

- Operating System and version:
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
- Browser and version:
Versão 80.0.3987.122 (Versão oficial) 64 bits
- JupyterLab version:
Version 2.1.1
<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
$PATH:
	/home/juliano/.local/bin
	/home/juliano/scripts
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/snap/bin

sys.path:
	/home/juliano/.local/bin
	/usr/lib/python38.zip
	/usr/lib/python3.8
	/usr/lib/python3.8/lib-dynload
	/home/juliano/.local/lib/python3.8/site-packages
	/usr/local/lib/python3.8/dist-packages
	/usr/lib/python3/dist-packages

sys.executable:
	/usr/bin/python3

sys.version:
	3.8.2 (default, Mar 13 2020, 10:14:16) 
	[GCC 9.3.0]

platform.platform():
	Linux-5.4.0-28-generic-x86_64-with-glibc2.29

which -a jupyter:
	/home/juliano/.local/bin/jupyter

pip list:
	Package                 Version       
	----------------------- --------------
	AnyQt                   0.0.10        
	appdirs                 1.4.3         
	apsw                    3.28.0.post1  
	apturl                  0.5.2         
	asn1crypto              0.24.0        
	attrs                   19.3.0        
	backcall                0.1.0         
	baycomp                 1.0.2         
	bcrypt                  3.1.7         
	beautifulsoup4          4.8.2         
	bleach                  3.1.4         
	blinker                 1.4           
	Bottleneck              1.3.2         
	Brlapi                  0.7.0         
	CacheControl            0.12.6        
	certifi                 2019.11.28    
	chardet                 3.0.4         
	click                   7.1.2         
	command-not-found       0.3           
	commonmark              0.9.1         
	cryptography            2.8           
	css-parser              1.0.4         
	cssselect               1.1.0         
	cssutils                1.0.2         
	cupshelpers             1.0           
	cycler                  0.10.0        
	dbus-python             1.2.16        
	decorator               4.4.2         
	defer                   1.0.6         
	defusedxml              0.6.0         
	devscripts              2.20.2ubuntu2 
	dictdiffer              0.8.1         
	distlib                 0.3.0         
	distro                  1.4.0         
	distro-info             0.23ubuntu1   
	dnspython               1.16.0        
	docutils                0.16          
	duplicity               0.8.12.0      
	entrypoints             0.3           
	et-xmlfile              1.0.1         
	fasteners               0.14.1        
	feedparser              5.2.1         
	filelock                3.0.12        
	future                  0.18.2        
	gpg                     1.13.1-unknown
	h11                     0.9.0         
	h2                      3.2.0         
	hpack                   3.0.0         
	hstspreload             2020.4.24     
	html2text               2020.1.16     
	html5-parser            0.4.9         
	html5lib                1.0.1         
	httplib2                0.14.0        
	httpx                   0.12.1        
	hyperframe              5.2.0         
	idna                    2.8           
	ifaddr                  0.1.6         
	importlib-metadata      1.5.0         
	ipykernel               5.2.1         
	ipython                 7.13.0        
	ipython-genutils        0.2.0         
	jdcal                   1.4.1         
	jedi                    0.17.0        
	Jinja2                  2.11.2        
	joblib                  0.14.1        
	json5                   0.9.4         
	jsonschema              3.2.0         
	jupyter-client          6.1.3         
	jupyter-core            4.6.3         
	jupyterlab              2.1.1         
	jupyterlab-server       1.1.1         
	kazam                   1.4.5         
	keyring                 18.0.1        
	keyrings.alt            3.4.0         
	kiwisolver              1.2.0         
	language-selector       0.1           
	launchpadlib            1.10.13       
	lazr.restfulclient      0.14.2        
	lazr.uri                1.0.3         
	llvmlite                0.32.0        
	lockfile                0.12.2        
	louis                   3.12.0        
	lxml                    4.5.0         
	macaroonbakery          1.3.1         
	Mako                    1.1.0         
	Markdown                3.1.1         
	MarkupSafe              1.1.0         
	matplotlib              3.2.1         
	mechanize               0.4.5         
	mistune                 0.8.4         
	monotonic               1.5           
	more-itertools          4.2.0         
	msgpack                 0.6.2         
	nbconvert               5.6.1         
	nbformat                5.0.6         
	netifaces               0.10.4        
	networkx                2.4           
	nltk                    3.5           
	nose                    1.3.7         
	notebook                6.0.3         
	numba                   0.49.0        
	numpy                   1.18.3        
	oauthlib                3.1.0         
	olefile                 0.46          
	openpyxl                3.0.3         
	openshot-qt             2.4.3         
	openTSNE                0.3.12        
	orange-canvas-core      0.1.12        
	orange-widget-base      4.5.0         
	Orange3                 3.25.0        
	Orange3-Associate       1.1.5         
	packaging               20.3          
	pandas                  1.0.3         
	pandocfilters           1.4.2         
	paramiko                2.6.0         
	parso                   0.7.0         
	pexpect                 4.6.0         
	pickleshare             0.7.5         
	Pillow                  7.0.0         
	pip                     20.0.2        
	prometheus-client       0.7.1         
	prompt-toolkit          3.0.5         
	protobuf                3.6.1         
	ptyprocess              0.6.0         
	pycairo                 1.16.2        
	pychm                   0.8.6         
	pycrypto                2.6.1         
	pycups                  1.9.73        
	Pygments                2.3.1         
	PyGObject               3.36.0        
	PyJWT                   1.7.1         
	pymacaroons             0.13.0        
	PyNaCl                  1.3.0         
	pynndescent             0.4.7         
	pyparsing               2.4.6         
	PyQt5                   5.14.1        
	pyqtgraph               0.10.0        
	PyQtWebEngine           5.14.0        
	pyRFC3339               1.1           
	pyrsistent              0.16.0        
	python-apt              2.0.0         
	python-dateutil         2.7.3         
	python-debian           0.1.36ubuntu1 
	python-distutils-extra  2.39          
	python-louvain          0.14          
	python-magic            0.4.16        
	pytz                    2019.3        
	pyxdg                   0.26          
	PyYAML                  5.3.1         
	pyzmq                   18.1.1        
	regex                   2019.8.19     
	reportlab               3.5.34        
	repoze.lru              0.7           
	requests                2.22.0        
	requests-unixsocket     0.2.0         
	rfc3986                 1.4.0         
	Routes                  2.4.1         
	scikit-learn            0.22.2.post1  
	scipy                   1.4.1         
	scour                   0.37          
	screen-resolution-extra 0.0.0         
	SecretStorage           2.3.1         
	Send2Trash              1.5.0         
	serverfiles             0.3.0         
	setuptools              45.2.0        
	simplejson              3.16.0        
	sip                     4.19.21       
	six                     1.14.0        
	sniffio                 1.1.0         
	soupsieve               1.9.5         
	system-service          0.3           
	systemd-python          234           
	terminado               0.8.3         
	testpath                0.4.4         
	tornado                 6.0.4         
	tqdm                    4.45.0        
	traitlets               4.3.3         
	ubuntu-advantage-tools  20.3          
	ubuntu-drivers-common   0.0.0         
	ufw                     0.36          
	unattended-upgrades     0.1           
	unidiff                 0.5.5         
	urllib3                 1.25.8        
	usb-creator             0.3.7         
	virtualenv              20.0.17       
	wadllib                 1.3.3         
	wcwidth                 0.1.9         
	webencodings            0.5.1         
	WebOb                   1.8.5         
	wheel                   0.34.2        
	xkit                    0.0.0         
	xlrd                    1.2.0         
	XlsxWriter              1.2.8         
	youtube-dl              2020.3.24     
	zeroconf                0.24.4        
	zipp                    1.0.0

</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>

W 19:38:41.080 LabApp] JupyterLab server extension not enabled, manually loading...
[I 19:38:41.661 LabApp] JupyterLab extension loaded from /home/juliano/.local/lib/python3.8/site-packages/jupyterlab
[I 19:38:41.661 LabApp] JupyterLab application directory is /home/juliano/.local/share/jupyter/lab
[I 19:38:41.663 LabApp] Serving notebooks from local directory: /home/juliano/PycharmProjects/getspotifycharts/charts
[I 19:38:41.663 LabApp] The Jupyter Notebook is running at:
[I 19:38:41.663 LabApp] http://localhost:8888/?token=a24b58e6baa5d24158340ebed66e9f12e7748e66e84fed75
[I 19:38:41.663 LabApp]  or http://127.0.0.1:8888/?token=a24b58e6baa5d24158340ebed66e9f12e7748e66e84fed75
[I 19:38:41.663 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 19:38:41.683 LabApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/juliano/.local/share/jupyter/runtime/nbserver-22701-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=a24b58e6baa5d24158340ebed66e9f12e7748e66e84fed75
     or http://127.0.0.1:8888/?token=a24b58e6baa5d24158340ebed66e9f12e7748e66e84fed75
[I 19:38:45.015 LabApp] Build is up to date
[I 19:38:46.741 LabApp] Kernel started: 4f9a6601-906b-4c6d-9fb2-3d1eac14ab30

</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>

Starting application in workspace: "/lab"
2vendors~main.3497bb7b5ef294ef439d.js:2 Starting WebSocket: ws://localhost:8888/api/kernels/4f9a6601-906b-4c6d-9fb2-3d1eac14ab30

</details>

**Comment by rahulpshah** [comment] 2020-05-01 20:53
Hi @julianofischer, it looks like the issue is with the underlying pandas code you are using. The row['Track Number'] probably contains NaN value causing the above issue. Please filter the dataframe you are using with null values and try running the code again.

**Comment by jasongrout** [comment] 2020-05-05 10:21
Closing as answered.

**Closed by jasongrout** 2020-05-05 10:21 UTC
