### ISSUE TITLE
Feedback for single-document/classic notebook mode in 3.0

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#9117] opened 2020-09-30 17:04 UTC
Let's use this issue to provide feedback about the new single document mode that is in JupyterLab 3.0.

**Comment by jtpio** [comment] 2020-09-30 17:12
Should we link to the existing issues?

Or copy-paste the comments here? (and optionally close the issue)

**Comment by meeseeksmachine** [comment] 2020-10-05 10:34
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyterlab-3-0-release-candidate-available/6248/2

**Comment by choldgraf** [comment] 2020-10-05 15:16
A few quick thoughts:

First - this is much-improved over the previous behavior, I really like it!

- Agree about the splash screen when opening new documents
- Is there a keyboard shortcut to trigger this? I couldn't find it...it would make it easier to open new documents without opening new windows, but still use single document mode.
- I found myself expecting to be able to "click" the title of the notebook to rename it. Instead I needed to go to file->rename.
- Is there documentation for how this mode could be customized in a *different* way from the "`lab/`" mode? I am wondering if the vision is for people to have `doc/`-specific extensions activated, layouts, etc...

Also I love the fact that you can specify this in the URL!

**Comment by jasongrout** [comment] 2020-10-05 15:20
> Is there a keyboard shortcut to trigger this? I couldn't find it...it would make it easier to open new documents without opening new windows, but still use single document mode.

Yes. It is listed in the View menu. (And it has been that same keyboard shortcut all along, so if you didn't know about it, perhaps we need to make it more discoverable)

> I found myself expecting to be able to "click" the title of the notebook to rename it. Instead I needed to go to file->rename.

Yes, someone else pointed this out as well. Agreed.

**Comment by choldgraf** [comment] 2020-10-05 15:23
Ah thanks for the pointer. In case it helps I'll explain my thought pattern: when I was looking for the keyboard shortcut for this, I looked in the "settings" menu, then "advanced settings" when I didn't find it. Then I found the "keyboard shortcuts" section of "advanced settings" and opened it. I `ctrl-f`ed for "single" as well as "document", and didn't find anything there that seemed to be for single-doc mode, and so I assumed there wasn't a shortcut for this.

**Comment by jasongrout** [comment] 2020-10-05 15:26
Ah, it's this shortcut:

```json
        {
            "command": "application:toggle-mode",
            "keys": [
                "Accel Shift D"
            ],
            "selector": "body"
        },
```

We should probably add help for that shortcut that indicates that the mode here is single-document mode.

**Comment by choldgraf** [comment] 2020-10-05 15:28
ah yes - that would definitely have helped find it. I assumed either "single" or "doc" would be in it :-)

**Comment by jeffyjefflabs** [comment] 2020-10-05 20:28
Nice improvements over 2.x so far.  I like that "Copy shareable link" gives you a `/doc/...` URL and especially that fixed doc URLs exist in the first place - that will useful at my workplace.

Definitely +1 on the click-to-rename request but also a couple minor things that haven't been mentioned:
 * When you double-click to open a new tab or navigate directly to a doc URL, it shows the Launcher for a split second between the splash screen and displaying the file you requested; would be nice to avoid that if possible.  You can see this happen in the demo gif on #9099, but seems like a separate thing from the rest of that issue.
 * Should the sidebars collapse automatically when you switch into single document mode?  I kind of think yes but can see arguments either way, and I'm seeing some inconsistent behavior so not sure what's intended.  For example if you use the toggle button then they stay expanded, but if you're in doc mode and double-click something in the file browser to open in a new browser tab, then sometimes they're collapsed in the new tab.  (I was also playing with workspaces so maybe there's some weird interplay going on.)

One "wish list" item - has there been any thought to an equivalent of the classic `/tree` page?  Currently `/doc` gives you a Launcher with a File Browser sidebar but potentially `/doc/tree` (currently 404) could be a more file-centric view.  I'm thinking of the business analysts where I work - they're used to `/tree` as their "home page" but also a lot of them are mostly running existing notebooks rather than writing new ones, so the Launcher takes up a disproportionate amount of space when something like a full-width File Browser might be more appealing.  I don't know how common this use case would be though.

**Comment by betatim** [comment] 2020-10-06 06:23
I'm lovin' it! and using [this demo](https://mybinder.org/v2/gist/jtpio/8d392846c2f3ee6fab38cdfab5a364ec/master?urlpath=/lab) to try it out.

When I click `File -> New -> Notebook` a new notebook is opened but it is in the same browser tab. This means I lose the one I already had open in that browser tab. When I double click a notebook in the file explorer it opens in a new tab. My expectation was that both would open in a new tab.

**Comment by joelostblom** [comment] 2020-10-07 19:46
Overall I really like having single document view more easily discoverable! I think the text takes up a bit too much space. What do you think about using more traditional icons for entering full screen / large view and exiting full screen / small view instead of the current slider/toggle? If you choose an icon that people are used to clicking on other sites (youtube, etc), then I think you don't need any text at all since the behavior of this icon is already recognized from elsewhere (together with a hover tooltip for clarification if needed) Some screenshot suggestions below:

What YouTube uses:

![image](https://user-images.githubusercontent.com/4560057/95379240-f9dd9900-0899-11eb-9864-ce92777364e9.png) ![image](https://user-images.githubusercontent.com/4560057/95379255-ff3ae380-0899-11eb-8382-9e7c36d273a2.png)

Two arrows:

![image](https://user-images.githubusercontent.com/4560057/95378717-280ea900-0899-11eb-82d2-9396e70c9490.png) ![image](https://user-images.githubusercontent.com/4560057/95378734-3066e400-0899-11eb-8e1d-dbd8374bbb29.png)

Four arrows:

![image](https://user-images.githubusercontent.com/4560057/95378917-7cb22400-0899-11eb-985b-b65cd0050b21.png) ![image](https://user-images.githubusercontent.com/4560057/95378989-9a7f8900-0899-11eb-8726-adebe81a8e37.png)



More elaborate:

![image](https://user-images.githubusercontent.com/4560057/95379088-bc790b80-0899-11eb-83db-c8267fa5c1b8.png) ![image](https://user-images.githubusercontent.com/4560057/95379113-c4d14680-0899-11eb-9cfd-44fbbd5a5865.png)

**Comment by jasongrout** [comment] 2020-10-07 20:17
Good thoughts about using icons. A *separate* feature I'd love to see is a fullscreen mode somewhere that full-screened the entire jlab interface, which would probably be a better fit for at least the top three icon sets.

See https://github.com/jupyterlab/jupyterlab/issues/8710

**Comment by choldgraf** [comment] 2020-10-08 18:16
I agree that icons for this would follow the visual style of JupyterLab more generally, and would help take up less screen real estate.

What about something like one / multiple docs icons:

single-doc mode:

![image](https://user-images.githubusercontent.com/1839645/95497767-bba6af00-0957-11eb-8b5c-c414dc62431c.png)

and 

multi-doc mode:

![image](https://user-images.githubusercontent.com/1839645/95497728-aaf63900-0957-11eb-882d-cb77b7d903ed.png)

**Comment by joelostblom** [comment] 2020-10-08 22:06
An icon with tabs could also work for "lab mode":

![image](https://user-images.githubusercontent.com/4560057/95502683-0aa41280-095f-11eb-8550-7c29a798da8b.png)

Although I would personally vote on an icon that is traditionally used for indicating that the media/window becomes larger. In terms of contrasting with full screen, I think for example two arrows for single document mode and four arrows for full screen could work. Or the "elaborate" icon I posted above for single document mode and the youtube icon for fullscreen. Just my thoughts.

**Comment by SylvainCorlay** [comment] 2020-10-26 22:07
Double-clicking on the tab handle to activate the single document mode may be another way.

**Comment by jasongrout** [comment] 2020-10-26 22:22
> Double-clicking on the tab handle to activate the single document mode may be another way.

Yes, though I think a lot of people expect double-clicking on a tab to trigger renaming, based on experience with spreadsheets, etc.

**Comment by jtpio** [comment] 2020-11-12 16:13
Posting here for visibility, since a couple of people have engaged in the conversation.

This (draft) PR moves the single document mode switch to the status bar: https://github.com/jupyterlab/jupyterlab/pull/9296

Feel free to try both versions (Binder links in the description), and share feedback on the PR directly.

**Comment by choldgraf** [comment] 2020-11-12 16:19
Here are two GIFs of each version so people can compare (I'd recommend putting these GIFs side-by-side in a more prominent place):

![](https://user-images.githubusercontent.com/591645/94660397-e5335b00-0305-11eb-8af4-df1c4985c3db.gif)

![](https://user-images.githubusercontent.com/591645/98399029-1f5cee80-2062-11eb-9531-ac1277017cd1.gif)

**Comment by choldgraf** [comment] 2020-11-12 16:21
I think that visually I like it more on the bottom, it feels less like an interruption of the page flow.

that said, this probably also makes it less discoverable so will be important to document and direct attention to it.

Longer-term, I guess the other question I have is whether this breaks from the mental model people should have about the status bar, since the bar will now be used to *do* things, not just report status.

**Comment by jtpio** [comment] 2020-11-12 16:25
>  the other question I have is whether this breaks from the mental model people should have about the status bar, since the bar will now be used to _do_ things, not just report status.

This is already the case with the terminals / kernels icons that open the running tab when clicked. And also the "Python 3 | Idle" indicator to select the kernel.

**Comment by choldgraf** [comment] 2020-11-12 16:27
@jtpio well maybe as one data point, I had no idea that those UI elements were clickable because I assumed it was all just "read-only" style status updates :-)

**Comment by jasongrout** [comment] 2020-11-12 16:29
> Here are two GIFs of each version so people can compare (I'd recommend putting these GIFs side-by-side in a more prominent place):

Can you make the status quo gif with 3.0rc7? It has significant improvements with the ux and feel of the switch at the top.

**Comment by choldgraf** [comment] 2020-11-12 16:37
@jasongrout I was just copy-pasting from GIFs that @jtpio had posted in other issues, I wasn't running it myself. If someone can give me a Binder link that'll create the proper environment I can quickly make a GIF of each one though

**Comment by jasongrout** [comment] 2020-11-12 16:39
Ah, thanks. Jeremy posted binder links in the original description above for 3.0rc7 and this PR.

**Comment by choldgraf** [comment] 2020-11-12 16:46
I just updated the GIF with one from the binder link @jtpio sent in that PR (dunno why my cursor is missing though). I'd suggest putting those GIFs in a prominent place so that people can properly compare (or even posting in the community forum if you want a wider audience than jupyterlab devs)

**Comment by jasongrout** [comment] 2020-11-12 17:08
I posted on Discourse at https://discourse.jupyter.org/t/seeking-feedback-jupyterlab-single-document-mode-switch-position/6715

**Comment by choldgraf** [comment] 2020-11-12 17:12
Nice! I made a little tweet about it :-) https://twitter.com/choldgraf/status/1326935838442332161

**Comment by choldgraf** [comment] 2020-11-12 17:14
A quick thought on the UI of the single-doc mode. Have folks explored how it looks if you set a max-width and centered the notebook in the middle of the page, similar to the classic notebook UI? I think that the fixed width and "looks like a notebook page" UI could be a nice addition and shout-out to the previous feel of the classic interface

**Comment by jasongrout** [comment] 2020-11-12 17:17
> Have folks explored how it looks if you set a max-width and centered the notebook in the middle of the page, similar to the classic notebook UI?

Yes, there has been discussion about it (thanks for another vote for it :), and indeed there is still a lot to iterate on in the 3.x series and for 4.0.

**Comment by choldgraf** [comment] 2020-11-12 17:18
@jasongrout if there's a better place for me to voice that opinion let me know where! I'm using this issue as a catch-all for all opinions about the single-doc mode :-)

**Comment by jasongrout** [comment] 2020-11-12 17:36
> @jasongrout if there's a better place for me to voice that opinion let me know where! I'm using this issue as a catch-all for all opinions about the single-doc mode :-)

This is the right place - it *is* a catch-all issue for opinions about single-doc mode. I'm glad you brought up your point here.

**Comment by jtpio** [comment] 2020-11-12 18:16
Thanks all!

The tweet and post on Discourse should help get more feedback on this :+1:

**Comment by betatim** [comment] 2020-11-13 06:58
👍  on fixed width for single doc mode. +0 for putting the toggle on the top right.

**Comment by manics** [comment] 2020-11-17 19:17
I've finally gotten round to trying the single document mode properly, and I really like it 😄 

I'm undecided on the toggle. I already knew what it did from reading the Discourse posts, but I'm not sure it'd be that obvious if I'd come straight to it, and it just feels a bit out of place in eiher location. I can see what you're trying to do though, is the idea of using a toggle modelled on another application? If so it might be useful to compare.

Given the choice between a toggle and icons such as https://github.com/jupyterlab/jupyterlab/issues/9117#issuecomment-705155573 and https://github.com/jupyterlab/jupyterlab/issues/9117#issuecomment-705740559 I think the icons are more intuitive.

**Comment by meeseeksmachine** [comment] 2020-11-19 19:36
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/seeking-feedback-jupyterlab-single-document-mode-switch-position/6715/14

**Comment by jtpio** [comment] 2020-11-23 17:49
Since a couple of people in this thread were suggesting using icons to toggle the single document mode, here is a PR that implements this idea: https://github.com/jupyterlab/jupyterlab/pull/9389

Posting the summary from the PR description here, with Binder links:

---
- Using the latest commit on master with the SDM switch in the status bar: https://mybinder.org/v2/gh/jupyterlab/jupyterlab/71a6d84164f04c982768669b4b01a172e05309c3?urlpath=lab-dev
- Using the PR with the Binder dev mode, with icons instead of a switch: https://mybinder.org/v2/gh/jtpio/jupyterlab/icons-sdm?urlpath=lab-dev

### Before (switch)

![sdm-switch-statusbar](https://user-images.githubusercontent.com/591645/98399029-1f5cee80-2062-11eb-9531-ac1277017cd1.gif)

### After (icons)

![sdm-icons-left](https://user-images.githubusercontent.com/591645/99863030-8c14d480-2b9c-11eb-98c2-f6a6fc1101cd.gif)

**Comment by jasongrout** [comment] 2021-01-06 00:50
https://github.com/jupyterlab/jupyterlab/issues/9559 notes that it is confusing to try to close a tab in the simple interface.

**Comment by kariharju** [comment] 2021-01-21 15:11
Hi,
One gripe, the automatic switch to Simple Interface -mode is quite confusing.
So when I resize the windows to small enough (not really clear when this happens) the mode is switched on. 
Going the other direction does not however switch the mode back off. 
So the logic is kind of a trap for "unsuspecting victims" to get locked to Simple Interface and having to manually turn it off :D 

I think this should be a conscious choice by the user or have a setting to enable/disable the automatic behavior.

**Comment by jtpio** [comment] 2021-01-21 15:17
Thanks @kariharju.

> So when I resize the windows to small enough (not really clear when this happens) the mode is switched on.

I think some of this logic is in: 

https://github.com/jupyterlab/jupyterlab/blob/871e5608f2944cf6d1ded9bc29cae9d45792108d/packages/application/src/lab.ts#L310-L319

(matching a specific media query)

**Comment by sc1f** [comment] 2021-04-13 15:42
Hi all,

I'm working on some automated screenshot tests for [Perspective](https://github.com/finos/perspective)'s Jupyterlab plugin, and I found this thread while I was looking for a way to reliably open single notebooks without dealing with the rest of the UI. I'm using the `/doc/...` URL, and I found a small bug that broke my assumption that the `doc` URL could open any document without taking into account the current workspace:

![jupyterlab_doc_url_redirect](https://user-images.githubusercontent.com/13220267/114577821-5acf9a80-9c4a-11eb-87da-6fe29157f398.gif)

I have two notebooks, `first` and `second`, and when I open a direct `doc` link to `second.ipynb` after opening `first.ipynb`, the URL redirects back to `first.ipynb` because that is the current notebook in the workspace. The same issue happens if I open `first.ipynb` after `second.ipynb`.

I am aware that adding `?reset` to the URL will reset the workspace and make the links work correctly, but it seems to me that a single document URL should always override the workspace and make itself the current notebook.

I reproduced this on a completely clean directory using Jupyterlab 3.0.14 and Python 3.7 -  let me know if any more info is needed. Thanks!

**Comment by jtpio** [comment] 2023-01-25 17:41
Something that came up during the [Jupyter for Education workshop](https://blog.jupyter.org/jupyter-community-workshop-jupyter-for-education-82af9e34b510) today was that the simple mode should maybe hide the activity bars as well to remove more noise.

It is now possible to hide the activity bars in JupyterLab 4. Maybe the Simple Mode should do it by default?

The end result would be this:

![image](https://user-images.githubusercontent.com/591645/214640513-0e591f62-e99d-468a-b1e8-7b84fb47abfa.png)

And without the status bar:

![image](https://user-images.githubusercontent.com/591645/214640636-c06ed024-f630-45fd-bc98-d4e060a33772.png)

**Comment by JasonWeill** [comment] 2024-08-28 21:50
Per conversation in this morning's Jupyter frontends meeting, I'm going to close this issue in favor of the newly spun-out #16728 and #16729.

**Closed by JasonWeill** 2024-08-28 21:50 UTC
