### ISSUE TITLE
Shift + Enter is not executing next consecutive cells.

### ISSUE THREAD

**Issue by ieglonew01f** [jupyterlab/jupyterlab#6891] opened 2019-07-25 09:03 UTC
**Shift + Enter is not executing the next consecutive cells.**

When I try to run cells by selecting using the arrow keys and then press shift + enter to run it, it doesn't execute the cell. I have to focus the cell editor then only it works.

**Steps to reproduce the behavior:**

1. Open a notebook with multiple cells
2. Execute the first cell by shift+enter
3. The selector moves to next output if there are any or it moves to the next cell.
4. Press shift + enter, it doesn't execute the cell like it used to before.

**Expected behavior**

If a cell is selected with the arrow keys, it should execute it without having to focus on the editor

**GIF**

![not-working3](https://user-images.githubusercontent.com/9274615/61860968-89429a80-aee8-11e9-85cd-560f823457f6.gif)

As you can see in this GIF, I'm unable to execute the cells unless I focus on the editor.

**Comment by bkerkhof** [comment] 2019-08-08 11:01
I can confirm to having the same issue (using Chrome on Windows)
```
jupyter                   1.0.0                    py37_7
jupyter_client            5.3.1                      py_0
jupyter_console           6.0.0                    py37_0
jupyter_core              4.5.0                      py_0
```
When re-executing a cell with shift-enter, the pointer jumps to the next cell which will not be executed when typing shift-enter a second time.

**Comment by jasongrout** [comment] 2019-08-08 15:26
> also using the regular notebook interface

If you are saying that this is also a problem with classic notebook, that indicates this is not a problem with JupyterLab.

If you are having this issue, please see if you can reproduce it:

1. In a new environment with just the latest JupyterLab installed. If you are using conda, create a new environment with `conda create -n jlab-test -c conda-forge jupyterlab` and activate the environment with `conda activate jlab-test`, then start `jupyter lab`. This checks to see if the issue has been fixed in the current JupyterLab, or if the issue comes from an extension, not JupyterLab itself.
2. Try to reproduce the issue after turning off chrome or firefox browser extensions, particularly browser extensions that modify webpages. We've had issues before where a browser extension was changing the page under JupyterLab, creating very unpredictable problems.
3. Try to reproduce the issue in the classic notebook (make sure to launch it from the JupyterLab help menu). If you can, this points to a problem that is outside of JupyterLab, such as a problem with the kernel, the notebook server, etc.
4. If you can still reproduce the issue in steps 1 and 2, and can *not* reproduce the issue in step 3, collect relevant server and javascript error messages, your `jupyterlab` and `notebook` versions (along with version numbers of any other relevant packages), screenshots or short screencasts illustrating the problem, and post an issue. Tell us what you tried in steps 1-3 above.

**Comment by ieglonew01f** [comment] 2019-08-15 11:11
Looks like I had a different issue with the shortcuts extension causing shift+enter, to fail.

**Comment by timkpaine** [comment] 2019-09-13 19:01
I see two things happening:
If I shift-enter and im in the last cell, a new cell gets created and focused (so i can shift-enter again). If i'm not in the last cell, it does not focus/enable editing on the next cell (it merely selects it).

I also seem to have lost autocompletes, on a vanilla jlab build 1.1.3.

**Comment by telamonian** [comment] 2019-09-13 19:50
> If I shift-enter and im in the last cell, a new cell gets created and focused (so i can shift-enter again). If i'm not in the last cell, it does not focus/enable editing on the next cell (it merely selects it).

Can you clarify this a little? I'm confused as what is actually going wrong. By "focused", you mean that the new cell is in edit mode (as opposed to command mode), right? I'm pretty sure that what you're describing is the expected behavior, so I assume I'm missing something. Some screenshots of the deviant behavior may help.

**Comment by timkpaine** [comment] 2019-09-13 21:00
On edit mode in a cell, shift enter executed the cell and brings you into command mode on the next cell, rather than edit mode on the next cell. Shift enter in command mode on any cell has no effect.

**Comment by telamonian** [comment] 2019-09-13 22:53
I can't reproduce this in `1.1.3` on mac in chrome/firefox. @timkpaine If you do a clean install in a new venv, do you still see the same bug?

**Comment by timkpaine** [comment] 2019-09-16 13:37
Looks like this is a py2 vs py3 thing, will close.

**Closed by timkpaine** 2019-09-16 13:37 UTC
Labels: tag:Design and UX, type:Bug

**Comment by timkpaine** [comment] 2019-09-16 13:46
fwiw i think the issue is going to be related to `prompt_toolkit`/`IPython`, not jupyterlab, as i have no issues in our python3 version.

**Comment by jasongrout** [comment] 2019-09-16 13:57
FWIW, JupyterLab should still be able to talk to python 2 kernels, though.

**Comment by timkpaine** [comment] 2019-09-16 18:51
Found the problem, I incorrectly backported:
`schema_paths = [path for path in glob(schema_pattern, recursive=True)]` 
in `jupyterlab_server/settings_handler.py` for the older glob functionality. The result was that nothing in `jupyterlab/schemas` got loaded. I would expect anyone with stale settings or moved folders to get similar symptoms, for future people looking at this issue.

**Comment by jasongrout** [comment] 2019-09-16 18:55
So does something need to change in jupyterlab_server to fix this?

**Comment by timkpaine** [comment] 2019-09-16 20:07
nope, we don't support python2

**Comment by jasongrout** [comment] 2019-09-16 20:21
Okay, I was misunderstanding the issue. It sounded like others would be caught on this in migrating old things, even if they were running python 3, but if you're saying that anyone running python 3 should be okay, then great!
