### ISSUE TITLE
JupyterLab fails to build

### ISSUE THREAD

**Issue by amzon-ex** [jupyterlab/jupyterlab#11456] opened 2021-11-14 11:09 UTC
## Description

JupyterLab fails to build using `jupyter lab build`. I read a few issues relating to this in the repo, but they don't seem to answer my issue.

## Context

JupyterLab installed with pip.

- Operating System and version: WSL Ubuntu 20.04
- Python version: 3.8.10
- Browser and version: Edge 95 
- JupyterLab version: 3.2.3
- Nodejs version: 17.1.0

## Error Log
```
[LabBuildApp] > node /home/amzon-ex/.local/lib/python3.8/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.21.1
$ webpack --config webpack.prod.minimize.config.js
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve './base.css' in '/home/amzon-ex/.local/share/jupyter/lab/staging/node_modules/@mohirio/jupyterlab-horizon-theme/style'
    at /home/amzon-ex/.local/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:2011:28
    at /home/amzon-ex/.local/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (/home/amzon-ex/.local/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/amzon-ex/.local/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/home/amzon-ex/.local/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/amzon-ex/.local/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at /home/amzon-ex/.local/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /home/amzon-ex/.local/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at /home/amzon-ex/.local/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at /home/amzon-ex/.local/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:972:5
resolve './base.css' in '/home/amzon-ex/.local/share/jupyter/lab/staging/node_modules/@mohirio/jupyterlab-horizon-theme/style'
  using description file: /home/amzon-ex/.local/share/jupyter/lab/staging/node_modules/@mohirio/jupyterlab-horizon-theme/package.json (relative path: ./style)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /home/amzon-ex/.local/share/jupyter/lab/staging/node_modules/@mohirio/jupyterlab-horizon-theme/package.json (relative path: ./style/base.css)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/amzon-ex/.local/share/jupyter/lab/staging/node_modules/@mohirio/jupyterlab-horizon-theme/style/base.css doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/amzon-ex/.local/share/jupyter/lab/staging/node_modules/@mohirio/jupyterlab-horizon-theme/style/base.css.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /home/amzon-ex/.local/share/jupyter/lab/staging/node_modules/@mohirio/jupyterlab-horizon-theme/style/base.css.json doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /home/amzon-ex/.local/share/jupyter/lab/staging/node_modules/@mohirio/jupyterlab-horizon-theme/style/base.css.wasm doesn't exist
      as directory
        /home/amzon-ex/.local/share/jupyter/lab/staging/node_modules/@mohirio/jupyterlab-horizon-theme/style/base.css doesn't exist
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/home/amzon-ex/.local/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 48, in debug_logging
    yield

[LabBuildApp]   File "/home/amzon-ex/.local/lib/python3.8/site-packages/jupyterlab/labapp.py", line 176, in start
    raise e

[LabBuildApp]   File "/home/amzon-ex/.local/lib/python3.8/site-packages/jupyterlab/labapp.py", line 172, in start
    build(name=self.name, version=self.version,

[LabBuildApp]   File "/home/amzon-ex/.local/lib/python3.8/site-packages/jupyterlab/commands.py", line 482, in build
    return handler.build(name=name, version=version, static_url=static_url,

[LabBuildApp]   File "/home/amzon-ex/.local/lib/python3.8/site-packages/jupyterlab/commands.py", line 697, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab
```

**Comment by jtpio** [comment] 2021-11-15 09:38
Thanks @amzon-ex for reporting.

> resolve './base.css' in '/home/amzon-ex/.local/share/jupyter/lab/staging/node_modules/@mohirio/jupyterlab-horizon-theme/style'

This might be an issue with the `@mohirio/jupyterlab-horizon-theme` extension. Have you tried installing it with `pip install jupyterlab-horizon-theme` only? (after creating a new environment just to make sure to start clean)

**Comment by amzon-ex** [comment] 2021-11-15 11:52
@jtpio 

I installed the theme via pip only. I didn't try the node route. Node is installed on my system because I was trying another extension which didn't seem to have a pip installation route. 

Does that help or should I still try re-installing?

**Comment by jtpio** [comment] 2021-11-15 12:30
I just tried locally in a new environment with the following:

```
mamba create -n tmp python -y
conda activate tmp
pip install jupyterlab-horizon-theme
```

And it seems to be working fine.

> JupyterLab fails to build using jupyter lab build

Do you need to build JupyterLab?

**Comment by amzon-ex** [comment] 2021-11-15 15:28
@jtpio 

> And it seems to be working fine.

Great, works fine for me too... that's alright.

> Do you need to build JupyterLab?

I don't know, really, this is what jupyter recommended and so I proceeded to build it. The theme works, but the fact that the build fails, is a problem, isn't it? I mean, in what situations in future may the failure to build cause a problem? I don't know...

**Comment by jtpio** [comment] 2021-11-15 16:48
> but the fact that the build fails, is a problem, isn't it?

I would say yes. But maybe it's caused by leftover files from previous installations. Does it build in a new environment?

With JupyterLab 3.0+ and the new prebuilt extension system (installable via `pip`) there is almost no need for running `jupyter lab build` when installing new extensions. Building JupyterLab is still possible for various reasons (generating non minified assets, more advanced deployment and bundling scenarios), but for a regular use it can normally be omitted now.

**Comment by krassowski** [comment] 2021-11-15 17:24
@jtpio I think that many users install extensions using the Extension Manager which installs source extensions and proceeds with rebuilding JupyterLab (invoking `jupyter lab build` under the hood, after prompting the user to confirm that they want to proceed) - the user may not even know that there is a different installation procedure out there - they just follow what UI recommends them to do. This would explain:

> I don't know, really, this is what jupyter recommended and so I proceeded to build it

I believe we should do something about the Extension Manager - which could be as simple as adding a note in the UI saying that we recommend using pip/conda instead (and obviously long term refactor/remove the source installation and make the extension manager use the prebuilt extensions _somehow_ - as discussed elsewhere).

**Comment by jtpio** [comment] 2021-11-15 20:04
> I believe we should do something about the Extension Manager

Agree. Given the current state of the extension manager we could even go one step further and remove support for installing source extensions (related to #11336) since we now recommend installing prebuilt extensions.

**Comment by amzon-ex** [comment] 2021-11-16 12:42
Thanks for your insights. As @jtpio asks, I'll try in a new environment once, to see if the error occurs. Otherwise, I'll be mindful not to overindulge in building when not strictly necessary.

**Comment by jtpio** [comment] 2021-11-17 10:45
Thanks @amzon-ex for the patience and @krassowski for improving the error message in #11476.

I think we can close the issue as answered for now. @amzon-ex if this is still an issue feel free to reopen or open a new one. Thanks!

**Closed by jtpio** 2021-11-17 10:45 UTC
Labels: bug
