### ISSUE TITLE
Changing cell type only works with keyboard, but not with mouse in Firefox

### ISSUE THREAD

**Issue by alexpyattaev** [jupyterlab/jupyterlab#10189] opened 2021-05-04 07:39 UTC
## Description
Menu for changing cell type only works with keyboard, but not with mouse. 
Apparently repeat of https://github.com/jupyterlab/jupyterlab/issues/2995
![image](https://user-images.githubusercontent.com/5932526/116972138-3ef86b00-acc3-11eb-906d-2c1b50393d92.png)

## Reproduce
Apparently using Firefox is enough. Start jupyter-lab, create cell, observe bug.  
Surprisingly, using keyboard to select from menu works fine

## Expected behavior

Should work with mouse same as with keyboard =)

## Context

- Operating System and version: Arch linux (probably does not matter)
- Browser and version: Firefox 89.0b4 (64-bit)
- JupyterLab version: Jupyter Server 1.6.4 is running 

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/opt/miniconda3/condabin
	/usr/local/sbin
	/usr/local/bin
	/usr/bin
	/home/xxx/.dotnet/tools
	/usr/lib/jvm/default/bin
	/usr/bin/site_perl
	/usr/bin/vendor_perl
	/usr/bin/core_perl
	/home/xxx/.local/bin

sys.path:
	/usr/bin
	/usr/lib/python39.zip
	/usr/lib/python3.9
	/usr/lib/python3.9/lib-dynload
	/home/xxx/.local/lib/python3.9/site-packages
	/home/xxx/pysh/src/pysh
	/usr/lib/python3.9/site-packages
	/usr/lib/python3.9/site-packages/linkgrammar
	/usr/share/panda3d

sys.executable:
	/usr/bin/python3

sys.version:
	3.9.4 (default, Apr 20 2021, 15:51:38) 
	[GCC 10.2.0]

platform.platform():
	Linux-5.9.6-arch1-1-x86_64-with-glibc2.33

which -a jupyter:
	/usr/bin/jupyter

pip list:
	Package                       Version                   Location
	----------------------------- ------------------------- ------------------------------
	absl-py                       0.12.0
	alabaster                     0.7.12
	anyio                         2.2.0
	anytree                       2.8.0
	apipkg                        1.5
	apparmor                      3.0.1
	appdirs                       1.4.4
	arandr                        0.1.10
	argon2-cffi                   20.1.0
	astor                         0.8.1
	astroid                       2.5.4
	astunparse                    1.6.3
	async-generator               1.10
	attrs                         20.3.0
	Automat                       20.2.0
	Babel                         2.9.0
	backcall                      0.2.0
	bcc                           0.19.0
	Beaker                        1.11.0
	beautifulsoup4                4.9.3
	bfi                           1.0.2
	bidict                        0.21.2
	black                         21.4b0
	bleach                        3.3.0
	Brlapi                        0.8.2
	btrfsutil                     5.11.1
	CacheControl                  0.12.6
	cachetools                    4.2.1
	Cartopy                       0.18.0
	ceph                          1.0.0
	ceph-volume                   1.0.0
	cephfs                        2.0.0
	cephfs-shell                  0.0.1
	cffi                          1.14.5
	chardet                       4.0.0
	click                         7.1.2
	click-plugins                 1.1.1
	colorama                      0.4.4
	constantly                    15.1.0
	contextlib2                   0.6.0.post1
	cryptography                  3.4.7
	cssselect                     1.1.0
	cycler                        0.10.0
	Cython                        0.29.23
	dataclasses-json              0.5.2
	decorator                     4.4.2
	defusedxml                    0.7.1
	deprecation                   2.1.0
	distlib                       0.3.1
	distro                        1.5.0
	dnspython                     1.16.0
	docopt                        0.6.2
	docutils                      0.16
	entrypoints                   0.3
	et-xmlfile                    1.0.1
	filelock                      3.0.12
	findimports                   1.5.2
	flake8                        3.9.1
	flake8-blind-except           0.2.0
	flatbuffers                   1.12.0
	frozendict                    1.2
	future                        0.18.2
	gast                          0.3.3
	GDAL                          3.2.2
	gitdb                         4.0.7
	GitPython                     3.1.14
	gmpy2                         2.1.0b5
	google-auth                   1.28.1
	google-auth-oauthlib          0.4.4
	google-pasta                  0.2.0
	gps                           3.22
	graphviz                      0.16
	greenlet                      1.0.0
	grpcio                        1.36.4
	h5py                          3.2.1
	html5-parser                  0.4.9
	html5lib                      1.1
	hyperlink                     21.0.0
	idna                          3.1
	imagesize                     1.2.0
	importlib-metadata            4.0.1
	incremental                   21.3.0
	infinity                      1.5
	inflect                       5.3.0
	iniconfig                     1.1.1
	intervals                     0.9.1
	ipykernel                     5.5.3
	ipympl                        0.6.3
	ipython                       7.22.0
	ipython-genutils              0.2.0
	ipywidgets                    7.6.3
	isc                           2.0
	isort                         5.8.0
	jdcal                         1.4.1
	jedi                          0.18.0
	Jinja2                        2.11.3
	json5                         0.9.5
	jsonschema                    3.2.0
	jupyter-client                6.1.12
	jupyter-console               6.2.0
	jupyter-core                  4.7.1
	jupyter-jsmol                 2021.3.0
	jupyter-packaging             0.9.2
	jupyter-server                1.6.4
	jupyterlab                    3.0.14
	jupyterlab-pygments           0.1.2
	jupyterlab-server             2.5.0
	jupyterlab-widgets            1.0.0
	Keras-Applications            1.0.8
	Keras-Preprocessing           1.1.2
	kiwisolver                    1.3.1
	lazy-object-proxy             1.6.0
	lensfun                       0.3.95
	LibAppArmor                   3.0.1
	libfdt                        1.6.0
	libmsym                       0.2.4
	libvirt-python                7.1.0
	linecache2                    1.0.0
	lit                           0.11.1.dev0
	lockfile                      0.12.2
	louis                         3.17.0
	lxml                          4.6.3
	Mako                          1.1.4
	Markdown                      3.3.4
	Markups                       3.0.0
	MarkupSafe                    1.1.1
	marshmallow                   3.9.1
	marshmallow-enum              1.5.1
	matplotlib                    3.4.1
	mccabe                        0.6.1
	meld                          3.20.3
	mercurial                     5.7.1
	metakernel                    0.27.5
	mistune                       0.8.4
	mock                          3.0.5
	more-itertools                8.7.0
	mpmath                        1.2.1
	msgpack                       1.0.2
	mypy                          0.812
	mypy-extensions               0.4.3
	mypy-protobuf                 1.24
	nbclassic                     0.2.7
	nbclient                      0.5.3
	nbconvert                     6.0.7
	nbformat                      5.1.2
	nest-asyncio                  1.5.1
	netsnmp-python                1.0a1
	networkx                      2.5.1
	nose                          1.3.7
	notebook                      6.2.0
	nptyping                      1.3.0
	num2words                     0.5.10
	numpy                         1.20.2
	oauthlib                      3.1.0
	octave-kernel                 0.32.0
	openpyxl                      3.0.7
	opt-einsum                    3.3.0
	ordered-set                   4.0.2
	packaging                     20.9
	panda3d                       1.10.8
	pandas                        1.2.3
	pandocfilters                 1.4.3
	parso                         0.8.1
	pathspec                      0.8.1
	pbr                           5.6.0
	pep517                        0.10.0
	pexpect                       4.8.0
	pickleshare                   0.7.5
	Pillow                        8.2.0
	Pint                          0.16.1
	pip                           20.3.1
	Pivy                          0.6.5
	pluggy                        0.13.1
	ply                           3.11
	progress                      1.5
	prometheus-client             0.9.0
	prompt-toolkit                3.0.18
	protobuf                      3.15.8
	psutil                        5.8.0
	ptyprocess                    0.7.0
	py                            1.10.0
	pyaml                         20.4.0
	pyasn1                        0.4.8
	pyasn1-modules                0.2.8
	pybind11                      2.6.2
	pycairo                       1.20.0
	pycodestyle                   2.7.0
	pycparser                     2.20
	pydeps                        1.9.13
	pydot                         1.4.2
	pyflakes                      2.3.1
	pyglet                        1.5.16
	Pygments                      2.8.1
	PyGObject                     3.40.1
	PyHamcrest                    1.10.0
	pylint                        2.7.4
	pymongo                       3.11.3
	pyOpenSSL                     20.0.1
	pyparsing                     2.4.7
	pyprof2calltree               1.4.5
	PyQt5                         5.15.4
	PyQt5-sip                     12.8.1
	PyQtWebEngine                 5.15.4
	pyquaternion                  0.9.9
	pyrealsense2                  2.42.0
	pyroute2                      0.5.18
	pyrsistent                    0.17.3
	pyserial                      3.5
	pysh                          1.0                       /home/xxx/pysh/src/pysh
	pyshp                         2.1.2
	PySide2                       5.15.2
	pytest                        6.2.3
	pytest-asyncio                0.15.1
	pytest-black                  0.3.12
	pytest-datadir                1.3.1
	pytest-flake8                 1.0.7
	pytest-html                   3.1.1
	pytest-metadata               1.11.0
	pytest-mock                   3.1.1
	pytest-pylint                 0.18.0
	pytest-randomly               3.5.0
	pytest-regressions            2.0.2
	pytest-sugar                  0.9.4
	pytest-twisted                1.13.2
	python-dateutil               2.8.1
	python-libtorrent             1.2.11
	python-markdown-math          0.8
	pytz                          2021.1
	pyvcd                         0.2.3
	PyX                           0.15
	PyYAML                        5.4.1
	pyzmq                         22.0.3
	qrtools                       2.1
	quantiphy                     2.13.0
	quantulum3                    0.7.6
	rados                         2.0.0
	ranger-fm                     1.9.3
	rbd                           2.0.0
	rectpack                      0.2.1
	regex                         2021.4.4
	requests                      2.25.1
	requests-oauthlib             1.3.0
	resolvelib                    0.5.4
	ReText                        7.2.1
	retrying                      1.3.3
	rgw                           2.0.0
	rsa                           4.7.2
	scapy                         git-archive.dev8b63d73a17
	scipy                         1.6.3
	scons                         3.1.2
	Send2Trash                    1.5.0
	service-identity              18.1.0
	setuptools                    56.0.0
	Shapely                       1.7.1
	shiboken2                     5.15.2
	six                           1.15.0
	smmap                         4.0.0
	sniffio                       1.2.0
	snowballstemmer               2.1.0
	sortedcontainers              2.3.0
	soupsieve                     2.2.1
	Sphinx                        3.5.4
	sphinx-rtd-theme              0.5.2
	sphinxcontrib-applehelp       1.0.2
	sphinxcontrib-devhelp         1.0.2
	sphinxcontrib-htmlhelp        1.0.3
	sphinxcontrib-jsmath          1.0.1
	sphinxcontrib-qthelp          1.0.3
	sphinxcontrib-serializinghtml 1.1.4
	stdlib-list                   0.8.0
	stringcase                    1.2.0
	sympy                         1.8
	team                          1.0
	tensorboard                   2.4.1
	tensorboard-plugin-wit        1.7.0
	tensorflow                    2.4.1
	tensorflow-estimator          2.3.0
	termcolor                     1.1.0
	terminado                     0.9.4
	testpath                      0.4.4
	toml                          0.10.2
	tomlkit                       0.7.0
	tornado                       6.1
	tqdm                          4.60.0
	traceback2                    1.4.0
	traitlets                     5.0.5
	transitions                   0.8.5
	Twisted                       21.2.0
	typed-ast                     1.4.2
	typing-extensions             3.7.4.3
	typing-inspect                0.6.0
	typish                        1.9.1
	unittest2                     1.1.0
	urllib3                       1.26.4
	VerbalExpressions             0.0.2
	virtualenv                    20.4.4
	wcwidth                       0.2.5
	webencodings                  0.5.1
	Werkzeug                      1.0.1
	wheel                         0.36.2
	widgetsnbextension            3.5.1
	wrapt                         1.12.1
	xlrd                          2.0.1
	youtube-dl                    2021.4.26
	zipp                          3.4.1
	zope.interface                5.4.0

conda list:
	# packages in environment at /opt/miniconda3:
	#
	# Name                    Version                   Build  Channel
	_libgcc_mutex             0.1                        main  
	brotlipy                  0.7.0           py38h27cfd23_1003  
	ca-certificates           2020.10.14                    0  
	certifi                   2020.6.20          pyhd3eb1b0_3  
	cffi                      1.14.3           py38h261ae71_2  
	chardet                   3.0.4           py38h06a4308_1003  
	conda                     4.9.2            py38h06a4308_0  
	conda-package-handling    1.7.2            py38h03888b9_0  
	cryptography              3.2.1            py38h3c74f83_1  
	idna                      2.10                       py_0  
	ld_impl_linux-64          2.33.1               h53a641e_7  
	libedit                   3.1.20191231         h14c3975_1  
	libffi                    3.3                  he6710b0_2  
	libgcc-ng                 9.1.0                hdf63c60_0  
	libstdcxx-ng              9.1.0                hdf63c60_0  
	ncurses                   6.2                  he6710b0_1  
	openssl                   1.1.1h               h7b6447c_0  
	pip                       20.2.4           py38h06a4308_0  
	pycosat                   0.6.3            py38h7b6447c_1  
	pycparser                 2.20                       py_2  
	pyopenssl                 19.1.0             pyhd3eb1b0_1  
	pysocks                   1.7.1            py38h06a4308_0  
	python                    3.8.5                h7579374_1  
	readline                  8.0                  h7b6447c_0  
	requests                  2.24.0                     py_0  
	ruamel_yaml               0.15.87          py38h7b6447c_1  
	setuptools                50.3.1           py38h06a4308_1  
	six                       1.15.0           py38h06a4308_0  
	sqlite                    3.33.0               h62c20be_0  
	tk                        8.6.10               hbc83047_0  
	tqdm                      4.51.0             pyhd3eb1b0_0  
	urllib3                   1.25.11                    py_0  
	wheel                     0.35.1             pyhd3eb1b0_0  
	xz                        5.2.5                h7b6447c_0  
	yaml                      0.2.5                h7b6447c_0  
	zlib                      1.2.11               h7b6447c_3

</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Nothing interesting from `jupyter lab --debug`, seems that mouse clicks do not get passed to the server at all.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Nothing in javascript console (no errors, nothing relevant to changing cell type)
</pre>
</details>

**Comment by krassowski** [comment] 2021-05-05 10:23
Confirmed on binder using JupyterLab 3.0.7 and Firefox Nightly 90.0a1. It works fine on Google Chrome.

**Comment by Eyon42** [comment] 2021-06-22 04:31
I'm seeing the same behavior.
OS: Pop os 20.04
Conda jupyterlab-3.0.14
Firefox 89.0

**Comment by strawpants** [comment] 2021-06-22 14:34
Same here, interesting enough. If I go into developer mode and force :hover on the upper div of the cell drop-down menu it works.

![image](https://user-images.githubusercontent.com/9840083/122941874-119c7500-d376-11eb-9fcf-c1169c0d679b.png)

**Comment by fcollonval** [comment] 2021-07-08 13:39
I had a try looking into this. I used the following snippet to see if something was stealing the focus as suggested by Jason:

```
document.addEventListener('focusin', function() {
  console.log('focused: ', document.activeElement)
}, true);
```

But the focus is not changing when opening the select element.

> Note: the HTMLSelect component used for the cell type does not come from blueprintJS.

**Comment by fcollonval** [comment] 2021-07-13 11:03
More testing - actually this is probably due to some CSS when using the [demo from mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select), the list of items stays display on Firefox when the mouse leave the list. But in JupyterLab, the list disappears.

> The bug is also affecting the delimiter picker of the DSV viewer.

**Comment by krassowski** [comment] 2021-07-17 12:20
The "focus on a cell as soon as possible" approach (which may or may not be related) is causing some other issues like #10638.

**Comment by n8xm** [comment] 2021-07-22 23:56
Can confirm on: 
- JupyterLab 3.0.16 
- Firefox 90.0.1
- Arch Linux (kernel `5.13.4-arch1-1`)

Workaround: 
1. Click on the dropdown menu.
2. Use the arrow keys on the keyboard to select the desired cell type.
3. Press enter to confirm.

**Comment by fcollonval** [comment] 2021-07-23 09:08
Some updates - I still have not found the root cause. But I discovered that the simpler notebook example is also suffering the bug.

**Comment by huyfam** [comment] 2021-07-28 09:49
I confirm this issue on my system.

- OS: Ubuntu 20.04.2
- Jupyter Lab 3.0.14 (through conda)
- Firefox 90.0 (64 bit).

It has occured for some time.

**Comment by krassowski** [comment] 2021-07-30 00:28
I spend too many hours trying to solve this.
- there is no mouse, control nor pointer event that we handle that is associated with this behaviour
- there are some transient events in React which could be somehow associated but this is difficult for me to debug
- this is uniquely associated with the toolbar: moving the `<select>` to other element (e.g. menubar) makes it behave well; moving it back to a toolbar in a different main area widget such as the licenses tab makes it break again
- removing all other widgets from toolbar does nothing
- I also set breakpoints on lumino message handlers in associated widgets, and went as far as investigating completer's scroll event which also fires around that time; there were no useful lessons from that
- when in a breakpoint with all JavaScript execution on pause, the select dropdowns are still behaving like that; it seems like if they are beyond DOM and beyond the JavaScripts, control - they are event painted on top of the Firefox's debugger grey-out background...
- Firefox has multiple bugs with handling `<select>` and mouseleave, some of which are many years old; they all sound related, but the main point is they don't have a good test coverage of this area:
   - [Dropdowns probably should be preserved among reframe](https://bugzilla.mozilla.org/show_bug.cgi?id=1440506) - this might be the root cause
   - ['mouseout' event fires prematurely for <select> element](https://bugzilla.mozilla.org/show_bug.cgi?id=1480664)
   - [mouseenter/mouseleave fire differently on <select>s in e10s mode.](https://bugzilla.mozilla.org/show_bug.cgi?id=1342569)
   - [Incorrect mouseOut triggered when using select element](https://bugzilla.mozilla.org/show_bug.cgi?id=423719)
   - [Select element closes on mouseout if this causes CSS filter to be added/removed](https://bugzilla.mozilla.org/show_bug.cgi?id=1608175)

Ideally someone would debug this on the Firefox implementation level...

If we cannot find a solution, we might want to consider re-implementing the dropdown manually instead of using native `<select>` (but this might be sub-optimal accessibility-wise...); for example, there is `@blueprintjs/select` (since we are already using blueprint).

**Comment by fcollonval** [comment] 2021-07-30 06:20
Thanks a lot @krassowski to diving into this.

Should we open an issue on Firefox tracker to get some insights from them?

**Comment by krassowski** [comment] 2021-07-30 11:07
I found it! It turns out this is because of the mobile-friendly, scrollable toolbar feature from #8417 added in 2.2. [This](https://github.com/jupyterlab/jupyterlab/pull/8417/files#diff-22fc19a2f3ef27551a83af0f75d33604a07ad8f48331fdfbec42f1859ae9c72eR27-R29) CSS rule:

```css
.jp-Toolbar:hover {
  overflow-x: auto;
}
```

causes a reframe in Firefox triggering [Firefox bug 1440506](https://bugzilla.mozilla.org/show_bug.cgi?id=1440506) (Dropdowns probably should be preserved among reframe), so it is very similar to its duplicate ([Select element closes on mouseout if this causes CSS filter to be added/removed](https://bugzilla.mozilla.org/show_bug.cgi?id=1608175)) which is what lead me to the culprit. CC @jtpio. This is a different bug in Firefox than [the earlier issue](https://github.com/jupyterlab/jupyterlab/issues/2995).

**Comment by krassowski** [comment] 2021-07-30 15:45
Also CC @3coins and @ellisonbg who are currently working on improving the toolbar experience. Any ideas how to solve this one? Should we remove the tiny scrollbars now given that #10720 is in? Or create a custom selector widget instead of using `<select>` as this seems to be causing multiple problems (and is difficult to style)?

**Comment by 3coins** [comment] 2021-07-30 18:47
@krassowski Thanks for including in the discussion. Having scrollbars with responsive toolbar is redundant and likely to cause more issues, so this should be removed regardless of whether we go with custom selector widget or not.
Creating a custom selector widget would help with other issues with current <select> (quirks across browsers) and also provide flexibility in styling the widget.

**Comment by ellisonbg** [comment] 2021-07-30 18:52
Yeah, I think we should remove toolbar scrolling with the responsive design that was merged.

**Closed** 2021-08-13 14:54 UTC
Labels: bug, help wanted, pkg:notebook
