### ISSUE TITLE
Cursor keeps shifting to the top of notebooks in JLab v4

### ISSUE THREAD

**Issue by erkin98** [jupyterlab/jupyterlab#16144] opened 2024-04-10 10:10 UTC
## Description

[Screencast_10.04.2024_13:59:40.webm](https://github.com/jupyterlab/jupyterlab/assets/20378722/24eb9a41-0082-4f82-b96c-82a17e37b595)

## Reproduce

1. Go to Notebook (notebook opening with `IDocumentManager.openOrReveal`)
2. Click on insert cell button
3. Auto Scroll down happens 
4. See video

## Expected behavior

It shouldn't go to that down

## Context

- Operating System and version: Linux Ubuntu 22.04
- Browser and version: Chrome 123 
- JupyterLab version: 4.1.5

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by JasonWeill** [comment] 2024-04-15 21:52
Are you using real-time collaboration (RTC)? If so, this may be a duplicate of #14106.

**Comment by erkin98** [comment] 2024-04-16 01:14
> Are you using real-time collaboration (RTC)? If so, this may be a duplicate of #14106.

yes, we are using RTC

**Comment by JasonWeill** [comment] 2024-04-16 16:06
Let's continue the conversation in #14106. Thank you for your contribution!

**Closed by JasonWeill** 2024-04-16 16:06 UTC
Labels: bug, status:Duplicate, status:Needs Triage

**Comment by andrii-i** [comment] 2024-06-12 23:31
I looked at this issue while trying to troubleshoot #14106. Auto scroll down described here and shown on video is a standard / expected behavior during the creation of a new cell. Viewport is expected to move / scroll to automatically show the new cell including during the creation of a new cell via "Insert a cell below (B)" as shown on video. 

@erkin98 if you find this default behavior problematic, it would be more fruitful to open an issue about "Auto Scroll on new cell creation" to for example discuss a possibility of making such a behavior optional.
