### ISSUE TITLE
Erratic behaviour of cell operations (C, V, A, B)

### ISSUE THREAD

**Issue by dirkroorda** [jupyterlab/jupyterlab#16533] opened 2024-06-27 09:52 UTC
## Description

In JupyterLab 4.2, when trying to add cells above or below the current cell, or when copying and pasting a cell, the behaviour is erratic. Most of the time you see no effect, but when scrolling a little, the created cells suddenly appear.
It does not matter whether the actions are triggered by a shortcut or by the toolbar or by the cell menu.

## Reproduce

On macos, in a terminal, start `jupyter lab` (using safari as default browser) and create a new notebook. Type something in the first code cell. Do not run it. Try to add a cell above or below. You will not see it happening.
Scroll the notebook. The new cell will spring into existence.

## Expected behavior

The new cell should be instantly visible.

## Context

Macos Sonoma 14.5, macbook pro arm, Safari browser (Version 17.5 (19618.2.12.11.6)), JupyterLab version 4.2 or higher.

* No problem with Jupyterlab versions < 4.2
* No problem with Chrome and Firefox, even with versions >= 4.2

Other measures taken:

* using fresh install of python 3.12.4 from python.org; with no other modules installed.
* cleared all website data in Safari.
* fresh install of jupyter lab, no customisations, no extensions
* removed ~/.jupyter
* cleaned the PATH env var to the minimum

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/Library/Frameworks/Python.framework/Versions/3.12/bin
	/usr/local/bin
	/System/Cryptexes/App/usr/bin
	/usr/bin
	/bin
	/usr/sbin
	/sbin
	/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
	/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
	/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
	/Library/TeX/texbin

sys.path:
	/Library/Frameworks/Python.framework/Versions/3.12/bin
	/Library/Frameworks/Python.framework/Versions/3.12/lib/python312.zip
	/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12
	/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/lib-dynload
	/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages

sys.executable:
	/Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12

sys.version:
	3.12.4 (v3.12.4:8e8a4baf65, Jun  6 2024, 17:33:18) [Clang 13.0.0 (clang-1300.0.29.30)]

platform.platform():
	macOS-14.5-arm64-arm-64bit

which -a jupyter:
	/Library/Frameworks/Python.framework/Versions/3.12/bin/jupyter

pip list:
	Package                   Version
	------------------------- --------------
	aiofiles                  22.1.0
	aiosqlite                 0.20.0
	anyio                     3.7.1
	appnope                   0.1.4
	argon2-cffi               23.1.0
	argon2-cffi-bindings      21.2.0
	arrow                     1.3.0
	asttokens                 2.4.1
	async-lru                 2.0.4
	attrs                     23.2.0
	Babel                     2.15.0
	beautifulsoup4            4.12.3
	bleach                    6.1.0
	certifi                   2024.6.2
	cffi                      1.16.0
	charset-normalizer        3.3.2
	comm                      0.2.2
	debugpy                   1.8.2
	decorator                 5.1.1
	defusedxml                0.7.1
	entrypoints               0.4
	executing                 2.0.1
	fastjsonschema            2.20.0
	fqdn                      1.5.1
	h11                       0.14.0
	httpcore                  1.0.5
	httpx                     0.27.0
	idna                      3.7
	ipykernel                 6.29.4
	ipython                   8.25.0
	ipython-genutils          0.2.0
	isoduration               20.11.0
	jedi                      0.19.1
	Jinja2                    3.1.4
	json5                     0.9.25
	jsonpointer               3.0.0
	jsonschema                4.22.0
	jsonschema-specifications 2023.12.1
	jupyter_client            7.4.9
	jupyter_core              5.7.2
	jupyter-events            0.10.0
	jupyter-lsp               2.2.5
	jupyter_server            2.14.1
	jupyter_server_fileid     0.9.2
	jupyter_server_terminals  0.5.3
	jupyter_server_ydoc       0.8.0
	jupyter-ydoc              0.2.5
	jupyterlab                4.2.3
	jupyterlab_pygments       0.3.0
	jupyterlab_server         2.27.2
	MarkupSafe                2.1.5
	matplotlib-inline         0.1.7
	mistune                   3.0.2
	nbclassic                 0.5.6
	nbclient                  0.10.0
	nbconvert                 7.16.4
	nbformat                  5.10.4
	nest-asyncio              1.6.0
	notebook                  6.5.7
	notebook_shim             0.2.4
	overrides                 7.7.0
	packaging                 24.1
	pandocfilters             1.5.1
	parso                     0.8.4
	pexpect                   4.9.0
	pip                       24.1.1
	platformdirs              4.2.2
	prometheus_client         0.20.0
	prompt_toolkit            3.0.47
	psutil                    6.0.0
	ptyprocess                0.7.0
	pure-eval                 0.2.2
	pycparser                 2.22
	Pygments                  2.18.0
	python-dateutil           2.9.0.post0
	python-json-logger        2.0.7
	PyYAML                    6.0.1
	pyzmq                     26.0.3
	referencing               0.35.1
	requests                  2.32.3
	rfc3339-validator         0.1.4
	rfc3986-validator         0.1.1
	rpds-py                   0.18.1
	Send2Trash                1.8.3
	setuptools                70.1.1
	six                       1.16.0
	sniffio                   1.3.1
	soupsieve                 2.5
	stack-data                0.6.3
	terminado                 0.18.1
	tinycss2                  1.3.0
	tornado                   6.4.1
	traitlets                 5.14.3
	types-python-dateutil     2.9.0.20240316
	typing_extensions         4.12.2
	uri-template              1.3.0
	urllib3                   2.2.2
	wcwidth                   0.2.13
	webcolors                 24.6.0
	webencodings              0.5.1
	websocket-client          1.8.0
	y-py                      0.6.2
	ypy-websocket             0.8.4

</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
me:~ > jupyter lab --debug
[D 2024-06-27 11:40:51.255 ServerApp] Searching ['/Users/me/.jupyter', '/Users/me/Library/Python/3.12/etc/jupyter', '/Library/Frameworks/Python.framework/Versions/3.12/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 2024-06-27 11:40:51.255 ServerApp] Looking for jupyter_config in /etc/jupyter
[D 2024-06-27 11:40:51.255 ServerApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 2024-06-27 11:40:51.255 ServerApp] Looking for jupyter_config in /Library/Frameworks/Python.framework/Versions/3.12/etc/jupyter
[D 2024-06-27 11:40:51.255 ServerApp] Looking for jupyter_config in /Users/me/Library/Python/3.12/etc/jupyter
[D 2024-06-27 11:40:51.255 ServerApp] Looking for jupyter_config in /Users/me/.jupyter
[D 2024-06-27 11:40:51.256 ServerApp] Looking for jupyter_server_config in /etc/jupyter
[D 2024-06-27 11:40:51.256 ServerApp] Looking for jupyter_server_config in /usr/local/etc/jupyter
[D 2024-06-27 11:40:51.256 ServerApp] Looking for jupyter_server_config in /Library/Frameworks/Python.framework/Versions/3.12/etc/jupyter
[D 2024-06-27 11:40:51.256 ServerApp] Looking for jupyter_server_config in /Users/me/Library/Python/3.12/etc/jupyter
[D 2024-06-27 11:40:51.256 ServerApp] Looking for jupyter_server_config in /Users/me/.jupyter
[I 2024-06-27 11:40:51.278 ServerApp] jupyter_lsp | extension was successfully linked.
[D 2024-06-27 11:40:51.280 FileIdExtension] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue {'update': {'jupyter_lsp': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook_shim': True}}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[D 2024-06-27 11:40:51.280 ServerApp] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_lsp': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2024-06-27 11:40:51.280 ServerApp] jupyter_server_fileid | extension was successfully linked.
[D 2024-06-27 11:40:51.281 TerminalsExtensionApp] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_lsp': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[D 2024-06-27 11:40:51.282 ServerApp] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_lsp': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2024-06-27 11:40:51.282 ServerApp] jupyter_server_terminals | extension was successfully linked.
[D 2024-06-27 11:40:51.283 YDocExtension] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_lsp': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[D 2024-06-27 11:40:51.283 ServerApp] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_lsp': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2024-06-27 11:40:51.284 ServerApp] jupyter_server_ydoc | extension was successfully linked.
[D 2024-06-27 11:40:51.285 LabApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_lsp': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2024-06-27 11:40:51.285 ServerApp] jupyterlab | extension was successfully linked.
[D 2024-06-27 11:40:51.287 NotebookApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_lsp': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2024-06-27 11:40:51.287 ServerApp] nbclassic | extension was successfully linked.
[I 2024-06-27 11:40:51.387 ServerApp] notebook_shim | extension was successfully linked.
[D 2024-06-27 11:40:51.388 ServerApp] Config changed: {'ExtensionApp': {'log_level': 'DEBUG'}, 'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_lsp': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook_shim': True}>}}
[D 2024-06-27 11:40:51.388 ServerApp] Raising open file limit: soft 2048->4096; hard 9223372036854775807->9223372036854775807
[I 2024-06-27 11:40:51.448 ServerApp] notebook_shim | extension was successfully loaded.
[D 2024-06-27 11:40:51.449 ServerApp] [lsp] rootUri will be file:///Users/me
[D 2024-06-27 11:40:51.449 ServerApp] [lsp] virtualDocumentsUri will be file:///Users/me/.virtual_documents
[I 2024-06-27 11:40:51.449 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-06-27 11:40:51.449 FileIdExtension] Configured File ID manager: ArbitraryFileIdManager
[I 2024-06-27 11:40:51.449 FileIdExtension] ArbitraryFileIdManager : Configured root dir: /Users/me
[I 2024-06-27 11:40:51.449 FileIdExtension] ArbitraryFileIdManager : Configured database path: /Users/me/Library/Jupyter/file_id_manager.db
[I 2024-06-27 11:40:51.449 FileIdExtension] ArbitraryFileIdManager : Successfully connected to database file.
[I 2024-06-27 11:40:51.449 FileIdExtension] ArbitraryFileIdManager : Creating File ID tables and indices with journal_mode = DELETE
[I 2024-06-27 11:40:51.449 FileIdExtension] Attached event listeners.
[I 2024-06-27 11:40:51.449 ServerApp] jupyter_server_fileid | extension was successfully loaded.
[I 2024-06-27 11:40:51.450 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-06-27 11:40:51.450 ServerApp] jupyter_server_ydoc | extension was successfully loaded.
[I 2024-06-27 11:40:51.450 LabApp] JupyterLab extension loaded from /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jupyterlab
[I 2024-06-27 11:40:51.450 LabApp] JupyterLab application directory is /Library/Frameworks/Python.framework/Versions/3.12/share/jupyter/lab
[I 2024-06-27 11:40:51.451 LabApp] Extension Manager is 'pypi'.
[D 2024-06-27 11:40:51.451 LabApp] Plugins in PyPIExtensionManager will managed on the sys_prefix level
[D 2024-06-27 11:40:51.467 LabApp] Extensions list will be fetched from https://pypi.org/pypi.
[D 2024-06-27 11:40:51.467 LabApp] Plugins in PluginManager will managed on the sys_prefix level
[I 2024-06-27 11:40:51.469 ServerApp] jupyterlab | extension was successfully loaded.

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|
                                                                           

</pre>

... truncated to comply with length restrictions ...

</details>

<details><summary>Browser Output</summary>
<pre>
[Warning] Language pack 'en_US' not installed! (jlab_core.c1feae0690cd2229a88c.js, line 1)
[Debug] Starting application in workspace: "default" (jlab_core.c1feae0690cd2229a88c.js, line 1)
[Debug] Starting WebSocket: ws://localhost:8888/api/kernels/46ddc2b9-6c2c-4e08-b84b-74f77ee25a71 (jlab_core.c1feae0690cd2229a88c.js, line 1)
[Debug] Starting WebSocket: ws://localhost:8888/api/kernels/46ddc2b9-6c2c-4e08-b84b-74f77ee25a71 (jlab_core.c1feae0690cd2229a88c.js, line 1)
[Debug] Starting WebSocket: ws://localhost:8888/api/kernels/46ddc2b9-6c2c-4e08-b84b-74f77ee25a71 (jlab_core.c1feae0690cd2229a88c.js, line 1)

</pre>
</details>

**Comment by krassowski** [comment] 2024-06-27 11:31
Thank you for reporting! I believe this is a duplicate of https://github.com/jupyterlab/jupyterlab/issues/16373. The possible workarounds are to either:
- go to Settings → Settings Editor → Notebook → Windowing mode → change it from "full" to "defer"
- upgrade Safari to latest Technical Preview
- downgrade JupyterLab to 4.1.x

**Comment by dirkroorda** [comment] 2024-06-27 15:36
I did the downgrade, and that works.
By the way, github now thinks that I have published my Personal Access Token. Hm.

**Comment by krassowski** [comment] 2024-06-27 15:58
Sorry about that, make sure to invalidate the token ASAP. I opened https://github.com/jupyter-server/jupyter_server/issues/1436

**Comment by dirkroorda** [comment] 2024-06-27 16:05
GitHub already did it form me.
In the meanwhile I upgraded again to 4.2.3 and put the windowing mode to `defer`. That works nicely, as far as I can quickly see. Thanks for suggesting it, it helps to understand what was going on.

**Comment by JasonWeill** [comment] 2024-07-02 16:19
@dirkroorda @krassowski Thank you for your contributions! Let's keep the conversation going about Safari compatibility in #16373.

**Closed by JasonWeill** 2024-07-02 16:19 UTC
Labels: bug, status:Needs Triage
