### ISSUE TITLE
Jupyter lab build error

### ISSUE THREAD

**Issue by robmarkcole** [jupyterlab/jupyterlab#6086] opened 2019-03-10 10:19 UTC
**Describe the bug**
`Jupyter lab build` always fails with:

```
ERROR in ./~/vega-lite/build/src/compile/scale/component.js
Module not found: Error: Can't resolve 'vega' in '/Users/robincole/anaconda3/share/jupyter/lab/staging/node_modules/vega-lite/build/src/compile/scale'
 @ ./~/vega-lite/build/src/compile/scale/component.js 1:0-31
 @ ./~/vega-lite/build/src/compile/scale/parse.js
 @ ./~/vega-lite/build/src/compile/model.js
 @ ./~/vega-lite/build/src/compile/facet.js
 @ ./~/vega-lite/build/src/compile/buildmodel.js
 @ ./~/vega-lite/build/src/compile/compile.js
 @ ./~/vega-lite/build/src/index.js
 @ ./~/vega-embed/build/src/embed.js
 @ ./~/@jupyterlab/vega3-extension/lib/index.js
 @ ./build/index.out.js
 @ multi whatwg-fetch ./build/index.out.js
```

**Comment by rowles** [comment] 2019-03-11 19:22
I am seeing this same issue. Vega had a different issue a couple months ago broke our JupyterLab builds.

**Comment by javabrett** [comment] 2019-03-11 20:04
Appears fixed in their `master` but still pending release at this time.

https://github.com/vega/vega-lite/commit/1bf8cae0a22e52b9e0ed9a6259dc04c60bebf6a6

**Comment by javabrett** [comment] 2019-03-11 20:08
Possibly regressed in https://github.com/vega/vega-lite/commit/3f3637aa77e797f0272dc34f3ea0746c337cad3e so locking temporarility to < 3.0.0-rc14 might fix build, or wait on next rc.

**Comment by rowles** [comment] 2019-03-11 20:21
Hmm, looks like the vega extension locks the [vega-embed version](https://github.com/jupyterlab/jupyterlab/blob/8a141cadf904150b01886f189a10a3143676a1eb/packages/vega4-extension/package.json#L36). It looks like vega-embed is very generous on its dependencies and rc versions get put in the dependency tree. Not that ideal. Maybe an issue should be created somewhere in vega.

**Comment by francoislauger** [comment] 2019-03-11 20:25
Same bug  here I think,  jupyter lab build  stop here:

```
[LabBuildApp] > node /Users/USER/anaconda3/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build
yarn run v1.9.4
$ webpack
ModuleNotFoundError: Module not found: Error: Can't resolve 'vega' in '/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/vega-lite/build/src/compile/scale'
    at factory.create (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:535:10)
    at factory (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/neo-async/async.js:2825:7
    at /Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/neo-async/async.js:6886:13
    at normalResolver.resolve (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn41 (eval at create (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:381:1)
    at resolver.doResolve (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:23:37)
    at hook.callAsync (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at args (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/forEachBail.js:30:14)
    at hook.callAsync (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
resolve 'vega' in '/Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/vega-lite/build/src/compile/scale'
  Parsed request is a module
  using description file: /Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/vega-lite/build/package.json (relative path: ./src/compile/scale)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/vega-lite/build/src/compile/scale/node_modules doesn't exist or is not a directory
      /Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/vega-lite/build/src/compile/node_modules doesn't exist or is not a directory
      /Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/vega-lite/build/src/node_modules doesn't exist or is not a directory
      /Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/vega-lite/build/node_modules doesn't exist or is not a directory
      /Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/node_modules doesn't exist or is not a directory
      /Users/USER/anaconda3/share/jupyter/lab/node_modules doesn't exist or is not a directory
      /Users/USER/anaconda3/share/jupyter/node_modules doesn't exist or is not a directory
      /Users/USER/anaconda3/share/node_modules doesn't exist or is not a directory
      /Users/USER/anaconda3/node_modules doesn't exist or is not a directory
      /Users/USER/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/vega-lite/node_modules
        using description file: /Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/vega-lite/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in /Users/USER/anaconda3/share/jupyter/lab/staging/node_modules
        using description file: /Users/USER/anaconda3/share/jupyter/lab/staging/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/vega-lite/package.json (relative path: ./node_modules/vega)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
          using description file: /Users/USER/anaconda3/share/jupyter/lab/staging/package.json (relative path: ./node_modules/vega)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/vega-lite/node_modules/vega doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/vega doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/vega-lite/node_modules/vega.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/vega.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/vega-lite/node_modules/vega.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/vega.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/vega-lite/node_modules/vega.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/vega.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/vega-lite/node_modules/vega.json doesn't exist
              /Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/vega.json doesn't exist
            as directory
              /Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/vega-lite/node_modules/vega doesn't exist
            as directory
              /Users/USER/anaconda3/share/jupyter/lab/staging/node_modules/vega doesn't exist
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jasongrout** [comment] 2019-05-08 21:47
Is this fixed with the recent vega upgrade? https://github.com/jupyterlab/jupyterlab/pull/6294

**Comment by saulshanabrook** [comment] 2019-05-15 18:13
Yeah I cannot reproduce this on master or on the latest alpha release.

**Comment by jasongrout** [comment] 2019-12-02 17:37
Closing as resolved. Please post here if this is still an issue. Thanks @saulshanabrook for checking on this!

**Closed by jasongrout** 2019-12-02 17:37 UTC
Labels: pkg:vega, status:Needs Info
