### ISSUE TITLE
Erratic scroll jumps when performing actions in notebook

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#15693] opened 2024-01-25 07:46 UTC
## Description

Hi, I've experienced some erratic jumps when doing some actions on a notebook (eg. re-running cells). Here's a GIF - 

![scroll_jump](https://github.com/jupyterlab/jupyterlab/assets/30082866/9995ad6c-bd98-4cd5-a154-dd2a6f671fb8)

FTR, the windowing mode is set to the default which is `defer`.

The jumps probably feel more erratic when the height of the cell output changes too drastically between re-runs or when there are too many cells.

## Reproduce

The snippet in the gif is - 

```
import matplotlib.pyplot as plt
from IPython.display import display

for _ in range(4):
    axes = plt.axes()
    axes.plot([1, 2, 3], [4, 5, 6])
    plt.close()
    display(axes.get_figure())
```

## Context

- JupyterLab version: v4.1.0b2

**Comment by krassowski** [comment] 2024-01-25 08:56
Thank you for the report. I believe this is the same issue as https://github.com/jupyterlab/jupyterlab/issues/14878 that was fixed by https://github.com/jupyterlab/jupyterlab/pull/15288 for the `full` windowing mode (confirmed by three users in the linked issue). I think we should apply a similar fix for the `defer` mode.

**Comment by krassowski** [comment] 2024-01-25 15:44
It is slightly different because previously we fixed `Shift + Enter` behaviour, whereas this relates to `Ctrl + Enter` behaviour.

**Closed** 2024-02-01 10:42 UTC
Labels: bug, tag:Regression
