### ISSUE TITLE
Double clicking the filename doesn't open file in Safari

### ISSUE THREAD

**Issue by polakowo** [jupyterlab/jupyterlab#5996] opened 2019-02-16 13:05 UTC
The file only opens when double clicking the area outside of the filename. Is it expected behavior?

**Comment by jasongrout** [comment] 2019-02-16 15:33
I can open a file by double-clicking on the filename in macOS in Firefox using the latest prerelease, jlab 1.0a1. What jlab version, browser and version, and OS are you using? Can you test in the latest prerelease?

**Comment by polakowo** [comment] 2019-02-16 15:38
I have the latest stable release jlab 35.4 installed, Safari Version 12.0.3, OS X 10.14.3. Also checked Chrome, it seems to work there as expected.

**Comment by jasongrout** [comment] 2019-02-16 15:49
Thanks. I can confirm that double-clicking on the actual filename doesn't work for me in Safari in the latest prerelease either, 1.0a1.

**Comment by jasongrout** [comment] 2019-02-16 15:50
Moving to 1.0 since Safari is in our [list of supported browsers](https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html#supported-browsers)

**Comment by jasongrout** [comment] 2019-06-02 02:15
I've been looking into this. Here are some debugging insights:

1. double-clicking on the actual filename span just gives a mousedown/mouseup event, but not a click or double click.
2. Clicking outside the item text span, but inside the li, gives appropriate click/doubleclick events
3. Commenting out the mousedown handler makes click and doubleclick events start working when clicking on the item text in safari

Still investigating...

**Comment by jasongrout** [comment] 2019-06-03 09:22
Latest result: it's this line that is causing the issue, in that things work in Safari if I comment out this single line: https://github.com/jupyterlab/jupyterlab/blob/2a3644a5290b592296516b5a304883ffd373a4c5/packages/filebrowser/src/listing.ts#L1273

**Comment by afshin** [comment] 2019-06-06 14:36
I can reproduce this issue only sporadically. What appears to be happening is that *sometimes* `dblclick` events fire as we would expect. Other times, two `mousedown` events happen in rapid succession *instead* of a `dblclick`. This happens to me a little less than half the time. I am not exactly sure what the cause is yet.

**Comment by jasongrout** [comment] 2019-06-06 14:43
Well, to be fair you'll have two mousedown events no matter what. What seems to be happening is that safari for some reason doesn't issue click or double click events, perhaps because in the update we are messing with the DOM?

**Comment by jasongrout** [comment] 2019-06-06 14:43
+1 to moving this to 1.1 and asking for someone to help with this issue.

**Comment by jasongrout** [comment] 2019-06-07 21:26
Fixed in #6502

**Closed** 2019-06-08 01:37 UTC
Labels: help wanted, pkg:filebrowser

**Comment by daejong123** [comment] 2019-07-12 09:25
How can i overwrite dblclick event in filebrowser's file 
![image](https://user-images.githubusercontent.com/19252403/61117829-01ad6280-a4ca-11e9-942e-526f4c485352.png)

**Comment by jasongrout** [comment] 2019-07-12 10:12
Let's answer this in your other issue: #6809
