### ISSUE TITLE
Save and Export Notebook as ...

### ISSUE THREAD

**Issue by erlebach** [jupyterlab/jupyterlab#11806] opened 2022-01-08 18:50 UTC
## Description

I am running on a Mac, M1 Chip, Big Sur,  OS 11.5.2 ,   with Anaconda 3, and Python 3.8 with Jupyterlab 3.2.6. 
Recently, the File menu item "Save and Export Notebook as ..." does not show any subitems. 
I have not seen this reported, and have no idea how to fix it. Any help would be appreciated. Thanks.

   Gordon

**Comment by krassowski** [comment] 2022-01-08 18:52
Thank you, This sounds like a duplicate of https://github.com/jupyterlab/jupyterlab/issues/11687. Would you mind checking if `nbconvert` is installed in your environment and in which version?

**Comment by krassowski** [comment] 2022-01-26 17:41
Labelling as a duplicate and answered due to lack of response. Please feel free to re-open if the suggestions in the linked issue do not help.

**Comment by erlebach** [comment] 2022-01-30 15:50
Thanks for the reply. I got the menu items back by doing the following: 
sudo chmod -R 777 ~/Library/Jupyter
The fact I had to do that would indicate something wrong with the installation process of nbconvert. I am on a mac.

**Closed** 2022-02-12 01:52 UTC
Labels: bug, status:Duplicate, status:Answered, status:Closing as Answered
