### ISSUE TITLE
Vision for stable platform for long-lived, reproducible Notebooks?

### ISSUE THREAD

**Issue by nealmcb** [jupyterlab/jupyterlab#5576] opened 2018-11-02 15:43 UTC
Forgive me for just noting my deep anxiety that the stability of the Jupyter Notebook world may not be what I had hoped, and how this relates to our core values around reproducibility and the like.

As background, I *highly* suggest watching ["The Mess We're In" by Joe Armstrong](https://youtu.be/lKXe3HUG2l4), about how hard it is these days for even engineers designing computer systems to have a clue how to track down a bug.  For me that bug was [Markdown table alignment stopped working · Issue #3919 · jupyter/notebook](https://github.com/jupyter/notebook/issues/3919). It turns out that the appearance of tables in our foundational document, the notebook, changed in a non-backwards-compatible way, and it was because the project wanted to support a cool new thing called JupyterLab, which I hadn't even even heard of before. But it is "the future", *slated to eventually replace the classic Jupyter Notebook*. But it broke expectations about how to specify alignment of columns in tables.

So I dug in to this new JupyterLab thing, and quickly got terrified by the notion that

> JupyterLab itself is co-developed on top of PhosphorJS, a new Javascript library for building extensible, high-performance, desktop-style web applications.

I'm no Javascript developer, but everything I hear from my developer friends is that the state of churn in frameworks and libraries is way out of control, in line with what Armstrong is talking about.

So I guess I want to know if this new direction for notebooks is really going to allow us to write reproducible scientific reports, in ways that will actually continue to work for decades, and won't rely on the sorts of houses of cards that we seem to all be building.

**Comment by blink1073** [comment] 2018-11-03 19:40
Hi @nealmcb ,

I don't claim to speak for the whole Juptyer team, so here are my thoughts:

The state of JavaScript development is admittedly moving fast.  The technologies that were used to build the original notebook 
(jQuery, require.js, and bower), are being actively left behind.

We strove to embrace the state of the art while building JupyterLab, and were wary of passing fads:

- We are still using the same Jupyter document and message protocols.
- We still use CodeMirror for the text editors.
- term.js was abandoned, but we helped support its replacement, xterm.js, which is also used by VSCode.
- We evaluated a variety of library loading schemes, including RequireJS, SystemJS, and StealJS.  Webpack provides us with the
most flexibility for core maintainers and extension authors.
- We embraced TypeScript as it allowed us to write code that tracks the EMCAScript standards while providing the saftey net of
a compiler and making it far easier to have a self-documented public API, which was lacking in the classic notebook.
- We developed Phosphor as a necessity to provide the scaffolding of our application, after evaluating existing frameworks at the 
time and finding they did not address our design goals.
- We had previously shied away from the use of React as a core technology, because of the toxic patents clause, but have since
embraced it as a way to provide components within the scaffolding that Phosphor provides.

This is a large and complex space, and we are doing our best to provide a seamless transition into the future.

**Comment by jasongrout** [comment] 2018-11-03 22:02
I agree with what @blink1073 said, and I'll add that in lab we took great pains to work with the existing Jupyter notebook and message protocols precisely because backwards compatibility is *very* important to us.

> It turns out that the appearance of tables in our foundational document, the notebook, changed in a non-backwards-compatible way, and it was because the project wanted to support a cool new thing called JupyterLab

Are you saying this because of the question on https://github.com/jupyter/notebook/issues/3919 about why the change happened? As far as I know, the statement is not true (i.e., the notebook did not break backwards compatibility because of jlab). I'm not sure what is going on with table rendering in that issue - perhaps an upgrade in the markdown renderer in notebook broke things, or the library we use to render markdown is using old html that somehow is broken? Not sure, but (a) it shouldn't have anything to do with JupyterLab, and (b) it should be addressed on that issue. 

However, your underlying concern does bring up the larger issue of how Markdown works with the notebook format, though. In general, forward compatibility with Markdown is a weak point in the Jupyter notebook file format, since Markdown is essentially not very well specified, and different implementations do things differently. Already there are many notebook renderers out there that use different Markdown implementations, hopefully only differing on small corner cases. We have a de facto Markdown "standard" which is basically whatever the library we use to render Markdown in the classic Notebook does, but if there is a backwards incompatible change in the library we use to render Markdown, that can break notebooks. There is/was an effort (CommonMark) to formalize the Markdown spec in the broader Markdown community to make it much more robust against corner cases, different implementations, etc. However, we have held back from adopting CommonMark precisely because it is backwards incompatible in small ways with the current implementation.

**Comment by nealmcb** [comment] 2018-12-03 21:19
Thank you all very much for your work, and your responses. They are mostly reassuring. I wonder if the goals for backwards compatibility are documented anywhere.

Last I checked (when I wrote up this issue, and as documented in [Markdown table alignment stopped working · Issue #3919 · jupyter/notebook](https://github.com/jupyter/notebook/issues/3919)) I couldn't find a way to get cells aligned left in Jupyter Notebook, and the way the documentation suggests fails. Is there an approach that works, @ellisonbg? Or is that use case beyond the scope of the supported Markdown functionality? If the latter, can the documentation be changed? Can such documentation be shared between JupyterLab and Jupyter Notebook?

**Comment by ellisonbg** [comment] 2018-12-05 16:17
@nealmcb do you know if this PR fixed the situation in JupyterLab:

https://github.com/jupyterlab/jupyterlab/pull/5301

**Comment by nealmcb** [comment] 2018-12-06 01:02
I haven't tried this at all on JupyterLab, but will when I get more time.

I'm hoping that this fixes it for jupyter notebook: https://github.com/jupyter/notebook/pull/4130 but it seems to be stuck waiting for feedback on a build warning.

**Comment by gravitypersists** [comment] 2019-05-06 22:28
Chiming in here as a dev trying to wrap my head around this beast of a thing - from Backbone.js+require to Phosphor+webpack is not a good look. It shouldn't be about what web framework is popular, it shouldn't be about Typescript or React or whatever is hot at the time of building, which will only cause headache for developers for years to come (also, hello future!).

The issue is that APIs are built into classes and now if anybody wants to do anything special, they need to subclass that original class or create some mediator between a custom class or data structure and it.

Wanna make a dynamic python structure and tie it to an ipywidget? You can't do that. ipywidgets require static declaration, because it subclasses Widget, or whatever, and that has to have these things called traitlets, or whatever, and traitlets need observers to be declared on them using cool `@decorators` that can only be done statically. So no, you can't do that. What do we get instead - monstronsities [like this](https://github.com/jupyter-widgets/ipyleaflet/blob/master/ipyleaflet/leaflet.py) which should be bridgeable super easy, but they aren't.

The docs [here](https://jupyterlab.readthedocs.io/en/stable/developer/notebook.html) have a "simple example" for adding a button to a notebook, basically a "hello world" except it's 70 lines long, it's importing things from `@phosphor` (what even is that? oh, it doesn't even look like it's being [maintained a whole bunch](https://github.com/phosphorjs/phosphor/graphs/contributors)), it's importing things from JupyterLabPlugin, it's importing things from ToolbarButton, it's hacking it all together.

What if, instead, we just got a simple message bus and a dom element to render into? No fuss over UI frameworks, compile-to-JS languages, blah blah blah, and let plugin developers choose those things on their own? Something a little more [future-proof](https://developer.mozilla.org/en-US/docs/Web/Web_Components) and minimal?

**Comment by blink1073** [comment] 2019-05-07 01:10
Closing this as the original question has been answered and I don't want this to become a place to voice complaints about the project.

**Closed by blink1073** 2019-05-07 01:10 UTC
Labels: type:Question

**Comment by jasongrout** [comment] 2019-05-07 03:59
@gravitypersists - I'll just add that some of your ideas sound intriguing (though in this space, please be positive and constructive rather than disparaging the project).

The JLab plugin system was built in part so that people could experiment with such ideas. I think perhaps the next step for you is to write a JLab plugin that implements your ideas. You can use the comm messaging framework to communicate between the kernel and the frontend. Your frontend object can do whatever it wants with its DOM node. I'd love to see what you come up with, and what lessons we learn from the experiment.

**Comment by jasongrout** [comment] 2019-05-07 04:02
I see Steve has closed and locked this issue--it was answered long ago. If you'd like to continue the conversation, please open another (positive, constructively-worded) issue, and we can help you get started in implementing some of your ideas.
