### ISSUE TITLE
"jupyter lab build" failed on windows with encoding GBK

### ISSUE THREAD

**Issue by ankaisen** [jupyterlab/jupyterlab#8600] opened 2020-06-22 19:58 UTC
## Description
A `UnicodeDecodeError` Error occurred when I ran `jupyter lab build` after a fresh install of jupyterlab. I fixed this error by manually adding parameter `encoding='utf-8'` to `self._create_process` (jupyter/commands.py line 88). I'm not sure if this also happens on other non UTF-8 platform, so maybe it's better to do some tests. Debug log attached [jupyterlab-debug-fkhp_5pq.log](https://github.com/jupyterlab/jupyterlab/files/4815341/jupyterlab-debug-fkhp_5pq.log).
## Reproduce
1. Running command "jupyter lab build" after a fresh install (with system encoding GBK )
## Expected behavior
A successful build
## Context
- Operating System and version: Windows 10 19041 (default encoding: GBK)
- Browser and version: Chrome
- JupyterLab version: 2.1.4
<details><summary>Command Line Output</summary>
<pre>
(base) PS D:\Developer> jupyter lab build
[LabBuildApp] JupyterLab 2.1.4
[LabBuildApp] Building in C:\Users\ankaisen\miniconda3\share\jupyter\lab
[LabBuildApp] Building jupyterlab assets (build:dev:minimize)
/Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\Users\ankaisen\miniconda3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\ankaisen\miniconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ankaisen\miniconda3\lib\subprocess.py", line 1267, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 275: illegal multibyte sequence

Build failed.
...
</pre>
</details>

## Solution
Add `encoding='utf-8'` to jupyter/commands.py line 88, in `self._create_process`

**Comment by supercaizehua** [comment] 2020-07-16 11:00
my same problem solved, thanks! @ankaisen

**Comment by agateriver** [comment] 2020-08-29 03:06
Thanks! @ankaisen

**Comment by badiku** [comment] 2020-10-23 01:49
I solved this by adding kwargs['encoding'] = 'utf8' in definition of _create_process 
at site-packages\jupyterlab_server\process.py line 178:
        proc = subprocess.Popen(cmd, **kwargs)

**Comment by jasongrout** [comment] 2020-10-23 02:08
> A `UnicodeDecodeError` Error occurred when I ran `jupyter lab build` after a fresh install of jupyterlab. I fixed this error by manually adding parameter `encoding='utf-8'` to `self._create_process` (jupyter/commands.py line 88). I'm not sure if this also happens on other non UTF-8 platform, so maybe it's better to do some tests.

Could someone submit a PR with this fix? Thanks!

**Comment by devanshgoenka97** [comment] 2020-11-04 17:51
I will be happy to work on this, please assign it to me.

**Comment by blink1073** [comment] 2020-11-04 21:47
> I will be happy to work on this, please assign it to me.

Thanks, done!

**Closed** 2020-11-06 08:35 UTC
Labels: good first issue

**Comment by krassowski** [comment] 2020-12-16 01:59
Heads up (@ianhi?), I had this occur to my extension on 2.2.x line when I added ⌘ to my extension schema file, with an effect of completely blowing up JupyterLab for users on Windows with this specific codec. I cannot reproduce (no Windows at hand) and do not know if the fix herein fixes the schema issue too, so I will just leave this as a comment.

The related log was:

> [W 09:04:29.765 LabApp] Failed parsing schema (@krassowski/jupyterlab-lsp:jump_to): 'gbk' codec can't decode byte 0x98 in position 555: illegal multibyte sequence

**Comment by telamonian** [comment] 2020-12-16 03:25
@krassowski I added a backport PR for the fix. I don't think we're making 2.2.x releases anymore, so you'll still have to upgrade to at least jlab 2.3.x to pick up the fix once the backport gets pulled in and released
