### ISSUE TITLE
Syntax highlighting in dark themes

### ISSUE THREAD

**Issue by dannykliu** [jupyterlab/jupyterlab#14839] opened 2023-07-17 16:43 UTC
So I'm creating a custom theme for jupyterlab 4 but having a problem with syntax highlighting in dark mode. Everything works fine in general but when I try to highlight a block of text in edit mode on any cell the syntax highlighting is white which makes all the code underneath unreadable. I was upgrading an old theme from jupyter 3 and it didn't have this issue even with the same variables.css. Posted this on dev chats and was informed this was a regression and asked to post an issue here. Attached screenshot below.
![image](https://github.com/jupyterlab/jupyterlab/assets/12521399/a3370f82-9852-4ebb-ab38-c3cd52064770)

**Comment by krassowski** [comment] 2023-07-20 16:08
This appears to be a duplicate of https://github.com/jupyterlab/jupyterlab/issues/14737 already fixed on main branch - fix will likely be included in 4.0.4 release.

**Closed** 2023-08-03 01:51 UTC
Labels: bug, status:Duplicate, pkg:codemirror, tag:CSS, status:Answered, status:Closing as Answered, tag:Regression
