### ISSUE TITLE
remark: Jupyterlab-1.2.0rc0 failed to build on Win 10 64bt

### ISSUE THREAD

**Issue by stonebig** [jupyterlab/jupyterlab#7425] opened 2019-10-28 11:08 UTC
error:
````
[LabBuildApp] JupyterLab 1.2.0rc0
[LabBuildApp] Building in C:\WinP\bd37\bu\WPy64-3750b1\python-3.7.5.amd64\share\jupyter\lab
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  C:\Users\helene\AppData\Local\Temp\jupyterlab-debug-28c_6km5.log
JupyterLab v1.2.0rc0
Known labextensions:
   app dir: C:\WinP\bd37\bu\WPy64-3750b1\python-3.7.5.amd64\share\jupyter\lab
        @jupyter-widgets/jupyterlab-manager v1.0.3 enabled  ok
        @jupyterlab/vega3-extension v1.0.0 enabled  ok
        @pyviz/jupyterlab_pyviz v0.8.0 enabled  ok
        bqplot v0.4.9 enabled  ok
        jupyter-leaflet v0.11.4 enabled  ok
        jupyter-matplotlib v0.4.2 enabled  ok
        jupyter-threejs v2.1.1 enabled  ok
        jupyterlab-datawidgets v6.2.0 enabled  ok
        jupyterlab_bokeh v1.0.0 enabled  ok

Build recommended, please run `jupyter lab build`:
    bqplot needs to be included in build
    jupyter-leaflet needs to be included in build
    jupyter-matplotlib needs to be included in build
    jupyter-threejs needs to be included in build
    @jupyter-widgets/jupyterlab-manager needs to be included in build
    jupyterlab-datawidgets needs to be included in build
    jupyterlab_bokeh needs to be included in build
    @pyviz/jupyterlab_pyviz needs to be included in build
    @jupyterlab/vega3-extension needs to be included in build
````

jupyterlab-debug-28c_6km5.log is
````
[LabBuildApp] Building in C:\WinP\bd37\bu\WPy64-3750b1\python-3.7.5.amd64\share\jupyter\lab
[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Node v12.13.0

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node C:\WinP\bd37\bu\WPy64-3750b1\python-3.7.5.amd64\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
warning bqplot > topojson@1.6.27: Use topojson-client, topojson-server or topojson-simplify directly.
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "jupyter-leaflet > leaflet.markercluster@1.4.1" has incorrect peer dependency "leaflet@~1.3.1".
warning "@jupyterlab/vega3-extension > vega-embed > vega-themes@2.5.0" has unmet peer dependency "vega@*".
warning "@jupyterlab/vega3-extension > vega-embed > vega-lite@2.7.0" has unmet peer dependency "vega@^3.0.0 || ^4.0.0".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 193.48s.

[LabBuildApp] > node C:\WinP\bd37\bu\WPy64-3750b1\python-3.7.5.amd64\lib\site-packages\jupyterlab\staging\yarn.js yarn-deduplicate -s fewer
[LabBuildApp] yarn run v1.15.2
$ C:\WinP\bd37\bu\WPy64-3750b1\python-3.7.5.amd64\share\jupyter\lab\staging\node_modules\.bin\yarn-deduplicate -s fewer
Done in 0.81s.

[LabBuildApp] > node C:\WinP\bd37\bu\WPy64-3750b1\python-3.7.5.amd64\lib\site-packages\jupyterlab\staging\yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.15.2
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
child_process.js:642
    throw err;
    ^

Error: spawnSync webpack ENOENT
    at Object.spawnSync (internal/child_process.js:1041:20)
    at spawnSync (child_process.js:607:24)
    at Object.execFileSync (child_process.js:634:15)
    at Object.<anonymous> (C:\WinP\bd37\bu\WPy64-3750b1\python-3.7.5.amd64\share\jupyter\lab\staging\node_modules\@jupyterlab\buildutils\lib\ensure-max-old-space.js:30:17)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawnSync webpack',
  path: 'webpack',
  spawnargs: [ '--config', 'webpack.prod.minimize.config.js' ],
  error: [Circular],
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "C:\WinP\bd37\bu\WPy64-3750b1\python-3.7.5.amd64\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "C:\WinP\bd37\bu\WPy64-3750b1\python-3.7.5.amd64\lib\site-packages\jupyterlab\labapp.py", line 98, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "C:\WinP\bd37\bu\WPy64-3750b1\python-3.7.5.amd64\lib\site-packages\jupyterlab\commands.py", line 459, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "C:\WinP\bd37\bu\WPy64-3750b1\python-3.7.5.amd64\lib\site-packages\jupyterlab\commands.py", line 669, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab
````

### Tools

Name | Version | Description
-----|---------|------------
[Nodejs](https://nodejs.org) | v12.13.0 | a JavaScript runtime built on Chrome's V8 JavaScript engine
[npmjs](https://www.npmjs.com/) | 6.12.0 | a package manager for JavaScript

**Comment by jasongrout** [comment] 2019-10-28 15:00
Thanks for testing the rc!

My first guess, from `Error: spawnSync webpack ENOENT` indicating it couldn't find a file, is that perhaps the `webpack.prod.minimize.config.js` config file is missing somehow? Can you check in the staging directory for that file?

Can you try doing a `jupyter lab clean` to make sure you get a refreshed staging directory?

**Comment by stonebig** [comment] 2019-10-28 17:13
retrying, with pre-clean and a fix to add voila plugin.

**Comment by stonebig** [comment] 2019-10-28 17:33
webpack.prod.minimize.config.js
````
const TerserPlugin = require('terser-webpack-plugin');
var merge = require('webpack-merge');
var config = require('./webpack.config');

config[0] = merge(config[0], {
  mode: 'production',
  devtool: 'source-map',
  optimization: {
    minimizer: [
      new TerserPlugin({
        parallel: true,
        sourceMap: true,
        terserOptions: {
          compress: false,
          ecma: 6,
          mangle: true,
          output: {
            beautify: false,
            comments: false
          },
          safari10: true
        },
        cache: process.platform !== 'win32'
      })
    ]
  }
});

module.exports = config;
````

![image](https://user-images.githubusercontent.com/4312421/67702091-69bc8180-f9b1-11e9-9a37-a342273aaae3.png)

**Comment by jasongrout** [comment] 2019-10-28 19:00
Okay, so it's probably not that particular file it is complaining about. It would be nice to know what file it was trying to access when it gave the ENOENT error.

Googling "Error: spawnSync webpack ENOENT" gives this as one result, which may help you debug where the error is occurring. From these answers, it seems that perhaps it can't find webpack?

https://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js

Can you try looking at some of the suggestions in the link above to narrow down where the ENOENT is coming from?

**Comment by stonebig** [comment] 2019-10-28 19:15
May we beg for a more detailed  error message to upstream  ?

**Comment by ablaagaard** [comment] 2019-10-31 08:45
I have the same (or very similar) problem with 1.2.0 on windows 10.
I can build 1.1.4 in the same environment.

**Comment by Slimsladey2** [comment] 2019-11-04 13:08
I also have the exact same traceback as reported above (minus file directory differences).
I am using Jupyter Lab 1.2.0 on windows 10 64bit.

**Comment by scottwsides** [comment] 2019-11-04 17:58
Just to motivate a fix... I'm having a similar problem on windows when trying to configure ipywidgets for JupyterLab. This first big error I see is a message about the platform 'win32' being incompatible.

Yarn configuration loaded.
Node v10.16.3

> C:\Users\swsides\chemistream\npm.CMD pack @jupyter-widgets/jupyterlab-manager
npm notice
npm notice package: @jupyter-widgets/jupyterlab-manager@1.1.0
npm notice === Tarball Contents ===
npm notice 2.3kB  package.json
npm notice 1.5kB  LICENSE
npm notice 1.9kB  README.md
npm notice 277B   lib/index.d.ts
npm notice 380B   lib/index.js
npm notice 5.9kB  lib/manager.d.ts
npm notice 14.5kB lib/manager.js
npm notice 1.9kB  lib/output.d.ts
npm notice 5.2kB  lib/output.js
npm notice 830B   lib/plugin.d.ts
npm notice 7.8kB  lib/plugin.js
npm notice 956B   lib/renderer.d.ts
npm notice 3.3kB  lib/renderer.js
npm notice 216B   lib/semvercache.d.ts
npm notice 862B   lib/semvercache.js
npm notice 375B   schema/plugin.json
npm notice === Tarball Details ===
npm notice name:          @jupyter-widgets/jupyterlab-manager
npm notice version:       1.1.0
npm notice filename:      jupyter-widgets-jupyterlab-manager-1.1.0.tgz
npm notice package size:  12.2 kB
npm notice unpacked size: 48.3 kB
npm notice shasum:        6196b9e3df314d488180fb5ed3bfb11df2dfdeaf
npm notice integrity:     sha512-2dKdzl43nMvmr[...]53y1/ADuNbzhg==
npm notice total files:   16
npm notice
jupyter-widgets-jupyterlab-manager-1.1.0.tgz

Yarn configuration loaded.
Node v10.16.3

Building jupyterlab assets (build:prod:minimize)
> node C:\Users\swsides\chemistream\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
success Saved lockfile.
Done in 58.10s.

> node C:\Users\swsides\chemistream\lib\site-packages\jupyterlab\staging\yarn.js yarn-deduplicate -s fewer
yarn run v1.15.2
$ C:\Users\swsides\chemistream\share\jupyter\lab\staging\node_modules\.bin\yarn-deduplicate -s fewer
Done in 0.36s.

> node C:\Users\swsides\chemistream\lib\site-packages\jupyterlab\staging\yarn.js run build:prod:minimize
yarn run v1.15.2
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
child_process.js:650
    throw err;
    ^

Error: spawnSync webpack ENOENT
    at Object.spawnSync (internal/child_process.js:1002:20)
    at spawnSync (child_process.js:614:24)
    at Object.execFileSync (child_process.js:642:13)
    at Object.<anonymous> (C:\Users\swsides\chemistream\share\jupyter\lab\staging\node_modules\@jupyterlab\buildutils\lib\ensure-max-old-space.js:30:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "C:\Users\swsides\chemistream\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "C:\Users\swsides\chemistream\lib\site-packages\jupyterlab\labextensions.py", line 105, in start
    command=command, app_options=app_options)

  File "C:\Users\swsides\chemistream\lib\site-packages\jupyterlab\commands.py", line 459, in build
    command=command, clean_staging=clean_staging)

  File "C:\Users\swsides\chemistream\lib\site-packages\jupyterlab\commands.py", line 669, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: jupyter

**Comment by jasongrout** [comment] 2019-11-04 18:53
Thanks. It appears that indeed ` info fsevents@1.2.9: The platform "win32" is incompatible with this module.` seems like the relevant error message. I don't have a win32 box to even try to debug this. 

https://github.com/jupyterlab/jupyterlab/issues/3462 seems relevant?

**Comment by scottwsides** [comment] 2019-11-04 19:07
I don't have a win32 box either. I'm on a 64 bit machine. Not sure why error message mentions win32... I think that's the problem ;-)

**Comment by jasongrout** [comment] 2019-11-04 20:28
Does the discussion at the issue above help?

**Comment by stonebig** [comment] 2019-11-04 21:22
well, I have the fsevent error message since the inception of internet, or at least Jupyterlab, and it never stopped Jupyterlab to build.

**Comment by scottwsides** [comment] 2019-11-04 21:42
My solution is to back up to jupyterlab==1.1.0

**Comment by jasongrout** [comment] 2019-11-04 22:30
> well, I have the fsevent error message since the inception of Internet, or at least of Jupyterlab, and it never prevented Jupyterlab to build on 64 bit.

Ah, good to know. Thanks.

**Comment by owenlamont** [comment] 2019-11-05 12:51
I think I'm getting this same error on Windows 10 with jupyter lab 1.2.1. This is my log:

```
[LabBuildApp] Building in C:\Users\owenr\Miniconda3\envs\notebook\share\jupyter\lab
[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Node v12.12.0

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node C:\Users\owenr\Miniconda3\envs\notebook\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.99s.

[LabBuildApp] > node C:\Users\owenr\Miniconda3\envs\notebook\lib\site-packages\jupyterlab\staging\yarn.js yarn-deduplicate -s fewer
[LabBuildApp] yarn run v1.15.2
$ C:\Users\owenr\Miniconda3\envs\notebook\share\jupyter\lab\staging\node_modules\.bin\yarn-deduplicate -s fewer
Done in 0.70s.

[LabBuildApp] > node C:\Users\owenr\Miniconda3\envs\notebook\lib\site-packages\jupyterlab\staging\yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.15.2
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
child_process.js:642
    throw err;
    ^

Error: spawnSync webpack ENOENT
    at Object.spawnSync (internal/child_process.js:1041:20)
    at spawnSync (child_process.js:607:24)
    at Object.execFileSync (child_process.js:634:15)
    at Object.<anonymous> (C:\Users\owenr\Miniconda3\envs\notebook\share\jupyter\lab\staging\node_modules\@jupyterlab\buildutils\lib\ensure-max-old-space.js:30:17)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawnSync webpack',
  path: 'webpack',
  spawnargs: [ '--config', 'webpack.prod.minimize.config.js' ],
  error: [Circular],
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "C:\Users\owenr\Miniconda3\envs\notebook\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "C:\Users\owenr\Miniconda3\envs\notebook\lib\site-packages\jupyterlab\labapp.py", line 98, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "C:\Users\owenr\Miniconda3\envs\notebook\lib\site-packages\jupyterlab\commands.py", line 459, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "C:\Users\owenr\Miniconda3\envs\notebook\lib\site-packages\jupyterlab\commands.py", line 669, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab
```

Reproduced on a new conda environment (conda create -n new_env python=3.7 jupyterlab nodejs):

```
# Name                    Version                   Build  Channel
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
colorama                  0.4.1                      py_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
importlib_metadata        0.23                     py37_0    conda-forge
ipykernel                 5.1.3            py37h5ca1d4c_0    conda-forge
ipython                   7.9.0            py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.15.1                   py37_0    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
json5                     0.8.5                      py_0    conda-forge
jsonschema                3.1.1                    py37_0    conda-forge
jupyter_client            5.3.3                    py37_1    conda-forge
jupyter_core              4.5.0                      py_0    conda-forge
jupyterlab                1.2.1                      py_0    conda-forge
jupyterlab_server         1.0.6                      py_0    conda-forge
libsodium                 1.0.17               h2fa13f4_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py37hfa6e2cd_0    conda-forge
mistune                   0.8.4           py37hfa6e2cd_1000    conda-forge
more-itertools            7.2.0                      py_0    conda-forge
msys2-conda-epoch         20160418                      1
nbconvert                 5.6.1                    py37_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
nodejs                    12.12.0                       0    conda-forge
notebook                  6.0.1                    py37_0    conda-forge
openssl                   1.1.1c               hfa6e2cd_0    conda-forge
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.5.1                      py_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pip                       19.3.1                   py37_0    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.10                     py_0    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pyrsistent                0.15.5           py37hfa6e2cd_0    conda-forge
python                    3.7.3                h510b542_1    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pywin32                   225              py37hfa6e2cd_0    conda-forge
pywinpty                  0.5.5                 py37_1000    conda-forge
pyzmq                     18.1.0           py37h16f9016_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                41.6.0                   py37_1    conda-forge
six                       1.12.0                py37_1001    conda-forge
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
terminado                 0.8.2                    py37_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tornado                   6.0.3            py37hfa6e2cd_0    conda-forge
traitlets                 4.3.3                    py37_0    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_0
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
wincertstore              0.2                   py37_1003    conda-forge
winpty                    0.4.3                         4    conda-forge
zeromq                    4.3.2                h6538335_2    conda-forge
zipp                      0.6.0                      py_0    conda-forge
```

**Comment by AndrewTsao** [comment] 2019-11-06 03:29
I meet the same problem too.

I run command: `jupyter lab build` failed.

My os is 'Windows Server 2012 R2 Standard'.
output log:
```
[LabBuildApp] Building in c:\programdata\anaconda3\share\jupyter\lab
[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Node v10.16.3

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node c:\programdata\anaconda3\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
success Saved lockfile.
Done in 6.81s.

[LabBuildApp] > node c:\programdata\anaconda3\lib\site-packages\jupyterlab\staging\yarn.js yarn-deduplicate -s fewer
[LabBuildApp] yarn run v1.15.2
$ c:\programdata\anaconda3\share\jupyter\lab\staging\node_modules\.bin\yarn-deduplicate -s fewer
Done in 0.38s.

[LabBuildApp] > node c:\programdata\anaconda3\lib\site-packages\jupyterlab\staging\yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.15.2
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
child_process.js:650
    throw err;
    ^

Error: spawnSync webpack ENOENT
    at Object.spawnSync (internal/child_process.js:1002:20)
    at spawnSync (child_process.js:614:24)
    at Object.execFileSync (child_process.js:642:13)
    at Object.<anonymous> (c:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\buildutils\lib\ensure-max-old-space.js:30:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "c:\programdata\anaconda3\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "c:\programdata\anaconda3\lib\site-packages\jupyterlab\labapp.py", line 98, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "c:\programdata\anaconda3\lib\site-packages\jupyterlab\commands.py", line 459, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "c:\programdata\anaconda3\lib\site-packages\jupyterlab\commands.py", line 669, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab

```

**Comment by n8vm** [comment] 2019-11-06 23:44
I'm getting the same error as the others above, specifically when trying to run `jupyter lab build`. As a result I can't seem to install ipywidgets. 

Not sure if it's related, but I also have been getting the following error with python 3.8 and jupyter:

`
File "C:\Users\natevm\AppData\Local\Programs\Python\Python38\lib\site-packages\jupyter_core\paths.py", line 359, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed while importing win32api: The specified module could not be found.
`

I was able to fix the above by editing paths.py to first import pywintypes before importing win32api, (the solution to which i found from here: https://stackoverflow.com/questions/58631512/pywin32-and-python-3-8-0). But I'm not sure why win32api is needed, since I'm running a 64bit distribution of python38...

**Comment by owenlamont** [comment] 2019-11-07 14:11
Is there anything else that can be done to identify the problem? I had to revert back to version 1.1.4 too. Thanks so much for finding the issue @stonebig - it's frustrating jupyterlab 1.2 was released despite you finding it is apparently broken for Windows users on the release candidate.

**Comment by jasongrout** [comment] 2019-11-07 16:11
I'm trying to reproduce this right now

**Comment by jasongrout** [comment] 2019-11-07 16:26
I'm pretty sure we don't support python 3.8 yet, IIRC.

**Comment by jasongrout** [comment] 2019-11-07 18:53
We've reproduced the error, now we are tracking down what is wrong.

**Comment by jasongrout** [comment] 2019-11-07 22:22
Turns out the problem is that on windows, you need to execute `webpack.cmd`, not `webpack`. Fix coming up.

**Comment by jasongrout** [comment] 2019-11-07 22:32
> it's frustrating jupyterlab 1.2 was released despite you finding it is apparently broken for Windows users on the release candidate.

Agreed. This should have been a blocker for the release. Sorry it slipped through.

**Comment by telamonian** [comment] 2019-11-08 01:30
Wait, so why didn't this show up in our windows CI?

**Closed** 2019-11-08 04:51 UTC

**Comment by owenlamont** [comment] 2019-11-08 13:00
Thanks for fixing the issue @jasongrout Sorry for sounding over entitled - I really like the project and appreciate your effort. Looking forward to trying 1.2 once your fix is released.

**Comment by jasongrout** [comment] 2019-11-08 13:10
> Sorry for sounding over entitled

Apology accepted :).

This really is a major blocking issue, so thanks for helping escalate it.

1.2.2 should be out now on pip and conda-forge with the fix.

**Comment by owenlamont** [comment] 2019-11-08 14:57
Just installed 1.2.2 from conda-forge and it built and ran fine. Thanks again!

**Comment by stonebig** [comment] 2019-11-09 19:34
works indeed better now on 64 bit.
