### ISSUE TITLE
Clicking on shutdown button for a closed notebook reopens the notebook and restarts the kernel

### ISSUE THREAD

**Issue by joonro** [jupyterlab/jupyterlab#5110] opened 2018-08-12 01:53 UTC
I'm on Version 0.33.8. If I close a notebook, and click on `SHUTDOWN` of its kernel in `RUNNING` tab, the lab reopens the notebook and then restarts the kernel. When I `SHUTDOWN` the kernel first and then close the notebook, it works as expected. 

By the way, I think it would be great to have an option where if I close a notebook it automatically shuts down its kernel ... 

Thanks!

**Comment by t-makaro** [comment] 2018-08-12 07:45
Duplicate of #5084 and #5065. Was supposedly fixed in #5067, and backported to 0.33.x in #5068. Which should have been release in 0.33.8? But this bug still occurs for me in 0.33.8 (on windows 10).

**Comment by blink1073** [comment] 2018-08-12 09:53
Confirmed, let's leave this one open.

**Comment by AlbertWigmore** [comment] 2018-08-12 20:38
I had this issue occur when updating from 0.33.4 to 0.33.8, I believe it's due to jupyter lab not rebuilding the react source code for the UI, or perhaps the machine doesn't have node/npm installed to rebuild it.

Running the following command fixed the issue for me:
```
jupyter lab build
```

Ubuntu 16.04
Python 3.5.2
Node 8.11.3
npm 5.6.0

**Comment by blink1073** [comment] 2018-08-13 02:40
Fixed in the 0.33.10 release.

**Closed by blink1073** 2018-08-13 02:40 UTC
Labels: pkg:running, type:Bug
