### ISSUE TITLE
Inconsistency in the toolbar

### ISSUE THREAD

**Issue by djangoliv** [jupyterlab/jupyterlab#15758] opened 2024-02-07 09:47 UTC
## Description

Since jupyterlab 4.1.0, I noticed inconsistencies when adding buttons (with panel.toolbar.insertItem, panel.toolbar.insertAfter and panel.toolbar.inserBefore) in the toolbar.

## Reproduce

Create an extension adding a button with panel.toolbar.insertItem or panel.toolbar.insertAfter in the toolbar and toggle from full screen to half screen, and you will see differences in the order of the buttons.

A more simple example is to install https://github.com/logilab/jupyterlab-friendly-traceback/ which add a button with insert Item here: https://github.com/logilab/jupyterlab-friendly-traceback/blob/f62c03af0355437269559da07ffb8773eb3c7eda/src/index.ts#L68

Before (without jupyterlab-friendly-traceback) :
![before](https://github.com/jupyterlab/jupyterlab/assets/13416971/61b65700-6681-4e89-814e-0ad1d98fcfcb)

After (with jupyterlab-friendly-traceback):
![after](https://github.com/jupyterlab/jupyterlab/assets/13416971/08494037-9c93-46a8-bc29-469630292131)

## Expected behavior

Stability even after adding button with extension.

## Context

Jupyterlab 4.1.0 on firefox 122.0 (64 bits) on debian bookworm with i3.

Thanks and regards

**Comment by JasonWeill** [comment] 2024-02-13 17:12
This looks similar to #15509, which was reported as fixed in 4.1.x, but which seems to be recurring

**Comment by mbektas** [comment] 2024-02-20 22:43
issue probably caused by this [commit](https://github.com/jupyterlab/jupyterlab/commit/7084699339bde3c10567f80601538428e9c5da76#diff-00e4c3dd1d53c87918423484191102bdfda9a86263e410a858ec62b1669bfbe1R431) which defaults to position zero when reference item is not found. It used to return false if not found. Some extensions use this logic to try inserts. for example debugger button may not be available right away and insert is tried with other reference etc. cc. @brichet

**Comment by brichet** [comment] 2024-02-21 16:33
Thanks @djangoliv for opening this issue.
For reference the same issue was already mentioned here https://github.com/jupyterlab/jupyterlab/issues/15676

@mbektas thanks for the link, the issue probably comes from that commit.
I think the order of the items is not properly saved when an item is inserted in the toolbar.
It does not compute the position of the following items, which result in several item with the same position.

**Closed** 2024-03-04 10:49 UTC
Labels: bug
