### ISSUE TITLE
Very Weird and Annoying Behavior of Messing up Pasted Text  in Markdown Mode Editor

### ISSUE THREAD

**Issue by firezym** [jupyterlab/jupyterlab#15624] opened 2024-01-10 09:12 UTC
## Description

When I copy `Ctrl+C` & paste `Ctrl+V` some long text with some markdown formats into the editor in markdown mode , there is a very great chance of messing up the text for display. The executed display and text content in the editor is inconsistant. Also `Ctrl+Z` to reverse editing has a high prob to break. You can see the actual difference if you switch between markdown and code mode. The behavior is very strange and annoying because I rely on the markdown to edit and when this happens, the original text can not be recovered completely.

![markdown-editor-error](https://github.com/jupyterlab/jupyterlab/assets/3654421/fc234a85-b388-4e51-87e6-b82933073fe4)

## Reproduce

Try to copy some long texts (especially markdown texts) into the editor in markdwon mode, as the gif shows. You can copy below texts as the gif:

\```
aaaaaaaaaaaa
bbbbbbbbbbbb
cccccccccccc
dddddddddddd
eeeeeeeeeeee
\```

## Expected behavior

Texts are messed up and can not be recovered. The executed display and text content in the editor is inconsistant. 

## Context

- Operating System and version: Windows 10/11 for Chrome Frontend
- Browser and version: Chrome 120.0.6099.130 and also the latest official version of Chrome.
- JupyterLab version: 4.0.10 via official pip install, Tried Windows and Linux for Backend

```md
jupyter_client            8.6.0
jupyter_core              5.7.1
jupyter-events            0.9.0
jupyter-lsp               2.2.1
jupyter_server            2.12.3
jupyter_server_terminals  0.5.1
jupyterlab                4.0.10
jupyterlab_pygments       0.3.0
jupyterlab_server         2.25.2
```

**Comment by firezym** [comment] 2024-01-12 09:05
To add up, I also tried to copy these test texts from browser/vscode/notepad/word, it all cause the messed up texts. But If I try to copy it from the jupyterlab text editor in markdown/code mode to markdown cell, the texts will be fine.
\```
aaaaaaaaaaaa
bbbbbbbbbbbb
cccccccccccc
dddddddddddd
eeeeeeeeeeee
\```

**Comment by krassowski** [comment] 2024-01-12 12:09
At a quick glance this looks like a duplicate of:
- https://github.com/jupyterlab/jupyterlab/issues/14752

**Comment by firezym** [comment] 2024-01-12 12:15
Yep, it looks related. I have that kind of error too, invisible results for markdown output. But I did not make that error gif.

**Comment by firezym** [comment] 2024-01-12 12:17
I rely a lot on the markdown. But when the markdown is corrupted, I will need to create a new cell. But that will change the unique id of the cell, which I am using it for cross note book refencing. That's why I need the markdown cell to be stable for copy/paste editing...

**Comment by JasonWeill** [comment] 2024-01-23 17:17
Closing as duplicate of #14752; let's keep the conversation going in the older issue. Thanks @firezym !

**Closed by JasonWeill** 2024-01-23 17:17 UTC
Labels: bug, status:Needs Triage
