### ISSUE TITLE
Toolbar button hover state and "mouseDown" state are identical.

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#3] opened 2016-06-04 18:04 UTC
It is confusing.

The "depressed" appearance when hovering is IMHO against most design principle, where depressed means clicked.

**Comment by blink1073** [comment] 2016-06-08 13:26
These we done according to spec: https://github.com/jupyter/design/issues/20#issuecomment-185985799.  @cameronoelsen, thoughts?

**Comment by Carreau** [comment] 2016-06-08 17:19
Well I think that designing in static is one thing (it actually looks great on the PNG), actually trying it I honestly don't see the difference between hover and pressed and I am confused. 

I'm giving first impressions, and I perfectly understand that there is no right or wrong and that : 
  - I can miss a lot of JupyterLab visual language because I'm not used to it
  - You can be so used to the various design that you become blind to major issues.
  - Anything in between

I think the spec might have to be revised a bit to get a stronger distinction, or maybe the spec is not correctly implemented, or there is a bug somewhere else ?

**Comment by cameronoelsen** [comment] 2016-06-09 22:39
![file browser](https://cloud.githubusercontent.com/assets/6437976/15948723/460f70b8-2e57-11e6-8db8-9e3315bef841.png)

@Carreau & @blink1073: We are most likely going to change the styling of those action buttons and will be getting rid of the refresh button since the file browser does it itself. For the new design (as seen above) the buttons have been changed to the color of the background of the file browser (#FAFAFA). I am thinking that for these new buttons, since the color is so close to white, we will only have a pressed state.

If we were going to stick with the current action buttons, we could definitely need something else added to make it more distinct. Maybe something like a slight internal drop shadow for the pressed state kinda like what GitHub does:

![giphy](https://cloud.githubusercontent.com/assets/6437976/15948903/59ec4696-2e58-11e6-9f32-340f5c056121.gif)

**Comment by ellisonbg** [comment] 2016-08-23 19:36
I will do some research...

**Comment by AbdealiJK** [comment] 2016-08-27 05:34
I believe I know why this is happening.
The issue is that the CSS `.jp-NBToolbar-button:hover` is taking more precedence than `.jp-NBToolbar-button.jp-mod-pressed`. So, when you're clicking on something, you're also hovering on the DOM element, the color of the :hover is being shown always even while clicking

**Comment by AbdealiJK** [comment] 2016-08-27 05:37
Here's an example that shows this:
I've manually added the .jp-mod-pressed to the "refresh" button as comparison and I'm clicking on the "run" button

![screenshot from 2016-08-27 11-01-57](https://cloud.githubusercontent.com/assets/2200743/18025413/619266e2-6c46-11e6-9b45-e00537abaca7.png)

**Comment by ellisonbg** [comment] 2017-02-07 19:28
@cameronoelsen can you check this to see how our current buttons are behaving?

**Comment by ellisonbg** [comment] 2017-07-06 00:35
Fixed in master!

**Closed by ellisonbg** 2017-07-06 00:35 UTC
Labels: pkg:notebook, tag:Design and UX, type:Bug
