### ISSUE TITLE
Dark theme text editor uses light theme styling

### ISSUE THREAD

**Issue by stephanie-howson** [jupyterlab/jupyterlab#4866] opened 2018-07-10 15:33 UTC
Dark theme text editor should follow with rest of dark theme style (uses entire light theme styling). See image:
<img width="492" alt="screen shot 2018-07-10 at 10 43 43 am" src="https://user-images.githubusercontent.com/41071250/42521321-254e36a0-842e-11e8-898b-57e5a9837496.png">

**Comment by ian-r-rose** [comment] 2018-07-10 15:45
Was this also fixed by a rebuild, as per #4865?

**Comment by stephanie-howson** [comment] 2018-07-10 15:47
No - I updated this issue after rebuild, this is the view I have after rebuilding.

**Comment by ian-r-rose** [comment] 2018-07-10 15:50
What text editor theme are you using (from the settings menu)? The `jupyter` theme is the one that is set up to use the theme CSS variables.

**Comment by stephanie-howson** [comment] 2018-07-10 15:52
I was using default - maybe that should inherit the change to the jupyter lab theme?

**Comment by ian-r-rose** [comment] 2018-07-10 15:54
I think this is the intended behavior. CodeMirror comes with a bunch of editor themes which are largely independent of the overall JupyterLab theme. We've exposed a setting for those in case users want them, but they are not really aware of the outside theme environment.

**Comment by ian-r-rose** [comment] 2018-07-10 15:55
I agree this is a confusing state, do you have any suggestion as to how we could improve the UI or documentation here?

**Comment by stephanie-howson** [comment] 2018-07-10 15:59
I guess my only suggestion would be to change the wording of "default" - seems counterintuitive.

**Comment by ian-r-rose** [comment] 2018-07-10 16:00
That makes good sense. Perhaps we could call it the `codemirror` theme, since it is the default theme for CodeMirror?

**Comment by stephanie-howson** [comment] 2018-07-10 16:01
Like it - sounds good to me!

**Comment by ian-r-rose** [comment] 2018-07-10 16:22
Tagging as a "good first issue"

**Comment by ian-r-rose** [comment] 2018-12-04 19:38
Fixed by #5638. Thanks @joker2600!

**Closed by ian-r-rose** 2018-12-04 19:38 UTC
Labels: good first issue, pkg:codemirror
