### ISSUE TITLE
svg images do not print

### ISSUE THREAD

**Issue by callegar** [jupyterlab/jupyterlab#13071] opened 2022-09-09 10:47 UTC
## Description

If you use something like `matplotlib_inline.backend_inline.set_matplotlib_formats('svg')` then matplotlib produces images in the svg format. In many situations this is a good thing with respect to the image quality.

However, if you have this kind of images in the notebook, then *File->Print* results in a preview and in printouts where the svg images are not visible.

## Reproduce

1. Create a cell with
    ```python
    from matplotlib import pyplot as plt
    import matplotlib_inline
    matplotlib_inline.backend_inline.set_matplotlib_formats('svg')
   ```
    and evaluate it

2. Create a cell with
    ```python
    plt.plot([0,0],[1,1])
    ```
    and evaluate it

3. Use *File->Print* from the menu

## Expected behavior

You should see a plot after point 2. above and then a preview including that plot at point 3.  Conversely, in the preview there is no plot.

## Context

- Operating System and version: Manjaro and Ubuntu 22.04
- Browser and version: Firefox 103 and Chromium 104
- JupyterLab version: 3.4.6

**Comment by jweill-aws** [comment] 2022-09-15 17:15
We can reproduce this with Firefox on macOS on 3.4.x and 4.x (tip of `master`).

**Comment by jweill-aws** [comment] 2022-09-15 17:41
Resolving this in favor of https://github.com/jupyter/nbconvert/issues/1863. This came up in notebook as well (https://github.com/jupyter/notebook/issues/6541) so I think the root cause is in nbconvert. Thank you for filing the nbconvert issue as well!

**Closed by jweill-aws** 2022-09-15 17:41 UTC
Labels: bug
