### ISSUE TITLE
JN7 Regression: File browser should show as many parent folders as long as there is space instead of just two

### ISSUE THREAD

**Issue by burnpanck** [jupyterlab/jupyterlab#15044] opened 2023-08-30 06:28 UTC
The file browser unnecessarily collapses the parents of the current view very early, showing only the two deepest folders. This is even more so an issue in the notebook, where there is lot's of screen real-estate. It is one of the things that were "better" in JN6, and contributes to the feeling that JN7 is a significant step back in usability.

In Jupyter Notebook 7:
<img width="1226" alt="Screenshot 2023-08-30 at 08 10 50" src="https://github.com/jupyterlab/jupyterlab/assets/1310437/d85480cd-f3fc-400f-8de4-207c9e5704f8">

In Jupyter Lab:
<img width="821" alt="Screenshot 2023-08-30 at 08 13 57" src="https://github.com/jupyterlab/jupyterlab/assets/1310437/d84d3f5b-bf4c-46ef-a3eb-3e6e4c67f7b0">

This is obviously not a super-important issue, it just wanted to note it down somewhere. I hope it doesn't create undue triage effort.

**Comment by krassowski** [comment] 2023-08-30 13:16
This appears to be a duplicate of https://github.com/jupyterlab/jupyterlab/issues/13770, for which there is a PR open already: https://github.com/jupyterlab/jupyterlab/pull/14866. Feel welcome to help reviewing the PR.

**Closed** 2023-09-05 16:11 UTC
Labels: status:Duplicate, enhancement, pkg:filebrowser, status:Needs Triage
