### ISSUE TITLE
"CLEAR WORKSPACE" is white in white background

### ISSUE THREAD

**Issue by hainm** [jupyterlab/jupyterlab#4220] opened 2018-03-22 00:00 UTC
Hi,

I am using the lab's latest release. I can only see the words if selecting the text, otherwise, they are white in white background.

<img width="827" alt="screen shot 2018-03-21 at 7 59 01 pm" src="https://user-images.githubusercontent.com/4451957/37743843-80627ecc-2d42-11e8-844b-535c9ca9e2fd.png">

**Comment by jasongrout** [comment] 2018-03-22 00:24
Just to make sure - can you try in incognito/Private mode to make sure it's not a caching issue?

**Comment by hainm** [comment] 2018-03-22 03:26
hi, still the same issue.

<img width="1274" alt="screen shot 2018-03-21 at 11 25 27 pm" src="https://user-images.githubusercontent.com/4451957/37749634-3b0c3440-2d5f-11e8-85f4-33b2ffe2f72c.png">

**Comment by jasongrout** [comment] 2018-03-22 05:18
It looks like it has the same error as in #4204. What happens if you uninstall the extension so the error is gone?

**Comment by jasongrout** [comment] 2018-03-22 05:36
Technical notes: 

I reproduced this by setting a breakpoint in the code that shows the dialog, and setting the dialog timeout for something really short (100ms). Basically, what is going on here is that the error button is supposed to be styled with:

```css

button.jp-mod-styled.jp-mod-warn {
    background: var(--jp-error-color1);
    color: white;
    border: 1px solid var(--jp-error-color1);
}
```
However, it looks like the light theme is not loaded, so that css variable is not defined.

I think the splash page and things like this error box should somehow have some default styling loaded immediately. Perhaps we can define at least this variable with some reasonable default, which the theme overrides later.

Thanks @hainm for bringing this up!

**Comment by jasongrout** [comment] 2018-03-22 05:36
CC @afshin, who I believe worked on this part of the codebase.

**Comment by jasongrout** [comment] 2018-06-27 17:02
Fixed by @afshin's recent work.

**Closed by jasongrout** 2018-06-27 17:02 UTC
Labels: tag:Backwards compatible
