### ISSUE TITLE
Links in dialogs are not visually distinct

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10837] opened 2021-08-15 16:30 UTC
Looking into #10836 remained me that the links in popup dialogs are not visually distinct:

![Screenshot from 2021-08-15 17-13-28](https://user-images.githubusercontent.com/5832902/129485059-a49fc82c-888e-42cf-8919-5ac9245673d1.png)

"the the Jupyter security documentation" is a link.

Should we change the colours of links and maybe add some other visual indicators?

Here is another example of how a link in a popup is displayed, but with the text equal to the URL:

![Screenshot from 2021-08-15 17-16-13](https://user-images.githubusercontent.com/5832902/129485142-215816f1-c507-4fce-abd2-0e4330b04763.png).

By the way I think that we should avoid using URLs as the text of a link as this might be annoying for screen readers.

_Originally posted by @krassowski in https://github.com/jupyterlab/jupyterlab/issues/10836#issuecomment-899075385_

**Comment by jweill-aws** [comment] 2022-01-06 18:58
Call me old-school, but I still prefer having links be a different color and underlined to emphasize that they are present in hypertext.

**Comment by jweill-aws** [comment] 2022-01-11 22:49
This is what the dialog would look like with link styling overrides removed.
![image](https://user-images.githubusercontent.com/93281816/149033690-4cca2971-3e5e-421f-bf26-ead75133bf78.png)

**Comment by jweill-aws** [comment] 2022-01-11 22:51
Incidentally, the message says "Selecting **trust** will …" (emphasis added) but the action button in the dialog reads "Ok".

**Comment by Jessie-Newman** [comment] 2022-05-02 16:28
Looks like this was fixed in https://github.com/jupyterlab/jupyterlab/pull/11827

**Comment by jasongrout** [comment] 2022-05-02 16:29
Awesome, confirmed. Thanks for linking the PR!

**Closed by jasongrout** 2022-05-02 16:29 UTC
Labels: bug, help wanted, good first issue
