### ISSUE TITLE
Error executing Jupyter command 'lab': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by sanjivsoni17** [jupyterlab/jupyterlab#3921] opened 2018-02-21 06:11 UTC
I have installed jupyter lab using `$pip install jupyterlab` command. After running `$jupyter lab` I am getting this error `Error executing Jupyter command 'lab': [Errno 2] No such file or directory`. 

It seems jupyterlab is installed but the path is not linked. Any pointers on what to do ?

`pip show jupyterlab`
Name: jupyterlab
Version: 0.31.8
Summary: The JupyterLab notebook server extension.
Home-page: http://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.com
License: BSD
Location: /Library/Python/2.7/site-packages
Requires: futures, notebook, jupyterlab-launcher, subprocess32, ipython-genutils

**Comment by blink1073** [comment] 2018-02-21 16:24
Hi @sanjivsoni17, what does `which jupyter` show?  Also, does `jupyter-lab` work (with a hyphen).

**Comment by sanjivsoni17** [comment] 2018-02-22 04:58
Hey @blink1073, thanks for responding. This is what the output of which is.

$which jupyter - /usr/local/bin/jupyter
$ jupyter-lab - zsh: command not found: jupyter-lab

**Comment by vidartf** [comment] 2018-02-22 09:04
What does `which pip` show?

**Comment by sanjivsoni17** [comment] 2018-02-23 11:30
`which pip` - /usr/local/bin/pip

**Comment by blink1073** [comment] 2018-02-26 19:57
I'm not sure why it would install but not add the script.  Can you please try `pip uninstall -y jupyterlab && pip install jupyterlab`?

**Comment by sanjivsoni** [comment] 2018-02-27 05:10
I could make to work in virtual env.

**Comment by HardoScherz** [comment] 2018-03-07 09:31
Thank you @blink1073. On my Computer helped:
> sudo -H pip3 uninstall -y jupyterlab && sudo -H pip3 install jupyterlab

**Comment by garciparedes** [comment] 2018-04-30 13:58
Hi! I'm getting the same error. I reinstalled `jupyterlab` of many ways and the problem continues. Can anybody help me? I think the problem is that `jupyterlab` isn't registering the `jupyter lab`command or something like that because when I perform `jupyter serverextension list` `jupyterlab`appears as enabled.

**Comment by zzploveyou** [comment] 2018-08-29 02:04
`jupyter-lab` can work in my enviroment. But it failed to start when using supervisor.

Strange problem.

I soved it by using absolute exec path.
`/home/user/.local/bin/jupyter-lab`

**Comment by danbri** [comment] 2018-09-05 11:35
FWIW I ran into this error after adding '--user' to address permissions problem installing globally. Running 

> ./.local/bin/jupyter-labhub

... seems to work

**Comment by andrejberg** [comment] 2018-11-12 21:52
I had the problem after installation with pip. Solved it by adding 
`/home/username/.local/bin`
to PATH.

**Comment by otayeby** [comment] 2019-01-28 04:38
> Thank you @blink1073. On my Computer helped:
> 
> > sudo -H pip3 uninstall -y jupyterlab && sudo -H pip3 install jupyterlab

Nice tip! It didn't work without the home (-H) flag, thanks!
Now I can see jupyter installed on Mac under `/usr/local/bin/`

**Comment by CreationTribe** [comment] 2019-07-14 07:50
> I had the problem after installation with pip. Solved it by adding
> `/home/username/.local/bin`
> to PATH.

Perfect, thank you. That fixed mine as well.

**Comment by lydnguyen** [comment] 2019-09-30 21:37
> I had the problem after installation with pip. Solved it by adding
> `/home/username/.local/bin`
> to PATH.

I opened the bash file by typing this line in terminal:
`gedit ~/.bashrc`
and added at the end of the file:
`PATH=$PATH:home/username/.local/bin`
This makes sure that the path is added permanently in the variable $PATH.
Afterward, I can just open Jupyterlab by command line:
`jupyter-lab`

**Comment by jasongrout** [comment] 2019-09-30 21:55
Thanks everyone for sharing how you resolved this. Closing as answered.

**Closed by jasongrout** 2019-09-30 21:55 UTC
Labels: tag:Build System, type:Question
