### ISSUE TITLE
Println in a for loop of Julia 0.5 does not work

### ISSUE THREAD

**Issue by arsenal9971** [jupyterlab/jupyterlab#1751] opened 2017-02-20 15:41 UTC
When I am trying to run in a notebook with kernel Julia 0.5, inside Jupyter Lab and try to run a loop to print the iterators I got an error saying that a for loop needs an end, which I actually put, here the screenshot
![bug_println](https://cloud.githubusercontent.com/assets/9786736/23131716/6632a13c-f78b-11e6-9df6-4239dd90366b.png)

**Comment by jasongrout** [comment] 2017-02-20 20:09
This seems to work fine for me:
<img width="505" alt="screen shot 2017-02-20 at 3 08 30 pm" src="https://cloud.githubusercontent.com/assets/192614/23140251/7e683b0c-f77e-11e6-8221-24c4e4a889c5.png">

Just to double-check - does it work from the Julia Console in Lab for you?

**Comment by blink1073** [comment] 2017-02-20 22:39
Working for me as well.  @arsenal9971, can you also give your JupyterLab version (found in Help -> About), your OS and browser?

<image src="https://cloud.githubusercontent.com/assets/2096628/23144110/094edb52-f78b-11e6-9bf5-43fad3220889.png" width=400>

**Comment by arsenal9971** [comment] 2017-02-21 09:00
My version is 0.15.1, I've seen that you already released 0.16, will try with that version

**Comment by arsenal9971** [comment] 2017-02-22 14:08
I already updated to released 0.16 and I still have the same problem, I also noticed that error happens just when is the first cell where you are running the loop, if I run the same code in a new cell on the same notebook, it works just fine. I attached a screenshot

<img width="1280" alt="screen shot 2017-02-20 at 4 23 30 pm 2" src="https://cloud.githubusercontent.com/assets/9786736/23214879/a7df30d8-f910-11e6-8d54-091f5a921e20.png">

**Comment by blink1073** [comment] 2017-02-22 16:30
Hi @arsenal9971, I am still unable to reproduce.  What is the output of `jupyter notebook --version`, and which Operating System are you using?

**Comment by arsenal9971** [comment] 2017-02-22 20:25
4.4.1, I am using OSX Yosemite

**Comment by blink1073** [comment] 2017-02-22 20:36
I am using 4.4.1 on OSX Sierra.  To be clear, this happens if you open a new notebook with the Julia kernel, type in that first cell, and execute it?

**Comment by arsenal9971** [comment] 2017-02-23 10:41
Yes exactly,  @dpsanders has the same bug.

**Comment by blink1073** [comment] 2017-02-23 11:41
@arsenal9971, do you see the same behavior in the classic notebook?

**Comment by arsenal9971** [comment] 2017-02-23 11:49
No, in the notebook the loop works even in the first cell

**Comment by blink1073** [comment] 2017-02-23 12:21
Debugging time ;).

- Open the `main.bundle.js` source file in your browser.
- Search for "DefaultKernel.prototype.requestExecute"
- Set the debug point below
- Run that first cell
- Inspect the `content` variable.  For me, the `code` is `"for i = 1:10↵    println(i)↵end"`


![image](https://cloud.githubusercontent.com/assets/2096628/23258922/276e77a8-f990-11e6-9078-72de3a1193c2.png)

**Comment by arsenal9971** [comment] 2017-02-24 14:23
Hey @blink1073 I already did that and this is the screenshot
<img width="643" alt="screen shot 2017-02-24 at 3 22 00 pm" src="https://cloud.githubusercontent.com/assets/9786736/23306747/1591e6d0-faa5-11e6-893d-a35edd12ecce.png">
 It looks that somehow is not including the ```end``` but it has a ```en``` instead.

**Comment by blink1073** [comment] 2017-02-24 17:23
Ah, I think this may be addressed by https://github.com/jupyterlab/jupyterlab/pull/1791.

**Comment by blink1073** [comment] 2017-03-01 20:02
@arsenal9971, do you mind seeing if upgrading to JupyterLab 0.17 fixes this?

**Comment by arsenal9971** [comment] 2017-03-01 21:00
THank you very much

**Comment by blink1073** [comment] 2017-03-01 21:01
It works?

**Comment by arsenal9971** [comment] 2017-03-01 21:08
Yes, thank you very much

**Comment by blink1073** [comment] 2017-03-01 21:09
Great!

**Closed by blink1073** 2017-03-01 21:09 UTC
Labels: component:Notebook, status:Needs Info
