### ISSUE TITLE
clearIcon fails to display

### ISSUE THREAD

**Issue by dian533** [jupyterlab/jupyterlab#16781] opened 2024-09-16 05:15 UTC
## Description
When there are two clearIcon from @jupyterlab/ui-components in the file and the first icon is hidden, the other icon fails to display correctly, as shown in the image:
![image](https://github.com/user-attachments/assets/8a81a832-22ea-4095-b117-9269bc4248c3)

The SVG icon depicted is duplicated from the clearIcon within the @jupyterlab/ui-components.

## Expected behavior
![image](https://github.com/user-attachments/assets/c3f19132-0779-4910-8c0b-79015b2634d4)

**Comment by krassowski** [comment] 2024-09-16 09:57
How can we reproduce this?

**Comment by dian533** [comment] 2024-09-20 10:43
> How can we reproduce this?

The following code can be reproduced:
```JSX
import React, { JSX } from 'react';
import { ReactWidget, clearIcon } from '@jupyterlab/ui-components';

export class ClearIconTest extends ReactWidget {
  protected render(): JSX.Element {
    return (
      <span>
        <span style={{ display: 'none' }}>
          <clearIcon.react />
        </span>
        <span>
          <clearIcon.react />
        </span>
      </span>
    );
  }
}
```

**Comment by JasonWeill** [comment] 2024-09-24 16:19
@dian533 Does this happen only with the clearIcon, or with any other icons in this component? I'm surprised by the icon's appearance, since the SVG you're seeing doesn't suggest the 🚫 style of what you'd expect.

Which version of the JupyterLab UI components module are you using?

**Comment by JasonWeill** [comment] 2024-10-08 16:10
We haven't received updates regarding this issue, so in light of the changes made in #16678, I'm going to close it. Please reopen this issue or open a new issue if you find a problem with this icon in the 4.3 beta.

**Closed by JasonWeill** 2024-10-08 16:10 UTC
Labels: bug, status:Needs Info, status:Needs Triage
