### ISSUE TITLE
404 GET /src/css and src/resources error in browser

### ISSUE THREAD

**Issue by kanekalla** [jupyterlab/jupyterlab#6806] opened 2019-07-12 03:10 UTC
Hello ,

I am getting the following error in the terminal and when i use any other tab apart from my jupuyter lab tab, I need to refresh the tab and am loosing some information while refreshing 

Error observed in terminal:

`404 GET /src/css/common.css (::1) 36.18ms referer=http://localhost:8888/lab
[W 22:05:37.208 LabApp] 404 GET /src/resources/graph.txt (::1) 1.15ms referer=http://localhost:8888/lab
[W 22:05:37.217 LabApp] 404 GET /src/resources/editor.txt (::1) 1.12ms referer=http://localhost:8888/lab`

**Comment by kanekalla** [comment] 2019-07-13 14:57
I also did try to use nteract instead of jupyterlab but even then, it's blanking out after some time

**Comment by LukaPitamic** [comment] 2019-08-01 11:51
I'm having same problem :(
![image](https://user-images.githubusercontent.com/34914144/62291166-bba54800-b452-11e9-858e-0802249e8ef2.png)

**Comment by komjum6** [comment] 2019-08-18 20:05
![image](https://user-images.githubusercontent.com/6501519/63229753-27820180-c204-11e9-9e44-4554103317cd.png)
The same problem here.

**Comment by vidartf** [comment] 2019-08-21 10:12
Do you have any lab extensions (`jupyter labextension list`), or is this with vanilla jupyterlab?

**Comment by kanekalla** [comment] 2019-08-22 20:15
I do have lab extensions, 
JupyterLab v1.0.6
Known labextensions:
   app dir: /usr/local/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.0.1  enabled  OK
        @jupyterlab/git v0.7.0  enabled  OK
        @jupyterlab/github v1.0.0  enabled  OK
        @jupyterlab/plotly-extension v0.18.1  enabled  OK
        @jupyterlab/toc v1.0.1  enabled  OK
        bqplot v0.4.2  enabled  OK
        jupyterlab-chart-editor v1.0.0  enabled  OK
        jupyterlab-drawio v0.6.0  enabled  OK
        jupyterlab-jupytext v0.1.0  enabled  OK
        jupyterlab-spreadsheet v0.1.0  enabled  OK
        qgrid v1.1.1  enabled  OK

**Comment by telamonian** [comment] 2019-08-22 20:30
Have you tried a clean build of the `lab` application resources?

```bash
jupyter lab clean
jupyter lab build
```

**Comment by jasongrout** [comment] 2019-08-22 21:30
I would also suggest going through the diagnosis guide at https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html

**Comment by kanekalla** [comment] 2019-08-23 01:25
Yes @telamonian, I did try cleaning and rebuilding it , it still gives the same error in terminal 
[E 20:11:37.564 LabApp] Could not open static file ''
[W 20:11:37.568 LabApp] 404 GET /src/css/common.css (::1) 40.26ms referer=http://localhost:8888/lab
[W 20:11:37.570 LabApp] 404 GET /src/resources/graph.txt (::1) 1.26ms referer=http://localhost:8888/lab
[W 20:11:37.578 LabApp] 404 GET /src/resources/editor.txt (::1) 2.39ms referer=http://localhost:8888/lab
[I 20:11:40.319 LabApp] Build is up to date

Moreover, when I change my tab from jupyter lab to any other tab its going blank and I need to reload the jupyter browser.

**Comment by Lips7** [comment] 2019-08-29 03:29
same here
[W 11:27:02.622 LabApp] 404 GET /src/css/common.css (::1) 34.71ms referer=http://localhost:8888/lab?
[W 11:27:02.626 LabApp] 404 GET /src/resources/graph.txt (::1) 2.56ms referer=http://localhost:8888/lab?
[W 11:27:02.638 LabApp] 404 GET /src/resources/editor.txt (::1) 1.38ms referer=http://localhost:8888/lab?
[W 11:27:03.766 LabApp] 404 GET /jupyterlab_code_formatter/formatters?1567049223674 (::1) 156.06ms referer=http://localhost:8888/lab?

**Comment by chengyumeng** [comment] 2019-08-29 03:48
me too!

**Comment by jasongrout** [comment] 2019-08-29 04:04
For those having this problem, can you go through the diagnosis guide at https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html to try to narrow down where the problem might be and get more specific information to reproduce the issue?

**Comment by mashaojing** [comment] 2019-08-30 06:24
I get the same error after I install three extensions named jupyterlab-go-to-definition ,  Jupyterlab-drawio , Jupyterlab_voyager , then I restart my Jupiter lab.

**Comment by jasongrout** [comment] 2019-08-30 17:33
@mashaojing - can you go through the diagnosis guide at https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html to try to narrow down where the problem might be?

**Comment by jasongrout** [comment] 2019-08-30 17:40
The question here is who is requesting these three files. It most likely isn't JupyterLab. It looks like jupyterlab-drawio is in common between the two people that listed their extensions. Can someone verify it is that extension? If it is, please file an issue with that extension: https://github.com/QuantStack/jupyterlab-drawio/

**Comment by jasongrout** [comment] 2019-08-30 17:45
I just verified that I get

```
[W 10:39:19.252 LabApp] 404 GET /src/css/common.css (::1) 43.88ms referer=http://localhost:8888/lab
[W 10:39:19.255 LabApp] 404 GET /src/resources/graph.txt (::1) 2.11ms referer=http://localhost:8888/lab
[W 10:39:19.277 LabApp] 404 GET /src/resources/editor.txt (::1) 2.02ms referer=http://localhost:8888/lab
```
with JupyterLab 1.1.1 in a clean conda environment with just jupyterlab-drawio installed, and I don't get those errors when I `jupyter labextension disable jupyterlab-drawio`. It looks like these errors come from jupyterlab-drawio. I opened https://github.com/QuantStack/jupyterlab-drawio/issues/44. I'll close this issue and let's continue the conversation over there since it doesn't appear to be a jupyterlab issue.

**Closed by jasongrout** 2019-08-30 17:45 UTC

**Comment by LukaPitamic** [comment] 2019-09-01 16:54
@jasongrout you are absolutely right, Drawio is to blame. I disabled the extension and all errors gone away. Thank you very much, you are awesome by the way!
