### ISSUE TITLE
Wrong with the "ctrl+v" keyboard shortcut for paste 

### ISSUE THREAD

**Issue by yydxlv** [jupyterlab/jupyterlab#16851] opened 2024-10-10 05:46 UTC
When i paste the copied text on the cell, the pasted results is wrong in the lastest jupyter Lab version

For example , 
After copy the text "colqwen2-v0.1",   
I want to use the pasted text to replace the " colpali-v1.2 "  in the code snippets such as
"docs_retrieval_model = RAGMultiModalModel.from_pretrained("vidore/colpali-v1.2")"

![1728538947896](https://github.com/user-attachments/assets/55e17d40-465e-4286-b57c-6486985f8a44)

However, i get the surprising results below,
" docs_retrieval_model docs_retrieval_model docs_retrieval_model docs_retrieval_model = RAGMultiModalModel RAGMultiModalModel RAGMultiModalModel RAGMultiModalModel.from_pretrained("vidore/colqwen2-v0.1")"

![1728539042623](https://github.com/user-attachments/assets/187d5819-1265-4b66-b8db-15f8b688b2bf)

How can i solve the paste (ctrl+v) problem in the jupyter lab cell ?  
thank you.

**Comment by krassowski** [comment] 2024-10-10 09:01
@yydxlv I cannot reproduce this in JupyterLab 4.2.5 which is the latest released JupyterLab version.

Can you please follow the [bug report issue template](https://github.com/jupyterlab/jupyterlab/issues/new?assignees=&labels=bug%2C+status%3ANeeds+Triage&projects=&template=bug_report.md ) and fill in all the information requested?

![cannot-repro2](https://github.com/user-attachments/assets/261550d0-183e-46b2-90b5-66554321388d)

**Comment by yydxlv** [comment] 2024-10-10 09:59
https://github.com/user-attachments/assets/416f7d90-f6eb-401e-acf6-a5f5b0a0bd8e

Thanks very much,  this is the results i conducted in my docker with JupyterLab 4.2.5
 
I am very confused with the cell , 'ctrl+c' and 'ctrl+v'.

**Comment by krassowski** [comment] 2024-10-10 10:06
Can you please follow the [bug report issue template](https://github.com/jupyterlab/jupyterlab/issues/new?assignees=&labels=bug%2C+status%3ANeeds+Triage&projects=&template=bug_report.md) and fill in all the information requested?

**Comment by JasonWeill** [comment] 2024-10-15 16:09
@yydxlv It looks like when you highlight text and press <kbd>CTRL</kbd>+<kbd>C</kbd>, the highlighted text isn't getting copied to the clipboard. Can you paste this text into any other application, such as a GUI text editor? Do you have any keyboard shortcuts in your browser that are bound to this shortcut? Does this happen with other web pages, or with other browsers on your system?

**Comment by JasonWeill** [comment] 2024-10-22 16:11
@yydxlv Can you answer the questions listed above, please? Also, what type of keyboard layout (US English, Chinese, etc) and are you seeing any errors in the Chrome developer tools console?

**Comment by JasonWeill** [comment] 2024-10-29 16:05
@yydxlv We haven't received the requested information. I'm going to close this issue, but if you see any other problems, please reopen this issue or open a new one. Thanks!

**Closed by JasonWeill** 2024-10-29 16:05 UTC
Labels: bug, status:Needs Info, status:Needs Triage
