### ISSUE TITLE
Issue with /lab/tree

### ISSUE THREAD

**Issue by timkpaine** [jupyterlab/jupyterlab#4009] opened 2018-02-26 01:39 UTC
If you have a lot of stuff in the top level, and navigate to /lab/tree/a/sub/directory, the subdirectory loads in the file browser, then it redirects to the top directory. I think this is because the calls are asynchronous, and getting the contents of the subdirectory finishes before the top directory, but the other calls should be ignored if the url is /lab/tree.

**Comment by ian-r-rose** [comment] 2018-02-26 01:45
Thanks for the report @timkpaine. I think you are correct: there is probably a race condition between the restoration of the filebrowser cwd and the `tree` handler.

**Comment by timkpaine** [comment] 2018-02-26 21:57
@ian-r-rose thanks! its especially noticeable for us because the tree handler default path has like 4 items, but the top level has literally 4000, so its like 2 seconds after page load the directory changes.

**Comment by ian-r-rose** [comment] 2018-02-27 18:23
I've been trying to reproduce this with a directory that has 5000 files, and a subdirectory with just one. It seems to be working correctly, as far as I can tell. Is there any other information that you can think of that would be relevant here, @timkpaine?

**Comment by blink1073** [comment] 2018-03-05 15:01
I think this might be addressed by https://github.com/jupyterlab/jupyterlab/pull/3687.

**Comment by jasongrout** [comment] 2018-03-16 04:15
Ping @timkpaine - #3687 is now merged into master. Can you see if this is still an issue with that PR merged?

**Comment by jasongrout** [comment] 2018-03-21 16:37
Closing as resolved. Please add a new comment if we still need to do something or to continue the discussion.

**Comment by timkpaine** [comment] 2018-08-20 14:38
This is still an issue, let me write a script to generate a directory structure to simulate it

**Comment by timkpaine** [comment] 2018-08-21 18:11
here is a repro, it will put you in the wrong folder the first time, correct folders on subsequent calls to /lab/tree/test2

```bash
#!/bin/bash


mkdir test
cd test

echo "c.NotebookApp.default_url = '/login?next=/lab/tree/test2" >>test.cfg


for i in `seq 1 10000`; do
        touch $i.py
done    

mkdir test2
cd test2
touch test.py

cd ../
jupyter lab --config=./test.cfg
```

**Comment by timkpaine** [comment] 2018-08-27 13:55
More info, the initial launcher is in the correct sub directory, it's just the file browser that is wrong

**Comment by ian-r-rose** [comment] 2018-08-27 16:09
@timkpaine I am still having a hard time reproducing this with your script. Can you confirm that it is still an issue with 0.34.3?

**Comment by timkpaine** [comment] 2018-08-27 16:26
yes. I'm poking around in the debugger, it looks like the default file browser created [here](https://github.com/jupyterlab/jupyterlab/blob/master/packages/filebrowser-extension/src/index.ts#L168) doesn't have any of the path information (I.e. /lab/tree/<path>), while by the time you get [here](https://github.com/jupyterlab/jupyterlab/blob/master/packages/filebrowser-extension/src/index.ts#L206) the browser.model now has the path info.

**Comment by timkpaine** [comment] 2018-08-27 16:29
basically, its possible for the browser model's path to not match what it is showing

**Comment by timkpaine** [comment] 2018-08-27 16:59
heres the sequence of the [cd function](https://github.com/jupyterlab/jupyterlab/blob/master/packages/filebrowser/src/model.ts#L241) being called:

- called with '.'
- called with '<my path>'
- hit [here](https://github.com/jupyterlab/jupyterlab/blob/master/packages/filebrowser/src/model.ts#L265) with '<my path>'
- hit there with '.', but oldValue is still equal to ''

**Comment by blink1073** [comment] 2018-08-29 09:07
Fixed by #5224

**Comment by vidartf** [comment] 2019-07-29 16:29
Just tested this locally by adding a delay to the contents API:

```diff
--- a/packages/services/src/contents/index.ts
+++ b/packages/services/src/contents/index.ts
@@ -1022,6 +1022,16 @@ export class Drive implements Contents.IDrive {

     let settings = this.serverSettings;
     return ServerConnection.makeRequest(url, {}, settings)
+      .then(response => {
+        if (!options.content) {
+          return response;
+        }
+        return new Promise<Response>(resolve =>
+          setTimeout(() => {
+            resolve(response);
+          }, 5000)
+        );
+      })
       .then(response => {
         if (response.status !== 200) {
           throw new ServerConnection.ResponseError(response);
```

If I have a session where the file browser is sitting in `subdir/a`, and I then navigating to `/tree/some/path` the following calls are made (according to network tab in chrome devtools):
- `api/contents/?content=1` (root dir)
- `api/contents/subdir/a` (previous session dir)
- `api/contents/some/path?content=0` (URL navigation dir)
- `api/contents/subdir/a?content=1` (previous session dir, dir listing)
- `api/contents/some/path?content=0` (URL navigation dir)
- `api/contents/some/path?content=1` (URL navigation dir, dir listing)

With the above delay, this will take 15s+ to get the dir listing from the URL arg.

**Comment by vidartf** [comment] 2019-07-29 16:32
([where the diff was applied](https://github.com/jupyterlab/jupyterlab/blob/75166c60cd0d0c74045b66de473be6ca39c94a7c/packages/services/src/contents/index.ts#L1024))

**Comment by vidartf** [comment] 2019-07-29 16:44
Ideal resolution:
- When a `tree` URL is given, have the file browser navigate directly there on load (assuming it is a valid path).
- Without a (valid) `tree` URL, have the file browser navigate directly to the previous session dir on load (assuming it is still a valid path).
- Otherwise navigate to server default dir (`/`).

In all cases, there should only be one API call with `content=1`.

**Comment by afshin** [comment] 2019-12-24 00:36
I think the race condition is fixed, but the initial load still happens. I think the file browser may need some refactoring to prevent its initial API request, so while the current fix is an improvement, it's not a complete fix.

I will look at this before 2.0, but it may need to be pushed to a later release.

**Closed** 2020-01-02 15:55 UTC
Labels: pkg:filebrowser, type:Bug
