### ISSUE TITLE
markdown cell: background color not working

### ISSUE THREAD

**Issue by teucer** [jupyterlab/jupyterlab#11558] opened 2021-11-26 13:06 UTC
## Description

Previously we were able to set the background color of a  cell by using the following syntax:

```markdown
<div style="background-color: red">

**hello** world
</div>
```

After the update (v3.2.4) this doesn't seem to work anymore

## Reproduce

See description above

## Expected behavior

The cell should have a background color.

## Context

- Operating System and version: Linux
- Browser and version: Edge 95
- JupyterLab version: 3.2.4

**Comment by krassowski** [comment] 2021-11-26 13:10
Thanks for opening this issue. This is a duplicate of https://github.com/jupyterlab/jupyterlab/issues/11473 - it was already fixed and the fix will be available with the next patch release.

**Comment by teucer** [comment] 2021-11-26 13:14
@krassowski ok thx! do you know when it would be released?

**Closed** 2021-11-26 14:19 UTC
Labels: bug, status:Duplicate, status:Answered

**Comment by krassowski** [comment] 2021-11-26 16:08
I guess that next week as this week was holiday in the US (if you are reading it in the future, [this thread](https://gitter.im/jupyterlab/jupyterlab?at=61a0e06242fc2863b22b5ec7) may have updates).
