### ISSUE TITLE
find replace to support longer string length

### ISSUE THREAD

**Issue by jgunstone** [jupyterlab/jupyterlab#15226] opened 2023-10-05 11:59 UTC
loving the new find replace functionality in jlab>4

### Problem

<img width="358" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/21370980/5e0fbee7-4a3d-486c-90d6-83c4f0d170a6">

the text string box has been shrunk by the additional (awesome!) tool buttons, this makes reading the search string difficult even with relatively short strings.

### Proposed Solution

make the text box wider. even better expand to match the string up to a given max size.

**Comment by krassowski** [comment] 2023-10-05 15:29
> by the additional (awesome!) tool buttons

thank you :green_heart: 

> make the text box wider. even better expand to match the string up to a given max size.

I totally agree. I had created https://github.com/jupyterlab/jupyterlab/issues/15049 before, so this issue is a duplicate. There is a pull request which helps a bit (https://github.com/jupyterlab/jupyterlab/pull/15080) but does not yet implement growing the width itself (just prevents word wrapping). Thank you for explaining your expectation, this helps a lot!

**Comment by JasonWeill** [comment] 2023-10-10 16:11
Closing as duplicate of #15049

**Closed by JasonWeill** 2023-10-10 16:11 UTC
Labels: status:Duplicate, enhancement, tag:Search and Replace, pkg:documentsearch, status:Needs Triage
