### ISSUE TITLE
non-ascii file name not render correctly

### ISSUE THREAD

**Issue by joei1994** [jupyterlab/jupyterlab#6461] opened 2019-06-03 03:28 UTC
I've configured my locale as following
![Screen Shot 2562-06-03 at 10 24 51](https://user-images.githubusercontent.com/11014898/58774036-d9d50000-85e9-11e9-9d78-2fd60ebd6805.png)

and I've written a scrip to create these files with non-ascii string
this is what I see in console 
![Screen Shot 2562-06-03 at 10 14 27](https://user-images.githubusercontent.com/11014898/58773865-fc1a4e00-85e8-11e9-8825-b4c4ec41aeb1.png)
but this is what I get after ls command in terminal
![Screen Shot 2562-06-03 at 10 14 35](https://user-images.githubusercontent.com/11014898/58773904-2704a200-85e9-11e9-80da-a552ab760d0b.png)

also, I can't open these file 
![Screen Shot 2562-06-03 at 10 20 54](https://user-images.githubusercontent.com/11014898/58773989-a1cdbd00-85e9-11e9-8966-573286275c6e.png)

How can I config locale of jupyterlab to support non-ascii string?

**Comment by vidartf** [comment] 2019-06-06 12:38
@joei1994 Just to narrow down where this issue occurs: Does the filename render correctly in the classic notebook tree browser?

**Comment by vidartf** [comment] 2019-06-06 12:39
Also: Could you paste the filename here as text for reproduction?

**Comment by jasongrout** [comment] 2019-09-28 07:12
Closing since there was no follow-up. If you'd like to pursue this further and help us figure out what might be going on, please comment below.

**Closed by jasongrout** 2019-09-28 07:12 UTC
Labels: status:Needs Info
