### ISSUE TITLE
Search in new Settings Editor is broken

### ISSUE THREAD

**Issue by andrii-i** [jupyterlab/jupyterlab#14292] opened 2023-03-30 00:55 UTC
## Description

If you attempt to use search while using new settings editor, it doesn't show any results and shows a bunch of errors

## Reproduce

1. Go to Extension Manager 
2. Try to use search input in the left panel 

![settings_editor_search](https://user-images.githubusercontent.com/26686070/228700453-b283dad5-5c3a-4222-8262-aa57f836d099.gif)

## Expected behavior

Search functionality works if available

**Comment by andrii-i** [comment] 2023-03-30 01:18
This problem is not present in Version 3.6.2

**Comment by krassowski** [comment] 2023-03-30 03:34
Duplicate of #13651 I think.

**Comment by andrii-i** [comment] 2023-03-30 17:28
@krassowski it actually is, I do like the urgency of this issues naming a bit more. This issue should be definitely fixed before 4.0.0 as search feature is essentially broken. Please feel free to close this issue as duplicate, let's just make sure  https://github.com/jupyterlab/jupyterlab/issues/13651 is included into 4.0.0 milestone

**Closed** 2023-03-30 19:29 UTC
Labels: bug, pkg:settingeditor, status:Needs Triage
