### ISSUE TITLE
jupyterlab installed on Ubuntu does not see conda environments

### ISSUE THREAD

**Issue by StevenCHowell** [jupyterlab/jupyterlab#1092] opened 2016-10-14 13:23 UTC
After installing jupyter lab from source, I cannot see other conda environments.  I am running on Ubuntu 16.04.  I worked with @blink1073 to try to sort this out without success.  I recommend someone with more familiarity try debugging this from an Ubuntu machine (hopefully I am just crazy and this only affects me).  

Here are the commands I ran and the output:

```
(jlab-test3) ➜  odin: jupyterlab/> git:(master) ✗ conda create -n jlab_test jupyter nb_conda_kernels
Fetching package metadata .......
Solving package specifications: ..........
Using Anaconda Cloud api site https://api.anaconda.org

Package plan for installation in environment /home/schowell/data/myPrograms/anaconda/envs/jlab_test:

The following NEW packages will be INSTALLED:

    backports:          1.0-py27_0    
    backports_abc:      0.4-py27_0    
    configparser:       3.5.0-py27_0  
    dbus:               1.10.10-0     
    decorator:          4.0.10-py27_0 
    entrypoints:        0.2.2-py27_0  
    enum34:             1.1.6-py27_0  
    expat:              2.1.0-0       
    fontconfig:         2.11.1-6      
    freetype:           2.5.5-1       
    functools32:        3.2.3.2-py27_0
    get_terminal_size:  1.0.0-py27_0  
    glib:               2.43.0-1      
    gst-plugins-base:   1.8.0-0       
    gstreamer:          1.8.0-0       
    icu:                54.1-0        
    ipykernel:          4.5.0-py27_0  
    ipython:            5.1.0-py27_0  
    ipython_genutils:   0.1.0-py27_0  
    ipywidgets:         5.2.2-py27_0  
    jinja2:             2.8-py27_1    
    jpeg:               8d-2          
    jsonschema:         2.5.1-py27_0  
    jupyter:            1.0.0-py27_3  
    jupyter_client:     4.4.0-py27_0  
    jupyter_console:    5.0.0-py27_0  
    jupyter_core:       4.2.0-py27_0  
    libffi:             3.2.1-0       
    libgcc:             5.2.0-0       
    libpng:             1.6.22-0      
    libsodium:          1.0.10-0      
    libxcb:             1.12-0        
    libxml2:            2.9.2-0       
    markupsafe:         0.23-py27_2   
    mistune:            0.7.3-py27_0  
    nb_conda_kernels:   2.0.0-py27_0  
    nbconvert:          4.2.0-py27_0  
    nbformat:           4.1.0-py27_0  
    notebook:           4.2.3-py27_0  
    openssl:            1.0.2j-0      
    path.py:            8.2.1-py27_0  
    pathlib2:           2.1.0-py27_0  
    pexpect:            4.0.1-py27_0  
    pickleshare:        0.7.4-py27_0  
    pip:                8.1.2-py27_0  
    prompt_toolkit:     1.0.3-py27_0  
    ptyprocess:         0.5.1-py27_0  
    pygments:           2.1.3-py27_0  
    pyqt:               5.6.0-py27_0  
    python:             2.7.12-1      
    pyzmq:              15.4.0-py27_0 
    qt:                 5.6.0-1       
    qtconsole:          4.2.1-py27_1  
    readline:           6.2-2         
    setuptools:         27.2.0-py27_0 
    simplegeneric:      0.8.1-py27_1  
    singledispatch:     3.4.0.3-py27_0
    sip:                4.18-py27_0   
    six:                1.10.0-py27_0 
    sqlite:             3.13.0-0      
    ssl_match_hostname: 3.4.0.2-py27_1
    terminado:          0.6-py27_0    
    tk:                 8.5.18-0      
    tornado:            4.4.2-py27_0  
    traitlets:          4.3.1-py27_0  
    wcwidth:            0.1.7-py27_0  
    wheel:              0.29.0-py27_0 
    widgetsnbextension: 1.2.6-py27_0  
    zeromq:             4.1.4-0       
    zlib:               1.2.8-3       

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|########################################################################################| 100%
#
# To activate this environment, use:
# $ source activate jlab_test
#
# To deactivate this environment, use:
# $ source deactivate
#
(jlab-test3) ➜  odin: jupyterlab/> git:(master) ✗ source activate jlab_test
(jlab_test) ➜  odin: jupyterlab/> git:(master) ✗ pip install -e .
Obtaining file:///home/schowell/data/code/jupyterlab
Requirement already satisfied (use --upgrade to upgrade): notebook>=4.2.0 in /home/schowell/data/myPrograms/anaconda/envs/jlab_test/lib/python2.7/site-packages (from jupyterlab==0.5.0)
Installing collected packages: jupyterlab
  Running setup.py develop for jupyterlab
Successfully installed jupyterlab
(jlab_test) ➜  odin: jupyterlab/> git:(master) ✗ jupyter serverextension enable --py jupyterlab    
Enabling: jupyterlab
- Writing config: /home/schowell/.jupyter
    - Validating...
      jupyterlab  OK
(jlab_test) ➜  odin: jupyterlab/> git:(master) ✗ cd 
(jlab_test) ➜  odin: ~/> jupyter lab
[I 09:12:11.166 LabApp] The port 8888 is already in use, trying another port.
[I 09:12:11.166 LabApp] The port 8889 is already in use, trying another port.
[I 09:12:11.171 LabApp] It looks like you're running JupyterLab from source.
    If you're working on the TypeScript sources of JupyterLab, try running

        npm run watch

    from the JupyterLab repo directory in another terminal window to have the
    system incrementally watch and build JupyterLab's TypeScript for you, as you
    make changes.

[I 09:12:11.171 LabApp] JupyterLab alpha preview extension loaded from /home/schowell/data/code/jupyterlab/jupyterlab
[I 09:12:11.175 LabApp] Serving notebooks from local directory: /home/schowell
[I 09:12:11.175 LabApp] 0 active kernels 
[I 09:12:11.176 LabApp] The Jupyter Notebook is running at: http://localhost:8890/
[I 09:12:11.176 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

(firefox:6662): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:68:17: Theming engine 'unico' not found

(firefox:6662): Gtk-WARNING **: Failed to parse /usr/share/themes/Ambiance-Dark-Blue/gtk-3.0/settings.ini: Key file contains line 'selected_fg_color:#ffffff\nlink_color:#aa0000\nbg_color_dark:#333230\nfg_color_dark:#dfdbd2"' which is not a key-value pair, group, or comment
[I 09:12:15.762 LabApp] Creating new notebook in /
```

Notice that when `jupyter lab` runs, there is not a line that provides information about `N kernels found`.  This is what is shown in my conda-forge installation of jupyterlab, from a different conda env that I setup before the environment in which I installed it from source:

```
[I 08:35:12.374 LabApp] [nb_conda_kernels] enabled, 5 kernels found
```

Surprisingly, if I create a new conda environment and install jupyterlab from conda-forge, it cannot see other environments.

**Comment by jasongrout** [comment] 2016-10-21 14:55
> After installing jupyter lab from source, I cannot see other conda environments.

Trying to isolate the problem, and see if it is specific to JupyterLab:

1. Could you see the other conda environments before, in the `jupyter notebook`?
2. Can you see the other conda environments after you do the above in `jupyter notebook`?

**Comment by StevenCHowell** [comment] 2016-10-21 16:07
1. Before installing `jupyter lab` from source, I am not sure if I could see other conda environments after starting `jupyter notebook` from a different conda environment.  I did setup a conda environment, installed `jupyter lab` from the conda channel, then while in that environment I was able to start `jupyter lab` and see other environments (not exactly what you asked but closely related).  When I repeated this using the github source, I could not see other environments after starting `jupyter lab`.

2. Now, I can only see other environments when I start `jupyter notebook` from the main anaconda code, not from within an environment.  When I start `jupyter notebook` from within an environment, I cannot see other environments, just the one I started from.

**Comment by blink1073** [comment] 2016-11-17 21:18
Hi @StevenCHowell, I tried the steps you outlined above on Ubuntu 14.04 from a fresh Anaconda install, and I was able to see the other environments.   I was able to run `jupyter lab` and `jupyter notebook` from the root environment and the created environment and see all kernels.

Next, I created a new environment and installed from conda-forge, and verified that `lab` and `notebook` have the desired behavior in the new environment an the new environment.  
I'm not sure what the root of your problem could be.

**Comment by blink1073** [comment] 2016-11-17 21:19
cc @damianavila, @bollwyvl

**Comment by willingc** [comment] 2016-11-17 21:23
@blink1073 Perhaps output from `jupyter troubleshoot` would help.

**Comment by blink1073** [comment] 2016-11-17 21:29
@willingc, good call: 
http://pastebin.com/ey41P242  from the root env.

**Comment by blink1073** [comment] 2016-11-17 21:46
and the environment with the conda-forge install: http://pastebin.com/bifvasKM

**Comment by bollwyvl** [comment] 2016-11-20 18:57
A few things:
- This looks like an older anaconda release (some tell-tale signs). If you've done a bunch of stuff to your root environment/.condarc, it's kind of hard to tell what the current config is. a `conda info` might help
- `conda create -n jlab_test jupyter nb_conda_kernels`
  - this _should_ pull from `defaults` (i.e. `repo.continuum.io`) (see above about `.condarc`) which will pull along `_nb_ext_conf`, which is the anaconda approach to being able to ship and enable a set of jupyter extensions without running post-link scripts. If you're doing development on jupyter tools, you probably _shouldn't_ have `_nb_ext_conf` installed, and preferentially take the ones from `conda-forge`.
  - the simplest way to do this is an `environment.yml`, a la [this one](https://github.com/jovyan/jupyter-flight-simulator/blob/master/environment.yml) which will preferentially pull `conda-forge` packages
  - of course, `jupyterlab` is almost-continuously released on `conda-forge`, so you can `conda install -c conda-forge jupyterlab`!
- `jupyter serverextension enable --py jupyterlab`
  - this might cause [some troubles](https://github.com/jupyter/notebook/issues/1508). If you have already created an environment in which to test-drive lab, you should probably use this (with `jlab_test` enabled):
    - `jupyter serverextension enable --py --sys-prefix jupyterlab`
      - this will enable jupyterlab only in the `jlab_test` environment

So:
- if you can stomach it:
  - `mv ~/.jupyter ~/.jupyter_backup`
  - so that the user-level config stuff doesn't affect what you see
- `conda create -n jlab_test -c conda-forge jupyter nb_conda_kernels`
- `source activate jlab_test`
- `pip install -e .`
- `jupyter serverextension enable --py --sys-prefix jupyterlab`

And you should be able to see all of your kernels, as well as have hot access to your jupyterlab source!

I don't have a working ubuntu environment handy, but was able to reproduce these steps in docker. Here are the [key files](https://gist.github.com/bollwyvl/04c6e6ac025b981411f16ca579438fae).

**Comment by damianavila** [comment] 2016-11-25 21:21
Given @bollwyvl's comment and the +1 from @StevenCHowell, I think this one could be closed.

**Comment by blink1073** [comment] 2016-11-26 01:25
Great, closing, feel free to reopen if you disagree @StevenCHowell.

**Closed by blink1073** 2016-11-26 01:25 UTC
Labels: component:Build System, type:Bug

**Comment by StevenCHowell** [comment] 2016-11-28 14:35
While I did not try it, @bollwyvl's post seems reasonable and helpful (hence the +1, until I could try it and provide more input).  I think it fine to leave this closed for now.  If this comes up again (me or someone else) we can reopen this.

**Comment by damianavila** [comment] 2016-11-30 12:55
>If this comes up again (me or someone else) we can reopen this.

Sure thing!

**Comment by StevenCHowell** [comment] 2016-12-08 15:30
> if you can stomach it:
> 
>     mv ~/.jupyter ~/.jupyter_backup
>     so that the user-level config stuff doesn't affect what you see
> 
> conda create -n jlab_test -c conda-forge jupyter nb_conda_kernels
> source activate jlab_test
> pip install -e .
> jupyter serverextension enable --py --sys-prefix jupyterlab

I can confirm that following these step resolved the issue.  I can now see the different conda environments.  Thanks @bollwyvl!
