### ISSUE TITLE
"Insert cell below" button creating cell in the wrong location

### ISSUE THREAD

**Issue by fperez** [jupyterlab/jupyterlab#676] opened 2016-08-16 20:47 UTC
I can't seem to reproduce this with all notebooks, but it is happening reliably with one I have open, so I'll just put the gif below.  The problem is that, while I have the nb's last cell selected, when I click the "+" button for "insert cell below", instead the new cell gets created at the top of the notebook, as the 2nd overall cell. Very weird:

![new-cell](https://cloud.githubusercontent.com/assets/57394/17715205/fad95c8a-63b7-11e6-8e0e-a701ff481c96.gif)

**Comment by jasongrout** [comment] 2016-08-16 20:50
Are you running master as of a few minutes ago? We just merged some things that fixed some focus bugs, etc. (Just checking to see if you can reproduce it on master...)

**Comment by fperez** [comment] 2016-08-16 21:01
Yup, master as of right now, i.e. eb6a710.

**Comment by fperez** [comment] 2016-08-16 21:02
As I mentioned, it doesn't happen on all notebooks, but it is happening with one that's currently open... I haven't been able to make it happen again with fresh ones, so I don't know what's special about that one.

**Comment by jasongrout** [comment] 2016-08-16 21:25
It runs this function: https://github.com/jupyter/jupyterlab/blob/b99060f39a9d2bc6c91cfef3492ac7534d37d772/src/notebook/notebook/actions.ts#L241.

If you still have that notebook open, can you put a breakpoint in that function and see what the activeCellIndex is? Is it zero?

**Comment by fperez** [comment] 2016-08-16 21:31
Mmh, my JS-debug-fu is really primitive... I just set a breakpoint there in the Chrome dev tools, but it's not getting triggered at all...

**Comment by fperez** [comment] 2016-08-16 21:51
BTW, first I tried both setting the BP in the actions.ts file at the source.  But I think that's wrong, since that's not what's being served...  But then I tried setting it via the bundle.js file as seen from the server:

![image](https://cloud.githubusercontent.com/assets/57394/17717084/b1afb4a6-63c0-11e6-957b-304543243ba9.png)

This took me automatically to the actions.js file (note extension), where I did set it at line 209:

![image](https://cloud.githubusercontent.com/assets/57394/17717106/d3d847b4-63c0-11e6-838c-0a16f58c5c06.png)

But still, when I click the `+` button, nothing... I don't get dropped into the JS console.  Should I?  Sorry for my naive questions, but as I said, I'm pretty green on JS debugging :)

**Comment by jasongrout** [comment] 2016-08-16 22:11
Set it inside the insert below function, like line 201. I usually set it
inside of the bundle.js

**Comment by fperez** [comment] 2016-08-16 22:20
No luck...

**Comment by fperez** [comment] 2016-08-16 23:24
Mmh... I couldn't get it to pause at the breakpoint, so finally I tried a page reload.  Now unfortunately the Heisenbug is gone! 

Glad I grabbed that GIF to at least show I wasn't crazy :)

**Comment by fperez** [comment] 2016-08-16 23:29
Ah, it's back! OK, I could reproduce it now after the reload just by trying a few times, and now I do get the breakpoint to work...

While executing in `insertBelow` in the debugger, I get `widget.activeCellIndex == 2`. 

Does that help?

**Comment by fperez** [comment] 2016-08-17 00:38
Ok, more interesting/weird behavior! That new cell is being inserted at the top of the notebook, but in terms of internal counting, it *is* being treated as the last one. I see it by navigating the nb with the keyboard, it jumps over it at first, then gets to it at the end:

![cell-jumping](https://cloud.githubusercontent.com/assets/57394/17720609/2adddca6-63d8-11e6-9e10-f1a81a2da9f8.gif)

So internally, the counters that control navigation treat it as last, but on the page it's towards the top (cell `#2`).

**Comment by blink1073** [comment] 2016-08-29 15:26
I tried and failed to reproduce this on master just now.  I added/deleted/cut/paste executed cells randomly.

**Comment by jasongrout** [comment] 2016-09-19 18:36
From JLab dev meeting: we need a way to reproduce this, or to sit down next to you while you reproduce.

**Comment by fperez** [comment] 2016-09-19 18:57
I'll keep trying, it's very odd that only I see it.  It happened to me again last week on a plane, and it forced me to stop using Lab and revert to the classic nb.  Very frustrating and really weird that I'm the only one seeing it.  It's a complete show-stopper to actually use Lab for real work.

**Comment by blink1073** [comment] 2016-11-15 21:17
Closing as a duplicate of #228 in that they are caused by the same errant Chrome Extension.

**Closed by blink1073** 2016-11-15 21:17 UTC
Labels: component:Notebook, status:Needs Info, type:Bug
