### ISSUE TITLE
Copy sharable link doesn't work always

### ISSUE THREAD

**Issue by serengiti** [jupyterlab/jupyterlab#7163] opened 2019-09-06 22:42 UTC
## Description
I wanted to share a notebook URL with another user. All users use different jupyter instance but share file system. I used "Copy Sharable Link" to get the link and shared with the user. The user pasted the URL and all he got was jupyterlab with a terminal - not the notebook. I later verified, that the user already had a jupyter lab session open and hence this issue. If we close all browser tabs with jupyter lab session and paste the URL , it works as expected. This is complex . In jupyter classing - sharing URL was easy , jupyterlab has made it very complex.

URL I copied was 
https://jupyter.mydomain.com/user/myid/lab/tree/Users/xyz/LEARN/abc.ipynb

When pasted with an existing session of Jupyterlab still open in a different browser tab, it redirects to 
https://jupyter.mydomain.com/user/myid/lab/workspaces/auto-3/tree/Users/xyz/LEARN/abc.ipynb and displays the console screen in lab

## Reproduce
In jupyterlab
1. Right click on a file in the left hand explorer view
2. Click on "Copy Shareable Link" (eg; https://jupyter.mydomain.com/user/myid/lab/tree/Users/xyz/LEARN/abc.ipynb)
3. Open a new tab
4. Paste the link
5. It doesn't show the notebook that was copied in the link but a console window i JupyterLab view

## Expected behavior

Expected it to open the notebook , whose URL was copied (eg; /Users/xyz/LEARN/abc.ipynb )

## Context

JupyterLab + JupyterHub + KubeSpawner
- Browser and version: Google Chrome 76.0.3809.132 (Official Build) (64-bit)
- JupyterLab version: 1.0.2

**Comment by afshin** [comment] 2019-09-07 09:17
Thanks for the report! This is caused by this issue: https://github.com/jupyterlab/jupyterlab/issues/7156 so I'm closing this one to have a single place where we can track its progress.

**Closed by afshin** 2019-09-07 09:17 UTC

**Comment by serengiti** [comment] 2019-09-08 08:37
Thanks @afshin for taking a look at it. Do you have a estimated time by when it could be done ?
