### ISSUE TITLE
Inline image attachments in a notebook do not show in collaborative mode

### ISSUE THREAD

**Issue by 3coins** [jupyterlab/jupyterlab#13436] opened 2022-11-17 15:57 UTC
## Description
Inline images in a notebook do not show when jupyterlab is running with the `--collaborative` flag on. The inline image attachments are loading fine without the collaborative flag on.

## Reproduce
Copy the attached notebook to jupyterlab workspace and open in collaborative mode `jupyter lab --collaborative`.  Second image in the attached notebook does not load.

[inline-image-test.ipynb.zip](https://github.com/jupyterlab/jupyterlab/files/10037409/inline-image-test.ipynb.zip)

<img width="774" alt="Screen Shot 2022-11-17 at 7 08 56 AM" src="https://user-images.githubusercontent.com/289369/202488386-31c70a5b-dd60-4963-8254-d1707ce93b65.png">

## Expected behavior
The inline image attachment should load correctly in the notebook.

## Context
jupyter_server                : 2.0.0rc3
jupyterlab                        : 3.6.0a3
jupyter_server_ydoc      :0.2.0
jupyter-ydoc                   :0.2.2

cc @ellisonbg

**Comment by davidbrochart** [comment] 2022-11-17 16:13
Is `test.png` supposed to be a local file?

**Comment by davidbrochart** [comment] 2022-11-17 16:18
Got it, you need to drag and drop the image into the cell.

**Comment by davidbrochart** [comment] 2022-11-17 16:29
It seems to be a frontend issue, because the image is shown if it is already in the notebook, but dragging and dropping doesn't seem to work.

**Comment by 3coins** [comment] 2022-11-17 21:44
@davidbrochart 
Don't follow how drag-drop is the issue here. The 2nd image here is referring to the first image, which is loaded from a URL; there is no need to add the image to the workspace. This is working as expected in non-collaborative mode with both images loaded correctly.

**Comment by 3coins** [comment] 2022-11-18 03:14
@davidbrochart 
Updated the summary and attached a notebook file to test.

**Comment by hbcarlos** [comment] 2022-11-18 20:02
Hi @3coins, I can reproduce it now. I look into it.
Actually, seams to work fine in Lab 4.0.

**Comment by fcollonval** [comment] 2022-11-21 13:25
Fixed by #13450

**Closed by fcollonval** 2022-11-21 13:25 UTC
Labels: bug, tag:Real Time Collaboration, pkg:collaboration
