### ISSUE TITLE
Terminal not working post jupyter_server_terminals latest version

### ISSUE THREAD

**Issue by divyabiyani** [jupyterlab/jupyterlab#15527] opened 2023-12-14 06:30 UTC
## Description

After the latest version of jupyter_server_terminals (0.5.0), terminals websocket connections are not sending the stdout back resulting in terminal getting stuck.

Error in jupyter logs- 
`Exception in callback functools.partial(<function WebSocketProtocol._run_callback.<locals>.<lambda> at 0x7ff186d31ab0>, <Task finished name='Task-609' coro=<TermSocket.on_message() done, defined at /usr/python310/lib/python3.10/site-packages/jupyter_server_terminals/handlers.py:59> exception=TypeError("object NoneType can't be used in 'await' expression")>)`

## Reproduce

This error is reproducible consistently with versions - 
JupyterLab - 4.0.9 
jupyter_server_terminals - 0.5.0

**Comment by krassowski** [comment] 2023-12-14 10:52
I cannot reproduce:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/6fdb29b7-3ece-4ab2-a4b1-e8e20d1d8482)

This would likely be an issue in jupyter-server though.

Can you add `jupyter --version` and `pip list | grep jupyter` results?

**Comment by divyabiyani** [comment] 2023-12-14 17:17
@krassowski , Here are the details - 
```
jupyter --version
4.4.0
```

```
pip list | grep jupyter
jupyter_client            8.6.0
jupyter_core              5.5.0
jupyter-events            0.9.0
jupyter-lsp               2.2.1
jupyter-resource-usage    0.7.2
jupyter_server            2.12.1
jupyter_server_terminals  0.5.0
jupyterlab                4.0.6
jupyterlab_pygments       0.3.0
jupyterlab_server         2.25.2
jupyterlab-widgets        3.0.9
```

**Comment by krassowski** [comment] 2023-12-15 19:52
I tried with the newer versions to align with yours but still could not reproduce. Can you provide exact reproduction steps, ideally with a screen recording so that I could follow step-by-step?

Also, may I suggest that opening an issue over https://github.com/jupyter-server/jupyter_server_terminals/issues maybe get more experiences eyes on your issue?

**Comment by JasonWeill** [comment] 2023-12-19 17:08
@divyabiyani Also, could you share what OS and what Python version you're running Jupyter Server / JupyterLab with? Thanks!

**Comment by JasonWeill** [comment] 2024-01-02 17:12
@divyabiyani Any update on what OS and Python version you're running?

**Comment by JasonWeill** [comment] 2024-01-09 17:07
@divyabiyani Because we can't reproduce this bug, I'm going to close it. Please let us know if this is still a problem with JupyterLab 4.0.10 or prereleases of JupyterLab 4.1.0. Thanks!

**Closed by JasonWeill** 2024-01-09 17:07 UTC
Labels: bug, status:Needs Info, status:Needs Triage

**Comment by julienchastang** [comment] 2024-01-16 22:53
More information and workaround can be found here: https://github.com/jupyter-server/jupyter_server_terminals/issues/103
