### ISSUE TITLE
Files in jupyterlab file explorer disappears

### ISSUE THREAD

**Issue by Streeter220** [jupyterlab/jupyterlab#12688] opened 2022-06-13 11:56 UTC
Hi, recently some of our users started reporting that all files and directories are gone from the file explorer in jupyterlab. I have checked the container logs and there is nothing that points out the error. The files are viewable in the API '/user/api/contents'.

We run jupyterhub/jupyterhub:2.2.2 and jupyter/pyspark-notebook:spark-3.2.1

Any help would be greatly appreciated.

**Comment by jweill-aws** [comment] 2022-06-16 17:32
Thank you for your contribution! We need some more information to triage this issue.

Which JupyterLab version are you running?

Are there any errors either in the browser's console or in the JupyterLab console output/error?

Can you attach before/after screen shots to this issue to better explain the issue?

**Comment by krassowski** [comment] 2022-06-23 13:38
`jupyter-server` version may be relevant as well.

**Comment by jweill-aws** [comment] 2022-06-23 17:06
@Streeter220 Can you please provide the information that @krassowski and I requested? That will help us identify the cause of your issue. Thanks.

**Comment by jweill-aws** [comment] 2022-07-07 17:03
Closing due to lack of information. Please reopen if you can provide the info requested. Thanks!

**Closed by jweill-aws** 2022-07-07 17:03 UTC
Labels: bug, status:Needs Info, pkg:filebrowser, status:Needs Triage
