### ISSUE TITLE
`requestCommInfo` not honoring target name

### ISSUE THREAD

**Issue by kb0304** [jupyterlab/jupyterlab#6947] opened 2019-08-05 12:19 UTC
**Describe the bug**
When developing an extension which sends custom comm messages, and with ipywidgets' jupyterlab-manager installed, the messages even with target other than `jupyter.widget` are being intercepted by jupyterlab-manager

Why the `requestCommInfo` is not honoring target name [here](https://github.com/jupyter-widgets/ipywidgets/blob/6ec38c76fb93be0e840e8dfc96495f6e77f533fe/packages/jupyterlab-manager/src/manager.ts#L269)?

**Expected behavior**
Messages only with target `jupyter.widget` are intercepted

- Browser [chrome ]
- JupyterLab [1.0.2]
- @jupyter-widgets/jupyterlab-manager@1.0.1

**Comment by kb0304** [comment] 2019-08-05 12:39
Turns out they're using `target` here instead of `target_name`
`const reply = await this._context.session.kernel.requestCommInfo({target: this.comm_target_name});`

**Comment by jasongrout** [comment] 2019-08-05 17:08
c.f. https://github.com/jupyter-widgets/ipywidgets/issues/2526

**Comment by jasongrout** [comment] 2019-08-05 17:20
Thanks for finding and reporting this, and finding the underlying cause. Let's move the discussion over to the ipywidgets issue, since that's where the problem is.

**Comment by Madhu94** [comment] 2019-08-05 17:44
@jasongrout I believe the KernelMessage type should be fixed in lab first - [here](https://github.com/jupyterlab/jupyterlab/blob/32451a627a9443003edf65d7a1e452ff06026a91/packages/services/src/kernel/messages.ts#L1083), before you could fix ipywidgets (TS errors may surface)

**Comment by Madhu94** [comment] 2019-08-05 17:46
If we change the type, would that constitute a breaking change for services package? If so, could  renaming target to target_name here may be a quicker temporary fix?

**Comment by jasongrout** [comment] 2019-08-05 17:52
> @jasongrout I believe the KernelMessage type should be fixed in lab first - [here](https://github.com/jupyterlab/jupyterlab/blob/32451a627a9443003edf65d7a1e452ff06026a91/packages/services/src/kernel/messages.ts#L1083), before you could fix ipywidgets (TS errors may surface)

Good catch. This is deeper than I thought.

> If we change the type, would that constitute a breaking change for the services package?

Technically, yes, but it's also a pretty clear bug-fix, in that it is not following the spec.

**Comment by jasongrout** [comment] 2019-08-05 18:31
What do you think of https://github.com/jupyterlab/jupyterlab/pull/6949 ?

**Comment by Madhu94** [comment] 2019-08-05 21:40
This is exactly what I meant when I said "renaming it can be a quick fix".
Poorly worded I guess. :)  Thanks for fixing it !

**Closed** 2019-08-06 19:37 UTC
