### ISSUE TITLE
Cannot build 3.2.7

### ISSUE THREAD

**Issue by enriqueartal** [jupyterlab/jupyterlab#11854] opened 2022-01-13 10:18 UTC
## Description
Jupyter lab 3.2.7 is not buitd (3.2.6 is built without errors)

## Reproduce

1. Upgrade jupyterlab via pip to 3.2.7
2. Execute jupyter lab build
3. Got an error (see attached log) 

## Expected behavior

Succesful build
## Context

- Operating System and version: Linux Fedora 35
- JupyterLab version: 3.2.7
[jupyterlab-debug-kpjlh22o.log](https://github.com/jupyterlab/jupyterlab/files/7861923/jupyterlab-debug-kpjlh22o.log)

**Comment by krassowski** [comment] 2022-01-13 10:26
```ts
$ webpack --config webpack.prod.minimize.config.js
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve 'crypto' in '/usr/local/share/jupyter/lab/staging/node_modules/@lumino/coreutils/dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }
    at /usr/local/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:2011:28
    at /usr/local/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (/usr/local/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /usr/local/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/usr/local/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /usr/local/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at /usr/local/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /usr/local/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at /usr/local/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at /usr/local/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:972:5
resolve 'crypto' in '/usr/local/share/jupyter/lab/staging/node_modules/@lumino/coreutils/dist'
  Parsed request is a module
  using description file: /usr/local/share/jupyter/lab/staging/node_modules/@lumino/coreutils/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
```

This was originally fixed in https://github.com/jupyterlab/lumino/pull/70 but the fix was removed in https://github.com/jupyterlab/lumino/commit/cfc30baea0d05df33e1641ea8798b6484dac89e7#diff-4efe7e2a73ac9c972932d5a7d9fc763d3a344b15c6d6bb9fdb0917007b36a312L25-L27 (part of https://github.com/jupyterlab/lumino/pull/274) by @GordonSmith.

**Comment by GordonSmith** [comment] 2022-01-13 12:40
Can you point me to the webpack.prod.minimize.config.js file? 
It claims to resolve to "module" which points to:  https://cdn.jsdelivr.net/npm/@lumino/coreutils@1.12.0/dist/index.es6.js which doesn't have a `require("crypto")` but somehow is pulling in either https://cdn.jsdelivr.net/npm/@lumino/coreutils@1.12.0/dist/index.node.js or https://cdn.jsdelivr.net/npm/@lumino/coreutils@1.12.0/dist/index.es6.node.js ???

**Comment by krassowski** [comment] 2022-01-13 12:56
Are you saying that `crypto` was completely removed from `@lumino/coreutils` and therefore the issue is on the level of stale webpack config? This is strange indeed. Could it be because crypto is still listed as a peer dependency in `package.json` of `@lumino/coreutils` and webpack pulls that?

> Can you point me to the webpack.prod.minimize.config.js file?

I believe it is this one: [`3.2.x/dev_mode/webpack.prod.minimize.config.js`](https://github.com/jupyterlab/jupyterlab/blob/3.2.x/dev_mode/webpack.prod.minimize.config.js); it gets copied over to another location in [`buildutils/src/update-core-mode.ts`](https://github.com/jupyterlab/jupyterlab/blob/b228e5d6cb4f4cdb5fc9ad09a24ad8accb727508/buildutils/src/update-core-mode.ts#L46).

**Comment by GordonSmith** [comment] 2022-01-13 14:57
FWIW - the reason I made the change was that I was getting the crypto error in my Rollup / Webpack Bundles <g>.  The way its supposed to be working now, is that if webpack is targeting a Node environment it will pull the source file from the "main" field and if its a "browser" from the browser field (which its complaining about and falling back to "module" which should also be ok as the only dist file which include the crypto are index.node and index.es6.node...

**Comment by krassowski** [comment] 2022-01-13 19:10
@enriqueartal would you mind trying with 3.2.8?

**Comment by enriqueartal** [comment] 2022-01-13 21:33
It works! Thank you very much.

**Comment by jtpio** [comment] 2022-01-14 09:52
Great, closing as fixed then.

Thanks all!

**Closed by jtpio** 2022-01-14 09:52 UTC
Labels: bug

**Comment by enriqueartal** [comment] 2022-05-04 22:17
[jupyterlab-debug-e52wja00.log](https://github.com/jupyterlab/jupyterlab/files/8627694/jupyterlab-debug-e52wja00.log)
A similar problem seems to happen with 3.4.0; may it be related? Building jupyter lab fails with the above log Thanks, Enrique.
