### ISSUE TITLE
PDF scrolls to top everytime when you click the tab

### ISSUE THREAD

**Issue by mrinalraghupathi** [jupyterlab/jupyterlab#5714] opened 2018-12-01 18:42 UTC
**Describe the bug**
When you open a tab with a PDF and switch back to it, the PDF reloads and I lose my position in the file.

**To Reproduce**

Open a PDF in jupyter lab
Switch to another open tab
Switch back to the PDF tab. 
The PDF file reloads and I'm scrolled back to the top. So now I have to scroll down to get back to where I left off reading the PDF.

**Expected behavior**
Switching back to the PDF tab should keep you at the same place in the PDF when you swtiched away.

**Desktop (please complete the following information):**

- OS: [Sierra 10.12.6]
- Browser [chrome 70.0.3538.77]
- JupyterLab [e.g. 0.35.3]

**Comment by lhoff94** [comment] 2018-12-02 12:00
Same issue for me. 

OS: [Windows 10 1803]
Browser : [Opera 56.0.3051, Edge 42.17134.1.0]
JupterLab: [0.35.4]

**Comment by PEERCRED** [comment] 2018-12-02 21:32
The problem is that the `renderModel` method of MIME rendering extension is called every time you switch to the tab with the widget. And pdf extension re-renders its content every time.

In my extension, I return from `renderModel` immediately unless it is called for the first time.

**Comment by contagon** [comment] 2019-02-08 05:54
Was there ever any solution or workaround for this? I'm running into the same issue on a Linux device, with jupyter lab open in chrome.

**Comment by AlbertHilb** [comment] 2019-02-08 10:50
This is just one of the issues related to the current PDF renderer (another is #4892).
The long term solution is to adopt a renderer based on PDFJS.
A renderer based on PDFJS is already used in [jupyterlab-latex][1], so it's a matter of moving it to a standalone extension. Some preliminary work is underway (jupyterlab/jupyterlab-latex#107), but there is no definite deadline.


[1]: ../../jupyterlab-latex

**Comment by ian-r-rose** [comment] 2019-02-09 20:53
@AlbertHilb is right that a longer term solution would be to migrate to something PDF.js based. This would allow for an actual API to drive the PDF viewer, which would be useful in a number of contexts. I'm a bit concerned that Mozilla may not be planning to support PDF.js in the long-term, however.

As for this issue, a more short-term fix would be to check if the PDF string has changed between renders. If it hasn't changed, there is no need to rerender the document, and the viewer can handle any resize events internally. This is potentially a somewhat expensive check, especially for large PDFs, but it is preferable to a full rerender, which is happening right now.

I'm marking this as a good first issue. The fix would involve going to the PDF renderer, storing a reference to the old string, and on rendering, check if the new string is identical to the old one, then return if that is the case:
https://github.com/jupyterlab/jupyterlab/blob/bbc1bbd20f69db70e2c38cbf4ef7d0c8f198561d/packages/pdf-extension/src/index.ts#L36

**Comment by mihai-dinculescu** [comment] 2019-03-08 13:20
I had a look at this. It turns out that caching the PDF string has no effect on the outcome.

Firefox, because it uses *pdf.js*, it manages to remember the position even if the PDF string is not cached. Surprinsingly, the PDF position is remembered after a page refresh as well.

Other browsers, like Chrome, completely re-render the PDF document even when the PDF string is cached. I suspect that the re-render is triggered by the `embed` HTML element being removed and re-added to the DOM when the tabs are changed.

**Comment by ian-r-rose** [comment] 2019-03-08 16:23
@mihai-dinculescu Do you have a branch that shows this behavior? I just checked the fix that I described above, and it seems to work correctly (that is, it no longer reloads when switching or moving the tab).

**Comment by mihai-dinculescu** [comment] 2019-03-08 16:42
Yes, it is the change from `embed` to `iframe` that did the trick for you.

**Comment by mihai-dinculescu** [comment] 2019-03-08 17:01
Also, while the iframe and the caching fixes the refresh issue in Chrome, it breaks it in Firefox.

**Comment by ian-r-rose** [comment] 2019-03-08 17:02
It seems to work correctly on firefox for me (using Ubuntu).

**Comment by mihai-dinculescu** [comment] 2019-03-08 17:05
I'm running Firefox 65.0.2 (64-bit) on Windows 10.

**Comment by jasongrout** [comment] 2019-04-26 23:40
> I suspect that the re-render is triggered by the `embed` HTML element being removed and re-added to the DOM when the tabs change.

FYI, the embed element is displayed/hidden (using `display: none` css), not removed and added to the page, when a tab is shown/hidden.

**Comment by jasongrout** [comment] 2019-04-26 23:41
> Also, while the iframe and the caching fixes the refresh issue in Chrome, it breaks it in Firefox.

It also seems to break things in Firefox for me on macOS. It worked in 1.0a3, it breaks in #6255 (and always shows page 1 when unhiding the tab).

**Comment by jasongrout** [comment] 2019-04-26 23:54
@ian-r-rose and I decided we still need a follow-up to #6255, and we'll make a matrix to make it very clear what the current behavior is and what it is after a PR.

**Comment by ian-r-rose** [comment] 2019-05-04 01:48
Fixed by #6255, #6264. I'm closing this as it worked on the browsers/OSs that we tried, but if the people here can test to see if it fixes it for them as well, it would be much appreciated.

**Closed by ian-r-rose** 2019-05-04 01:48 UTC
Labels: good first issue, pkg:pdf
