### ISSUE TITLE
auto quit edit mode after back from visiting other tabs

### ISSUE THREAD

**Issue by immorBen** [jupyterlab/jupyterlab#12649] opened 2022-06-03 07:30 UTC
Problem: I have to re-click the cell into edit mode after back from visiting other chrome tabs, do we have the workflow that:
- coding in the cell, (need to search something...)
- go to a new tab
- got the search result
- back to Jupyterlab and *continue* editing... **but now I have to use the mouse and re-select the cell I edited just seconds ago, can we have the cursor stay at the cell?**

environments:
JupyterLab v3.4.2
        @krassowski/jupyterlab-lsp v3.10.1 enabled OK (python, jupyterlab-lsp)
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)

Appreciate any helps~

**Comment by jweill-aws** [comment] 2022-06-09 17:14
We cannot reproduce this bug by switching browser tabs (e.g., from the JupyterLab tab in Chrome to a Google search engine tab in Chrome). When switching from one JupyterLab tab to another, then back, the previously-active cell remains active, but not in edit mode; pressing `ENTER` re-enables edit mode.

I'm closing this out as part of our weekly triage process because I was unable to reproduce the bug as you filed it. If you have another reproduction process, please reopen your issue. Thank you for your contribution to Project Jupyter!

**Closed by jweill-aws** 2022-06-09 17:14 UTC
Labels: bug, status:Needs Triage
