### ISSUE TITLE
Complex folium maps don't render in Chrome

### ISSUE THREAD

**Issue by robroc** [jupyterlab/jupyterlab#3991] opened 2018-02-24 00:00 UTC
Folium maps render fine in Jupyter notebook using Chrome, but not Lab. In my case, a map with 500+ circle markers.

Details: Windows 7, Python 3.6, folium==0.5.0

This was also brought up in the [folium repo](https://github.com/python-visualization/folium/issues/812), FYI.

**Comment by jasongrout** [comment] 2018-02-24 04:46
Does folium ever render anything in JupyterLab? i.e., is it just that folium needs to provide a jupyterlab extension?

**Comment by jasongrout** [comment] 2018-02-24 04:52
As far as I can tell, looking at the folium code, folium needs to have a jupyterlab extension to expose itself as a renderer in the system. See the [extension developer guide](http://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html) - likely folium will want to be a rendermime extension.

For example, here's a geojson jupyterlab plugin to render geojson data using leaflet: https://github.com/jupyterlab/jupyter-renderers/tree/master/packages/geojson-extension

**Comment by robroc** [comment] 2018-02-25 17:25
To answer your previous question, basic folium maps do render in JupyterLab. 

But I just tested on my Mac machine at home and complex maps render just fine. Might be a Windows problem, then.

Here's a code sample that worked on Mac:

```
from folium import Map, CircleMarker
import random

mapa = Map(location = [45.6, -73.5], tiles = 'cartodbpositron' )

for x in range(600):
    lat = random.uniform(45.4, 45.8)
    lon = random.uniform(-73.3, -73.9)
    CircleMarker(location = [lat, lon], radius = 200).add_to(mapa)
    
mapa
```

**Comment by saulshanabrook** [comment] 2018-04-30 17:47
Someone [posted in the folium issue that it was unable to render these complex maps in any iframe](https://github.com/python-visualization/folium/issues/812#issuecomment-383733263), not just in jupyterlab or jupyter notebook. I am going to close this for now, assuming that the problem is with folium rendering and not jupyterlab.

However, if someone has a map that renders properly in a standalone iframe and doesn't in jupyterlab, feel free to re-open.

**Closed by saulshanabrook** 2018-04-30 17:47 UTC
