### ISSUE TITLE
Multi-line commenting shortcut key Ctrl + / (slash) works only intermittently (Jupyter Notebook 6)

### ISSUE THREAD

**Issue by dinohsu1019** [jupyterlab/jupyterlab#14818] opened 2023-07-12 08:06 UTC
## Description

Mark multiple lines and press Ctrl + / (slash) toggles commenting and uncommenting, but only intermittently. After a moment, it stops working, and the Ctrl + / comes out with three-dots (...), which replace the whole thing. After another moment, it suddently starts working again. Unfortunately, I failed to figure out how to reproduce the problem effectively (don't know the rule).

## Reproduce

Unfortunately, I failed to figure out how to reproduce the problem effectively (don't know the rule).

1. Open an ipynb file and do editing.
2. Mark multiple lines with mouse (selecting multiple lines with left button and holding it moving) or with both keyboard (cursor placed at the beginning of the first line to mark, holding shift key, and press the down key multiple times and release the shift key)
3. Click Ctrl + / (slash)
4. See ... (three dots) replacing the whole thing selected. (but intermittely back to normal with commenting and uncommenting)

## Expected behavior

Commening (add the # + space at the beginning of lines) and uncommenting (remove the # + space at the beginning of the lines) of the multiple lines of code selected.

## Context

Editing an opened ipynb file.

- Operating System and version: Windows 11 Home Edition
- Browser and version: Chrome (latest version) 版本 114.0.5735.199 (正式版本) (64 位元)
- JupyterLab version: not yet using Jupyter Lab, 
- Server Information:
You are using Jupyter Notebook.

The version of the notebook server is: 6.5.2
The server is running on this version of Python:
Python 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]

Current Kernel Information:
Python 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]

<details><summary>Troubleshoot Output</summary>
<pre>
Please see the attach file for the output. 
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
I am not using JupyterLab yet, only Jupyter Notebook.
</pre>
</details>
[jupyter troubleshoot output.txt](https://github.com/jupyterlab/jupyterlab/files/12025410/jupyter.troubleshoot.output.txt)

<details><summary>Browser Output</summary>

<pre>
Sorry, this seems not applicable.

</pre>
</details>

**Comment by JasonWeill** [comment] 2023-07-18 16:12
This is a duplicate of https://github.com/jupyter/notebook/issues/6060. In the future, you can open Jupyter Notebook issues not found in JupyterLab at https://github.com/jupyter/notebook/issues/ . Thanks for your contribution!

**Closed by JasonWeill** 2023-07-18 16:12 UTC
Labels: bug, status:Duplicate, status:Needs Triage
