### ISSUE TITLE
Cannot render execution_count = 21 cell after reopen ipynb file (jupyterlab-3.1.0a13)

### ISSUE THREAD

**Issue by jenghung** [jupyterlab/jupyterlab#10488] opened 2021-06-25 14:48 UTC
## Description
Execute notebook cells step by step and then save it. 
After reopen it , the 21st execution cell cannot be rendered.

![image](https://user-images.githubusercontent.com/4241017/123438338-2b9eb780-d603-11eb-8219-e0cd4d816a93.png)

## Reproduce
Download the sample.ipynb file and open it on jupyterlab-3.1.0a13:
https://raw.githubusercontent.com/jenghung/files/master/sample.ipynb

![image](https://user-images.githubusercontent.com/4241017/123441186-2858fb00-d606-11eb-8cef-fe3987f1930e.png)

## Expected behavior
![image](https://user-images.githubusercontent.com/4241017/123441455-753cd180-d606-11eb-873a-dea5086b2500.png)

**It worked well on jupyterlab-3.1.0a12.**

## Context
- Operating System and version: Ubuntu 20.04.2 LTS (jupyterlab server)
- Browser and version: Chrome 91.0.4472.114
- JupyterLab version: jupyterlab-3.1.0a13

**Comment by krassowski** [comment] 2021-06-25 16:39
Thank you for testing the alpha release and providing this bug report - it is really useful!

**Comment by fcollonval** [comment] 2021-06-29 07:46
Thanks for testing @jenghung 

i'm unfortunately unable to reproduce; tested on 
- Chromium Version 90.0.4430.212 
- Firefox 88.0.1
OS Debian 11.0

**Comment by krassowski** [comment] 2021-06-29 08:36
Repro on master (actually on fcollonval:ft/e2e-docker as it had a binder ready faster):

![repro](https://user-images.githubusercontent.com/5832902/123764848-1359c180-d8bd-11eb-8ef9-a603592e8eaa.gif)

It's very pesky bug it did not show up on the first try, showed on the second open of the file (but I did not have the recording tool) and then it did not show for the next ~13 trials; only showed up again in 14th attempt. The exact sequence to reproduce in both cases was:

- download the example notebook
- open it
- save it (new kernel metadata)
- refresh JupyterLab
- scroll down to see if 21st cell went away

**Comment by echarles** [comment] 2021-07-02 08:02
Fixed by https://github.com/jupyterlab/jupyterlab/pull/10505

**Closed by echarles** 2021-07-02 08:02 UTC
Labels: bug, pkg:notebook
