### ISSUE TITLE
Tab completion not working in console

### ISSUE THREAD

**Issue by gioarma** [jupyterlab/jupyterlab#11466] opened 2021-11-15 14:38 UTC
## Description

The tab completion works as expected in the notebook, suggesting all possibilities when pressing the tab key after the `.`
Example: 
`object.<TAB KEY>` works as expected giving all possible attributes and methods of `object`.

However **in the console** this does not work and the tab key simply works as a tab spacer.

I noticed that instead tab completion works fine in the console when pressing TAB while typing a file path inside a string. In this case it correctly suggests all file contained in the folder. So it seems a problem with tab completion after the `.`

I attach a video to clear this out

- Operating System and version: macOS 10.15.7
- Browser and version: Chrome 95.0.4638.69
- JupyterLab version:  3.2.3  

https://user-images.githubusercontent.com/59478987/141798550-b608f42b-fbd7-42de-ad6f-39c04a26dcc2.mov

**Comment by gvermillion** [comment] 2022-01-24 17:17
I am experiencing the same issue for JupyterLab 3.2.5.

**Comment by fperez** [comment] 2022-01-29 08:57
Is this a regression? I could have sworn it used to work, but all the installations I have easy access to are 3.2.5 or newer, and they all show the problem...

If it is a regression, perhaps we can add a unit test to catch at least the basics, say `imp<tab>` -> `import` to start with.

**Comment by krassowski** [comment] 2022-01-29 14:45
Yes, this is a regression introduced with RTC changes, and it was also filled in https://github.com/jupyterlab/jupyterlab/issues/11710. I have missed labelling the other one as a duplicate of this one, but it was just resolved on master in https://github.com/jupyterlab/jupyterlab/pull/11949 (which already added a test case, big thanks to @fcollonval) and we also have a backport for 3.3.x open in https://github.com/jupyterlab/jupyterlab/pull/11956.

We should consider whether we want to backport it to 3.2.x too (given that 3.3.0 is still a few weeks away). Any thoughts on this?

**Comment by fperez** [comment] 2022-01-29 20:29
Thanks for the input @krassowski! It's not a huge issue, to be honest, so I'd say if it takes away any significant amount of time that could be better put to use elsewhere, then no worries, we can wait til 3.3.0. But I really appreciate the quick response!

**Comment by jtpio** [comment] 2022-02-02 09:07
> We should consider whether we want to backport it to 3.2.x too (given that 3.3.0 is still a few weeks away). Any thoughts on this?

We can indeed backport to 3.2.x it since 3.3 final might be approximately two weeks away from now.

**Comment by jtpio** [comment] 2022-02-04 13:02
Closing as fixed and released in `3.2.9`: https://github.com/jupyterlab/jupyterlab/releases/tag/v3.2.9

Thanks all!

**Closed by jtpio** 2022-02-04 13:02 UTC
Labels: bug, pkg:completer

**Comment by gioarma** [comment] 2022-02-07 15:55
I saw that version `3.2.9` solved the tab completion issue when pressing `tab` after `.`, however the issue remains with auto-close brakets. `(`, `[`, `{`, `'` and `"` auto-close only the first time that a command is run in the console. After that, auto-close brakets does not work anymore.

Should I open a new issue about this or is it still related to this one?

**Comment by fcollonval** [comment] 2022-02-07 17:09
Thanks for testing @gioarma 

The bug for auto-close brackets is tracked in your other issue: https://github.com/jupyterlab/jupyterlab/issues/10874

**Comment by fperez** [comment] 2022-02-08 02:28
Well, seeing how this got fixed, I wanted to say thanks to the team! I've pushed a [PR into our production hubs](https://github.com/berkeley-dsep-infra/datahub/pull/3246) so my students can get the benefit right away. Much appreciated!
