### ISSUE TITLE
Jupyter gives blank page on start

### ISSUE THREAD

**Issue by tarabishy2020** [jupyterlab/jupyterlab#6119] opened 2019-03-21 12:15 UTC
- Jupyterlab version 0.35.4
- Python 3.7.2

This error in chrome console appears, after launching jupyter lab from console
`
Refused to execute script from 'http://localhost:8888/lab/static/vendors~main.10079ad9676c70f28097.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
lab:1 Refused to execute script from 'http://localhost:8888/lab/static/main.13de647526d0a582493b.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
`

I believe this is similar to what is going on with jupyter notebook as well
[Issue #4467](https://github.com/jupyter/notebook/issues/4467)

**Comment by jasongrout** [comment] 2019-03-21 14:28
Indeed, the fix might be https://github.com/jupyter/notebook/issues/4468.

Can you see if you're having the same problem in the classic notebook (verifying that it's most likely https://github.com/jupyter/notebook/issues/4467), and if so, let's consolidate the discussion there.

**Comment by tarabishy2020** [comment] 2019-03-24 17:34
@jasongrout yes, same problem in the classic notebook

**Comment by fr34q** [comment] 2019-08-02 09:02
Hello, I encounter the same problem with Python 3.7.3 and Jupyterlab 1.0.2
I could get Jupyter Notebook running by downgrading to 5.7.8 (as suggested in @jasongrout s link). but Jupyterlab is still staying blank with the same error in the JS console.

Any ideas how I can get Jupyterlab working? Should I also downgrade to some specific version? Thanks for the help!

**Comment by DavidNemeskey** [comment] 2019-09-23 13:59
Python 3.7.3 and Jupyterlab 1.1.3 here. The errors are slightly different, but I still get a blank page:
```
The script from “https://jupyterhub.*.*/user/***/static/lab/main.cc81084897cab6cafd8c.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
The script from “https://jupyterhub.*.*/user/***/static/lab/vendors~main.9ef8ee00f059a70822ca.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
Loading failed for the <script> with source “https://jupyterhub.*.*/user/***/static/lab/main.cc81084897cab6cafd8c.js”.
The script from “https://jupyterhub.*.*/user/***/static/lab/vendors~main.9ef8ee00f059a70822ca.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
Loading failed for the <script> with source “https://jupyterhub.*.*/user/***/static/lab/vendors~main.9ef8ee00f059a70822ca.js”.
```

The scripts inside the lab html source are referenced to as:
```
<script type="text/javascript" src="/user/***/static/lab/main.cc81084897cab6cafd8c.js"></script>
```
So even if it is **not** the standard `application/javascript`, it is at least described as `javascript` in the source. It is the .js files themselves which seem to be at fault, first for having a different mime type (`text/html`), and second, for failing to load. I tried, but could not open them with a browser either: I get a 404.

**Comment by jasongrout** [comment] 2019-09-23 16:13
My guess is that the errors are related, in that it's probably returning an HTML error page because it can't find the file (which explains the text/html mimetype).

So the first place I would look is in the JupyterHub configuration for running JupyterLab, and make sure that's right. Perhaps you could also launch JupyterLab with the `--debug` flag which tells you where it is trying to find files on disk?

Hopefully someone more familiar with JupyterHub running jlab will comment too.

It does sound like the OP's issue is fixed, and the second person's separate issue is also resolved, so if we resolve this last issue, we should probably close this (triple-duty) GitHub issue.

**Comment by dmbhatti** [comment] 2020-02-11 06:20
Greetings, 

I've been having this weird issue for a while now. Sometimes (not always), I spin up the server on a remote machine and when I run the link in any browser on my local machine, the page is blank white. The problem appears to be with the vendors~main.a861638f675c21acb02b.js request. It's not getting a response in a timely manner. I've left this to cook and after about 10mins the file finally loaded and jupyter lab spun up. Afterwards, restarting the server with a new token or refreshing the page gave no problems whatsoever. I expect this will continue to work fine for a few days and then "break" again due to some reason beyond my limited grasp. I recently upgraded to 1.2.5 in the hopes of getting rid of this problem but no sauce. The request is as follows in cURL format:

curl 'http://localhost:8899/static/lab/vendors~main.a861638f675c21acb02b.js' -H 'Connection: keep-alive' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36' -H 'Sec-Fetch-Dest: script' -H 'Accept: */*' -H 'Sec-Fetch-Site: same-origin' -H 'Sec-Fetch-Mode: no-cors' -H 'Referer: http://localhost:8899/lab?token=cdf7de0360c99be405320500cd3677d1e35214ad94624ab0' -H 'Accept-Language: en-US,en;q=0.9' -H 'Cookie: username-localhost-8889="2|1:0|10:1579777573|23:username-localhost-8889|44:ZjE0ZjM3Y2YyMTc1NGI3NmIxNDQ5ZGI4ZDFhNjE5ZTE=|fa6a986af4e0f98e345aa6baf68d83ef28bd706fc7f00d59736384b0b875349f"; _xsrf=2|99287c4e|d1f06c1ca46249ceca96fa7e170d0902|1579777573; username-localhost-8899="2|1:0|10:1581400572|23:username-localhost-8899|44:OTM2ZGNjMWEyMzBlNGZjM2JiZTY5OWNiNjA3OGZmNDk=|ad1993988a5dde16c1f576e0de41f7df2b085801622ed092c462e0aeab01d36f"' --compressed 

Any support to resolve this for good would be highly appreciated. Let me know if you require any other information. 

Best Regards

**Comment by jasongrout** [comment] 2020-02-11 06:48
Key words to me are "remote server" and that it eventually loads. Perhaps the connection has limited bandwidth and it takes that long to load the js file? After it is loaded once, it is in the browser cache, so it is quicker, until it either is evicted from the browser cache or the file changes (like from an extension installation, etc.).

**Comment by jasongrout** [comment] 2020-02-11 06:49
How large is the file? We have done some things that may cut down on the size of that file too - any chance you could try with JupyterLab 2.0rc0, the latest 2.0 prerelease? You can install with `pip install --pre jupyterlab` if you are using pip.

**Comment by jasongrout** [comment] 2020-02-11 06:50
Also, that file size may depend on the plugins you have installed beyond the core plugins.

**Comment by dmbhatti** [comment] 2020-02-11 08:25
Thank you for the insight! I ran it again from an incognito window and this time I noted the file as 7.4MB that took 2.2min to download. It really should have taken a few seconds. I've been trying to get a bandwidth measurement using iperf but its proving to be beyond my abilities. 

Assuming plugins refers to the extensions, I only have the plotly-extension installed at the moment and I vaguely remember someone mentioning it as a cause of their loading problems in searches past.

**Comment by ahmadmahmood4040** [comment] 2022-11-29 15:31
I am also facing the black page for jupyterLab using firefox. Below is the error, i found it in the browser console:

SyntaxError: invalid regexp group
jlab_core.e37d4bbc8c984154bc26.js:2:941202
Error: 
main.bf515ddb81bbc946ace6.js:1:68352
SyntaxError: invalid identity escape in regular expression
3308.3a94151c0d57440646ab.js:1:10762
Source map error: request failed with status 404
Resource URL: http://bipcdpe02acdfrp.asiacell.com:50070/static/lab/main.bf515ddb81bbc946ace6.js?v=bf515ddb81bbc946ace6
Source Map URL: main.bf515ddb81bbc946ace6.js.map?v=bf515ddb81bbc946ace6
[Learn More]

**Comment by jasongrout** [comment] 2022-11-30 22:38
> I am also facing the black page for jupyterLab using firefox. Below is the error, i found it in the browser console:
> SyntaxError: invalid regexp group

This sounds like a very different problem from this issue. Can you file a new issue, and include your browser name and version? My first guess is that there is some code in jupyterlab or a plugin you've installed that your browser doesn't support.

**Comment by ahmadmahmood4040** [comment] 2022-11-30 22:52
@jasongrout, my issue has been fixed after updating my firfox to the latest version. JupyterLab is not supporting the firefox version which is less than 56.

**Comment by jasongrout** [comment] 2022-12-01 19:26
Since this issue is old, and has since become a place for many different root causes, I'm going to close this issue. If you are reading this issue in the future, and have a blank page, please open a new issue with the full debugging information the issue template asks for.

**Closed by jasongrout** 2022-12-01 19:26 UTC
Labels: tag:Server Change
