### ISSUE TITLE
Allow to disable the document-wide history tracking

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10791] opened 2021-08-09 21:04 UTC
#10694 highlighted some issues with the document-wide history tracking relating to outputs, but in the discussion it also came up that it might be a good idea to allow to disable this feature entirely. @mlucool noted that this behavior is detrimental to the workflow of some users (https://github.com/jupyterlab/jupyterlab/issues/10694#issuecomment-891390472).

During the weekly call (https://github.com/jupyterlab/team-compass/issues/128#issuecomment-892826198) @williamstein provided very useful feedback:
1. (against) teachers may want to have full history tracking available
2. (in favour) users sometimes mistakenly paste secretes into notebooks

The first issue does not apply to online sessions where a concern of some disruption to the lesson/vandalism could be a considerations since *I think* we would only want to allow to disable the tracking when not in RTC mode. Still there are some settings (exams?) where instructors may want to keep the history tamper-proof, should an ability to view it be introduced in the future.

The second issue could indeed be a substantial problem once #10544 gets implemented.

I would add another point related to (1):

3. There are regulatory settings (e.g. statistical analysis of clinical trials, see 21 CFR Part 11) where an audit trial record is required; some statistical analysis software products implement it by setting a flag on startup which persists through the session, this is the history tracking cannot be disabled without restarting the application (which clears the history/restarts the signature keys making it tamper-proof on the sufficient level to comply with the regulations).

Given the points (1) and (3) I think we can allow to opt-out of the document-wide history tracking, and it would make sense to require a server restart (so the setting should be implemented on server level).

**Comment by mlucool** [comment] 2021-08-09 22:29
FWIW, I think its perfectly reasonable to always have document level history so long as users can continue to have cell level redo/undo as in previous version of Jupyter. The problem users like being able to think of cells closer to how IDEs treat files. This means sometimes undo between files has meaning at times (e.g. undo a rename), but ctrl-z inside a file (i.e. in a codecell) means undo my last action in this block.

As shown here, I push ctrl+z twice in the top cell but start removing code from another cell (see the +2 get deleted)!
![cross-cell-undo](https://user-images.githubusercontent.com/1813603/128782023-0fd0ff05-421d-4f18-8d1b-9cfb2651f933.gif)

Even worse, at times it seems ctrl+z removes larger swaths of work including deleting cells:
![buggy-undo](https://user-images.githubusercontent.com/1813603/128782150-e467dc8a-7015-4d71-a92f-a7dbab46c575.gif)

**Comment by krassowski** [comment] 2021-08-12 20:49
Adding a help plea encountered in the wild: https://stackoverflow.com/q/68763795/6646912. Tangential to the matter, we should really make a better effort in making changelogs describe what happens to UX (as they previously did) and why.

**Comment by mlucool** [comment] 2021-08-12 23:42
One idea to improve document-wide history is to force the browser to focus on the last undo operation. This would help the undoing the+2 case above as it would jump to where the edit just happened to make it more obvious. This doesn't change my overall view from above, but I think would improve the UX for those who want to keep the new style.

**Comment by meeseeksmachine** [comment] 2021-08-15 23:19
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/how-to-limit-undo-only-to-code-edits-in-active-cell/10374/2

**Comment by hbcarlos** [comment] 2021-08-24 09:16
In my case, I also prefer a cell level undo/redo. It would be great to make it configurable but could be a bit tricky to implement.
I can work on this.

Btw, there is an RTC meeting on Mondays. We could discuss this there.
https://zoom.us/my/jovyan?pwd%3Dc0JZTHlNdS9Sek9vdzR3aTJ4SzFTQT09

**Comment by RafalSkolasinski** [comment] 2021-08-24 10:02
Well, it was working on cell-level before 3.1.x so fact that now it is a global history is just breaking my (and probably many other users) workflow...

**Comment by echarles** [comment] 2021-08-28 07:34
Hi, I wanted to make sure what is needed for the "document-wide history tracking disabling".

I have read the initial issue reported on https://github.com/jupyterlab/jupyterlab/issues/10694#issue-952117882 by @krassowski . However, I see https://github.com/jupyterlab/jupyterlab/pull/10756 implemented by @hbcarlos which disables the outputs to be undo/redo (see the false attribute):
```
    this.transact(() => {
      youtputs.delete(0, youtputs.length);
      youtputs.insert(0, outputs);
    }, false);
  }
```

I have tested that and indeed nor `z` nor `ctrl+z` has an impact on the outputs.

![Untitled](https://user-images.githubusercontent.com/226720/131209732-d6ac0a51-c75d-4157-bc57-ee75778e36f1.gif)

@krassowski @hbcarlos @mlucool Could you confirm that we need:

- A add a setting on the notebook `enableRtcUndoRedo` being `true` but default.
- If `enableRtcUndoRedo` is `true`, we keep the behavior as it is today: undo/redo on cells actions like move, edit..., but not on the outputs.
-  If `enableRtcUndoRedo` is `false`, we disable RTC (Y.js) undo/redo for everything (cells actions, outputs..), but the former CodeMirror `ctrl+z` remains.

Looking forward feedback before I implement.

**Comment by krassowski** [comment] 2021-08-28 10:44
Yes, this is independent of the output undo issue.

> Could you confirm that we need:
>
> - A add a setting on the notebook enableRtcUndoRedo being true but default.
> - If enableRtcUndoRedo is true, we keep the behavior as it is today: undo/redo on cells actions like move, edit..., but not on the outputs.
> - If enableRtcUndoRedo is false, we disable RTC (Y.js) undo/redo for everything (cells actions, outputs..), but the former CodeMirror ctrl+z remains.

Yes, that would be basically it. I would call it `enableDocumentWideUndoRedo` to represent the UX rather than implementation detail and only mention RTC in the description.

**Comment by dmonad** [comment] 2021-08-30 19:04
We could make it configurable to fall back to the old (a separate undo manager for each cell and another one for moving cells). We can achieve this with Yjs undo manager as well (just create a separate undo manager for each cell). In any case, we should use the Yjs undo manager for this. Otherwise, users will be able to undo changes from remote users.

My perception of applications is that there is usually one undo-manager for each document. This is true for all rich-text block editors I have worked with. The web is more and more evolving to a place with just a single undo-manager. The reason is that this concept is much easier to understand for newcomers. From my personal experience, it was very weird that there was a separate undo-manager for moving cells. The undo action was different depending on which element is currently selected. I don't expect that a newcomer will be able to distinguish between the different kinds of undo.

However, I see how having different undo-managers is more powerful. Ideally, we make a user study, but I don't think anyone has the time to organize this. So I proposed in last week's Jupyter Team Meeting that we should discuss again and put to a vote what the default behavior should be. We can make our arguments and then decide there.

**Comment by fcollonval** [comment] 2021-09-28 12:43
Switching to 4.0 as mentioned in #10949 this needs some thinking on the shared model structure.

**Comment by mlucool** [comment] 2021-09-30 11:27
Thinking about this a bit more - it is better to have a 95% working solution in 3.2 that is opt-in (AFAIK https://github.com/jupyterlab/jupyterlab/pull/10949 is very usable, but loses history when cells are moved) or force a breaking change and users to wait until 4.0 to bring back a feature from 2.x?

I'd vote not to wait given how much this forces changes on users concept of a notebook.

**Comment by echarles** [comment] 2021-09-30 11:37
> I'd vote not to wait given how much this forces changes on users concept of a notebook.

I love @mlucool proposal to still get this feature into 3.2 with an opt-in option. If I get thumb-ups on it, I can rebase double check https://github.com/jupyterlab/jupyterlab/pull/10949 to get it merged.

Based on the current planning, a decision (`go for 3.2 with opt-in` or `pause until 4.0`) is needed ASAP.

**Comment by blink1073** [comment] 2021-09-30 11:50
I still think we should wait until 4.0 for this one.  Even with opt-in, losing history is not a good experience.

**Comment by echarles** [comment] 2021-09-30 11:58
> I still think we should wait until 4.0 for this one. Even with opt-in, losing history is not a good experience.

To be more precise, it will only be the history of the moved cell which will be lost. The rest of the history will continue to work like it was before in jupyterlab <=2.

**Comment by blink1073** [comment] 2021-09-30 12:30
Ah, understood. Since we haven't settled on a name for the feature, I'd support adding an "experimental" prefixed setting to opt-in.

**Comment by echarles** [comment] 2021-09-30 12:44
> Ah, understood. Since we haven't settled on a name for the feature, I'd support adding an "experimental" prefixed setting to opt-in.

Wonderfull. unless I hear other opinion here, I will take over the https://github.com/jupyterlab/jupyterlab/pull/10949 (my) tomorrow with an `experimental_` prefix for the setting. It should be ready for review by (my) EOT.

**Comment by RafalSkolasinski** [comment] 2021-11-15 10:18
> In the Advanced Settings > Notebook:
> 
> ```js
> {
>     experimentalDisableDocumentWideUndoRedo: true
> }
> ```

I just tried it and it seems to do the trick! Will keep testing and report back if I encounter any problems.

**Comment by thistleknot** [comment] 2021-11-26 00:34
[additional property error] experimentalDisableDocumentWideUndoRedo is not a valid

:(

Jupyter Lab 3.1.12

**Comment by RafalSkolasinski** [comment] 2021-11-26 00:46
> [additional property error] experimentalDisableDocumentWideUndoRedo is not a valid
> 
> :(
> 
> Jupyter Lab 3.1.12

@thistleknot, according to @jasongrout this was added in 3.2 so you may just need to upgrade - this flag solved the issue for me

**Comment by adrienpacifico** [comment] 2022-01-23 20:40
Hi,
I miss what is at stake with this issue, but I do not understand why we don't interact with:
* an **overall document history** when we use the `Command mode`  
* the **cell history** when using the `Edit` mode.

Could someone explain?

I do not see the exact link with the collaborative mode as activating the `experimentalDisableDocumentWideUndoRedo` option still makes the collaborative mode working. The change of the default behaviour is to me as strange as the collaborative option is exciting!

**Comment by hbcarlos** [comment] 2022-01-24 10:58
Hi @adrienpacifico!

The problem is that notebooks in Jupyterlab have a by-cell undo/redo. When undoing changes, it acts only in the selected cell. We changed the undo/redo behavior to a document-wide undo/redo when we introduced the real-time collaboration. When undoing changes, it acts over the whole document instead of the selected cell. This was a breaking change that we introduced in 3.1 involuntarily.

The reason is that with the collaborative mode we use the undo manager from Yjs, and we can not have a cell-based undo manager because every time the user moves a cell, we have to delete the cell and create a new one losing the undo history of the cell. When using `experimentalDisableDocumentWideUndoRedo` we are disabling the Yjs undo manager and using the codemirror undo manager. In the notebook, each cell has an instance of codemirror, which translates to an individual undo manager for each cell having the expected by cell undo/redo behavior.

**Comment by adrienpacifico** [comment] 2022-01-27 06:54
Hi @hbcarlos, thank you very much for you answer! I did not get that the breaking change was involuntary. Anyhow I really enjoy the collaborative feature!

**Comment by JNYH** [comment] 2022-05-25 12:59
Thank you so much, it works! 
I've added a picture to illustrate how to disable document-wide undo/redo here: 
https://stackoverflow.com/questions/69211578

**Closed** 2023-03-10 10:14 UTC
Labels: tag:Real Time Collaboration, tag:Regression

**Comment by jiahe224** [comment] 2023-04-23 08:07
首先我提出一个可能的共识，那就是notebook更适合在初期构建、试验代码，这种情况下，每个cell都是一个小模块，用来实现相应的功能，那么，对cell内的代码修改时，光标在cell内闪烁，Ctrl-Z和Ctrl-Y应该只对此cell内的历史编辑起效，而不是整个notebook，否则有可能会删除一些已经敲定的cell。当光标不在某个具体的cell内时，也就是经典notebook的命令模式下，Z键会恢复删除的cell，但经典notebook在恢复删除的cell时会发生cell顺序错乱，希望基于jupyter lab的notebook 7能改善。实际上，我就是因为Ctrl-Z作用于整个notebook而放弃jupyter lab转而继续使用经典notebook。
First of all, I propose a possible consensus, that is, notebooks are more suitable for building and testing codes in the early stage. In this case, each cell is a small module used to realize corresponding functions. Then, for the cell When the code is modified, the cursor is blinking in the cell, Ctrl-Z and Ctrl-Y should only take effect on the historical editing in this cell, not the entire notebook, otherwise some finalized cells may be deleted. When the cursor is not in a specific cell, that is, in the command mode of the classic notebook, the Z key will restore the deleted cell, but the order of the cells will be disordered when the classic notebook restores the deleted cell. I hope that notebook 7 based on jupyter lab can improve. In fact, I gave up jupyter lab and continued to use classic notebooks because Ctrl-Z acts on the entire notebook.
