### ISSUE TITLE
some sub-folders unable to open !

### ISSUE THREAD

**Issue by maheshs11** [jupyterlab/jupyterlab#11568] opened 2021-11-28 16:39 UTC
![image](https://user-images.githubusercontent.com/7268915/143777296-182d36ca-cb7e-46dd-a72f-857e7354dceb.png)
i wanted to open the checkpoint file unable to open .
and also
![image](https://user-images.githubusercontent.com/7268915/143777361-c318f261-4934-429d-9ae0-484269c6bcc8.png)
any folder starting with a  '  .   ' dot symbol also not displayed.

**Comment by krassowski** [comment] 2021-11-28 17:16
Thank you for opening the issue, welcome!

Yes, there is an issue with opening `checkpoints` folder. This was already reported previously in #11200 which was a duplicate of #9913, making this issue a duplicate of a duplicate ;) This core problem is tracked in https://github.com/jupyter-server/jupyter_server/issues/58 - please feel welcome to contribute by helping to narrow down the cause and/or finding a fix. I spend some hours looking at it previously, so maybe a fresh look from someone new could help :)

> any folder starting with a ' . ' dot symbol also not displayed.

Please read the documentation: [Displaying Hidden files](https://jupyterlab.readthedocs.io/en/stable/user/files.html?highlight=hidden#displaying-hidden-files).

**Comment by maheshs11** [comment] 2021-11-29 10:17
> https://github.com/googlecolab/colabtools/issues/621

if not os.path.exists("proxy"):
  os.symlink("checkpoints", "proxy")

someone in google colab have same issue !
could u look into this?

**Closed** 2021-12-13 01:50 UTC
Labels: bug, status:Duplicate, status:Answered, status:Closing as Answered
