### ISSUE TITLE
Safari not caching large Javascript resources

### ISSUE THREAD

**Issue by malmaud** [jupyterlab/jupyterlab#5558] opened 2018-10-31 16:28 UTC
**Describe the bug**
Desktop Safari is not caching `vendors*.js`, resulting in ~15 MB downloads every time a remote Jupyter session is navigated to.

**To Reproduce**

* Open a Safari window and navigate to jupyter lab.
* Close the window.
* Open a new window and navigate to the same lab.  Confirm with the safari devtools that no assets are being loaded from the cache.

This isn't a big deal if the server is local, but for a remote server, this means the 14.77 MB "lab/static/vendors~main.c2e649db00cf6963e74a.js" is being re-downloaded every time jupyterlab is navigated to.

Although note that in Safari, if you reload the same frame that is displaying a notebook, then the resources IS cached and loaded from memory. So the problem is that for some reason, the javascript resources aren't being cached to disk that is shared across Safari windows. I've confirmed that Safari is caching to disk resources from other websites, so this is not a general failure of Safari to cache.

**Expected behavior**

Safari caches static resources, as Chrome does.

**Desktop (please complete the following information):**

- OS: 10.14
- Browser Safari 12.0
- JupyterLab [e.g. 0.34.2] 0.34.0

**Comment by jasongrout** [comment] 2018-11-13 01:08
So Chrome *does* cache things?

**Comment by jasongrout** [comment] 2018-11-13 01:14
I just checked, and it works for me. I have to make sure the cache is enabled, though:
<img width="837" alt="screen shot 2018-11-12 at 5 13 09 pm" src="https://user-images.githubusercontent.com/192614/48384236-529c5b00-e69e-11e8-8afe-6b3878c9fc9b.png">


(enable the cache by clicking on the second-to-last icon on the far right, that looks like a cylinder with a line through it, until it is not blue, and the tooltip reads "Ignore the resource cache when loading files")

**Comment by malmaud** [comment] 2018-11-13 13:58
And ya, chrome devtools confirms that chrome is caching the javascript bundles, even if you close the Chrome frame and open a new one.

**Comment by charliwardbd** [comment] 2019-06-04 16:47
I think that the problem its no te caching. The problem its de large javascript file. The navigator cut the petition sometimes and when you try reload if you are lucky the jupyter works.

**Comment by flixr** [comment] 2019-07-31 14:23
I'm having the same problem with JupyterLab 1.0 and Firefox.
My vendors~main.xxxx.js is ~100MB and it is never cached.
In the response headers I can see that `Cache-Control` is set to `no-cache`. Same for main.xxxxx.js

**Comment by juliusvonkohout** [comment] 2019-08-01 19:35
I can confirm that it is not cached in firefox, but in chrome for jupyterlab 1.0.4
![grafik](https://user-images.githubusercontent.com/45896133/62321961-377bb080-b4a4-11e9-95e8-63c4fbc8d332.png)

**Comment by juliusvonkohout** [comment] 2019-08-01 19:37
I can confirm that it is not cached in firefox, but in chrome for jupyterlab 1.0.4 
![grafik](https://user-images.githubusercontent.com/45896133/62322103-96d9c080-b4a4-11e9-8046-1b6ee68c7f12.png)

**Comment by jasongrout** [comment] 2019-08-01 20:08
The js is cached for me in Firefox 68 

```
conda create -n del-jlab5558 jupyterlab
conda activate del-jlab5558
conda list | grep jupyterlab
```
gives
```
jupyterlab                1.0.4                    py37_0    conda-forge
jupyterlab_server         1.0.0                      py_1    conda-forge
```
<img width="1516" alt="Screen Shot 2019-08-01 at 1 08 15 PM" src="https://user-images.githubusercontent.com/192614/62324036-7b979280-b45d-11e9-8f56-a9194d4f36df.png">

**Comment by jasongrout** [comment] 2019-08-01 20:10
I notice your vendors js file hash is different than mine. Is it a fresh install of jlab 1.0.4 with no extensions?

**Comment by jasongrout** [comment] 2019-08-01 20:12
Better screenshot, showing the cache-control header *and* the 304 not modified response:
<img width="1673" alt="Screen Shot 2019-08-01 at 1 11 38 PM" src="https://user-images.githubusercontent.com/192614/62324281-024c6f80-b45e-11e9-8e19-735dc89718f2.png">

**Comment by jasongrout** [comment] 2019-08-01 20:18
Note that `no-cache` is the expected value of that cache control header. See the difference between `no-cache` and `no-store` at https://www.cloudflare.com/learning/cdn/glossary/what-is-cache-control/

Essentially, `no-cache` is asking the browser to check to see if it has the most recent file before using the cache.

**Comment by juliusvonkohout** [comment] 2019-08-01 21:26
> Note that `no-cache` is the expected value of that cache control header. See the difference between `no-cache` and `no-store` at https://www.cloudflare.com/learning/cdn/glossary/what-is-cache-control/
> 
> Essentially, `no-cache` is asking the browser to check to see if it has the most recent file before using the cache.

Thanks for the explanation. i have found the problem. the deprecated plotly extension https://github.com/jupyterlab/jupyter-renderers/tree/master/packages/plotly-extension prevents caching and adds almost 20 Megabyte. 

I uninstalled it and caching is working.

I installed plotly-jupyterlab and the caching is again not working.

**Comment by juliusvonkohout** [comment] 2019-08-02 07:41
@jasongrout @flixr i have solved the problem. It is just firefox caching settings. By default it does not cache files over 51200 KB or 51,2 Megabyte! I changed it to 128 MB and now everything is working fine. Should we put this in the official documentation? Maybe create a bug report in the firefox bugtracker?
![grafik](https://user-images.githubusercontent.com/45896133/62352763-42b4f780-b509-11e9-8894-36bdabeb68de.png)

**Comment by flixr** [comment] 2019-08-02 10:06
@juliusvonkohout :+1: that was it

**Comment by charliwardbd** [comment] 2019-08-02 10:55
i think that it's not a good solution. 

In a platform with hundred users ..... all user must be configure the navigator?

**Comment by juliusvonkohout** [comment] 2019-08-02 11:42
@flixr @jasongrout  the solution is to use --dev-build=False everytime you install something. the javascript went down from 55 to 8 Megabyte. The developers should make this default...

**Comment by jasongrout** [comment] 2019-08-02 14:51
>  the solution is to use --dev-build=False everytime you install something

Fixing this I think is https://github.com/jupyterlab/jupyterlab/pull/6907 - just merged into master.

**Comment by jasongrout** [comment] 2019-08-02 14:53
> i have solved the problem. It is just firefox caching settings. By default it does not cache files over 51200 KB or 51,2 Megabyte!

Thanks, that explains why it was different for me, as I was using stock JLab without extensions.

**Comment by jasongrout** [comment] 2019-08-03 17:47
Can people here try the new alpha just released on pypi (not available on conda-forge):

```
pip install --pre --upgrade jupyterlab
```
This includes some recent changes to build a smaller js bundle by default.

**Comment by madsi1m** [comment] 2019-08-23 10:47
Awesome work by the way, really like the lab UX.

Any way to reduce the size of the vendors-main with some kind of minify?
Mine is about 79mb which is very big for ADSL users

**Comment by jasongrout** [comment] 2019-09-17 12:52
FYI, minification is turned on by default in the latest release of jlab.

**Comment by jasongrout** [comment] 2019-12-02 17:29
Closing as resolved. Please post a comment if this is still an issue.

**Closed by jasongrout** 2019-12-02 17:29 UTC
Labels: type:Question
