### ISSUE TITLE
UI is extremely laggy and block interaction when open a folder with lots of files

### ISSUE THREAD

**Issue by franckchen** [jupyterlab/jupyterlab#12060] opened 2022-02-16 04:11 UTC
## Description

ui is extremely laggy and block interaction when open a folder with lots of files

I'm sure it's blocking the browser main thread. bcz from the @jupyterlab/filebrowser listing [source code](https://github.com/jupyterlab/jupyterlab/blob/159b01568c3d0b22b9436f328499cd3071fc2b98/packages/filebrowser/src/listing.ts#L762) i found there are lots of DOM manipulation and these manipulation cause  layout and paint many times.

just take a look at the code blow. too many DOM manipulation. The problem is obvious.

```typescript
protected onUpdateRequest(msg: Message): void {
    this._isDirty = false;

    // Fetch common variables.
    const items = this._sortedItems;
    const nodes = this._items;
    const content = DOMUtils.findElement(this.node, CONTENT_CLASS);
    const renderer = this._renderer;

    this.removeClass(MULTI_SELECTED_CLASS);
    this.removeClass(SELECTED_CLASS);

    // Remove any excess item nodes.
    while (nodes.length > items.length) {
      content.removeChild(nodes.pop()!);
    }

    // Add any missing item nodes.
    while (nodes.length < items.length) {
      const node = renderer.createItemNode(this._hiddenColumns);
      node.classList.add(ITEM_CLASS);
      nodes.push(node);
      content.appendChild(node);
    }

    // Remove extra classes from the nodes.
    nodes.forEach(item => {
      item.classList.remove(SELECTED_CLASS);
      item.classList.remove(RUNNING_CLASS);
      item.classList.remove(CUT_CLASS);
    });

    // Add extra classes to item nodes based on widget state.
    items.forEach((item, i) => {
      const node = nodes[i];
      const ft = this._manager.registry.getFileTypeForModel(item);
      renderer.updateItemNode(
        node,
        item,
        ft,
        this.translator,
        this._hiddenColumns
      );
      if (this.selection[item.path]) {
        node.classList.add(SELECTED_CLASS);

        if (this._isCut && this._model.path === this._prevPath) {
          node.classList.add(CUT_CLASS);
        }
      }

      // add metadata to the node
      node.setAttribute(
        'data-isdir',
        item.type === 'directory' ? 'true' : 'false'
      );
    });

    // Handle the selectors on the widget node.
    const selected = Object.keys(this.selection).length;
    if (selected) {
      this.addClass(SELECTED_CLASS);
      if (selected > 1) {
        this.addClass(MULTI_SELECTED_CLASS);
      }
    }

    // ... so on
  }
```

## Reproduce

1. Create a folder with lots of files
2. From Jupyterlab enter this folder

## Expected behavior

I think we need refactor the code. React maybe helpful(concurrent mode would be more helpful in this scenario 😃)

## Context

- Operating System and version:  any system
- Browser and version:  any browser
- JupyterLab version:  any version

<details><summary>Troubleshoot Output</summary>
<pre>
None
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
None
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
None
</pre>
</details>

**Comment by fcollonval** [comment] 2022-02-16 09:34
Thanks for reporting @franckchen 

Closing as duplicate of https://github.com/jupyterlab/jupyterlab/issues/8700

**Closed by fcollonval** 2022-02-16 09:34 UTC
Labels: bug, status:Needs Triage
