### ISSUE TITLE
Error Starting Kernel

### ISSUE THREAD

**Issue by iljya** [jupyterlab/jupyterlab#9574] opened 2021-01-08 11:07 UTC
## Description
I create a new virtualenv workspace, installed Jupyter Lab, ran it but cannot create a kernel. Could someone please advise? Thanks!

![image](https://user-images.githubusercontent.com/5646495/104008184-61f98f00-51a9-11eb-926c-711e3aad1c34.png)

```
# Stack trace
Traceback (most recent call last):
      File "/home/iljya/code/envs/myenv/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/home/iljya/code/envs/myenv/lib/python3.8/site-packages/jupyter_server/services/sessions/handlers.py", line 67, in post
        model = await sm.create_session(
      File "/home/iljya/code/envs/myenv/lib/python3.8/site-packages/jupyter_server/services/sessions/sessionmanager.py", line 86, in create_session
        kernel_id = await self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "/home/iljya/code/envs/myenv/lib/python3.8/site-packages/jupyter_server/services/sessions/sessionmanager.py", line 94, in start_kernel_for_session
        kernel_id = await self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/home/iljya/code/envs/myenv/lib/python3.8/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 183, in start_kernel
        kernel_id = await ensure_async(self.pinned_superclass.start_kernel(self, **kwargs))
      File "/home/iljya/code/envs/myenv/lib/python3.8/site-packages/jupyter_client/multikernelmanager.py", line 184, in start_kernel
        km, kernel_name, kernel_id = self.pre_start_kernel(kernel_name, kwargs)
      File "/home/iljya/code/envs/myenv/lib/python3.8/site-packages/jupyter_client/multikernelmanager.py", line 169, in pre_start_kernel
        km = self.kernel_manager_factory(connection_file=os.path.join(
      File "/home/iljya/code/envs/myenv/lib/python3.8/site-packages/jupyter_client/multikernelmanager.py", line 83, in create_kernel_manager
        km = kernel_manager_ctor(*args, **kwargs)
      File "/home/iljya/code/envs/myenv/lib/python3.8/site-packages/traitlets/config/configurable.py", line 82, in __init__
        super(Configurable, self).__init__(**kwargs)
      File "/home/iljya/code/envs/myenv/lib/python3.8/site-packages/traitlets/traitlets.py", line 1080, in __init__
        super_kwargs[key] = value
      File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
        next(self.gen)
      File "/home/iljya/code/envs/myenv/lib/python3.8/site-packages/traitlets/traitlets.py", line 1214, in hold_trait_notifications
        self.notify_change(change)
      File "/home/iljya/code/envs/myenv/lib/python3.8/site-packages/traitlets/traitlets.py", line 1227, in notify_change
        return self._notify_observers(change)
      File "/home/iljya/code/envs/myenv/lib/python3.8/site-packages/traitlets/traitlets.py", line 1264, in _notify_observers
        c(event)
      File "/home/iljya/code/envs/myenv/lib/python3.8/site-packages/traitlets/traitlets.py", line 888, in compatible_observer
        return func(self, change)
    TypeError: _kernel_spec_manager_changed() takes 1 positional argument but 2 were given
```

## Reproduce

1. Install and run
```
virtualenv ~/code/myenv
pip install jupyterlab
jupyter lab
```
2. Click "Python 3" notebook to create one

I tried clearing all pip packages and installing `pip install jupyterlab==2.2.9` but that exhibited the same symptoms.

## Expected behavior

Notebook created and kernel started as usual

## Context

OS: Ubuntu 20.04.1 LTS
Browser: Chrome Version 85.0.4183.83 (Official Build) (64-bit)
JupyterLab version: 3.0.1

**Comment by jasongrout** [comment] 2021-01-08 11:09
This looks like https://github.com/jupyter/jupyter_client/pull/598 - apparently a very recent release that is being fixed soon.

Closing as a duplicate of https://github.com/jupyter/jupyter_client/pull/598

**Closed by jasongrout** 2021-01-08 11:09 UTC

**Comment by jasongrout** [comment] 2021-01-08 11:11
As a workaround, pin jupyter_client to 6.1.7: `pip install jupyter_client==6.1.7`

**Comment by iljya** [comment] 2021-01-08 11:14
Thanks so much! I looked around but didn't find that one. The workaround works!

**Comment by jasongrout** [comment] 2021-01-08 11:20
> Thanks so much! I looked around but didn't find that one. The workaround works!

I just happened to see the github notification of that one and noticed it was similar. The problematic release was done an hour or two ago.

**Comment by jasongrout** [comment] 2021-01-08 11:27
jupyter_client 6.1.10 has been released, which hopefully fixes this now.

**Comment by edzkite** [comment] 2021-01-30 00:14
@jasongrout

I installed JupyterLab 3.0.6 in a fresh conda env on Windows 10, and downgraded `jupyter_client` to 6.1.7. However, I'm still experiencing this issue, albeit with slightly different error output in terminal.

```
[E 2021-01-29 16:13:55.997 ServerApp] Failed to run command:
    ['C:/Users/kite/miniconda3/envs/jl-3.0/bin/python', '-m', 'ipykernel_launcher', '-f', 'C:\\Users\\kite\\AppData\\Roaming\\jupyter\\runtime\\kernel-70e97c90-2529-4f25-9f53-82639c924c88.json']
        PATH='C:\\Users\\kite\\miniconda3\\envs\\jl-3.0;C:\\Users\\kite\\miniconda3\\envs\\jl-3.0\\Library\\mingw-w64\\bin;C:\\Users\\kite\\miniconda3\\envs\\jl-3.0\\Library\\usr\\bin;C:\\Users\\kite\\miniconda3\\envs\\jl-3.0\\Library\\bin;C:\\Users\\kite\\miniconda3\\envs\\jl-3.0\\Scripts;C:\\Users\\kite\\miniconda3\\envs\\jl-3.0\\bin;C:\\Users\\kite\\miniconda3\\condabin;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\nodejs;C:\\Program Files (x86)\\Yarn\\bin;C:\\Program Files\\Git LFS;C:\\Program Files (x86)\\vim\\vim80;C:\\WINDOWS\\System32\\OpenSSH;C:\\WINDOWS\\System32;C:\\WINDOWS;.;C:\\WINDOWS\\system32;C:\\Go\\bin;C:\\Program Files\\PowerShell\\7;C:\\Users\\kite\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\kite\\go\\bin;C:\\ProgramData\\chocolatey\\lib\\mingw\\tools\\install\\mingw64\\bin;C:\\Users\\kite\\AppData\\Roaming\\npm;C:\\Users\\kite\\AppData\\Local\\Yarn\\bin;C:\\tools\\neovim\\Neovim\\bin;C:\\Users\\kite\\AppData\\Local\\atom\\bin;C:\\Users\\kite\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\kite\\AppData\\Local\\Microsoft\\WindowsApps;.;C:\\Users\\kite\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\bin;C:\\Users\\kite\\go\\bin'
        with kwargs:
    {'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': 'C:\\Users\\kite', 'close_fds': False}

[E 2021-01-29 16:13:55.998 ServerApp] Uncaught exception POST /api/sessions?1611965635927 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/sessions?1611965635927', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Users\kite\miniconda3\envs\jl-3.0\lib\site-packages\tornado\web.py", line 1704, in _execute
        result = await result
      File "C:\Users\kite\miniconda3\envs\jl-3.0\lib\site-packages\jupyter_server\services\sessions\handlers.py", line 70, in post
        type=mtype)
      File "C:\Users\kite\miniconda3\envs\jl-3.0\lib\site-packages\jupyter_server\services\sessions\sessionmanager.py", line 86, in create_session
        kernel_id = await self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "C:\Users\kite\miniconda3\envs\jl-3.0\lib\site-packages\jupyter_server\services\sessions\sessionmanager.py", line 94, in start_kernel_for_session
        kernel_id = await self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "C:\Users\kite\miniconda3\envs\jl-3.0\lib\site-packages\jupyter_server\services\kernels\kernelmanager.py", line 184, in start_kernel
        kernel_id = await ensure_async(self.pinned_superclass.start_kernel(self, **kwargs))
      File "C:\Users\kite\miniconda3\envs\jl-3.0\lib\site-packages\jupyter_client\multikernelmanager.py", line 185, in start_kernel
        km.start_kernel(**kwargs)
      File "C:\Users\kite\miniconda3\envs\jl-3.0\lib\site-packages\jupyter_client\manager.py", line 313, in start_kernel
        self.kernel = self._launch_kernel(kernel_cmd, **kw)
      File "C:\Users\kite\miniconda3\envs\jl-3.0\lib\site-packages\jupyter_client\manager.py", line 220, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "C:\Users\kite\miniconda3\envs\jl-3.0\lib\site-packages\jupyter_client\launcher.py", line 131, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "C:\Users\kite\miniconda3\envs\jl-3.0\lib\subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "C:\Users\kite\miniconda3\envs\jl-3.0\lib\subprocess.py", line 1207, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
[W 2021-01-29 16:13:56.004 ServerApp] Unhandled error
[E 2021-01-29 16:13:56.005 ServerApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "117",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36 Edg/88.0.705.53",
      "X-Xsrftoken": "2|213a91c1|2deedd19688f026cbd9e1d0d952d50a1|1611965602",
      "Authorization": "token 785ecf5e653aaaebff0adfb4ee01d904d54c9f47d990d2b8",
      "Content-Type": "text/plain;charset=UTF-8",
      "Accept": "*/*",
      "Origin": "http://localhost:8888",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8888/lab/tree/Untitled.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|213a91c1|2deedd19688f026cbd9e1d0d952d50a1|1611965602; username-localhost-8888=\"2|1:0|10:1611965633|23:username-localhost-8888|44:MjkxYjVlYTQ4YTZiNGQ3ZmFkYTg4N2UxOTkzZGY1NjE=|8373eaf5ca5c145e0a084189e5e46966d802911426f34901653a36f2559ee882\""
    }
[E 2021-01-29 16:13:56.005 ServerApp] 500 POST /api/sessions?1611965635927 (::1) 58.97ms referer=http://localhost:8888/lab/tree/Untitled.ipynb
```
