### ISSUE TITLE
Settings editor JSON is incorrect after saving user settings

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#8816] opened 2020-08-11 22:22 UTC
There is a regression where if you save settings in the settings editor, they come back in an incorrect format. It may have something to do with the new JSON library we are using. (cf. #8225)

## Description
![settings](https://user-images.githubusercontent.com/159529/89954972-f4f9c180-dc29-11ea-87d4-72731998af55.gif)

## Reproduce
1. Open advanced settings editor
2. Save some new user settings

**Comment by goanpeca** [comment] 2020-08-11 22:24
When saving this is popping up on the server, in case it helps

```
 Failed validating input: Additional properties are not allowed ('raw' was unexpected)

    Failed validating 'additionalProperties' in schema:
        {'additionalProperties': False,
         'definitions': {'cssOverrides': {'additionalProperties': False,
                                          'description': 'The description '
                                                         'field of each item '
                                                         'is the CSS property '
                                                         'that will be used to '
                                                         'validate an '
                                                         "override's value",
                                          'properties': {'code-font-size': {'description': 'font-size',
                                                                            'type': ['string',
                                                                                     'null']},
                                                         'content-font-size1': {'description': 'font-size',
                                                                                'type': ['string',
                                                                                         'null']},
                                                         'ui-font-size1': {'description': 'font-size',
                                                                           'type': ['string',
                                                                                    'null']}},
                                          'type': 'object'}},
         'description': 'Theme manager settings.',
         'jupyter.lab.setting-icon-label': 'Theme Manager',
         'properties': {'overrides': {'$ref': '#/definitions/cssOverrides',
                                      'default': {'code-font-size': None,
                                                  'content-font-size1': None,
                                                  'ui-font-size1': None},
                                      'description': 'Override theme CSS '
                                                     'variables by setting '
                                                     'key-value pairs here',
                                      'title': 'Theme CSS Overrides'},
                        'theme': {'default': 'JupyterLab Light',
                                  'description': 'Application-level visual '
                                                 'styling theme',
                                  'title': 'Selected Theme',
                                  'type': 'string'},
                        'theme-scrollbars': {'default': False,
                                             'description': 'Enable/disable '
                                                            'styling of the '
                                                            'application '
                                                            'scrollbars',
                                             'title': 'Scrollbar Theming',
                                             'type': 'boolean'}},
         'title': 'Theme',
         'type': 'object'}

    On instance:
        {'raw': '{\n'
                '    // Theme\n'
                '    // @jupyterlab/apputils-extension:themes\n'
                '    // Theme manager settings.\n'
                '    // *************************************\n'
                '\n'
                '    // Theme CSS Overrides\n'
                '    // Override theme CSS variables by setting key-value '
                'pairs here\n'
                '    "overrides": {\n'
                '        "code-font-size": "12px"\n'
                '    },\n'
                '\n'
                '    // Selected Theme\n'
                '    // Application-level visual styling theme\n'
                '    "theme": "JupyterLab Darka"\n'
                '}'}
```

**Comment by jasongrout** [comment] 2020-08-11 23:36
Looks like we need an updated `jupyterlab_server` released with https://github.com/jupyterlab/jupyterlab_server/pull/87

**Comment by blink1073** [comment] 2020-08-11 23:41
ohhh, I think we already did in #8225,
they just hadn't upgraded locally

**Comment by blink1073** [comment] 2020-08-11 23:42
https://github.com/jupyterlab/jupyterlab/pull/8225/files#diff-2eeaed663bd0d25b7e608891384b7298R154

**Comment by jasongrout** [comment] 2020-09-18 03:35
This should be fixed now. @afshin is going to see if he can reproduce it with the current beta and jupyterlab_server, and if not, close this.

**Closed** 2020-09-21 11:13 UTC
Labels: help wanted, tag:Settings, type:Bug
