### ISSUE TITLE
JupyterLab is getting Stuck when accessing folder with 300k Files

### ISSUE THREAD

**Issue by sarathreddy154** [jupyterlab/jupyterlab#12605] opened 2022-05-20 16:04 UTC
Hi ,

We are trying to access folder with 300k file from JupyterLab UI.We are getting stuck with 502 error and unable to carryout any other operations after this error.We have to delete that jupyter session inorder to perform any action.

We are able to 300k list files from folder using JupyterLab Terminal without any issue.Issue is happening only with Web Interface.

Do we have any configuration parameter for Jupyterhub/Jupyterlab to handle many files requests operation??

We are using below versions in our Environment.

Selected Jupyter core packages…
IPython : 7.21.0
ipykernel : 5.5.0
ipywidgets : 7.6.3
jupyter_client : 7.3.1
jupyter_core : 4.10.0
jupyter_server : 1.5.1
jupyterlab : 3.0.12
nbclient : 0.5.3
nbconvert : 6.0.7
nbformat : 5.1.2
notebook : 6.2.0
qtconsole : 5.3.0
traitlets : 5.0.5

![image](https://user-images.githubusercontent.com/76185440/169567789-21c893b9-baab-482d-ba31-654e08096f71.png)

**Comment by jweill-aws** [comment] 2022-05-26 18:37
Closing as duplicate of #10351.

**Closed by jweill-aws** 2022-05-26 18:37 UTC
Labels: bug, status:Duplicate, pkg:filebrowser, tag:Performance
