### ISSUE TITLE
Does jupyter lab build always build in dev mode?

### ISSUE THREAD

**Issue by eoinmurray** [jupyterlab/jupyterlab#5683] opened 2018-11-27 10:49 UTC
dev_build seems to default to True (https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/labapp.py#L63) 

and I it can't be unset because of this line https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/labapp.py#L70

since its true when the `--dev` flag is set and without? 

Is this intended, the reason I want it is since I want the minified assets after I install extensions?

I currently need to manually build myself to get minified assets with 

```
RUN node /opt/conda/share/jupyter/lab/staging/yarn.js
RUN node /opt/conda/share/jupyter/lab/staging/yarn.js clean
RUN node /opt/conda/share/jupyter/lab/staging/yarn.js build:prod
```

**Comment by vidartf** [comment] 2018-12-05 09:46
This seems to be a duplicate of #5661. Feel free to comment if there are any differences between the two issues, and we will reopen this.

**Closed by vidartf** 2018-12-05 09:46 UTC
Labels: tag:Build System
