### ISSUE TITLE
Load timeout dialog styling issue

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab#4421] opened 2018-04-19 15:28 UTC
Developing on a server extension that caused an error on load, I got this dialog:

![image](https://user-images.githubusercontent.com/510760/39001439-98c1543c-43f6-11e8-8ffa-b09d3ff3892b.png)

Once it finally finished, the splash screen was hidden, and a brief view of a "correct" dialog could be seen before it too was dismissed. This seems to indicate a styling issue when showing a dialog onto of the splash screen.

**Comment by vidartf** [comment] 2018-04-19 15:28
version 0.32.0

**Comment by jasongrout** [comment] 2018-04-19 17:42
Is this a duplicate of https://github.com/jupyterlab/jupyterlab/issues/4220?

**Closed** 2018-04-19 17:42 UTC
