### ISSUE TITLE
postBuild fails to open workspace on MyBinder JupyterLab 3.0.6

### ISSUE THREAD

**Issue by valhuber** [jupyterlab/jupyterlab#9795] opened 2021-02-14 00:16 UTC
In [ApiLogicServerTutorial](https://github.com/valhuber/ApiLogicServerTutorial), I followed [this example](https://github.com/jupyterlab/jupyterlab-demol), using a postBuild to start MyBinder with pre-specified workspace.

It works locally, but the notebook and terminal windows do not open on MyBinder.

It specifies JupyterLab, since I need to open windows for terminals (to run curl for a server the user creates).

<img width="1114" alt="MyBinder Initial Not Open" src="https://user-images.githubusercontent.com/5579631/107864960-dd88d480-6e16-11eb-9337-beb6015db7df.png">

**Comment by jtpio** [comment] 2021-02-17 21:32
Thanks @valhuber.

Looks like this sounds similar to this issue? https://github.com/jupyterlab/jupyterlab/issues/9590

It might be a regression in JupyterLab 3.0 which fails at restoring workspaces.

**Comment by valhuber** [comment] 2021-02-17 22:14
Yes indeed, looks the same.  Hoping this is high on the list - “arrange your workspace” is a bit of a demo-turn-off if you are new to Notebooks / lab.

**Comment by jtpio** [comment] 2021-02-17 22:21
Thanks for getting back.

Let's close this issue in favor of #9590 then. Feel free to comment there and provide more details.

Thanks!

**Closed by jtpio** 2021-02-17 22:21 UTC
