### ISSUE TITLE
Mixing federated bundle for widgets with non-federated source distributions do not work well together

### ISSUE THREAD

**Issue by maartenbreddels** [jupyterlab/jupyterlab#9289] opened 2020-11-05 15:22 UTC
## Description

If jupyter-widgets is installed as federated bundle, downstream widgets also need to be, otherwise they cannot find eachother.

## Reproduce

```
$ mamba create -n jlab3test jupyterlab=3 ipywidgets jupyterlab_widgets -c conda-forge/label/jupyterlab_rc -c conda-forge/label/jupyterlab_server_rc -c conda-forge/label/jupyterlab_widgets_rc nodejs
$ conda activate jlab3test
$ jupyter labextension install bqplot
```
Run in cell
```python
import bqplot
import numpy as np
N = 1000
x, y = np.random.normal(size=(2, N))
scale_x = bqplot.LinearScale()
scale_y = bqplot.LinearScale(min=0, max=2)
mark = bqplot.Scatter(x=x, y=y, scales={'x': scale_x, 'y': scale_y})
fig = bqplot.Figure(marks=[mark])#, axes=[axis])
fig
```

JS console:
````
````
![image](https://user-images.githubusercontent.com/1765949/98259914-fc0f4200-1f82-11eb-999f-db1cb76d7316.png)

## Context

- Operating System and version: osx
- Browser and version: chrome
- JupyterLab version: 3.0.0rc6

**Comment by jasongrout** [comment] 2020-11-05 15:31
A guess: bqplot is forcing jlab to compile in a version of the base widgets package that has the token, and the federated jlab package has a different copy of base (i.e., a different token), which it is providing to the system via sharing, but bqplot is not using.

**Comment by maartenbreddels** [comment] 2020-11-05 15:41
Does this tell you something:
```
 ~CONDA_PREFIX/share/jupyter/lab/staging$ npm ls @jupyter-widgets/jupyterlab-manager                                                   jlab3b
@jupyterlab/application-top@3.0.0-rc.6 /Users/maartenbreddels/miniconda3/envs/jlab3b/share/jupyter/lab/staging
└── (empty)

~CONDA_PREFIX/share/jupyter/lab/staging$ npm ls  @jupyter-widgets/base                                                                jlab3b
@jupyterlab/application-top@3.0.0-rc.6 /Users/maartenbreddels/miniconda3/envs/jlab3b/share/jupyter/lab/staging
├─┬ bqplot@0.5.18 invalid
│ └── @jupyter-widgets/base@3.0.0  extraneous
├─┬ jupyter-threejs@2.2.0 invalid
│ └── @jupyter-widgets/base@3.0.0  deduped extraneous
└─┬ jupyterlab-datawidgets@6.3.0 invalid
  └── @jupyter-widgets/base@3.0.0  deduped extraneous

npm ERR! invalid: bqplot@0.5.18 /Users/maartenbreddels/miniconda3/envs/jlab3b/share/jupyter/lab/staging/node_modules/bqplot
npm ERR! extraneous: @jupyter-widgets/base@3.0.0 /Users/maartenbreddels/miniconda3/envs/jlab3b/share/jupyter/lab/staging/node_modules/@jupyter-widgets/base
npm ERR! invalid: jupyter-threejs@2.2.0 /Users/maartenbreddels/miniconda3/envs/jlab3b/share/jupyter/lab/staging/node_modules/jupyter-threejs
npm ERR! extraneous: @jupyter-widgets/base@3.0.0 /Users/maartenbreddels/miniconda3/envs/jlab3b/share/jupyter/lab/staging/node_modules/@jupyter-widgets/base
npm ERR! invalid: jupyterlab-datawidgets@6.3.0 /Users/maartenbreddels/miniconda3/envs/jlab3b/share/jupyter/lab/staging/node_modules/jupyterlab-datawidgets
npm ERR! extraneous: @jupyter-widgets/base@3.0.0 /Users/maartenbreddels/miniconda3/envs/jlab3b/share/jupyter/lab/staging/node_modules/@jupyter-widgets/base
```

**Comment by jasongrout** [comment] 2020-11-06 05:41
Strategy for testing:

1. Create two extensions, extensionProvide and extensionConsume. extensionProvide will export a token, and extensionConsume will require that token and print something out from it.
2. Check what happens if extensionProvide is normal and extensionConsume is federated.
3. Check what happens if extensionProvide is federated and extensionConsume is normal.

**Comment by jasongrout** [comment] 2020-11-06 18:47
Update:

1. I created https://github.com/jasongrout/provider and https://github.com/jasongrout/consumer as clean modules from the current 3.0 extension cookiecutter. Provider provides a token and a string, consumer consumes it and prints out the string.

2. If both are installed with `jupyter labextension install`, or both are installed as federated modules, things work well.

3. If provider is installed with `labextension install`, it does *not* appear in the list of shared modules (even though the generated webpack config indicates it should be), which means the consumer installed as a federated extension does not see it. I'm currently investigating this.

**Comment by jasongrout** [comment] 2020-11-06 19:06
Investigations:
- Hypothesis: the consumer module is bringing its own copy of the provider, and somehow the paths are getting messed up or something.
  - Test: Change the consumer to not bundle the provider
  - Result: Even when the consumer does not bundle the provider, it cannot find the provider in the shared cache. This problem is the provider or the core build problem, so pursuing it there, just to even get the provider registered in the sharing system.
- Hypothesis: Locally installed extensions, from disk, have something special about them.
  - Test: Install verdaccio, publish provider to verdaccio, then install from verdaccio
  - Result: Installing from an npm server still copies the extension pack into share/jupyter/lab/extensions, and is still listed in the package.json as a local install. Interestingly, this also seems to create a dev build by default. Are we *always* going to have a dev build anytime we do labextension install?
- Hypothesis: The provider module is bundled in the application extension js bundle. Perhaps that is causing a problem with it being a top-level shared module?
  - Test: make the provider extension much bigger to get it to be its own file, or change the webpack compilation config to split *all* modules.

**Comment by jasongrout** [comment] 2020-11-07 01:06
More work-in-progress notes:

When both provider and consumer are labextension installed, with provider coming from verdaccio and consumer coming from disk, only consumer shows up in the resolutions, though both show up in dependencies. Neither is listed in register() handlers in the compiled result. Interestingly, lots of other modules are not listed in the shared modules, like application-extension (and most -extension modules).

When I labextension install both provider and consumer via local files, the provider *does* show up in the registered packages, and it also has its own js file instead of being contained in the application-extension js file.

From `ProvideSharedPlugin.js`, it's clear that we do not share a module just because it is listed in shared, but only if it is listed in shared *and* it is used as a dependency somewhere. That's why `provider` ends up shared when we install consumer and provider: when we install provider, it gets listed in the shared config, but only when it is used by consumer is it actually added as a shared module.

Now, there is a way to include the top-level module in the shared modules: [here](https://github.com/jupyterlab/jupyterlab/blob/05e704f20cc3358e3066adef8273a602a3f76e91/builder/src/extensionConfig.ts#L143-L147) and [here](https://github.com/jupyterlab/jupyterlab/blob/05e704f20cc3358e3066adef8273a602a3f76e91/builder/src/extensionConfig.ts#L48-L50). 

- [ ] Explicitly provide shared packages for all of our core packages and all plugins compiled into core. We prevent extensions from bundling core packages, so we need to make sure they are available as shared modules.

**Comment by jasongrout** [comment] 2020-11-07 06:34
Okay, I think having the producer as a labextension installed module and consumer as a federated module is fixed by #9300. Checking this...

**Comment by jasongrout** [comment] 2020-11-07 07:54
Yep, it works. See https://github.com/jupyterlab/jupyterlab/pull/9300#issuecomment-723414848

**Comment by jasongrout** [comment] 2020-11-07 07:54
So still to check: provider as a federated extension, consumer as a normal extension

**Comment by jasongrout** [comment] 2020-11-07 08:43
> So still to check: provider as a federated extension, consumer as a normal extension

Thinking out loud: This will probably take a bit more code. The problem here (in my test setup) is that the consumer bundles the provider, but instead in the main build the provider should be added as a shared extension so it can be provided by the federated extension. So one thought: for any extension installed, do the same thing we do in the federated case - add its dependencies as shared extensions. 

Another thought is to add any dependencies that are explicitly listed in the package.json of the extension (though just keep the version, don't say `bundled: false`, since that extension might be provided in another part of the build. Actually, perhaps we can say `bundled: false` unless it is installed a separate extension as well). This would mean that we need to explicitly list the dependencies we want shared - perhaps not a bad thing? However, we should probably be consistent with the federated case and just automatically list direct dependencies as shared.

**Comment by jasongrout** [comment] 2020-11-10 00:49
Thinking more about this, federated extensions automatically share and bundle all their direct dependencies. We probably want things to be behave the same if an extension is built in or installed as a federated extension. So that would mean that any extensions built into JupyterLab should also share their direct dependencies. For consistency, we probably also want to share any core extension direct dependency as well. (Right now, I think we basically just share the resolutions)

**Comment by jasongrout** [comment] 2020-11-11 04:19
#9310 should solve the other half of this problem: a compiled extension using a federated dependency. That should take care of the case @maartenbreddels is trying: for example, installing bqplot with `jupyter labextension install`, but the base manager with the federated `jupyterlab_widgets` python package.

**Comment by jasongrout** [comment] 2020-11-12 14:23
Fixed in #9310 and #9300. Thanks for bringing this up!

**Closed by jasongrout** 2020-11-12 14:23 UTC

**Comment by jasongrout** [comment] 2020-11-12 17:38
@maartenbreddels - 3.0.0rc8 was released with fixes for these issues. Can you try again with 3.0.0rc8?

**Comment by jasongrout** [comment] 2020-11-12 18:18
I tried your example above, and it still has errors, but I don't think they are inherent in the system anymore.

I think you'll need to add some metadata to the bqplot package.json to indicate that you are relying on something else providing the jlab manager package. (A similar snippet is also in the jlab 3 widget cookie cutter package.json)

```
  "jupyterlab": {
    "extension": "lib/jupyterlab-plugin",
    "sharedPackages": {
      "@jupyter-widgets/base": {
        "requiredVersion": "^2 || ^3 || ^4"
        "bundled": false,
        "singleton": true
      }
    }
  }
```

**Comment by jasongrout** [comment] 2020-11-13 21:42
> @maartenbreddels - 3.0.0rc8 was released with fixes for these issues. Can you try again with 3.0.0rc8?

3.0rc9 has an important fix for this usecase - please try that instead of rc8.

**Comment by maartenbreddels** [comment] 2020-11-26 13:20
Hi Jason,

thanks for looking into this! I finally had time to look into this again, here are my findings.

(install 3.0.0rc10)
```
$ mamba create -n jlab3h nodejs jupyterlab=3 ipywidgets jupyterlab_widgets -c conda-forge/label/jupyterlab_rc -c conda-forge/label/jupyterlab_server_rc -c conda-forge/label/jupyterlab_widgets_rc -c conda-forge
$ conda activate jlab3h
$ jupyter lab
```
Run snippet
```python
import ipywidgets as widgets
widgets.FloatSlider()
```

Works 🎉 

Install bqplot jlab3 branch https://github.com/bqplot/bqplot/pull/1222
```
$ pip install -v git+https://github.com/martinRenou/bqplot@jlab3
# not sure why this version does not work:
# $ pip install https://github.com/martinRenou/bqplot/archive/jlab3.zip
# confirm it build and is copied
$ ls $CONDA_PREFIX/share/jupyter/labextensions/
@jupyter-widgets bqplot
```

Refresh page to load bundle, and run snippet:
```python
import numpy as np
from bqplot import pyplot as plt

plt.figure(1, title='Line Chart')
np.random.seed(0)
n = 200
x = np.linspace(0.0, 10.0, n)
y = np.cumsum(np.random.randn(n))
plt.plot(x, y)
plt.show()
```

Works 🎉 

Install a 'classical' bundle (https://github.com/vidartf/ipydatawidgets/pull/40):
```
$ pip install -v git+https://github.com/maartenbreddels/ipydatawidgets@jlab3
```

Reload page, asks for rebuild `jupyterlab-datawidgets needs to be included in build`, click `build`, asks for refresh, click `Save and Reload`. Now widgets fail to display, and the js console gives me:
```
Plugin 'jupyter.extensions.datawidgets' failed to activate.
(anonymous) @ index.es6.js:282
Promise.catch (async)
(anonymous) @ index.es6.js:281
e.start @ index.es6.js:280
c @ index.out.js:470
async function (async)
c @ index.out.js:122
load (async)
e @ bootstrap.js:115
async function (async)
e @ bootstrap.js:96
37559 @ bootstrap.js:85
r @ bootstrap:18
(anonymous) @ startup:6
(anonymous) @ main.66422b943698fd748250.js:1
14:03:00.264 index.es6.js:283 Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    at $.e.resolveRequiredService (index.es6.js:197)
    at index.es6.js:155
    at Array.map (<anonymous>)
    at $.e.activatePlugin (index.es6.js:155)
    at index.es6.js:281
    at Array.map (<anonymous>)
    at $.e.start (index.es6.js:280)
    at c (index.out.js:470)
(anonymous) @ index.es6.js:283
Promise.catch (async)
(anonymous) @ index.es6.js:281
e.start @ index.es6.js:280
c @ index.out.js:470
async function (async)
c @ index.out.js:122
load (async)
e @ bootstrap.js:115
async function (async)
e @ bootstrap.js:96
37559 @ bootstrap.js:85
r @ bootstrap:18
(anonymous) @ startup:6
(anonymous) @ main.66422b943698fd748250.js:1
14:03:00.264 index.es6.js:282 Plugin 'bqplot' failed to activate.
(anonymous) @ index.es6.js:282
Promise.catch (async)
(anonymous) @ index.es6.js:281
e.start @ index.es6.js:280
c @ index.out.js:470
async function (async)
c @ index.out.js:122
load (async)
e @ bootstrap.js:115
async function (async)
e @ bootstrap.js:96
37559 @ bootstrap.js:85
r @ bootstrap:18
(anonymous) @ startup:6
(anonymous) @ main.66422b943698fd748250.js:1
14:03:00.264 index.es6.js:283 Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    at $.e.resolveRequiredService (index.es6.js:197)
    at index.es6.js:155
    at Array.map (<anonymous>)
    at $.e.activatePlugin (index.es6.js:155)
    at index.es6.js:281
    at Array.map (<anonymous>)
    at $.e.start (index.es6.js:280)
    at c (index.out.js:470)
```

Then to recover from this, we uninstall ipydatawidgets:
```
$ pip uninstall ipydatawidgets                                                                        jlab3h
Found existing installation: ipydatawidgets 4.1.1.dev0
Uninstalling ipydatawidgets-4.1.1.dev0:
  Would remove:
    /Users/maartenbreddels/miniconda3/envs/jlab3h/etc/jupyter/nbconfig/notebook.d/jupyter-datawidgets.json
    /Users/maartenbreddels/miniconda3/envs/jlab3h/lib/python3.9/site-packages/ipydatawidgets-4.1.1.dev0.dist-info/*
    /Users/maartenbreddels/miniconda3/envs/jlab3h/lib/python3.9/site-packages/ipydatawidgets/*
    /Users/maartenbreddels/miniconda3/envs/jlab3h/share/jupyter/lab/extensions/jupyterlab-datawidgets-6.3.0.tgz
    /Users/maartenbreddels/miniconda3/envs/jlab3h/share/jupyter/nbextensions/jupyter-datawidgets/extension.js
    /Users/maartenbreddels/miniconda3/envs/jlab3h/share/jupyter/nbextensions/jupyter-datawidgets/index.js
    /Users/maartenbreddels/miniconda3/envs/jlab3h/share/jupyter/nbextensions/jupyter-datawidgets/index.js.map
``` 

Refreshing does not ask to rebuild, we do it manually:
```
$ jupyter lab build
....
$ jupyter labextension list                                                                           jlab3h
JupyterLab v3.0.0rc10
/Users/maartenbreddels/miniconda3/envs/jlab3h/share/jupyter/labextensions
        bqplot v0.5.19 enabled OK
        @jupyter-widgets/jupyterlab-manager v3.0.0-alpha.2 enabled OK
```

Refresh, widgets work 👍 , but, Jupyter Lab asks `jupyterlab-datawidgets needs to be included in build` (Note that `$CONDA_PREFIX/share/jupyter/lab/extensions` is empty).

After suggested `Save and Reload`, we get the same error as above.


Maybe something is still missing from https://github.com/vidartf/ipydatawidgets/pull/40 but I thought it would be good to share the whole experience in a reproducable way.

PS: What would be the way to get rid of the jupyterlab-datawidgets extension, `jupyter lab clean && jupyter lab build` will make the widgets render in the frontend, but jupyter lab still asks `jupyterlab-datawidgets needs to be included in build` on a page refresh.

**Comment by maartenbreddels** [comment] 2020-12-02 16:34
Can we reopen this? I think also @mariobuikhuizen has similar issues with ipyvue/jupyter-vue

**Comment by jasongrout** [comment] 2020-12-02 16:49
Just to be clear, the problem now is that the build needed detection doesn't work like it should? That's a different problem than prebuilt and source extensions sharing assets with each other. If that is what is not working, can you open a new issue?

**Comment by maartenbreddels** [comment] 2020-12-02 18:51
It is still the same issue, mixing federated and normal bundles do not work. There is a new issue interleaved, that is true, I just shared all steps for reproducibility.

**Comment by jasongrout** [comment] 2020-12-02 19:06
> mixing federated and normal bundles do not work

I'm trying to nail down exactly what didn't work. As far as I can tell, installing `jupyterlab_widgets` (i.e., prebuilt core widgets extension), then doing `pip install -v git+https://github.com/maartenbreddels/ipydatawidgets@jlab3` made the core ipywidgets (like `IntSlider()`) not work anymore?

**Comment by maartenbreddels** [comment] 2020-12-02 19:08
Yes, correct, and I think the datawidget should work as well, but it reports `No provider for: jupyter.extensions.jupyterWidgetRegistry.`

**Comment by jasongrout** [comment] 2020-12-02 20:01
I'm trying to reproduce the issue. I do the following:

1. create a new conda environment with nodejs and python. 
2. `pip install --pre jupyterlab jupyterlab_widgets`
3. `pip install ipywidgets`.
4. Launch jupyterlab and check that ipywidgets is working with an int slider. It does. Great!
5. `pip install -v git+https://github.com/maartenbreddels/ipydatawidgets@jlab3`
6. I check `share/jupyter/lab/extensions`, and find jupyterlab-datawidgets-6.3.0.tgz. I untar it and see the package.json has `    "@jupyter-widgets/base": "^1 || ^2 || ^3 ||  ^4.0.0-beta.1",`, which is great.
7. `jupyter lab clean`
8. `jupyter lab build`
9. I check `share/jupyter/lab/staging/node_modules/jupyterlab-datawidgets/package.json` - yep, we still depend on base 4.0 beta 1, so we're good there.
10. however, the dependency `jupyter-datawidgets` and `jupyter-dataserializers` in node_modules do not accept the 4.0 beta 1 - that's not good.

Furthermore, all three of the packages do not have sharing config that says to not bundle the base package - they should all have that so they don't bundle in the wrong version of base themselves.

So, I would suggest fixing all three packages to have 
* `    "@jupyter-widgets/base": "^1 || ^2 || ^3 ||  ^4.0.0-beta.1",`
* The same base package sharing exclusion as in the cookiecutter: https://github.com/jupyter-widgets/widget-ts-cookiecutter/blob/eceb791e4ba1514fc0dcfb5666bf9418c926a9dd/%7B%7Bcookiecutter.github_project_name%7D%7D/package.json#L97-L101

**Comment by maartenbreddels** [comment] 2020-12-02 20:13
That's why I created the jlab3 branch, i thought that would fix it:
https://github.com/vidartf/ipydatawidgets/pull/40/files

so... it does not pick up *that* jupyter-datawidgets it seems, but probably gets them from npm 🤦 


I thought the `sharedPackages` is only relevant for fed-bundles?

**Comment by jasongrout** [comment] 2020-12-02 20:43
Setting the `sharedPackages` is important even for source extensions since it will make sure that the base bundle does not include an extra copy of the base widgets package - it will be supplied by a prebuilt extension.



> so... it does not pick up _that_ jupyter-datawidgets it seems, but probably gets them from npm 🤦

Right - the jlab build will pull dependencies directly from npm. You can work around this in testing using verdaccio.

**Comment by jasongrout** [comment] 2020-12-02 20:51
In general, you should have that "sharedPackages" exclusion for any tokens you are importing. It is done  automatically for core packages for you, but if you are using tokens from non-core packages, you'll have to do the exclusion yourself.

**Comment by maartenbreddels** [comment] 2020-12-08 12:23
The verdaccio idea was great, it got me a bit further, now I get `Class WidgetModel not found in module jupyter-datawidgets`

It seems the widget manager is looking into the `jupyter-datawidgets` module instead of `"@jupyter-widgets/base` for `WidgetModel`.

**Comment by maartenbreddels** [comment] 2020-12-08 13:11
Ok, that was a user error (I created `ipydatawidgets.DataWidget()`) which does not have a front end model set, it work if I create `w = ipydatawidgets.NDArray()`.

LTDR: it works jupyter widgets as federated bundle, ipydatawidgets as classical 🎉
