### ISSUE TITLE
Extension Manager is broken

### ISSUE THREAD

**Issue by allefeld** [jupyterlab/jupyterlab#7872] opened 2020-02-11 20:23 UTC
## Description

About half of the time when I use JupyterLab and open the Extension Manager, it is broken:

![image](https://user-images.githubusercontent.com/1738353/74274837-b29f0880-4d0a-11ea-9652-95755d124061.png)

I don't know what triggers this, it just seems to happen randomly.

Sometimes restarting the JupyerLab server restores the Extension Manager, but also not always.

The Developer Tools Console shows the error message `Failed to load resource: the server responded with a status of 500 (Internal Server Error)` along with a URL. When I open the URL outside of JupyterLab, there is a JSON response:

`{"message": "Unhandled error", "reason": null, "traceback": "Traceback (most recent call last):\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/web.py\", line 1699, in _execute\n    result = await result\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 742, in run\n    yielded = self.gen.throw(*exc_info)  # type: ignore\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py\", line 222, in get\n    extensions = yield self.manager.list_extensions()\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 735, in run\n    value = future.result()\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 742, in run\n    yielded = self.gen.throw(*exc_info)  # type: ignore\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py\", line 92, in list_extensions\n    pkg_info = yield self._get_pkg_info(name, data)\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 735, in run\n    value = future.result()\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 742, in run\n    yielded = self.gen.throw(*exc_info)  # type: ignore\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py\", line 161, in _get_pkg_info\n    outdated = yield self._get_outdated()\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 735, in run\n    value = future.result()\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/web.py\", line 1699, in _execute\n    result = await result\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/web.py\", line 1699, in _execute\n    result = await result\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 742, in run\n    yielded = self.gen.throw(*exc_info)  # type: ignore\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py\", line 222, in get\n    extensions = yield self.manager.list_extensions()\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 735, in run\n    value = future.result()\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 742, in run\n    yielded = self.gen.throw(*exc_info)  # type: ignore\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py\", line 222, in get\n    extensions = yield self.manager.list_extensions()\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 735, in run\n    value = future.result()\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 742, in run\n    yielded = self.gen.throw(*exc_info)  # type: ignore\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py\", line 92, in list_extensions\n    pkg_info = yield self._get_pkg_info(name, data)\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 735, in run\n    value = future.result()\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 742, in run\n    yielded = self.gen.throw(*exc_info)  # type: ignore\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py\", line 92, in list_extensions\n    pkg_info = yield self._get_pkg_info(name, data)\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 735, in run\n    value = future.result()\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 742, in run\n    yielded = self.gen.throw(*exc_info)  # type: ignore\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py\", line 161, in _get_pkg_info\n    outdated = yield self._get_outdated()\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 735, in run\n    value = future.result()\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 742, in run\n    yielded = self.gen.throw(*exc_info)  # type: ignore\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py\", line 161, in _get_pkg_info\n    outdated = yield self._get_outdated()\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 735, in run\n    value = future.result()\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 742, in run\n    yielded = self.gen.throw(*exc_info)  # type: ignore\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py\", line 195, in _load_outdated\n    app_options=self.app_options\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 735, in run\n    value = future.result()\n  File \"/home/ac/.conda/envs/std/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n    return self.__get_result()\n  File \"/home/ac/.conda/envs/std/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n    raise self._exception\n  File \"/home/ac/.conda/envs/std/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/commands.py\", line 550, in get_latest_compatible_package_versions\n    return handler.latest_compatible_package_versions(names)\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/commands.py\", line 1678, in latest_compatible_package_versions\n    ret = self._run([which('npm'), 'pack'] + keys, cwd=tempdir)\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/commands.py\", line 1748, in _run\n    return proc.wait()\n  File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/commands.py\", line 101, in wait\n    sys.stdout.flush()                # flush stdout buffer (actual character display)\nOSError: [Errno 5] Input/output error\n"}`

## Context

- Operating System and version: Debian 10.2
- Browser and version: Chrome Version 80.0.3987.87 (Official Build) (64-bit)
- JupyterLab version: Version 1.2.6

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        /home/ac/.conda/envs/std/bin
        /opt/conda/condabin
        /home/ac/bin
        /home/ac/bin/xbin
        /usr/local/bin
        /usr/bin
        /bin
        /usr/local/games
        /usr/games
        /snap/bin

sys.path:
        /home/ac/.conda/envs/std/bin
        /home/ac/.conda/envs/std/lib/python37.zip
        /home/ac/.conda/envs/std/lib/python3.7
        /home/ac/.conda/envs/std/lib/python3.7/lib-dynload
        /home/ac/.conda/envs/std/lib/python3.7/site-packages

sys.executable:
        /home/ac/.conda/envs/std/bin/python

sys.version:
        3.7.6 (default, Jan  8 2020, 19:59:22) 
        [GCC 7.3.0]

platform.platform():
        Linux-4.19.0-6-amd64-x86_64-with-debian-10.3

which -a jupyter:
        /home/ac/.conda/envs/std/bin/jupyter

pip list:
        Package                Version            
        ---------------------- -------------------
        asn1crypto             1.3.0              
        attrs                  19.3.0             
        backcall               0.1.0              
        bleach                 3.1.0              
        certifi                2019.11.28         
        cffi                   1.13.2             
        chardet                3.0.4              
        conda                  4.8.2              
        conda-package-handling 1.6.0              
        cryptography           2.8                
        cycler                 0.10.0             
        decorator              4.4.1              
        defusedxml             0.6.0              
        entrypoints            0.3                
        idna                   2.8                
        importlib-metadata     1.5.0              
        inflect                4.1.0              
        ipyevents              0.7.0              
        ipykernel              5.1.4              
        ipyparallel            6.2.4              
        ipython                7.12.0             
        ipython-genutils       0.2.0              
        ipywidgets             7.5.1              
        jaraco.itertools       5.0.0              
        jedi                   0.16.0             
        Jinja2                 2.11.1             
        joblib                 0.14.1             
        json5                  0.9.0              
        jsonschema             3.2.0              
        jupyter-client         5.3.4              
        jupyter-core           4.6.1              
        jupyterlab             1.2.6              
        jupyterlab-server      1.0.6              
        kiwisolver             1.1.0              
        MarkupSafe             1.1.1              
        matplotlib             3.1.3              
        mistune                0.8.4              
        mkl-fft                1.0.15             
        mkl-random             1.1.0              
        mkl-service            2.3.0              
        more-itertools         8.2.0              
        nbconvert              5.6.1              
        nbformat               5.0.4              
        notebook               6.0.3              
        numpy                  1.18.1             
        pandas                 1.0.1              
        pandocfilters          1.4.2              
        parso                  0.6.0              
        patsy                  0.5.1              
        pexpect                4.8.0              
        pickleshare            0.7.5              
        pip                    20.0.2             
        plotly                 4.5.0              
        prometheus-client      0.7.1              
        prompt-toolkit         3.0.3              
        psutil                 5.6.7              
        ptyprocess             0.6.0              
        pycosat                0.6.3              
        pycparser              2.19               
        Pygments               2.5.2              
        pyOpenSSL              19.1.0             
        pyparsing              2.4.6              
        pyrsistent             0.15.7             
        PySocks                1.7.1              
        python-dateutil        2.8.1              
        pytz                   2019.3             
        pyzmq                  18.1.1             
        requests               2.22.0             
        retrying               1.3.3              
        ruamel-yaml            0.15.87            
        scikit-learn           0.22.1             
        scipy                  1.4.1              
        seaborn                0.10.0             
        Send2Trash             1.5.0              
        setuptools             45.1.0.post20200127
        six                    1.14.0             
        statsmodels            0.11.0             
        terminado              0.8.3              
        testpath               0.4.4              
        tornado                6.0.3              
        tqdm                   4.42.0             
        traitlets              4.3.3              
        urllib3                1.25.8             
        wcwidth                0.1.8              
        webencodings           0.5.1              
        wheel                  0.34.2             
        widgetsnbextension     3.5.1              
        zipp                   2.1.0

conda list:
        # packages in environment at /home/ac/.conda/envs/std:
        #
        # Name                    Version                   Build  Channel
        _libgcc_mutex             0.1                        main  
        asn1crypto                1.3.0                    py37_0  
        attrs                     19.3.0                     py_0  
        backcall                  0.1.0                    py37_0  
        blas                      1.0                         mkl  
        bleach                    3.1.0                    py37_0  
        ca-certificates           2019.11.28           hecc5488_0    conda-forge
        certifi                   2019.11.28               py37_0    conda-forge
        cffi                      1.13.2           py37h2e261b9_0  
        chardet                   3.0.4                 py37_1003  
        conda                     4.8.2                    py37_0  
        conda-package-handling    1.6.0            py37h7b6447c_0  
        cryptography              2.8              py37h1ba5d50_0  
        cycler                    0.10.0                   py37_0  
        dbus                      1.13.12              h746ee38_0  
        decorator                 4.4.1                      py_0  
        defusedxml                0.6.0                      py_0  
        entrypoints               0.3                      py37_0  
        expat                     2.2.6                he6710b0_0  
        fontconfig                2.13.0               h9420a91_0  
        freetype                  2.9.1                h8a8886c_1  
        glib                      2.63.1               h5a9c865_0  
        gmp                       6.1.2                h6c8ec71_1  
        gst-plugins-base          1.14.0               hbbd80ab_1  
        gstreamer                 1.14.0               hb453b48_1  
        icu                       58.2                 h9c2bf20_1  
        idna                      2.8                      py37_0  
        importlib_metadata        1.5.0                    py37_0  
        inflect                   4.1.0                    py37_0  
        intel-openmp              2020.0                      166  
        ipyevents                 0.7.0                      py_0    conda-forge
        ipykernel                 5.1.4            py37h39e3cac_0  
        ipyparallel               6.2.4                    py37_0    conda-forge
        ipython                   7.12.0           py37h5ca1d4c_0  
        ipython_genutils          0.2.0                    py37_0  
        ipywidgets                7.5.1                      py_0    conda-forge
        jaraco.itertools          5.0.0                      py_0  
        jedi                      0.16.0                   py37_0  
        jinja2                    2.11.1                     py_0  
        joblib                    0.14.1                     py_0  
        jpeg                      9b                   h024ee3a_2  
        json5                     0.9.0                      py_0  
        jsonschema                3.2.0                    py37_0  
        jupyter_client            5.3.4                    py37_0  
        jupyter_core              4.6.1                    py37_0  
        jupyterlab                1.2.6                      py_0    conda-forge
        jupyterlab_server         1.0.6                      py_0  
        kiwisolver                1.1.0            py37he6710b0_0  
        ld_impl_linux-64          2.33.1               h53a641e_7  
        libblas                   3.8.0           7_h6e990d7_netlib    conda-forge
        libcblas                  3.8.0           7_h6e990d7_netlib    conda-forge
        libedit                   3.1.20181209         hc058e9b_0  
        libffi                    3.2.1                hd88cf55_4  
        libgcc-ng                 9.1.0                hdf63c60_0  
        libgfortran-ng            7.3.0                hdf63c60_0  
        liblapack                 3.8.0           7_h6e990d7_netlib    conda-forge
        libpng                    1.6.37               hbc83047_0  
        libsodium                 1.0.16               h1bed415_0  
        libstdcxx-ng              9.1.0                hdf63c60_0  
        libuuid                   1.0.3                h1bed415_2  
        libxcb                    1.13                 h1bed415_1  
        libxml2                   2.9.9                hea5a465_1  
        markupsafe                1.1.1            py37h7b6447c_0  
        matplotlib                3.1.3                    py37_0  
        matplotlib-base           3.1.3            py37hef1b27d_0  
        mistune                   0.8.4            py37h7b6447c_0  
        mkl                       2020.0                      166  
        mkl-service               2.3.0            py37he904b0f_0  
        mkl_fft                   1.0.15           py37ha843d7b_0  
        mkl_random                1.1.0            py37hd6b4f25_0  
        more-itertools            8.2.0                      py_0  
        nbconvert                 5.6.1                    py37_0  
        nbformat                  5.0.4                      py_0  
        ncurses                   6.1                  he6710b0_1  
        nodejs                    12.4.0               he1b5a44_0    conda-forge
        notebook                  6.0.3                    py37_0  
        numpy                     1.18.1           py37h95a1406_0    conda-forge
        numpy-base                1.18.1           py37hde5b4d6_1  
        openssl                   1.1.1d               h516909a_0    conda-forge
        pandas                    1.0.1            py37hb3f55d8_0    conda-forge
        pandoc                    2.2.3.2                       0  
        pandocfilters             1.4.2                    py37_1  
        parso                     0.6.0                      py_0  
        patsy                     0.5.1                      py_0    conda-forge
        pcre                      8.43                 he6710b0_0  
        pexpect                   4.8.0                    py37_0  
        pickleshare               0.7.5                    py37_0  
        pip                       20.0.2                   py37_1  
        plotly                    4.5.0                      py_0    plotly
        plotly-orca               1.2.1                         1    plotly
        prometheus_client         0.7.1                      py_0  
        prompt_toolkit            3.0.3                      py_0  
        psutil                    5.6.7            py37h516909a_0    conda-forge
        ptyprocess                0.6.0                    py37_0  
        pycosat                   0.6.3            py37h7b6447c_0  
        pycparser                 2.19                     py37_0  
        pygments                  2.5.2                      py_0  
        pyopenssl                 19.1.0                   py37_0  
        pyparsing                 2.4.6                      py_0  
        pyqt                      5.9.2            py37h05f1152_2  
        pyrsistent                0.15.7           py37h7b6447c_0  
        pysocks                   1.7.1                    py37_0  
        python                    3.7.6                h0371630_2  
        python-dateutil           2.8.1                      py_0  
        pytz                      2019.3                     py_0  
        pyzmq                     18.1.1           py37he6710b0_0  
        qt                        5.9.7                h5867ecd_1  
        readline                  7.0                  h7b6447c_5  
        requests                  2.22.0                   py37_1  
        retrying                  1.3.3                    py37_2  
        ruamel_yaml               0.15.87          py37h7b6447c_0  
        scikit-learn              0.22.1           py37hcdab131_1    conda-forge
        scipy                     1.4.1            py37h921218d_0    conda-forge
        seaborn                   0.10.0                     py_1    conda-forge
        send2trash                1.5.0                    py37_0  
        setuptools                45.1.0                   py37_0  
        sip                       4.19.8           py37hf484d3e_0  
        six                       1.14.0                   py37_0  
        sqlite                    3.31.1               h7b6447c_0  
        statsmodels               0.11.0           py37h516909a_0    conda-forge
        terminado                 0.8.3                    py37_0  
        testpath                  0.4.4                      py_0  
        tk                        8.6.8                hbc83047_0  
        tornado                   6.0.3            py37h7b6447c_1  
        tqdm                      4.42.0                     py_0  
        traitlets                 4.3.3                    py37_0  
        urllib3                   1.25.8                   py37_0  
        wcwidth                   0.1.8                      py_0  
        webencodings              0.5.1                    py37_1  
        wheel                     0.34.2                   py37_0  
        widgetsnbextension        3.5.1                    py37_0  
        xz                        5.2.4                h14c3975_4  
        yaml                      0.1.7                had09818_2  
        zeromq                    4.3.1                he6710b0_3  
        zipp                      2.1.0                      py_0  
        zlib                      1.2.11               h7b6447c_3
</pre>
</details>

## Command Line Output

When I reran JupyterLab with  `--debug`, the Extension Manager happened to work. In the last startup where the error occurred there was no error message.

**Comment by jasongrout** [comment] 2020-02-11 20:30
Here is that error formatted so we can read it:

```

/
Name

1

x="Traceback (most recent call last):\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/web.py\", line 1699, in _execute\n result = await result\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 742, in run\n yielded = self.gen.throw(*exc_info) # type: ignore\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py\", line 222, in get\n extensions = yield self.manager.list_extensions()\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 735, in run\n value = future.result()\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 742, in run\n yielded = self.gen.throw(*exc_info) # type: ignore\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py\", line 92, in list_extensions\n pkg_info = yield self._get_pkg_info(name, data)\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 735, in run\n value = future.result()\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 742, in run\n yielded = self.gen.throw(*exc_info) # type: ignore\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py\", line 161, in _get_pkg_info\n outdated = yield self._get_outdated()\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 735, in run\n value = future.result()\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/web.py\", line 1699, in _execute\n result = await result\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/web.py\", line 1699, in _execute\n result = await result\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 742, in run\n yielded = self.gen.throw(*exc_info) # type: ignore\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py\", line 222, in get\n extensions = yield self.manager.list_extensions()\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 735, in run\n value = future.result()\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 742, in run\n yielded = self.gen.throw(*exc_info) # type: ignore\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py\", line 222, in get\n extensions = yield self.manager.list_extensions()\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 735, in run\n value = future.result()\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 742, in run\n yielded = self.gen.throw(*exc_info) # type: ignore\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py\", line 92, in list_extensions\n pkg_info = yield self._get_pkg_info(name, data)\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 735, in run\n value = future.result()\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 742, in run\n yielded = self.gen.throw(*exc_info) # type: ignore\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py\", line 92, in list_extensions\n pkg_info = yield self._get_pkg_info(name, data)\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 735, in run\n value = future.result()\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 742, in run\n yielded = self.gen.throw(*exc_info) # type: ignore\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py\", line 161, in _get_pkg_info\n outdated = yield self._get_outdated()\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 735, in run\n value = future.result()\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 742, in run\n yielded = self.gen.throw(*exc_info) # type: ignore\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py\", line 161, in _get_pkg_info\n outdated = yield self._get_outdated()\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 735, in run\n value = future.result()\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 742, in run\n yielded = self.gen.throw(*exc_info) # type: ignore\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py\", line 195, in _load_outdated\n app_options=self.app_options\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py\", line 735, in run\n value = future.result()\n File \"/home/ac/.conda/envs/std/lib/python3.7/concurrent/futures/_base.py\", line 428, in result\n return self.__get_result()\n File \"/home/ac/.conda/envs/std/lib/python3.7/concurrent/futures/_base.py\", line 384, in __get_result\n raise self._exception\n File \"/home/ac/.conda/envs/std/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n result = self.fn(*self.args, **self.kwargs)\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/commands.py\", line 550, in get_latest_compatible_package_versions\n return handler.latest_compatible_package_versions(names)\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/commands.py\", line 1678, in latest_compatible_package_versions\n ret = self._run([which('npm'), 'pack'] + keys, cwd=tempdir)\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/commands.py\", line 1748, in _run\n return proc.wait()\n File \"/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/commands.py\", line 101, in wait\n sys.stdout.flush() # flush stdout buffer (actual character display)\nOSError: [Errno 5] Input/output error\n"

1

print(x)

Traceback (most recent call last):
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
 result = await result
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
 yielded = self.gen.throw(*exc_info) # type: ignore
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 222, in get
 extensions = yield self.manager.list_extensions()
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
 value = future.result()
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
 yielded = self.gen.throw(*exc_info) # type: ignore
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 92, in list_extensions
 pkg_info = yield self._get_pkg_info(name, data)
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
 value = future.result()
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
 yielded = self.gen.throw(*exc_info) # type: ignore
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 161, in _get_pkg_info
 outdated = yield self._get_outdated()
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
 value = future.result()
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
 result = await result
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
 result = await result
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
 yielded = self.gen.throw(*exc_info) # type: ignore
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 222, in get
 extensions = yield self.manager.list_extensions()
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
 value = future.result()
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
 yielded = self.gen.throw(*exc_info) # type: ignore
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 222, in get
 extensions = yield self.manager.list_extensions()
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
 value = future.result()
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
 yielded = self.gen.throw(*exc_info) # type: ignore
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 92, in list_extensions
 pkg_info = yield self._get_pkg_info(name, data)
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
 value = future.result()
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
 yielded = self.gen.throw(*exc_info) # type: ignore
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 92, in list_extensions
 pkg_info = yield self._get_pkg_info(name, data)
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
 value = future.result()
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
 yielded = self.gen.throw(*exc_info) # type: ignore
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 161, in _get_pkg_info
 outdated = yield self._get_outdated()
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
 value = future.result()
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
 yielded = self.gen.throw(*exc_info) # type: ignore
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 161, in _get_pkg_info
 outdated = yield self._get_outdated()
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
 value = future.result()
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
 yielded = self.gen.throw(*exc_info) # type: ignore
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 195, in _load_outdated
 app_options=self.app_options
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
 value = future.result()
 File "/home/ac/.conda/envs/std/lib/python3.7/concurrent/futures/_base.py", line 428, in result
 return self.__get_result()
 File "/home/ac/.conda/envs/std/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
 raise self._exception
 File "/home/ac/.conda/envs/std/lib/python3.7/concurrent/futures/thread.py", line 57, in run
 result = self.fn(*self.args, **self.kwargs)
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/commands.py", line 550, in get_latest_compatible_package_versions
 return handler.latest_compatible_package_versions(names)
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/commands.py", line 1678, in latest_compatible_package_versions
 ret = self._run([which('npm'), 'pack'] + keys, cwd=tempdir)
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/commands.py", line 1748, in _run
 return proc.wait()
 File "/home/ac/.conda/envs/std/lib/python3.7/site-packages/jupyterlab/commands.py", line 101, in wait
 sys.stdout.flush() # flush stdout buffer (actual character display)
OSError: [Errno 5] Input/output error
```

**Comment by jasongrout** [comment] 2020-02-11 20:31
Looks like there is some problem on the server side when it is trying to run npm.

**Comment by vidartf** [comment] 2020-02-12 13:03
Given the exception trace, it might be related to the `/-\-` spinner code. It is not obvious to me why the `--debug` flag should matter.

**Comment by asd1054** [comment] 2020-02-25 14:15
do u have fixed it?   
could u give me some commands?
I can't repair it .

**Comment by Felihong** [comment] 2020-03-26 16:01
+1, have the same issue here. 

Have been used the same image for a long time, and like suddenly the extension manager is broken. The problem can be resolved by uninstalling all extensions `
```
jupyter labextension uninstall --all
jupyter lab build
```
But I haven't get the logic here, anyone knows what is going on?

**Comment by tarjintor** [comment] 2020-04-02 09:50
@Felihong this works for me,but can't figure out why
and when I use
`jupyter labextension list`
the extension manager will not show in the list

and I can reproduce this
If you 
```
jupyter labextension uninstall --all
jupyter lab build
```
then restart jupyterlab,this works,but if you use 

https://jupyterlab.readthedocs.io/en/1.2.x/developer/extension_tutorial.html

to create a extension yourself

just use step 1

instead of use 
```
jlpm install
jupyter labextension install . --no-build
```
I use yarn 1.22.4 with 

```
yarn install
jupyter labextension install .
```

then you can see extension manager broken

I use jupyterlab 1.2.3

**Comment by jtpio** [comment] 2023-09-01 20:09
Closing as the extension manager has been revamped in JupyterLab 4 to install extensions from PyPI: https://jupyterlab.readthedocs.io/en/latest/user/extensions.html#managing-extensions-using-the-extension-manager

Feel free to open a new issue if needed, thanks!

**Closed by jtpio** 2023-09-01 20:09 UTC
