### ISSUE TITLE
Create 'native' Jupyter Lab notebook application

### ISSUE THREAD

**Issue by janmichiel** [jupyterlab/jupyterlab#2040] opened 2017-04-12 20:12 UTC
It would be great if Jupyter Lab notebook would handle 'as if' it was a native application.
Please look at Visual Studio Code as an example for how this would work.: The content of the application will still be pure web based technology, but rendered in a platform native window/frame

This would greatly improve the handling of application in a platform native way, including:
* Starting the notebook using a desktop/start menu shortcut, removing the need for having the notebook server run in a separate command prompt window that needs to be open at all times (server output can be shown inside notebook in a tab on the left)
* Better handling of the notebook application in a native way, including features such as a dedicated notebook application icon in the task bar (instead of being buried as one of the browser tabs), alt-tab support, etc.
* Better vertical space usage in notebook application: doing away with the web browser tabs and address bar + jupyter notebook menu bar can be converted to 'native' menu bar

**Comment by jaredly** [comment] 2017-04-13 04:30
@janmichiel have you looked at the nteract project? https://nteract.io/ It's probably what you want

**Comment by jasongrout** [comment] 2017-04-13 04:48
Try launching jupyterlab in Chrome application mode: For example, using chrome on OS X, you should be able to do:
```
jupyter lab --browser="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --app='%s'"
```
You should also be able to add something to the lab config to do this automatically.

You may also be able to do something with something like https://applicationize.me/

That said, I think it would also be interesting for someone to explore packaging JupyterLab up in an Electron app like VS Code does it.

**Comment by ellisonbg** [comment] 2017-04-13 04:54
Yep! This is a essentially a duplicate of #474.

We have a team of interns this summer that are going to tackle this. They are getting started in the next month and we will start to report back regularly.

**Comment by jasongrout** [comment] 2017-04-13 04:55
Great. Let's close this as a duplicate and move the discussion over there to keep it in one place. @janmichiel - thanks for bringing this up!

**Closed by jasongrout** 2017-04-13 04:55 UTC
