### ISSUE TITLE
docker build failed because user group with GID 20 already exists

### ISSUE THREAD

**Issue by FoSuCloud** [jupyterlab/jupyterlab#15663] opened 2024-01-19 10:26 UTC
## Description

First execute the script: `sh docker/start.sh`
The GID of my computer user is 20
<img width="1386" alt="截屏2024-01-19 18 20 28" src="https://github.com/jupyterlab/jupyterlab/assets/49218295/e69db997-9a89-408d-8c64-27e48d709f21">

error: 
`groupmod: GID '20' already exists`
<img width="1382" alt="截屏2024-01-19 18 23 06" src="https://github.com/jupyterlab/jupyterlab/assets/49218295/b0a9bdca-1d8d-4f02-8a8e-21ebefb8b538">

reason:
in start.sh
    `docker build  --build-arg NEW_MAMBA_USER_ID=$UID --build-arg NEW_MAMBA_USER_GID=$GID $ROOT_DIR -f $SCRIPT_DIR/Dockerfile -t $IMAGE_TAG`
The default variable `ARG NEW_MAMBA_USER_GID=57440` of the `docker/Dockerfile` file has been overwritten to `20`

## Reproduce

sh docker/start.sh

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment] 2024-01-19 10:29
Is this related to https://github.com/jupyterlab/jupyterlab/issues/15654?

**Comment by FoSuCloud** [comment] 2024-01-19 10:31
> Is this related to #15654?这与#15654有关吗？
No, I don't think it's the same problem, I was successful on this command: 
`RSYNC_CMD="rsync -ar /home/$DEV_USER/jupyterlab_cache/node_modules/. /home/$DEV_USER/jupyterlab/node_modules"`

**Comment by pipilacha** [comment] 2024-01-19 16:10
The GID 20 is already being used in the micromamba image which is the base image for jupyterlab.

Groups used in the micromamba image:
![image](https://github.com/jupyterlab/jupyterlab/assets/44210264/8d003fc4-ae8c-46b6-a692-5a7733b3e64f)

**Comment by trungleduc** [comment] 2024-01-25 09:01
> > The GID 20 is already being used in the micromamba image which is the base image for jupyterlab.
> > Groups used in the micromamba image: ![image](https://private-user-images.githubusercontent.com/44210264/298126667-8d003fc4-ae8c-46b6-a692-5a7733b3e64f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NDg2NTEsIm5iZiI6MTcwNTc0ODM1MSwicGF0aCI6Ii80NDIxMDI2NC8yOTgxMjY2NjctOGQwMDNmYzQtYWU4Yy00NmI2LWE2OTItNWE3NzMzYjNlNjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDEwNTkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2N2M0ZjRmNTIzODBiNDQ0YjEwZDM2NGVjYjBiZTgxZDBjMDkyZWExNTY0N2IyMmY3NjZjOWRiMzdlNmZkMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bJomOqD8iPBCcM0gJkr_lFQrDaCHKdIW8b3bEvzVBXw)
> 
> You are right. I think it is possible to use the default value ARG NEW_MAMBA_USER_GID=57440 directly.

No, you need to have the same UID and GID of your host machine to be able to start jupyterlab in dev mode and edit your files from the container.

**Comment by Mehak261124** [comment] 2024-02-19 20:18
As a student eager to contribute to open source, I've been diving into JupyterLab lately. However, while setting up the codebase on my macOS, I hit a snag. The error message I encountered reads: 

ERROR: failed to solve: process "/usr/local/bin/_dockerfile_shell.sh if [ \"$(id ${MAMBA_USER} -u)\" != \"$NEW_MAMBA_USER_ID\" ]; then   usermod \"-u ${NEW_MAMBA_USER_ID}\" \"${MAMBA_USER}\";   fi" did not complete successfully: exit code: 4.
                                                                                                                     
Upon researching, I discovered a similar issue reported by another contributor last month. Despite trying various troubleshooting steps, I have not been successful in resolving it.
I am reaching out to seek guidance on how to tackle this problem effectively. Additionally, once a solution is identified, I am eager to contribute by improving the project documentation and sharing the fix. I believe that enhancing the documentation will not only benefit future contributors but also foster a more accessible and collaborative environment.
@krassowski  @trungleduc  @JasonWeill  @pipilacha  @FoSuCloud 

<img width="1440" alt="Screenshot 2024-02-20 at 12 36 12 AM" src="https://github.com/jupyterlab/jupyterlab/assets/145124929/38c3702a-ef21-49a2-b2cd-683d81f1405d">

**Comment by krassowski** [comment] 2024-02-19 20:27
@Mehak261124 I had just merged https://github.com/jupyterlab/jupyterlab/pull/15699, let us know if it fixed it.

**Closed** 2024-02-19 20:27 UTC
Labels: bug

**Comment by trungleduc** [comment] 2024-02-20 03:48
@Mehak261124  it looks like the issue is because your current uid in your host system is 0. I don't think #15699 fixed this issue. We are trying to ensure that the user inside the docker container has the same UID and GID as the host system user. Could you try to add the[ `-o` option](https://linux.die.net/man/8/usermod) to the `usermod` command? it will allow to change the user ID to a non-unique value.
