### ISSUE TITLE
Folder retained in Favorites even after it is deleted

### ISSUE THREAD

**Issue by suganya-sk** [jupyterlab/jupyterlab#14563] opened 2023-05-18 09:31 UTC
## Description

When I mark a folder as Favorite and then delete it, it is still retained in the Favorites section of the File Browser.

Refreshing file browser and refreshing the whole page did not help. 
## Reproduce
1. Right click on a folder and select "Add Favorite"
2. The folder shows up immediately, w/o any refresh in the Favorites section of the file browser 
3. Now, delete the folder; the folder is still present in the Favorites section
4. Click on "Refresh file browser"; the folder is still present in the Favorites section
5. Reload the page; the folder is still present in the Favorites section
## Expected behavior

The folder is no longer listed in Favorites once it has been deleted.

## Context
- Browser and version: Chrome 113
- JupyterLab version: 3.6.2

**Comment by krassowski** [comment] 2023-05-18 09:51
This seems to relate to `jupyterlab-favorites` and be a duplicate of https://github.com/jupyterlab-contrib/jupyterlab-favorites/issues/7, correct?

**Comment by JasonWeill** [comment] 2023-05-23 16:14
Per @krassowski , this is an issue in the `jupyterlab-favorites` extension. Closing in favor of https://github.com/jupyterlab-contrib/jupyterlab-favorites/issues/7

**Closed by JasonWeill** 2023-05-23 16:14 UTC
Labels: bug, status:Needs Triage
