### ISSUE TITLE
-y does not confirm exit prompt

### ISSUE THREAD

**Issue by laundmo** [jupyterlab/jupyterlab#9585] opened 2021-01-09 13:49 UTC
## Description

When running jupyter lab with -y and pressing ctrl+c to stop, it still prompts for "Shutdown this jupyter server"
![image](https://user-images.githubusercontent.com/24855949/104093156-00105680-5289-11eb-8021-f92061d77c65.png)

## Reproduce

1. Run jupyter lab with the `-y` flag
2. Press `ctrl + C` to stop jupyter lab
3. Observe it asking for a confirmation.

## Expected behavior

I expect `-y` to skip the confirmation. 

## Context

Running in WSL, with a largely default config, where the only changed variables are:
```
c.ServerApp.browser = '/mnt/c/Program Files/Mozilla Firefox/firefox.exe'
c.ServerApp.use_redirect_file = False
```

- Operating System and version: Windwos 10 + WSL Ubuntu 18
- JupyterLab version: 3.0.2 (3.0.3 has another issue with authentication)

<details><summary>Command Line Output</summary>
<pre>
jupyter lab --allow-root -y
[I 2021-01-09 14:42:36.621 ServerApp] jupyterlab | extension was successfully linked.
[I 2021-01-09 14:42:36.947 ServerApp] nbclassic | extension was successfully linked.
[I 2021-01-09 14:42:36.976 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.6/dist-packages/jupyterlab
[I 2021-01-09 14:42:36.976 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 2021-01-09 14:42:36.979 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-01-09 14:42:36.984 ServerApp] nbclassic | extension was successfully loaded.
[I 2021-01-09 14:42:36.984 ServerApp] Serving notebooks from local directory: /mnt/d/user/Documents
[I 2021-01-09 14:42:36.984 ServerApp] Jupyter Server 1.2.1 is running at:
[I 2021-01-09 14:42:36.984 ServerApp] http://localhost:8888/lab?token=
[I 2021-01-09 14:42:36.984 ServerApp]  or http://127.0.0.1:8888/lab?token=
[I 2021-01-09 14:42:36.985 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2021-01-09 14:42:36.992 ServerApp]

    To access the server, open this file in a browser:
        file:///home/l/.local/share/jupyter/runtime/jpserver-15471-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=
     or http://127.0.0.1:8888/lab?token=
[W 2021-01-09 14:42:41.264 LabApp] Could not determine jupyterlab build status without nodejs
^C[I 2021-01-09 14:42:46.580 ServerApp] interrupted
Serving notebooks from local directory: /mnt/d/lauri/Documents
0 active kernels
Jupyter Server 1.2.1 is running at:
http://localhost:8888/lab?token=
 or http://127.0.0.1:8888/lab?token=
Shutdown this Jupyter server (y/[n])?
</pre>
</details>

**Comment by jasongrout** [comment] 2021-01-13 20:41
Setting as 3.0, as it appears to be a regression linked to moving to Server.

CC @Zsailer @blink1073 as well.

**Comment by jasongrout** [comment] 2021-01-13 20:43
Looks like `jupyter server -y` also prompts on exit, instead of promptly exiting.

**Comment by jasongrout** [comment] 2021-01-13 20:49
Actually, it looks like Jupyter Notebook 6.1.6 also prompts on exit, even if we give `-y`, so this is not a regression.

Looking through the code, it seems that the only place this `answer_yes` configuration is used is here: https://github.com/jupyter/jupyter_core/blob/ed132166c929fa9dff942a499e97bb29f33fc20f/jupyter_core/application.py#L119

It seems like it should also be used for the shutdown confirmation, but since it hasn't been like that (as far as I can tell) ever, it is not a regression, so I'm moving this off the 3.0 milestone. The discussion should probably should be taken up in the Jupyter Server repo rather than here.

**Comment by jasongrout** [comment] 2021-01-13 20:49
@laundmo - can you file this issue in the Jupyter Server repo at https://github.com/jupyter-server/jupyter_server?

**Comment by laundmo** [comment] 2021-01-13 21:47
@jasongrout im assuming you cannot transfer the issue? i will recreate it over there in a bit if you cant move it.

**Comment by jasongrout** [comment] 2021-01-13 22:20
Right - we can't transfer issues across different orgs.

**Comment by jasongrout** [comment] 2021-01-13 23:16
Opened at jupyter-server/jupyter_server#383

**Closed by jasongrout** 2021-01-13 23:16 UTC
