### ISSUE TITLE
Extra rectangle under the Console menu on Safari

### ISSUE THREAD

**Issue by willingc** [jupyterlab/jupyterlab#948] opened 2016-09-23 16:27 UTC
![screen shot 2016-09-23 at 9 25 39 am](https://cloud.githubusercontent.com/assets/2680980/18793498/e5781892-816f-11e6-9c38-4970c54d3edb.png)

**Comment by jasongrout** [comment] 2016-09-26 12:19
Is that when you click on the Console menu, and expect a full menu? It looks like perhaps there was an error in populating the menu. Is it reproducible?

**Comment by willingc** [comment] 2016-09-27 14:40
@jasongrout Yes. Reproducible on latest version of Safari and the Safari Technology Preview for OSX 10.11.6. Works ok on Chrome. 
<img width="286" alt="screen shot 2016-09-27 at 07 37 07" src="https://cloud.githubusercontent.com/assets/2680980/18878382/3e87715e-8485-11e6-95c8-65a58f6b23cd.png">
<img width="288" alt="screen shot 2016-09-27 at 07 37 39" src="https://cloud.githubusercontent.com/assets/2680980/18878403/4e9a8b08-8485-11e6-9bde-bf86a9eb8bd1.png">
<img width="379" alt="screen shot 2016-09-27 at 07 38 38" src="https://cloud.githubusercontent.com/assets/2680980/18878465/7f4ae6e4-8485-11e6-8ae6-89ecbdc1c8b8.png">

**Comment by Deborah-Digges** [comment] 2016-10-09 12:03
This is the error message I see in the browser console:

```
http://localhost:8888/lab/es6-promise.map
Failed to load resource: the server responded with a status of 404 (Not Found)
```

Safari isn't able to find es6-promise.map

**Comment by ellisonbg** [comment] 2017-12-19 06:10
Fixed in master with menu redesign.

**Closed by ellisonbg** 2017-12-19 06:10 UTC
Labels: pkg:application, type:Bug
