### ISSUE TITLE
Server side execution not working with jupyter-server-nbmodel

### ISSUE THREAD

**Issue by ujjawal-khare** [jupyterlab/jupyterlab#16877] opened 2024-10-18 07:26 UTC
## Description
Installed jupyter 4.2.5 and  jupyter-server-nbmodel and tried executing cell, it is not even executing cell

## Reproduce

- Install juoyterlab 4.2.5
- Install  jupyter-server-nbmodel extension
- Refresh the web page
- Try executing the cell with code. print(1)

## Expected behavior

Code should execute with server side execution.

## Context

I am running code MacOS M1 in fresh virtualenv

Screenshot
<img width="1723" alt="Screenshot 2024-10-18 at 12 53 08 PM" src="https://github.com/user-attachments/assets/8c09fed2-baa1-485b-81d9-e9b0ee510507">

**Comment by echarles** [comment] 2024-10-19 07:44
Hi @ujjawal-khare, I have quickly discussed the issue you are reporting with @fcollonval and the cause may just be that your server has not been restarted (if that is the case, this is a generic issue about client+server side extensions, not tighed to jupyter-server-nbmodel). Could you restart and try again?

If you are still facing issues, I suggest that you open an new issue on https://github.com/datalayer/jupyter-server-nbmodel for now. We are discussing with @krassowski and @Zsailer to let evolve that repo to other places.

Also please take into account that it is still WIP (see the version being alpha) - Though we are super interested in any early user feedback about usage and use case :+1:

**Comment by JasonWeill** [comment] 2024-10-29 16:19
Closing per @echarles 's comment. @ujjawal-khare if you are still seeing problems, please open an issue against jupyter-server-nbmodel here: https://github.com/datalayer/jupyter-server-nbmodel/issues . Thanks!

**Closed by JasonWeill** 2024-10-29 16:19 UTC
Labels: bug, status:Needs Info, status:Needs Triage
