### ISSUE TITLE
SymPy printing in the console

### ISSUE THREAD

**Issue by asmeurer** [jupyterlab/jupyterlab#389] opened 2016-07-14 22:32 UTC
I would like to get SymPy printing working well in the console. I don't know if this requires changes to SymPy, or just to jupyterlab. 

There are two main issues. This is what I get as of now (note, you will need LaTeX installed to reproduce this):

<img width="294" alt="screenshot 2016-07-14 17 28 52" src="https://cloud.githubusercontent.com/assets/71486/16857890/8a8966de-49e8-11e6-9967-79f001e36d9f.png">

Two issues here:
- It is not using MathJax. This could be a SymPy issue, as we do try to detect the frontend for things (and not enable latex math in some cases, because the frontent LaTeX rendering is crappy if it's not MathJax).
- The png images, which SymPy is generating from the system `latex`, are not rendered at retina resolution. I noticed this issue in the Jupyter notebook as well (using `init_printing(use_latex='png')`), so perhaps that is also an issue with upstream SymPy, or with one of jupterlab's dependencies. 

I'll be at the SciPy sprints if someone wants to look at this with me there.

**Comment by fperez** [comment] 2016-07-14 23:06
Yup, here's for reference a side-by-side comparison of how sympy renders in Lab (left) and the "classic" notebook (right):

![image](https://cloud.githubusercontent.com/assets/57394/16858559/931ad938-49dc-11e6-8d6f-50813913d416.png)

I think the issue is simply that in Lab, our selection order from the output mimebundle is different than in classic.

Eventually we need to offer a better UI for selecting output types from bundles, rather than that behavior being hardcoded to each client.  It gets a bit messy in terms of how to balance flexibility (global defaults, per-notebook, per-session, per-output, etc) with simplicity of UI.

I'm going to tag this as 0.90 feature-parity, but only in as much as we should offer the current experience of Classic Notebook to Sympy users.  The notion of an improved UI for output type selection is just me thinking out loud...

**Comment by fperez** [comment] 2016-07-14 23:07
Sorry, I should have said 1.0... 0.90 is really bare-minimal functionality, which at least does work already (if not ideally).  I don't want to overload the 0.90 milestone to the point of making it meaningless.

**Comment by asmeurer** [comment] 2016-07-14 23:11
I think the first point is a SymPy issue:

<img width="560" alt="screenshot 2016-07-14 18 10 05" src="https://cloud.githubusercontent.com/assets/71486/16858681/3c43aace-49ee-11e6-8933-11b2012d79e2.png">

The issue is, as I said, SymPy explicitly doesn't render itself as LaTeX unless it detects that its in the notebook, because the default LaTeX rendering in the qtconsole is crappy (worse than what we can provide with our `png` renderer).

**Comment by asmeurer** [comment] 2016-07-14 23:14
[This](https://github.com/sympy/sympy/blob/master/sympy/interactive/printing.py#L390) is how it checks.

**Comment by fperez** [comment] 2016-07-14 23:20
Ah, you do a sympy-side check, got it.  That means you probably work differently even in a qt console if the kernel is internal than if it's pre-started (external to the qt console), since it won't be detected by that code the same way.

Still, our rendering defaults are different in the Lab and classic notebooks: my screenshot above is of *the same notebook document* opened simultaneously in both.  And in that sense, I think for ease of users' transition, we should offer pure feature parity for now.

**Comment by asmeurer** [comment] 2016-07-15 03:37
That's right. The real feature we want is the ability to redefine the display precedence for the different front ends, so that we can tell the qtconsole to never try to render math, but for now, this is how we work around it.

**Comment by Carreau** [comment] 2016-07-15 06:21
IIRC [but I'm unsure] is that this is link to QtConsole saying it was able to render Html for a long time. Though the ability of QT to render  html was more and more discutable, so it should not be the case anymore.

**Comment by asmeurer** [comment] 2016-07-15 14:47
Can the qtconsole render mathjax?

**Comment by fperez** [comment] 2016-07-15 16:55
@asmeurer, I'm nearly certain the answer is no.  It's a fairly basic HTML renderer, without any JS support that I know of:

![image](https://cloud.githubusercontent.com/assets/57394/16882127/3d49c712-4a72-11e6-8cd1-1a3a5a5ebe88.png)

**Comment by asmeurer** [comment] 2016-07-18 01:08
Actually, I looked closer, and I think I might be wrong. That check is only checking for the jupyter console. From what I can tell, the issue here is that the jupyter qtconsole prefers png over math (I vaguely remember convincing you guys to do that, CC @Carreau). But I guess the jupyter lab is doing that too? It shouldn't. It should prefer to render math, same as the notebook, since it can use MathJax. 

I would need to do more digging to verify that this is indeed the case, unless a Jupyter developer can confirm/deny it for me.

**Comment by fperez** [comment] 2016-07-18 18:01
Yes @asmeurer, that's what I pointed out [above](https://github.com/jupyter/jupyterlab/issues/389#issuecomment-232818026).  Right now, the Lab render order priority is different from Classic, so for now a first order of business is just to do the same thing we used to (if nothing else, to keep the experience consistent while people make the transition and often use both in the process).

Later on, as a feature enhancement, we can consider offering UI and mechanisms for selecting/changing that order (and that's where I think there's some UX thinking to be done to balance flexibility and simplicity).

**Comment by asmeurer** [comment] 2016-07-18 18:03
I don't care so much about a UI as an API. SymPy knows the best which backends will render the best.

**Comment by jasongrout** [comment] 2016-07-19 15:50
> The real feature we want is the ability to redefine the display precedence for the different front ends

@asmeurer, to summarize, I think your actionable suggestion right now is this, right? Can you open an issue about that general topic where we can discuss it? For example, I can see the other point of view, that the number of frontends will explode and evolve rapidly, and you'll always be chasing to catch up with the capabilities of the frontend or add new frontends.

**Comment by jasongrout** [comment] 2016-07-19 15:51
That said, I think it makes a lot of sense for there to be content/capability negotiation between frontends and some level of the backend, to avoid transferring unnecessary content over the network.

**Comment by asmeurer** [comment] 2016-07-19 18:41
There's probably already an issue for it somewhere (not sure where that would be). It's something we've been discussing ever since the notebook first came out. 

I agree that there could be a lot of frontends, which is why the frontends should be responsible for setting reasonable defaults (e.g., the browser-based frontends know that they will be good at displaying math, and the non-browser ones know that they won't be).

**Comment by ian-r-rose** [comment] 2018-09-06 15:57
I just checked this, and the notebook and console in lab appear to be selecting MathJax rendering rather than png rendering, so the original issue seems resolved.

**Closed by ian-r-rose** 2018-09-06 15:57 UTC
Labels: pkg:notebook, tag:Feature Parity, type:Bug
