### ISSUE TITLE
Setting JUPYTERLAB_DIR causes jupyterlab to stop working

### ISSUE THREAD

**Issue by pmav99** [jupyterlab/jupyterlab#5881] opened 2019-01-18 11:47 UTC
This issue has the same symptoms as #3487 but that one was for an older jupyterlab version and the original issuer used a workaround (linking etc). I am opening a new issue because I think that I have a clear reproducer here.

More specifically it seems that directly setting `$JUPYTERLAB_DIR` causes jupyterlab to stop working.

Also related to #5653. 

**Describe the bug**
Instead of a normal jupyterlab session I see an error with the following message
```
Cannot find template: "index.html"

In "/home/testuser/.config/jupyter/lab/static"
```

**To Reproduce**
Just do the following
```
# create a new user
adduser -m -s /bin/bash testuser

# become the new user and move to his home directory
sudo su - testuser
cd

# create a virtualenv and activate it
python -mvenv venv
source venv/bin/activate

# install jupyterlab
pip install wheel
pip install jupyterlab

# start jupyterlab
jupyter lab
# Go to the browser and test. Everything works fine. 
# Close jupyter lab (ctrl + C)

# set JUPYTERLAB_DIR
export JUPYTERLAB_DIR=$HOME/.config/jupyter/lab
mkdir -p $JUPYTERLAB_DIR

# try to run jupyter lab again
jupyter lab

# Go to the browser to test. You will get the following error
Cannot find template: "index.html"
In "/home/testuser/.config/jupyter/lab/static"
```
If you need to cleanup just use: `sudo userdel -r testuser`

**Expected behavior**
Just a normal jupyterlab session

**Desktop (please complete the following information):**

- OS: Archlinux + Ubuntu 18.04
- Browser firefox
- JupyterLab 0.35.4

**Additional context**
<details><summary>Troubleshoot Output</summary>
<pre>
$ jupyter troubleshoot
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
$PATH:
	/home/foo/venv/bin
	/home/foo/venv/bin
	/usr/local/bin
	/usr/bin
	/bin
	/usr/local/games
	/usr/games

sys.path:
	/home/foo/venv/bin
	/usr/lib/python36.zip
	/usr/lib/python3.6
	/usr/lib/python3.6/lib-dynload
	/home/foo/venv/lib/python3.6/site-packages

sys.executable:
	/home/foo/venv/bin/python3

sys.version:
	3.6.7 (default, Oct 22 2018, 11:32:17) 
	[GCC 8.2.0]

platform.platform():
	Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic

which -a jupyter:
	/home/foo/venv/bin/jupyter
	/home/foo/venv/bin/jupyter

pip list:
	backcall (0.1.0)
	bleach (3.1.0)
	decorator (4.3.0)
	defusedxml (0.5.0)
	entrypoints (0.3)
	ipykernel (5.1.0)
	ipython (7.2.0)
	ipython-genutils (0.2.0)
	jedi (0.13.2)
	Jinja2 (2.10)
	jsonschema (2.6.0)
	jupyter-client (5.2.4)
	jupyter-core (4.4.0)
	jupyterlab (0.35.4)
	jupyterlab-server (0.2.0)
	MarkupSafe (1.1.0)
	mistune (0.8.4)
	nbconvert (5.4.0)
	nbformat (4.4.0)
	notebook (5.7.4)
	pandocfilters (1.4.2)
	parso (0.3.1)
	pexpect (4.6.0)
	pickleshare (0.7.5)
	pip (9.0.1)
	pkg-resources (0.0.0)
	prometheus-client (0.5.0)
	prompt-toolkit (2.0.7)
	ptyprocess (0.6.0)
	Pygments (2.3.1)
	python-dateutil (2.7.5)
	pyzmq (17.1.2)
	Send2Trash (1.5.0)
	setuptools (39.0.1)
	six (1.12.0)
	terminado (0.8.1)
	testpath (0.4.2)
	tornado (5.1.1)
	traitlets (4.3.2)
	wcwidth (0.1.7)
	webencodings (0.5.1)
	wheel (0.32.3)
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
$ jupyter lab --debug
[D 13:42:15.167 LabApp] Searching ['/home/foo', '/home/foo/.jupyter', '/home/foo/venv/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 13:42:15.168 LabApp] Looking for jupyter_config in /etc/jupyter
[D 13:42:15.168 LabApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 13:42:15.168 LabApp] Looking for jupyter_config in /home/foo/venv/etc/jupyter
[D 13:42:15.168 LabApp] Looking for jupyter_config in /home/foo/.jupyter
[D 13:42:15.168 LabApp] Looking for jupyter_config in /home/foo
[D 13:42:15.169 LabApp] Looking for jupyter_notebook_config in /etc/jupyter
[D 13:42:15.169 LabApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 13:42:15.169 LabApp] Looking for jupyter_notebook_config in /home/foo/venv/etc/jupyter
[D 13:42:15.169 LabApp] Looking for jupyter_notebook_config in /home/foo/.jupyter
[D 13:42:15.169 LabApp] Looking for jupyter_notebook_config in /home/foo
[D 13:42:15.335 LabApp] Paths used for configuration of jupyter_notebook_config: 
    	/etc/jupyter/jupyter_notebook_config.json
[D 13:42:15.336 LabApp] Paths used for configuration of jupyter_notebook_config: 
    	/usr/local/etc/jupyter/jupyter_notebook_config.json
[D 13:42:15.337 LabApp] Paths used for configuration of jupyter_notebook_config: 
    	/home/foo/venv/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
    	/home/foo/venv/etc/jupyter/jupyter_notebook_config.json
[D 13:42:15.337 LabApp] Paths used for configuration of jupyter_notebook_config: 
    	/home/foo/.jupyter/jupyter_notebook_config.json
[I 13:42:15.340 LabApp] JupyterLab extension loaded from /home/foo/venv/lib/python3.6/site-packages/jupyterlab
[I 13:42:15.340 LabApp] JupyterLab application directory is /home/foo/.config/jupyter
[W 13:42:15.341 LabApp] JupyterLab server extension not enabled, manually loading...
[I 13:42:15.343 LabApp] JupyterLab extension loaded from /home/foo/venv/lib/python3.6/site-packages/jupyterlab
[I 13:42:15.343 LabApp] JupyterLab application directory is /home/foo/.config/jupyter
[I 13:42:15.344 LabApp] Serving notebooks from local directory: /home/foo
[I 13:42:15.344 LabApp] The Jupyter Notebook is running at:
[I 13:42:15.344 LabApp] http://localhost:8888/?token=e4043b78889b58e56a5be184e454b1560ae646868d449ca6
[I 13:42:15.344 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 13:42:15.347 LabApp] No web browser found: could not locate runnable browser.
[C 13:42:15.347 LabApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/foo/.local/share/jupyter/runtime/nbserver-17036-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=e4043b78889b58e56a5be184e454b1560ae646868d449ca6
[D 13:42:22.373 LabApp] Using contents: services/contents
[D 13:42:22.374 LabApp] 304 GET /lab (::1) 2.13ms
</pre>
</details>

**Comment by jasongrout** [comment] 2019-01-25 07:00
This may be related to #5653.

**Comment by GuillaumeDesforges** [comment] 2019-05-13 16:34
Same issue installing from pacman while trying to do a clean install and activate ipywidget, following the advice here : https://wiki.archlinux.org/index.php/Jupyter

**Comment by blink1073** [comment] 2019-05-15 08:23
I can reproduce, assigning to myself for 1.0.

**Comment by blink1073** [comment] 2019-05-18 09:03
This appears to be fixed in master.  What I did:

```
conda create -n lab-test jupyter
source activate lab-test
pip install --pre jupyterlab
cp -r <path_to_share>/jupyter/lab lab_test
export JUPYTERLAB_DIR=`pwd`/lab_test
jupyter lab
```

```
$ jupyter lab paths
Application directory:   C:\Users\steve\workspace\lab_test
User Settings directory: C:\Users\steve\.jupyter\lab\user-settings
```

Workspaces directory: C:\Users\steve\.jupyter\lab\workspaces

**Comment by blink1073** [comment] 2019-05-18 09:08
Ah, looking at the original example you were setting `JUPYTERLAB_DIR` to point to an empty folder.  If you had installed node and run `jupyter lab build` afterward, that folder would get populated.  I'll clarify the docs on `JUPYTERLAB_DIR`.  The issue I had seen locally prior was because I was in a half-built state from local development.

**Comment by pmav99** [comment] 2019-05-18 09:28
>  If you had installed node and run jupyter lab build afterward, that folder would get populated. 
Still, an error message suggesting that `jupyter lab build` is required, would not be a bad idea.

**Comment by blink1073** [comment] 2019-05-18 10:54
In #6372 we attempt to build there if no assets are found and error out if node is unavailable.

**Closed** 2019-05-21 08:17 UTC
Labels: tag:Build System, type:Bug
