### ISSUE TITLE
Changing-tab while in terminal adds completion

### ISSUE THREAD

**Issue by mocquin** [jupyterlab/jupyterlab#5076] opened 2018-08-08 18:06 UTC
When in a terminal in jlab, and I hit (CTRL+TAB) to change web-browser tab, it adds a completion to the terminal because of the tab - although I'm hitting and holding CTRL before TAB.

For exemple, it creates a "Display all XXX possibilities? (y or n)" invite.

Hope it's clear.
(Jlab 0.32.1, Firefox 60.0.2)

**Comment by liffiton** [comment] 2018-08-09 00:52
FWIW, this issue does not occur for me in Jupyterlab 0.33.4, Firefox 61.0.1 64-bit Windows.

**Comment by Liberus** [comment] 2018-08-19 13:53
same, not reproduciable on my side, jlab 0.33.11, Chrome, 64-bit Windows

**Comment by saulshanabrook** [comment] 2018-09-10 21:35
Closing this since we could not be reproduced

**Closed by saulshanabrook** 2018-09-10 21:35 UTC
