### ISSUE TITLE
The nbformat package should be a module

### ISSUE THREAD

**Issue by Falven** [jupyterlab/jupyterlab#15484] opened 2023-12-04 07:11 UTC
## Description

The nbformat module currently cannot be imported from an ESModule. It was built as an ESModule, however the package.json type was left empty, which defaults to CommonJS. The `package.json` type needs to be changed to `"type": "module"` or the file extensions should be changed to `.mjs` for the package to be able to be imported. Even if you default import it, the module would not work because it itself is using ESModule-style imports.

## Reproduce

Just import it from an ESModule and try to run it with ts-node.

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

I diagnosed the issue by trying to import the module.

## Expected behavior

I will be able to import the module as an ESModule once the `"type": "module"` `package.json` entry is added.

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment] 2023-12-04 18:11
Is this issue a duplicate of https://github.com/jupyterlab/jupyterlab/issues/12518?

**Comment by Falven** [comment] 2023-12-04 18:17
> Is this issue a duplicate of #12518?

It seems so! This is one of the packages that needs that treatment.
Apologies, missed that thread in my search.

**Comment by JasonWeill** [comment] 2023-12-05 17:55
Closing as a duplicate of #12518.

**Closed by JasonWeill** 2023-12-05 17:55 UTC
Labels: bug, status:Duplicate, status:Needs Triage
