### ISSUE TITLE
'Select Kernel' for deleted notebook

### ISSUE THREAD

**Issue by gioarma** [jupyterlab/jupyterlab#8023] opened 2020-03-10 10:09 UTC
## Description

Everytime I launch jupyter lab it asks for selecting the kernel for a notebook that I have created weeks ago and never reopened. I tried to delete the file, since I dind't care about it and I still get the same popup everytime I launch jupyter lab. Here is a screenshot of what I see everytime, as soon as I launch Jupyter Lab:

![Schermata 2020-03-10 alle 11 07 32](https://user-images.githubusercontent.com/59478987/76301963-7d60e880-62bf-11ea-8b3f-7a79bf0f5239.png)

## Expected behavior

Open jupyter lab without launching a kernel for a file I did not open and that now I have even deleted.

## Context

- Operating System and version: macOS High Sierra 10.13.6
- Browser and version: Firefox 73.0.1
- JupyterLab version: 1.2.4

**Comment by jasongrout** [comment] 2020-04-01 08:49
What happens after you select a kernel?

**Comment by gioarma** [comment] 2020-04-01 08:59
The Kernel starts with no errors and I can see it in the kernel sessions. If I shut it down, it shuts down with no errors

**Comment by jasongrout** [comment] 2020-04-01 09:16
But no file opens? Are there any errors in the browser Javascript console or in the server logs?

**Comment by jasongrout** [comment] 2020-04-01 09:30
I tried to reproduce by:

1. Installing a fresh new JupyterLab in a clean conda environment: `conda create -c conda-forge -n test8023 jupyterlab`, `conda activate test8023`
2. Launch JupyterLab, create a new notebook with a Python kernel, use one cell to make sure the kernel was working.
3. Close JupyterLab tab and shut down the server (without closing the notebook)
4. Delete the notebook from the command line
5. Start up JupyterLab again

It did not ask me to select a kernel, nor did it launch the non-existent file.

This was with JupyterLab 2.0.1, Firefox on macOS.

Could you try to reproduce this with JupyterLab 2.0.1, or could you try getting a reproducible set of steps from a clean fresh environment to reproduce the problem?

**Comment by gioarma** [comment] 2020-04-01 09:39
I get this in the Chrome console:

<img width="1279" alt="Schermata 2020-04-01 alle 11 35 13" src="https://user-images.githubusercontent.com/59478987/78122327-e7773400-740c-11ea-82c9-0000feb62a83.png">


Yes, I also have this problem _only for this specific notebook_, probably I should have specified it sorry. For any other notebook I don't get asked for selecting kernel if it was not open during the last session or if it was deleted.
My current version of JupyterLab is 2.0.1, I upgraded since I wrote the initial post, but the problem still remains.

**Comment by jasongrout** [comment] 2020-04-01 09:48
Very interesting. The errors indicate you may have some extra extensions installed, etc. What happens if you follow the issue diagnosis guidelines for reporting issues at https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html to try to reproduce the issue in a clean JupyterLab?

Do you recall anything about this notebook?

Or do you just want to clean out the workspace so that this notebook is not trying to open, and not really care about reproducing the error? In that case, you can reset the default workspace by appending `?reset` to the url, like `localhost:8888/lab?reset`

**Comment by jasongrout** [comment] 2020-04-01 09:49
(I found that reset command by reading https://jupyterlab.readthedocs.io/en/stable/user/urls.html)

**Comment by gioarma** [comment] 2020-04-01 09:57
Actually I just wanted JLab not try to open the notebook anymore and the reset command worked perfectly! Thank you!

**Comment by jasongrout** [comment] 2020-04-01 10:09
Great! If anyone else experiences this and wants to help us track down whatever might be the issue, please open a new issue and follow the reporting diagnosis guide (or post the notebook in question, if you can) to help us reproduce what the problem might be. My current thought based on the errors above is that it may be caused by a third-party extension.

**Closed by jasongrout** 2020-04-01 10:09 UTC
