### ISSUE TITLE
Ctrl+S triggers "save page" instead of saving .ipynb file in V4.1.3

### ISSUE THREAD

**Issue by TeetotalingTom** [jupyterlab/jupyterlab#15925] opened 2024-03-06 09:51 UTC
## Description

When typing Ctrl+S in Jupyter Lab V4.1.3 in WSL2 on Windows, I receive a request to save the web page as .htm file instead of saving an updated version of the file in its current location. This issue seems similar to issue #306 although I am not sure how to get the "green left edge" that is described on said page. I have also tried to disable all of the "Accel S" shortcuts, but none of them are doing the trick.

## Reproduce
1. Install LJ V4.1.3 on Ubuntu
2. $ jupyter lab
3. Try to save a cell with Ctrl+S

## Expected behavior

Save an updated version of the file in its current location.

## Context

- Operating System and version: Ubuntu V22.04.4 via WSL2 on Windows 11
- Browser and version: Firefox 123.0 Windows / WSL2 default
- JupyterLab version: 4.1.3

</pre>
</details>

**Comment by krassowski** [comment] 2024-03-06 09:57
Thanks for opening the issue @TeetotalingTom. This appears to be a duplicate of https://github.com/jupyterlab/jupyterlab/issues/15912.

**Closed by krassowski** 2024-03-06 09:57 UTC
Labels: bug, status:Duplicate, status:Needs Triage
