### ISSUE TITLE
Markdown cell doesn't render strike-through through it shows preview

### ISSUE THREAD

**Issue by DataEagle** [jupyterlab/jupyterlab#3756] opened 2018-01-31 11:07 UTC
1. Add a markdown cell
2. Type in text with strike-through mark down
3. Edit preview shows strike-through style.
4. Hit enter. Text is rendered without strike-through.

Jupyter lab Build: **Beta 1 Release, v0.31.2**

Attached screenshot.
![preview](https://user-images.githubusercontent.com/35996290/35619736-f69dc2c8-06a4-11e8-82b2-92e147c0f531.png)
![rendered](https://user-images.githubusercontent.com/35996290/35619738-f70f0a46-06a4-11e8-9b1c-315f9f679f53.png)

**Comment by jasongrout** [comment] 2018-01-31 12:04
Thanks! I've confirmed this bug. Looking at the HTML, it looks like the `<del>` tag was stripped out. Perhaps our sanitizer is stripping it out, but shouldn't?

**Comment by jasongrout** [comment] 2018-01-31 12:06
Labeling as a good first issue, as I'm thinking it might be as easy as checking that our sanitizer is letting `<del>` tags through: https://github.com/jupyterlab/jupyterlab/blob/9d5cf865200b57acefdaa9fb6c2e4a1c366e4af7/packages/apputils/src/sanitizer.ts#L28

**Comment by jasongrout** [comment] 2018-01-31 12:08
(yes, it looks like our sanitizer defaults also don't include `<del>`: https://github.com/punkave/sanitize-html/blob/cfe21220b80b7130755b7e3fd9abadc7ba6f1658/src/index.js#L521-L523)

**Comment by jasongrout** [comment] 2018-01-31 12:09
@DataEagle - do you want to try fixing this?

**Comment by jasongrout** [comment] 2018-01-31 12:12
@DataEagle - I see you just joined GitHub today. Welcome! I think this is as easy as adding `'del'` to the list of whitelisted tags in https://github.com/jupyterlab/jupyterlab/blob/9d5cf865200b57acefdaa9fb6c2e4a1c366e4af7/packages/apputils/src/sanitizer.ts#L28. Do you want to try it and submit a PR? You can even edit the file online and submit the PR by clicking on the pencil icon in the upper right of https://github.com/jupyterlab/jupyterlab/blob/master/packages/apputils/src/sanitizer.ts#L64. Even better (but a lot more complicated) would be to clone the JupyterLab repo, make the change and test that it works, then submit a PR.

**Comment by DataEagle** [comment] 2018-02-01 07:23
Submitted a PR - #3771

**Comment by dlukes** [comment] 2018-02-17 00:23
I see the PR has been merged, maybe this can be closed now? :)

**Comment by jasongrout** [comment] 2018-02-17 01:58
Can you check really quickly if it works? If it does, then yes!

**Comment by jasongrout** [comment] 2018-02-17 01:59
I realized I had a jlab instance open, so I checked it. It works! Thanks!

**Closed by jasongrout** 2018-02-17 01:59 UTC
Labels: good first issue, pkg:notebook, type:Bug
