### ISSUE TITLE
Sidebar disappears after installing any extension

### ISSUE THREAD

**Issue by MLBurnham** [jupyterlab/jupyterlab#7122] opened 2019-08-29 20:46 UTC
## Description

After installing any extension the default sidebar tabs disappear and file tabs give visual glitches. Here's an image with the default tabs gone and one of the file tabs glitched:
![Screenshot from 2019-08-29 14-31-38](https://user-images.githubusercontent.com/41241150/63974249-7b011480-ca7a-11e9-971d-9386c1a7dde9.png)

Here's and image of what happens when I drag that file tab down:
![Screenshot from 2019-08-29 14-31-54](https://user-images.githubusercontent.com/41241150/63974278-8a805d80-ca7a-11e9-9aa9-3132b0829e77.png)

And here's an image of the side bar opened:
![Screenshot from 2019-08-29 16-30-30](https://user-images.githubusercontent.com/41241150/63974306-966c1f80-ca7a-11e9-94b8-9e8550690df8.png)

## Reproduce
I have not been able to reproduce the error in a virtual environment. I can reproduce the error in my base by:
1. reinstalling jupyter lab via conda remove and conda install
2. installing any extension.
3. rebuilding

After the rebuild there is no way to revert jupyter lab back to normal without reinstalling. Jupyter lab is basically unusable unless I run it in core mode or a virtual environment.

## Expected behavior

extensions don't bug the interface

## Context

- Operating System and version:Ubuntu 18.04
- Browser and version: Firefox 68.0.2
- JupyterLab version: 1.0.2

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/home/mike/anaconda3/bin
	/home/mike/anaconda3/condabin
	/home/mike/.local/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/snap/bin

sys.path:
	/home/mike/anaconda3/bin
	/home/mike/anaconda3/lib/python37.zip
	/home/mike/anaconda3/lib/python3.7
	/home/mike/anaconda3/lib/python3.7/lib-dynload
	/home/mike/anaconda3/lib/python3.7/site-packages

sys.executable:
	/home/mike/anaconda3/bin/python3.7

sys.version:
	3.7.3 (default, Mar 27 2019, 22:11:17) 
	[GCC 7.3.0]

platform.platform():
	Linux-4.15.0-1050-oem-x86_64-with-debian-buster-sid

which -a jupyter:
	/home/mike/anaconda3/bin/jupyter
	/home/mike/.local/bin/jupyter
	/usr/bin/jupyter

pip list:
	Package                       Version  
	----------------------------- ---------
	anaconda-client               1.7.2    
	anaconda-navigator            1.9.7    
	asn1crypto                    0.24.0   
	attrs                         19.1.0   
	backcall                      0.1.0    
	backports.functools-lru-cache 1.5      
	backports.tempfile            1.0      
	backports.weakref             1.0.post1
	beautifulsoup4                4.8.0    
	bleach                        3.1.0    
	certifi                       2019.6.16
	cffi                          1.12.3   
	chardet                       3.0.4    
	Click                         7.0      
	clyent                        1.2.2    
	conda                         4.7.11   
	conda-build                   3.18.8   
	conda-package-handling        1.3.11   
	conda-verify                  3.4.2    
	cryptography                  2.7      
	decorator                     4.4.0    
	defusedxml                    0.6.0    
	entrypoints                   0.3      
	filelock                      3.0.12   
	future                        0.17.1   
	glob2                         0.7      
	idna                          2.8      
	ipykernel                     5.1.2    
	ipython                       7.7.0    
	ipython-genutils              0.2.0    
	jedi                          0.15.1   
	Jinja2                        2.10.1   
	json5                         0.8.5    
	jsonschema                    3.0.2    
	jupyter-client                5.3.1    
	jupyter-core                  4.5.0    
	jupyterlab                    1.0.2    
	jupyterlab-server             1.0.0    
	libarchive-c                  2.8      
	lief                          0.9.0    
	MarkupSafe                    1.1.1    
	mistune                       0.8.4    
	navigator-updater             0.2.1    
	nbconvert                     5.5.0    
	nbformat                      4.4.0    
	notebook                      6.0.0    
	olefile                       0.46     
	pandocfilters                 1.4.2    
	parso                         0.5.1    
	pexpect                       4.7.0    
	pickleshare                   0.7.5    
	Pillow                        6.1.0    
	pip                           19.2.2   
	pkginfo                       1.5.0.1  
	prometheus-client             0.7.1    
	prompt-toolkit                2.0.9    
	psutil                        5.6.3    
	ptyprocess                    0.6.0    
	pycosat                       0.6.3    
	pycparser                     2.19     
	Pygments                      2.4.2    
	pyOpenSSL                     19.0.0   
	pyrsistent                    0.14.11  
	PySocks                       1.7.0    
	python-dateutil               2.8.0    
	pytz                          2019.2   
	PyYAML                        5.1.2    
	pyzmq                         18.1.0   
	QtPy                          1.9.0    
	requests                      2.22.0   
	ruamel-yaml                   0.15.46  
	Send2Trash                    1.5.0    
	setuptools                    41.0.1   
	six                           1.12.0   
	soupsieve                     1.9.2    
	terminado                     0.8.2    
	testpath                      0.4.2    
	tornado                       6.0.3    
	tqdm                          4.32.1   
	traitlets                     4.3.2    
	urllib3                       1.24.2   
	wcwidth                       0.1.7    
	webencodings                  0.5.1    
	wheel                         0.33.4

conda list:
	# packages in environment at /home/mike/anaconda3:
	#
	# Name                    Version                   Build  Channel
	_libgcc_mutex             0.1                        main  
	anaconda-client           1.7.2                    py37_0  
	anaconda-navigator        1.9.7                    py37_0  
	asn1crypto                0.24.0                   py37_0  
	attrs                     19.1.0                   py37_1  
	backcall                  0.1.0                    py37_0  
	backports                 1.0                        py_2  
	backports.functools_lru_cache 1.5                        py_2  
	backports.tempfile        1.0                        py_1  
	backports.weakref         1.0.post1                  py_1  
	beautifulsoup4            4.8.0                    py37_0  
	bleach                    3.1.0                    py37_0  
	bzip2                     1.0.8                h7b6447c_0  
	ca-certificates           2019.5.15                     1  
	certifi                   2019.6.16                py37_1  
	cffi                      1.12.3           py37h2e261b9_0  
	chardet                   3.0.4                 py37_1003  
	click                     7.0                      py37_0  
	clyent                    1.2.2                    py37_1  
	conda                     4.7.11                   py37_0  
	conda-build               3.18.8                   py37_0  
	conda-env                 2.6.0                         1  
	conda-package-handling    1.3.11                   py37_0  
	conda-verify              3.4.2                      py_1  
	cryptography              2.7              py37h1ba5d50_0  
	dbus                      1.13.6               h746ee38_0  
	decorator                 4.4.0                    py37_1  
	defusedxml                0.6.0                      py_0  
	entrypoints               0.3                      py37_0  
	expat                     2.2.6                he6710b0_0  
	filelock                  3.0.12                     py_0  
	fontconfig                2.13.0               h9420a91_0  
	freetype                  2.9.1                h8a8886c_1  
	future                    0.17.1                   py37_0  
	glib                      2.56.2               hd408876_0  
	glob2                     0.7                        py_0  
	gmp                       6.1.2                h6c8ec71_1  
	gst-plugins-base          1.14.0               hbbd80ab_1  
	gstreamer                 1.14.0               hb453b48_1  
	icu                       58.2                 h9c2bf20_1  
	idna                      2.8                      py37_0  
	ipykernel                 5.1.2            py37h39e3cac_0  
	ipython                   7.7.0            py37h39e3cac_0  
	ipython_genutils          0.2.0                    py37_0  
	jedi                      0.15.1                   py37_0  
	jinja2                    2.10.1                   py37_0  
	jpeg                      9b                   h024ee3a_2  
	json5                     0.8.5                      py_0  
	jsonschema                3.0.2                    py37_0  
	jupyter_client            5.3.1                      py_0  
	jupyter_core              4.5.0                      py_0  
	jupyterlab                1.0.2            py37hf63ae98_0  
	jupyterlab_server         1.0.0                      py_1  
	libarchive                3.3.3                h5d8350f_5  
	libedit                   3.1.20181209         hc058e9b_0  
	libffi                    3.2.1                hd88cf55_4  
	libgcc-ng                 9.1.0                hdf63c60_0  
	liblief                   0.9.0                h7725739_2  
	libpng                    1.6.37               hbc83047_0  
	libsodium                 1.0.16               h1bed415_0  
	libstdcxx-ng              9.1.0                hdf63c60_0  
	libtiff                   4.0.10               h2733197_2  
	libuuid                   1.0.3                h1bed415_2  
	libxcb                    1.13                 h1bed415_1  
	libxml2                   2.9.9                hea5a465_1  
	lz4-c                     1.8.1.2              h14c3975_0  
	lzo                       2.10                 h49e0be7_2  
	markupsafe                1.1.1            py37h7b6447c_0  
	mistune                   0.8.4            py37h7b6447c_0  
	navigator-updater         0.2.1                    py37_0  
	nbconvert                 5.5.0                      py_0  
	nbformat                  4.4.0                    py37_0  
	ncurses                   6.1                  he6710b0_1  
	nodejs                    10.13.0              he6710b0_0  
	notebook                  6.0.0                    py37_0  
	olefile                   0.46                     py37_0  
	openssl                   1.1.1c               h7b6447c_1  
	pandoc                    2.2.3.2                       0  
	pandocfilters             1.4.2                    py37_1  
	parso                     0.5.1                      py_0  
	patchelf                  0.9                  he6710b0_3  
	pcre                      8.43                 he6710b0_0  
	pexpect                   4.7.0                    py37_0  
	pickleshare               0.7.5                    py37_0  
	pillow                    6.1.0            py37h34e0f95_0  
	pip                       19.2.2                   py37_0  
	pkginfo                   1.5.0.1                  py37_0  
	prometheus_client         0.7.1                      py_0  
	prompt_toolkit            2.0.9                    py37_0  
	psutil                    5.6.3            py37h7b6447c_0  
	ptyprocess                0.6.0                    py37_0  
	py-lief                   0.9.0            py37h7725739_2  
	pycosat                   0.6.3            py37h14c3975_0  
	pycparser                 2.19                     py37_0  
	pygments                  2.4.2                      py_0  
	pyopenssl                 19.0.0                   py37_0  
	pyqt                      5.9.2            py37h05f1152_2  
	pyrsistent                0.14.11          py37h7b6447c_0  
	pysocks                   1.7.0                    py37_0  
	python                    3.7.3                h0371630_0  
	python-dateutil           2.8.0                    py37_0  
	python-libarchive-c       2.8                     py37_13  
	pytz                      2019.2                     py_0  
	pyyaml                    5.1.2            py37h7b6447c_0  
	pyzmq                     18.1.0           py37he6710b0_0  
	qt                        5.9.7                h5867ecd_1  
	qtpy                      1.9.0                      py_0  
	readline                  7.0                  h7b6447c_5  
	requests                  2.22.0                   py37_0  
	ruamel_yaml               0.15.46          py37h14c3975_0  
	send2trash                1.5.0                    py37_0  
	setuptools                41.0.1                   py37_0  
	sip                       4.19.8           py37hf484d3e_0  
	six                       1.12.0                   py37_0  
	soupsieve                 1.9.2                    py37_0  
	sqlite                    3.29.0               h7b6447c_0  
	terminado                 0.8.2                    py37_0  
	testpath                  0.4.2                    py37_0  
	tk                        8.6.8                hbc83047_0  
	tornado                   6.0.3            py37h7b6447c_0  
	tqdm                      4.32.1                     py_0  
	traitlets                 4.3.2                    py37_0  
	urllib3                   1.24.2                   py37_0  
	wcwidth                   0.1.7                    py37_0  
	webencodings              0.5.1                    py37_1  
	wheel                     0.33.4                   py37_0  
	xz                        5.2.4                h14c3975_4  
	yaml                      0.1.7                had09818_2  
	zeromq                    4.3.1                he6710b0_3  
	zlib                      1.2.11               h7b6447c_3  
	zstd                      1.3.7                h0b5b093_0

</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[D 16:40:12.313 LabApp] Searching ['/home/mike', '/home/mike/.jupyter', '/home/mike/anaconda3/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 16:40:12.313 LabApp] Looking for jupyter_config in /etc/jupyter
[D 16:40:12.313 LabApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 16:40:12.313 LabApp] Looking for jupyter_config in /home/mike/anaconda3/etc/jupyter
[D 16:40:12.313 LabApp] Looking for jupyter_config in /home/mike/.jupyter
[D 16:40:12.313 LabApp] Looking for jupyter_config in /home/mike
[D 16:40:12.314 LabApp] Looking for jupyter_notebook_config in /etc/jupyter
[D 16:40:12.314 LabApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 16:40:12.314 LabApp] Looking for jupyter_notebook_config in /home/mike/anaconda3/etc/jupyter
[D 16:40:12.314 LabApp] Looking for jupyter_notebook_config in /home/mike/.jupyter
[D 16:40:12.314 LabApp] Loaded config file: /home/mike/.jupyter/jupyter_notebook_config.json
[D 16:40:12.314 LabApp] Looking for jupyter_notebook_config in /home/mike
[D 16:40:12.317 LabApp] Paths used for configuration of jupyter_notebook_config: 
    	/etc/jupyter/jupyter_notebook_config.json
[D 16:40:12.317 LabApp] Paths used for configuration of jupyter_notebook_config: 
    	/usr/local/etc/jupyter/jupyter_notebook_config.json
[D 16:40:12.318 LabApp] Paths used for configuration of jupyter_notebook_config: 
    	/home/mike/anaconda3/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
    	/home/mike/anaconda3/etc/jupyter/jupyter_notebook_config.json
[D 16:40:12.318 LabApp] Paths used for configuration of jupyter_notebook_config: 
    	/home/mike/.jupyter/jupyter_notebook_config.json
[I 16:40:12.436 LabApp] JupyterLab extension loaded from /home/mike/anaconda3/lib/python3.7/site-packages/jupyterlab
[I 16:40:12.436 LabApp] JupyterLab application directory is /home/mike/anaconda3/share/jupyter/lab
[I 16:40:12.437 LabApp] Serving notebooks from local directory: /home/mike
[I 16:40:12.437 LabApp] The Jupyter Notebook is running at:
[I 16:40:12.437 LabApp] http://localhost:8888/?token=37f7e21c7c329dc4ea0145f26c26c79184384122b8b42efb
[I 16:40:12.437 LabApp]  or http://127.0.0.1:8888/?token=37f7e21c7c329dc4ea0145f26c26c79184384122b8b42efb
[I 16:40:12.437 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:40:12.449 LabApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/mike/.local/share/jupyter/runtime/nbserver-24694-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=37f7e21c7c329dc4ea0145f26c26c79184384122b8b42efb
     or http://127.0.0.1:8888/?token=37f7e21c7c329dc4ea0145f26c26c79184384122b8b42efb
[D 16:40:13.531 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:13.535 LabApp] Using contents: services/contents
[D 16:40:13.544 LabApp] 200 GET /lab?token=37f7e21c7c329dc4ea0145f26c26c79184384122b8b42efb (127.0.0.1) 14.59ms
[D 16:40:13.595 LabApp] Path main.b4da50a1ec3b8275cf9f.js served from /home/mike/anaconda3/share/jupyter/lab/static/main.b4da50a1ec3b8275cf9f.js
[D 16:40:13.596 LabApp] 304 GET /static/lab/main.b4da50a1ec3b8275cf9f.js (127.0.0.1) 1.59ms
[D 16:40:13.598 LabApp] Path vendors~main.223d09b1c10b083964d9.js served from /home/mike/anaconda3/share/jupyter/lab/static/vendors~main.223d09b1c10b083964d9.js
[D 16:40:13.598 LabApp] 304 GET /static/lab/vendors~main.223d09b1c10b083964d9.js (127.0.0.1) 1.38ms
[D 16:40:14.249 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:14.250 LabApp] 200 GET /api/sessions?1567111214248 (127.0.0.1) 1.20ms
[D 16:40:14.251 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:14.251 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:14.252 LabApp] Found kernel python3 in /home/mike/.local/share/jupyter/kernels
[D 16:40:14.252 LabApp] Found kernel python2 in /home/mike/.local/share/jupyter/kernels
[D 16:40:14.252 LabApp] Found kernel ir in /home/mike/.local/share/jupyter/kernels
[D 16:40:14.254 LabApp] 200 GET /api/kernelspecs?1567111214249 (127.0.0.1) 3.12ms
[D 16:40:14.254 LabApp] 200 GET /api/terminals?1567111214249 (127.0.0.1) 2.98ms
[D 16:40:14.256 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:14.273 LabApp] 200 GET /lab/api/settings/?1567111214255 (127.0.0.1) 17.33ms
[I 16:40:14.297 LabApp] 301 GET /lab/workspaces/auto-A/?clone (127.0.0.1) 0.58ms
[D 16:40:14.324 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:14.326 LabApp] 200 GET /metrics?1567111214321 (127.0.0.1) 1.99ms
[D 16:40:14.334 LabApp] Using contents: services/contents
[D 16:40:14.337 LabApp] 200 GET /lab/workspaces/auto-A?clone (127.0.0.1) 3.37ms
[D 16:40:14.339 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:14.340 LabApp] 200 GET /api/sessions?1567111214338 (127.0.0.1) 0.84ms
[D 16:40:14.341 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:14.341 LabApp] Found kernel python3 in /home/mike/.local/share/jupyter/kernels
[D 16:40:14.341 LabApp] Found kernel python2 in /home/mike/.local/share/jupyter/kernels
[D 16:40:14.341 LabApp] Found kernel ir in /home/mike/.local/share/jupyter/kernels
[D 16:40:14.342 LabApp] 200 GET /api/kernelspecs?1567111214339 (127.0.0.1) 1.94ms
[D 16:40:14.343 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:14.344 LabApp] 200 GET /api/terminals?1567111214339 (127.0.0.1) 0.66ms
[D 16:40:14.361 LabApp] 304 GET /static/lab/main.b4da50a1ec3b8275cf9f.js (127.0.0.1) 1.07ms
[D 16:40:14.363 LabApp] 304 GET /static/lab/vendors~main.223d09b1c10b083964d9.js (127.0.0.1) 2.08ms
[D 16:40:15.096 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:15.096 LabApp] 200 GET /api/sessions?1567111215094 (127.0.0.1) 1.17ms
[D 16:40:15.097 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:15.098 LabApp] Found kernel python3 in /home/mike/.local/share/jupyter/kernels
[D 16:40:15.098 LabApp] Found kernel python2 in /home/mike/.local/share/jupyter/kernels
[D 16:40:15.098 LabApp] Found kernel ir in /home/mike/.local/share/jupyter/kernels
[D 16:40:15.100 LabApp] 200 GET /api/kernelspecs?1567111215094 (127.0.0.1) 2.54ms
[D 16:40:15.100 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:15.101 LabApp] 200 GET /api/terminals?1567111215096 (127.0.0.1) 0.75ms
[D 16:40:15.105 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:15.122 LabApp] 200 GET /lab/api/settings/?1567111215104 (127.0.0.1) 17.09ms
[D 16:40:15.239 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:15.240 LabApp] 200 GET /api/sessions?1567111215238 (127.0.0.1) 0.73ms
[D 16:40:15.240 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:15.241 LabApp] Found kernel python3 in /home/mike/.local/share/jupyter/kernels
[D 16:40:15.241 LabApp] Found kernel python2 in /home/mike/.local/share/jupyter/kernels
[D 16:40:15.241 LabApp] Found kernel ir in /home/mike/.local/share/jupyter/kernels
[D 16:40:15.242 LabApp] 200 GET /api/kernelspecs?1567111215239 (127.0.0.1) 1.60ms
[D 16:40:15.266 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:15.267 LabApp] 200 GET /metrics?1567111215265 (127.0.0.1) 1.98ms
[D 16:40:15.268 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:15.269 LabApp] 200 GET /api/terminals?1567111215266 (127.0.0.1) 0.65ms
[D 16:40:15.396 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:15.401 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:15.460 LabApp] 200 GET /api/nbconvert?1567111215399 (127.0.0.1) 58.60ms
[D 16:40:15.461 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:15.462 LabApp] Path @jupyterlab/theme-dark-extension/index.css served from /home/mike/anaconda3/share/jupyter/lab/themes/@jupyterlab/theme-dark-extension/index.css
[D 16:40:15.462 LabApp] 304 GET /lab/api/themes/@jupyterlab/theme-dark-extension/index.css (127.0.0.1) 1.67ms
[D 16:40:15.490 LabApp] 200 GET /api/nbconvert?1567111215422 (127.0.0.1) 28.92ms
[D 16:40:15.491 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:15.493 LabApp] 200 GET /lab/api/extensions?1567111215488 (127.0.0.1) 2.10ms
[D 16:40:15.493 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:15.494 LabApp] 200 GET /api/sessions?1567111215470 (127.0.0.1) 1.13ms
[D 16:40:15.516 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:15.517 LabApp] 200 GET /lab/api/workspaces/lab?1567111215515 (127.0.0.1) 1.17ms
[D 16:40:15.518 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:15.522 LabApp] 200 GET /api/contents/?content=1&1567111215516 (127.0.0.1) 4.11ms
[D 16:40:15.536 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:15.538 LabApp] 200 GET /lab/api/extensions?1567111215534 (127.0.0.1) 2.26ms
[D 16:40:15.569 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:15.572 LabApp] 200 GET /api/contents/?1567111215568 (127.0.0.1) 3.43ms
[D 16:40:15.660 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:15.662 LabApp] 200 GET /api/contents/?content=1&1567111215658 (127.0.0.1) 2.72ms
[D 16:40:15.670 LabApp] Serving kernel resource from: /home/mike/.local/share/jupyter/kernels/python3
[D 16:40:15.671 LabApp] 304 GET /kernelspecs/python3/logo-64x64.png (127.0.0.1) 1.58ms
[D 16:40:15.673 LabApp] Serving kernel resource from: /home/mike/.local/share/jupyter/kernels/python2
[D 16:40:15.673 LabApp] 304 GET /kernelspecs/python2/logo-64x64.png (127.0.0.1) 1.61ms
[D 16:40:15.674 LabApp] Serving kernel resource from: /home/mike/.local/share/jupyter/kernels/ir
[D 16:40:15.675 LabApp] 304 GET /kernelspecs/ir/logo-64x64.png (127.0.0.1) 1.57ms
[D 16:40:15.741 LabApp] Node v10.13.0
    
[I 16:40:15.742 LabApp] Build is up to date
[D 16:40:15.743 LabApp] 200 GET /lab/api/build?1567111215377 (127.0.0.1) 346.38ms
[D 16:40:15.943 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:15.955 LabApp] 200 GET /metrics?1567111215937 (127.0.0.1) 12.41ms
[D 16:40:16.216 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:16.218 LabApp] 204 PUT /lab/api/workspaces/lab/workspaces/auto-A?1567111216210 (127.0.0.1) 3.22ms
[D 16:40:19.469 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:19.475 LabApp] 200 GET /metrics?1567111219461 (127.0.0.1) 7.61ms
[D 16:40:25.278 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:25.281 LabApp] 200 GET /api/sessions?1567111225271 (127.0.0.1) 3.62ms
[D 16:40:25.284 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:25.286 LabApp] 200 GET /api/terminals?1567111225276 (127.0.0.1) 2.87ms
[D 16:40:25.625 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:25.638 LabApp] 200 GET /api/contents/?content=1&1567111225620 (127.0.0.1) 13.97ms
[D 16:40:28.403 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:28.411 LabApp] 200 GET /metrics?1567111228397 (127.0.0.1) 8.17ms
[D 16:40:35.295 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:35.296 LabApp] 200 GET /api/sessions?1567111235291 (127.0.0.1) 1.49ms
[D 16:40:35.297 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:35.298 LabApp] 200 GET /api/terminals?1567111235294 (127.0.0.1) 1.07ms
[D 16:40:35.656 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:35.662 LabApp] 200 GET /api/contents/?content=1&1567111235649 (127.0.0.1) 7.48ms
[D 16:40:45.305 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:45.307 LabApp] 200 GET /api/sessions?1567111245299 (127.0.0.1) 3.10ms
[D 16:40:45.310 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:45.312 LabApp] 200 GET /api/terminals?1567111245301 (127.0.0.1) 2.39ms
[D 16:40:45.675 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:45.681 LabApp] 200 GET /api/contents/?content=1&1567111245668 (127.0.0.1) 6.81ms
[D 16:40:50.659 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:40:50.674 LabApp] 200 GET /metrics?1567111250651 (127.0.0.1) 15.59ms

</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `NotebookTrustComponent`. vendors~main.223d09b1c10b083964d9.js:195544:15
XML Parsing Error: not well-formed
Location: http://localhost:8888/lab/workspaces/auto-A?clone
Line Number 1, Column 11: auto-A:1:11
TypeError: this._settings.schema.definitions is undefined vendors~main.223d09b1c10b083964d9.js:58957:25
Could not write session state file  
Object { operation: "open", path: "/home/mike/.mozilla/firefox/cbi7i63d.default-release/sessionstore-backups/recovery.jsonlz4.tmp", unixErrno: 2, stack: "", fileName: "(unknown module)", lineNumber: undefined }
 SessionFile.jsm:405:15
Attempt to set a forbidden header was denied: Connection
Could not write session state file  
Object { operation: "open", path: "/home/mike/.mozilla/firefox/cbi7i63d.default-release/sessionstore-backups/recovery.jsonlz4.tmp", unixErrno: 2, stack: "", fileName: "(unknown module)", lineNumber: undefined }
 SessionFile.jsm:405:15
Could not write session state file  
Object { operation: "open", path: "/home/mike/.mozilla/firefox/cbi7i63d.default-release/sessionstore-backups/recovery.jsonlz4.tmp", unixErrno: 2, stack: "", fileName: "(unknown module)", lineNumber: undefined }
 SessionFile.jsm:405:15
Could not write session state file  
Object { operation: "open", path: "/home/mike/.mozilla/firefox/cbi7i63d.default-release/sessionstore-backups/recovery.jsonlz4.tmp", unixErrno: 2, stack: "", fileName: "(unknown module)", lineNumber: undefined }
 SessionFile.jsm:405:15
Could not write session state file  
Object { operation: "open", path: "/home/mike/.mozilla/firefox/cbi7i63d.default-release/sessionstore-backups/recovery.jsonlz4.tmp", unixErrno: 2, stack: "", fileName: "(unknown module)", lineNumber: undefined }
 SessionFile.jsm:405:15
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://accounts.google.com/ServiceLogin?service=cloudconsol…ps://console.developers.google.com/m/tos/required&authuser=0. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://accounts.google.com/ServiceLogin?service=cloudconsol…ps://console.developers.google.com/m/tos/required&authuser=0. (Reason: CORS request did not succeed).

Request to access cookie or storage on “https://www.google-analytics.com/analytics.js” was blocked because it came from a tracker and content blocking is enabled.
Browser_Console
Request to access cookie or storage on “https://www.google-analytics.com/r/collect?v=1&_v=j79&aip=1&…7&_r=1&cd12=1561334&cd17=Tools%2FBrowser_Console&z=362685953” was blocked because it came from a tracker and content blocking is enabled.
Browser_Console
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://accounts.google.com/ServiceLogin?service=cloudconsol…%26angularjs_route%3Dfalse%26pid%3Dmlb-jupyterlab&authuser=0. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://accounts.google.com/ServiceLogin?service=cloudconsol…%26angularjs_route%3Dfalse%26pid%3Dmlb-jupyterlab&authuser=0. (Reason: CORS request did not succeed).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://accounts.google.com/ServiceLogin?service=cloudconsol…of%2Btype%2B%2522sc%2522%26line%3DNot%2Bavailable&authuser=0. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://accounts.google.com/ServiceLogin?service=cloudconsol…of%2Btype%2B%2522sc%2522%26line%3DNot%2Bavailable&authuser=0. (Reason: CORS request did not succeed).

Could not write session state file  
Object { operation: "open", path: "/home/mike/.mozilla/firefox/cbi7i63d.default-release/sessionstore-backups/recovery.jsonlz4.tmp", unixErrno: 2, stack: "", fileName: "(unknown module)", lineNumber: undefined }
 SessionFile.jsm:405:15
Could not write session state file  
Object { operation: "open", path: "/home/mike/.mozilla/firefox/cbi7i63d.default-release/sessionstore-backups/recovery.jsonlz4.tmp", unixErrno: 2, stack: "", fileName: "(unknown module)", lineNumber: undefined }
 SessionFile.jsm:405:15
Attempt to set a forbidden header was denied: Connection 
</pre>
</details>

**Comment by remborg** [comment] 2019-08-30 12:22
I've been investigating this issue as it happened to me today (v1.0.2).
I've got the feeling that it happens because of a npm dependency being updated when installing a new extension to a stable environment.

It looks like the issue is fixed in v1.1.1, can you try to update your version of Jupyter Lab? I think it has to do with the iconRegistry not working in previous versions.

**Comment by FlorianGD** [comment] 2019-08-30 13:07
This worked for me, thank you

**Comment by jasongrout** [comment] 2019-08-30 14:22
@MLBurnham - can you check if upgrading to 1.1.1 fixes the issue for you too?

**Comment by MLBurnham** [comment] 2019-08-31 02:57
Upgrading seems to have resolved the issue. Thanks!

**Comment by jasongrout** [comment] 2019-08-31 05:21
Great!

**Closed by jasongrout** 2019-08-31 05:21 UTC

**Comment by MichelCarroll** [comment] 2019-09-05 00:39
Is there any way I can downgrade back to 1.0.2? Version 1.1.1 has this issue https://github.com/jupyterlab/jupyterlab/issues/7144 which is causing problems for my team.

**Comment by bobmayuze** [comment] 2019-09-05 13:09
> Is there any way I can downgrade back to 1.0.2? Version 1.1.1 has this issue #7144 which is causing problems for my team.

try `pip install jupyterlab==1.0.2`
