### ISSUE TITLE
With Ctrl+V it is possible to paste text into a cell with "editable": false metadata

### ISSUE THREAD

**Issue by raffaele-cappelli** [jupyterlab/jupyterlab#11124] opened 2021-09-23 10:40 UTC
I can add text to cells with "editable": false using Ctrl+V

Reproduced in a clean env (conda create -n jlab-test --override-channels --strict-channel-priority -c conda-forge -c nodefaults jupyterlab)

- JupyterLab Version 3.1.13
- Google Chrome | 93.0.4577.82
- Windows 10 OS Version 2009
- JavaScript | V8 9.3.345.19

I was NOT able to reproduce the problem in Jupyter notebook.

**Comment by krassowski** [comment] 2021-09-23 20:33
I am unable to reproduce this behaviour on JupyterLab 3.1.13 with Chrome 93.0.4577.82. Could you please provide detailed reproduction instructions? Are you using the collaborative mode by any chance? Does it happen in every notebook? Does it happen in specific kind of cells? Can you share a notebook to reproduce it? Are you sure you saved the metadata by pressing the tick icon?

**Comment by raffaele-cappelli** [comment] 2021-09-24 05:14
Thank you for your reply. I have just checked it only happens in Markdown cells, not in code cells.

In the notebook below, the "dddddddd" string was added after editing the metadata and after checking that the cell was actually non-editable.

{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f5074734-0197-4708-81da-4c2f91a5e0ee",
   "metadata": {
    "editable": false,
    "tags": []
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "0e80d6e6-392f-4c83-9b88-299ebe01cf00",
   "metadata": {
    "editable": false,
    "tags": []
   },
   "source": [
    "- a\n",
    "- b\n",
    "- c\n",
    "dddddddd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bd01b4f3-41f8-47a8-bd4c-55e96e03d904",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

**Comment by raffaele-cappelli** [comment] 2021-09-24 05:19
Other info:
- Shift+Ins works as well
- If text is selected in the "non-editable" Markdown cell, Ctrl+V (or Shift+Ins) replaces it
- I was not able to make changes in other ways to the non-editable text (I tried Ctrl+X, typing, Del, Ctrl+Del, Backspace)

**Comment by raffaele-cappelli** [comment] 2021-09-24 05:29
I have also noted that:
- Ctrl+V pastes text into Markdown cells if you are in "command mode"! Code cells do not seem to be affected. Note this happens both on editable and non-editable cells.
- In command mode, Ctrl+V pastes text into Markdown cell even if they have been "rendered" pressing Ctrl+Enter, that is they are showing the Markdown output and not the Markdown source.

**Comment by krassowski** [comment] 2021-09-24 10:03
> Thank you for your reply. I have just checked it only happens in Markdown cells, not in code cells.

I can confirm that. Thank you for all the extra details - excellent testing and summary.

**Comment by nthiery** [comment] 2022-10-18 08:35
Just to bump the issue, here is an extra data point: we are hitting the same bug here at 
Paris-Saclay with JupyterLab 3.4.5 and 4.0.027. It's reproducible as described by
@raffaele-cappelli .

Since we use quite extensively read-only cells in our teaching material, it's relatively
annoying for our students since they cannot easily fix the modifications.

Would there be a chance to have this fixed in JupyterLab 4 ?

Thank you in advance!

Just for the record: there used to be a similar looking bug with the legacy notebook; it
affected code cells, but I never managed to craft a reproducible scenario to be able to
report. That one was very annoying since it affected the execution of the notebook.

**Comment by nthiery** [comment] 2024-10-23 11:58
Sorry, I did not report earlier. The behaviour is in fact still there with JupyterLab 4.2.5.

**Comment by nthiery** [comment] 2024-10-23 12:01
By the way (should this be a separate issue?): using the keyboard shortcuts `1`, `2`, etc while in
command mode to turn cells into a title cells also modifies cells that are supposed to be read-only.

**Comment by krassowski** [comment] 2024-10-23 12:19
@nthiery there is one already here: https://github.com/jupyterlab/jupyterlab/issues/13307

**Comment by nthiery** [comment] 2024-10-23 19:40
Ah, yes, thanks for the ref; I had searched for keywords like read only rather than editable :-)

**Closed** 2024-11-12 12:52 UTC
Labels: bug
