### ISSUE TITLE
Extension manager - blank (not working)

### ISSUE THREAD

**Issue by LukaPitamic** [jupyterlab/jupyterlab#7171] opened 2019-09-08 10:27 UTC
## Description

Extension Manager in JLab v1.1.1 shows only blank space:
![image](https://user-images.githubusercontent.com/34914144/64486888-8abeec80-d222-11e9-9907-e5d92fcb6b37.png)

## Reproduce
click on the left sidebar Extension Manager icon

## Context

- Operating System and version: macOS v10.14.6
- Browser and version: Google Chrome - Version 76.0.3809.132 (Official Build) (64-bit)
- JupyterLab version: 1.1.1
-  Extensions installed:
```
JupyterLab v1.1.1
Known labextensions:
   app dir: /Users/luka/miniconda3/envs/lab2/share/jupyter/lab
        @adamcsanders/theme-dark v1.0.0a1.1  enabled  OK
        @jupyter-widgets/jupyterlab-manager v1.0.2  enabled  OK
        @jupyter-widgets/jupyterlab-sidecar v0.4.0  enabled  OK
        @jupyterlab/celltags v0.1.5 disabled OK
        @jupyterlab/toc v1.0.1  enabled  OK
        ipyevents v1.6.3  enabled  OK
        ipysheet v0.4.3  enabled  OK
        jupyterlab-datawidgets v6.2.0  enabled  OK
        jupyterlab-floatview v0.2.0  enabled  OK
        jupyterlab-plotly v1.1.0  enabled  OK
        plotlywidget v1.1.0  enabled  OK
        qgrid v1.1.1  enabled  OK

```

**Comment by jasongrout** [comment] 2019-09-09 15:33
Can you go through the diagnosis guide to try to narrow down where the problem might be? https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html

**Comment by vivenkyan** [comment] 2019-12-04 20:36
I was getting the same error. I tried to uninstall Jupyter Lab and re-install with no effect. 
In my case it was due to an extension that I had uninstalled but somehow it was giving problem- (`@yeebc/jupyterlab_neon_theme`)

Even `$ jupyter lab build` wasn't working. I did the following then:

**1. Deleted these files** 
		/home/user_name/anaconda3/envs/embedRank/share/jupyter/lab/settings/build_config.json
/home/user_name/anaconda3/envs/embedRank/share/jupyter/lab/settings/page_config.json
	
These contained this info respectively:	
```
        {
	    "uninstalled_core_extensions": [
	        "@yeebc/jupyterlab_neon_theme"
	    ]
	}
	
	{
	    "disabledExtensions": [
	        "@yeebc/jupyterlab_neon_theme"
	    ]
	}
```

**2. Deleted the problematic extension**
/home/user_name/anaconda3/envs/embedRank/share/jupyter/lab/extensions/yeebc_jupyterlab_neon_theme.tgz

**3. Build again** `$ jupyter lab build`

**4. Restarted Jupyter Lab** 

My extensions were there now
I hope it helps.

**Comment by vidartf** [comment] 2020-01-14 11:16
If someone else gets this error, it would be very helpful if you could go through the diagnostics guide linked by Jason above. The more obscure logs we have access to, the more likely we will be able to properly find the cause of the issue.

**Comment by jasongrout** [comment] 2020-02-05 22:16
Closing since the author did not follow up. Please comment here if you'd like to continue the discussion.

**Closed by jasongrout** 2020-02-05 22:16 UTC
Labels: status:Needs Info

**Comment by samarthiith** [comment] 2020-03-05 09:38
I have the same problem.

**Comment by javicarron** [comment] 2020-03-05 11:42
I used to have this problem, but it got solved when I installed a new environment with a different theme. I am sorry I can not access it anymore to do any diagnostics, as I deleted it. Maybe this can be useful to someone anyway.
