### ISSUE TITLE
Output appears in wrong cell

### ISSUE THREAD

**Issue by thwee-alchemist** [jupyterlab/jupyterlab#3936] opened 2018-02-21 15:31 UTC
I'm running ijavascript and have an http/socket.io server running in one of the cells. The console output for that cell appears in the right place when I run the cell individually, but when I restart and run all cells,  the output for the sever cell appears in a later cell.

**Comment by ian-r-rose** [comment] 2018-02-21 15:35
Hi @thwee-alchemist, do you have a minimal notebook that you can share that reproduces the issue?

**Comment by jasongrout** [comment] 2018-02-21 15:36
Does this work in the classic Notebook?

**Comment by thwee-alchemist** [comment] 2018-02-21 17:24
This works in the classic notebook. Let me see if I can reproduce the issue
in a minimal notebook...

**Comment by thwee-alchemist** [comment] 2018-02-21 17:33
I reproduced the issue at
https://github.com/thwee-alchemist/output-in-wrong-cell.

**Comment by jasongrout** [comment] 2021-03-09 15:15
Is this still an issue?

**Comment by Krastanov** [comment] 2021-03-09 17:43
I do not remember seeing this issue in the last year.

**Comment by jasongrout** [comment] 2021-03-09 22:16
Closing then. Thanks for following up.

**Comment by krassowski** [comment] 2023-12-08 17:06
Reopening this one because I have a reliable reproducer and other issues were closed as a duplicate of this one. Namely, when any code is run async it will go to the most recently executed, rather than initial cell:

![async-case](https://github.com/jupyterlab/jupyterlab/assets/5832902/1cd21f60-d712-4def-84c0-3291b47de12a)

On some level I wonder if we should include cell IDs in the iopub messages?

<details>

```python
from threading import Thread
import asyncio

async def countdown(n=100):
    for i in range(n):
        await asyncio.sleep(0.1)
        print('\r', n - i, end='', flush=True)

loop = asyncio.get_event_loop()
loop.create_task(countdown())
```

</details>

**Comment by krassowski** [comment] 2023-12-21 21:53
https://github.com/ipython/ipykernel/pull/1186 proposes a solution on ipykernel side using [`contextvars`](https://docs.python.org/3/library/contextvars.html) to associate asyncio task emitting outputs with the appropriate execution request.

**Closed** 2024-01-16 14:41 UTC
Labels: bug, status:Needs Info, tag:Feature Parity, pkg:notebook, status:resolved-locked

**Comment by krassowski** [comment] 2025-10-16 19:23
In `ipykernel` 7.0.2+ this will require manually setting the desired output thread as per https://github.com/ipython/ipykernel/pull/1451
