### ISSUE TITLE
Unhandled promise rejection in future.js of @jupyterlab/services

### ISSUE THREAD

**Issue by alexeckert** [jupyterlab/jupyterlab#4790] opened 2018-06-27 14:41 UTC
Using v 2.0.3, when calling `kernel.dispose()` an unhandled future rejection might occur in `node_modules/@jupyterlab/services/lib/kernel/future.js:155`.

I've looked at the code, and it seems that there is some code which just tries to catch the rejected promise: See `this._done.promise.catch(() => { /* no-op */ });` here https://github.com/jupyterlab/jupyterlab/blob/master/packages/services/src/kernel/future.ts#L162

However when I look at the transpiled `future.js`, this part is missing, which leads to unhandled promise rejections.

```
    KernelFutureHandler.prototype.dispose = function () {
        this._stdin = Private.noOp;
        this._iopub = Private.noOp;
        this._reply = Private.noOp;
        if (!this._testFlag(Private.KernelFutureFlag.IsDone)) {
            this._done.reject(new Error('Canceled'));
        }
        _super.prototype.dispose.call(this);
    };
```

**Comment by afshin** [comment] 2018-06-27 14:46
This should be resolved with the merging of https://github.com/jupyterlab/jupyterlab/pull/4697 so the resolution will appear in our next release.

**Closed** 2018-06-27 14:47 UTC

**Comment by jtpio** [comment] 2018-09-27 21:45
I've seen something similar recently after using `ClientSession` to start Python kernels (on 0.34.10).

It also happens on `master` (tested on commit https://github.com/jupyterlab/jupyterlab/commit/98b4e6a73256d6a6980170fcde404ba3e2f6893d).

There seems to be different ways to reproduce this by just starting consoles. Sometimes it happens right after a fresh start:

![kernel_future](https://user-images.githubusercontent.com/591645/46176156-b285a080-c2ae-11e8-979a-e9c557008c26.gif)

Another way would be:

1. Open a Python file
2. Create Console for Editor
3. Wait for the console to be ready
4. Refresh the whole webpage (Empty Cache and Hard Reload)
5. Wait for a few seconds

![error_kernel_future_2](https://user-images.githubusercontent.com/591645/46176206-de088b00-c2ae-11e8-8c4d-4b5f132f74f8.gif)

#### Stacktrace for reference

```
future.ts:174 Uncaught (in promise) Error: Canceled
    at KernelFutureHandler.dispose (future.ts:174)
    at _futures.forEach.future (default.ts:858)
    at Map.forEach (<anonymous>)
    at DefaultKernel._clearState (default.ts:857)
    at DefaultKernel.dispose (default.ts:231)
    at DefaultSession.dispose (default.ts:218)
    at editorTracker.forEach.file (index.ts:201)
    at algorithm_1.each.widget (instancetracker.ts:268)
    at Object.each (iter.js:60)
    at InstanceTracker.forEach (instancetracker.ts:267)
```
