### ISSUE TITLE
Stderr shaded red can confuse users

### ISSUE THREAD

**Issue by jasongrout-db** [jupyterlab/jupyterlab#14298] opened 2023-03-30 15:19 UTC
### Problem

In JupyterLab, stderr outputs are shaded in red. However, sometimes stderr is used for a separate stream of information from stdout, not necessarily errors. For example, the Python logging module by default redirects logging messages to stderr (and, to be fair, by default limits messages to warning/error levels). If a user or package sets its logger level to info, the result is that the info messages appear as shaded red, which signifies to the user an error, but is not. This can be confusing to users.

To illustrate:

<img width="569" alt="Screenshot 2023-03-30 at 08 59 39" src="https://user-images.githubusercontent.com/95326326/228880556-f6941986-f772-42a3-988a-87759ceca1b8.png">

We've seen this recently at Databricks, where users are confused that info log messages are shaded red as if they were errors.

Note that a number of notebook products out on the market do not shade stderr as red.

### Proposed Solution

Brainstorming some options:

1. Keep the status quo. The logging module by default limits log levels to warning/error levels, so if no one changes the log level, red is consistent with logging warnings/errors showing up in stderr. This is consistent with the name "stderr", but inconsistent with how stderr is used in practice sometimes.
2. Shade stderr in a more neutral color (like light blue or green) so it still stands out as a separate text stream from stdout, but does not convey "this is an error" to the user.
3. (impractical) Petition the Python default logger to log warning/error messages on stderr and debug/info messages on stdout?

Thoughts?

### Additional context

Source for above screenshot is:
```python
# The default logging handler is to send messages to stderr,
# which is shaded red in Jupyter. The effect is that info
# and debug messages are also shaded red.
import logging
logging.basicConfig(level=logging.DEBUG)
logging.debug('debug message')
logging.info('info message')
logging.warning('warning message')
logging.error('error message')
```
```python
# A specific example - easy for a user to think
# the info messages are errors since they are shaded red.
logging.info('Starting task')
print('task output', flush=True)
logging.info('Ending task')
```

**Comment by ellisonbg** [comment] 2023-03-31 03:53
Yeah, the red background isn't great - it is also just difficult to look at. One option would be to to keep using the red color (to help users who are used to looking for the red) but reduce the visual area (maybe a vertical red bar to the left of the error, etc.).

**Comment by jasongrout-db** [comment] 2023-03-31 15:30
FYI, Chrome console uses this `#fffbe6` for their warning messages, which is easier to read, I think:
<img width="311" alt="Screenshot 2023-03-31 at 09 30 24" src="https://user-images.githubusercontent.com/95326326/229164459-15c8b605-f907-4b4a-804e-c72b138a1ade.png">

**Comment by krassowski** [comment] 2023-04-04 16:51
Some thoughts:
- would having a few colour options (light yellow/light red as is, etc) and allowing users to change it in settings help? Or is that something that only novice users would be concerned about and they would not search for a setting in the first place?
- did you consider [coloredlogs](https://pypi.org/project/coloredlogs/)? Are we doing good job in supporting output of packages like coloredlogs? Would an IPython extension, e.g. a magic, augmenting the logger  as shown in answers to https://stackoverflow.com/questions/384076/how-can-i-color-python-logging-output be a good solution?

**Comment by jasongrout-db** [comment] 2023-04-05 03:24
> * would having a few colour options (light yellow/light red as is, etc) and allowing users to change it in settings help?

Personally, I think it's better to have a standard single color for stderr so it is a consistent experience - I don't see people personalizing this a lot. However, I do see themes customizing it (since you might want to have different shading if your background is different, for example).

> * did you consider [coloredlogs](https://pypi.org/project/coloredlogs/)? Are we doing good job in supporting output of packages like coloredlogs?

I think coloredlogs and similar packages would be layered on top of this shaded background for stderr, so I think that would be an additional reason to make the background shading more similar to the normal background (so contrast isn't so much an issue).

**Comment by JasonWeill** [comment] 2024-02-10 02:03
Closing as duplicate of #7892.

**Closed by JasonWeill** 2024-02-10 02:03 UTC
Labels: status:Duplicate, enhancement, tag:Design and UX, tag:CSS

**Comment by etep** [comment] 2024-08-06 20:09
Hi @JasonWeill,

This does not look like a duplicate of #7892. That issue describes a background color that comes as a result of a literal error. This issue describes a background color that comes as a result of the use of `stderr`. There is a well known pattern where input and output are passed around via `stdin` and `stdout` which enables piped command lines like the following:
```cat some.pcap | some-binary | some-other-binary > output.pcap```
In this scheme (not my use case for Jupyter!), if any program has log information to print, it writes to `stderr`. I think this:
[Why python logging writes to stderr.](https://stackoverflow.com/questions/58971197/why-python-logging-writes-to-stderr-by-default) neatly encapsulates what I'm putting forward here.

I disagree with @jasongrout-db on the point of personalization: I see the background color for stderr as being a great candidate for personalization. In Python and in Jupyter, I use colored logs and those are written to stderr. The red background is sub-optimal.

Maybe this is already a configurable param somewhere, but if not, please consider opening the issue and creating some config so that the default red background for stderr can be changed.
