### ISSUE TITLE
Files - Sorting by Name and Last Modified

### ISSUE THREAD

**Issue by prathamatic** [jupyterlab/jupyterlab#2089] opened 2017-04-23 09:51 UTC
I am using Jupyter Lab version - 0.16.2.

I tried sort by Name and Last modified in Files section on Left hand side and observed following behaviour: 

Behaviour on Sort by Name: 
               a. Folders and files will be grouped 
               b. Folder will be shown first and sorted according to name 
               c. Files will be show after folders and sorted according to name 

Behaviour on Sort by Modified: 
              a. Folder and files are jumbled 
              b. Last modified file or folder will be shown first 

Is this expected behaviour and is there anyway to make both behaviour same? 

<img width="342" alt="sortbyname" src="https://cloud.githubusercontent.com/assets/895174/25312495/6f962680-2838-11e7-8745-4322df3b31d4.png">
<img width="336" alt="sortbylastmodified" src="https://cloud.githubusercontent.com/assets/895174/25312496/6f96682a-2838-11e7-82c0-6792a66d4740.png">

**Comment by blink1073** [comment] 2017-04-24 15:40
Sorting by name sorts them using the order they are listed on the server, which has the grouping.  When we sort them by timestamp we are sorting by that value only.

**Comment by prathamatic** [comment] 2017-04-24 18:04
I understand the logic, but This might be different behaviour for clicks on Name and Last modified. Are you guys planning to change this so that both sorting has same behaviour?

**Comment by blink1073** [comment] 2017-04-24 19:29
As of right now, this is the intended behavior, I marked it for 1.0 so we can get more feedback/make a final decision.

**Comment by sccolbert** [comment] 2017-04-24 19:38
I think we should keep the folders at the top for both sort modes. This should be a pretty simple change to the sort comparator.

**Comment by prathamatic** [comment] 2017-04-24 20:11
User experience should be consistent across both sort modes. I would go with first grouping and after sorting. Agree with @sccolbert

**Comment by blink1073** [comment] 2017-04-25 12:17
Part of the issue is that the server also sorts notebooks together, should we preserve that when sorting by last modified?

**Comment by prathamatic** [comment] 2017-04-29 17:29
Is server ungrouping and sorting them on time?

**Comment by blink1073** [comment] 2017-04-30 19:10
The original order is from the server, which is an implementation detail of the [ContentsManager](https://github.com/jupyter/notebook/blob/4f4ff3141cc0ec2ed613e54bde08fd9f18804943/notebook/notebookapp.py#L894) that the notebook server uses by default (can be overridden).  When we sort by last modified, we are currently doing so on the client without regard to the original ordering given by the server.  If we sort by type and then last modified on the client, we would have to assume the default groupings were valid.

**Comment by prathamatic** [comment] 2017-05-01 06:18
I understand your point, but even current sorting on time is overriding the original order given by server, so even if we group by first and then do last modified, we will still be overriding server order.

**Comment by blink1073** [comment] 2017-05-01 12:38
Agreed that by `type` (directory, file, notebook), and then by name or last modified is the best solution for now.

**Comment by prathamatic** [comment] 2017-05-02 13:37
Will this go as one of the features?

**Comment by prathamatic** [comment] 2017-05-02 18:23
Thanks

**Comment by ellisonbg** [comment] 2017-07-06 00:20
I think this is done in master?

**Comment by blink1073** [comment] 2017-07-06 00:35
Yep, fixed by https://github.com/jupyterlab/jupyterlab/pull/2438.

**Closed by blink1073** 2017-07-06 00:35 UTC
Labels: pkg:filebrowser, tag:Design and UX, type:Enhancement
