### ISSUE TITLE
[Feature Request] Synchronize the markdown preview and the markdown editor.

### ISSUE THREAD

**Issue by caizefeng** [jupyterlab/jupyterlab#8401] opened 2020-05-10 04:43 UTC
Fascinating project!
But is it possible to enable the synchronization between the markdown perview window and the editor window?
People would like it if the preview window can automatically scroll up or down to the position where the editor window focus on, and vice versa. (in 2-windows mode)

![](https://raw.githubusercontent.com/caizefeng/Imgs/master/ydn_img/Annotation%202020-05-10%20124002.png)

This feature is available in other common markdown editors like typora.

**Comment by AbhinavA10** [comment] 2020-11-09 03:46
:+1: I'd like to know if this is possible as well. This would be quite neat!
VSCode has this feature, and it makes editing markdown files very pleasant.

**Comment by jasongrout** [comment] 2021-03-05 18:38
This is a duplicate of https://github.com/jupyterlab/jupyterlab/issues/4323 - let's consolidate the discussion there since it is the earlier issue. Thanks!

**Closed by jasongrout** 2021-03-05 18:38 UTC
