### ISSUE TITLE
Find/replace: creating a new cell triggers activation/scroll to cell with current match

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/jupyterlab#6701] opened 2019-06-25 04:10 UTC
Here's an illustration of the problem. Say that I have the find/replace dialog open, and that I have a match in an existing cell:

![image](https://user-images.githubusercontent.com/2263641/60068324-305ec700-96dc-11e9-91ac-f5de7d465e1f.png)

If I then scroll to the bottom of the notebook and hit `B` in order to make a new cell, this is what happens:

![jupyterlab_jupyterlab_6701](https://user-images.githubusercontent.com/2263641/60068737-fa224700-96dd-11e9-8d7b-d59d0fcf6a59.gif)

The new cell does get created, but the scroll snaps back to the find/replace match, and the focus snaps to the cell containing the match. Instead, jlab should follow its standard behavior here and focus on/scroll to the newly created cell:

![image](https://user-images.githubusercontent.com/2263641/60068622-7ff1c280-96dd-11e9-8a6f-5640df10d4a2.png)

Further, as long as find/replace is open, jlab will snap back to the match under a number of different circumstances (including on deletion of an existing cell), but I figure if we fix one of these issues it's likely we'll have fixed them all.

**Comment by aschlaep** [comment] 2019-06-25 23:06
After looking at this a bit, it's not going to be super straightforward to fix in a clean way.  What's happening here is that when a change is made to the notebook, the `NotebookSearchProvider` calls `endQuery()` and then `startQuery()` to make sure that if cells were copied/deleted, search matches in any new cell(s) are shown and changes are reflected in the x/y counter in the dialog.  When `startQuery()` is called, it does the work of building the match state and highlighting the matches on the screen.  It finishes up by calling `highlightNext()` to highlight the next match after the cursor's current position.  `NotebookSearchProvider::hightlightNext` calls `CodeMirrorSearchProvider::highlightNext`, which calls `CodeMirrorSearchProvider::_findNext()` is what sets the selection.  We'd need to pass in the `{ scroll: false }` option object to that call to `setSelection()` only in the case where we're restarting the search on a notebook cell list changed signal.  I don't see a very straightforward way of doing that, unfortunately.

So the scrolling is done here:
https://github.com/jupyterlab/jupyterlab/blob/25082f0f1010235f30857bfcdf5b6a15e80f2469/packages/documentsearch/src/providers/codemirrorsearchprovider.ts#L475

And the call stack looks like:
`CodeMirrorEditor.setSelection`
`CodeMirrorSearchProvider._findNext`
`CodeMirrorSearchProvider.highlightNext`
`NotebookSearchProvider._stepNext`
`NotebookSearchProvider.startQuery`
`NotebookSearchProvider._restartQuery`
`Notebook.model.cells.changed` signal fired

**Comment by telamonian** [comment] 2019-06-25 23:21
Probably a reasonable first step would be to only enable the scrolling behavior when the search box is focused/clicked in. That implies that the user is focused on search at that moment, in which case the scrolling behavior is convenient. I think it would be safe to assume that if the search box isn't the focused element then the scroll behavior will always be inconvenient.

Is the search box a widget? If so then the above should be pretty straightforward to implement.

Longer term, it might be worthwhile to look into what eg Chrome's searchbox does when a page's contents change.

**Comment by aschlaep** [comment] 2019-06-27 17:00
The search box is a widget, but limiting scrolling to only when the search box is focused would break <kbd>ctrl</kbd> + (<kbd>shift</kbd>) + <kbd>g</kbd>, which calls `highlightNext` or `highlightPrevious` and can be used even when the search box is unfocused.  I do agree though that the execution of the search itself could do with some smarter optimizations.  The reason it's completely redoing the search when the content changes is because it needs to recount the matches to make sure the current highlighted index number is correct and update the index of each match object (currently unused, though was intended to be used once we do whole workspace search).

**Comment by telamonian** [comment] 2019-06-27 18:18
Ah, I hadn't thought of <kbd>ctrl</kbd> + <kbd>g</kbd>. That is somewhat trickier than I assumed.

> The reason it's completely redoing the search when the content changes is because it needs to recount the matches to make sure the current highlighted index number is correct...

I just checked. If the contents of a page change, the search boxes of both Firefox and Chrome will postpone that kind of recalculation until the next search event (eg the user hits <kbd>ctrl</kbd> + <kbd>g</kbd>). Can we take this same approach?

**Comment by krassowski** [comment] 2019-07-03 14:15
The same happens when trying to change cell type. Here I had a focus on code cell 6 and pressed <kbd>m</kbd> to change it to markdown: 

![Screenshot from 2019-07-03 15-09-53](https://user-images.githubusercontent.com/5832902/60598728-1e98b600-9da5-11e9-88c8-f277434c0431.png)

While the type it was correctly changed it jumped to the current search result at the end of the notebook:

![Screenshot from 2019-07-03 15-10-27](https://user-images.githubusercontent.com/5832902/60598783-38d29400-9da5-11e9-9326-27b56620aba0.png)

**Comment by BrenBarn** [comment] 2020-01-02 05:06
This bug still exists and is a serious annoyance that makes the Jupyterlab search seem quite crippled.

Focus should only shift to search results in response to an explicit search action.  I agree that it would be fine to defer any UI updates (e.g., to the "match # X/Y" text) until an explicit search action.  I think that all the recalculation (basically the entire search operation) should be taken out of the call chain from the "changed" event handler and only happen when a search is actually performed (via CTRL+g or a click on a search button).

**Comment by thomasaarholt** [comment] 2021-01-19 10:18
I'll add that this also happens when cutting a cell, and on my laptop (3 year old "standard Dell"), cutting or adding a cell while search is active becomes very slow in a larger notebook.

Perhaps the developers who are interested could take a look at this with fresh eyes?

**Comment by krassowski** [comment] 2021-08-03 21:50
This was fixed in #7835 included in JupyterLab 2.0 release. I will close this issue as we are currently at JupyterLab 3.1.

Demo of this working as expected:

![works-ok-now](https://user-images.githubusercontent.com/5832902/128090951-7a83bb02-b38a-4f9a-afe0-a73b11afcbaa.gif)

**Closed by krassowski** 2021-08-03 21:50 UTC
Labels: bug, pkg:documentsearch, tag:Design and UX
