### ISSUE TITLE
add `Run All` or `Restart Kernal and Run All` into both keyboard shortcut setting and command palette

### ISSUE THREAD

**Issue by YongcaiHuang** [jupyterlab/jupyterlab#16912] opened 2024-11-03 15:48 UTC
### Problem
It is not that convenient to write and run the python scrip (.py file). I have to go to the run manu first and then click `Run All` or `Restart Kernal and Run All`. I also find there is no keyboard shortcut can be set or command in command palette. My current solution is select all and run selected, although I think it is not that convenient.

<img width="381" alt="image" src="https://github.com/user-attachments/assets/306ec559-af37-4faf-bc17-bb3e7b4a078d">

<img width="448" alt="image" src="https://github.com/user-attachments/assets/d27a751a-1279-4683-a352-2459f879d7fd">

<img width="462" alt="image" src="https://github.com/user-attachments/assets/a47078e7-47ab-426c-a13e-256895d70bf0">

### Proposed Solution
it would be great to add `Run All` or `Restart Kernal and Run All` into both keyboard shortcut setting and command palette.

### Additional context

JupyterLab 4.3.0

**Comment by krassowski** [comment] 2024-11-05 09:29
Thanks for the report!

> it would be great to add `Run All` or `Restart Kernal and Run All` into both keyboard shortcut setting [...].

I agree! Though this looks like a duplicate of:
- https://github.com/jupyterlab/jupyterlab/issues/13705 (which covers the keyboard shortcuts setting part).

There is also a stale PR which needs rebasing:
- https://github.com/jupyterlab/jupyterlab/pull/14015

I would love to see it in 4.4.0 but might not have time to work on it myself - but I would certainly find time to review a PR and guide any contributors willing to take this on.

> it would be great to add `Run All` or `Restart Kernal and Run All` into [...] and command palette.

I believe these are already in the command palette:

![Screenshot from 2024-11-05 09-27-55](https://github.com/user-attachments/assets/53d69032-2852-4763-99ff-97c0b7961312)
![Screenshot from 2024-11-05 09-27-50](https://github.com/user-attachments/assets/315612bd-2b26-4b21-999a-de3d0fc48384)

Is it good to close as a duplicate?

**Comment by JasonWeill** [comment] 2024-11-05 17:15
Closing as a duplicate of #13705. Let's keep the conversation going there.

**Closed by JasonWeill** 2024-11-05 17:15 UTC
Labels: enhancement, status:Needs Triage
