### ISSUE TITLE
Jupyter lab menu bar is missing

### ISSUE THREAD

**Issue by rayh2020** [jupyterlab/jupyterlab#13573] opened 2022-12-12 12:34 UTC
Hi,

the menu bar is missing when I open up jupyter lab in chrome. could you please help me get it back.

The errors I find from chrome are :
jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2 ReferenceError: WeakRef is not defined
    at new ir (jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2)
    at or.insertItem (jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2)
    at or.addItem (jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2)
    at i (jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2)
    at jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2
    at Array.map (<anonymous>)
    at n (jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2)
    at i (jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2)
    at jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2
    at Array.map (<anonymous>)
(anonymous) @ jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2
jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2 Plugin '@jupyterlab/help-extension:resources' failed to activate.
(anonymous) @ jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2
jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2 ReferenceError: WeakRef is not defined
    at new ir (jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2)
    at or.insertItem (jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2)
    at or.addItem (jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2)
    at i (jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2)
    at jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2
    at Array.map (<anonymous>)
    at n (jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2)
    at i (jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2)
    at jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2
    at Array.map (<anonymous>)
(anonymous) @ jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2
jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2 Plugin '@jupyterlab/translation-extension:plugin' failed to activate.
(anonymous) @ jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2
jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2 ReferenceError: WeakRef is not defined
    at new ir (jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2)
    at or.insertItem (jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2)
    at or.addItem (jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2)
    at i (jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2)
    at jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2
    at Array.map (<anonymous>)
    at n (jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2)
    at i (jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2)
    at jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2
    at Array.map (<anonymous>)
(anonymous) @ jlab_core.10fe219debf69ce9aa32.js?v=10fe219debf69ce9aa32:2
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/6700.c96344a466d1896657bf.js.map?v=c96344a466d1896657bf
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/main.ba640423c18189c6f571.js.map?v=ba640423c18189c6f571
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/4155.784ca1752696680bf373.js.map?v=784ca1752696680bf373
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/1036.a055f7326513fc5a04f7.js.map?v=a055f7326513fc5a04f7
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/2719.3fe9e6fa24f270d8b8d1.js.map?v=3fe9e6fa24f270d8b8d1
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/4570.53adcb6f69939da383ff.js.map?v=53adcb6f69939da383ff
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/9473.2e52d2ba788beec303be.js.map?v=2e52d2ba788beec303be
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/7294.f71c2889fedcd71bd1ee.js.map?v=f71c2889fedcd71bd1ee
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/3935.4159b022aa6d82e44127.js.map?v=4159b022aa6d82e44127
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/1033.890eeae47460e241b1e9.js.map?v=890eeae47460e241b1e9
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/5096.96faf5ddac346a9ad9c3.js.map?v=96faf5ddac346a9ad9c3
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/1142.074d125bb59f5a332666.js.map?v=074d125bb59f5a332666
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/3308.3a94151c0d57440646ab.js.map?v=3a94151c0d57440646ab
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/807.381f2a52fee17a03f5bc.js.map?v=381f2a52fee17a03f5bc
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/4631.96a143e70f005fef7b59.js.map?v=96a143e70f005fef7b59
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/7755.d506a1d9dadf30b1e490.js.map?v=d506a1d9dadf30b1e490
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/6080.78e4d399b3bc0d7f376c.js.map?v=78e4d399b3bc0d7f376c
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/2040.6489997c35a5d7b0b100.js.map?v=6489997c35a5d7b0b100
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/1057.a0608544097dd22a589e.js.map?v=a0608544097dd22a589e
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/3502.c915d993b864739407e3.js.map?v=c915d993b864739407e3
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/3029.8636761a48c8422ce37f.js.map?v=8636761a48c8422ce37f
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/294.ac30890c62bd6754cc7b.js.map?v=ac30890c62bd6754cc7b
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/4151.fd7ca59b64f0adc97032.js.map?v=fd7ca59b64f0adc97032
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/4429.c4f083ef6b6e29345fd4.js.map?v=c4f083ef6b6e29345fd4
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/126.aaf215b7858daacad7c6.js.map?v=aaf215b7858daacad7c6
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/911.0c08f040896753efc653.js.map?v=0c08f040896753efc653
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/3496.ecb0e7fcc54191234ae6.js.map?v=ecb0e7fcc54191234ae6
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/466.239a0c009f33f1cb7cab.js.map?v=239a0c009f33f1cb7cab
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/1249.047c76b5ea96a41605db.js.map?v=047c76b5ea96a41605db
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/1358.9ab4f57e8227ce75f427.js.map?v=9ab4f57e8227ce75f427
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/7796.1c22f93923a532922dc1.js.map?v=1c22f93923a532922dc1
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/714.ff3007d0b781b5538482.js.map?v=ff3007d0b781b5538482
DevTools failed to parse SourceMap: http://localhost:8888/static/lab/jlab_core.10fe219debf69ce9aa32.js.map?v=10fe219debf69ce9aa32
nbsafety-project.png:1 GET https://github.com/nbsafety-project.png?size=32 404

**Comment by krassowski** [comment] 2022-12-12 22:32
@rayh2020 thank you for opening the issue. This appears to be a duplicate of #12862 and it is very likely that you are using an outdated and probably unsupported version of Chrome. Please see https://github.com/jupyterlab/jupyterlab/issues/12862#issuecomment-1347433054 for details.

Just to confirm, would you mind sharing which version of Chrome are you using?

**Comment by rayh2020** [comment] 2022-12-13 14:48
it solved after updating to the latest google chrome

**Closed** 2022-12-13 18:40 UTC
Labels: bug, status:Needs Triage
