### ISSUE TITLE
Cell lines cut off <jupyterlab==0.35.1>

### ISSUE THREAD

**Issue by jingw222** [jupyterlab/jupyterlab#5520] opened 2018-10-21 14:14 UTC
<img width="706" alt="image" src="https://user-images.githubusercontent.com/5494367/47268056-74626080-d57e-11e8-9cb0-1dd31b41b931.png">

**Comment by gnestor** [comment] 2019-02-15 20:09
I've observed this and it seems like a common occurrence when screen sharing. I can't reproduce when simply resizing the browser or changing the screen's resolution, but hopefully this provides some clues...

**Comment by gnestor** [comment] 2019-02-15 20:09
Related to https://github.com/jupyter/notebook/issues/1467

**Comment by jasongrout** [comment] 2019-02-15 22:20
Is there something you can do to get the codemirror to refresh as a workaround? Like dragging a splitter, clicking a new tab and back, etc.?

**Comment by whyboris** [comment] 2019-03-19 16:34
I've had this issue because of changing to a lower resolution: https://github.com/jupyter/notebook/issues/1467

Fixing the bug was simple: 
by zooming out to 90% and zooming back in to 100% with Chrome `Ctrl` + `-` / `+`

**Comment by wesinator** [comment] 2019-09-09 13:20
also reported at https://github.com/jupyterlab/jupyterlab/issues/4156#issuecomment-510525207
cc @jasongrout 

still experiencing this Firefox 69.0 macOS 10.14

**Comment by jasongrout** [comment] 2019-09-09 14:13
@wesinator - can you go through the diagnosis guide to try to narrow down where the problem might be, and include the information mentioned there to help us reproduce the issue? https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html

**Comment by jasongrout** [comment] 2020-02-05 22:05
Closing since the author never followed up. Please comment here if you'd like to continue the discussion.

**Closed by jasongrout** 2020-02-05 22:05 UTC
Labels: status:Needs Info

**Comment by wesinator** [comment] 2020-02-15 18:59
> @wesinator - can you go through the diagnosis guide to try to narrow down where the problem might be, and include the information mentioned there to help us reproduce the issue? https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html

jupyterlab 1.2.4, 1.2.6
macOS 10.14.6 Macbook Pro 15-inch retina
Firefox 72.0.2 

**To reproduce:**
 - Connect external 1920x1080 monitor (display adapter or dock)
 - Drag browser tab window to monitor if it doesn't automatically move
 - Jupyter notebook with many cells, long scroll 
 - Cursor in cell edited (cell above latest)
 - Disconnect from external display

**workaround:** opening the browser console seems to reset the page view
(the issue is not in console, obviously - it's a UI behavior)
