### ISSUE TITLE
Text in Terminal does not render properly - V4

### ISSUE THREAD

**Issue by rhlarora84** [jupyterlab/jupyterlab#14687] opened 2023-06-14 19:44 UTC
## Description
Text in Terminal does not render properly and the text color is most of the time same as the theme background color. The text color updates properly after typing more characters or executing the command.

## Reproduce

Launch docker container using the below image

`docker run -p 8888:8888 jupyter/datascience-notebook:lab-4.0.0 `

Open the Terminal and type any command/text.

See attached video.

https://github.com/jupyterlab/jupyterlab/assets/15618263/b2f5eeb1-2578-41a2-9d74-d6fdd95aa92e

This is not an issue in the previous version of the image

`docker run -p 8888:8888 jupyter/datascience-notebook:lab-3.6.3`

## Expected behavior

Text entered on Terminal should be visible.

**Comment by appleparan** [comment] 2023-08-16 02:19
In my environment, firefox doesn’t have the issue (edge and chrome have the one). Isn’t it related to chromium & xterm.js things?

**Comment by appleparan** [comment] 2023-08-24 01:05
I have identified the [following](https://github.com/xtermjs/xterm.js/issues/4665) [issue](https://github.com/microsoft/vscode/issues/190195)  and it seems to be related to the same phenomenon as this current problem. It appears to be a clear xterm.js issue, and I hope it will be addressed by the xterm.js team.

**Comment by JasonWeill** [comment] 2024-01-30 01:05
https://github.com/xtermjs/xterm.js/issues/4665 was fixed in September 2023. Is this still a problem in more recent JupyterLab 4 versions?

**Comment by appleparan** [comment] 2024-01-30 01:08
@JasonWeill No, I’ve tested with 4.0.10, and I can confirm this issue was fixed.

**Comment by JasonWeill** [comment] 2024-01-30 01:09
@appleparan Thank you for the quick response! I'll close this issue, then.

**Closed by JasonWeill** 2024-01-30 01:09 UTC
Labels: bug, pkg:terminal
