### ISSUE TITLE
Issue with markdown editor

### ISSUE THREAD

**Issue by ericmjl** [jupyterlab/jupyterlab#522] opened 2016-07-22 23:25 UTC
I'm struggling to describe this clearly, but on Mac OS X 10.11.6 (15G31) in Safari (Version 9.1.2 (11601.7.7)), running Jupyter lab with commit a645b08, I noticed that the Markdown editor in the Jupyter notebook isn't working "smoothly". Particularly, spaces are not rendered clearly in the Markdown editing mode. I tried conveying this as best as I could with a silent screencast.

https://www.dropbox.com/s/mx1m7pmxk6sxu46/markdown-issues.mov?dl=0

I'm happy to answer clarifying questions if the devs need them answered!

**Comment by jasongrout** [comment] 2016-07-23 01:18
Oh wow, that is really weird. Does it work with Chrome or Firefox?

**Comment by ericmjl** [comment] 2016-07-23 22:49
Just did another silent screencast:

https://www.dropbox.com/s/6pknf40o1nmkmwe/markdown-issues-2.mov?dl=0

It appears that Markdown editing is fine in Chrome and Firefox. Not sure if on your end Safari users are experiencing the same thing?

This time round, I was on commit 1ae9e37b92ccf90827b223c2aa12e17e792c545c.

**Comment by blink1073** [comment] 2016-08-25 14:48
I confirmed this differs between Notebook and JupyterLab.  When typing a space in the cell editor, it does not move the cursor forward until you type another character.

**Comment by blink1073** [comment] 2016-08-25 14:50
It does not occur in "Code" mode, but does occur in "Raw" mode.  I think this may just be a CodeMirror setting we are missing.

**Comment by jasongrout** [comment] 2016-08-25 16:27
I confirmed this in Safari for markdown and raw cells too. Looking into it.

**Comment by jasongrout** [comment] 2016-08-25 16:42
Here is a screencast showing the problem. It seems that codemirror is calculating the wrong position for the cursor (note the cursor left position in the debug window). This doesn't seem to happen in codemirror's markdown demo at https://codemirror.net/mode/gfm/index.html. @minrk - do you see this happening in the tech preview? (I can't install the tech preview since my OS is too old right now.)

![safari-cursor](https://cloud.githubusercontent.com/assets/192614/17977818/2f5831c4-6ac1-11e6-98ec-69597b1c9820.gif)

**Comment by jasongrout** [comment] 2016-08-25 17:16
I dove into some internals of Codemirror, and got as far as realizing that the line measurement cache seems to be off (referenced at https://github.com/codemirror/CodeMirror/blob/master/lib/codemirror.js#L2580, which has the positions of specific characters, called from https://github.com/codemirror/CodeMirror/blob/master/lib/codemirror.js#L2856). Interestingly, when unhiding the Codemirror-measure div (and disabling the height 0 for that div), the super-imposed `x`s indicate that the cursor jumps to the right spot after two spaces.

I'm leaving it there for now. If the tech preview doesn't have the problem, it'd be nice.

**Comment by jasongrout** [comment] 2016-08-25 18:14
I pinpointed the rule that causes this problem in #764.

**Comment by blink1073** [comment] 2016-08-30 12:05
The rule is:

```css
.jp-CellEditor .CodeMirror-lines {
   padding: 0.4em;
}
```

**Comment by jasongrout** [comment] 2016-09-02 19:42
Assigning to @ellisonbg since he is looking closely at the styling issues. Feel free to reassign, of course.

**Comment by blink1073** [comment] 2016-10-24 11:48
This issue is not present using latest master and Safari 10.0.

**Closed by blink1073** 2016-10-24 11:48 UTC
Labels: cat:Browser Compatibility, cat:Design and UX, component:Notebook, type:Bug

**Comment by gnestor** [comment] 2016-12-15 06:19
This is affecting notebook, too. I tried making the changes made in https://github.com/jupyterlab/jupyterlab/issues/764 but no luck. Any ideas?

**Comment by blink1073** [comment] 2016-12-15 13:04
I haven't been able to reproduce the issue on either notebook nor lab, I'm not sure what to do.

**Comment by blink1073** [comment] 2016-12-15 13:08
I spoke too soon, I am seeing it in Notebook 4.3 on Safari 10.0.2 but not in lab.  Both are using Codemirror 5.21.

**Comment by blink1073** [comment] 2016-12-15 13:12
Note we are no longer using `em` for the padding.

**Comment by blink1073** [comment] 2016-12-15 13:21
cf https://github.com/jupyter/notebook/blob/179bb24fbf79d153812858126127a91431da3319/notebook/static/notebook/less/variables.less#L12

**Comment by blink1073** [comment] 2016-12-15 13:21
and https://github.com/jupyter/notebook/blob/179bb24fbf79d153812858126127a91431da3319/notebook/static/notebook/less/codemirror.less#L29

**Comment by gnestor** [comment] 2016-12-15 16:23
Yes, I can confirm that it's working as expected in lab. 

I have tried disabling `.CodeMirror-lines` but no luck. I also compared the CSS rules of notebook and lab side-by-side and I don't see any obvious discrepancies. 

I see that lab has switched from LESS to CSS so the above `variables.less` doesn't exist anymore. I wonder what else may have changed that affected this? 🤔
