### ISSUE TITLE
SourceMap mislocated on JupyterLab running on a JupyterHub?

### ISSUE THREAD

**Issue by consideRatio** [jupyterlab/jupyterlab#8055] opened 2020-03-19 16:39 UTC
I lack a lot of understanding of relevance here, but I think I fail to get SourceMap's for JupyterLab when working against a JupyterLab instance in JupyterHub where the root path of the jupyterlab server is `/home/erik` rather than `/`.

Could this be the reason for me failing to inspect non-minimized source code? I would love to improve the debugging experience on JupyterLab's served through JupyterHub if possible as I do it a lot. Having the source map can make me track down issues to the respective JupyterLab extension and avoid looking for answers in the wrong places.

The reason for me suggesting there may be a JupyterHub + JupyterLab issue is that I saw this line in the end of the screenshot below:

```
DevTools failed to parse SourceMap: https://jupyter.dsp.sandvik.com/42870dd85cfc9e317c9d.worker.js.map
```

... while I was running JupyterLab under the path `https://jupyter.dsp.sandvik.com/user/erik.sundell@sandvik.com` rather than under https://jupyter.dsp.sandvik.com/`.

![image](https://user-images.githubusercontent.com/3837114/77090818-f969d780-6a07-11ea-8981-84ac2f9b75ff.png)

## Question
Is this a JupyterHub + JupyterLab interaction issue?
Is there something else that would made me able to click on the vendor source files and get a nice view on the source code?

**Comment by LuisFRoch** [comment] 2020-06-05 20:13
Hi @consideRatio, I just encountered the same error running a different process. Did you solve this issue? If so, can you provide steps to solving the issue?

Thanks in advance

**Comment by consideRatio** [comment] 2020-06-05 21:08
No update from my end =/

**Comment by LuisFRoch** [comment] 2020-06-05 22:12
> No update from my end =/

This appears to have solve part of my issue: [https://github.com/jupyter-widgets/widget-ts-cookiecutter/issues/39](url)

**Comment by a3626a** [comment] 2022-04-15 02:15
I think there is no source map file at all.
https://github.com/jupyterlab/jupyterlab/releases/download/v3.3.3/jupyterlab-3.3.3.tar.gz
After downloading this file, I can access minified js files.

For example, `9845.8b6c837a5ff754554b39.js` has source map directives, `//# sourceMappingURL=9845.8b6c837a5ff754554b39.js.map?v=8b6c837a5ff754554b39` but there is no `9845.8b6c837a5ff754554b39.js.map`.

Additionally, jupyter lab without hub shows same error in browser consoles.

I think `.map` fils are ignored during build process.

**Comment by vidartf** [comment] 2023-02-17 16:31
Closing in favor of #7851, which I believe is the root cause of this issue.

**Closed by vidartf** 2023-02-17 16:31 UTC
