### ISSUE TITLE
[Feature Request] Shorten "Modified Last" column details

### ISSUE THREAD

**Issue by jrwrigh** [jupyterlab/jupyterlab#6355] opened 2019-05-15 14:38 UTC
In the file browser, the "Last Modified" column has the format "## [minutes|hours|days] ago". It'd be nice if this could be shortened to "## [min|hrs|day]".

Alternatively, the ability to hide the column all together would also be pretty nice too.

**Comment by jasongrout** [comment] 2019-05-21 15:00
Putting as 1.0 for the design review since this column really takes up a lot of room in the design, and anything to shorten it would be great.

**Comment by ellisonbg** [comment] 2019-05-22 17:06
Closing as a duplicate of https://github.com/jupyterlab/jupyterlab/issues/6093

The way the question way described is slightly different, but the solution is the same (width conditional styling).

**Closed by ellisonbg** 2019-05-22 17:06 UTC
Labels: tag:Design and UX
