### ISSUE TITLE
Right clicking in the blank part of the files section doesn't bring up a context menu.

### ISSUE THREAD

**Issue by SimonBiggs** [jupyterlab/jupyterlab#3602] opened 2018-01-11 04:13 UTC
![image](https://user-images.githubusercontent.com/6559099/34808248-c32033f4-f6e1-11e7-8b4f-ac7fb1c093d7.png)

I right clicked in that location expecting to see menu items like "create new directory", "create new file", etc.

**Comment by jasongrout** [comment] 2018-01-11 05:43
Note that even where there are files, there is no "create new directory" or "create new file" options in the context menu.

I agree that in a normal file manager, I would have expected those options in a right click in the empty space.

**Comment by ian-r-rose** [comment] 2018-02-14 15:30
I think the cause of this is that the hit-test for the listing ends at the end of the listing for click events. If the listing is short or empty, this means it can be hard or impossible to trigger the context menu.

**Comment by jasongrout** [comment] 2018-03-27 16:15
This is coming up over and over again, and should be relatively easy, so moving to beta 2

**Comment by ian-r-rose** [comment] 2018-03-27 16:58
Unfortunately, the file browser context menu is special-cased, and not using the global application context menu. This makes modifying and extending it rather more difficult than we would want. See also #3775 and #3994.

**Comment by jasongrout** [comment] 2018-03-27 22:02
> Unfortunately, the file browser context menu is special-cased, and not using the global application context menu. This makes modifying and extending it rather more difficult than we would want. See also #3775 and #3994.

Thanks for looking at this!

**Closed** 2018-03-29 22:30 UTC
Labels: pkg:filebrowser, type:Enhancement

**Comment by SimonBiggs** [comment] 2018-03-29 23:44
Does this also cover "create new directory" and "create new file"?

Not worried if it doesn't. Just realised this issue sort of became about two things, the paste context menu, but also the other items also.

**Comment by ian-r-rose** [comment] 2018-03-29 23:46
It does not add create new directory/file. I thought it was a bit out of scope of this bugfix, since they were not present in the usual context menu. Happy to continue discussing whether to add them, though.

**Comment by jasongrout** [comment] 2018-03-29 23:51
Let's make a new issue for the new items

**Comment by SimonBiggs** [comment] 2018-03-30 00:04
Done :)
