### ISSUE TITLE
Responding bash prompt inside a cell output

### ISSUE THREAD

**Issue by rezaeir** [jupyterlab/jupyterlab#8522] opened 2020-06-06 13:09 UTC
### Problem
As much as I know, there is no such feature in jupyterlab to answer prompts like 'yes/no questions' or other prompts in jupyterlab. However, the Google Colab version of the jupyterlab has this built-in feature.

### Proposed Solution
The best thing is to use Colab code, if it is opensource, to add this feature because Colab is very similar to jupyterlab.

### Additional context

Using bash tools is a large part of my bioinformatics pipelines. I also use Python and R along with bash. Recently, I came across a plugin for Jupiter, Script of scripts (SoS) which makes it possible to run bash, Python, R, and other kernels in the same notebook which is really awesome. Having the possibility of answering bash prompts would be very helpful for my work. I know it is possible to use printf <prompt_answer> and pipe it to the next command. However, being able to answer prompts instantaneously is much better.

**Comment by jasongrout** [comment] 2020-06-06 15:12
JupyterLab supports the Jupyter standard for gathering standard input in cell outputs. To see this, for example, run some python code like `input('prompt: ')`, and you'll see a text box to give some stdin text.

It sounds like you are wanting this for the bash prompt, so the bash kernel needs to figure out when it needs input from stdin and send that request to JupyterLab. If you are using the SoS kernel, can you file an issue there?

**Comment by jasongrout** [comment] 2020-06-06 15:14
Can you post a screenshot of what Colab does?

@blois - do you happen to know what Colab does to get stdin in bash (if I'm understanding @rezaeir  correctly)?

**Comment by rezaeir** [comment] 2020-06-06 16:20
@jasongrout I know that if I explicitly state that I have an input field in python, jupyterlab will prompt an input box for me. I want it to do so when I don't ask explicitly ask but what I run in the cell asks!! I mean like when installing a package with `!pip` or when running a bash script.  
regarding example, I've tests this functionality in colab myself but I reference a question in [StackOverflow](https://stackoverflow.com/questions/49431895/answering-yes-no-shell-prompt-on-notebook).  
This picture is also from the same StackOverflow ![prompt responding in colab](https://i.stack.imgur.com/7hCnv.png)

**Comment by echarles** [comment] 2020-06-07 08:12
@rezaeir I have tested the snippet provided by @jasongrout in jlab and it gives similar results to what you show from collab.

<img width="626" alt="Screenshot 2020-06-07 at 10 10 50" src="https://user-images.githubusercontent.com/226720/83963562-5195d480-a8a7-11ea-8722-5901a38097db.png">

**Comment by rezaeir** [comment] 2020-06-07 08:25
@echarles 
No the point is that colab asks for input even when there is no clear input command in the function call. However, jlab just asks when you explicitly type an input() command

**Comment by rezaeir** [comment] 2020-06-07 12:39
@echarles consider the following example which doesn't have any explicit `input` or `read` function associated with it:
```
!touch something.txt
!rm -i something.txt
```
If I run this code in colab, a prompt will come up and ask me if I want to delete `something.txt`. However, if I run the same code in jlab, the kernel keeps running in that cell and I get no prompt or any other output until I interrupt the kernel manually!!

**Comment by echarles** [comment] 2020-06-07 16:09
Thx for clarification @rezaeir. I have done a few debugging on kernel communication level with google deverloper tool and kernel-spy.

For `a = input('Prompt: ')`, the kernel sends to jupyterlab a [stdin message](https://jupyter-protocol.readthedocs.io/en/latest/messaging.html#messages-on-the-stdin-router-dealer-channel) and jupyterlab opens the prompt as expected.

<img width="507" alt="Screenshot 2020-06-07 at 18 05 31" src="https://user-images.githubusercontent.com/226720/83973903-ca1d8500-a8e9-11ea-9aac-5a314d4030f5.png">

For the `!rm -i something.txt`, the kernel does not send any stdin message.

<img width="522" alt="Screenshot 2020-06-07 at 18 05 48" src="https://user-images.githubusercontent.com/226720/83973912-d73a7400-a8e9-11ea-8ea6-cce5a659aa20.png">

I would say the issue is more on the magic kernel which should tell his clients via the stdin channel that a prompt has to be opened.

**Comment by rezaeir** [comment] 2020-06-07 16:32
I'm not sure if this is what actually happens but I think The colab kernel is parsing the output and constantly looks for a prompt or input request. However, jlab just looks for input when there is an explicit call for input. I have two ideas to add this functionality:  
- It could be a feature to constantly parse and search for input request like colab which I think it would make the notebook slower to run which isn't a good result!!
- Or it could be a new magic command to be explicitly added to the cell that the user expects prompt from the code in that cell but not explicit prompt like `input`. This method would be much faster because it would just affect the running speed of the cell containing that implicit prompt requesting command

**Comment by echarles** [comment] 2020-06-08 04:00
> a new magic command to be explicitly added to the cell, which its code produces input request without having explicit input command in the code

We could open an feature request on ipython kernel for this so it will get into the [built-in magic commands](https://ipython.readthedocs.io/en/stable/interactive/magics.html).

**Comment by rezaeir** [comment] 2020-06-10 04:09
> > a new magic command to be explicitly added to the cell, which its code produces input request without having explicit input command in the code
> 
> We could open an feature request on ipython kernel for this so it will get into the [built-in magic commands](https://ipython.readthedocs.io/en/stable/interactive/magics.html).

@echarles Did you open the feature request or should I do it?

**Comment by echarles** [comment] 2020-06-10 05:25
@rezaeir Please open an issue on https://github.com/ipython/ipykernel for this.

**Comment by jasongrout** [comment] 2020-06-10 06:11
Thanks. Closing in deference to the issue opened in ipykernel.

**Closed by jasongrout** 2020-06-10 06:11 UTC
Labels: type:Enhancement
