### ISSUE TITLE
Toolbar Buttons are not visible

### ISSUE THREAD

**Issue by andyhegedus** [jupyterlab/jupyterlab#7959] opened 2020-03-01 21:47 UTC
## Toolbar Icons are not visible Safari
Similar to 3331 which was previously closed
The buttons still work.  If I wait for the tool tip to show up I can identify the button.

<img width="354" alt="missing toolbar buttons" src="https://user-images.githubusercontent.com/44418310/75634392-5cfba480-5bc2-11ea-836f-adb63c836196.png">

Open notebook or create a new one.

## Expected behavior

Previously open notebook (yesterday) displayed correctly.
Tried restarting system - no effect.
## Context

- Operating System and version:
- Browser and version: Safari 13.0.5
- JupyterLab version: 1.2.6

**Comment by telamonian** [comment] 2020-03-02 03:56
Well, that's not right. Jupyterlab won't just change on it's own, though. Did you do anything to trigger a Jupyterlab build recently, such as installing a new extension?

When problems like this occur, it's almost always due to a mismatch between package versions in your jupyterlab build. If I had to guess, you installed an extension that somehow pulled `@jupyterlab/apputils@2.0.0` into your jupyterlab 1.x build.

**Comment by andyhegedus** [comment] 2020-03-02 14:19
Hi,

I have NOT installed any extensions.  I have just switched over from Notebooks and had only used it for a day or two.  In that time I had started and used JupyterLab without issue about 10 times.  It then started up with the missing toolbar buttons.  What is odd is when I work with it as such on occasion the buttons with reappear for a while and then disappear again. I have not seen a pattern when they disappear or reappear yet.

The code I am working with include these libraries none out of the ordinary.
import sqlite3
import pandas as pd
import numpy as np
import datetime
import warnings
warnings.filterwarnings('ignore’)

import spacy
nlp=spacy.load('en_core_web_md')
from spacy import displacy
from pathlib import Path
from collections import Counter

import gensim
from gensim import corpora, models
import pyLDAvis.gensim

Regards,

Andy Hegedus

**Comment by anirrudh** [comment] 2020-03-02 15:38
Hey @andyhegedus, I just checked this issue on safari 13.0.5, and JupyterLab version 2.0.0. This error does not occur. Then, I went ahead and installed the version you had (1.2.6) -- and tested it again. I would either attempt a reinstall or upgrade to the latest version. Maybe it is a Safari bug?

**Comment by andyhegedus** [comment] 2020-03-02 16:28
Hi,

Updated to version 2.0.0
Restarted computer and clear caches in Safari. It seems to have gotten worse. Now all buttons are gone. Before I had buttons on the left hand side.

Regards,

Andy Hegedus

**Comment by jasongrout** [comment] 2020-03-02 16:33
Does it work in other browsers? Are there any errors in the server logs or browser JavaScript console? There are no browser or jupyterlab extensions installed? Is this a fresh installation in a clean new environment?

**Comment by andyhegedus** [comment] 2020-03-02 21:51
Java Script Log from Safari

[Log] Starting application in workspace: "/lab" (vendors~main.842eeaf450a183e1e755.js, line 2)
[Log] Starting WebSocket: ws://localhost:8888/api/kernels/25d1b9bc-7fa0-4c7a-8584-6f79754fba55 (vendors~main.842eeaf450a183e1e755.js, line 2)
[Log] lambda_select – "#ldavis_el661854853336242060520235-lambda" (ldavis.v1.0.0.js, line 155)
[Log] Starting WebSocket: ws://localhost:8888/api/kernels/25d1b9bc-7fa0-4c7a-8584-6f79754fba55 (vendors~main.842eeaf450a183e1e755.js, line 2)
[Error] Error: Kernel connection is disposed
_errorIfDisposed — vendors~main.842eeaf450a183e1e755.js:2:2428844
_assertCurrentMessage — vendors~main.842eeaf450a183e1e755.js:2:2425872
(anonymous function) — vendors~main.842eeaf450a183e1e755.js:2:2427654
asyncFunctionResume
[native code]
promiseReactionJob

	(anonymous function) (vendors~main.842eeaf450a183e1e755.js:2:2416997)
	promiseReactionJob

The problem also exists in Chrome



Javascript log from Chrome
Starting application in workspace: "/lab"
vendors~main.842eeaf450a183e1e755.js:2 Starting WebSocket: ws://localhost:8888/api/kernels/25d1b9bc-7fa0-4c7a-8584-6f79754fba55
ldavis.v1.0.0.js:155 lambda_select #ldavis_el661854853336242060520235-lambda
vendors~main.842eeaf450a183e1e755.js:2 Starting WebSocket: ws://localhost:8888/api/kernels/25d1b9bc-7fa0-4c7a-8584-6f79754fba55

Regards,

Andy Hegedus

**Comment by andyhegedus** [comment] 2020-03-03 02:02
Hi,
Some new info.  The buttons show are gone, then reappear for a bit and then disappear again.

When I start up via Anaconda Navigator.  The buttons are not visible, thought still work and the tool tips show up.


	The Javaconsole output here:
[Log] Starting application in workspace: "/lab" (vendors~main.842eeaf450a183e1e755.js, line 2)
[Log] Starting WebSocket: ws://localhost:8888/api/kernels/25d1b9bc-7fa0-4c7a-8584-6f79754fba55 <ws://localhost:8888/api/kernels/25d1b9bc-7fa0-4c7a-8584-6f79754fba55> (vendors~main.842eeaf450a183e1e755.js, line 2)
[Log] lambda_select – "#ldavis_el661854853336242060520235-lambda" (ldavis.v1.0.0.js, line 155)
[Log] Starting WebSocket: ws://localhost:8888/api/kernels/25d1b9bc-7fa0-4c7a-8584-6f79754fba55 <ws://localhost:8888/api/kernels/25d1b9bc-7fa0-4c7a-8584-6f79754fba55> (vendors~main.842eeaf450a183e1e755.js, line 2)
[Error] Error: Kernel connection is disposed
_errorIfDisposed — vendors~main.842eeaf450a183e1e755.js:2:2428844
_assertCurrentMessage — vendors~main.842eeaf450a183e1e755.js:2:2425872
(anonymous function) — vendors~main.842eeaf450a183e1e755.js:2:2427654
asyncFunctionResume
[native code]
promiseReactionJob

	(anonymous function) (vendors~main.842eeaf450a183e1e755.js:2:2416997)
	promiseReactionJob


As I run the following script in cells the buttons remain invisible

import sqlite3
import pandas as pd
import numpy as np
import datetime
import warnings
warnings.filterwarnings('ignore')

portfolio =pd.read_csv('/Users/andreashegedus/Desktop/Subset of alta_out.csv', sep='\t')


print(datetime.datetime.now())
cpc= sqlite3.connect('/Volumes/Patents/sqlitetest/brf_sum_text.db')
cpc.row_factory = lambda cursor, row: row[0]
cpc_cursor = cpc.cursor()
cpc_code=list()
for row in portfolio.itertuples(index=False):
    patent = str(row[0])
    cpc_cursor.execute('Select text FROM brf_sum_text Where patent_id=%s'% (patent))
    cpc_list = cpc_cursor.fetchall()
    cpc_code.append(cpc_list)
cpc.close()
print(datetime.datetime.now())

import spacy
nlp=spacy.load('en_core_web_md')
from spacy import displacy
from pathlib import Path
from collections import Counter

import gensim
from gensim import corpora, models

print(datetime.datetime.now())
nlist=list()
exclude = ('-PRON-','embodiment','invention')
for case in cpc_code:
    if len(case)>0:
        claimSlice =nlp(case[0])
        clist=list()
        for chunk in claimSlice.noun_chunks:
            for token in chunk:
                if not token.is_stop and len(token.lemma_)>3 and token.lemma_ not in exclude:
                    clist.append(token.lemma_)
        nlist.append(clist)
    
print(datetime.datetime.now())

dictionary = corpora.Dictionary(nlist)
corpus = [dictionary.doc2bow(text) for text in nlist]

print(datetime.datetime.now())
ldamodel = gensim.models.ldamodel.LdaModel(corpus, num_topics=10, id2word = dictionary, passes=20)
print(datetime.datetime.now())

top_words_per_topic = []
for t in range(ldamodel.num_topics):
    top_words_per_topic.extend([(t, ) + x for x in ldamodel.show_topic(t, topn = 10)])

pd.DataFrame(top_words_per_topic, columns=['Topic', 'Word', 'P']).to_csv("/Users/andreashegedus/Desktop/Alta_brf_sum_text.csv")

Here is when it changes.  When this group runs the buttons reappear.  This group takes about 1 min to run on my computer

import pyLDAvis.gensim
pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim.prepare(ldamodel, corpus, dictionary=ldamodel.id2word)
vis


Nothing in the Javaconsole


After it completes. The buttons disappear again.


Javaconsole
[Log] lambda_select – "#ldavis_el1127456987517289674929457-lambda" (ldavis.v1.0.0.js, line 155)

Regards,

Andy Hegedus

**Comment by anirrudh** [comment] 2020-03-03 22:25
Hey @andyhegedus, you are starting the lab instance using Anaconda Navigator only, correct? What I mean to say is, you aren't using the terminal command to start an instance of the lab, right?

**Comment by andyhegedus** [comment] 2020-03-03 22:29
Correct.


And also to be a bit more clear in my last post since the formatting got worked out.

I was running some code mostly doing some simple NLP with Spacy and Gensim.

When I ran this block of code.  The buttons REAPPEARED  while it was processing and then disappeared once complete.  for my data this took about 1 min so I had a chance to see the buttons show up again.

import pyLDAvis.gensim
pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim.prepare(ldamodel, corpus, dictionary=ldamodel.id2word)
vis

I was able to reproduce that effect.

Regards,

Andy Hegedus

**Comment by andyhegedus** [comment] 2020-03-03 22:43
Hi,

Did a quick text launching from terminal.

Same issue.  Buttons do not show up.

Regards,

Andy Hegedus
Founder
AGH Analytics, LLC

An Engineering Services Firm

Learn Fast

1561 Ralston Ave
Burlingame, CA 94010

andy.hegedus@aghanalytics.com
M 650.619.1365

**Comment by anirrudh** [comment] 2020-03-03 22:48
Just debugging wise, can you also try creating a new conda environment, installing jupyterlab, and then starting it from the env? I'm just not able to reproduce it on my end :(. macOS 10.5.3 is the version you are running, correct?

**Comment by andyhegedus** [comment] 2020-03-03 22:49
Mac 10.14.6 (Mojave)

Regards,

Andy Hegedus

**Comment by andyhegedus** [comment] 2020-03-03 23:01
Created another environment within Anaconda Navigator. Loaded JupyterLab application version 1.2.6 which is the Anaconda package version.  It will not launch.

From within Anaconda Navigator but from my base environment I can launch JupyterLab version 2.0.
Regards,

Andy Hegedus

**Comment by andyhegedus** [comment] 2020-03-04 00:05
I was able to create test environment within Anaconda Navigator.  Installed JupyterLab version 1.2.6 which is their distro.
Launched same issue.

Regards,

Andy Hegedus
Founder
AGH Analytics, LLC

An Engineering Services Firm

Learn Fast

1561 Ralston Ave
Burlingame, CA 94010

andy.hegedus@aghanalytics.com
M 650.619.1365

**Comment by jasongrout** [comment] 2020-03-04 00:34
The common thing in all of these cases seems to be using Anaconda Navigator (and presumably using the Anaconda packages, which we don't have control over). Can you try reproducing this using the command line tools in a clean environment using the official Jupyter packages?

```
conda create -n testenv jupyterlab=1.2.6 -c conda-forge
conda activate testenv
jupyter lab
```
Alternatively, have you tried asking Anaconda?

**Comment by andyhegedus** [comment] 2020-03-04 00:39
Hi,

Just ran test creating environment from terminal per your instructions.

Same result: Buttons are invisible, though they still work.

Regards,

Andy Hegedus
Founder
AGH Analytics, LLC

An Engineering Services Firm

Learn Fast

1561 Ralston Ave
Burlingame, CA 94010

andy.hegedus@aghanalytics.com
M 650.619.1365

**Comment by jasongrout** [comment] 2020-03-04 00:46
And for that environment, what is `conda list --explicit`?

**Comment by andyhegedus** [comment] 2020-03-04 00:49
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
@EXPLICIT
https://conda.anaconda.org/conda-forge/osx-64/ca-certificates-2019.11.28-hecc5488_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libcxx-9.0.1-1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libsodium-1.0.17-h01d97ff_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pandoc-2.9.2-0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/xz-5.2.4-h1de35cc_1001.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/zlib-1.2.11-h0b31af3_1006.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libffi-3.2.1-h6de7cb9_1006.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/ncurses-6.1-h0a44026_1002.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/openssl-1.1.1d-h0b31af3_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/tk-8.6.10-hbbe82c9_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/zeromq-4.3.2-h6de7cb9_2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/readline-8.0-hcfe32e1_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/sqlite-3.30.1-h93121df_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/python-3.8.2-hdc38147_1_cpython.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/appnope-0.1.0-py38_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/attrs-19.3.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/backcall-0.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/certifi-2019.11.28-py38_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/decorator-4.4.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/defusedxml-0.6.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/entrypoints-0.3-py38_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/ipython_genutils-0.2.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/json5-0.9.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/markupsafe-1.1.1-py38h0b31af3_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/mistune-0.8.4-py38h0b31af3_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pandocfilters-1.4.2-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/parso-0.6.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pickleshare-0.7.5-py38_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/prometheus_client-0.7.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/ptyprocess-0.6.0-py_1001.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pyzmq-19.0.0-py38h4bf09a9_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/send2trash-1.5.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/six-1.14.0-py38_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/testpath-0.4.4-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/tornado-6.0.3-py38h0b31af3_4.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/wcwidth-0.1.8-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/webencodings-0.5.1-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/zipp-3.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/importlib_metadata-1.5.0-py38_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/jedi-0.16.0-py38_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pexpect-4.8.0-py38_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pyrsistent-0.15.7-py38h0b31af3_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/python-dateutil-2.8.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/setuptools-45.2.0-py38_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/terminado-0.8.3-py38_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/traitlets-4.3.3-py38_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/bleach-3.1.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jinja2-2.11.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/jsonschema-3.2.0-py38_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/jupyter_core-4.6.3-py38_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pygments-2.5.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/wheel-0.34.2-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jupyter_client-6.0.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/nbformat-5.0.4-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pip-20.0.2-py_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/prompt_toolkit-3.0.3-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/ipython-7.13.0-py38h5ca1d4c_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/nbconvert-5.6.1-py38_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/ipykernel-5.1.4-py38h5ca1d4c_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/notebook-6.0.3-py38_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jupyterlab_server-1.0.7-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jupyterlab-1.2.6-py_0.tar.bz2
Regards,

Andy Hegedus

**Comment by jasongrout** [comment] 2020-03-04 01:04
Okay, I have exactly the same environment. Icons in a new Jupyter notebook show up just fine for me in Safari 12.1.2 and Firefox 73. 

In Safari, I right-click on the save button in the notebook toolbar (the first button), and click "inspect element", and get something that looks like this:

<img width="686" alt="Screen Shot 2020-03-03 at 5 03 06 PM" src="https://user-images.githubusercontent.com/192614/75834505-054f6b80-5d71-11ea-8e55-7e63a76a0976.png">

Do you see that svg source too?

**Comment by andyhegedus** [comment] 2020-03-04 01:11
Here is what I get.

Also Interesting note:  When I start up the icons above the notebook list are visible UNTIL the the list is return and then they become invisible.  So they are there for a time.


Regards,

Andy Hegedus

**Comment by jasongrout** [comment] 2020-03-04 01:26
Did you mean to attach a picture?

**Comment by andyhegedus** [comment] 2020-03-04 01:52
Email does keep pictures.

<img width="1233" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/44418310/75836770-c1ac3000-5d77-11ea-9a16-caa4c7e99fe9.png">

**Comment by jasongrout** [comment] 2020-03-04 02:05
And that was inspecting an icon that was not showing?

**Comment by andyhegedus** [comment] 2020-03-04 02:20
Correct Icon was not showing.

Regards,

Andy Hegedus
Founder
AGH Analytics, LLC

An Engineering Services Firm

Learn Fast

1561 Ralston Ave
Burlingame, CA 94010

andy.hegedus@aghanalytics.com
M 650.619.1365

**Comment by andyhegedus** [comment] 2020-03-04 02:25
With toolbar in image.  Notice the toolbar where the save icon would be has a box visible.

<img width="957" alt="Invisible button,png" src="https://user-images.githubusercontent.com/44418310/75838904-2073a880-5d7c-11ea-96de-fa2d060153e6.png">
Andy Hegedus

**Comment by silvioalvim** [comment] 2020-03-04 19:22
Same problem here. Jupyterlab started on the terminal, but in both browsers it shows a buttonless interface. The menu seems incomplete, there is no way to work. Installed today, using pip3, I do not use Anaconda, I was planning to start learning but I have already encountered this problem, so far without a solution. I tested on Safari and Chrome, emptied caches and it still didn't work.
Mac 10.13.6 (High Sierra)
Jupyterlab 2.0.0
Jupyterlab-server 1.0.7
Python 3.7.6

**Comment by jasongrout** [comment] 2020-03-04 19:37
I'm sorry to hear you are also having a similar issue. Maybe with two people seeing this, we can narrow down what the issue might be.

@andyhegedus - in your screenshot, I notice some differences in my icon vs yours. For example, yours has height/width 24, whereas mine is 18. Also, mine has an extra initial `<path>` element in the SVG. So it seems that we are actually not running the same JupyterLab.

**Comment by jasongrout** [comment] 2020-03-04 19:41
@andyhegedus - When I run JupyterLab 2.0, I get what looks like the same svg as what you posted in your screenshot. Was your screenshot actually JupyterLab 2.0? I thought it was from the jlab 1.2.6 environments we were comparing.

**Comment by jasongrout** [comment] 2020-03-04 19:42
CC also @telamonian, who has worked a lot more on icons than I have.

**Comment by andyhegedus** [comment] 2020-03-04 19:43
Mine issues are with version 2.0.0

Regards,

Andy Hegedus

**Comment by jasongrout** [comment] 2020-03-04 19:45
Also, @andyhegedus - can you screenshot with only opening a single new blank notebook? I don't know if there is additional css in the notebooks you are opening that may affect things.

> Mine issues are with version 2.0.0

In the original issue and when we were comparing environments, jlab 1.2.6 was the relevant version. Does JupyterLab 1.2.6 work for you?

If we are talking about jlab 2.0, can you give the `conda list --explicit` for that environment?

**Comment by silvioalvim** [comment] 2020-03-04 19:54
Nobody asked, but here's the screenshot of my Jupyterlab when it opens in Safari. I hope it helps us find some solution
![Captura de Tela 2020-03-04 às 16 48 18](https://user-images.githubusercontent.com/9044286/75917416-bbca5380-5e38-11ea-8955-da7a2cceef56.png)

**Comment by telamonian** [comment] 2020-03-04 20:18
> @andyhegedus - in your screenshot, I notice some differences in my icon vs yours. For example, yours has height/width 24, whereas mine is 18. Also, mine has an extra initial `<path>` element in the SVG

@jasongrout As far as I can tell, andy's save.svg is the one from the 2.0.0 release, whereas yours is the one from 2.0.0-rc1 or -rc2. Jason, are you sure you're running the 2.0.0 release? The icon name in your `data-icon` field also isn't namespaced (yours is "save" instead of "ui-components:save"), which also suggests that your `@jupyterlab/ui-components` is from one of the earlier RCs

**Comment by jasongrout** [comment] 2020-03-04 20:22
My screenshot is from jlab 1.2.6, which is the version I thought we were discussing at the time.

**Comment by jasongrout** [comment] 2020-03-04 20:23
@silvioalvim - does your browser javascript console show any errors? It looks like you have a different issue where no css is getting loaded.

**Comment by telamonian** [comment] 2020-03-04 20:29
@andyhegedus @silvioalvim If I was in your shoes, the first thing I would try is to nuke and rebuild your lab app dir, then immediately launch a new instance of Jupyterlab:

```
# WARNING: this will delete all of your installed extensions
jupyter lab clean --all
jupyter lab build
jupyter lab
```

This should fix any version conflicts between your `@jupyterlab` packages. If the problem still persists after the above, that will help us narrow down the issue considerably, since no external extensions will be present.

This has fixed a number of similar issues in the past. The downside is that all of your installed extensions will be deleted, so you'll have to manually reinstall them.

**Comment by telamonian** [comment] 2020-03-04 20:41
@andyhegedus I'm sorry that you're having trouble. Your problem is particularly odd, since the HTML for the toolbar icon that you should be seeing is present and well-formed. The only thing I can think of is that there's a problem the icon's CSS styling.

**Comment by silvioalvim** [comment] 2020-03-04 21:09
When I try to build (jupyter lab build), I got errors. Logged below. In my case, I can try a fresh install again, from scratch. 
--------
[LabBuildApp] Building in /usr/local/share/jupyter/lab
[LabBuildApp] Node v8.11.4

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node /usr/local/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error marked@0.8.0: The engine "node" is incompatible with this module. Expected version ">= 8.16.2". Got "8.11.4"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

[LabBuildApp] npm dependencies failed to install
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/usr/local/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/usr/local/lib/python3.7/site-packages/jupyterlab/labapp.py", line 138, in start
    raise e

[LabBuildApp]   File "/usr/local/lib/python3.7/site-packages/jupyterlab/labapp.py", line 135, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 460, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 652, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: npm dependencies failed to install

[LabBuildApp] Exiting application: JupyterLab

**Comment by andyhegedus** [comment] 2020-03-04 21:10
Hi,
Confirming I am using 2.0.0.
First I think this is an interesting effect.  In general I do not see the button icons.
HOWEVER! When I run a particular piece of code relative to genesis and LDA the icons reappear while the code is being processed. Notice the asterisk indicating the running cell.
<img width="883" alt="while running" src="https://user-images.githubusercontent.com/44418310/75923027-19e73e80-5e19-11ea-8ff9-29acf2f891a6.png">

Once the cell has finished running the icons disappear again.
<img width="876" alt="gone" src="https://user-images.githubusercontent.com/44418310/75923145-574bcc00-5e19-11ea-9f94-1b1894ba6a39.png">

This particular cell and code is the only one thus far that I have seen this effect.

The other pieces you requested:
<img width="1392" alt="svg styles" src="https://user-images.githubusercontent.com/44418310/75923220-7c403f00-5e19-11ea-9e65-4184a18e7af4.png">

<img width="1392" alt="svg computed" src="https://user-images.githubusercontent.com/44418310/75923231-82362000-5e19-11ea-83c5-0f9707b92eb4.png">

<img width="338" alt="span styles" src="https://user-images.githubusercontent.com/44418310/75923243-882c0100-5e19-11ea-8551-ed6edb947990.png">

<img width="335" alt="span computed" src="https://user-images.githubusercontent.com/44418310/75923257-8e21e200-5e19-11ea-8e97-4939d99e9461.png">

Andy

**Comment by andyhegedus** [comment] 2020-03-04 21:22
OK,

Now I am hosed!
Per your instruction

jupyter lab clean --all
jupyter lab build
jupyter lab

I got an error on the jupyter lab build.
[LabBuildApp] JupyterLab 2.0.0
[LabBuildApp] Building in /Users/andreashegedus/anaconda3/share/jupyter/lab
Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

I am now dead in the water!

**Comment by silvioalvim** [comment] 2020-03-04 21:25
I got same error on the jupyter lab build!!! The log file says error on "node" version
(The engine "node" is incompatible with this module. Expected version ">= 8.16.2". Got "8.11.4"
error Found incompatible module.)
and finally ends with the message ([LabBuildApp] RuntimeError: npm dependencies failed to install)

**Comment by andyhegedus** [comment] 2020-03-04 21:32
What I just did is use Anaconda Navigator to uninstall Jupyter Lab.
Close Navigator
and then reinstall via
conda install -c conda-forge jupyterlab

Start via terminal with jupyter lab.

I get back but button icons are still gone.
I can also start via Anaconda Navigator.  Side Note Anaconda Navigator shows version 2.0.0 and has icon showing an update is available.  If you update it actually takes you to version 1.2.6.
I have not updated and can confirm version 2.0.0 is running.
Andy

**Comment by telamonian** [comment] 2020-03-04 21:49
@silvioalvim As the error message says, your version of node is too old. Can you upgrade to the latest version of node 8, or better yet node 12 or 13 (I'm currently using 13.8.0)? If you can't, you can at least get back to you initial jupyterlab install as so:

```
pip uninstall jupyterlab
pip install jupyterlab
```

Also, it seems like your issue is completely different from that of @andyhegedus. It would be very helpful if you could start a new issue with information more specific to your particular problem.

**Comment by jasongrout** [comment] 2020-03-04 21:51
You should have node 12 or later for JupyterLab 2.0.

**Comment by telamonian** [comment] 2020-03-04 22:28
@andyhegedus Whelp, the good news is that I figured out how to reproduce the error that you're seeing:

- I ran one of the test notebooks from the pyLDAvis project: https://github.com/bmabey/pyLDAvis/blob/master/notebooks/Movie%20Reviews%2C%20AP%20News%2C%20and%20Jeopardy.ipynb

- As soon as I ran the visualization step (the third code cell), all of the icons in jlab broke:

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/2263641/75928875-588ef000-5e3d-11ea-99a8-9d89d4f90284.png">

So the short answer to your problem is that the jupyterlab integration in pyLDAvis is hilariously, uniquely broken. I'll see if I can get to the bottom of it

**Comment by andyhegedus** [comment] 2020-03-04 22:31
Well,

I would say that proves that I am not crazy, except it doesn’t really prove that.

Question if you run it again do they should up while it is running that cell like my case?

Regards,

Andy Hegedus

**Comment by telamonian** [comment] 2020-03-04 22:32
"inspect element" offers no easy answers, but it does seem that as soon as I delete the cell containing the visualization all of the icons magically reappear...

@andyhegedus Can you please try deleting any related visualization cells and see what happens?

**Comment by jasongrout** [comment] 2020-03-04 22:33
This does look rather suspicious: https://github.com/bmabey/pyLDAvis/blob/a108b0c6458012e17d0d0f8a5b09015e17201982/pyLDAvis/js/ldavis.css#L5-L8

**Comment by andyhegedus** [comment] 2020-03-04 22:35
I can confirm that if I cut cell with visualization the icons reappear.  and when I revert the notebook to last check point they are gone again.

Regards,

Andy Hegedus

**Comment by jasongrout** [comment] 2020-03-04 22:35
It looks to me like pyLDAvis is very specifically coded for the classic notebook (i.e., it includes javascript and css that is very specific to the classic notebook frontend). It doesn't claim to support JupyterLab. Perhaps an issue can be opened there about supporting JupyterLab?

**Comment by telamonian** [comment] 2020-03-04 22:38
> This does look rather suspicious: https://github.com/bmabey/pyLDAvis/blob/a108b0c6458012e17d0d0f8a5b09015e17201982/pyLDAvis/js/ldavis.css#L5-L8

Yep, that's exactly what it is. I just traced it back then saw your comment. Apparently, that stylesheet gets loaded so long as any pyLDAvis visualizations are present, and the offending lines:

```
path {
  fill: none;
  stroke: none;
}
```

render all of the `<path>` elements inside of svgs invisible

**Comment by andyhegedus** [comment] 2020-03-04 22:40
also on the issues for pyLDAvis
https://github.com/bmabey/pyLDAvis/issues/121 <https://github.com/bmabey/pyLDAvis/issues/121>
There is another example showing the buttons are missing.

Regards,

Andy Hegedus

**Comment by andyhegedus** [comment] 2020-03-04 22:47
I raised an issue on pyLDAvis.
Andy

**Comment by jasongrout** [comment] 2020-03-04 22:48
> [bmabey/pyLDAvis#121](https://github.com/bmabey/pyLDAvis/issues/121) <[bmabey/pyLDAvis#121](https://github.com/bmabey/pyLDAvis/issues/121)>

Good find! Apparently I've investigated this before, which I totally forgot: https://github.com/bmabey/pyLDAvis/issues/121#issuecomment-387215639

**Comment by jasongrout** [comment] 2020-03-04 22:49
> I raised an issue on pyLDAvis.

Thanks. Closing this as resolved from our perspective then, and further conversation sounds like it should happen over there: https://github.com/bmabey/pyLDAvis/issues/162

**Closed by jasongrout** 2020-03-04 22:49 UTC
