### ISSUE TITLE
Today I upgrade jupyter and jupyterlab, and I can't use "show in file browser"

### ISSUE THREAD

**Issue by Ethan-Chen-plus** [jupyterlab/jupyterlab#14889] opened 2023-08-01 10:10 UTC
as title.
![image](https://github.com/jupyterlab/jupyterlab/assets/84905965/5dddc08f-6059-49cb-bb14-59dbc56cbde6)
version:
![image](https://github.com/jupyterlab/jupyterlab/assets/84905965/8c745758-bc56-40dc-8eab-47e67f35b89a)

**Comment by krassowski** [comment] 2023-08-01 15:40
Closing as a duplicate of a duplicate https://github.com/jupyterlab/jupyterlab/issues/14879 https://github.com/jupyterlab/jupyterlab/issues/14850

**Closed by krassowski** 2023-08-01 15:40 UTC
Labels: bug, status:Duplicate, status:Needs Triage
