### ISSUE TITLE
Can't install extensions not uploaded to npm

### ISSUE THREAD

**Issue by akarukappadath** [jupyterlab/jupyterlab#5852] opened 2019-01-10 21:56 UTC
I'm having trouble installing JupyterLab extensions that are not uploaded to npm. According to the docs, I should be able to install using "a local directory containing the extension, a gzipped tarball, or a URL to a gzipped tarball" with `jupyter labextension install my-extension`. I'm using the table of contents extension (https://github.com/jupyterlab/jupyterlab-toc) as an example here. 

If I try to install this extension using the package uploaded to npm, it looks like this: `jupyter labextension install @jupyterlab/toc`, which works perfectly. 

If I clone the github repo and specify the folder (`jupyter labextension install jupyterlab-toc-master`), it fails with this message: 
```
Node v8.11.4

> node /usr/local/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.9.4
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 0.04s.
> /usr/local/bin/npm pack /Users/akarukap/jupyterlab-toc-master
npm ERR! code ENOLOCAL
npm ERR! Could not install from "../../../../../../../Users/akarukap/jupyterlab-toc-master" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/akarukap/.npm/_logs/2019-01-10T21_46_29_965Z-debug.log

Errored, use --debug for full output:
ValueError: "/Users/akarukap/jupyterlab-toc-master" is not a valid npm package
```

If I compress the folder into a gzipped tarball, and try again (`jupyter labextension install toc.tar.gz`), I get the following error: 

```
Node v8.11.4

> /usr/local/bin/npm pack /Users/akarukap/toc.tar.gz
npm notice 
npm notice 📦  @jupyterlab/toc@0.6.0
npm notice === Tarball Contents === 
npm notice 212B   ./._jupyterlab-toc-master                                                       
npm notice 0      jupyterlab-toc-master/                                                          
npm notice 212B   jupyterlab-toc-master/._LICENSE                                                 
npm notice 1.5kB  jupyterlab-toc-master/LICENSE                                                   
npm notice 212B   jupyterlab-toc-master/._toc.gif                                                 
npm notice 3.6MB  jupyterlab-toc-master/toc.gif                                                   
npm notice 212B   jupyterlab-toc-master/._style                                                   
npm notice 0      jupyterlab-toc-master/style/                                                    
npm notice 212B   jupyterlab-toc-master/._.prettierignore                                         
npm notice 20B    jupyterlab-toc-master/.prettierignore                                           
npm notice 212B   jupyterlab-toc-master/._README.md                                               
npm notice 1.2kB  jupyterlab-toc-master/README.md                                                 
npm notice 212B   jupyterlab-toc-master/._yarn.lock                                               
npm notice 68.7kB jupyterlab-toc-master/yarn.lock                                                 
npm notice 212B   jupyterlab-toc-master/._.gitignore                                              
npm notice 79B    jupyterlab-toc-master/.gitignore                                                
npm notice 212B   jupyterlab-toc-master/._package.json                                            
npm notice 2.1kB  jupyterlab-toc-master/package.json                                              
npm notice 212B   jupyterlab-toc-master/._tslint.json                                             
npm notice 3.0kB  jupyterlab-toc-master/tslint.json                                               
npm notice 212B   jupyterlab-toc-master/._.prettierrc                                             
npm notice 25B    jupyterlab-toc-master/.prettierrc                                               
npm notice 212B   jupyterlab-toc-master/._tsconfig.json                                           
npm notice 389B   jupyterlab-toc-master/tsconfig.json                                             
npm notice 212B   jupyterlab-toc-master/._src                                                     
npm notice 0      jupyterlab-toc-master/src/                                                      
npm notice 212B   jupyterlab-toc-master/src/._extension.ts                                        
npm notice 3.4kB  jupyterlab-toc-master/src/extension.ts                                          
npm notice 212B   jupyterlab-toc-master/src/._toc.tsx                                             
npm notice 7.6kB  jupyterlab-toc-master/src/toc.tsx                                               
npm notice 212B   jupyterlab-toc-master/src/._registry.ts                                         
npm notice 3.2kB  jupyterlab-toc-master/src/registry.ts                                           
npm notice 212B   jupyterlab-toc-master/src/._index.ts                                            
npm notice 185B   jupyterlab-toc-master/src/index.ts                                              
npm notice 212B   jupyterlab-toc-master/src/._generators                                          
npm notice 0      jupyterlab-toc-master/src/generators/                                           
npm notice 212B   jupyterlab-toc-master/src/generators/._markdowndocgenerator                     
npm notice 0      jupyterlab-toc-master/src/generators/markdowndocgenerator/                      
npm notice 212B   jupyterlab-toc-master/src/generators/._shared.ts                                
npm notice 2.5kB  jupyterlab-toc-master/src/generators/shared.ts                                  
npm notice 212B   jupyterlab-toc-master/src/generators/._notebookgenerator                        
npm notice 0      jupyterlab-toc-master/src/generators/notebookgenerator/                         
npm notice 212B   jupyterlab-toc-master/src/generators/._latexgenerator.ts                        
npm notice 2.4kB  jupyterlab-toc-master/src/generators/latexgenerator.ts                          
npm notice 212B   jupyterlab-toc-master/src/generators/._index.ts                                 
npm notice 215B   jupyterlab-toc-master/src/generators/index.ts                                   
npm notice 212B   jupyterlab-toc-master/src/generators/notebookgenerator/._tagstool               
npm notice 0      jupyterlab-toc-master/src/generators/notebookgenerator/tagstool/                
npm notice 212B   jupyterlab-toc-master/src/generators/notebookgenerator/._codemirror.tsx         
npm notice 1.1kB  jupyterlab-toc-master/src/generators/notebookgenerator/codemirror.tsx           
npm notice 212B   jupyterlab-toc-master/src/generators/notebookgenerator/._itemrenderer.tsx       
npm notice 4.7kB  jupyterlab-toc-master/src/generators/notebookgenerator/itemrenderer.tsx         
npm notice 212B   jupyterlab-toc-master/src/generators/notebookgenerator/._heading.ts             
npm notice 398B   jupyterlab-toc-master/src/generators/notebookgenerator/heading.ts               
npm notice 212B   jupyterlab-toc-master/src/generators/notebookgenerator/._optionsmanager.ts      
npm notice 3.2kB  jupyterlab-toc-master/src/generators/notebookgenerator/optionsmanager.ts        
npm notice 212B   jupyterlab-toc-master/src/generators/notebookgenerator/._index.ts               
npm notice 19.7kB jupyterlab-toc-master/src/generators/notebookgenerator/index.ts                 
npm notice 212B   jupyterlab-toc-master/src/generators/notebookgenerator/._toolbargenerator.tsx   
npm notice 8.0kB  jupyterlab-toc-master/src/generators/notebookgenerator/toolbargenerator.tsx     
npm notice 212B   jupyterlab-toc-master/src/generators/notebookgenerator/tagstool/._index.tsx     
npm notice 4.4kB  jupyterlab-toc-master/src/generators/notebookgenerator/tagstool/index.tsx       
npm notice 212B   jupyterlab-toc-master/src/generators/notebookgenerator/tagstool/._tag.tsx       
npm notice 710B   jupyterlab-toc-master/src/generators/notebookgenerator/tagstool/tag.tsx         
npm notice 212B   jupyterlab-toc-master/src/generators/notebookgenerator/tagstool/._tagslist.tsx  
npm notice 2.3kB  jupyterlab-toc-master/src/generators/notebookgenerator/tagstool/tagslist.tsx    
npm notice 212B   jupyterlab-toc-master/src/generators/markdowndocgenerator/._itemrenderer.tsx    
npm notice 976B   jupyterlab-toc-master/src/generators/markdowndocgenerator/itemrenderer.tsx      
npm notice 212B   jupyterlab-toc-master/src/generators/markdowndocgenerator/._optionsmanager.ts   
npm notice 1.0kB  jupyterlab-toc-master/src/generators/markdowndocgenerator/optionsmanager.ts     
npm notice 212B   jupyterlab-toc-master/src/generators/markdowndocgenerator/._index.ts            
npm notice 7.7kB  jupyterlab-toc-master/src/generators/markdowndocgenerator/index.ts              
npm notice 212B   jupyterlab-toc-master/src/generators/markdowndocgenerator/._toolbargenerator.tsx
npm notice 1.9kB  jupyterlab-toc-master/src/generators/markdowndocgenerator/toolbargenerator.tsx  
npm notice 212B   jupyterlab-toc-master/style/._list-dark.svg                                     
npm notice 625B   jupyterlab-toc-master/style/list-dark.svg                                       
npm notice 212B   jupyterlab-toc-master/style/._index.css                                         
npm notice 9.2kB  jupyterlab-toc-master/style/index.css                                           
npm notice 212B   jupyterlab-toc-master/style/._list-light.svg                                    
npm notice 625B   jupyterlab-toc-master/style/list-light.svg                                      
npm notice 212B   jupyterlab-toc-master/style/._img                                               
npm notice 0      jupyterlab-toc-master/style/img/                                                
npm notice 212B   jupyterlab-toc-master/style/img/._menu_arrow.svg                                
npm notice 264B   jupyterlab-toc-master/style/img/menu_arrow.svg                                  
npm notice 212B   jupyterlab-toc-master/style/img/._toggle_down_darktheme.svg                     
npm notice 202B   jupyterlab-toc-master/style/img/toggle_down_darktheme.svg                       
npm notice 212B   jupyterlab-toc-master/style/img/._toggle_right_darktheme.svg                    
npm notice 189B   jupyterlab-toc-master/style/img/toggle_right_darktheme.svg                      
npm notice 212B   jupyterlab-toc-master/style/img/._tag.svg                                       
npm notice 1.2kB  jupyterlab-toc-master/style/img/tag.svg                                         
npm notice 212B   jupyterlab-toc-master/style/img/._toggle_right.svg                              
npm notice 187B   jupyterlab-toc-master/style/img/toggle_right.svg                                
npm notice 212B   jupyterlab-toc-master/style/img/._code_darktheme.svg                            
npm notice 320B   jupyterlab-toc-master/style/img/code_darktheme.svg                              
npm notice 212B   jupyterlab-toc-master/style/img/._markdown_darktheme.svg                        
npm notice 357B   jupyterlab-toc-master/style/img/markdown_darktheme.svg                          
npm notice 212B   jupyterlab-toc-master/style/img/._numbering.svg                                 
npm notice 523B   jupyterlab-toc-master/style/img/numbering.svg                                   
npm notice 212B   jupyterlab-toc-master/style/img/._eyeball_hidden.svg                            
npm notice 669B   jupyterlab-toc-master/style/img/eyeball_hidden.svg                              
npm notice 212B   jupyterlab-toc-master/style/img/._code.svg                                      
npm notice 305B   jupyterlab-toc-master/style/img/code.svg                                        
npm notice 212B   jupyterlab-toc-master/style/img/._markdown.svg                                  
npm notice 363B   jupyterlab-toc-master/style/img/markdown.svg                                    
npm notice 212B   jupyterlab-toc-master/style/img/._check.svg                                     
npm notice 264B   jupyterlab-toc-master/style/img/check.svg                                       
npm notice 212B   jupyterlab-toc-master/style/img/._toggle_down.svg                               
npm notice 181B   jupyterlab-toc-master/style/img/toggle_down.svg                                 
npm notice 212B   jupyterlab-toc-master/style/img/._autonumbering_darktheme.svg                   
npm notice 559B   jupyterlab-toc-master/style/img/autonumbering_darktheme.svg                     
npm notice 212B   jupyterlab-toc-master/style/img/._eyeball_hover.svg                             
npm notice 619B   jupyterlab-toc-master/style/img/eyeball_hover.svg                               
npm notice 212B   jupyterlab-toc-master/style/img/._tag_darktheme.svg                             
npm notice 762B   jupyterlab-toc-master/style/img/tag_darktheme.svg                               
npm notice 212B   jupyterlab-toc-master/style/img/._eyeball_view.svg                              
npm notice 617B   jupyterlab-toc-master/style/img/eyeball_view.svg                                
npm notice 212B   jupyterlab-toc-master/style/img/._autonumbering.svg                             
npm notice 343B   jupyterlab-toc-master/style/img/autonumbering.svg                               
npm notice === Tarball Details === 
npm notice name:          @jupyterlab/toc                         
npm notice version:       0.6.0                                   
npm notice filename:      jupyterlab-toc-0.6.0.tgz                
npm notice package size:  3.6 MB                                  
npm notice unpacked size: 3.8 MB                                  
npm notice shasum:        3853a8518ef2b0d349ed6545cc19140aa0598a1b
npm notice integrity:     sha512-3n6C4xQUnuilb[...]qzxOIN2zKFRbA==
npm notice total files:   118                                     
npm notice 
jupyterlab-toc-0.6.0.tgz

Errored, use --debug for full output:
KeyError: "filename 'package/package.json' not found"
```

I just need to be able to install a custom extension to Jupyterlab without having to upload it to npm first. Is there some workaround for this? Thank you!

**Comment by bollwyvl** [comment] 2019-01-11 02:00
In the future, it might be cool to be able to handle building things from
random archives, but right now... it has to be the tarball structured by
`npm pack`, and the built js assets won't be in there, as most
labextensions are written in typescript.

For that one, you'd probably do...

- Download the tarball
- Unpack the tarball
- CD to the directory where package.json lives

Then...

jlpm
# installs dependencies and build tools typescript
jlpm build
# builds the lib directory
jupyter labextension install .
# actually install and rebuild lab

hooray!

We should probably bite the bullet at some point and package a whole dev
environment suitable for extending lab locally with lab!

**Comment by telamonian** [comment] 2019-01-21 01:46
@bollwyvl I just tried your suggestion, but the build dies at the `jupyter labextension install .` step. 

I was trying to come up with an answer to [this question on SO](https://stackoverflow.com/q/54148668/425458) (it boils down to "How do I install a labextension when my internet at work is poorly configured?"), and here's how I tried to manually install the Plotly extension:

```
npm pack @jupyterlab/plotly-extension
tar xzvf <whatever>.tgz
cd package
jlpm
jlpm build
jupyter labextension install .
```

The `jupyter labextension install .` command fails pretty quickly:

```
ValueError: "/Users/tel/src/package" is not a valid extension:
Missing mimeExtension module "lib/index.js"
```

The `lib/index.js` is in the tarball, and it exists up until I run the `labextension install` command. It seems the problem is that `labextension install` ends up calling `npm run clean`, which calls `rimraf lib`, which I suppose is nuking the very file I'm trying to install. Is there any simple way to tell `labextension install` to skip the `clean` step?

**Comment by telamonian** [comment] 2019-01-21 03:21
Well, I "fixed" the problem. While in the `package` dir I opened up `node_modules/rimraf/bin.js` and commented out the lines that actually made `rimraf` do anything. The `jupyter labextension install .` command then worked correctly, so I was able to completely install a labextension from a tarball.

There's probably a better way then just breaking `rimraf`? But hey, at least I only had to mess up the package-local copy.

**Comment by vidartf** [comment] 2019-02-05 10:56
This seems like a bug to me. Could you post the log for installing from a local directory with the `--debug` flag given? The error message that it cannot find package.json seems weird.

**Comment by jtpio** [comment] 2019-08-29 09:48
On the topic of installing extensions not uploaded to npm, it would be useful to be able to install directly from GitHub (same as `npm install`). For example:

`jupyter labextension install git+https://git@github.com/jupyterlab/jupyterlab-git.git`

**Comment by jtpio** [comment] 2023-09-01 20:23
Closing as prebuilt extensions are now the recommended way for installing extensions with JupyterLab 3+, using `pip` or `conda` / `mamba`: https://jupyterlab.readthedocs.io/en/latest/user/extensions.html#installing-extensions

Moreover the table of contents mentioned in the top comment is now built into JupyterLab itself.

Feel free to open a new issue if you still have questions about installing extensions, thanks!

**Closed by jtpio** 2023-09-01 20:23 UTC
Labels: question, tag:Build System
