### ISSUE TITLE
Not properly display of the HTML in the output

### ISSUE THREAD

**Issue by aakhmetz** [jupyterlab/jupyterlab#16497] opened 2024-06-18 08:00 UTC
Hi all,

Previously, I was able to display the HTML page like this:
![image](https://github.com/jupyterlab/jupyterlab/assets/2173206/481596cb-62ec-46c4-860c-95e0d1086694)
But now, if I run the same command in my jupyterlab, it is not shown anymore:
![image](https://github.com/jupyterlab/jupyterlab/assets/2173206/de874517-827d-486b-890e-dc2dd11ff823)

Do you know what could be the reason?

Jupyterlab: 4.2.0

**Comment by krassowski** [comment] 2024-06-18 08:11
Can you provide the code sample to allow reproducing it?

What version of JupyterLab were you using previously?

**Comment by aakhmetz** [comment] 2024-06-18 09:16
Here it is: https://gist.github.com/aakhmetz/0ad85ff1cfe9c7b94a6606c0e6015843

Regarding the previous version, it is difficult to recall the number, but it was last December (2023)

**Comment by krassowski** [comment] 2024-06-18 09:22
Can you paste just the `conmat_html[0]` content please? It is hard to test the gist you linked as it requires R and rpy2

**Comment by aakhmetz** [comment] 2024-06-19 02:22
It's like this
```html
np.str_('<table class="table table-hover" style="width: auto !important; margin-left: auto; margin-right: auto;">\n <thead>\n  <tr>\n   <th style="text-align:left;">  </th>\n   <th style="text-align:left;"> [0,30) </th>\n   <th style="text-align:left;"> [30,50) </th>\n   <th style="text-align:left;"> [50,65) </th>\n   <th style="text-align:left;"> [65,75) </th>\n   <th style="text-align:left;"> 75+ </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style="text-align:left;"> [0,30) </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: red !important;" &gt;8.79&lt;/span&gt; </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: red !important;" &gt;3.72&lt;/span&gt; </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(182, 48, 139, 255) !important;" &gt;1.33&lt;/span&gt; </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(63, 4, 156, 255) !important;" &gt;0.29&lt;/span&gt; </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(49, 5, 151, 255) !important;" &gt;0.2&lt;/span&gt; </td>\n  </tr>\n  <tr>\n   <td style="text-align:left;"> [30,50) </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: red !important;" &gt;4.01&lt;/span&gt; </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: red !important;" &gt;6.25&lt;/span&gt; </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(243, 136, 74, 255) !important;" &gt;2.25&lt;/span&gt; </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(91, 1, 165, 255) !important;" &gt;0.51&lt;/span&gt; </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(55, 4, 153, 255) !important;" &gt;0.23&lt;/span&gt; </td>\n  </tr>\n  <tr>\n   <td style="text-align:left;"> [50,65) </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(245, 139, 71, 255) !important;" &gt;2.28&lt;/span&gt; </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: red !important;" &gt;3.9&lt;/span&gt; </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: red !important;" &gt;3.4&lt;/span&gt; </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(93, 1, 166, 255) !important;" &gt;0.53&lt;/span&gt; </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(74, 3, 161, 255) !important;" &gt;0.38&lt;/span&gt; </td>\n  </tr>\n  <tr>\n   <td style="text-align:left;"> [65,75) </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(210, 79, 113, 255) !important;" &gt;1.67&lt;/span&gt; </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(251, 159, 58, 255) !important;" &gt;2.46&lt;/span&gt; </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(248, 148, 65, 255) !important;" &gt;2.36&lt;/span&gt; </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(199, 67, 124, 255) !important;" &gt;1.53&lt;/span&gt; </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(123, 2, 168, 255) !important;" &gt;0.76&lt;/span&gt; </td>\n  </tr>\n  <tr>\n   <td style="text-align:left;"> 75+ </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(168, 34, 150, 255) !important;" &gt;1.18&lt;/span&gt; </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(202, 69, 122, 255) !important;" &gt;1.57&lt;/span&gt; </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(222, 95, 101, 255) !important;" &gt;1.85&lt;/span&gt; </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(161, 28, 155, 255) !important;" &gt;1.1&lt;/span&gt; </td>\n   <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(157, 24, 157, 255) !important;" &gt;1.06&lt;/span&gt; </td>\n  </tr>\n</tbody>\n</table>')
```

**Comment by krassowski** [comment] 2024-06-19 10:09
This does not look like a JupyterLab issue - the string which you shared already includes escaped HTML tags if you look at it carefully - I used a formatter to make it easier:

```html
<table class="table table-hover" style="width: auto !important; margin-left: auto; margin-right: auto;">
  <thead>
        <tr>
            <th style="text-align:left;">  </th>
            <th style="text-align:left;"> [0,30) </th>
            <th style="text-align:left;"> [30,50) </th>
            <th style="text-align:left;"> [50,65) </th>
            <th style="text-align:left;"> [65,75) </th>
            <th style="text-align:left;"> 75+ </th>
          </tr>
  </thead>
  <tbody>
        <tr>
            <td style="text-align:left;"> [0,30) </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: red !important;" &gt;8.79&lt;/span&gt; </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: red !important;" &gt;3.72&lt;/span&gt; </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(182, 48, 139, 255) !important;" &gt;1.33&lt;/span&gt; </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(63, 4, 156, 255) !important;" &gt;0.29&lt;/span&gt; </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(49, 5, 151, 255) !important;" &gt;0.2&lt;/span&gt; </td>
          </tr>
        <tr>
            <td style="text-align:left;"> [30,50) </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: red !important;" &gt;4.01&lt;/span&gt; </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: red !important;" &gt;6.25&lt;/span&gt; </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(243, 136, 74, 255) !important;" &gt;2.25&lt;/span&gt; </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(91, 1, 165, 255) !important;" &gt;0.51&lt;/span&gt; </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(55, 4, 153, 255) !important;" &gt;0.23&lt;/span&gt; </td>
          </tr>
        <tr>
            <td style="text-align:left;"> [50,65) </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(245, 139, 71, 255) !important;" &gt;2.28&lt;/span&gt; </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: red !important;" &gt;3.9&lt;/span&gt; </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: red !important;" &gt;3.4&lt;/span&gt; </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(93, 1, 166, 255) !important;" &gt;0.53&lt;/span&gt; </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(74, 3, 161, 255) !important;" &gt;0.38&lt;/span&gt; </td>
          </tr>
        <tr>
            <td style="text-align:left;"> [65,75) </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(210, 79, 113, 255) !important;" &gt;1.67&lt;/span&gt; </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(251, 159, 58, 255) !important;" &gt;2.46&lt;/span&gt; </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(248, 148, 65, 255) !important;" &gt;2.36&lt;/span&gt; </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(199, 67, 124, 255) !important;" &gt;1.53&lt;/span&gt; </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(123, 2, 168, 255) !important;" &gt;0.76&lt;/span&gt; </td>
          </tr>
        <tr>
            <td style="text-align:left;"> 75+ </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(168, 34, 150, 255) !important;" &gt;1.18&lt;/span&gt; </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(202, 69, 122, 255) !important;" &gt;1.57&lt;/span&gt; </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(222, 95, 101, 255) !important;" &gt;1.85&lt;/span&gt; </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(161, 28, 155, 255) !important;" &gt;1.1&lt;/span&gt; </td>
            <td style="text-align:left;"> &lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: rgba(157, 24, 157, 255) !important;" &gt;1.06&lt;/span&gt; </td>
          </tr>
    </tbody>
</table>
```

So `&lt;span style="     color: white !important;border-radius: 4px; padding-right: 4px; padding-left: 4px; background-color: red !important;" &gt;8.79&lt;/span&gt;` has `<` character escaped to `&lt;` and `>` escaped to `&gt;`.

From taking a look at the reproducer, assuming that your code has not changed since it worked, it might be a regression in `kableExtra` or `dplyr`.

**Comment by JasonWeill** [comment] 2024-06-25 16:08
@krassowski Thank you for this explanation! Because the HTML in question is already escaped, this doesn't appear to be a bug in JupyterLab. Closing this because there's nothing that we need to fix in JupyterLab. Thank you for your contribution.

**Closed by JasonWeill** 2024-06-25 16:08 UTC
Labels: bug, status:Needs Info, status:Needs Triage

**Comment by aakhmetz** [comment] 2024-06-25 16:24
@krassowski, thank you very much for investicating and finding the issue!

I am not sure what to do next, but I will try to figure out. Maybe it could be also an issue of rpy2

**Comment by aakhmetz** [comment] 2024-11-09 12:16
Yes, I simply did:
```python
display(HTML([x.replace("&lt;", "<").replace("&gt;", ">") for x in conmat_html][0]))
```

@krassowski, thanks for finding out the problem
