### ISSUE TITLE
3-7 cells in middle of notebook run but display no output (introduced in 3.1.6, not present in 3.1.4)

### ISSUE THREAD

**Issue by Doggie52** [jupyterlab/jupyterlab#10895] opened 2021-08-23 14:18 UTC
## Description

On and after `3.1.6`, some 3-7 cells usually in the middle of the notebook (typically after cell 10) do not show `[*]` when all cells are run and show no output. However, they are run, as one can access the variables created in them later.

## Reproduce

Be on version `3.1.6` or `3.1.7`.

1. Have a notebook ready with at least 20 code cells, and perhaps some markdown cells too (have not tested any notebooks without markdown)
2. Clear the notebook from all output using _Restart kernel and clear all outputs_
3. Close the notebook
4. Shut down the notebook's kernel
5. Open the notebook
6. Run _Restart kernel and run all cells_
7. Observe that cells ~10 to ~15 show up as having not been run

## Expected behavior

Expect all cells to be run properly. `3.1.4` works flawlessly.

## Context

- Operating System and version: OSX `11.5.1`
- Browser and version: Chrome `92.0.4515.159`
- JupyterLab version: `>= 3.1.6`

This has been observed across at least two separate machines. I don't know the exact versions of OSX and Chrome on the other machine.

**Comment by goanpeca** [comment] 2021-08-23 16:26
@echarles could this be related to the virtual notebook when interacting with the dirty state `[*]` indicator introducedt recently?

**Comment by krassowski** [comment] 2021-08-23 16:32
Thank you @Doggie52. Would you be able to share a shortest possible notebook with which the problem can be reproduced (replacing all code content with placeholders, and all markdown text with placeholder, but preserving the cell structure)? Would you be able to run any of the online CPU benchmarks and provide a result for comparison?

This looks very similar to the issue described in https://github.com/jupyterlab/jupyterlab/issues/10840#issuecomment-903130229. There are two missing bits to understand:
- a) why we cannot reproduce the problem without modifying settings (as described in the linked comment).
- b) why do users experience the problem only on 3.1.6+ if the reproducer from my comment works as well on 3.1.0.

Maybe this comes down to performance? Maybe myself and @echarles have too fast computers so the rendering completes before the restart all action, masking the problem? I do have a fast multi-core beast. Maybe there was no relevant regression in 3.1.6 but instead there was a performance regression exposing the problem to many more users?

**Comment by krassowski** [comment] 2021-08-23 16:34
@goanpeca, the dirty indicator was introduced in 3.1.0, but now multiple users say they saw a deterioration of the rendering issues in releases after 3.1.4 so I would say it is not the best candidate for an explanation. I think that `[*]` refers to the busy state in the report above.

**Comment by goanpeca** [comment] 2021-08-23 16:39
Got it!

**Comment by Doggie52** [comment] 2021-08-23 16:52
[reproduce.ipynb.zip](https://github.com/jupyterlab/jupyterlab/files/7033648/reproduce.ipynb.zip)

Here's as minimal of a working example as I can manage. If you open it in its current state, you can see the 2 cells that are empty.

I'm running a 15" 2019 Macbook with a 6-core Intel Core i7 @ 2.6 GHz.

**Comment by echarles** [comment] 2021-08-23 17:10
I have applied the following procedure on the given `reproduce.ipynb` and everything is working fine on my "Super Power" laptop (Powerfull MacBookPro bought 8 months ago). All cells are executed and outputs are shown.

```
Have a notebook ready with at least 20 code cells, and perhaps some markdown cells too (have not tested any notebooks without markdown)
Clear the notebook from all output using Restart kernel and clear all outputs
Close the notebook
Shut down the notebook's kernel
Open the notebook
Run Restart kernel and run all cells
Observe that cells ~10 to ~15 show up as having not been run
```

@Doggie52 Would you have time to record in an animated GIF what you do and see and upload it on this issue? This would be super helpful to try to understand.

2 more questions:
- Do you have a strong machine?
- Do you run on your local server, or via a network to something like an enterprise jupyterhub?

**Comment by krassowski** [comment] 2021-08-23 17:14
Thank you! I was able to reproduce the issue using `reproduce.ipynb` on the following binder: 3. ["Support collapsible headers with virtual notebook rendering"](https://mybinder.org/v2/gh/meeseeksmachine/jupyterlab/auto-backport-of-pr-10793-on-3.1.x?urlpath=lab-dev) and not on any earlier, narrowing down the issue to that commit.

```
widget.ts:737 Uncaught (in promise) TypeError: Cannot set property 'future' of undefined
    at Function.execute (/user/meeseeksmachine-jupyterlab-3fqcjwwj/lab-dev/static/lab/packages_outputarea_lib_index_js.2a62da7619ca4080b36c.js:956)
    at Function.execute (/user/meeseeksmachine-jupyterlab-3fqcjwwj/lab-dev/static/lab/packages_cells_lib_index_js.4a0073628ea36c934ee8.js:2330)
    at runCell (/user/meeseeksmachine-jupyterlab-3fqcjwwj/lab-dev/static/lab/packages_notebook_lib_index_js.ead0b3b917fb3513e959.js:1676)
    at /user/meeseeksmachine-jupyterlab-3fqcjwwj/lab-dev/static/lab/packages_notebook_lib_index_js.ead0b3b917fb3513e959.js:1616
    at Array.map (<anonymous>)
    at Object.runSelected (/user/meeseeksmachine-jupyterlab-3fqcjwwj/lab-dev/static/lab/packages_notebook_lib_index_js.ead0b3b917fb3513e959.js:1616)
    at Function.runAll (/user/meeseeksmachine-jupyterlab-3fqcjwwj/lab-dev/static/lab/packages_notebook_lib_index_js.ead0b3b917fb3513e959.js:546)
    at /user/meeseeksmachine-jupyterlab-3fqcjwwj/lab-dev/static/lab/packages_notebook_lib_index_js.ead0b3b917fb3513e959.js:2611
execute @ widget.ts:737
execute @ widget.ts:1093
runCell @ actions.tsx:1983
(anonymous) @ actions.tsx:1911
runSelected @ actions.tsx:1911
runAll @ actions.tsx:642
(anonymous) @ default-toolbar.tsx:201
Promise.then (async)
onClick @ default-toolbar.tsx:199
handleMouseDown @ toolbar.tsx:506
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
widget.ts:1131 Uncaught (in promise) TypeError: Cannot read property 'future' of undefined
    at Function.execute (/user/meeseeksmachine-jupyterlab-3fqcjwwj/lab-dev/static/lab/packages_cells_lib_index_js.4a0073628ea36c934ee8.js:2359)
    at runCell (/user/meeseeksmachine-jupyterlab-3fqcjwwj/lab-dev/static/lab/packages_notebook_lib_index_js.ead0b3b917fb3513e959.js:1676)
    at /user/meeseeksmachine-jupyterlab-3fqcjwwj/lab-dev/static/lab/packages_notebook_lib_index_js.ead0b3b917fb3513e959.js:1616
    at Array.map (<anonymous>)
    at Object.runSelected (/user/meeseeksmachine-jupyterlab-3fqcjwwj/lab-dev/static/lab/packages_notebook_lib_index_js.ead0b3b917fb3513e959.js:1616)
    at Function.runAll (/user/meeseeksmachine-jupyterlab-3fqcjwwj/lab-dev/static/lab/packages_notebook_lib_index_js.ead0b3b917fb3513e959.js:546)
    at /user/meeseeksmachine-jupyterlab-3fqcjwwj/lab-dev/static/lab/packages_notebook_lib_index_js.ead0b3b917fb3513e959.js:2611
```

@echarles I was able to reproduce it on my fairly powerful laptop, but the other thing you may want to change is the viewport (if using 4k screen resize the window to take much less space, no more than full HD) to prevent the intersection observer from kicking in.

**Comment by krassowski** [comment] 2021-08-23 17:42
@echarles could it be that https://github.com/jupyterlab/jupyterlab/pull/10793 leads to non-contiguous blocks of rendered and non-rendered cells, or more precisely the [`this._incrementRenderedCount()`](https://github.com/jupyterlab/jupyterlab/pull/10793/files#diff-5d4be2d463ce0219eead775eeb3bbc80160d57d64673559fc0e928640637ff6aR574) call in the `else` block which is now run for markdown cells that are sandwiched between code cells leads to `_renderedCellsCount` not matching up with the cells that actually need to be rendered thus not being a reliable `index` for the cell that needs rendering in:

https://github.com/jupyterlab/jupyterlab/blob/d48e0c04efb786561137fb20773fc15788507f0a/packages/notebook/src/widget.ts#L587-L597

Is there a sanity check ensuring that we do not attempt to render already rendered cells? If not, we need one to prevent issues like this in the future.

So in a sense, this is distinct from my reproduction in https://github.com/jupyterlab/jupyterlab/issues/10840#issuecomment-903130229 (the error is the same, but the underlying cause is slightly different; I was right to say that the bug like that is present since 3.1, but this code path was indeed only introduced in 3.1.6)

**Comment by echarles** [comment] 2021-08-23 18:07
I can indeed reproduce on binder. I see now an issue with the rendering of markdown cells to take into account the collapsible headers. I will hopefully come wit a PR tomorrow. We have now a reproducer which will help.

**Comment by Doggie52** [comment] 2021-08-23 21:31
Thank you @krassowski, @echarles and @goanpeca for the help, much appreciated. Looking forward to see what comes out of this :)

**Comment by krassowski** [comment] 2021-09-01 15:52
Hi @Doggie52, just letting you know that the fix was released in 3.1.10. Could you please see how it works for ou?

**Comment by krassowski** [comment] 2021-09-03 09:44
We got confirmation that JupyterLab 3.1.10 fixes the major issue in the other thread.
I will close this one to focus discussion on remaining edge cases in https://github.com/jupyterlab/jupyterlab/issues/10933 (please feel welcome to leave your feedback there).

**Closed by krassowski** 2021-09-03 09:44 UTC
Labels: bug

**Comment by Doggie52** [comment] 2021-09-13 13:19
Yes - works for me now. Thank you!
