### ISSUE TITLE
Kernel sources in debugger are uninformative and spams console

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#11966] opened 2022-01-31 17:00 UTC
## Description

1. `console.log` slipped through review during backport:

https://github.com/jupyterlab/jupyterlab/blob/f995e5d8be9a31b40fc08d8a210ec32bc849b0bf/packages/debugger/src/panels/kernelSources/body.ts#L56

2. it does not really work for me locally? All sources are labelled "id":

![Screenshot from 2022-01-31 16-49-06](https://user-images.githubusercontent.com/5832902/151837347-38144ced-868a-4568-ae5e-84937c697651.png)

## Reproduce

1. Open debugger, import some modules
2. Press refresh kernel sources
4. See all sources labelled as "id"

https://github.com/jupyterlab/jupyterlab/blob/f995e5d8be9a31b40fc08d8a210ec32bc849b0bf/packages/debugger/src/panels/kernelSources/body.ts#L56

## Expected behavior

- Sources are properly labelled.
- Any requirements for using this feature are in the user-facing documentation

## Context

- Browser and version: Chrome 97
- JupyterLab version: 3.3.0 alpha2+ ( f995e5d8be9a31b40fc08d8a210ec32bc849b0bf )
- ipykernel 6.7.0

**Comment by krassowski** [comment] 2022-01-31 17:15
Commented code to be removed:

https://github.com/jupyterlab/jupyterlab/blob/70fb169f2014131cdaba9cb65e1ed1e8570aa03e/packages/debugger/src/panels/kernelSources/filter.tsx#L19-L26

?

**Comment by echarles** [comment] 2022-01-31 17:19
Thx @krassowski I will open a PR to remove the unneeded source code.

Are you running with the latest https://github.com/ipython/ipykernel master?

**Comment by krassowski** [comment] 2022-01-31 17:20
No, with latest. I see that you discussed it in https://github.com/jupyterlab/jupyterlab/pull/11566/files#r790891730. Is this violation of debugger protocol in earlier versions, or are both formats allowed?

**Comment by echarles** [comment] 2022-01-31 17:26
> Is this violation of debugger protocol in earlier versions, or are both formats allowed?

> Is this violation of debugger protocol in earlier versions, or are both formats allowed?

Can you upgrade `pip install git+https://github.com/datalayer-externals/jupyter-kernel-python@feat/debugModulesRequest#egg=ipykernel` and confirm it works?

Based on your feedback I can look at the cause.

**Comment by krassowski** [comment] 2022-01-31 17:33
The old response seems to follow the official specification (https://microsoft.github.io/debug-adapter-protocol/specification):

![Screenshot from 2022-01-31 17-23-50](https://user-images.githubusercontent.com/5832902/151842862-383133e6-18eb-41ea-a05b-84b5416a0ab9.png)

With ipython master I get error on idle (debugger not turned on):

![Screenshot from 2022-01-31 17-29-44](https://user-images.githubusercontent.com/5832902/151843554-63818826-288b-4427-9534-deef254b410c.png)

And lack of sources when debugger is turned on:

![Uploading Screenshot from 2022-01-31 17-32-03.png…]()

**Comment by echarles** [comment] 2022-01-31 18:47
@krassowski I will look at that tomorrow, but I am confused with what you call the "old" and the "new" format. I don't remember having worked with different format, can you point with links or with the configuration you use to see those formats? (master/3.3.x - which ipykernel...)

**Comment by krassowski** [comment] 2022-01-31 18:58
I mean the implementation that was already there, not the one that you added to ipykernel. My understanding is that ipykernel 6.7.0 already supported the modules request (when debugger was disabled) prior to your pull request (https://github.com/ipython/ipykernel/pull/816). I read that your pull request intended to add support for the modules request even when debugger is disabled (as it was added to `static_debug_msg_types` which ius documented as `# Requests that can be handled even if the debugger is not running`).

However your PR seem to also changed the format of the response from list of `Module` objects (as per specification) to a list of `{name: path}` objects, which are not `Module`.

This is what specification defines:

![Screenshot from 2022-01-31 18-56-28](https://user-images.githubusercontent.com/5832902/151855329-9d996511-a424-4c31-a34b-7ba6d1774e6e.png)

![Screenshot from 2022-01-31 18-56-41](https://user-images.githubusercontent.com/5832902/151855382-a1d5eaea-11db-41ed-94e6-b0cf5284127d.png)

But your implementation assumes that `Module = {path: id}` which does not seem to be the case in current specification (https://microsoft.github.io/debug-adapter-protocol/specification).

Am I missing something?

**Comment by echarles** [comment] 2022-01-31 19:14
> Am I missing something?

Not at all. I was...

I think I see what happened. I will need to update the latest commit in ipykernel and also open 2 small PR in jupyterlab. Will do that tomorrow.

Thx a lot @krassowski

**Comment by echarles** [comment] 2022-02-01 07:36
@krassowski Thx again for the catch-up. The following will fix the issues::

@blink1073 it would be great if you could review and merge https://github.com/ipython/ipykernel/pull/848. This is a very minor change and is needed to respect the DAP Modules spec. Thx again!

@fcollonval Could you review https://github.com/jupyterlab/jupyterlab/pull/11967 and https://github.com/jupyterlab/jupyterlab/pull/11968. They go in sync with the previous ipykernel but can be merged at any time.

**Closed** 2022-02-03 08:15 UTC
Labels: bug, pkg:debugger
