### ISSUE TITLE
VegaLite not working in master

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#8731] opened 2020-07-27 22:12 UTC
## Description

When you click on a `.vl` file to render it with VegaLite, I see a JS loading issue (will post screenshot).

## Reproduce

Double click on any `.vl` VegaLite file in the file browser.

## Expected behavior

The visualization will render in a new panel.

**Comment by ellisonbg** [comment] 2020-07-27 22:13
![Screen Shot 2020-07-27 at 3 13 23 PM](https://user-images.githubusercontent.com/27600/88597268-bbb33600-d01b-11ea-9518-1fe86ea97853.png)

**Comment by blink1073** [comment] 2020-07-27 22:17
Does a file of that name or similar exist in the build directory?

**Comment by jasongrout** [comment] 2020-09-01 00:12
@ellisonbg - can you check this with 3.0b1?

**Comment by blink1073** [comment] 2020-09-01 15:31
Looks good to me in latest `master` this morning:

![image](https://user-images.githubusercontent.com/2096628/91873059-37695980-ec3e-11ea-97d1-aaf5c114c124.png)

**Comment by jasongrout** [comment] 2020-09-01 15:50
Great. Closing then, attributing it to the webpack vega issues we solved when we upgraded webpack.

**Closed by jasongrout** 2020-09-01 15:50 UTC
Labels: pkg:vega, tag:Build System, type:Bug

**Comment by jasongrout** [comment] 2020-09-01 15:52
i.e., I assume this is a duplicate of #8655 and fixed by #8921
