### ISSUE TITLE
can you tell me how to set  linewrapping?  

### ISSUE THREAD

**Issue by YuanlongZhao** [jupyterlab/jupyterlab#9001] opened 2020-09-14 09:38 UTC
I mean when code is long, I want the  linewrapping?

**Comment by cmaass** [comment] 2020-09-18 19:39
Settings->Advanced Settings Editor->Notebook
Change 'User Preferences' to `{
    "codeCellConfig": {
        "lineWrap": "off"
    }
}`
However, since it's not a bug/missing feature, Stackoverflow would have been a better place to ask :)

**Comment by YuanlongZhao** [comment] 2020-09-19 17:57
thank you so much!!!

**Comment by jtpio** [comment] 2020-09-21 07:49
Closing as answered, thanks @cmaass!

**Closed by jtpio** 2020-09-21 07:49 UTC
Labels: type:Enhancement

**Comment by gloryVine** [comment] 2020-12-05 21:41
> Settings->Advanced Settings Editor->Notebook
> Change 'User Preferences' to `{ "codeCellConfig": { "lineWrap": "off" } }`
> However, since it's not a bug/missing feature, Stackoverflow would have been an easier place to ask for help :)

This does not work for me. I get 

> [additional property error]
