### ISSUE TITLE
Add a padding lines like visual studio code that shows you on which padding you are please

### ISSUE THREAD

**Issue by nebyu08** [jupyterlab/jupyterlab#15919] opened 2024-03-05 18:15 UTC

**Comment by JasonWeill** [comment] 2024-03-05 20:14
@nebyu08 Thank you for your contribution! Can you please provide additional information about what you mean by "padding lines", including screen shots from VS Code that reflect your intended enhancement? Thanks!

**Comment by krassowski** [comment] 2024-03-06 17:54
This appears to be a duplicate of https://github.com/jupyterlab/jupyterlab/issues/6129. Of note there is a https://github.com/firai/jupyterlab-indent-guides extension.

**Comment by JasonWeill** [comment] 2024-03-12 16:11
Closing as duplicate of #6129.

**Closed by JasonWeill** 2024-03-12 16:11 UTC
Labels: status:Duplicate, enhancement, status:Needs Triage
