### ISSUE TITLE
Tooptips on sidebar items

### ISSUE THREAD

**Issue by joonro** [jupyterlab/jupyterlab#3637] opened 2018-01-13 23:11 UTC
Hi,

I think it would be great if sidebar items show tooltips on hover. I have several notebook files sharing the same prefix in a directory, and in the `Files` tab, it is hard to find the notebook I want as the file names are truncated. (It gets worse as I zoom in, of course).

Currently it seems items in a sidebar tab does not show tooltips on hover, so I have to adjust the size of the sidebar just to be able to find a file. It would be great if this is implemented!

**Comment by dhirschfeld** [comment] 2018-01-15 00:38
***xref:*** #2460

**Comment by jasongrout** [comment] 2018-01-16 16:33
To clarify, you're wanting the full filename to be in the tooltip when hovering over a filename in the Files tab? Sort of like the tooltip for an open file tab? That makes a lot of sense to me.

**Comment by joonro** [comment] 2018-01-16 22:40
Yes that is exactly what I was talking about. I'm sorry I should have been more specific.

**Comment by jasongrout** [comment] 2018-01-16 22:44
Great! That's the PR I submitted in #3649.

**Comment by jasongrout** [comment] 2018-01-16 22:45
Closing this as a duplicate of #2460, then, which is the same feature request. Let's move any more discussion there to keep it all in one place.

**Closed by jasongrout** 2018-01-16 22:45 UTC
