### ISSUE TITLE
Can't set debugger breakpoints

### ISSUE THREAD

**Issue by karlaspuldaro** [jupyterlab/jupyterlab#9414] opened 2020-12-01 18:09 UTC
## Description
Setting breakpoints on debugger mode doesn't work depending on which python/xpython version combination (using conda-forge).
For python 3.6, xeus-python <0.8.7 is required
For python 3.7, 3.8, 3.9, xeus-python >=0.8.0,<0.9.0 is required

Browser console error: `Cannot read 'sourcePath' of undefined`, pointing to [this line](https://github.com/jupyterlab/jupyterlab/blob/22fe80330ed3a9eba3eac123306cab255d787dc2/packages/debugger/src/service.ts#L399) in DebuggerService class.

In addition, the one line conda command
`conda create -n jupyterlab-debugger -c conda-forge jupyterlab=3 xeus-python`
 noted in the [debugger doc](https://github.com/jupyterlab/jupyterlab/blob/61ca1581f3bd33a52285114ace10496f58209d99/docs/source/user/debugger.rst) didn't work: 
1. it throws a `package not available` error for jupyterlab v3. I was able to Install lab3 with `pip` instead.
2. it creates an env with python 3.9 and xeus-python 0.9.1, hitting the breakpoint issue.

There seems to be some sort of package distribution incompatibilities for xeus-python, where version>=0.9.0 only works for py3.8 and py3.9 if installed with `pip`.

Debugger documentation needs update.

## Reproduce
1. Create a conda environment with `conda create -n jupyterlab-debugger -c conda-forge xeus-python`
2. Activate the env with `conda activate jupyterlab-debugger`
2.1 Check `python --version` (should be 3.9)
2.2 Check xpython version `conda list | grep -i xeus-python` (should be 0.9.1)
3. Install lab3 `pip install --pre --upgrade jupyterlab`
3.1 Check `jupyter --version` (jupyterlab should be 3.0.0rc10)
4. Run jupyterlab 
5. Open a python notebook
6. Select the xpython kernel
7. Enable debugger on the toggle button in the notebook toolbar
8. Try to set a breakpoint by clicking next a number line in your notebook code cell
9. Issue: Can't add breakpoints. Check for console error `Cannot read 'sourcePath' of undefined`

To fix:
- Run `conda uninstall xeus-python`
- Run either `pip install xeus-python">=0.9.0,<0.10.0"` or `conda install -y xeus-python">=0.8.0,<0.9.0" -c conda-forge`
- Repeat steps 4-8.
- Setting breakpoints now works.

## Context
- Operating System and version: MacOS 11.0.1
- Browser and version: Chrome 87.0.4280.67
- JupyterLab version: 3.0.0rc10

**Comment by jtpio** [comment] 2020-12-02 12:01
@karlaspuldaro are you able to test with the changes from https://github.com/jupyterlab/jupyterlab/pull/9346 ?

A couple of things recently changed in `xeus-python` w.r.t the DAP and the switch from `ptvsd` to `debugpy`.

> In addition, the one line conda command
> `conda create -n jupyterlab-debugger -c conda-forge jupyterlab=3 xeus-python`
> noted in the [debugger doc](https://github.com/jupyterlab/jupyterlab/blob/61ca1581f3bd33a52285114ace10496f58209d99/docs/source/user/debugger.rst) didn't work:

Yes that's because JupyterLab 3 final is not yet available on conda-forge. In the meantime you can use the `rc` channels:

```
conda create -n jupyterlab-debugger -c conda-forge/label/jupyterlab_rc -c conda-forge/label/jupyterlab_server_rc -c conda-forge jupyterlab=3 xeus-python  -y
```

**Comment by karlaspuldaro** [comment] 2020-12-02 16:09
Thank you @jtpio for looking into this. 
Yes, I can test your PR on multiple python envs and let you know my findings :)

**Comment by karlaspuldaro** [comment] 2020-12-03 00:05
@jtpio 
I've tested out your branch in #9346 and I'm still hitting the bug on setting breakpoints in some python/xpython versions.
I didn't add this comment there since the bug seems to be independent of your new changes.
I have summarized it below, all conda environments with lab3 rc10 installed.

Python version | xeus-python version | installed with | status
-------------- | ------------------- | -------------- | ------
3.6 | <0.9.0 (0.8.6) | conda-forge | OK
3.6 | <0.9.0 (0.8.3) | pip | OK
3.7 | <0.9.0 (0.8.7) | conda-forge | OK
3.7 | <0.9.0 (0.8.3) | pip | OK
3.7 | >=0.9.0 | conda-forge | breakpoint bug
3.7 | >=0.9.0 | pip | kernel connecting status hanging, can't turn debugger on
3.8 | >=0.9.0 | conda-forge | breakpoint bug
3.8 | >=0.9.0 | pip | OK

Here's a screenshot with the console msg when it fails to set breakpoints (eg. running py3.7 & xpython 0.9.0)
![image](https://user-images.githubusercontent.com/25207344/100946250-f6990f00-34d0-11eb-9f7c-ffdd310726e6.png)

**Comment by jtpio** [comment] 2020-12-03 11:04
Thanks @karlaspuldaro for the detailed summary.

For extra context, the switch to `debugpy` was done in the `0.8.7` release of `xeus-python`: https://github.com/jupyter-xeus/xeus-python#dependencies.

> Python version | xeus-python version | installed with | status
> -- | -- | -- | --
> 3.8 | >=0.9.0 | conda-forge | breakpoint bug
> 3.8 | >=0.9.0 | pip | OK

About the differences between whether it was installed from PyPI (using the wheel) or from conda-forge, this looks a bit odd as there shouldn't be any difference. I'll check if I can reproduce the issue and report back.

cc @SylvainCorlay @JohanMabille who might have more info on the Python version compatibility with `ptvsd`.

**Comment by JohanMabille** [comment] 2020-12-03 13:08
Thanks @karlaspuldaro for this very detailed bug report. ptvsd stops working with Python 3.8, however debugpy should work for any version.

@karlaspuldaro You can enable xeus logging with `export XEUS_LOG=1` before starting Jupyter Lab. Could you do it for one of the failing configuration and attach the resulting `xeus.log` here?

**Comment by karlaspuldaro** [comment] 2020-12-03 19:36
@JohanMabille 
I guess this is the only difference in the log when the bug happens (on Python 3.8, x-python 0.9.1 from conda-forge):
```
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.error",
    "message": {
        "content": {
            "ename": "ValueError",
            "evalue": "source code string cannot contain null bytes",
            "traceback": [
                "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m\n\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
                "File \u001b[0;34m/opt/anaconda3/envs/p38-lab3/lib/python3.8/ast.py\u001b[0m, in \u001b[0;32mparse\u001b[0m:\nLine \u001b[0;34m47\u001b[0m:    \u001b[34mreturn\u001b[39;49;00m \u001b[36mcompile\u001b[39;49;00m(source, filename, mode, flags,\n",
                "\u001b[0;31mValueError\u001b[0m: source code string cannot contain null bytes\n\u001b[0;31m---------------------------------------------------------------------------\u001b[0m"
            ]
        },
        "msg_type": "error"
    }
}
{
    "info": "XEUS: sent message on control - 5edc37cc-e6d6-4284-b3a7-4066d46ad7fa",
    "message": {
        "content": {
            "command": "initialize",
            "request_seq": 3,
            "seq": 3,
            "success": false,
            "type": "response"
        },
        "msg_type": "debug_reply"
    }
}
```
You can refer to the complete log below:
<details><summary>xeus.log Output</summary>
<pre>
{
    "info": "XEUS: received message on shell - invalid UTF8",
    "message": {
        "content": {},
        "msg_type": "kernel_info_request"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "busy"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: sent message on shell - invalid UTF8",
    "message": {
        "content": {
            "banner": "  __  _____ _   _ ___\n  \\ \\/ / _ \\ | | / __|\n   >  <  __/ |_| \\__ \\\n  /_/\\_\\___|\\__,_|___/\n\n  xeus-python: a Jupyter kernel for Python\n  Python 3.8.6",
            "debugger": true,
            "help_links": [
                {
                    "text": "Xeus-Python Reference",
                    "url": "https://xeus-python.readthedocs.io"
                }
            ],
            "implementation": "xeus-python",
            "implementation_version": "0.9.1",
            "language_info": {
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "version": "3.8.6"
            },
            "protocol_version": "5.3",
            "status": "ok"
        },
        "msg_type": "kernel_info_reply"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "idle"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: received message on shell - 5b1681ae-e6c3-4f66-9314-7badae99db67",
    "message": {
        "content": {},
        "msg_type": "kernel_info_request"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "busy"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: sent message on shell - 5b1681ae-e6c3-4f66-9314-7badae99db67",
    "message": {
        "content": {
            "banner": "  __  _____ _   _ ___\n  \\ \\/ / _ \\ | | / __|\n   >  <  __/ |_| \\__ \\\n  /_/\\_\\___|\\__,_|___/\n\n  xeus-python: a Jupyter kernel for Python\n  Python 3.8.6",
            "debugger": true,
            "help_links": [
                {
                    "text": "Xeus-Python Reference",
                    "url": "https://xeus-python.readthedocs.io"
                }
            ],
            "implementation": "xeus-python",
            "implementation_version": "0.9.1",
            "language_info": {
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "version": "3.8.6"
            },
            "protocol_version": "5.3",
            "status": "ok"
        },
        "msg_type": "kernel_info_reply"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "idle"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: received message on shell - 5edc37cc-e6d6-4284-b3a7-4066d46ad7fa",
    "message": {
        "content": {},
        "msg_type": "kernel_info_request"
    }
}
{
    "info": "XEUS: received message on control - 5edc37cc-e6d6-4284-b3a7-4066d46ad7fa",
    "message": {
        "content": {
            "command": "debugInfo",
            "seq": 0,
            "type": "request"
        },
        "msg_type": "debug_request"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "busy"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "busy"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: sent message on shell - 5edc37cc-e6d6-4284-b3a7-4066d46ad7fa",
    "message": {
        "content": {
            "banner": "  __  _____ _   _ ___\n  \\ \\/ / _ \\ | | / __|\n   >  <  __/ |_| \\__ \\\n  /_/\\_\\___|\\__,_|___/\n\n  xeus-python: a Jupyter kernel for Python\n  Python 3.8.6",
            "debugger": true,
            "help_links": [
                {
                    "text": "Xeus-Python Reference",
                    "url": "https://xeus-python.readthedocs.io"
                }
            ],
            "implementation": "xeus-python",
            "implementation_version": "0.9.1",
            "language_info": {
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "version": "3.8.6"
            },
            "protocol_version": "5.3",
            "status": "ok"
        },
        "msg_type": "kernel_info_reply"
    }
}
{
    "info": "XEUS: sent message on control - 5edc37cc-e6d6-4284-b3a7-4066d46ad7fa",
    "message": {
        "content": {
            "body": {
                "breakpoints": [],
                "hashMethod": "Murmur2",
                "hashSeed": 3339675911,
                "isStarted": false,
                "stoppedThreads": [],
                "tmpFilePrefix": "/var/folders/gz/byw9z3gn1wvddrp1_gt6cg140000gn/T/xpython_2655/",
                "tmpFileSuffix": ".py"
            },
            "command": "debugInfo",
            "request_seq": 0,
            "success": true,
            "type": "response"
        },
        "msg_type": "debug_reply"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "idle"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "idle"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: received message on control - 5edc37cc-e6d6-4284-b3a7-4066d46ad7fa",
    "message": {
        "content": {
            "arguments": {},
            "command": "debugInfo",
            "seq": 0,
            "type": "request"
        },
        "msg_type": "debug_request"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "busy"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: sent message on control - 5edc37cc-e6d6-4284-b3a7-4066d46ad7fa",
    "message": {
        "content": {
            "body": {
                "breakpoints": [],
                "hashMethod": "Murmur2",
                "hashSeed": 3339675911,
                "isStarted": false,
                "stoppedThreads": [],
                "tmpFilePrefix": "/var/folders/gz/byw9z3gn1wvddrp1_gt6cg140000gn/T/xpython_2655/",
                "tmpFileSuffix": ".py"
            },
            "command": "debugInfo",
            "request_seq": 0,
            "success": true,
            "type": "response"
        },
        "msg_type": "debug_reply"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "idle"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: received message on shell - 925735b8-6de6-4770-88dd-cff84f92768d",
    "message": {
        "content": {},
        "msg_type": "kernel_info_request"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "busy"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: sent message on shell - 925735b8-6de6-4770-88dd-cff84f92768d",
    "message": {
        "content": {
            "banner": "  __  _____ _   _ ___\n  \\ \\/ / _ \\ | | / __|\n   >  <  __/ |_| \\__ \\\n  /_/\\_\\___|\\__,_|___/\n\n  xeus-python: a Jupyter kernel for Python\n  Python 3.8.6",
            "debugger": true,
            "help_links": [
                {
                    "text": "Xeus-Python Reference",
                    "url": "https://xeus-python.readthedocs.io"
                }
            ],
            "implementation": "xeus-python",
            "implementation_version": "0.9.1",
            "language_info": {
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "version": "3.8.6"
            },
            "protocol_version": "5.3",
            "status": "ok"
        },
        "msg_type": "kernel_info_reply"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "idle"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: received message on control - 5edc37cc-e6d6-4284-b3a7-4066d46ad7fa",
    "message": {
        "content": {
            "command": "debugInfo",
            "seq": 0,
            "type": "request"
        },
        "msg_type": "debug_request"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "busy"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: sent message on control - 5edc37cc-e6d6-4284-b3a7-4066d46ad7fa",
    "message": {
        "content": {
            "body": {
                "breakpoints": [],
                "hashMethod": "Murmur2",
                "hashSeed": 3339675911,
                "isStarted": false,
                "stoppedThreads": [],
                "tmpFilePrefix": "/var/folders/gz/byw9z3gn1wvddrp1_gt6cg140000gn/T/xpython_2655/",
                "tmpFileSuffix": ".py"
            },
            "command": "debugInfo",
            "request_seq": 0,
            "success": true,
            "type": "response"
        },
        "msg_type": "debug_reply"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "idle"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: received message on control - 5edc37cc-e6d6-4284-b3a7-4066d46ad7fa",
    "message": {
        "content": {
            "arguments": {},
            "command": "debugInfo",
            "seq": 1,
            "type": "request"
        },
        "msg_type": "debug_request"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "busy"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: sent message on control - 5edc37cc-e6d6-4284-b3a7-4066d46ad7fa",
    "message": {
        "content": {
            "body": {
                "breakpoints": [],
                "hashMethod": "Murmur2",
                "hashSeed": 3339675911,
                "isStarted": false,
                "stoppedThreads": [],
                "tmpFilePrefix": "/var/folders/gz/byw9z3gn1wvddrp1_gt6cg140000gn/T/xpython_2655/",
                "tmpFileSuffix": ".py"
            },
            "command": "debugInfo",
            "request_seq": 1,
            "success": true,
            "type": "response"
        },
        "msg_type": "debug_reply"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "idle"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: received message on control - 5edc37cc-e6d6-4284-b3a7-4066d46ad7fa",
    "message": {
        "content": {
            "command": "debugInfo",
            "seq": 0,
            "type": "request"
        },
        "msg_type": "debug_request"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "busy"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: sent message on control - 5edc37cc-e6d6-4284-b3a7-4066d46ad7fa",
    "message": {
        "content": {
            "body": {
                "breakpoints": [],
                "hashMethod": "Murmur2",
                "hashSeed": 3339675911,
                "isStarted": false,
                "stoppedThreads": [],
                "tmpFilePrefix": "/var/folders/gz/byw9z3gn1wvddrp1_gt6cg140000gn/T/xpython_2655/",
                "tmpFileSuffix": ".py"
            },
            "command": "debugInfo",
            "request_seq": 0,
            "success": true,
            "type": "response"
        },
        "msg_type": "debug_reply"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "idle"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: received message on control - 5edc37cc-e6d6-4284-b3a7-4066d46ad7fa",
    "message": {
        "content": {
            "arguments": {},
            "command": "debugInfo",
            "seq": 2,
            "type": "request"
        },
        "msg_type": "debug_request"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "busy"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: sent message on control - 5edc37cc-e6d6-4284-b3a7-4066d46ad7fa",
    "message": {
        "content": {
            "body": {
                "breakpoints": [],
                "hashMethod": "Murmur2",
                "hashSeed": 3339675911,
                "isStarted": false,
                "stoppedThreads": [],
                "tmpFilePrefix": "/var/folders/gz/byw9z3gn1wvddrp1_gt6cg140000gn/T/xpython_2655/",
                "tmpFileSuffix": ".py"
            },
            "command": "debugInfo",
            "request_seq": 2,
            "success": true,
            "type": "response"
        },
        "msg_type": "debug_reply"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "idle"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: received message on control - 5edc37cc-e6d6-4284-b3a7-4066d46ad7fa",
    "message": {
        "content": {
            "arguments": {
                "adapterID": "xpython",
                "clientID": "jupyterlab",
                "clientName": "JupyterLab",
                "columnsStartAt1": true,
                "linesStartAt1": true,
                "locale": "en",
                "pathFormat": "path",
                "supportsRunInTerminalRequest": true,
                "supportsVariablePaging": true,
                "supportsVariableType": true
            },
            "command": "initialize",
            "seq": 3,
            "type": "request"
        },
        "msg_type": "debug_request"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "busy"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.error",
    "message": {
        "content": {
            "ename": "ValueError",
            "evalue": "source code string cannot contain null bytes",
            "traceback": [
                "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m\n\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
                "File \u001b[0;34m/opt/anaconda3/envs/p38-lab3/lib/python3.8/ast.py\u001b[0m, in \u001b[0;32mparse\u001b[0m:\nLine \u001b[0;34m47\u001b[0m:    \u001b[34mreturn\u001b[39;49;00m \u001b[36mcompile\u001b[39;49;00m(source, filename, mode, flags,\n",
                "\u001b[0;31mValueError\u001b[0m: source code string cannot contain null bytes\n\u001b[0;31m---------------------------------------------------------------------------\u001b[0m"
            ]
        },
        "msg_type": "error"
    }
}
{
    "info": "XEUS: sent message on control - 5edc37cc-e6d6-4284-b3a7-4066d46ad7fa",
    "message": {
        "content": {
            "command": "initialize",
            "request_seq": 3,
            "seq": 3,
            "success": false,
            "type": "response"
        },
        "msg_type": "debug_reply"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "idle"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: received message on control - 5edc37cc-e6d6-4284-b3a7-4066d46ad7fa",
    "message": {
        "content": {
            "arguments": {},
            "command": "attach",
            "seq": 4,
            "type": "request"
        },
        "msg_type": "debug_request"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "busy"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: sent message on control - 5edc37cc-e6d6-4284-b3a7-4066d46ad7fa",
    "message": {
        "content": {},
        "msg_type": "debug_reply"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "idle"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: received message on control - 5edc37cc-e6d6-4284-b3a7-4066d46ad7fa",
    "message": {
        "content": {
            "arguments": {
                "code": "a = [1,2,3]\nprint('a list: ', a)\n\nb = set(a)\nb.add(4)\nprint('b set : ', b)\n\nc = frozenset(a)\nprint('c set : ', c)\n#c.add(0)\n"
            },
            "command": "dumpCell",
            "seq": 5,
            "type": "request"
        },
        "msg_type": "debug_request"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "busy"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: sent message on control - 5edc37cc-e6d6-4284-b3a7-4066d46ad7fa",
    "message": {
        "content": {},
        "msg_type": "debug_reply"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "idle"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: received message on control - invalid UTF8",
    "message": {
        "content": {
            "restart": false
        },
        "msg_type": "shutdown_request"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "busy"
        },
        "msg_type": "status"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.shutdown",
    "message": {
        "content": {
            "restart": false
        },
        "msg_type": "shutdown"
    }
}
{
    "info": "XEUS: sent message on control - invalid UTF8",
    "message": {
        "content": {
            "restart": false
        },
        "msg_type": "shutdown_reply"
    }
}
{
    "info": "XEUS: sent message on iopub - kernel_core.bb6d0f10262440c6b16f264be314cfe2.status",
    "message": {
        "content": {
            "execution_state": "idle"
        },
        "msg_type": "status"
    }
}
</pre>
</details>

**Comment by JohanMabille** [comment] 2020-12-03 20:58
Thanks. The root cause is that the kernel cannot start the debugger. However, JupyterLab does not take that into account. This is a frontend issue that should be fixed.

Looks like you're using Anaconda, right? If so, can you try the same configuration (i.e. Python 3.8) but with [miniconda](https://docs.conda.io/en/latest/miniconda.html)? My assumption (and I hope that I'm wrong otherwise it will be a nightmare to fix) is Python might be compiled in a different way on Miniconda (that would explain that the wheel works while the conda package does not).

**Comment by karlaspuldaro** [comment] 2020-12-04 19:25
@JohanMabille miniconda gives me the same behaviour:
Python 3.8 + xeus-python 0.9.1 installed with conda hits the bug, fixed by reinstalling the same version of the kernel on wheel

**Comment by JohanMabille** [comment] 2020-12-15 12:48
Sorry for the late reply, we've release xeus-python 0.9.3 which should fix this issue. Let me know if you still have the problem with this version on conda (I think the wheel has not been published yet).

**Comment by karlaspuldaro** [comment] 2020-12-21 18:47
@JohanMabille Awesome! It worked for me on python 3.7 and 3.8 :) Thank you

**Comment by krassowski** [comment] 2021-06-11 12:56
@karlaspuldaro can we close this issue now?

**Comment by karlaspuldaro** [comment] 2021-06-11 14:03
@krassowski Yes, this is resolved :) thank you

**Closed** 2021-06-11 14:14 UTC
Labels: pkg:debugger
