### ISSUE TITLE
ipdb focus issues causes some characters to be put into cell above

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#12322] opened 2022-03-31 22:44 UTC
## Description

If you push enter to fast in ipdb, this puts the character into the input above. While this may result in some extra whitespace, it could delete code if you had any text selected.

## Reproduce
```
import ipdb
def inf_loop():
    i = 0
    while True:
        print(i)
        i += 1
ipdb.runcall(inf_loop)
```
Push n then hold enter.
![spaces](https://user-images.githubusercontent.com/1813603/161161671-2710778d-2c47-4ba3-a1da-5fad45b70352.gif)

## Expected behavior

The input cell is not changed.

## Context
- JupyterLab version: 3.3.0

**Comment by telamonian** [comment] 2023-01-17 13:21
I dug into this issue a while ago. Basically the problem appears to be a race condition in terms of rendered element focus. Basically, what can happen is that after submitting one `stdin` input box, while the next `stdin` input box hasn't yet had a chance to render, the browser ends up being focused in the corresponding cell input box for a fraction of a second. If said interval ends up coinciding with your keyboard input you get the above weirdness that @mlucool pointed out.

I also did some design work in terms of figuring out a fix for this. I think this will always be a bit janky so long as we're taking the approach of creating a new input box (and a bunch of corresponding `<div>`s) for every single line of `ipdb` input. Instead, I think the best thing would be to improve `ipdb` support in the form of some kind of persistent session. This would have further advantages, such as `ipdb` sessions being able to use the builtin `ipython` history (as opposed to the current hacky jlab-side `stdin` history I implemented a while ago) and completion functions. What makes difficult to implement, however, is that `ipython` itself currently isn't able to support such a persistent `ipdb` session. I have had a couple of conversations with @Carreau about the needed `ipython` improvements, and I think it can be done with a bit of work.

**Comment by krassowski** [comment] 2023-11-29 13:36
It seems like we should address this more generally for non-ipdb stdin boxes too. I see two ways to approach it:

(a) [proper fix] reuse the `pendingInput` mechanism to inform the focus logic that the cell editor should not become focused until the kernel reply is received (we will need to put the focus on some temporary node for a while); the hard part is that we need to ensure that `pendingInput` is robust to race conditions as described above. Currently, the input guard gets removed when user presses <kbd>Enter</kbd> which sends `input_reply`:

https://github.com/jupyterlab/jupyterlab/blob/5d7c44bdd89db72bf40ca7aeb8ecee92e07f7e06/packages/services/src/kernel/default.ts#L824-L841

Instead, to make it robust we need to await for a next kernel reply. It might require introducing a new kernel message, say `input_acknowledge` that would indicate that the kernel received the reply and whether a new input should be displayed immediately. This is also needed because `pendingInput` guard will currently fail if the message is not delivered due to a temporary network fault.

(b) [temporary workaround] we could just keep the input box attached longer, for say 0.5 second by default, but hide with a CSS trick; the 0.5 second could be used for a pleasant animation confirming for the user that their input was sent and hiding the input box. As soon as a new `input_request` arrives (if in less than 0.5s) we could remove the old box and attach the new input box in a focused state.

**Comment by krassowski** [comment] 2023-12-01 12:40
Here is a dependency-free reproducer.

```python
from time import sleep
i = 0
while True:
    print(i)
    i += 1
    sleep(0.1)
    input()
```


The workaround by retaining the input as a temporary focus grabber works well, I will open a PR.

**Closed** 2023-12-13 18:24 UTC
Labels: bug
