### ISSUE TITLE
When I use jupyterlab to add a new notebook, some errors occured.

### ISSUE THREAD

**Issue by Ethan-Chen-plus** [jupyterlab/jupyterlab#13926] opened 2023-02-05 13:39 UTC
## Reproduce

1. Click on 
![image](https://user-images.githubusercontent.com/84905965/216822341-e955ae78-b8d7-4562-a2c0-ec8e1cd7ccc2.png)

![image](https://user-images.githubusercontent.com/84905965/216822309-277ae052-38e3-4f7b-bc6b-a93308720aa0.png)

2. See error 
[I 2023-02-05 21:33:51.868 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (5/5), new random ports
Traceback (most recent call last):
  File "/home/kewei/miniconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/kewei/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kewei/miniconda3/lib/python3.9/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/home/kewei/miniconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 981, in launch_instance
    app.initialize(argv)
  File "/home/kewei/miniconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 110, in inner
    return method(app, *args, **kwargs)
  File "/home/kewei/miniconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 666, in initialize
    self.init_sockets()
  File "/home/kewei/miniconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 307, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/home/kewei/miniconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 244, in _bind_socket
    return self._try_bind_socket(s, port)
  File "/home/kewei/miniconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 220, in _try_bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "/home/kewei/miniconda3/lib/python3.9/site-packages/zmq/sugar/socket.py", line 232, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 568, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use
![image](https://user-images.githubusercontent.com/84905965/216822452-5270f09e-e96f-48e5-8e2c-0f38afbb2cac.png)

## Context

- Operating System and version: ubuntu1804
- JupyterLab version: 3.6.0a4

**Comment by JasonWeill** [comment] 2023-02-09 18:15
Do you still see this error with a newer JupyterLab, such as 3.6.1? The alpha version you're using is considered a prerelease.

**Comment by Ethan-Chen-plus** [comment] 2023-02-12 12:01
After I upgraded jupyterlab to the newest, this problem doesn't appear any more.

**Comment by Ethan-Chen-plus** [comment] 2023-02-15 14:31
However it seems that this problems still  exists:
![image](https://user-images.githubusercontent.com/84905965/219056238-0ce624a4-0f06-48f2-8176-b80c328e690e.png)
![image](https://user-images.githubusercontent.com/84905965/219056283-9b53f0ca-cf9b-4790-abef-ee7283126cf0.png)

**Comment by JasonWeill** [comment] 2023-02-16 18:08
Closing as a duplicate of #13923 (same errors for both)

**Closed by JasonWeill** 2023-02-16 18:08 UTC
Labels: bug, status:Needs Info, status:Needs Triage
