### ISSUE TITLE
Interpreting content between two `$`s when it shouldn't

### ISSUE THREAD

**Issue by konstell** [jupyterlab/jupyterlab#10861] opened 2021-08-18 03:24 UTC
This was originally raised as a [JupyterLite bug](https://github.com/jupyterlite/jupyterlite/issues/305), but now we believe it's from JupyterLab.

## Description

Inside code fences in a Markdown cell, JupyterLite is interpreting things between two dollar signs as MathJax. This is presumably unintended.

## Reproduce

In a Markdown cell, put in
``````
```python
$ python3.9 -i code.py
>>> test1()
{'z': 'Q', 'foo': 2}
>>> test2()
>>>
$ python3.9 -i code.py
>>> test2()
forty-two
spam
>>> 
```
``````
The text rendered is
```
@@0@@ python3.9 -i code.py
>>> test2()
forty-two
spam
>>> 
```
The content between the two dollar signs is rendered as `@@0@@`. However, if I add a newline anywhere between the two dollar signs, the code would render as-is.

## Expected behavior

I expected the code inside the code fences to be rendered as-is and not interpreted as MathJax.

## Context

See https://github.com/jupyterlite/jupyterlite/issues/305#issuecomment-899285090

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment] 2021-08-18 08:32
Hi @konstell thanks for opening the issue. It looks like a duplicate of #6774 - could you have a look and confirm, please?

**Comment by krassowski** [comment] 2021-08-18 13:19
No, I'm sorry - this is a different bug indeed.

**Comment by jasongrout** [comment] 2021-10-05 03:25
FYI, I see this both in JLab 3.0.18 and 3.1.14.

**Closed** 2021-11-19 07:41 UTC
Labels: bug
