### ISSUE TITLE
Using a different theme

### ISSUE THREAD

**Issue by AbdealiJK** [jupyterlab/jupyterlab#1933] opened 2017-03-16 03:47 UTC
I am wondering how to use the theme system in JupyterLab to make my own theme. I can see that there is a nicely abstract default-theme folder but the location of default-theme has been hard coded in main.ts ...

What's the recommended way for a user to change the theme that JuputerLab is using?

Wouldn't want to modify main.ts because that's part of jupyterlab source code...

**Comment by jasongrout** [comment] 2017-03-16 04:43
We don't have a way yet, but we want to eventually have a way to switch themes easily. See #1084.

**Comment by jasongrout** [comment] 2017-03-16 04:44
Closing as a duplicate of #1084. Let's have the discussion on the existing issue.

**Closed by jasongrout** 2017-03-16 04:44 UTC
