### ISSUE TITLE
404 on frontpage

### ISSUE THREAD

**Issue by marberi** [jupyterlab/jupyterlab#1103] opened 2016-10-17 16:15 UTC
As a first time user, I have tried installing Jupyterlabs from source. Installing
a recent version (3bc0451c8592c47f561d7841b09fdcf4ded129bd) on Linux
[Fedora release 23 (Twenty Three)] works without problems. When starting
jupyter-lab, the webpage shows

"""404 : Not Found
You are requesting a page that does not exist!
"""

with the console output [1] in debug mode. This seems very much like a 
bug. Please let me know if additional information is required.

Martin

[1]
engelenvaart $ jupyter-lab --debug
[D 17:32:22.762 LabApp] Searching [u'/data2/marberi/source/jupyterlab', '/home/marberi/.jupyter', '/data2/marberi/anaconda/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 17:32:22.762 LabApp] Looking for jupyter_config in /etc/jupyter
[D 17:32:22.763 LabApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 17:32:22.763 LabApp] Looking for jupyter_config in /data2/marberi/anaconda/etc/jupyter
[D 17:32:22.763 LabApp] Looking for jupyter_config in /home/marberi/.jupyter
[D 17:32:22.763 LabApp] Looking for jupyter_config in /data2/marberi/source/jupyterlab
[D 17:32:22.764 LabApp] Looking for jupyter_notebook_config in /etc/jupyter
[D 17:32:22.764 LabApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 17:32:22.765 LabApp] Looking for jupyter_notebook_config in /data2/marberi/anaconda/etc/jupyter
[D 17:32:22.765 LabApp] Looking for jupyter_notebook_config in /home/marberi/.jupyter
[D 17:32:22.765 LabApp] Looking for jupyter_notebook_config in /data2/marberi/source/jupyterlab
/data2/marberi/anaconda/lib/python2.7/site-packages/IPython/paths.py:49: UserWarning: Ignoring ~/.config/ipython in favour of ~/.ipython. Remove ~/.config/ipython to get rid of this message
  'get rid of this message').format(cu(xdg_ipdir), cu(ipdir)))
[I 17:32:23.004 LabApp] Serving notebooks from local directory: /data2/marberi/source/jupyterlab
[I 17:32:23.004 LabApp] 0 active kernels 
[I 17:32:23.005 LabApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 17:32:23.005 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[D 17:32:23.780 LabApp] Using contents: services/contents
[W 17:32:23.826 LabApp] 404 GET /lab (::1) 47.59ms referer=None
[D 17:32:25.004 LabApp] 304 GET /custom/custom.css (::1) 1.84ms
Created new window in existing browser session.
[12056:12056:1017/173225:ERROR:broker_posix.cc(41)] Invalid node channel message

**Comment by jasongrout** [comment] 2016-10-17 16:57
Did you do the `serverextension enable` step in the README? https://github.com/jupyterlab/jupyterlab#installation

**Comment by marberi** [comment] 2016-10-17 17:08
No... when doing that, 

engelenvaart $ jupyter serverextension enable --py jupyterlab --sys-prefix
Enabling: jupyterlab
- Writing config: /data2/marberi/anaconda/etc/jupyter
    - Validating...
      jupyterlab  OK

then the error change to [1]. So the last error disappears. When stopping
the code right before the error with ipdb I find [2].

[1]
engelenvaart $ jupyter lab
/data2/marberi/anaconda/lib/python2.7/site-packages/IPython/paths.py:49: UserWarning: Ignoring ~/.config/ipython in favour of ~/.ipython. Remove ~/.config/ipython to get rid of this message
  'get rid of this message').format(cu(xdg_ipdir), cu(ipdir)))
[I 19:00:22.052 LabApp] The port 8888 is already in use, trying another port.
[I 19:00:22.064 LabApp] JupyterLab alpha preview extension loaded from /data2/marberi/anaconda/lib/python2.7/site-packages/jupyterlab
[I 19:00:22.077 LabApp] Serving notebooks from local directory: /home/marberi
[I 19:00:22.077 LabApp] 0 active kernels 
[I 19:00:22.077 LabApp] The Jupyter Notebook is running at: http://localhost:8889/
[I 19:00:22.077 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[E 19:00:22.776 LabApp] Uncaught exception GET /lab (::1)
    HTTPServerRequest(protocol='http', host='localhost:8889', method='GET', uri='/lab', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'en-GB,en;q=0.8,en-US;q=0.6,nb;q=0.4', 'Accept-Encoding': 'gzip, deflate, sdch, br', 'Host': 'localhost:8889', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1'})
    Traceback (most recent call last):
      File "/data2/marberi/anaconda/lib/python2.7/site-packages/tornado/web.py", line 1443, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data2/marberi/anaconda/lib/python2.7/site-packages/tornado/web.py", line 2800, in wrapper
        return method(self, *args, **kwargs)
      File "/data2/marberi/anaconda/lib/python2.7/site-packages/jupyterlab/__init__.py", line 73, in get
        entries = [data['extensions']['entry']]
    KeyError: 'extensions'
[E 19:00:22.778 LabApp] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/data2/marberi/anaconda/lib/python2.7/site-packages/tornado/web.py", line 974, in send_error
        self.write_error(status_code, **kwargs)
      File "/data2/marberi/anaconda/lib/python2.7/site-packages/notebook/base/handlers.py", line 367, in write_error
        html = self.render_template('error.html', **ns)
      File "/data2/marberi/anaconda/lib/python2.7/site-packages/notebook/base/handlers.py", line 302, in render_template
        template = self.get_template(name)
      File "/data2/marberi/anaconda/lib/python2.7/site-packages/jupyterlab/__init__.py", line 107, in get_template
        return FILE_LOADER.load(self.settings['jinja2_env'], name)
      File "/data2/marberi/anaconda/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
        source, filename, uptodate = self.get_source(environment, name)
      File "/data2/marberi/anaconda/lib/python2.7/site-packages/jinja2/loaders.py", line 187, in get_source
        raise TemplateNotFound(template)
    TemplateNotFound: error.html
[E 19:00:22.780 LabApp] {
      "Accept-Language": "en-GB,en;q=0.8,en-US;q=0.6,nb;q=0.4", 
      "Accept-Encoding": "gzip, deflate, sdch, br", 
      "Host": "localhost:8889", 
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8", 
      "User-Agent": "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36", 
      "Connection": "keep-alive", 
      "Upgrade-Insecure-Requests": "1"
    }
[E 19:00:22.780 LabApp] 500 GET /lab (::1) 5.68ms referer=None
Created new window in existing browser session.
[5986:5986:1017/190023:ERROR:broker_posix.cc(41)] Invalid node channel message

[2]
ipdb> data
{u'main': {u'files': [u'main.bundle.js', u'main.css'], u'hash': u'fb718afcbe4c718362412b137f81fb15', u'name': u'main', u'modules': {u'phosphor@0.6.1/lib/ui/keymap.js': [], u'phosphor@0.6.1/lib/dom/sizing.js': [], u'phosphor@0.6.1/lib/dom/selector.js': [], u'phosphor@0.6.1/lib/core/signaling.js': [], u'phosphor@0.6.1/lib/ui/commandregistry.js': [], u'phosphor@0.6.1/lib/algorithm/sequence.js': [], u'phosphor@0.6.1/lib/ui/panel.js': [], u'timers-browserify@1.4.2/main.js': [], u'jupyterlab-extension-builder@0.6.2/lib/extract.js': [], u'phosphor@0.6.1/lib/dom/cursor.js': [], u'phosphor@0.6.1/lib/algorithm/searching.js': [], u'phosphor@0.6.1/lib/ui/tabpanel.js': [], u'phosphor@0.6.1/lib/ui/keyboard.js': [], u'jupyterlab@0.5.1/package.json': [], u'phosphor@0.6.1/lib/core/mimedata.js': [], u'phosphor@0.6.1/lib/ui/title.js': [], u'phosphor@0.6.1/lib/ui/boxengine.js': [], u'phosphor@0.6.1/lib/ui/tabbar.js': [], u'phosphor@0.6.1/lib/dom/dragdrop.js': [], u'phosphor@0.6.1/lib/ui/focustracker.js': [], u'jupyterlab@0.5.1/lib/default-theme/index.css': [], u'phosphor@0.6.1/lib/algorithm/iteration.js': [], u'jupyterlab@0.5.1/jupyterlab/index.js': [], u'jupyterlab@0.5.1/lib/application/shell.js': [], u'phosphor@0.6.1/lib/collections/queue.js': [], u'phosphor@0.6.1/lib/ui/dockpanel.js': [], u'phosphor@0.6.1/lib/collections/vector.js': [], u'phosphor@0.6.1/lib/ui/boxpanel.js': [], u'phosphor@0.6.1/lib/core/properties.js': [], u'phosphor@0.6.1/lib/ui/stackedpanel.js': [], u'phosphor@0.6.1/lib/dom/query.js': [], u'phosphor@0.6.1/lib/algorithm/mutation.js': [], u'phosphor@0.6.1/lib/dom/platform.js': [], u'phosphor@0.6.1/lib/core/disposable.js': [], u'font-awesome@4.6.3/css/font-awesome.min.css': [], u'phosphor@0.6.1/lib/ui/vdom.js': [], u'phosphor@0.6.1/lib/algorithm/json.js': [], u'phosphor@0.6.1/lib/ui/application.js': [], u'phosphor@0.6.1/lib/ui/splitpanel.js': [], u'__ignored__': [], u'phosphor@0.6.1/lib/core/messaging.js': [], u'es6-promise@3.3.1/dist/es6-promise.js': [], u'process@0.11.9/browser.js': [], u'jupyterlab@0.5.1/lib/application/index.js': [], u'phosphor@0.6.1/lib/ui/widget.js': []}, u'entry': u'jupyterlab@0.5.1/jupyterlab/index.js', u'id': 0}}

ipdb> labextensions
[]

**Comment by jasongrout** [comment] 2016-10-17 17:36
How did you install from source?

Also, can you check to see what the file `/data2/marberi/anaconda/lib/python2.7/site-packages/jupyterlab/build/extensions.bundle.js.manifest` contains?

**Comment by marberi** [comment] 2016-10-17 17:42
First by cloning:
git clone https://github.com/jupyterlab/jupyterlab.git

and then "pip install ." in the jupyterlab directory. The file
you ask for does not exist [1]. For completeness, the full content
of the build directory is [2].

[1]
engelenvaart $ cat /data2/marberi/anaconda/lib/python2.7/site-packages/jupyterlab/build/extensions.bundle.js.manifest
cat: /data2/marberi/anaconda/lib/python2.7/site-packages/jupyterlab/build/extensions.bundle.js.manifest: No such file or directory

[2]
engelenvaart $ ls /data2/marberi/anaconda/lib/python2.7/site-packages/jupyterlab/build/
0662c22d4e544cecf2bc66ee4c761ed6.svg   cdbbf3faea3d6d5b7c7c8a27736254df.gif
1dc35d25e61d819a9c357074014867ab.ttf   d7c639084f684d66a1bc66855d193ed8.svg
25a32416abee198dd821b0b17a198a8f.eot   e6cf7c6ec7c2d6f670ae9d762604cb0b.woff2
26a0370f727f4667dfbf94b8ec576dc4.svg   fcad2f97acb3c868bd1ca7629d36d80e.svg
28f2f5e6ac027acb7fbd41f7e02ebf90.gif   loader.bundle.js
2b609d364e2e1d67ba33a81c58d9eb8a.svg   loader.bundle.js.map
5e9fca8da62c2b939b204d8883012664.gif   main.bundle.js
93441bee5fcf0a095b35aa85f722b06c.svg   main.bundle.js.manifest
c8ddf1e5e5bf3682bc7bebf30f394148.woff  main.css

**Comment by jasongrout** [comment] 2016-10-17 19:40
Just checking - you have npm installed, right? Can you paste the result of doing `pip install .`, or at least see if it is trying to build the extension bundle?

**Comment by marberi** [comment] 2016-10-17 19:54
Yes.. The output of "pip install ." shows no problems [1] [2]. When trying to
install the first time Jupyterlabs complained about "npm" not being installed.
I therefore built npm from source and the installation proceeded without
any problems. Also, the npm command is in my path [3].

[1]
engelenvaart $ pip install .
Processing /data2/marberi/source/jupyterlab
  Requirement already satisfied (use --upgrade to upgrade): jupyterlab==0.5.1 from file:///data2/marberi/source/jupyterlab in /data2/marberi/anaconda/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): notebook>=4.2.0 in /data2/marberi/anaconda/lib/python2.7/site-packages (from jupyterlab==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): nbformat in /data2/marberi/anaconda/lib/python2.7/site-packages (from notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): tornado>=4 in /data2/marberi/anaconda/lib/python2.7/site-packages (from notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): terminado>=0.3.3; sys_platform != "win32" in /data2/marberi/anaconda/lib/python2.7/site-packages (from notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): jupyter-core in /data2/marberi/anaconda/lib/python2.7/site-packages (from notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): nbconvert in /data2/marberi/anaconda/lib/python2.7/site-packages (from notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): traitlets in /data2/marberi/anaconda/lib/python2.7/site-packages (from notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): ipython-genutils in /data2/marberi/anaconda/lib/python2.7/site-packages (from notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): ipykernel in /data2/marberi/anaconda/lib/python2.7/site-packages (from notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): jinja2 in /data2/marberi/anaconda/lib/python2.7/site-packages (from notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): jupyter-client in /data2/marberi/anaconda/lib/python2.7/site-packages (from notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): enum34; python_version == "2.7" in /data2/marberi/anaconda/lib/python2.7/site-packages (from traitlets->notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): six in /data2/marberi/anaconda/lib/python2.7/site-packages (from traitlets->notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): decorator in /data2/marberi/anaconda/lib/python2.7/site-packages (from traitlets->notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /data2/marberi/anaconda/lib/python2.7/site-packages (from jinja2->notebook>=4.2.0->jupyterlab==0.5.1)

[2]
# Testing forcing an upgrade

engelenvaart $ pip install . --upgrade
Processing /data2/marberi/source/jupyterlab
Requirement already up-to-date: notebook>=4.2.0 in /data2/marberi/anaconda/lib/python2.7/site-packages (from jupyterlab==0.5.1)
Collecting nbformat (from notebook>=4.2.0->jupyterlab==0.5.1)
  Downloading nbformat-4.1.0-py2.py3-none-any.whl (140kB)
    100% |████████████████████████████████| 143kB 1.8MB/s 
Collecting tornado>=4 (from notebook>=4.2.0->jupyterlab==0.5.1)
  Downloading tornado-4.4.2.tar.gz (460kB)
    100% |████████████████████████████████| 460kB 799kB/s 
Collecting terminado>=0.3.3; sys_platform != "win32" (from notebook>=4.2.0->jupyterlab==0.5.1)
  Downloading terminado-0.6.tar.gz
Collecting jupyter-core (from notebook>=4.2.0->jupyterlab==0.5.1)
  Downloading jupyter_core-4.2.0-py2.py3-none-any.whl (76kB)
    100% |████████████████████████████████| 81kB 2.1MB/s 
Collecting nbconvert (from notebook>=4.2.0->jupyterlab==0.5.1)
  Downloading nbconvert-4.2.0-py2.py3-none-any.whl (319kB)
    100% |████████████████████████████████| 327kB 1.0MB/s 
Requirement already up-to-date: traitlets in /data2/marberi/anaconda/lib/python2.7/site-packages (from notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already up-to-date: ipython-genutils in /data2/marberi/anaconda/lib/python2.7/site-packages (from notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already up-to-date: jinja2 in /data2/marberi/anaconda/lib/python2.7/site-packages (from notebook>=4.2.0->jupyterlab==0.5.1)
Collecting ipykernel (from notebook>=4.2.0->jupyterlab==0.5.1)
  Downloading ipykernel-4.5.0-py2.py3-none-any.whl (97kB)
    100% |████████████████████████████████| 102kB 2.4MB/s 
Collecting jupyter-client (from notebook>=4.2.0->jupyterlab==0.5.1)
  Downloading jupyter_client-4.4.0-py2.py3-none-any.whl (76kB)
    100% |████████████████████████████████| 81kB 2.2MB/s 
Collecting jsonschema!=2.5.0,>=2.0 (from nbformat->notebook>=4.2.0->jupyterlab==0.5.1)
  Downloading jsonschema-2.5.1-py2.py3-none-any.whl
Requirement already up-to-date: singledispatch in /data2/marberi/anaconda/lib/python2.7/site-packages (from tornado>=4->notebook>=4.2.0->jupyterlab==0.5.1)
Collecting certifi (from tornado>=4->notebook>=4.2.0->jupyterlab==0.5.1)
  Downloading certifi-2016.9.26-py2.py3-none-any.whl (377kB)
    100% |████████████████████████████████| 378kB 925kB/s 
Requirement already up-to-date: backports_abc>=0.4 in /data2/marberi/anaconda/lib/python2.7/site-packages (from tornado>=4->notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already up-to-date: ptyprocess in /data2/marberi/anaconda/lib/python2.7/site-packages (from terminado>=0.3.3; sys_platform != "win32"->notebook>=4.2.0->jupyterlab==0.5.1)
Collecting entrypoints (from nbconvert->notebook>=4.2.0->jupyterlab==0.5.1)
  Downloading entrypoints-0.2.2-py2.py3-none-any.whl
Requirement already up-to-date: pygments in /data2/marberi/anaconda/lib/python2.7/site-packages (from nbconvert->notebook>=4.2.0->jupyterlab==0.5.1)
Collecting mistune!=0.6 (from nbconvert->notebook>=4.2.0->jupyterlab==0.5.1)
  Downloading mistune-0.7.3-py2.py3-none-any.whl
Requirement already up-to-date: enum34; python_version == "2.7" in /data2/marberi/anaconda/lib/python2.7/site-packages (from traitlets->notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already up-to-date: six in /data2/marberi/anaconda/lib/python2.7/site-packages (from traitlets->notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already up-to-date: decorator in /data2/marberi/anaconda/lib/python2.7/site-packages (from traitlets->notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already up-to-date: MarkupSafe in /data2/marberi/anaconda/lib/python2.7/site-packages (from jinja2->notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already up-to-date: ipython>=4.0.0 in /data2/marberi/anaconda/lib/python2.7/site-packages (from ipykernel->notebook>=4.2.0->jupyterlab==0.5.1)
Collecting pyzmq>=13 (from jupyter-client->notebook>=4.2.0->jupyterlab==0.5.1)
  Downloading pyzmq-16.0.0-cp27-cp27mu-manylinux1_x86_64.whl (2.9MB)
    100% |████████████████████████████████| 2.9MB 152kB/s 
Collecting functools32; python_version == "2.7" (from jsonschema!=2.5.0,>=2.0->nbformat->notebook>=4.2.0->jupyterlab==0.5.1)
  Downloading functools32-3.2.3-2.zip
Collecting configparser>=3.5; python_version == "2.7" (from entrypoints->nbconvert->notebook>=4.2.0->jupyterlab==0.5.1)
  Downloading configparser-3.5.0.tar.gz
Requirement already up-to-date: prompt-toolkit<2.0.0,>=1.0.3 in /data2/marberi/anaconda/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel->notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already up-to-date: setuptools>=18.5 in /data2/marberi/anaconda/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel->notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already up-to-date: backports.shutil-get-terminal-size; python_version == "2.7" in /data2/marberi/anaconda/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel->notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already up-to-date: pickleshare in /data2/marberi/anaconda/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel->notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already up-to-date: pexpect; sys_platform != "win32" in /data2/marberi/anaconda/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel->notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already up-to-date: pathlib2; python_version == "2.7" or python_version == "3.3" in /data2/marberi/anaconda/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel->notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already up-to-date: simplegeneric>0.8 in /data2/marberi/anaconda/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel->notebook>=4.2.0->jupyterlab==0.5.1)
Requirement already up-to-date: wcwidth in /data2/marberi/anaconda/lib/python2.7/site-packages (from prompt-toolkit<2.0.0,>=1.0.3->ipython>=4.0.0->ipykernel->notebook>=4.2.0->jupyterlab==0.5.1)
Building wheels for collected packages: tornado, terminado, functools32, configparser
  Running setup.py bdist_wheel for tornado ... done
  Stored in directory: /home/marberi/.cache/pip/wheels/b3/db/47/46e05d1ee3ecfba252fcab42f0a156dab0df0cddf99fa0827c
  Running setup.py bdist_wheel for terminado ... done
  Stored in directory: /home/marberi/.cache/pip/wheels/3b/c2/ea/af635ffb63857a8c2ddd22da6a4b52f5b7ea3065db94ef5d7c
  Running setup.py bdist_wheel for functools32 ... done
  Stored in directory: /home/marberi/.cache/pip/wheels/3c/d0/09/cd78d0ff4d6cfecfbd730782a7815a4571cd2cd4d2ed6e69d9
  Running setup.py bdist_wheel for configparser ... done
  Stored in directory: /home/marberi/.cache/pip/wheels/1c/bd/b4/277af3f6c40645661b4cd1c21df26aca0f2e1e9714a1d4cda8
Successfully built tornado terminado functools32 configparser
Installing collected packages: jupyterlab, functools32, jsonschema, jupyter-core, nbformat, certifi, tornado, terminado, configparser, entrypoints, mistune, nbconvert, pyzmq, jupyter-client, ipykernel
  Found existing installation: jupyterlab 0.5.1
    Uninstalling jupyterlab-0.5.1:
      Successfully uninstalled jupyterlab-0.5.1
  Running setup.py install for jupyterlab ... /^[[done
  Found existing installation: jsonschema 2.4.0
    DEPRECATION: Uninstalling a distutils installed project (jsonschema) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling jsonschema-2.4.0:
      Successfully uninstalled jsonschema-2.4.0
  Found existing installation: jupyter-core 4.0.6
    DEPRECATION: Uninstalling a distutils installed project (jupyter-core) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling jupyter-core-4.0.6:
      Successfully uninstalled jupyter-core-4.0.6
  Found existing installation: nbformat 4.0.1
    DEPRECATION: Uninstalling a distutils installed project (nbformat) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling nbformat-4.0.1:
      Successfully uninstalled nbformat-4.0.1
  Found existing installation: certifi 14.5.14
    DEPRECATION: Uninstalling a distutils installed project (certifi) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling certifi-14.5.14:
      Successfully uninstalled certifi-14.5.14
  Found existing installation: tornado 4.3
    DEPRECATION: Uninstalling a distutils installed project (tornado) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling tornado-4.3:
      Successfully uninstalled tornado-4.3
  Found existing installation: terminado 0.5
    DEPRECATION: Uninstalling a distutils installed project (terminado) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling terminado-0.5:
      Successfully uninstalled terminado-0.5
  Found existing installation: mistune 0.7.1
    DEPRECATION: Uninstalling a distutils installed project (mistune) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling mistune-0.7.1:
      Successfully uninstalled mistune-0.7.1
  Found existing installation: nbconvert 4.1.0
    DEPRECATION: Uninstalling a distutils installed project (nbconvert) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling nbconvert-4.1.0:
      Successfully uninstalled nbconvert-4.1.0
  Found existing installation: pyzmq 15.1.0
    Uninstalling pyzmq-15.1.0:
      Successfully uninstalled pyzmq-15.1.0
  Found existing installation: jupyter-client 4.1.1
    DEPRECATION: Uninstalling a distutils installed project (jupyter-client) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling jupyter-client-4.1.1:
      Successfully uninstalled jupyter-client-4.1.1
  Found existing installation: ipykernel 4.2.2
    DEPRECATION: Uninstalling a distutils installed project (ipykernel) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling ipykernel-4.2.2:
      Successfully uninstalled ipykernel-4.2.2
Successfully installed certifi-2016.9.26 configparser-3.5.0 entrypoints-0.2.2 functools32-3.2.3.post2 ipykernel-4.5.0 jsonschema-2.5.1 jupyter-client-4.4.0 jupyter-core-4.2.0 jupyterlab-0.5.1 mistune-0.7.3 nbconvert-4.2.0 nbformat-4.1.0 pyzmq-16.0.0 terminado-0.6 tornado-4.4.2

[3]
engelenvaart $ which npm
/data2/marberi/bin/npm

engelenvaart $ npm --version
2.15.9

**Comment by jasongrout** [comment] 2016-10-19 23:26
Can we start fresh, and get the log from a clean checkout? And even better, can you do the following in the clean checkout:

```
node --version
npm install
npm run build:all
pip install .
```

to make sure we get the npm logs? For some reason, it seems that npm isn't building only one of the webpack bundles, which seems really odd.

**Comment by juliohm** [comment] 2016-10-20 05:45
I have installed jupyterlabs with pip following the instructions in the README:

```bash
pip install --user jupyterlab
jupyter serverextension enable --py jupyterlab
```

No error messages were displayed. However, when I try to start the lab, the command is not recognized:

```bash
jupyter lab
```
>jupyter: 'lab' is not a Jupyter command

Could you please guide me on how to fix this? I am looking forward to give JupyterLab a try.

**Comment by marberi** [comment] 2016-10-20 12:39
@juliohm Unless this is the same installation problem, could you open your question in another issue? It just makes the discussion simpler if not having all installation issues in a gigantic thread.

**Comment by marberi** [comment] 2016-10-20 12:46
I have deleted the old repository and made a new clone. The npm
version is

engelenvaart $ node --version
v4.6.0

and the output can be found in

npm install - npm_install.txt
npm run build:all - npm_build.txt

together with a npm debug file in npm-debug.log.txt . The problem is
occuring because a JavaScript file can not find the module 'supports-color'.
Is this a recently added dependency which all developers have installed
at their computers?

[npm-debug.log.txt](https://github.com/jupyterlab/jupyterlab/files/541690/npm-debug.log.txt)
[npm_build.txt](https://github.com/jupyterlab/jupyterlab/files/541688/npm_build.txt)
[npm_install.txt](https://github.com/jupyterlab/jupyterlab/files/541691/npm_install.txt)
[git_clone.txt](https://github.com/jupyterlab/jupyterlab/files/541689/git_clone.txt)

**Comment by juliohm** [comment] 2016-10-20 16:23
@marberi the issue has lots of overlap, that is I why I commented here, anyways, opening another one.

**Comment by marberi** [comment] 2016-10-20 21:44
@juliohm Ok. For me the error showed in the "npm run build:all" command
and running "npm install supports-color" appears to have fixed the problem. The 
building stages finish successfully, but have need to test connecting to the server from the office tomorrow.

**Comment by blink1073** [comment] 2016-10-20 22:32
Ah, it looks like that package may need to be an explicit dependency of our extension builder, I opened https://github.com/jupyterlab/extension-builder/issues/33 to track this.

**Comment by jasongrout** [comment] 2016-10-21 13:52
Closing the issue here, since it's being tracked over on the extension builder repo.

**Comment by jasongrout** [comment] 2016-10-21 14:43
Actually, we need to upgrade to that version of the extension builder, so re-opening for that change to this repo.

**Closed** 2016-10-25 18:45 UTC
Labels: component:Build System, in progress, type:Bug

**Comment by Afshintronic** [comment] 2018-02-22 08:43
Hi,

I have the same problem. when I launch jupyter lab from anaconda, '404 the page does not exist' shows up. I have enabled the server extension and I still have the same problem. Would you please help me figure this out?

**Comment by blink1073** [comment] 2018-02-22 15:10
Hi @marberi, when you run `conda list`, what does it show in the `jupyterlab` line?

**Comment by marberi** [comment] 2018-02-22 15:40
@blink1073, the user @Afshintronic opened an old thread. My problem eventually
got resolved.

**Comment by blink1073** [comment] 2018-02-22 17:53
Right, sorry, @Afshintronic, when you run `conda list`, what does it show in the `jupyterlab` line?

**Comment by Afshintronic** [comment] 2018-02-23 07:37
@blink1073 thanks for the response. the problem is solved now. I just upgraded jupyterlab and now it's working. thanks for the response though

**Comment by zizzipupp** [comment] 2018-03-06 15:12
@blink1073 I have the same 404 problem. When I run `conda list` this is what I get:

```
jupyterlab                      0.31.4                   py27_0    conda-forge
jupyterlab_launcher       0.10.2                   py27_0
```

**Comment by blink1073** [comment] 2018-03-06 16:57
Hi @zizzipupp, upgrading to a newer `jupyterlab` should fix the problem.
