### ISSUE TITLE
Attach images to Markdown cells via Drag'n'Drop

### ISSUE THREAD

**Issue by kolibril13** [jupyterlab/jupyterlab#15615] opened 2024-01-07 18:04 UTC
In Jupyter VS Code, I can paste an image into a markdown cell via Drag'n'Drop, and it will show up as an attached image.
It would be great to have this Drag'n'Drop feature as well in JLab! 

https://github.com/jupyterlab/jupyterlab/assets/44469195/50e1985a-0587-4fea-9c6e-c941233c7701

after Drag'n'Drop the notebook JSON looks like this. Note the extra part  `attachments": { "cute_dog.jpg": {....` )
<img width="560" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/44469195/5f23c846-38ce-4fed-914a-04061edd7f77">

**Comment by JasonWeill** [comment] 2024-01-08 23:50
@kolibril13 Thanks for opening this issue! Were you envisioning dragging a file from the file browser in the left panel, or from another window (such as Windows Explorer, macOS Finder, or other programs) to add it to your notebook?

**Comment by kolibril13** [comment] 2024-01-09 13:16
Thanks for your reply,

I was firstly thinking about dragging a file from the file browser in the left panel.

But from another window, and even pasting from the clipboard would be great as well! (VS Code notebooks already supports both these options)

**Comment by krassowski** [comment] 2024-01-09 15:40
> But from another window, and even pasting from the clipboard would be great as well! 

Dragging from another window which and pasting from clipboard should just work in JupyterLab. I confirmed with 4.0.9 on Ubuntu with Chrome but these worked basically forever; if it does not work for you please provide more details.

> dragging a file from the file browser in the left panel

Indeed, this does not work as proposed, instead it shows drop areas to open the graphics file.

**Comment by JasonWeill** [comment] 2024-01-09 17:43
I was just able to drag an image from the macOS Finder (13.6.3 "Ventura") into a markdown cell in edit mode, and JupyterLab created an attachment and rendered it when I rendered the markdown cell with SHIFT+ENTER. Do you see the same behavior when your markdown cell is in edit mode?

**Comment by JasonWeill** [comment] 2024-01-09 18:38
Closing because this feature is currently in place; please open other enhancements to help improve it. Thanks!

**Closed by JasonWeill** 2024-01-09 18:38 UTC
Labels: enhancement, status:Needs Info, status:Needs Triage
