### ISSUE TITLE
Can't open a directory named "checkpoints"

### ISSUE THREAD

**Issue by guoreex** [jupyterlab/jupyterlab#15264] opened 2023-10-12 09:02 UTC
## Reproduce
无法打开 checkpoints 文件夹

![image](https://github.com/jupyterlab/jupyterlab/assets/125869801/8a0f61be-ffd6-44b9-9cb0-9f6cb9079853)

1. open IP:8888/lab
2. Double-click on folder name 'checkpoints'
3. Nothing happened, checkpoints Not open.

## Expected behavior
I saw that this problem existed in 2022.
https://github.com/jupyterlab/jupyterlab/issues/12408

## Context
How can I solve this problem? I need to open the checkpoints folder normally in the lab.

$ jupyter --version
Selected Jupyter core packages...
IPython          : 8.16.1
ipykernel        : 6.25.2
ipywidgets       : 8.1.1
jupyter_client   : 8.4.0
jupyter_core     : 5.4.0
jupyter_server   : 2.7.3
jupyterlab       : 4.0.7
nbclient         : 0.8.0
nbconvert        : 7.9.2
nbformat         : 5.9.2
notebook         : 7.0.5
qtconsole        : 5.4.4
traitlets        : 5.11.2

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        /home/ubuntu/.local/bin
        /home/ubuntu/.local/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin
        /usr/games
        /usr/local/games
        /snap/bin

sys.path:
        /home/ubuntu/.local/bin
        /usr/lib/python310.zip
        /usr/lib/python3.10
        /usr/lib/python3.10/lib-dynload
        /home/ubuntu/.local/lib/python3.10/site-packages
        /usr/local/lib/python3.10/dist-packages
        /usr/lib/python3/dist-packages

sys.executable:
        /usr/bin/python3

sys.version:
        3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

platform.platform():
        Linux-5.15.0-76-generic-x86_64-with-glibc2.35

which -a jupyter:
        /home/ubuntu/.local/bin/jupyter
        /home/ubuntu/.local/bin/jupyter
        /usr/local/bin/jupyter

pip list:
        Package                   Version
        ------------------------- -------------
        anyio                     4.0.0
        argon2-cffi               23.1.0
        argon2-cffi-bindings      21.2.0
        arrow                     1.2.3
        asttokens                 2.4.0
        async-lru                 2.0.4
        attrs                     23.1.0
        Automat                   20.2.0
        Babel                     2.12.1
        backcall                  0.2.0
        bcrypt                    3.2.0
        beautifulsoup4            4.12.2
        bleach                    6.0.0
        blinker                   1.4
        certifi                   2023.7.22
        cffi                      1.15.1
        chardet                   4.0.0
        charset-normalizer        3.2.0
        click                     8.0.3
        cmake                     3.27.2
        colorama                  0.4.4
        comm                      0.1.4
        command-not-found         0.3
        configobj                 5.0.6
        constantly                15.1.0
        cryptography              3.4.8
        dbus-python               1.2.18
        debugpy                   1.7.0
        decorator                 5.1.1
        defusedxml                0.7.1
        distlib                   0.3.7
        distro                    1.7.0
        distro-info               1.1build1
        exceptiongroup            1.1.3
        executing                 1.2.0
        fastjsonschema            2.18.0
        filelock                  3.12.2
        fqdn                      1.5.1
        httplib2                  0.20.2
        hyperlink                 21.0.0
        idna                      3.3
        importlib-metadata        4.6.4
        incremental               21.3.0
        ipykernel                 6.25.2
        ipython                   8.16.1
        ipython-genutils          0.2.0
        ipywidgets                8.1.1
        isoduration               20.11.0
        jedi                      0.19.0
        jeepney                   0.7.1
        Jinja2                    3.1.2
        json5                     0.9.14
        jsonpointer               2.4
        jsonschema                4.19.0
        jsonschema-specifications 2023.7.1
        jupyter                   1.0.0
        jupyter_client            8.4.0
        jupyter-console           6.6.3
        jupyter_core              5.4.0
        jupyter-events            0.7.0
        jupyter-lsp               2.2.0
        jupyter_server            2.7.3
        jupyter_server_terminals  0.4.4
        jupyterlab                4.0.7
        jupyterlab-pygments       0.2.2
        jupyterlab_server         2.24.0
        jupyterlab-widgets        3.0.9
        keyring                   23.5.0
        launchpadlib              1.10.16
        lazr.restfulclient        0.14.4
        lazr.uri                  1.0.6
        lit                       16.0.6
        MarkupSafe                2.1.3
        matplotlib-inline         0.1.6
        mistune                   3.0.1
        more-itertools            8.10.0
        mpmath                    1.3.0
        nbclient                  0.8.0
        nbconvert                 7.9.2
        nbformat                  5.9.2
        nest-asyncio              1.5.7
        netifaces                 0.11.0
        networkx                  3.1
        notebook                  7.0.5
        notebook_shim             0.2.3
        numpy                     1.25.2
        oauthlib                  3.2.0
        overrides                 7.4.0
        packaging                 23.1
        pandocfilters             1.5.0
        parso                     0.8.3
        pexpect                   4.8.0
        pickleshare               0.7.5
        Pillow                    10.0.0
        pip                       22.0.2
        platformdirs              3.10.0
        prometheus-client         0.17.1
        prompt-toolkit            3.0.39
        psutil                    5.9.5
        ptyprocess                0.7.0
        pure-eval                 0.2.2
        pyasn1                    0.4.8
        pyasn1-modules            0.2.1
        pycparser                 2.21
        Pygments                  2.16.1
        PyGObject                 3.42.0
        PyHamcrest                2.0.2
        PyJWT                     2.3.0
        pyOpenSSL                 21.0.0
        pyparsing                 2.4.7
        pyserial                  3.5
        python-apt                2.3.0+ubuntu2
        python-dateutil           2.8.2
        python-debian             0.1.43ubuntu1
        python-json-logger        2.0.7
        python-magic              0.4.24
        PyYAML                    5.4.1
        pyzmq                     25.1.1
        qtconsole                 5.4.4
        QtPy                      2.4.0
        referencing               0.30.2
        requests                  2.31.0
        rfc3339-validator         0.1.4
        rfc3986-validator         0.1.1
        rpds-py                   0.10.2
        SecretStorage             3.3.1
        Send2Trash                1.8.2
        service-identity          18.1.0
        setuptools                59.6.0
        six                       1.16.0
        sniffio                   1.3.0
        sos                       4.4
        soupsieve                 2.5
        ssh-import-id             5.11
        stack-data                0.6.2
        sympy                     1.12
        systemd-python            234
        terminado                 0.17.1
        tinycss2                  1.2.1
        tomli                     2.0.1
        torch                     2.0.1+cu118
        torchaudio                2.0.2+cu118
        torchvision               0.15.2+cu118
        tornado                   6.3.3
        traitlets                 5.11.2
        triton                    2.0.0
        Twisted                   22.1.0
        typing_extensions         4.7.1
        ubuntu-advantage-tools    27.7
        ubuntu-drivers-common     0.0.0
        ufw                       0.36.1
        unattended-upgrades       0.1
        uri-template              1.3.0
        urllib3                   2.0.4
        virtualenv                20.24.3
        wadllib                   1.3.6
        wcwidth                   0.2.6
        webcolors                 1.13
        webencodings              0.5.1
        websocket-client          1.6.3
        wheel                     0.37.1
        widgetsnbextension        4.0.9
        xformers                  0.0.21
        xkit                      0.0.0
        zipp                      1.0.0
        zope.interface            5.4.0
</pre>
</details>

**Comment by krassowski** [comment] 2023-10-13 08:29
Thank you for opening this issue. Since this is a duplicate of #12408 I will close it. Please note that the problem is in jupyter-server, not in JupyterLab itself and would need addressing over there. Thank you!

**Closed by krassowski** 2023-10-13 08:29 UTC
Labels: bug, status:Duplicate, status:Needs Triage

**Comment by guoreex** [comment] 2023-10-17 14:06
thx
