### ISSUE TITLE
Opening a notebook now fails, since at least 1.0.0a10

### ISSUE THREAD

**Issue by athornton** [jupyterlab/jupyterlab#6697] opened 2019-06-24 22:03 UTC
Hi! Thanks for using JupyterLab.

If you are reporting an issue with JupyterLab, please use the [GitHub issue](https://github.com/jupyterlab/jupyterlab/issues) search feature to check if your issue has been asked already. If it has, please add your comments to the existing issue.

The JupyterLab team and Project Jupyter value our community, and JupyterLab
follows the Jupyter [Community Guides](https://jupyter.readthedocs.io/en/latest/community/content-community.html).

**Describe the bug**

Opening a notebook has no effect (from the user's perspective) and throws an error in the Javascript console.

**To Reproduce**

1. Try to open a notebook from the filebrowser.

or

1. Select a notebook in the filebrowser, and right-click, Open.

**Expected behavior**
The notebook opens in a tab.

**Desktop (please complete the following information):**

- OS: MacOS Mojave 10.14.5
- Browser [e.g. chrome 69.0, firefox 62.0]
- JupyterLab [e.g. 0.34.2]

**Additional context**

```
plugin.js:31 Uncaught TypeError: Cannot read property 'addFactory' of undefined
    at NBWidgetExtension.createNew (plugin.js:31)
    at widgetmanager.js:75
    at each (iter.js:60)
    at DocumentWidgetManager._initializeWidget (widgetmanager.js:74)
    at DocumentWidgetManager.createWidget (widgetmanager.js:61)
    at DocumentManager._createOrOpenDocument (manager.js:442)
    at DocumentManager.open (manager.js:264)
    at DocumentManager.openOrReveal (manager.js:288)
    at DirListing._handleOpen (listing.js:822)
    at DirListing._evtDblClick (listing.js:898)
    at DirListing.handleEvent (listing.js:543)
```

(double-click from file manager)

```
plugin.js:31 Uncaught (in promise) TypeError: Cannot read property 'addFactory' of undefined
    at NBWidgetExtension.createNew (plugin.js:31)
    at widgetmanager.js:75
    at each (iter.js:60)
    at DocumentWidgetManager._initializeWidget (widgetmanager.js:74)
    at DocumentWidgetManager.createWidget (widgetmanager.js:61)
    at DocumentManager._createOrOpenDocument (manager.js:442)
    at DocumentManager.open (manager.js:264)
    at DocumentManager.openOrReveal (manager.js:288)
    at index.js:227
    at async Promise.all (/nb/user/athornto/index 0)
```

(right-click then Open)

Things that are not .ipynb seem to work OK (e.g. .py files, .md files).

If available, please include the following details:

<details><summary>Troubleshoot Output</summary>
<pre>
[athornto@nb-athornto-d-2019-06-24 ~]$ jupyter troubleshoot
$PATH:
        /home/athornto/bin
        /home/athornto/.local/bin
        /usr/local/texlive/2018/bin/x86_64-linux
        /usr/local/bin
        /opt/rh/devtoolset-6/root/usr/bin
        /opt/rh/rh-git29/root/usr/bin
        /home/athornto/bin
        /home/athornto/.local/bin
        /usr/local/texlive/2018/bin/x86_64-linux
        /usr/local/bin
        /sbin
        /bin
        /usr/sbin
        /usr/bin

sys.path:
        /usr/local/bin
        /opt/rh/devtoolset-6/root/usr/lib64/python2.7/site-packages
        /opt/rh/devtoolset-6/root/usr/lib/python2.7/site-packages
        /usr/lib64/python36.zip
        /usr/lib64/python3.6
        /usr/lib64/python3.6/lib-dynload
        /usr/local/lib64/python3.6/site-packages
        /usr/local/lib64/python3.6/site-packages/Cartopy-0.17.0-py3.6-linux-x86_64.egg
        /usr/local/lib/python3.6/site-packages
        /usr/share/git/ipyaladin
        /usr/share/git/dask-labextension
        /usr/lib64/python3.6/site-packages
        /usr/lib/python3.6/site-packages

sys.executable:
        /usr/bin/python3

sys.version:
        3.6.8 (default, Apr 25 2019, 21:02:35) 
        [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

platform.platform():
        Linux-3.10.0-957.10.1.el7.x86_64-x86_64-with-centos-7.6.1810-Core

which -a jupyter:
        /usr/local/bin/jupyter
        /usr/local/bin/jupyter

pip list:
        Package                    Version     Location                        
        -------------------------- ----------- --------------------------------
        aiohttp                    4.0.0a0     
        alembic                    1.0.10      
        ansiwrap                   0.8.4       
        aplus                      0.11.0      
        asn1crypto                 0.24.0      
        astropy                    3.2.1       
        astroquery                 0.3.10.dev0 
        async-generator            1.10        
        async-timeout              3.0.1       
        atomicwrites               1.3.0       
        attrs                      19.1.0      
        backcall                   0.1.0       
        beautifulsoup4             4.7.1       
        bleach                     3.1.0       
        bokeh                      1.2.0       
        boto3                      1.9.174     
        botocore                   1.12.174    
        bqplot                     0.12.0a1    
        branca                     0.3.1       
        cachetools                 3.1.1       
        Cartopy                    0.17.0      
        certifi                    2019.6.16   
        certipy                    0.1.3       
        cffi                       1.12.3      
        chardet                    3.0.4       
        Click                      7.0         
        click-plugins              1.1.1       
        cligj                      0.5.0       
        cloudpickle                1.2.1       
        colorcet                   2.0.1       
        coverage                   5.0a5       
        cryptography               2.7         
        cycler                     0.10.0      
        Cython                     0.29.10     
        dask                       1.2.2       
        dask-kubernetes            0.8.0       
        dask-labextension          0.4.0a1     /usr/share/git/dask-labextension
        datashader                 0.7.0       
        datashape                  0.5.2       
        decorator                  4.4.0       
        defusedxml                 0.6.0       
        distributed                1.28.1      
        docutils                   0.14        
        entrypoints                0.3         
        fastparquet                0.3.1       
        Fiona                      1.8.6       
        firefly-client             2.1.1       
        future                     0.17.1      
        geopandas                  0.5.0       
        ginga                      2.7.2       
        google-auth                1.6.3       
        graphviz                   0.11        
        h5py                       2.9.0       
        healpy                     1.12.9      
        HeapDict                   1.0.0       
        holoviews                  1.12.3      
        html5lib                   1.0.1       
        idna                       2.8         
        idna-ssl                   1.1.0       
        imageio                    2.5.0       
        importlib-metadata         0.18        
        ipyaladin                  0.1.5       /usr/share/git/ipyaladin        
        ipydatawidgets             4.0.0       
        ipyevents                  0.5.0       
        ipykernel                  5.1.1       
        ipyleaflet                 0.10.5      
        ipympl                     0.2.1       
        ipython                    7.5.0       
        ipython-genutils           0.2.0       
        ipyvolume                  0.5.1       
        ipywebrtc                  0.4.3       
        ipywidgets                 7.4.2       
        jedi                       0.14.0      
        jeepney                    0.4         
        Jinja2                     2.10.1      
        jmespath                   0.9.4       
        jsonschema                 3.0.1       
        jupyter-client             5.2.4       
        jupyter-core               4.5.0       
        jupyter-firefly-extensions 0.2.6       
        jupyter-server-proxy       1.1.0       
        jupyterhub                 1.0.0       
        jupyterlab                 1.0.0rc0    
        jupyterlab-lsstquery       1.0.0a6     
        jupyterlab-server          1.0.0rc0    
        jupyterlabutils            0.0.13      
        kapteyn                    2.3.1       
        keyring                    19.0.2      
        kiwisolver                 1.1.0       
        kubernetes                 10.0.0a1    
        llvmlite                   0.29.0      
        locket                     0.2.0       
        Mako                       1.0.12      
        maproxy                    0.0.12      
        Markdown                   3.1.1       
        MarkupSafe                 1.1.1       
        matplotlib                 3.1.0       
        mimeparse                  0.1.3       
        mistune                    0.8.4       
        mock                       3.0.5       
        more-itertools             7.0.0       
        msgpack                    0.6.1       
        multidict                  4.5.2       
        multipledispatch           0.6.0       
        munch                      2.3.2       
        mysqlclient                1.4.2.post1 
        nbconvert                  5.5.0       
        nbformat                   4.4.0       
        nbval                      0.9.1       
        nclib                      1.0.0rc3    
        networkx                   2.3         
        notebook                   5.7.8       
        numba                      0.44.1      
        numexpr                    2.6.9       
        numpy                      1.16.4      
        oauthlib                   3.0.1       
        packaging                  19.0        
        pamela                     1.0.0       
        pandas                     0.24.2      
        pandocfilters              1.4.2       
        panel                      0.6.0       
        papermill                  1.0.1       
        param                      1.9.1       
        paramnb                    2.0.4       
        parso                      0.5.0       
        partd                      0.3.10      
        pbr                        5.3.1       
        pexpect                    4.7.0       
        pickleshare                0.7.5       
        Pillow                     6.0.0       
        pip                        19.1.1      
        pipenv                     2018.11.26  
        pluggy                     0.12.0      
        progressbar2               3.42.0      
        prometheus-client          0.7.1       
        prompt-toolkit             2.0.9       
        psutil                     5.6.3       
        ptyprocess                 0.6.0       
        py                         1.8.0       
        pyarrow                    0.13.0      
        pyasn1                     0.4.5       
        pyasn1-modules             0.2.5       
        pycparser                  2.19        
        pyct                       0.4.6       
        Pygments                   2.4.2       
        pyOpenSSL                  19.0.0      
        pypandoc                   1.4         
        pyparsing                  2.4.0       
        pyproj                     2.2.0       
        pyrsistent                 0.15.2      
        pyshp                      2.1.0       
        pytest                     4.6.3       
        python-dateutil            2.8.0       
        python-editor              1.0.4       
        python-snappy              0.5.4       
        python-utils               2.3.0       
        pythreejs                  2.1.0       
        pytz                       2019.1      
        pyviz-comms                0.7.2       
        pyvo                       0.9.3       
        PyWavelets                 1.0.3       
        PyYAML                     5.1.1       
        pyzmq                      18.0.1      
        QtPy                       1.8.0       
        requests                   2.22.0      
        requests-oauthlib          1.2.0       
        rsa                        4.0         
        s3fs                       0.2.1       
        s3transfer                 0.2.1       
        scikit-image               0.15.0      
        scipy                      1.3.0       
        SecretStorage              3.1.1       
        Send2Trash                 1.5.0       
        setuptools                 41.0.1      
        Shapely                    1.7a2       
        simpervisor                0.3         
        six                        1.12.0      
        sortedcontainers           2.1.0       
        soupsieve                  1.9.2       
        SQLAlchemy                 1.3.5       
        stevedore                  1.30.1      
        tables                     3.5.2       
        tabulate                   0.8.3       
        tblib                      1.4.0       
        tenacity                   5.0.4       
        terminado                  0.8.2       
        testpath                   0.3.1       
        textwrap3                  0.9.2       
        thrift                     0.11.0      
        toolz                      0.9.0       
        tornado                    5.1.1       
        tqdm                       4.32.2      
        traitlets                  4.3.2       
        traittypes                 0.2.1       
        typing-extensions          3.7.4       
        urllib3                    1.25.3      
        vaex-arrow                 0.3.2       
        vaex-astro                 0.4.0       
        vaex-core                  0.8.1       
        vaex-distributed           0.3.0       
        vaex-hdf5                  0.5.1       
        vaex-jupyter               0.2.3       
        vaex-server                0.2.1       
        vaex-viz                   0.3.3       
        virtualenv                 16.6.1      
        virtualenv-clone           0.5.3       
        virtualenvwrapper          4.8.4       
        wcwidth                    0.1.7       
        webencodings               0.5.1       
        websocket-client           0.56.0      
        wheel                      0.33.4      
        widgetsnbextension         3.4.2       
        ws4py                      0.5.1       
        xarray                     0.12.1      
        yarl                       1.3.0       
        zict                       0.1.4       
        zipp                       0.5.1
</pre>
</details>

<details><summary>Command Line Output</summary>
Difficult to retrieve, and nothing out of the ordinary.
</details>

<details><summary>Browser Output</summary>
See above for relevant details
</details>

<details><summary>JupyterLab extensions</summary>
<pre>
[athornto@nb-athornto-d-2019-06-24 ~]$ jupyter labextension list
JupyterLab v1.0.0rc0
Known labextensions:
   app dir: /usr/local/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v0.39.1  enabled  OK
        @jupyterlab/celltags v0.1.5  enabled  OK
        @jupyterlab/toc v1.0.0-rc.0  enabled  OK
        @lsst-sqre/jupyterlab-lsstquery v1.0.0-alpha.6  enabled  OK
        @lsst-sqre/jupyterlab-savequit v1.0.0-alpha.7  enabled  OK
        @pyviz/jupyterlab_pyviz v0.8.0-alpha.1  enabled  OK
        bqplot v0.4.5  enabled  OK
        dask-labextension v0.4.0-pre.6  enabled  OK*
        ipyaladin v0.1.5  enabled  OK*
        ipyevents v1.5.0  enabled  OK
        ipyvolume v0.5.1  enabled  OK
        jupyter-matplotlib v0.3.0  enabled  OK
        jupyter-threejs v2.1.0  enabled  OK
        jupyter_firefly_extensions v0.2.6  enabled  OK
        jupyterlab-datawidgets v6.1.0  enabled  OK
        jupyterlab-server-proxy v1.0.1  enabled  OK*
        jupyterlab_bokeh v1.0.0-alpha.7  enabled  OK*

   local extensions:
        dask-labextension: /usr/share/git/dask-labextension
        ipyaladin: /usr/share/git/ipyaladin/js
        jupyterlab-server-proxy: /usr/share/git/jupyter-server-proxy/jupyterlab-server-proxy
        jupyterlab_bokeh: /usr/share/git/jupyterlab_bokeh
</pre>
</details>

**Comment by athornton** [comment] 2019-06-24 22:05
Also, notebooks that were already open (that is, that come up as part of the saved layout from previous sessions) seem to work fine.

**Comment by telamonian** [comment] 2019-06-24 22:25
Weird/annoying. I haven't seen this particular issue in my own environment, but I have run into about a zillion similar issues in the last few weeks. With all of the rapid-fire changes gearing up for the release of v1.0 I think that the dev build is breaking w.r.t. itself all of the time right now. There are three things I've done that have usually fixed the issue:

- Try rerunning `pip install -e .` in your jlab repo.

- Update [jupyterlab/jupyterlab_server](https://github.com/jupyterlab/jupyterlab_server) to the latest HEAD (ie clone it and do a dev install: `pip install -e .`).

- If all else fails, try the nuclear option: clean your `jupyterlab` repo and then rebuild. Unfortunately, it seems like the only way to reliably clean the repo right now is to completely delete it and then start from a fresh clone:
     - easy way: 
        ```bash
        rm -rf jupyterlab
        git clone https://github.com/jupyterlab/jupyterlab.git
        cd jupyterlab
        pip install -e .
        ...
        ```
     - more complex way, will retain any commits you've made:
        ```bash
        mv jupyterlab old_jupyterlab
        git clone old_jupyterlab jupyterlab
        rm -rf old_jupyterlab
        cd jupyterlab
        git remote set-url origin https://github.com/jupyterlab/jupyterlab.git
        pip install -e .
        ...
        ```

**Comment by athornton** [comment] 2019-06-24 22:35
I have generally been trying to avoid git master from Jupyterlab, relying on PyPi versions, but I can certainly give master a whirl and see if anything changes.

**Comment by telamonian** [comment] 2019-06-24 22:38
If you're relying on what's on PyPi, definitely try updating `jupyterlab_server` first and see what happens.

**Comment by athornton** [comment] 2019-06-25 22:51
I've narrowed it down to the two extensions @pyviz/jupyterlab_pyviz and @jupyter-widgets/jupyterlab-manager which is...well, know I know which two extensions are having problems, but the bad news is I can't really live without at least the widget manager.

**Comment by jasongrout** [comment] 2019-06-25 22:58
The widget manager was updated for 1.0RC in https://github.com/jupyter-widgets/ipywidgets/pull/2456 (which has not been released yet). CC @SylvainCorlay, who is doing the ipywidgets release.

**Comment by david-waterworth** [comment] 2019-06-25 23:02
I reported this as well, the main problem I see is that even though the widget manager will be updated to fix it, if users upgrade from a pre-1.0 version without first updating jupyter-widgets/ipywidgets to a 1.0 compatible the end result is a broken install. Is there any way of disabling extensions at upgrade which are known to not be compatible?

**Comment by jasongrout** [comment] 2019-06-25 23:10
> Is there any way of disabling extensions at upgrade which are known to not be compatible (automatically, users who are aware of the issues don't need this step)?

Very good point. If lab builds, it should maybe ignore incompatible plugins with a big error or something, or refuse to build?

**Comment by athornton** [comment] 2019-06-25 23:17
The problem is, I don't think it recognizes it as incompatible.

**Comment by athornton** [comment] 2019-06-25 23:22
`npm run build` of widgets-master doesn't look great:

```
src/manager-base.ts(5,27): error TS2307: Cannot find module '@jupyterlab/services'.
src/manager-base.ts(166,41): error TS2339: Property 'get' does not exist on type 'WidgetModel'.
src/manager-base.ts(167,23): error TS2339: Property 'get' does not exist on type 'WidgetModel'.
src/manager-base.ts(168,23): error TS2339: Property 'get' does not exist on type 'WidgetModel'.
src/manager-base.ts(174,22): error TS2339: Property 'listenTo' does not exist on type 'WidgetView'.
src/manager-base.ts(221,47): error TS7006: Parameter 'b' implicitly has an 'any' type.
src/manager-base.ts(297,19): error TS2339: Property 'once' does not exist on type 'WidgetModel'.
src/manager-base.ts(360,42): error TS2554: Expected 0 arguments, but got 2.
src/manager-base.ts(579,41): error TS2339: Property 'get' does not exist on type 'WidgetModel'.
src/nativeview.ts(35,27): error TS2307: Cannot find module 'backbone'.
src/nativeview.ts(68,16): error TS2339: Property 'el' does not exist on type 'NativeView<T>'.
src/nativeview.ts(69,16): error TS2339: Property 'el' does not exist on type 'NativeView<T>'.
src/nativeview.ts(69,47): error TS2339: Property 'el' does not exist on type 'NativeView<T>'.
src/nativeview.ts(75,14): error TS2339: Property 'el' does not exist on type 'NativeView<T>'.
src/nativeview.ts(82,22): error TS2339: Property 'el' does not exist on type 'NativeView<T>'.
src/nativeview.ts(82,32): error TS2339: Property 'el' does not exist on type 'NativeView<T>'.
src/nativeview.ts(82,62): error TS2339: Property 'el' does not exist on type 'NativeView<T>'.
src/nativeview.ts(113,23): error TS2339: Property 'el' does not exist on type 'NativeView<T>'.
src/nativeview.ts(128,12): error TS2339: Property 'el' does not exist on type 'NativeView<T>'.
src/nativeview.ts(141,16): error TS2339: Property 'el' does not exist on type 'NativeView<T>'.
src/nativeview.ts(155,16): error TS2339: Property 'el' does not exist on type 'NativeView<T>'.
src/nativeview.ts(164,16): error TS2339: Property 'el' does not exist on type 'NativeView<T>'.
src/nativeview.ts(168,16): error TS2339: Property 'el' does not exist on type 'NativeView<T>'.
src/services-shim.ts(12,8): error TS2307: Cannot find module '@jupyterlab/services'.
src/services-shim.ts(125,18): error TS7006: Parameter 'jsServicesComm' implicitly has an 'any' type.
src/services-shim.ts(125,34): error TS7006: Parameter 'msg' implicitly has an 'any' type.
src/services-shim.ts(256,47): error TS7006: Parameter 'msg' implicitly has an 'any' type.
src/services-shim.ts(263,47): error TS7006: Parameter 'msg' implicitly has an 'any' type.
src/services-shim.ts(269,47): error TS7006: Parameter 'msg' implicitly has an 'any' type.
src/utils.ts(6,8): error TS7016: Could not find a declaration file for module 'base64-js'. '/Users/adam/git/ipywidgets/node_modules/base64-js/index.js' implicitly has an 'any' type.
  Try `npm install @types/base64-js` if it exists or add a new declaration (.d.ts) file containing `declare module 'base64-js';`
src/utils.ts(12,22): error TS7016: Could not find a declaration file for module 'lodash/isEqual'. '/Users/adam/git/ipywidgets/node_modules/lodash/isEqual.js' implicitly has an 'any' type.
  Try `npm install @types/lodash` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash/isEqual';`
src/utils.ts(13,27): error TS7016: Could not find a declaration file for module 'lodash/isPlainObject'. '/Users/adam/git/ipywidgets/node_modules/lodash/isPlainObject.js' implicitly has an 'any' type.
  Try `npm install @types/lodash` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash/isPlainObject';`
src/widget.ts(8,27): error TS2307: Cannot find module 'backbone'.
src/widget.ts(9,15): error TS2307: Cannot find module 'jquery'.
src/widget.ts(17,8): error TS2307: Cannot find module '@phosphor/widgets'.
src/widget.ts(21,8): error TS2307: Cannot find module '@phosphor/messaging'.
src/widget.ts(33,8): error TS2307: Cannot find module '@jupyterlab/services'.
src/widget.ts(155,14): error TS2339: Property 'trigger' does not exist on type 'WidgetModel'.
src/widget.ts(184,14): error TS2339: Property 'stopListening' does not exist on type 'WidgetModel'.
src/widget.ts(185,14): error TS2339: Property 'trigger' does not exist on type 'WidgetModel'.
src/widget.ts(201,14): error TS2339: Property 'trigger' does not exist on type 'WidgetModel'.
src/widget.ts(219,63): error TS7006: Parameter 'b' implicitly has an 'any' type.
src/widget.ts(234,22): error TS2339: Property 'trigger' does not exist on type 'WidgetModel'.
src/widget.ts(262,30): error TS2339: Property 'attributes' does not exist on type 'WidgetModel'.
src/widget.ts(324,30): error TS2339: Property 'changedAttributes' does not exist on type 'WidgetModel'.
src/widget.ts(494,18): error TS2339: Property 'save' does not exist on type 'WidgetModel'.
src/widget.ts(508,14): error TS2339: Property 'on' does not exist on type 'WidgetModel'.
src/widget.ts(509,33): error TS2339: Property 'hasChanged' does not exist on type 'WidgetModel'.
src/widget.ts(598,15): error TS2554: Expected 0 arguments, but got 1.
src/widget.ts(605,14): error TS2339: Property 'listenTo' does not exist on type 'WidgetView'.
src/widget.ts(605,28): error TS2339: Property 'model' does not exist on type 'WidgetView'.
src/widget.ts(606,44): error TS2339: Property 'model' does not exist on type 'WidgetView'.
src/widget.ts(616,14): error TS2339: Property 'once' does not exist on type 'WidgetView'.
src/widget.ts(617,29): error TS2339: Property 'model' does not exist on type 'WidgetView'.
src/widget.ts(618,22): error TS2339: Property 'model' does not exist on type 'WidgetView'.
src/widget.ts(618,52): error TS2339: Property 'model' does not exist on type 'WidgetView'.
src/widget.ts(619,22): error TS2339: Property 'model' does not exist on type 'WidgetView'.
src/widget.ts(623,14): error TS2339: Property 'once' does not exist on type 'WidgetView'.
src/widget.ts(624,29): error TS2339: Property 'model' does not exist on type 'WidgetView'.
src/widget.ts(625,22): error TS2339: Property 'model' does not exist on type 'WidgetView'.
src/widget.ts(625,52): error TS2339: Property 'model' does not exist on type 'WidgetView'.
src/widget.ts(626,22): error TS2339: Property 'model' does not exist on type 'WidgetView'.
src/widget.ts(631,18): error TS2339: Property 'once' does not exist on type 'WidgetView'.
src/widget.ts(658,21): error TS2339: Property 'model' does not exist on type 'WidgetView'.
src/widget.ts(666,21): error TS2339: Property 'model' does not exist on type 'WidgetView'.
src/widget.ts(673,14): error TS2339: Property 'model' does not exist on type 'WidgetView'.
src/widget.ts(677,14): error TS2339: Property 'model' does not exist on type 'WidgetView'.
src/widget.ts(682,15): error TS2339: Property 'remove' does not exist on type 'NativeView<WidgetModel>'.
src/widget.ts(683,14): error TS2339: Property 'trigger' does not exist on type 'WidgetView'.
src/widget.ts(724,18): error TS2339: Property 'isDisposed' does not exist on type 'JupyterPhosphorWidget'.
src/widget.ts(774,18): error TS2339: Property 'isDisposed' does not exist on type 'JupyterPhosphorPanelWidget'.
src/widget.ts(795,14): error TS2339: Property 'listenTo' does not exist on type 'DOMWidgetView'.
src/widget.ts(795,28): error TS2339: Property 'model' does not exist on type 'DOMWidgetView'.
src/widget.ts(796,37): error TS2339: Property 'previous' does not exist on type 'WidgetModel'.
src/widget.ts(801,14): error TS2339: Property 'listenTo' does not exist on type 'DOMWidgetView'.
src/widget.ts(801,28): error TS2339: Property 'model' does not exist on type 'DOMWidgetView'.
src/widget.ts(802,41): error TS2339: Property 'previous' does not exist on type 'WidgetModel'.
src/widget.ts(806,14): error TS2339: Property 'listenTo' does not exist on type 'DOMWidgetView'.
src/widget.ts(806,28): error TS2339: Property 'model' does not exist on type 'DOMWidgetView'.
src/widget.ts(807,40): error TS2339: Property 'previous' does not exist on type 'WidgetModel'.
src/widget.ts(811,42): error TS2339: Property 'model' does not exist on type 'DOMWidgetView'.
src/widget.ts(812,33): error TS2339: Property 'model' does not exist on type 'DOMWidgetView'.
src/widget.ts(813,32): error TS2339: Property 'model' does not exist on type 'DOMWidgetView'.
src/widget.ts(817,14): error TS2339: Property 'listenTo' does not exist on type 'DOMWidgetView'.
src/widget.ts(817,28): error TS2339: Property 'model' does not exist on type 'DOMWidgetView'.
src/widget.ts(827,26): error TS2339: Property 'stopListening' does not exist on type 'DOMWidgetView'.
src/widget.ts(831,61): error TS7006: Parameter 'view' implicitly has an 'any' type.
src/widget.ts(835,30): error TS2339: Property 'listenTo' does not exist on type 'DOMWidgetView'.
src/widget.ts(853,26): error TS2339: Property 'stopListening' does not exist on type 'DOMWidgetView'.
src/widget.ts(857,60): error TS7006: Parameter 'view' implicitly has an 'any' type.
src/widget.ts(875,23): error TS2339: Property 'el' does not exist on type 'DOMWidgetView'.
src/widget.ts(918,24): error TS2339: Property 'model' does not exist on type 'DOMWidgetView'.
src/widget.ts(920,20): error TS2339: Property 'model' does not exist on type 'DOMWidgetView'.
src/widget.ts(923,66): error TS2339: Property 'el' does not exist on type 'DOMWidgetView'.
src/widget.ts(927,24): error TS2339: Property 'model' does not exist on type 'DOMWidgetView'.
src/widget.ts(929,57): error TS2339: Property 'el' does not exist on type 'DOMWidgetView'.
src/widget.ts(938,14): error TS2339: Property 'el' does not exist on type 'DOMWidgetView'.
src/widget.ts(956,18): error TS2339: Property 'trigger' does not exist on type 'DOMWidgetView'.
src/widget.ts(962,18): error TS2339: Property 'model' does not exist on type 'DOMWidgetView'.
src/widget_layout.ts(98,18): error TS2339: Property 'listenTo' does not exist on type 'LayoutView'.
src/widget_layout.ts(98,32): error TS2339: Property 'model' does not exist on type 'LayoutView'.
src/widget_layout.ts(103,51): error TS2339: Property 'model' does not exist on type 'LayoutView'.
src/widget_layout.ts(108,14): error TS2339: Property 'listenTo' does not exist on type 'LayoutView'.
src/widget_layout.ts(108,28): error TS2339: Property 'model' does not exist on type 'LayoutView'.
src/widget_layout.ts(113,39): error TS2339: Property 'model' does not exist on type 'LayoutView'.
src/widget_layout.ts(133,24): error TS2339: Property 'el' does not exist on type 'DOMWidgetView'.
src/widget_layout.ts(135,24): error TS2339: Property 'el' does not exist on type 'DOMWidgetView'.
src/widget_layout.ts(152,26): error TS2339: Property 'model' does not exist on type 'LayoutView'.
src/widget_layout.ts(153,28): error TS2339: Property 'el' does not exist on type 'DOMWidgetView'.
src/widget_layout.ts(156,24): error TS2339: Property 'el' does not exist on type 'DOMWidgetView'.
src/widget_layout.ts(170,24): error TS2339: Property 'el' does not exist on type 'DOMWidgetView'.
src/widget_style.ts(45,30): error TS2339: Property 'model' does not exist on type 'StyleView'.
src/widget_style.ts(62,14): error TS2339: Property 'listenTo' does not exist on type 'StyleView'.
src/widget_style.ts(62,28): error TS2339: Property 'model' does not exist on type 'StyleView'.
src/widget_style.ts(74,34): error TS2339: Property 'model' does not exist on type 'StyleView'.
src/widget_style.ts(78,46): error TS2339: Property 'el' does not exist on type 'DOMWidgetView'.
src/widget_style.ts(78,87): error TS2339: Property 'el' does not exist on type 'DOMWidgetView'.
src/widget_style.ts(98,43): error TS2339: Property 'model' does not exist on type 'StyleView'.
src/widget_style.ts(107,30): error TS2339: Property 'model' does not exist on type 'StyleView'.
src/widget_style.ts(113,50): error TS2339: Property 'el' does not exist on type 'DOMWidgetView'.
src/widget_style.ts(113,91): error TS2339: Property 'el' does not exist on type 'DOMWidgetView'.
```

**Comment by telamonian** [comment] 2019-06-25 23:24
@athornton You might need to run something like `npm install` first (feel free to ignore me if you already did).

@jasongrout I actually thought that lab already did that. If it doesn't, then I fully support the idea of ignoring bad plugins while also loudly warning the user.

**Comment by athornton** [comment] 2019-06-25 23:25
Update: well, I get a much smaller set of errors if I am just trying to build the jupyterlab-manager extension.

**Comment by vidartf** [comment] 2019-06-25 23:50
As far as I can tell, the issues with the ipywidgets lab extension is due to a bad release. In that/those releases, the dependencies on the lab packages unfortunately used a caret specifier for the alpha release. That means that when lab tries to find a compatible version of the widget manager, it finds that broken release (since a proper one has not been released yet). Ideally, I think we (ipywidgets) should deprecate those releases.

**Comment by vidartf** [comment] 2019-06-25 23:55
E.g. if I try to `jupyter install @jupyter-widgets/jupyterlab-manager` on a fresh install of RC.0, it finds 0.39.1, which is actually incompatible, but looks compatible from the dependencies semvers.

That said, I do think it might be appropriate for a lab install/update procedure to clean out old build artifacts before updating, if we do not already do this.

**Comment by jasongrout** [comment] 2019-06-26 09:29
> E.g. if I try to `jupyter install @jupyter-widgets/jupyterlab-manager` on a fresh install of RC.0, it finds 0.39.1, which is actually incompatible, but looks compatible from the dependencies semvers.

I can confirm this. This seems very weird - not sure why it is settling on something that is not compatible.

**Comment by jasongrout** [comment] 2019-06-26 09:39
It looks like 0.39.1 incorrectly used a caret in its dependency semver range (e.g., it has `^1.0.0-alpha.3`, when it should have had `1.0.0-alpha.3`). So it looks like jlab is functioning properly, it's the ipywidgets manager that has a problem (which was fixed in 0.40 and beyond).

**Comment by jasongrout** [comment] 2019-06-26 09:40
> As far as I can tell, the issues with the ipywidgets lab extension is due to a bad release. In that/those releases, the dependencies on the lab packages unfortunately used a caret specifier for the alpha release. That means that when lab tries to find a compatible version of the widget manager, it finds that broken release (since a proper one has not been released yet). Ideally, I think we (ipywidgets) should deprecate those releases.

Which is exactly what @vidartf already said. Yes, I think it makes sense to deprecate those releases.

**Comment by jasongrout** [comment] 2019-06-26 11:10
I deprecated those releases, but it turns out our script doesn't pay attention to deprecations. I'll submit a PR.

**Comment by vidartf** [comment] 2019-06-26 11:28
@jasongrout Thanks, having lab disregard deprecated versions when searching would be good (we should probably allow it if the users specifies a version though, e.g. `foo@1.0.1`).

**Comment by michaelaye** [comment] 2019-07-01 17:21
i have another edge case here:

Remote System (where jlab runs): Linux (CentOS 6.x)
Python: 3.7 via conda-forge
Client Browser: Safari 12.0.3 on macOS 10.14.3
Symptom: Notebook not opening in jlab (using `/tree` works fine).

Error in console:

<img width="502" alt="Screenshot 2019-07-01 11 14 39" src="https://user-images.githubusercontent.com/69774/60454894-4bf13280-9bf2-11e9-8b49-c3e71521ad8d.png">

**Comment by michaelaye** [comment] 2019-07-01 17:26
this was caused by some incompatible extensions i had (i use a lot of extensions). Uninstalling all extensions and rebuilding solved the not opening notebook issue.

**Comment by jasongrout** [comment] 2019-12-02 18:08
Closing as resolved. If there is still an issue here, please post a comment and we can reopen it. Thanks!

**Closed by jasongrout** 2019-12-02 18:08 UTC
