### ISSUE TITLE
Typing {} in a notebook on MacOSX 14 dos not work.

### ISSUE THREAD

**Issue by lusis-ai** [jupyterlab/jupyterlab#16002] opened 2024-03-15 10:44 UTC
## Description

In a JL notebook, when I try to type `{}`, the first character works `{` but the second one `}` cannot be entered.

**Config**

- MacOSX Sonoma
- JL : 4.1.4 and 4.1.5 (both tested)

## Reproduce

Try to type `{}`, the first character works `{` but the second one `}` cannot be entered.

## When it works

It works in JL 4.1.3

**Comment by krassowski** [comment] 2024-03-15 11:12
I believe this is a duplicate of the pinned issue https://github.com/jupyterlab/jupyterlab/issues/15744.

Please try the workaround in https://github.com/jupyterlab/jupyterlab/issues/15744#issuecomment-1999433752.

**Comment by JasonWeill** [comment] 2024-03-19 16:25
@lusis-ai To clarify, which keyboard layout are you using? #15744 is reproducible with several non-English-based keyboards.

**Comment by lusis-ai** [comment] 2024-03-19 16:46
@JasonWeill [French keyboard](https://www.apple.com/fr/shop/product/MQ052F/A/magic-keyboard-avec-pavé-numérique-français).

**Comment by JasonWeill** [comment] 2024-03-26 16:08
Closing as duplicate of #15744.

**Closed by JasonWeill** 2024-03-26 16:08 UTC
Labels: bug, status:Duplicate, status:Needs Info, status:Needs Triage
