### ISSUE TITLE
no quit and logout button for lab web page

### ISSUE THREAD

**Issue by zgqallen** [jupyterlab/jupyterlab#4859] opened 2018-07-10 05:47 UTC
I known we can have these two buttons by switching to classic mode, but this is very ease-to-use. Just wonder if the lab has the plan to enable these two buttons in the lab web page by default.

**Comment by ian-r-rose** [comment] 2018-07-10 14:52
Hi @zgqallen, as far as I can tell this is a duplicate of #4414. Can we continue the discussion there?

**Closed by ian-r-rose** 2018-07-10 14:52 UTC

**Comment by zgqallen** [comment] 2018-07-13 06:41
@ian-r-rose  Thanks for your response, i will check status of the #4414.
