### ISSUE TITLE
getting this error about `jupyter_lsp`

### ISSUE THREAD

**Issue by hemangjoshi37a** [jupyterlab/jupyterlab#16289] opened 2024-05-06 12:58 UTC
```sh
(myenv) (base) hemang@hemang-levono-15arr:~$ python3.12 -m jupyter lab
[W 2024-05-06 18:26:53.190 ServerApp] notebook_dir is deprecated, use root_dir
[I 2024-05-06 18:26:53.564 ServerApp] ipyparallel | extension was successfully linked.
[I 2024-05-06 18:26:53.564 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-05-06 18:26:53.568 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-05-06 18:26:53.573 ServerApp] jupyterlab | extension was successfully linked.
[W 2024-05-06 18:26:53.575 NotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-05-06 18:26:53.577 ServerApp] ServerApp.password config is deprecated in 2.0. Use PasswordIdentityProvider.hashed_password.
[I 2024-05-06 18:26:53.577 ServerApp] nbclassic | extension was successfully linked.
[W 2024-05-06 18:26:53.579 JupyterNotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2024-05-06 18:26:53.582 ServerApp] notebook | extension was successfully linked.
[I 2024-05-06 18:26:53.587 ServerApp] jupyter_nbextensions_configurator | extension was found and enabled by notebook_shim. Consider moving the extension to Jupyter Server's extension paths.
[I 2024-05-06 18:26:53.587 ServerApp] jupyter_nbextensions_configurator | extension was successfully linked.
[WARNING 2024-05-06 18:26:53.588 traitlets]: A `_jupyter_server_extension_points` function was not found in jupyter_tabnine. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-05-06 18:26:53.588 ServerApp] jupyter_tabnine | extension was found and enabled by notebook_shim. Consider moving the extension to Jupyter Server's extension paths.
[I 2024-05-06 18:26:53.588 ServerApp] jupyter_tabnine | extension was successfully linked.
[I 2024-05-06 18:26:53.588 ServerApp] ipyparallel.nbextension | extension was found and enabled by notebook_shim. Consider moving the extension to Jupyter Server's extension paths.
[I 2024-05-06 18:26:53.589 ServerApp] ipyparallel.nbextension | extension was successfully linked.
[I 2024-05-06 18:26:53.589 ServerApp] notebook_shim | extension was successfully linked.
[W 2024-05-06 18:26:53.606 ServerApp] WARNING: The Jupyter server is listening on all IP addresses and not using encryption. This is not recommended.
[I 2024-05-06 18:26:53.606 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-05-06 18:26:53.607 ServerApp] Loading IPython parallel extension
[I 2024-05-06 18:26:53.607 ServerApp] ipyparallel | extension was successfully loaded.
[I 2024-05-06 18:26:53.607 ServerApp] Loading IPython parallel extension
[I 2024-05-06 18:26:53.608 ServerApp] ipyparallel.nbextension | extension was successfully loaded.
[W 2024-05-06 18:26:53.610 ServerApp] jupyter_lsp | extension failed loading with message: TraitError("schema errors:\n\t1 is not one of [2]\nfor:\n{'a-language-server-implementation': {'version': 1, 'argv': ['/absolute/path/to/a-language-server', '--stdio'], 'languages': ['a-language']}}")
    Traceback (most recent call last):
      File "/home/hemang/myenv/lib/python3.12/site-packages/jupyter_server/extension/manager.py", line 360, in load_extension
        extension.load_all_points(self.serverapp)
      File "/home/hemang/myenv/lib/python3.12/site-packages/jupyter_server/extension/manager.py", line 232, in load_all_points
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hemang/myenv/lib/python3.12/site-packages/jupyter_server/extension/manager.py", line 223, in load_point
        return point.load(serverapp)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/hemang/myenv/lib/python3.12/site-packages/jupyter_server/extension/manager.py", line 151, in load
        return loader(serverapp)
               ^^^^^^^^^^^^^^^^^
      File "/home/hemang/myenv/lib/python3.12/site-packages/jupyter_lsp/serverextension.py", line 54, in load_jupyter_server_extension
        manager = nbapp.language_server_manager = LanguageServerManager(parent=nbapp)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hemang/myenv/lib/python3.12/site-packages/jupyter_lsp/manager.py", line 127, in __init__
        super().__init__(**kwargs)
      File "/home/hemang/myenv/lib/python3.12/site-packages/traitlets/config/configurable.py", line 116, in __init__
        self.config = config
        ^^^^^^^^^^^
      File "/home/hemang/myenv/lib/python3.12/site-packages/traitlets/traitlets.py", line 716, in __set__
        self.set(obj, value)
      File "/home/hemang/myenv/lib/python3.12/site-packages/traitlets/traitlets.py", line 706, in set
        obj._notify_trait(self.name, old_value, new_value)
      File "/home/hemang/myenv/lib/python3.12/site-packages/traitlets/traitlets.py", line 1513, in _notify_trait
        self.notify_change(
      File "/home/hemang/myenv/lib/python3.12/site-packages/traitlets/traitlets.py", line 1525, in notify_change
        return self._notify_observers(change)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hemang/myenv/lib/python3.12/site-packages/traitlets/traitlets.py", line 1568, in _notify_observers
        c(event)
      File "/home/hemang/myenv/lib/python3.12/site-packages/traitlets/traitlets.py", line 1143, in compatible_observer
        return func(self, change)
               ^^^^^^^^^^^^^^^^^^
      File "/home/hemang/myenv/lib/python3.12/site-packages/traitlets/config/configurable.py", line 232, in _config_changed
        self._load_config(change.new, traits=traits, section_names=section_names)
      File "/home/hemang/myenv/lib/python3.12/site-packages/traitlets/config/configurable.py", line 193, in _load_config
        setattr(self, name, deepcopy(config_value))
      File "/home/hemang/myenv/lib/python3.12/site-packages/traitlets/traitlets.py", line 716, in __set__
        self.set(obj, value)
      File "/home/hemang/myenv/lib/python3.12/site-packages/traitlets/traitlets.py", line 690, in set
        new_value = self._validate(obj, value)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hemang/myenv/lib/python3.12/site-packages/traitlets/traitlets.py", line 722, in _validate
        value = self.validate(obj, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/hemang/myenv/lib/python3.12/site-packages/jupyter_lsp/trait_types.py", line 16, in validate
        raise traitlets.TraitError(
    traitlets.traitlets.TraitError: schema errors:
        1 is not one of [2]
    for:
    {'a-language-server-implementation': {'version': 1, 'argv': ['/absolute/path/to/a-language-server', '--stdio'], 'languages': ['a-language']}}
[I 2024-05-06 18:26:53.612 ServerApp] [jupyter_nbextensions_configurator] enabled 0.6.3
[I 2024-05-06 18:26:53.612 ServerApp] jupyter_nbextensions_configurator | extension was successfully loaded.
[I 2024-05-06 18:26:53.613 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[INFO 2024-05-06 18:26:53.613 Tabnine]:  install dir: /home/hemang/myenv/lib/python3.12/site-packages/jupyter_tabnine
[INFO 2024-05-06 18:26:53.613 Tabnine]: Tabnine binary already exists in /home/hemang/myenv/lib/python3.12/site-packages/jupyter_tabnine/binaries/4.159.0/x86_64-unknown-linux-musl/TabNine ignore downloading
[INFO 2024-05-06 18:26:55.623 Tabnine]:  Semantic completion enabled.
[I 2024-05-06 18:26:55.623 ServerApp] jupyter_tabnine | extension was successfully loaded.
[I 2024-05-06 18:26:55.629 LabApp] JupyterLab extension loaded from /home/hemang/myenv/lib/python3.12/site-packages/jupyterlab
[I 2024-05-06 18:26:55.629 LabApp] JupyterLab application directory is /home/hemang/myenv/share/jupyter/lab
[I 2024-05-06 18:26:55.630 LabApp] Extension Manager is 'pypi'.
[I 2024-05-06 18:26:55.692 ServerApp] jupyterlab | extension was successfully loaded.

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|
                                                                           
Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[I 2024-05-06 18:26:55.702 ServerApp] nbclassic | extension was successfully loaded.
[I 2024-05-06 18:26:55.709 ServerApp] notebook | extension was successfully loaded.
[I 2024-05-06 18:26:55.710 ServerApp] Serving notebooks from local directory: /home/hemang
[I 2024-05-06 18:26:55.711 ServerApp] Jupyter Server 2.14.0 is running at:
[I 2024-05-06 18:26:55.711 ServerApp] http://localhost:9999/lab
[I 2024-05-06 18:26:55.711 ServerApp]     http://127.0.0.1:9999/lab
[I 2024-05-06 18:26:55.712 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

**Comment by krassowski** [comment] 2024-05-06 13:23
Duplicate of https://github.com/jupyter-lsp/jupyterlab-lsp/issues/1082

**Comment by JasonWeill** [comment] 2024-05-07 16:35
Closing as duplicate of https://github.com/jupyter-lsp/jupyterlab-lsp/issues/1082.

**Closed by JasonWeill** 2024-05-07 16:35 UTC
Labels: bug, status:Duplicate, status:Needs Triage
