### ISSUE TITLE
Codemirror error in extension when upgrade JupyterLab from 1.0.1 to 1.0.10

### ISSUE THREAD

**Issue by fggrimmer** [jupyterlab/jupyterlab#7161] opened 2019-09-06 22:08 UTC
## Description

After upgrading JupyterLab from 1.0.1 to 1.0.10 (using 'conda install -c conda-forge jupyterlab=1.0.10'), our extension which uses codemirror to highlight sql words, stopped working. It was built with "@jupyterlab/codemirror": "^1.0.1" (package.json).

We see the following error in the Chrome >Developer Tools>Console
_TypeError: Cannot read property 'push' of undefined_

Below is the code:
`CodeMirror.modeInfo.push({
            ext: ['sql', 'tdrs'],
            mime: 'text/x-testsql',
            mode: 'testsql',
            name: 'Test SQL'
        });`

package.json:
` "dependencies": {
    "@jupyterlab/application": "^1.0.1",
    "@jupyterlab/codemirror": "^1.0.1",
    "codemirror": "^5.47.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "tslint": "^5.18.0"
  },`

## Expected behavior
  Words to be colored.

- Operating System and version: macOSx 10.13.6
- Browser and version: Chrome Version 76.0.3809.132
- JupyterLab version: 1.0.10

<details><summary>Browser Output</summary>
<pre>
_TypeError: Cannot read property 'push' of undefined_

</pre>
</details>

**Comment by ian-r-rose** [comment] 2019-09-06 22:11
Thanks for the report @fggrimmer. Is your extension available somewhere to see if I can reproduce?

**Comment by jasongrout** [comment] 2020-02-05 22:16
Closing since the author did not follow up. Please comment here if you'd like to continue the discussion.

**Closed by jasongrout** 2020-02-05 22:16 UTC
Labels: status:Needs Info
