### ISSUE TITLE
Find/replace on a single cell

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#8937] opened 2020-08-31 14:59 UTC
### Problem

Today, Jupyter has find/replace globally and only find on a single cell. Sometimes you want to replace just within the cell you are editing quickly.

### Proposed Solution

The find search-bar on a cell should be enhanced to include a replace option.

**Comment by jasongrout** [comment] 2021-03-17 16:35
This is a duplicate of #2017 - let's continue discussion over there.

**Closed by jasongrout** 2021-03-17 16:35 UTC
Labels: type:Enhancement
