### ISSUE TITLE
nable to load the right kernel

### ISSUE THREAD

**Issue by vlavorini** [jupyterlab/jupyterlab#9612] opened 2021-01-13 14:05 UTC
## Description

I've installed Jupyter Lab 3.0.in a miniconda virtual env, and I am trying to use a kernel with the local Python2.7.

The kernel actually appears in the list of the available kernels in jupyter  (upper right corner). The file where that kernel is defined describe the correct python version to use: 

    {
      "display_name": "Python 2.7.12 64-bit",
      "language": "python",
      "argv": [
        "/usr/bin/python",
        "-m",
        "ipykernel_launcher",
        "-f",
        "{connection_file}"
      ],
      "env": {},
      "metadata": {
        "interpreter": {
          "architecture": 3,
          "path": "/usr/bin/python",
          "version": {
            "options": {
              "loose": false,
              "includePrerelease": false
            },
            "loose": false,
            "raw": "2.7.12-final",
            "major": 2,
            "minor": 7,
            "patch": 12,
            "prerelease": [
              "final"
            ],
            "build": [],
            "version": "2.7.12-final"
          },
        "sysVersion": "2.7.12 (default, Oct  5 2020, 13:56:01) \n[GCC 5.4.0 20160609]",
          "sysPrefix": "/usr",
          "fileHash": "4e0e76d033654b01a59506c4579ae7f6b29cdce5215aba88aae73801497ea74cf992e2b2510014756356e46cde9843707272a614a556e6ae42b5f1fd35fb1f53",
          "envType": "Unknown",
          "displayName": "Python 2.7.12 64-bit"
        }
      }
    }

But when I select it, even if all seems to go right and the correct kernel name is shown in the upper right corner, the python version (and the available packages) is still the one of the miniconda environment:
    
    # in a jupyer cell
    !which python

    # cell output:
    /home/vincenzo/miniconda3/envs/py39/bin/python

I tried to run with the --debug option, and here still it seems that it loads the correct kernel, as you can spot in the following log.

    [D 2021-01-13 13:51:58.799 ServerApp] Received kernel info: {'status': 'ok', 'language_info': {'mimetype': 'text/x-python', 
    'nbconvert_exporter': 'python', 'name': 'python', 'pygments_lexer': 'ipython2', 'version': '2.7.12', 'file_extension': '.py', 
    'codemirror_mode': {'version': 2, 'name': 'ipython'}}, 'implementation_version': '5.7.0', 'implementation': 'ipython', 
    'protocol_version': '5.1', 'banner': 'Python 2.7.12 (default, Oct  5 2020, 13:56:01) \nType "copyright", "credits" or "license" for 
    more information.\n\nIPython 5.7.0 -- An enhanced Interactive Python.\n?         -> Introduction and overview of IPython\'s 
    features.\n%quickref -> Quick reference.\nhelp      -> Python\'s own help system.\nobject?   -> Details about \'object\', use 
    \'object??\' for extra details.\n', 'help_links': [{'url': 'https://docs.python.org/2.7', 'text': 'Python Reference'}, {'url': 
    'https://ipython.org/documentation.html', 'text': 'IPython Reference'}, {'url': 'https://docs.scipy.org/doc/numpy/reference/', 'text': 
    'NumPy Reference'}, {'url': 'https://docs.scipy.org/doc/scipy/reference/', 'text': 'SciPy Reference'}, {'url': 'https://matplotlib.org
    /contents.html', 'text': 'Matplotlib Reference'}, {'url': 'http://docs.sympy.org/latest/index.html', 'text': 'SymPy Reference'}, {'url': 
    'https://pandas.pydata.org/pandas-docs/stable/', 'text': 'pandas Reference'}]}

What am I missing?

## Context

- Operating System and version: Ubuntu 16.04
- JupyterLab version: 3.0 (but the same issue with 2.x)

**Comment by jasongrout** [comment] 2021-01-13 21:26
Closing because duplicate of #9614

**Closed by jasongrout** 2021-01-13 21:26 UTC
