### ISSUE TITLE
The default setting of Jupyterlab should show warning always.

### ISSUE THREAD

**Issue by hyperkai** [jupyterlab/jupyterlab#16825] opened 2024-10-02 17:48 UTC
Jupyterlab shows warning once by default as shown below:

```python
import torch
from torch import nn

tensor1 = torch.tensor([[8., -3., 0., 1.]])
tensor2 = torch.tensor([[5., 9., -4., 8.],
                        [-2., 7., 3., 6.]])
torch.manual_seed(42)

tran = nn.Transformer(d_model=4, nhead=2) # Warning
```

> UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")

But the default setting of showing warning once is problematic because some people including me will think warning is solved.

So, I suggest that the default setting should show warning always.

**Comment by JasonWeill** [comment] 2024-10-08 16:17
@hyperkai Thank you for opening this issue! I see the same behavior if I run Python 3.12.2 on the command line, run your code block, then run the last line again. This might be a bug in the PyTorch library. Are you able to reproduce this bug in JupyterLab with other code that, in Python, produces a warning on every run?

**Comment by JasonWeill** [comment] 2024-10-15 16:05
@hyperkai Please open an issue against the PyTorch library here, to request warnings on every call: https://github.com/pytorch/pytorch/issues

Closing this issue, because it is not an issue in JupyterLab. Thank you for your contribution.

**Closed by JasonWeill** 2024-10-15 16:05 UTC
Labels: enhancement, status:Needs Info, status:Needs Triage

**Comment by hyperkai** [comment] 2024-10-22 05:53
Just a short time ago, I reported it to [PyTorch](https://github.com/pytorch/pytorch/issues/138552). Thanks.
