### ISSUE TITLE
Domain and User relative non-files paths

### ISSUE THREAD

**Issue by consideRatio** [jupyterlab/jupyterlab#5211] opened 2018-08-25 14:51 UTC
## UPDATE: Actionplan
@blink1073 summarized desired behavior in [this comment](https://github.com/jupyterlab/jupyterlab/issues/5211#issuecomment-416583273) and that related code could be found in [packages/rendermime/src/renderers.ts's handleAttr() function](https://github.com/jupyterlab/jupyterlab/blob/d908577e59fc6ba624138fb9119068b158186252/packages/rendermime/src/renderers.ts#L701).

Perhaps we can tag this as a "Good first issue" @blink1073 ?

**Suggested goals:**
- Goal 1: make markdown point to the desired URLs
- Goal 2: pass all existing tests
- Goal 3: add a test to verify handleAttr's behavior in the future

---

## Problem
nbGitPuller can pull and download files if invoked by accessing the following type of URL:

```
https://mydomain.com/user/erik/git-pull?someQueryParamsHere
```

I want an index-notebook to contain links to utilize nbGitPuller to download various content. But currently, while I can create a link like above. I have hardcoded the domain and assumed usage of a jupyterhub as I'm referencing a specific user - **not good**!

So, if I write something more relative like the following:
```markdown
[a nbgitpuller triggering link](/git-pull?someQueryParamsHere)
```
I will be pointed to:
```
https://jupyter.se/user/erik/files/git-pull?someQueryParamsHere
```
And since **/files** are appended, I will not be able to utilize `git-pull`! So currently I'm forced to hardcode everything (!) or fail, as far as I understand.

## Question
What is needed to be done to allow a markdown link remain relative to domain and user, but not getting `/files` prefixed?

/cc: @adobs

**Comment by blink1073** [comment] 2018-08-27 11:16
Hi @consideRatio, it was great to meet you last week!  That logic is defined [here](https://github.com/jupyterlab/jupyterlab/blob/d908577e59fc6ba624138fb9119068b158186252/packages/rendermime/src/renderers.ts#L701).  The problem is that we are interpreting urls with a leading slash as local.  I verified that that classic notebook explicitly requires a leading `./` to use the `/files` endpoint.

**Comment by consideRatio** [comment] 2018-08-27 19:02
@blink1073 great to meet you as well :D

So `/X` in the address should refer to `/X` while `./X` should refer to `/files/X` and `X` should refer to `/files/some-working-dir/X`. Did I get it right?

**Comment by blink1073** [comment] 2018-08-28 09:18
A summary:

`./foo/bar` -> `/files/<current_path>/foo/bar`
`foo/bar` -> `files/<current_path>/foo/bar`
Anything else -> Unchanged

**Comment by jasongrout** [comment] 2018-08-28 11:52
That second line isn't `/files/...`?

**Comment by jasongrout** [comment] 2018-08-28 11:54
Where `/files` really means prepend whatever baseurl there is too, right?

**Comment by consideRatio** [comment] 2018-08-28 11:59
> Anything else -> Unchanged

Does this mean that `/X` should point to the full URL being `/X` or that the full URL should be `mydomain.com/user/erik/X` (on a jupyterhub) or `localhost:8888/X` (running locally without a hub).

**Comment by blink1073** [comment] 2018-08-28 13:26
Ah, good point.  Full behavior:

`./foo/bar` -> <prefix>/files/<current_path>/foo/bar`
`foo/bar` -> <prefix>/files/<current_pat>/foo/bar`
`/foo/bar` -> <prefix>/foo/bar`
`<protocol>://foo/bar` -> Unchanged

**Comment by blink1073** [comment] 2018-08-28 13:27
Also `//foo/bar` -> Unchanged

**Comment by consideRatio** [comment] 2018-08-28 17:08
@blink1073 thanks awesome! I documented the original post at the top, and suggested to tag this a `Good first issue`, it seems quite limited in scope and it is quite well documented on how to proceed. Feel free to update the post I made if the "suggested goals" were not suitable.

**Comment by blink1073** [comment] 2018-08-29 09:00
Nice summary, thanks again @consideRatio!

**Comment by apsknight** [comment] 2018-09-03 21:28
Hey @blink1073,

I'd like to work on this issue.

**Comment by consideRatio** [comment] 2018-09-03 21:30
@apsknight awesome! :D I for one would love to see this resolved!

**Comment by blink1073** [comment] 2018-09-04 08:48
Yes, please do, @apsknight!

**Comment by Ark-kun** [comment] 2018-11-08 05:30
This issue is really important for us.

We run JupyterHub and doing port forwarding, so the URL prefix can be different for different users.

We start some jobs and output links to those jobs. The links start with slash and point to another route of our server.

In Jupyter Notebook the links work fine, but in JupyterLab they're broken, because "/user/xxx/files/" is inserted before the URL.

**Comment by yebrahim** [comment] 2018-11-20 21:35
@blink1073, can you clarify what "prefix" is in your comment? Is this origin or origin + pathname?

Also, is the behavior here intentionally different from Jupyterhub? Why not copy that logic?

**Comment by Ark-kun** [comment] 2018-11-20 21:36
> Ah, good point. Full behavior:
> 
> `./foo/bar` -> `<prefix>/files/<current_path>/foo/bar`
> `foo/bar` -> `<prefix>/files/<current_pat>/foo/bar`
> `/foo/bar` -> `<prefix>/foo/bar`
> `<protocol>://foo/bar` -> Unchanged

Can you clarify what the `<prefix>` is? Is it `<protocol>://<domain>:<port>` ?

What about JupyterHub? We need to be able to create root-based links in JupyterHub instances. If I do `<a href="/something">` I want it to remain that way.

**Comment by Ark-kun** [comment] 2018-11-20 21:38
> Also, is the behavior here intentionally different from Jupyterhub? Why not copy that logic?

+1 Juputer Notebook (even working as JupyterHub instance) treats the links correctly as per the HTML specification.

**Comment by consideRatio** [comment] 2018-11-21 11:02
@yebrahim @ark-kun the prefix was referring to for example:

https://jupyter.se/user/erik
http://localhost:8000

---

To reference the url of a jupyterhubs root address from jupyterlab is probably out of scope for jupyterlab to address. I wonder if there are environment variables available for to build the URL with though? If not, you can let the hub provide an environment variable with info about the current root address perhaps?

```
# is the jupyterhub domain url available already from an env variable?
import os
os.environ

#if so, perhaps you could programmatically build up the url, this would be a bit more ugly, but it is probably too much to ask of jupyterlab to be jupyterhub aware
```

**Comment by saulshanabrook** [comment] 2019-01-26 02:15
Let's say you are running on  `https://jupyter.se/user/erik/` so your URL when loading the page is `https://jupyter.se/user/erik/lab`. Then you have a link to `/git-pull` in a markdown cell. This could point to either:

(a) `https://jupyter.se/git-pull`: don't change with the URL. Have it be an absolute URL from the domain.
(b) `https://jupyter.se/user/erik/git-pull`: Prepend the prefix to the URL. Have it relative to your Jupyter server

https://github.com/jupyterlab/jupyterlab/pull/5814 implements (a).

From what I understand, this *does not* cover the use case of @consideRatio but *does* cover the use case of @Ark-kun.

In the case that there is no prefix, both use cases are the same.

@jasongrout and I couldn't think of a way to infer between the different user intent based on markdown source.

Our preference is to merge the current PR to at least get some of the desired use cases working, because it treats absolute links as they would be treated in standard HTML.

**Comment by afshin** [comment] 2019-02-28 16:58
Since this issue is partly resolved, let's close it. If it needs further discussion, we can re-open it.

**Closed by afshin** 2019-02-28 16:58 UTC
Labels: pkg:rendermime, tag:Feature Parity, type:Bug

**Comment by consideRatio** [comment] 2019-02-28 21:33
@saulshanabrook ah! it kinda does thpugh i think, because i can always write:

/hub/user-redirect/git-pull?

Then JH will redirect me to the relevant user-server which could be /user/erik or /user/cat etc
